/**
 * The card library. Approximately 100 policy cards spanning four eras.
 * Each card represents a real lever a Chicago alderman, planner, or
 * organizer could pull. Costs are paid in capital, power, trust, and
 * knowledge. Effects move the four hidden scores and transform parcels.
 *
 * Cards are tagged with era windows so the deck rotates as years pass:
 * the 1940 deck has very different options than the 2020 deck.
 *
 * Lore notes carry the educational content. They cite real sources.
 * The game does not lecture, but a player who hovers a card sees the
 * one-paragraph history behind it.
 */

import type { Card } from "./types";

export const CARDS: Card[] = [
  /* ============================================================== *
   *  ZONING                                                         *
   * ============================================================== */
  {
    id: "downzone-northern-blocks",
    name: "Single-family overlay",
    flavor: "Property owners' association politely insistent.",
    description: "Lock the northern blocks to single-family only. Raises value, prevents density, signals exclusion.",
    lore: "Through the 1950s and 60s, white aldermen used single-family zoning to do what racial covenants no longer legally could. The overlay raised property values short term and prevented the construction of two-flats and small apartment buildings that working-class families could afford.",
    source: "Rothstein, The Color of Law (2017), ch. 3",
    category: "zoning",
    rarity: "common",
    cost: { power: 1, capital: 2 },
    fromYear: 1940,
    toYear: 1980,
    effect: {
      growth: -1,
      equity: -2,
      heritage: 1,
      transformParcels: [
        { selector: "block:0", delta: { value: 8 } },
        { selector: "block:1", delta: { value: 6 } },
      ],
    },
    glossary: ["Covenants"],
  },
  {
    id: "upzone-transit",
    name: "Upzone the transit corridor",
    flavor: "More homes near the train, by right.",
    description: "Allow three-flats and courtyards near transit. Adds units, intensifies pressure on existing buildings.",
    lore: "Transit-oriented development upzoning has been a major Chicago debate since 2015. Supporters note that allowing more homes near trains reduces sprawl and lowers per-household carbon. Critics note that without affordability requirements, the new units rent at market rate and accelerate displacement.",
    source: "Chicago TOD Reform 2015, 2019, 2021 amendments",
    category: "zoning",
    rarity: "common",
    cost: { power: 2 },
    fromYear: 1990,
    toYear: 2040,
    effect: {
      growth: 3,
      sustainability: 2,
      equity: -1,
      transformParcels: [
        { selector: "adjacent-to:transit", delta: { value: 10 } },
      ],
    },
    glossary: ["Gentrification"],
  },
  {
    id: "legalize-adu",
    name: "Legalize ADUs citywide",
    flavor: "Coach houses and basement apartments, again.",
    description: "Allow accessory dwelling units on every lot. Modest gain in housing supply.",
    lore: "Chicago banned new accessory dwelling units in 1957 as part of a wave of postwar zoning crackdowns. The 2021 pilot reintroduced them in five zones. Citywide legalization is scheduled for April 1, 2026.",
    source: "City of Chicago ADU pilot program reports",
    category: "zoning",
    rarity: "uncommon",
    cost: { power: 2, knowledge: 1 },
    fromYear: 2020,
    toYear: 2040,
    effect: {
      growth: 2,
      sustainability: 1,
      equity: 1,
      transformParcels: [
        { selector: "type:single-family", delta: { residents: 1 } },
      ],
    },
    glossary: ["ADU"],
  },
  {
    id: "form-based-code",
    name: "Form-based code",
    flavor: "Regulate the building shape, not the use.",
    description: "Replace use-based zoning with form-based code in the central blocks. Encourages mixed use.",
    lore: "Form-based codes regulate the physical form of buildings (height, setback, frontage) rather than what happens inside them. They allow mixed use by default, which can revive walkable commercial streets. Pioneered by Andrés Duany in Seaside, Florida.",
    source: "Form-Based Codes Institute reference materials",
    category: "zoning",
    rarity: "rare",
    cost: { knowledge: 2, power: 2, capital: 3 },
    fromYear: 2000,
    toYear: 2040,
    effect: {
      growth: 2,
      sustainability: 3,
      heritage: 1,
      transformParcels: [
        { selector: "block:2", delta: { value: 6 } },
      ],
    },
  },
  {
    id: "preservation-overlay",
    name: "Historic preservation overlay",
    flavor: "Plaques, restrictions, slow demolition.",
    description: "Block demolition in the central blocks. Protects what exists, slows new construction.",
    lore: "Chicago landmark designations require Commission on Chicago Landmarks approval before any demolition or major exterior alteration. The system saved the Reliance Building. It also gets criticized for protecting buildings while displacing people.",
    source: "Chicago Landmarks Ordinance",
    category: "preservation",
    rarity: "uncommon",
    cost: { power: 2, knowledge: 1 },
    fromYear: 1970,
    toYear: 2040,
    effect: {
      heritage: 4,
      growth: -2,
      transformParcels: [
        { selector: "block:2", set: { protected: true } },
      ],
    },
  },
  {
    id: "demolition-moratorium",
    name: "Demolition moratorium",
    flavor: "Nothing comes down for two years.",
    description: "Pause all demolitions in the ward. Stops displacement, freezes the housing stock.",
    lore: "The 1980s anti-demolition ordinances in Cleveland and Pittsburgh demonstrated that municipal moratoriums could stop blockbusting in real time. Chicago has used short demolition holds during landmark review.",
    source: "Pittsburgh Demolition Ordinance, 1985",
    category: "preservation",
    rarity: "uncommon",
    cost: { power: 3, trust: 1 },
    fromYear: 1980,
    toYear: 2040,
    effect: {
      heritage: 3,
      equity: 2,
      growth: -2,
    },
  },

  /* ============================================================== *
   *  HOUSING                                                        *
   * ============================================================== */
  {
    id: "build-cha-tower",
    name: "Build a CHA tower",
    flavor: "16 stories, 200 units, federal money.",
    description: "Add a public-housing tower in the south blocks. Cheap, dense, and historically catastrophic.",
    lore: "The CHA built towers because Congress would only fund concentrated public housing on cheap land, and white aldermen blocked siting in their wards. By the 1990s most of the towers were uninhabitable. The Plan for Transformation demolished them starting in 1999.",
    source: "Hunt, Blueprint for Disaster (2009)",
    category: "housing",
    rarity: "common",
    cost: { capital: 3, power: 2 },
    fromYear: 1948,
    toYear: 1980,
    effect: {
      growth: 2,
      equity: 1,
      heritage: -2,
      sustainability: -2,
      transformParcels: [
        { selector: "first-vacant:south", set: { type: "tower", residents: 200, owner: "cha" } },
      ],
    },
    glossary: ["CHA"],
  },
  {
    id: "scattered-site",
    name: "Scattered-site low-rise",
    flavor: "Smaller buildings, mixed across the ward.",
    description: "Build 30 units across 10 sites. Costs more, integrates better.",
    lore: "Scattered-site public housing was the remedy ordered in Hills v. Gautreaux (1976). The CHA fought it for years; lawsuits to enforce it ran through the 2000s.",
    source: "Hills v. Gautreaux, 425 U.S. 284 (1976)",
    category: "housing",
    rarity: "uncommon",
    cost: { capital: 4, power: 3 },
    fromYear: 1970,
    toYear: 2040,
    effect: {
      equity: 4,
      heritage: 2,
      growth: 1,
      transformParcels: [
        { selector: "random:10", set: { type: "courtyard", residents: 12 } },
      ],
    },
    glossary: ["Gautreaux"],
  },
  {
    id: "mixed-income",
    name: "Mixed-income redevelopment",
    flavor: "One-third public, one-third affordable, one-third market.",
    description: "Demolish a tower, build mixed-income. Cuts concentrated poverty, displaces existing residents.",
    lore: "The Plan for Transformation promised one-for-one replacement of public housing units. The actual rate ran around 60 percent. Tens of thousands of CHA residents were displaced and many never returned.",
    source: "Chaskin and Joseph, Integrating the Inner City (2015)",
    category: "housing",
    rarity: "rare",
    cost: { capital: 5, power: 3 },
    fromYear: 1995,
    toYear: 2040,
    requiresFlag: "tower-built",
    effect: {
      equity: 1,
      heritage: -3,
      growth: 3,
      transformParcels: [
        { selector: "type:tower", set: { type: "courtyard", residents: 80 } },
      ],
    },
    glossary: ["PlanForTransformation"],
  },
  {
    id: "rehab-in-place",
    name: "Rehab in place",
    flavor: "$90M federal grant. The towers stay.",
    description: "Major elevator and plumbing rehab. No displacement, ongoing maintenance burden.",
    lore: "HOPE VI funding could be used for rehab as well as demolition. Chicago chose demolition for almost every major site. Boston's Mission Main and Newark's Stella Wright were notable rehab successes.",
    source: "HUD HOPE VI Cost Comparisons (2008)",
    category: "housing",
    rarity: "uncommon",
    cost: { capital: 4 },
    fromYear: 1995,
    toYear: 2030,
    requiresFlag: "tower-built",
    effect: {
      heritage: 4,
      equity: 3,
      transformParcels: [
        { selector: "type:tower", set: { type: "rehab-tower", condition: 75 } },
      ],
    },
  },
  {
    id: "section-8-vouchers",
    name: "Expand Section 8 vouchers",
    flavor: "Tenants pay 30% of income, vouchers cover the rest.",
    description: "Issue 200 new vouchers. Helps families afford rent. Landlords often refuse them.",
    lore: "The Housing Choice Voucher program was created by the 1974 Housing Act and expanded under Reagan. Voucher holders face widespread discrimination from landlords. Chicago passed source-of-income protection in 1990, but enforcement is uneven.",
    source: "HUD Housing Choice Voucher administrative guidelines",
    category: "housing",
    rarity: "common",
    cost: { capital: 3, power: 1 },
    fromYear: 1975,
    toYear: 2040,
    effect: { equity: 3, growth: 1 },
    glossary: ["Section8"],
  },
  {
    id: "right-to-counsel",
    name: "Right to counsel for tenants",
    flavor: "Every tenant gets a lawyer in eviction court.",
    description: "Pay for legal representation for tenants facing eviction. Cuts evictions sharply.",
    lore: "New York City passed the first universal right to counsel for housing court in 2017. Eviction filings fell roughly 40 percent within five years. Chicago has had pilot programs but no citywide right.",
    source: "NYC Office of Civil Justice Annual Reports",
    category: "organizing",
    rarity: "uncommon",
    cost: { capital: 3, trust: 1 },
    fromYear: 2010,
    toYear: 2040,
    effect: { equity: 4, heritage: 2 },
  },
  {
    id: "anti-flipping-tax",
    name: "Anti-flipping tax",
    flavor: "Sell a property within 2 years and pay a steep transfer tax.",
    description: "Discourages speculative flipping. Slows price appreciation.",
    lore: "Various jurisdictions have used short-term sale taxes to dampen speculation. San Francisco voters considered a measure in 2014; it failed but inspired similar proposals nationally.",
    source: "Lincoln Institute of Land Policy speculation studies",
    category: "finance",
    rarity: "uncommon",
    cost: { power: 3 },
    fromYear: 1990,
    toYear: 2040,
    effect: { equity: 2, growth: -1, heritage: 2 },
  },
  {
    id: "land-trust-acquisition",
    name: "Community land trust acquisition",
    flavor: "Take five parcels off the speculative market forever.",
    description: "Purchase land into a permanent community trust. Locks affordability for the duration of the lease.",
    lore: "The Burlington Community Land Trust in Vermont, founded 1984, holds about 565 homes and 2,200 rental units. Resale formulas keep prices appreciating slowly enough that the units remain affordable across generations.",
    source: "Lincoln Institute CLT outcomes (2018)",
    category: "housing",
    rarity: "rare",
    cost: { capital: 5, trust: 2, knowledge: 1 },
    fromYear: 2000,
    toYear: 2040,
    effect: {
      equity: 5,
      heritage: 3,
      transformParcels: [
        { selector: "random:5", set: { type: "land-trust", owner: "land-trust", protected: true } },
      ],
    },
    glossary: ["CommunityLandTrust"],
  },
  {
    id: "tenant-opportunity-purchase",
    name: "Tenant opportunity to purchase",
    flavor: "Tenants get first right of refusal when their building goes up for sale.",
    description: "Slows speculative resale. Tenants can pool to buy as a co-op.",
    lore: "Washington, D.C.'s Tenant Opportunity to Purchase Act (TOPA) dates to 1980 and has produced thousands of co-op conversions. Chicago has discussed TOPA repeatedly without passing one.",
    source: "DC TOPA program data; Chicago TOPA proposals 2018-2024",
    category: "organizing",
    rarity: "rare",
    cost: { power: 3, trust: 2 },
    fromYear: 1985,
    toYear: 2040,
    effect: { equity: 3, heritage: 4 },
  },
  {
    id: "modular-affordable",
    name: "Modular affordable construction",
    flavor: "Factory-built units, faster and cheaper.",
    description: "20 modular units in 6 months instead of 24.",
    lore: "Modular construction can cut build time roughly in half but has struggled with quality control and union pushback in Chicago. Boston-based Factory OS has been a notable West Coast case.",
    source: "Factory OS production data",
    category: "housing",
    rarity: "uncommon",
    cost: { capital: 3, knowledge: 1 },
    fromYear: 2015,
    toYear: 2040,
    effect: { growth: 3, equity: 2 },
  },

  /* ============================================================== *
   *  FINANCE                                                        *
   * ============================================================== */
  {
    id: "establish-tif",
    name: "Establish a TIF district",
    flavor: "Freeze the property-tax base for 23 years.",
    description: "Capture future tax growth in a TIF fund. Subsidizes infrastructure or developers.",
    lore: "Chicago has 124 active TIF districts capturing $1.36 billion in 2023, about 42 percent of all property-tax growth. Most TIF dollars have historically gone to downtown projects rather than the disinvested neighborhoods the program was originally meant to help.",
    source: "Cook County Clerk 2023 TIF Report",
    category: "finance",
    rarity: "common",
    cost: { power: 2 },
    fromYear: 1985,
    toYear: 2040,
    effect: {
      growth: 2,
      capital: 3,
      sustainability: -1,
      setFlag: "tif-active",
    },
    glossary: ["TIF"],
  },
  {
    id: "tif-affordable-housing",
    name: "Direct TIF to affordable housing",
    flavor: "Captured property tax pays for permanent affordable units.",
    description: "Spends TIF dollars on affordable construction. Cuts available capital but raises equity.",
    lore: "About 25 percent of Chicago TIF dollars go to housing in any given year, but only a small share of that is permanently affordable. Activists have pushed for a much higher share since the early 2010s.",
    source: "DePaul Institute for Housing Studies, TIF and Housing analyses",
    category: "finance",
    rarity: "uncommon",
    cost: { capital: 3, knowledge: 1 },
    requiresFlag: "tif-active",
    fromYear: 1990,
    toYear: 2040,
    effect: { equity: 4, growth: 1, heritage: 1 },
  },
  {
    id: "tif-sunset",
    name: "TIF sunset clause",
    flavor: "Roll back the TIF early. Property tax flows to schools again.",
    description: "Ends an active TIF. Restores tax base to CPS.",
    lore: "Chicago has surplused several TIFs early under public pressure, with funds returned to schools. The 2017 surplus alone returned about $200M to CPS.",
    source: "Civic Federation TIF Surplus reports",
    category: "finance",
    rarity: "uncommon",
    cost: { power: 4 },
    requiresFlag: "tif-active",
    fromYear: 1995,
    toYear: 2040,
    effect: { equity: 3, sustainability: 2, growth: -2 },
  },
  {
    id: "developer-impact-fee",
    name: "Developer impact fee",
    flavor: "New construction pays into a community-benefits fund.",
    description: "Charges new market-rate developments a per-unit fee.",
    lore: "Impact fees are widespread on the West Coast (San Francisco, Berkeley, Oakland). Chicago's ARO in-lieu fee functions similarly but is paid only by ARO-triggered developments, not all new construction.",
    source: "California impact fee studies, Lincoln Institute",
    category: "finance",
    rarity: "common",
    cost: { power: 2 },
    fromYear: 2000,
    toYear: 2040,
    effect: { equity: 2, capital: 2, growth: -1 },
  },
  {
    id: "vacancy-tax",
    name: "Vacant property tax",
    flavor: "Empty buildings pay a steep annual fee.",
    description: "Pressures absentee owners to sell or rehab.",
    lore: "Vancouver's Empty Homes Tax, started in 2017, brought thousands of vacant homes onto the rental market within two years. Oakland passed its own version in 2018.",
    source: "Vancouver Empty Homes Tax annual reports",
    category: "finance",
    rarity: "uncommon",
    cost: { power: 3 },
    fromYear: 2010,
    toYear: 2040,
    effect: {
      equity: 2,
      sustainability: 2,
      transformParcels: [
        { selector: "type:vacant", delta: { condition: 5 } },
      ],
    },
  },
  {
    id: "down-payment-assistance",
    name: "Down-payment assistance",
    flavor: "$30K toward first homes, no repayment required.",
    description: "Helps long-term renters become owners. Limited number of slots per year.",
    lore: "Chicago's Building Neighborhoods and Affordable Homes Program has provided down-payment assistance since the 1990s. The program has also been criticized for steering Black buyers into still-redlined neighborhoods.",
    source: "City of Chicago Department of Housing program reports",
    category: "finance",
    rarity: "uncommon",
    cost: { capital: 3, knowledge: 1 },
    fromYear: 1990,
    toYear: 2040,
    effect: { equity: 3, heritage: 1 },
  },
  {
    id: "redlining-investigation",
    name: "Investigate continued redlining",
    flavor: "Disparity studies, public hearings, news coverage.",
    description: "Forces banks to lend equitably. Slow but durable.",
    lore: "The 2018 Reveal investigation 'Kept Out' found significant ongoing lending discrimination in 61 metro areas including Chicago, despite the Fair Housing Act of 1968 and the Community Reinvestment Act of 1977.",
    source: "Reveal from the Center for Investigative Reporting, 'Kept Out' (2018)",
    category: "research",
    rarity: "uncommon",
    cost: { knowledge: 2, power: 2 },
    fromYear: 1980,
    toYear: 2040,
    effect: { equity: 3, knowledge: 1 },
    glossary: ["Redlining", "FHA"],
  },
  {
    id: "fund-cra-banks",
    name: "Recruit a CRA-active bank",
    flavor: "A community-development bank opens a Parkhaven branch.",
    description: "Improves access to credit. Reverses some long-term redlining.",
    lore: "Community Reinvestment Act ratings affect bank merger approval, which gives the federal government some leverage on local lending patterns. South Side Community Federal Credit Union and Self-Help Credit Union are examples of CRA-driven local lenders.",
    source: "FFIEC CRA examination data",
    category: "finance",
    rarity: "uncommon",
    cost: { capital: 2, trust: 2 },
    fromYear: 1980,
    toYear: 2040,
    effect: { equity: 3, growth: 2 },
  },

  /* ============================================================== *
   *  INFRASTRUCTURE                                                 *
   * ============================================================== */
  {
    id: "accept-expressway",
    name: "Accept the expressway",
    flavor: "Federal money. A six-lane corridor through the C-graded blocks.",
    description: "Demolishes 7 parcels. Brings jobs and air pollution.",
    lore: "The Federal-Aid Highway Act of 1956 funded the urban interstates. Mayor Daley widened the Dan Ryan in 1962 specifically to keep Black residents east of the white South Side. The expressway demolished thousands of housing units.",
    source: "Mohl, The Interstates and the Cities (2008)",
    category: "infrastructure",
    rarity: "uncommon",
    cost: { power: 2 },
    fromYear: 1956,
    toYear: 1975,
    effect: {
      growth: 4,
      capital: 4,
      heritage: -4,
      sustainability: -3,
      equity: -3,
      transformParcels: [
        { selector: "expressway-line", set: { type: "expressway", residents: 0, owner: "city" } },
      ],
      setFlag: "expressway-built",
    },
    glossary: ["Expressway"],
  },
  {
    id: "decline-expressway",
    name: "Decline the expressway",
    flavor: "Federal money walks. Parkhaven flagged uncooperative.",
    description: "Saves the parcels. Loses the funding.",
    lore: "Few cities successfully fought interstate routings, but those that did, like Greenwich Village under Jane Jacobs against the Lower Manhattan Expressway, preserved their neighborhood fabric.",
    source: "Jacobs, The Death and Life of Great American Cities (1961)",
    category: "infrastructure",
    rarity: "uncommon",
    cost: { power: 3, trust: 2 },
    fromYear: 1956,
    toYear: 1970,
    effect: { heritage: 4, equity: 3, capital: -2 },
  },
  {
    id: "transit-extension",
    name: "Red Line Extension station",
    flavor: "$1.2B, four years to build, 40 percent land-value bump.",
    description: "Adds a train station. Activates surrounding parcels.",
    lore: "The Red Line Extension cost $5.75B for 5.6 miles and four stations, fully funded by an FTA grant signed in December 2024. CTA projects $1.7B in associated real-estate activity. Without preservation overlays first, the activity becomes displacement.",
    source: "FTA Full Funding Grant Agreement (Dec 2024)",
    category: "transit",
    rarity: "rare",
    cost: { capital: 6, power: 3 },
    fromYear: 2025,
    toYear: 2040,
    effect: {
      growth: 5,
      sustainability: 4,
      equity: 1,
      transformParcels: [
        { selector: "first-of-type:vacant", set: { type: "transit", owner: "city" } },
      ],
      setFlag: "transit-extension",
    },
    glossary: ["RedLineExtension"],
  },
  {
    id: "bus-rapid-transit",
    name: "Bus rapid transit corridor",
    flavor: "Dedicated lanes, level boarding, signal priority.",
    description: "Faster bus service through the central blocks.",
    lore: "Cleveland's HealthLine BRT, opened 2008, generated $9.5B in adjacent investment over its first decade. Chicago's Ashland BRT was proposed in 2013 and has stalled.",
    source: "Institute for Transportation and Development Policy BRT studies",
    category: "transit",
    rarity: "uncommon",
    cost: { capital: 3, power: 2 },
    fromYear: 2010,
    toYear: 2040,
    effect: { sustainability: 3, growth: 2, equity: 1 },
  },
  {
    id: "protected-bike-lanes",
    name: "Protected bike network",
    flavor: "Concrete bollards, not paint.",
    description: "Adds safe cycling infrastructure. Reduces car dependence.",
    lore: "Protected bike lanes are correlated with significant drops in cyclist fatalities. Chicago has built a partial network since 2011. Coverage is heavily concentrated on the North Side.",
    source: "City of Chicago Streets for Cycling Plan",
    category: "infrastructure",
    rarity: "common",
    cost: { capital: 2, power: 1 },
    fromYear: 2010,
    toYear: 2040,
    effect: { sustainability: 3, equity: 1 },
  },
  {
    id: "alley-permeable",
    name: "Permeable alley program",
    flavor: "Replace asphalt with permeable pavers.",
    description: "Reduces flooding, lowers urban heat.",
    lore: "Chicago's Green Alley Program, launched 2006, has converted hundreds of alleys to permeable surfaces. The city saves on stormwater management and reduces basement flooding.",
    source: "City of Chicago Department of Transportation Green Alley Handbook",
    category: "environment",
    rarity: "common",
    cost: { capital: 1 },
    fromYear: 2005,
    toYear: 2040,
    effect: { sustainability: 3 },
  },
  {
    id: "tree-canopy-program",
    name: "Restore the tree canopy",
    flavor: "10,000 trees over five years.",
    description: "Reduces summer heat, cleans air, raises adjacent property values.",
    lore: "Chicago's tree canopy is heavily concentrated in wealthy North Side neighborhoods. South and West Side blocks have measurably hotter summer temperatures, contributing to higher emergency-department visits during heat waves.",
    source: "Chicago Region Trees Initiative tree canopy assessment",
    category: "environment",
    rarity: "common",
    cost: { capital: 2, knowledge: 1 },
    fromYear: 1980,
    toYear: 2040,
    effect: { sustainability: 4, equity: 2 },
  },

  /* ============================================================== *
   *  ORGANIZING                                                     *
   * ============================================================== */
  {
    id: "tenant-union",
    name: "Support a tenant union",
    flavor: "Building-by-building organizing, then citywide.",
    description: "Builds organized power. Cuts evictions, raises trust slowly.",
    lore: "The Lifton Building tenants in Uptown Chicago organized one of the city's first known tenant unions in 1969. The Autonomous Tenants Union, active in Albany Park since 2017, has won several rent strikes.",
    source: "Autonomous Tenants Union case studies",
    category: "organizing",
    rarity: "uncommon",
    cost: { trust: 2, power: 1 },
    fromYear: 1965,
    toYear: 2040,
    effect: { equity: 3, trust: 2 },
  },
  {
    id: "contract-buyers-strike",
    name: "Back the Contract Buyers League",
    flavor: "500 families withhold contract payments.",
    description: "Forces speculator renegotiations. Some families keep their homes.",
    lore: "The Contract Buyers League's 1968-1971 strike was the largest organized resistance to predatory home-sale practices in U.S. history. Some families won renegotiated terms. Many lost their homes anyway.",
    source: "Satter, Family Properties (2009), chs. 9-11",
    category: "organizing",
    rarity: "rare",
    cost: { trust: 3, power: 2 },
    fromYear: 1968,
    toYear: 1972,
    effect: { equity: 4, heritage: 3, knowledge: 1 },
    glossary: ["ContractBuying"],
  },
  {
    id: "fair-housing-tester",
    name: "Fair-housing tester program",
    flavor: "Paired tests catch landlords discriminating.",
    description: "Documents and prosecutes housing discrimination.",
    lore: "Tester programs send paired auditors of different races to inquire about housing. The systematic differences they document have been the basis for many federal fair housing cases. The Chicago Lawyers' Committee for Civil Rights ran an active tester program through the 2010s.",
    source: "HUD Fair Housing Testing Program guidance",
    category: "research",
    rarity: "uncommon",
    cost: { power: 2, knowledge: 2 },
    fromYear: 1968,
    toYear: 2040,
    effect: { equity: 3, knowledge: 1 },
  },
  {
    id: "youth-research-cohort",
    name: "Youth research cohort",
    flavor: "High-school students lead the next round of research.",
    description: "Builds long-term knowledge. Pays back over the next decade.",
    lore: "Rooted Forward's own model. Youth-led research cohorts in Chicago, Detroit, and Philadelphia have produced policy briefs cited by city councils.",
    source: "Rooted Forward research cohort reports",
    category: "research",
    rarity: "uncommon",
    cost: { trust: 2, knowledge: 1 },
    fromYear: 2015,
    toYear: 2040,
    effect: { equity: 2, heritage: 2, knowledge: 3, trust: 1 },
  },
  {
    id: "community-benefits-agreement",
    name: "Community benefits agreement",
    flavor: "Developer signs an enforceable contract with the neighborhood.",
    description: "Major project must hire locally, fund affordable units, or build amenities.",
    lore: "The Staples Center CBA in Los Angeles (2001) was the first major community benefits agreement and became a template. Chicago has seen smaller CBAs around the Obama Presidential Center and the United Center.",
    source: "Partnership for Working Families CBA toolkit",
    category: "organizing",
    rarity: "rare",
    cost: { power: 3, trust: 3, knowledge: 1 },
    fromYear: 2000,
    toYear: 2040,
    effect: { equity: 4, growth: 1, heritage: 2 },
  },
  {
    id: "anti-displacement-coalition",
    name: "Anti-displacement coalition",
    flavor: "Pilsen Alliance, LSNA, Logan Square Neighborhood Association.",
    description: "Cross-neighborhood coalition. Long-term political muscle.",
    lore: "The Pilsen Alliance and LSNA have been continuously active since the 1970s, pushing back on displacement pressure and shaping Chicago's affordable housing policy.",
    source: "Pilsen Alliance / LSNA published advocacy materials",
    category: "organizing",
    rarity: "rare",
    cost: { trust: 3, power: 2 },
    fromYear: 1975,
    toYear: 2040,
    effect: { equity: 3, heritage: 3, trust: 2 },
  },

  /* ============================================================== *
   *  COMMERCE & CULTURE                                             *
   * ============================================================== */
  {
    id: "small-business-grant",
    name: "Small-business grants",
    flavor: "$25K microgrants to neighborhood shops.",
    description: "Stabilizes corner stores, bakeries, barbershops.",
    lore: "The Neighborhood Opportunity Fund, established in Chicago in 2016, taxes downtown developers to fund neighborhood-business grants on the South and West Sides.",
    source: "City of Chicago Neighborhood Opportunity Fund reports",
    category: "commerce",
    rarity: "common",
    cost: { capital: 2, trust: 1 },
    fromYear: 1985,
    toYear: 2040,
    effect: { equity: 2, heritage: 2, growth: 1 },
  },
  {
    id: "cultural-corridor",
    name: "Designate a cultural corridor",
    flavor: "Murals, banners, cultural-business protections.",
    description: "Recognizes and protects cultural identity. Reduces displacement of cultural institutions.",
    lore: "Pilsen's 18th Street and the Chinatown gateway are examples. Cultural-corridor designations don't stop displacement on their own, but they create a political and aesthetic baseline that organized residents can defend.",
    source: "City of Chicago cultural plan",
    category: "culture",
    rarity: "uncommon",
    cost: { trust: 2, knowledge: 1 },
    fromYear: 1990,
    toYear: 2040,
    effect: { heritage: 4, equity: 1 },
  },
  {
    id: "neighborhood-mural",
    name: "Commission a public mural",
    flavor: "Hector Duarte, William Walker, the next generation.",
    description: "Adds a mural that builds community memory.",
    lore: "Chicago's mural movement dates to the late 1960s, with William Walker's 'Wall of Respect' (1967) at 43rd and Langley as the foundational piece. Pilsen's mural tradition is one of the densest in the country.",
    source: "Public Art Chicago / Chicago Mural Project archives",
    category: "culture",
    rarity: "common",
    cost: { capital: 1, trust: 1 },
    fromYear: 1967,
    toYear: 2040,
    effect: {
      heritage: 3,
      transformParcels: [
        { selector: "first-of-type:vacant", set: { type: "mural" } },
      ],
    },
  },
  {
    id: "branch-library",
    name: "Branch library",
    flavor: "A new Carnegie-style library opens.",
    description: "Free internet, after-school programs, civic anchor.",
    lore: "Chicago Public Library has 81 branches; the South Side and West Side have systematically smaller and older branches than the North. Investments in branch libraries correlate with measurable improvements in adjacent property stability.",
    source: "Chicago Public Library system data",
    category: "schools",
    rarity: "uncommon",
    cost: { capital: 3, knowledge: 1 },
    fromYear: 1940,
    toYear: 2040,
    effect: {
      heritage: 2,
      sustainability: 2,
      transformParcels: [
        { selector: "first-of-type:vacant", set: { type: "library" } },
      ],
    },
  },
  {
    id: "community-clinic",
    name: "Community health clinic",
    flavor: "Free or sliding-scale primary care.",
    description: "Adds clinic; long-term improvement in resident health.",
    lore: "Chicago's Federally Qualified Health Centers serve over a million patients annually. The South Side network, including TCA Health and Friend Family Health Center, has long waitlists.",
    source: "Illinois Primary Health Care Association reports",
    category: "schools",
    rarity: "uncommon",
    cost: { capital: 3, trust: 1 },
    fromYear: 1965,
    toYear: 2040,
    effect: {
      equity: 3,
      sustainability: 2,
      transformParcels: [
        { selector: "first-of-type:vacant", set: { type: "clinic" } },
      ],
    },
  },
  {
    id: "community-garden",
    name: "Community garden",
    flavor: "Vacant lot, raised beds, neighborhood plots.",
    description: "Activates a vacant lot. Modest food security gain.",
    lore: "Chicago's NeighborSpace, a nonprofit land trust for community gardens, holds about 130 sites. Garden sites are correlated with reduced crime and higher neighborhood satisfaction in adjacent blocks.",
    source: "NeighborSpace annual reports",
    category: "environment",
    rarity: "common",
    cost: { trust: 1, capital: 1 },
    fromYear: 1980,
    toYear: 2040,
    effect: {
      sustainability: 2,
      heritage: 1,
      transformParcels: [
        { selector: "first-of-type:vacant", set: { type: "community-garden" } },
      ],
    },
  },

  /* ============================================================== *
   *  SCHOOLS                                                        *
   * ============================================================== */
  {
    id: "rebuild-school",
    name: "Rebuild a neighborhood school",
    flavor: "New building, new lab, new gym, same kids.",
    description: "Renovates the local elementary school.",
    lore: "Chicago closed 50 neighborhood schools in 2013, the largest single round of school closures in U.S. history. Almost all closures were on the South and West Sides. The closures were challenged in federal court and the schools were never reopened.",
    source: "Chicago Public Schools 2013 school closure documentation",
    category: "schools",
    rarity: "uncommon",
    cost: { capital: 4, power: 1 },
    fromYear: 1960,
    toYear: 2040,
    effect: {
      equity: 3,
      heritage: 2,
      transformParcels: [
        { selector: "type:school", delta: { condition: 30 } },
      ],
    },
  },
  {
    id: "fight-school-closure",
    name: "Fight a school closure",
    flavor: "Hunger strike, rally at city hall.",
    description: "Keeps a neighborhood school open.",
    lore: "The 2015 Dyett High School hunger strike in Bronzeville lasted 34 days and forced CPS to keep the school open. Twelve people went on the strike, mostly grandmothers and teachers.",
    source: "Coverage of the Dyett hunger strike, Chicago Tribune 2015",
    category: "organizing",
    rarity: "uncommon",
    cost: { trust: 3, power: 2 },
    fromYear: 1990,
    toYear: 2040,
    effect: { equity: 3, heritage: 4, knowledge: 1 },
  },
  {
    id: "fund-schools-fairly",
    name: "Equalize CPS funding",
    flavor: "End the per-pupil funding gap.",
    description: "Shifts resources to underfunded schools.",
    lore: "Chicago Public Schools has one of the largest per-pupil funding gaps in the country, driven by reliance on local property tax. Black and Latino students attend schools funded at thousands of dollars less per pupil than majority-white CPS schools.",
    source: "EdBuild, '$23 Billion' (2019)",
    category: "schools",
    rarity: "rare",
    cost: { power: 4, knowledge: 2 },
    fromYear: 1985,
    toYear: 2040,
    effect: { equity: 5 },
  },

  /* ============================================================== *
   *  ENVIRONMENT                                                    *
   * ============================================================== */
  {
    id: "industrial-cleanup",
    name: "Brownfield cleanup",
    flavor: "EPA Superfund, soil remediation, two years.",
    description: "Restores contaminated land for use.",
    lore: "Chicago has dozens of brownfield sites, mostly from industrial uses on the South and West Sides. The federal Brownfields program funds cleanup. Once cleaned, the sites can host housing, parks, or commercial use.",
    source: "U.S. EPA Brownfields Program",
    category: "environment",
    rarity: "uncommon",
    cost: { capital: 4, knowledge: 1 },
    fromYear: 1985,
    toYear: 2040,
    effect: {
      sustainability: 4,
      transformParcels: [
        { selector: "type:industrial", set: { type: "vacant" } },
      ],
    },
  },
  {
    id: "rooftop-solar",
    name: "Rooftop solar incentives",
    flavor: "Federal tax credit plus city rebate.",
    description: "Lowers utility bills, cuts emissions.",
    lore: "The Inflation Reduction Act of 2022 expanded federal solar incentives substantially. Chicago has historically lagged Sunbelt cities on adoption. Rebates and bulk-buy programs have accelerated installations on the West Side.",
    source: "Inflation Reduction Act, 2022",
    category: "environment",
    rarity: "common",
    cost: { capital: 2, knowledge: 1 },
    fromYear: 2020,
    toYear: 2040,
    effect: { sustainability: 3, equity: 1 },
  },
  {
    id: "lead-pipe-replacement",
    name: "Replace lead service lines",
    flavor: "Federal Lead Service Line Replacement program.",
    description: "Replaces lead pipes to homes. Long-term health win.",
    lore: "Chicago has the most lead service lines of any U.S. city, an estimated 400,000. Federal lead-pipe replacement funding from the 2021 infrastructure law has begun a multi-decade program.",
    source: "Bipartisan Infrastructure Law (2021)",
    category: "environment",
    rarity: "uncommon",
    cost: { capital: 3 },
    fromYear: 2022,
    toYear: 2040,
    effect: { sustainability: 4, equity: 3 },
  },

  /* ============================================================== *
   *  RESEARCH                                                       *
   * ============================================================== */
  {
    id: "publish-disparity-study",
    name: "Publish a disparity study",
    flavor: "Numbers in print. Hard to ignore.",
    description: "Quantifies racial disparities in lending, contracting, schools.",
    lore: "Disparity studies are required for cities to defend race-conscious contracting programs after Croson v. City of Richmond (1989). Chicago publishes one every few years.",
    source: "City of Chicago Department of Procurement Services disparity studies",
    category: "research",
    rarity: "uncommon",
    cost: { capital: 1, knowledge: 2 },
    fromYear: 1990,
    toYear: 2040,
    effect: { equity: 2, knowledge: 2 },
  },
  {
    id: "document-history",
    name: "Document the neighborhood history",
    flavor: "Oral histories, archived photos, walking-tour scripts.",
    description: "Builds heritage durably. Slow-burn equity gain.",
    lore: "The Chicago Public Library's StoryCorps initiative and the South Side Home Movie Project have preserved oral and visual histories that would otherwise be lost.",
    source: "Chicago Public Library StoryCorps; South Side Home Movie Project",
    category: "research",
    rarity: "common",
    cost: { trust: 1, knowledge: 1 },
    fromYear: 1990,
    toYear: 2040,
    effect: { heritage: 3, knowledge: 2 },
  },

  /* ============================================================== *
   *  AGGRESSIVE / SHADOW PLAYS                                       *
   * ============================================================== */
  {
    id: "speculator-buyout",
    name: "Court a speculator",
    flavor: "Quietly invite outside capital. Watch values rise.",
    description: "Speculator buys 5 parcels. Capital gain. Trust loss.",
    lore: "Tax-lien speculators have bought thousands of South and West Side parcels since the 2008 crisis, often holding them empty until prices rise. The Cook County Land Bank Authority was created in 2013 in part to push back on this practice.",
    source: "Cook County Land Bank Authority annual reports",
    category: "finance",
    rarity: "common",
    cost: { capital: 0 },
    fromYear: 2010,
    toYear: 2040,
    effect: {
      capital: 4,
      equity: -3,
      heritage: -2,
      transformParcels: [
        { selector: "random:5", set: { owner: "speculator" } },
      ],
    },
  },
  {
    id: "luxury-tower-deal",
    name: "Approve a luxury tower",
    flavor: "Gleaming glass, 80 units, no affordability.",
    description: "Big tax bump. Catalyzes gentrification of adjacent blocks.",
    lore: "Luxury towers without affordability requirements were the default outcome of Chicago's pre-2015 zoning regime. The 2021 ARO update addressed this in displacement-risk zones.",
    source: "Chicago Department of Housing market-rate development data",
    category: "housing",
    rarity: "common",
    cost: { power: 2 },
    fromYear: 2010,
    toYear: 2040,
    effect: {
      capital: 3,
      growth: 4,
      equity: -3,
      heritage: -2,
      transformParcels: [
        { selector: "first-of-type:vacant", set: { type: "tower", residents: 80, owner: "developer" } },
      ],
    },
  },
  {
    id: "evict-noncompliant-tenants",
    name: "Aggressive code enforcement",
    flavor: "Issue building citations. Push out absentee landlords.",
    description: "Drives renovation. Some legitimate landlords lose buildings too.",
    lore: "Aggressive code enforcement is a documented gentrification tactic. It can accelerate displacement under the cover of public-safety concerns. Code-enforcement displacement was a major theme in 1980s gentrification studies of Park Slope, Brooklyn.",
    source: "Smith, The New Urban Frontier (1996)",
    category: "zoning",
    rarity: "uncommon",
    cost: { power: 2 },
    fromYear: 1980,
    toYear: 2040,
    effect: {
      growth: 2,
      equity: -2,
      capital: 2,
    },
  },
  {
    id: "sign-summit-agreement",
    name: "Sign the Summit Agreement",
    flavor: "Daley calls it a victory. The marches stop.",
    description: "Quiet on the streets, no enforcement teeth.",
    lore: "The 1966 Summit Agreement ended the Chicago Open Housing Movement marches. The agreement contained vague language and no enforcement mechanism. Daley signed and then did not enforce it.",
    source: "Garrow, Bearing the Cross (1986); Ralph, Northern Protest (1993)",
    category: "organizing",
    rarity: "rare",
    cost: { power: 1 },
    fromYear: 1966,
    toYear: 1968,
    effect: { capital: 2, equity: -2, heritage: -1 },
  },

  /* ============================================================== *
   *  RARE / LATE GAME                                               *
   * ============================================================== */
  {
    id: "preservation-overlay-rle",
    name: "Lock in preservation before the RLE",
    flavor: "Pass the overlays. Then announce the train.",
    description: "Rights of first refusal, demolition holds, anti-flipping. Then transit.",
    lore: "Pre-emptive preservation before transit announcements is the most effective known anti-displacement tactic. Few American cities have done it. Boston's Fairmount Indigo CDC partnerships and the LA Metro Transit-Oriented Communities program are partial examples.",
    source: "Pollack and Bluestone, 'Maintaining Diversity in America's Transit-Rich Neighborhoods' (2010)",
    category: "preservation",
    rarity: "legendary",
    cost: { power: 4, trust: 4, knowledge: 2 },
    fromYear: 2020,
    toYear: 2035,
    effect: {
      equity: 6,
      heritage: 4,
      sustainability: 3,
      setFlag: "preservation-overlay",
    },
  },
  {
    id: "regional-fair-share",
    name: "Regional fair-share housing",
    flavor: "Suburbs absorb their share of affordable units.",
    description: "Spreads the affordability burden across the metro.",
    lore: "New Jersey's Mount Laurel doctrine, established 1975 and codified in 1985, requires every municipality to plan for its 'fair share' of regional affordable housing. The Chicago metro has nothing comparable.",
    source: "Mount Laurel Doctrine, NJ Supreme Court",
    category: "finance",
    rarity: "legendary",
    cost: { power: 5, knowledge: 3 },
    fromYear: 2000,
    toYear: 2040,
    effect: { equity: 7, growth: 1 },
  },
  {
    id: "reparations-fund",
    name: "Local reparations fund",
    flavor: "Targeted compensation for descendants of contract buyers and demolished blocks.",
    description: "Cash transfers and homeownership support.",
    lore: "Evanston, Illinois, established the country's first municipal reparations program in 2021, offering $25,000 housing grants to qualifying Black residents. Chicago has discussed but not enacted a similar program.",
    source: "City of Evanston Restorative Housing Program",
    category: "finance",
    rarity: "legendary",
    cost: { power: 5, capital: 5, knowledge: 2 },
    fromYear: 2020,
    toYear: 2040,
    effect: { equity: 8, heritage: 4 },
  },

  /* ============================================================== *
   *  CONTINUE - more cards                                           *
   * ============================================================== */
  {
    id: "ban-source-discrimination",
    name: "Ban source-of-income discrimination",
    flavor: "Landlords cannot refuse Section 8 vouchers.",
    description: "Expands voucher usability across the city.",
    lore: "Chicago passed source-of-income protection in 1990, one of the earliest such ordinances. Enforcement remains a challenge. The 2020 federal HUD rule clarified that source-of-income discrimination disparately impacts protected classes.",
    source: "Chicago Human Rights Ordinance, 1990 amendment",
    category: "organizing",
    rarity: "common",
    cost: { power: 2 },
    fromYear: 1990,
    toYear: 2040,
    effect: { equity: 3 },
    glossary: ["Section8"],
  },
  {
    id: "co-op-conversion",
    name: "Co-op conversion grants",
    flavor: "Help tenants buy their building together.",
    description: "Converts rental buildings to limited-equity co-ops.",
    lore: "Chicago has a smaller cooperative housing sector than New York or San Francisco. Limited-equity co-ops cap resale prices to maintain affordability across generations.",
    source: "Cooperative Development Foundation; Chicago co-op studies",
    category: "housing",
    rarity: "uncommon",
    cost: { capital: 3, trust: 2 },
    fromYear: 1980,
    toYear: 2040,
    effect: { equity: 4, heritage: 3 },
  },
  {
    id: "missing-middle-housing",
    name: "Missing middle housing",
    flavor: "Two-flats, three-flats, courtyards, fourplexes.",
    description: "Add gentle density. Adds capacity without towers.",
    lore: "The 'missing middle' framework, popularized by architect Daniel Parolek, refers to building types between single-family and high-rise. Chicago historically had abundant missing-middle stock; downzoning in the 1950s removed much of it.",
    source: "Parolek, Missing Middle Housing (2020)",
    category: "housing",
    rarity: "uncommon",
    cost: { capital: 3, power: 2 },
    fromYear: 2010,
    toYear: 2040,
    effect: { growth: 3, sustainability: 2, equity: 2 },
  },
  {
    id: "neighborhood-grocer",
    name: "Recruit a grocery store",
    flavor: "Full-service supermarket fills a food desert.",
    description: "Health and quality-of-life gain. Anchor for the commercial strip.",
    lore: "South and West Side Chicago has been documented as one of the largest urban food deserts in the country. The Healthy Food Financing Initiative provides federal funds to recruit grocers to underserved areas.",
    source: "USDA Healthy Food Financing Initiative",
    category: "commerce",
    rarity: "uncommon",
    cost: { capital: 3, trust: 1 },
    fromYear: 2010,
    toYear: 2040,
    effect: { equity: 3, sustainability: 2, growth: 1 },
  },
  {
    id: "block-club-revival",
    name: "Block club revival",
    flavor: "Front-yard meetings, gardening days, holiday parties.",
    description: "Builds resident ties. Slow but compounding equity.",
    lore: "Chicago's block club tradition dates to the early 20th century. The Chicago Department of Family and Support Services has maintained block-club registration through every administration since the 1960s.",
    source: "City of Chicago Block Club registration data",
    category: "organizing",
    rarity: "common",
    cost: { trust: 2 },
    fromYear: 1940,
    toYear: 2040,
    effect: { heritage: 2, equity: 1, trust: 2 },
  },
  {
    id: "participatory-budgeting",
    name: "Participatory budgeting",
    flavor: "Residents decide how to spend the menu money.",
    description: "Spends $1M on resident-chosen projects.",
    lore: "Chicago alderman Joe Moore (49th Ward) introduced the city's first participatory budgeting process in 2009. About a dozen wards have used it since. The process is associated with measurable increases in civic trust.",
    source: "Participatory Budgeting Project Chicago case study",
    category: "organizing",
    rarity: "uncommon",
    cost: { trust: 2, power: 1 },
    fromYear: 2009,
    toYear: 2040,
    effect: { equity: 2, heritage: 2, trust: 2 },
  },
  {
    id: "public-safety-investment",
    name: "Community safety investment",
    flavor: "Violence interrupters, after-school programs, mental health teams.",
    description: "Non-police safety strategies.",
    lore: "Cure Violence (originally CeaseFire), founded by Gary Slutkin in Chicago in 2000, treats violence as a public-health problem. The model has been replicated in dozens of cities and is associated with double-digit reductions in shootings in target areas.",
    source: "Cure Violence outcome studies",
    category: "organizing",
    rarity: "uncommon",
    cost: { capital: 3, trust: 2 },
    fromYear: 2000,
    toYear: 2040,
    effect: { equity: 3, heritage: 2, sustainability: 1 },
  },
  {
    id: "mortgage-counseling",
    name: "First-time homebuyer counseling",
    flavor: "Eight-hour course, certified counselors.",
    description: "Improves loan terms, reduces foreclosure risk.",
    lore: "Pre-purchase homebuyer counseling, required for many subsidized mortgage programs, is associated with significantly lower foreclosure rates. The Neighborhood Housing Services of Chicago has been a major provider since the 1970s.",
    source: "Neighborhood Housing Services of Chicago program data",
    category: "finance",
    rarity: "common",
    cost: { capital: 1, knowledge: 1 },
    fromYear: 1975,
    toYear: 2040,
    effect: { equity: 2 },
  },
  {
    id: "challenge-tax-assessment",
    name: "Challenge property assessments",
    flavor: "Cook County over-assesses Black neighborhoods. Dispute it.",
    description: "Lowers property tax burden for Black homeowners.",
    lore: "A 2017 ProPublica investigation found that Cook County's property tax assessments systematically over-assessed homes in Black and Latino neighborhoods relative to white ones. The county began reform after the report.",
    source: "ProPublica, 'The Tax Divide' (2017)",
    category: "research",
    rarity: "uncommon",
    cost: { knowledge: 2, power: 1 },
    fromYear: 2015,
    toYear: 2040,
    effect: { equity: 3 },
  },
  {
    id: "ai-disclosure-ordinance",
    name: "AI tenant-screening disclosure",
    flavor: "Algorithms that deny rentals must explain themselves.",
    description: "Reduces opaque algorithmic discrimination.",
    lore: "Tenant-screening algorithms have been documented to systematically discriminate against Black applicants and voucher holders. NYC Local Law 144 (2021) requires algorithmic-employment audits; tenant screening has lagged.",
    source: "Reveal CIR investigation of tenant-screening algorithms (2020)",
    category: "research",
    rarity: "rare",
    cost: { knowledge: 3, power: 2 },
    fromYear: 2022,
    toYear: 2040,
    effect: { equity: 3, knowledge: 1 },
  },
  {
    id: "community-energy-project",
    name: "Community solar project",
    flavor: "Residents subscribe to a shared solar array.",
    description: "Lowers utility bills. Builds renewable capacity.",
    lore: "Illinois passed the Future Energy Jobs Act in 2016 and the Climate and Equitable Jobs Act in 2021, which authorized and expanded community solar. Chicago participation has been slower than expected.",
    source: "Illinois Climate and Equitable Jobs Act (2021)",
    category: "environment",
    rarity: "uncommon",
    cost: { capital: 2, knowledge: 1 },
    fromYear: 2018,
    toYear: 2040,
    effect: { sustainability: 4, equity: 2 },
  },
  {
    id: "youth-employment",
    name: "Youth summer employment",
    flavor: "10,000 summer jobs.",
    description: "Pays young residents to work in the neighborhood.",
    lore: "Chicago's One Summer Chicago program has placed tens of thousands of young people in paid summer work. Studies have linked participation to large reductions in violent-crime arrests for participants.",
    source: "One Summer Chicago program evaluations",
    category: "schools",
    rarity: "common",
    cost: { capital: 2 },
    fromYear: 2011,
    toYear: 2040,
    effect: { equity: 3, heritage: 1 },
  },
  {
    id: "transit-fare-equity",
    name: "Free transit for low-income riders",
    flavor: "Reduced or free Ventra cards.",
    description: "Removes the fare barrier for the most cost-burdened.",
    lore: "Boston's MBTA piloted free buses on the Route 28 corridor in 2022; ridership rose, fare evasion fell, dwell times shortened. Chicago has discussed but not adopted free transit for low-income riders.",
    source: "MBTA Route 28 Free Bus Pilot evaluation (2022)",
    category: "transit",
    rarity: "rare",
    cost: { capital: 4, power: 2 },
    fromYear: 2022,
    toYear: 2040,
    effect: { equity: 4, sustainability: 2 },
  },
  {
    id: "restorative-zoning",
    name: "Restorative zoning",
    flavor: "Zoning bonuses tied to local hiring and affordable units.",
    description: "Aligns developer incentives with community needs.",
    lore: "Restorative-zoning frameworks tie any zoning bonus (height, density, FAR) to verified community benefits. Variants exist in Cambridge, Massachusetts and Pittsburgh, Pennsylvania.",
    source: "Cambridge inclusionary housing program documentation",
    category: "zoning",
    rarity: "rare",
    cost: { knowledge: 2, power: 3 },
    fromYear: 2015,
    toYear: 2040,
    effect: { equity: 4, growth: 1, sustainability: 1 },
  },
  {
    id: "art-in-public-housing",
    name: "Art-in-public-housing program",
    flavor: "Murals, sculpture, music in CHA developments.",
    description: "Builds heritage in housing the city often treats as disposable.",
    lore: "The CHA's percent-for-art program has commissioned dozens of works since the 1990s. The murals at the former Stateway Gardens and at Lathrop Homes are notable.",
    source: "CHA Percent-for-Art program",
    category: "culture",
    rarity: "common",
    cost: { capital: 1, trust: 1 },
    fromYear: 1990,
    toYear: 2040,
    effect: { heritage: 3, equity: 1 },
  },
  {
    id: "mutual-aid-network",
    name: "Mutual aid network",
    flavor: "Block-by-block, neighbor-to-neighbor support.",
    description: "Builds informal safety net.",
    lore: "Chicago saw a major expansion of mutual-aid networks during the COVID-19 pandemic in 2020. Pilsen Mutual Aid and Logan Square Mutual Aid have continued past the pandemic emergency.",
    source: "Pilsen Mutual Aid; Logan Square Mutual Aid public reports",
    category: "organizing",
    rarity: "common",
    cost: { trust: 2 },
    fromYear: 2020,
    toYear: 2040,
    effect: { heritage: 2, equity: 2, trust: 2 },
  },
  {
    id: "green-infrastructure-bond",
    name: "Green infrastructure bond",
    flavor: "$50M general obligation bond for green works.",
    description: "Funds bioswales, permeable surfaces, urban forestry.",
    lore: "Philadelphia's Green City, Clean Waters program, launched 2011, is the most cited urban green-infrastructure case in the U.S. The program meets EPA stormwater requirements without traditional gray infrastructure.",
    source: "Philadelphia Water Department Green City, Clean Waters reports",
    category: "environment",
    rarity: "uncommon",
    cost: { capital: 4, power: 2 },
    fromYear: 2010,
    toYear: 2040,
    effect: { sustainability: 5, growth: 1 },
  },
  {
    id: "no-net-loss-policy",
    name: "No net loss of affordability",
    flavor: "Every affordable unit demolished must be replaced.",
    description: "Prevents losing affordable units to redevelopment.",
    lore: "San Francisco's no-net-loss housing policies date to the late 1970s and have shaped how the city approves market-rate development. Chicago has discussed but not enacted no-net-loss for affordable housing.",
    source: "San Francisco Planning Department no-net-loss documentation",
    category: "housing",
    rarity: "rare",
    cost: { power: 4, knowledge: 1 },
    fromYear: 2010,
    toYear: 2040,
    effect: { equity: 4, heritage: 3 },
  },
  {
    id: "maker-space",
    name: "Public maker space",
    flavor: "Tools, training, micro-fabrication.",
    description: "Lowers the cost of starting a small business.",
    lore: "Chicago's Manufacturing Renaissance has worked since the 1980s to maintain industrial jobs in the city. Maker spaces and micro-manufacturing facilities have been a recent component.",
    source: "Manufacturing Renaissance Chicago program reports",
    category: "commerce",
    rarity: "common",
    cost: { capital: 2, knowledge: 1 },
    fromYear: 2010,
    toYear: 2040,
    effect: { growth: 2, equity: 2 },
  },
  {
    id: "ban-no-knock-warrants",
    name: "Ban no-knock warrants",
    flavor: "Police must announce themselves.",
    description: "Reduces violent encounters during searches.",
    lore: "Chicago restricted no-knock warrants in 2021 after the death of Anjanette Young in a wrong-address raid. The reform built on a longer national debate after the killing of Breonna Taylor in Louisville.",
    source: "City of Chicago Department of Police search warrant reform 2021",
    category: "organizing",
    rarity: "common",
    cost: { power: 2, trust: 1 },
    fromYear: 2021,
    toYear: 2040,
    effect: { equity: 3, trust: 1 },
  },
];

/** Map of card id to card for fast lookup */
export const CARD_BY_ID: Map<string, Card> = new Map(CARDS.map((c) => [c.id, c]));

/** Get cards available in a given year, optionally filtered by required flags */
export function availableCards(year: number, flags: Set<string>): Card[] {
  return CARDS.filter((c) => {
    if (c.fromYear !== undefined && year < c.fromYear) return false;
    if (c.toYear !== undefined && year > c.toYear) return false;
    if (c.requiresFlag && !flags.has(c.requiresFlag)) return false;
    return true;
  });
}
