/**
 * The card library. Approximately 100 policy cards spanning four eras.
 * Each card represents a real lever a Chicago alderman, planner, or
 * organizer could pull. Costs are paid in capital, power, trust, and
 * knowledge. Effects move the four hidden scores and transform parcels.
 *
 * Cards are tagged with era windows so the deck rotates as years pass:
 * the 1940 deck has very different options than the 2020 deck.
 *
 * Lore notes carry the educational content. They cite real sources.
 * The game does not lecture, but a player who hovers a card sees the
 * one-paragraph history behind it.
 */

import type { Card } from "./types";

export const CARDS: Card[] = [
  /* ============================================================== *
   *  ZONING                                                         *
   * ============================================================== */
  {
    id: "downzone-northern-blocks",
    name: "Single-family overlay",
    flavor: "Property owners' association politely insistent.",
    description: "Lock the northern blocks to single-family only. Raises value, prevents density, signals exclusion.",
    lore: "Through the 1950s and 60s, white aldermen used single-family zoning to do what racial covenants no longer legally could. The overlay raised property values short term and prevented the construction of two-flats and small apartment buildings that working-class families could afford.",
    source: "Rothstein, The Color of Law (2017), ch. 3",
    category: "zoning",
    rarity: "common",
    cost: { power: 1, capital: 2 },
    fromYear: 1940,
    toYear: 1980,
    effect: {
      growth: -1,
      equity: -2,
      heritage: 1,
      transformParcels: [
        { selector: "block:0", delta: { value: 8 } },
        { selector: "block:1", delta: { value: 6 } },
      ],
    },
    glossary: ["Covenants"],
  },
  {
    id: "upzone-transit",
    name: "Upzone the transit corridor",
    flavor: "More homes near the train, by right.",
    description: "Allow three-flats and courtyards near transit. Adds units, intensifies pressure on existing buildings.",
    lore: "Transit-oriented development upzoning has been a major Chicago debate since 2015. Supporters note that allowing more homes near trains reduces sprawl and lowers per-household carbon. Critics note that without affordability requirements, the new units rent at market rate and accelerate displacement.",
    source: "Chicago TOD Reform 2015, 2019, 2021 amendments",
    category: "zoning",
    rarity: "common",
    cost: { power: 2 },
    fromYear: 1990,
    toYear: 2040,
    effect: {
      growth: 3,
      sustainability: 2,
      equity: -1,
      transformParcels: [
        { selector: "adjacent-to:transit", delta: { value: 10 } },
      ],
    },
    glossary: ["Gentrification"],
  },
  {
    id: "legalize-adu",
    name: "Legalize ADUs citywide",
    flavor: "Coach houses and basement apartments, again.",
    description: "Allow accessory dwelling units on every lot. Modest gain in housing supply.",
    lore: "Chicago banned new accessory dwelling units in 1957 as part of a wave of postwar zoning crackdowns. The 2021 pilot reintroduced them in five zones. Citywide legalization is scheduled for April 1, 2026.",
    source: "City of Chicago ADU pilot program reports",
    category: "zoning",
    rarity: "uncommon",
    cost: { power: 2, knowledge: 1 },
    fromYear: 2020,
    toYear: 2040,
    effect: {
      growth: 2,
      sustainability: 1,
      equity: 1,
      transformParcels: [
        { selector: "type:single-family", delta: { residents: 1 } },
      ],
    },
    glossary: ["ADU"],
  },
  {
    id: "form-based-code",
    name: "Form-based code",
    flavor: "Regulate the building shape, not the use.",
    description: "Replace use-based zoning with form-based code in the central blocks. Encourages mixed use.",
    lore: "Form-based codes regulate the physical form of buildings (height, setback, frontage) rather than what happens inside them. They allow mixed use by default, which can revive walkable commercial streets. Pioneered by Andrés Duany in Seaside, Florida.",
    source: "Form-Based Codes Institute reference materials",
    category: "zoning",
    rarity: "rare",
    cost: { knowledge: 2, power: 2, capital: 3 },
    fromYear: 2000,
    toYear: 2040,
    effect: {
      growth: 2,
      sustainability: 3,
      heritage: 1,
      transformParcels: [
        { selector: "block:2", delta: { value: 6 } },
      ],
    },
  },
  {
    id: "preservation-overlay",
    name: "Historic preservation overlay",
    flavor: "Plaques, restrictions, slow demolition.",
    description: "Block demolition in the central blocks. Protects what exists, slows new construction.",
    lore: "Chicago landmark designations require Commission on Chicago Landmarks approval before any demolition or major exterior alteration. The system saved the Reliance Building. It also gets criticized for protecting buildings while displacing people.",
    source: "Chicago Landmarks Ordinance",
    category: "preservation",
    rarity: "uncommon",
    cost: { power: 2, knowledge: 1 },
    fromYear: 1970,
    toYear: 2040,
    effect: {
      heritage: 4,
      growth: -2,
      transformParcels: [
        { selector: "block:2", set: { protected: true } },
      ],
    },
  },
  {
    id: "demolition-moratorium",
    name: "Demolition moratorium",
    flavor: "Nothing comes down for two years.",
    description: "Pause all demolitions in the ward. Stops displacement, freezes the housing stock.",
    lore: "The 1980s anti-demolition ordinances in Cleveland and Pittsburgh demonstrated that municipal moratoriums could stop blockbusting in real time. Chicago has used short demolition holds during landmark review.",
    source: "Pittsburgh Demolition Ordinance, 1985",
    category: "preservation",
    rarity: "uncommon",
    cost: { power: 3, trust: 1 },
    fromYear: 1980,
    toYear: 2040,
    effect: {
      heritage: 3,
      equity: 2,
      growth: -2,
    },
  },

  /* ============================================================== *
   *  HOUSING                                                        *
   * ============================================================== */
  {
    id: "build-cha-tower",
    name: "Build a CHA tower",
    flavor: "16 stories, 200 units, federal money.",
    description: "Add a public-housing tower in the south blocks. Cheap, dense, and historically catastrophic.",
    lore: "The CHA built towers because Congress would only fund concentrated public housing on cheap land, and white aldermen blocked siting in their wards. By the 1990s most of the towers were uninhabitable. The Plan for Transformation demolished them starting in 1999.",
    source: "Hunt, Blueprint for Disaster (2009)",
    category: "housing",
    rarity: "common",
    cost: { capital: 3, power: 2 },
    fromYear: 1948,
    toYear: 1980,
    effect: {
      growth: 2,
      equity: 1,
      heritage: -2,
      sustainability: -2,
      transformParcels: [
        { selector: "first-vacant:south", set: { type: "tower", residents: 200, owner: "cha" } },
      ],
    },
    glossary: ["CHA"],
  },
  {
    id: "scattered-site",
    name: "Scattered-site low-rise",
    flavor: "Smaller buildings, mixed across the ward.",
    description: "Build 30 units across 10 sites. Costs more, integrates better.",
    lore: "Scattered-site public housing was the remedy ordered in Hills v. Gautreaux (1976). The CHA fought it for years; lawsuits to enforce it ran through the 2000s.",
    source: "Hills v. Gautreaux, 425 U.S. 284 (1976)",
    category: "housing",
    rarity: "uncommon",
    cost: { capital: 4, power: 3 },
    fromYear: 1970,
    toYear: 2040,
    effect: {
      equity: 4,
      heritage: 2,
      growth: 1,
      transformParcels: [
        { selector: "random:10", set: { type: "courtyard", residents: 12 } },
      ],
    },
    glossary: ["Gautreaux"],
  },
  {
    id: "mixed-income",
    name: "Mixed-income redevelopment",
    flavor: "One-third public, one-third affordable, one-third market.",
    description: "Demolish a tower, build mixed-income. Cuts concentrated poverty, displaces existing residents.",
    lore: "The Plan for Transformation promised one-for-one replacement of public housing units. The actual rate ran around 60 percent. Tens of thousands of CHA residents were displaced and many never returned.",
    source: "Chaskin and Joseph, Integrating the Inner City (2015)",
    category: "housing",
    rarity: "rare",
    cost: { capital: 5, power: 3 },
    fromYear: 1995,
    toYear: 2040,
    requiresFlag: "tower-built",
    effect: {
      equity: 1,
      heritage: -3,
      growth: 3,
      transformParcels: [
        { selector: "type:tower", set: { type: "courtyard", residents: 80 } },
      ],
    },
    glossary: ["PlanForTransformation"],
  },
  {
    id: "rehab-in-place",
    name: "Rehab in place",
    flavor: "$90M federal grant. The towers stay.",
    description: "Major elevator and plumbing rehab. No displacement, ongoing maintenance burden.",
    lore: "HOPE VI funding could be used for rehab as well as demolition. Chicago chose demolition for almost every major site. Boston's Mission Main and Newark's Stella Wright were notable rehab successes.",
    source: "HUD HOPE VI Cost Comparisons (2008)",
    category: "housing",
    rarity: "uncommon",
    cost: { capital: 4 },
    fromYear: 1995,
    toYear: 2030,
    requiresFlag: "tower-built",
    effect: {
      heritage: 4,
      equity: 3,
      transformParcels: [
        { selector: "type:tower", set: { type: "rehab-tower", condition: 75 } },
      ],
    },
  },
  {
    id: "section-8-vouchers",
    name: "Expand Section 8 vouchers",
    flavor: "Tenants pay 30% of income, vouchers cover the rest.",
    description: "Issue 200 new vouchers. Helps families afford rent. Landlords often refuse them.",
    lore: "The Housing Choice Voucher program was created by the 1974 Housing Act and expanded under Reagan. Voucher holders face widespread discrimination from landlords. Chicago passed source-of-income protection in 1990, but enforcement is uneven.",
    source: "HUD Housing Choice Voucher administrative guidelines",
    category: "housing",
    rarity: "common",
    cost: { capital: 3, power: 1 },
    fromYear: 1975,
    toYear: 2040,
    effect: { equity: 3, growth: 1 },
    glossary: ["Section8"],
  },
  {
    id: "right-to-counsel",
    name: "Right to counsel for tenants",
    flavor: "Every tenant gets a lawyer in eviction court.",
    description: "Pay for legal representation for tenants facing eviction. Cuts evictions sharply.",
    lore: "New York City passed the first universal right to counsel for housing court in 2017. Eviction filings fell roughly 40 percent within five years. Chicago has had pilot programs but no citywide right.",
    source: "NYC Office of Civil Justice Annual Reports",
    category: "organizing",
    rarity: "uncommon",
    cost: { capital: 3, trust: 1 },
    fromYear: 2010,
    toYear: 2040,
    effect: { equity: 4, heritage: 2 },
  },
  {
    id: "anti-flipping-tax",
    name: "Anti-flipping tax",
    flavor: "Sell a property within 2 years and pay a steep transfer tax.",
    description: "Discourages speculative flipping. Slows price appreciation.",
    lore: "Various jurisdictions have used short-term sale taxes to dampen speculation. San Francisco voters considered a measure in 2014; it failed but inspired similar proposals nationally.",
    source: "Lincoln Institute of Land Policy speculation studies",
    category: "finance",
    rarity: "uncommon",
    cost: { power: 3 },
    fromYear: 1990,
    toYear: 2040,
    effect: { equity: 2, growth: -1, heritage: 2 },
  },
  {
    id: "land-trust-acquisition",
    name: "Community land trust acquisition",
    flavor: "Take five parcels off the speculative market forever.",
    description: "Purchase land into a permanent community trust. Locks affordability for the duration of the lease.",
    lore: "The Burlington Community Land Trust in Vermont, founded 1984, holds about 565 homes and 2,200 rental units. Resale formulas keep prices appreciating slowly enough that the units remain affordable across generations.",
    source: "Lincoln Institute CLT outcomes (2018)",
    category: "housing",
    rarity: "rare",
    cost: { capital: 5, trust: 2, knowledge: 1 },
    fromYear: 2000,
    toYear: 2040,
    effect: {
      equity: 5,
      heritage: 3,
      transformParcels: [
        { selector: "random:5", set: { type: "land-trust", owner: "land-trust", protected: true } },
      ],
    },
    glossary: ["CommunityLandTrust"],
  },
  {
    id: "tenant-opportunity-purchase",
    name: "Tenant opportunity to purchase",
    flavor: "Tenants get first right of refusal when their building goes up for sale.",
    description: "Slows speculative resale. Tenants can pool to buy as a co-op.",
    lore: "Washington, D.C.'s Tenant Opportunity to Purchase Act (TOPA) dates to 1980 and has produced thousands of co-op conversions. Chicago has discussed TOPA repeatedly without passing one.",
    source: "DC TOPA program data; Chicago TOPA proposals 2018-2024",
    category: "organizing",
    rarity: "rare",
    cost: { power: 3, trust: 2 },
    fromYear: 1985,
    toYear: 2040,
    effect: { equity: 3, heritage: 4 },
  },
  {
    id: "modular-affordable",
    name: "Modular affordable construction",
    flavor: "Factory-built units, faster and cheaper.",
    description: "20 modular units in 6 months instead of 24.",
    lore: "Modular construction can cut build time roughly in half but has struggled with quality control and union pushback in Chicago. Boston-based Factory OS has been a notable West Coast case.",
    source: "Factory OS production data",
    category: "housing",
    rarity: "uncommon",
    cost: { capital: 3, knowledge: 1 },
    fromYear: 2015,
    toYear: 2040,
    effect: { growth: 3, equity: 2 },
  },

  /* ============================================================== *
   *  FINANCE                                                        *
   * ============================================================== */
  {
    id: "establish-tif",
    name: "Establish a TIF district",
    flavor: "Freeze the property-tax base for 23 years.",
    description: "Capture future tax growth in a TIF fund. Subsidizes infrastructure or developers.",
    lore: "Chicago has 124 active TIF districts capturing $1.36 billion in 2023, about 42 percent of all property-tax growth. Most TIF dollars have historically gone to downtown projects rather than the disinvested neighborhoods the program was originally meant to help.",
    source: "Cook County Clerk 2023 TIF Report",
    category: "finance",
    rarity: "common",
    cost: { power: 2 },
    fromYear: 1985,
    toYear: 2040,
    effect: {
      growth: 2,
      capital: 3,
      sustainability: -1,
      setFlag: "tif-active",
    },
    glossary: ["TIF"],
  },
  {
    id: "tif-affordable-housing",
    name: "Direct TIF to affordable housing",
    flavor: "Captured property tax pays for permanent affordable units.",
    description: "Spends TIF dollars on affordable construction. Cuts available capital but raises equity.",
    lore: "About 25 percent of Chicago TIF dollars go to housing in any given year, but only a small share of that is permanently affordable. Activists have pushed for a much higher share since the early 2010s.",
    source: "DePaul Institute for Housing Studies, TIF and Housing analyses",
    category: "finance",
    rarity: "uncommon",
    cost: { capital: 3, knowledge: 1 },
    requiresFlag: "tif-active",
    fromYear: 1990,
    toYear: 2040,
    effect: { equity: 4, growth: 1, heritage: 1 },
  },
  {
    id: "tif-sunset",
    name: "TIF sunset clause",
    flavor: "Roll back the TIF early. Property tax flows to schools again.",
    description: "Ends an active TIF. Restores tax base to CPS.",
    lore: "Chicago has surplused several TIFs early under public pressure, with funds returned to schools. The 2017 surplus alone returned about $200M to CPS.",
    source: "Civic Federation TIF Surplus reports",
    category: "finance",
    rarity: "uncommon",
    cost: { power: 4 },
    requiresFlag: "tif-active",
    fromYear: 1995,
    toYear: 2040,
    effect: { equity: 3, sustainability: 2, growth: -2 },
  },
  {
    id: "developer-impact-fee",
    name: "Developer impact fee",
    flavor: "New construction pays into a community-benefits fund.",
    description: "Charges new market-rate developments a per-unit fee.",
    lore: "Impact fees are widespread on the West Coast (San Francisco, Berkeley, Oakland). Chicago's ARO in-lieu fee functions similarly but is paid only by ARO-triggered developments, not all new construction.",
    source: "California impact fee studies, Lincoln Institute",
    category: "finance",
    rarity: "common",
    cost: { power: 2 },
    fromYear: 2000,
    toYear: 2040,
    effect: { equity: 2, capital: 2, growth: -1 },
  },
  {
    id: "vacancy-tax",
    name: "Vacant property tax",
    flavor: "Empty buildings pay a steep annual fee.",
    description: "Pressures absentee owners to sell or rehab.",
    lore: "Vancouver's Empty Homes Tax, started in 2017, brought thousands of vacant homes onto the rental market within two years. Oakland passed its own version in 2018.",
    source: "Vancouver Empty Homes Tax annual reports",
    category: "finance",
    rarity: "uncommon",
    cost: { power: 3 },
    fromYear: 2010,
    toYear: 2040,
    effect: {
      equity: 2,
      sustainability: 2,
      transformParcels: [
        { selector: "type:vacant", delta: { condition: 5 } },
      ],
    },
  },
  {
    id: "down-payment-assistance",
    name: "Down-payment assistance",
    flavor: "$30K toward first homes, no repayment required.",
    description: "Helps long-term renters become owners. Limited number of slots per year.",
    lore: "Chicago's Building Neighborhoods and Affordable Homes Program has provided down-payment assistance since the 1990s. The program has also been criticized for steering Black buyers into still-redlined neighborhoods.",
    source: "City of Chicago Department of Housing program reports",
    category: "finance",
    rarity: "uncommon",
    cost: { capital: 3, knowledge: 1 },
    fromYear: 1990,
    toYear: 2040,
    effect: { equity: 3, heritage: 1 },
  },
  {
    id: "redlining-investigation",
    name: "Investigate continued redlining",
    flavor: "Disparity studies, public hearings, news coverage.",
    description: "Forces banks to lend equitably. Slow but durable.",
    lore: "The 2018 Reveal investigation 'Kept Out' found significant ongoing lending discrimination in 61 metro areas including Chicago, despite the Fair Housing Act of 1968 and the Community Reinvestment Act of 1977.",
    source: "Reveal from the Center for Investigative Reporting, 'Kept Out' (2018)",
    category: "research",
    rarity: "uncommon",
    cost: { knowledge: 2, power: 2 },
    fromYear: 1980,
    toYear: 2040,
    effect: { equity: 3, knowledge: 1 },
    glossary: ["Redlining", "FHA"],
  },
  {
    id: "fund-cra-banks",
    name: "Recruit a CRA-active bank",
    flavor: "A community-development bank opens a Parkhaven branch.",
    description: "Improves access to credit. Reverses some long-term redlining.",
    lore: "Community Reinvestment Act ratings affect bank merger approval, which gives the federal government some leverage on local lending patterns. South Side Community Federal Credit Union and Self-Help Credit Union are examples of CRA-driven local lenders.",
    source: "FFIEC CRA examination data",
    category: "finance",
    rarity: "uncommon",
    cost: { capital: 2, trust: 2 },
    fromYear: 1980,
    toYear: 2040,
    effect: { equity: 3, growth: 2 },
  },

  /* ============================================================== *
   *  INFRASTRUCTURE                                                 *
   * ============================================================== */
  {
    id: "accept-expressway",
    name: "Accept the expressway",
    flavor: "Federal money. A six-lane corridor through the C-graded blocks.",
    description: "Demolishes 7 parcels. Brings jobs and air pollution.",
    lore: "The Federal-Aid Highway Act of 1956 funded the urban interstates. Mayor Daley widened the Dan Ryan in 1962 specifically to keep Black residents east of the white South Side. The expressway demolished thousands of housing units.",
    source: "Mohl, The Interstates and the Cities (2008)",
    category: "infrastructure",
    rarity: "uncommon",
    cost: { power: 2 },
    fromYear: 1956,
    toYear: 1975,
    effect: {
      growth: 4,
      capital: 4,
      heritage: -4,
      sustainability: -3,
      equity: -3,
      transformParcels: [
        { selector: "expressway-line", set: { type: "expressway", residents: 0, owner: "city" } },
      ],
      setFlag: "expressway-built",
    },
    glossary: ["Expressway"],
  },
  {
    id: "decline-expressway",
    name: "Decline the expressway",
    flavor: "Federal money walks. Parkhaven flagged uncooperative.",
    description: "Saves the parcels. Loses the funding.",
    lore: "Few cities successfully fought interstate routings, but those that did, like Greenwich Village under Jane Jacobs against the Lower Manhattan Expressway, preserved their neighborhood fabric.",
    source: "Jacobs, The Death and Life of Great American Cities (1961)",
    category: "infrastructure",
    rarity: "uncommon",
    cost: { power: 3, trust: 2 },
    fromYear: 1956,
    toYear: 1970,
    effect: { heritage: 4, equity: 3, capital: -2 },
  },
  {
    id: "transit-extension",
    name: "Red Line Extension station",
    flavor: "$1.2B, four years to build, 40 percent land-value bump.",
    description: "Adds a train station. Activates surrounding parcels.",
    lore: "The Red Line Extension cost $5.75B for 5.6 miles and four stations, fully funded by an FTA grant signed in December 2024. CTA projects $1.7B in associated real-estate activity. Without preservation overlays first, the activity becomes displacement.",
    source: "FTA Full Funding Grant Agreement (Dec 2024)",
    category: "transit",
    rarity: "rare",
    cost: { capital: 6, power: 3 },
    fromYear: 2025,
    toYear: 2040,
    effect: {
      growth: 5,
      sustainability: 4,
      equity: 1,
      transformParcels: [
        { selector: "first-of-type:vacant", set: { type: "transit", owner: "city" } },
      ],
      setFlag: "transit-extension",
    },
    glossary: ["RedLineExtension"],
  },
  {
    id: "bus-rapid-transit",
    name: "Bus rapid transit corridor",
    flavor: "Dedicated lanes, level boarding, signal priority.",
    description: "Faster bus service through the central blocks.",
    lore: "Cleveland's HealthLine BRT, opened 2008, generated $9.5B in adjacent investment over its first decade. Chicago's Ashland BRT was proposed in 2013 and has stalled.",
    source: "Institute for Transportation and Development Policy BRT studies",
    category: "transit",
    rarity: "uncommon",
    cost: { capital: 3, power: 2 },
    fromYear: 2010,
    toYear: 2040,
    effect: { sustainability: 3, growth: 2, equity: 1 },
  },
  {
    id: "protected-bike-lanes",
    name: "Protected bike network",
    flavor: "Concrete bollards, not paint.",
    description: "Adds safe cycling infrastructure. Reduces car dependence.",
    lore: "Protected bike lanes are correlated with significant drops in cyclist fatalities. Chicago has built a partial network since 2011. Coverage is heavily concentrated on the North Side.",
    source: "City of Chicago Streets for Cycling Plan",
    category: "infrastructure",
    rarity: "common",
    cost: { capital: 2, power: 1 },
    fromYear: 2010,
    toYear: 2040,
    effect: { sustainability: 3, equity: 1 },
  },
  {
    id: "alley-permeable",
    name: "Permeable alley program",
    flavor: "Replace asphalt with permeable pavers.",
    description: "Reduces flooding, lowers urban heat.",
    lore: "Chicago's Green Alley Program, launched 2006, has converted hundreds of alleys to permeable surfaces. The city saves on stormwater management and reduces basement flooding.",
    source: "City of Chicago Department of Transportation Green Alley Handbook",
    category: "environment",
    rarity: "common",
    cost: { capital: 1 },
    fromYear: 2005,
    toYear: 2040,
    effect: { sustainability: 3 },
  },
  {
    id: "tree-canopy-program",
    name: "Restore the tree canopy",
    flavor: "10,000 trees over five years.",
    description: "Reduces summer heat, cleans air, raises adjacent property values.",
    lore: "Chicago's tree canopy is heavily concentrated in wealthy North Side neighborhoods. South and West Side blocks have measurably hotter summer temperatures, contributing to higher emergency-department visits during heat waves.",
    source: "Chicago Region Trees Initiative tree canopy assessment",
    category: "environment",
    rarity: "common",
    cost: { capital: 2, knowledge: 1 },
    fromYear: 1980,
    toYear: 2040,
    effect: { sustainability: 4, equity: 2 },
  },

  /* ============================================================== *
   *  ORGANIZING                                                     *
   * ============================================================== */
  {
    id: "tenant-union",
    name: "Support a tenant union",
    flavor: "Building-by-building organizing, then citywide.",
    description: "Builds organized power. Cuts evictions, raises trust slowly.",
    lore: "The Lifton Building tenants in Uptown Chicago organized one of the city's first known tenant unions in 1969. The Autonomous Tenants Union, active in Albany Park since 2017, has won several rent strikes.",
    source: "Autonomous Tenants Union case studies",
    category: "organizing",
    rarity: "uncommon",
    cost: { trust: 2, power: 1 },
    fromYear: 1965,
    toYear: 2040,
    effect: { equity: 3, trust: 2 },
  },
  {
    id: "contract-buyers-strike",
    name: "Back the Contract Buyers League",
    flavor: "500 families withhold contract payments.",
    description: "Forces speculator renegotiations. Some families keep their homes.",
    lore: "The Contract Buyers League's 1968-1971 strike was the largest organized resistance to predatory home-sale practices in U.S. history. Some families won renegotiated terms. Many lost their homes anyway.",
    source: "Satter, Family Properties (2009), chs. 9-11",
    category: "organizing",
    rarity: "rare",
    cost: { trust: 3, power: 2 },
    fromYear: 1968,
    toYear: 1972,
    effect: { equity: 4, heritage: 3, knowledge: 1 },
    glossary: ["ContractBuying"],
  },
  {
    id: "fair-housing-tester",
    name: "Fair-housing tester program",
    flavor: "Paired tests catch landlords discriminating.",
    description: "Documents and prosecutes housing discrimination.",
    lore: "Tester programs send paired auditors of different races to inquire about housing. The systematic differences they document have been the basis for many federal fair housing cases. The Chicago Lawyers' Committee for Civil Rights ran an active tester program through the 2010s.",
    source: "HUD Fair Housing Testing Program guidance",
    category: "research",
    rarity: "uncommon",
    cost: { power: 2, knowledge: 2 },
    fromYear: 1968,
    toYear: 2040,
    effect: { equity: 3, knowledge: 1 },
  },
  {
    id: "youth-research-cohort",
    name: "Youth research cohort",
    flavor: "High-school students lead the next round of research.",
    description: "Builds long-term knowledge. Pays back over the next decade.",
    lore: "Rooted Forward's own model. Youth-led research cohorts in Chicago, Detroit, and Philadelphia have produced policy briefs cited by city councils.",
    source: "Rooted Forward research cohort reports",
    category: "research",
    rarity: "uncommon",
    cost: { trust: 2, knowledge: 1 },
    fromYear: 2015,
    toYear: 2040,
    effect: { equity: 2, heritage: 2, knowledge: 3, trust: 1 },
  },
  {
    id: "community-benefits-agreement",
    name: "Community benefits agreement",
    flavor: "Developer signs an enforceable contract with the neighborhood.",
    description: "Major project must hire locally, fund affordable units, or build amenities.",
    lore: "The Staples Center CBA in Los Angeles (2001) was the first major community benefits agreement and became a template. Chicago has seen smaller CBAs around the Obama Presidential Center and the United Center.",
    source: "Partnership for Working Families CBA toolkit",
    category: "organizing",
    rarity: "rare",
    cost: { power: 3, trust: 3, knowledge: 1 },
    fromYear: 2000,
    toYear: 2040,
    effect: { equity: 4, growth: 1, heritage: 2 },
  },
  {
    id: "anti-displacement-coalition",
    name: "Anti-displacement coalition",
    flavor: "Pilsen Alliance, LSNA, Logan Square Neighborhood Association.",
    description: "Cross-neighborhood coalition. Long-term political muscle.",
    lore: "The Pilsen Alliance and LSNA have been continuously active since the 1970s, pushing back on displacement pressure and shaping Chicago's affordable housing policy.",
    source: "Pilsen Alliance / LSNA published advocacy materials",
    category: "organizing",
    rarity: "rare",
    cost: { trust: 3, power: 2 },
    fromYear: 1975,
    toYear: 2040,
    effect: { equity: 3, heritage: 3, trust: 2 },
  },

  /* ============================================================== *
   *  COMMERCE & CULTURE                                             *
   * ============================================================== */
  {
    id: "small-business-grant",
    name: "Small-business grants",
    flavor: "$25K microgrants to neighborhood shops.",
    description: "Stabilizes corner stores, bakeries, barbershops.",
    lore: "The Neighborhood Opportunity Fund, established in Chicago in 2016, taxes downtown developers to fund neighborhood-business grants on the South and West Sides.",
    source: "City of Chicago Neighborhood Opportunity Fund reports",
    category: "commerce",
    rarity: "common",
    cost: { capital: 2, trust: 1 },
    fromYear: 1985,
    toYear: 2040,
    effect: { equity: 2, heritage: 2, growth: 1 },
  },
  {
    id: "cultural-corridor",
    name: "Designate a cultural corridor",
    flavor: "Murals, banners, cultural-business protections.",
    description: "Recognizes and protects cultural identity. Reduces displacement of cultural institutions.",
    lore: "Pilsen's 18th Street and the Chinatown gateway are examples. Cultural-corridor designations don't stop displacement on their own, but they create a political and aesthetic baseline that organized residents can defend.",
    source: "City of Chicago cultural plan",
    category: "culture",
    rarity: "uncommon",
    cost: { trust: 2, knowledge: 1 },
    fromYear: 1990,
    toYear: 2040,
    effect: { heritage: 4, equity: 1 },
  },
  {
    id: "neighborhood-mural",
    name: "Commission a public mural",
    flavor: "Hector Duarte, William Walker, the next generation.",
    description: "Adds a mural that builds community memory.",
    lore: "Chicago's mural movement dates to the late 1960s, with William Walker's 'Wall of Respect' (1967) at 43rd and Langley as the foundational piece. Pilsen's mural tradition is one of the densest in the country.",
    source: "Public Art Chicago / Chicago Mural Project archives",
    category: "culture",
    rarity: "common",
    cost: { capital: 1, trust: 1 },
    fromYear: 1967,
    toYear: 2040,
    effect: {
      heritage: 3,
      transformParcels: [
        { selector: "first-of-type:vacant", set: { type: "mural" } },
      ],
    },
  },
  {
    id: "branch-library",
    name: "Branch library",
    flavor: "A new Carnegie-style library opens.",
    description: "Free internet, after-school programs, civic anchor.",
    lore: "Chicago Public Library has 81 branches; the South Side and West Side have systematically smaller and older branches than the North. Investments in branch libraries correlate with measurable improvements in adjacent property stability.",
    source: "Chicago Public Library system data",
    category: "schools",
    rarity: "uncommon",
    cost: { capital: 3, knowledge: 1 },
    fromYear: 1940,
    toYear: 2040,
    effect: {
      heritage: 2,
      sustainability: 2,
      transformParcels: [
        { selector: "first-of-type:vacant", set: { type: "library" } },
      ],
    },
  },
  {
    id: "community-clinic",
    name: "Community health clinic",
    flavor: "Free or sliding-scale primary care.",
    description: "Adds clinic; long-term improvement in resident health.",
    lore: "Chicago's Federally Qualified Health Centers serve over a million patients annually. The South Side network, including TCA Health and Friend Family Health Center, has long waitlists.",
    source: "Illinois Primary Health Care Association reports",
    category: "schools",
    rarity: "uncommon",
    cost: { capital: 3, trust: 1 },
    fromYear: 1965,
    toYear: 2040,
    effect: {
      equity: 3,
      sustainability: 2,
      transformParcels: [
        { selector: "first-of-type:vacant", set: { type: "clinic" } },
      ],
    },
  },
  {
    id: "community-garden",
    name: "Community garden",
    flavor: "Vacant lot, raised beds, neighborhood plots.",
    description: "Activates a vacant lot. Modest food security gain.",
    lore: "Chicago's NeighborSpace, a nonprofit land trust for community gardens, holds about 130 sites. Garden sites are correlated with reduced crime and higher neighborhood satisfaction in adjacent blocks.",
    source: "NeighborSpace annual reports",
    category: "environment",
    rarity: "common",
    cost: { trust: 1, capital: 1 },
    fromYear: 1980,
    toYear: 2040,
    effect: {
      sustainability: 2,
      heritage: 1,
      transformParcels: [
        { selector: "first-of-type:vacant", set: { type: "community-garden" } },
      ],
    },
  },

  /* ============================================================== *
   *  SCHOOLS                                                        *
   * ============================================================== */
  {
    id: "rebuild-school",
    name: "Rebuild a neighborhood school",
    flavor: "New building, new lab, new gym, same kids.",
    description: "Renovates the local elementary school.",
    lore: "Chicago closed 50 neighborhood schools in 2013, the largest single round of school closures in U.S. history. Almost all closures were on the South and West Sides. The closures were challenged in federal court and the schools were never reopened.",
    source: "Chicago Public Schools 2013 school closure documentation",
    category: "schools",
    rarity: "uncommon",
    cost: { capital: 4, power: 1 },
    fromYear: 1960,
    toYear: 2040,
    effect: {
      equity: 3,
      heritage: 2,
      transformParcels: [
        { selector: "type:school", delta: { condition: 30 } },
      ],
    },
  },
  {
    id: "fight-school-closure",
    name: "Fight a school closure",
    flavor: "Hunger strike, rally at city hall.",
    description: "Keeps a neighborhood school open.",
    lore: "The 2015 Dyett High School hunger strike in Bronzeville lasted 34 days and forced CPS to keep the school open. Twelve people went on the strike, mostly grandmothers and teachers.",
    source: "Coverage of the Dyett hunger strike, Chicago Tribune 2015",
    category: "organizing",
    rarity: "uncommon",
    cost: { trust: 3, power: 2 },
    fromYear: 1990,
    toYear: 2040,
    effect: { equity: 3, heritage: 4, knowledge: 1 },
  },
  {
    id: "fund-schools-fairly",
    name: "Equalize CPS funding",
    flavor: "End the per-pupil funding gap.",
    description: "Shifts resources to underfunded schools.",
    lore: "Chicago Public Schools has one of the largest per-pupil funding gaps in the country, driven by reliance on local property tax. Black and Latino students attend schools funded at thousands of dollars less per pupil than majority-white CPS schools.",
    source: "EdBuild, '$23 Billion' (2019)",
    category: "schools",
    rarity: "rare",
    cost: { power: 4, knowledge: 2 },
    fromYear: 1985,
    toYear: 2040,
    effect: { equity: 5 },
  },

  /* ============================================================== *
   *  ENVIRONMENT                                                    *
   * ============================================================== */
  {
    id: "industrial-cleanup",
    name: "Brownfield cleanup",
    flavor: "EPA Superfund, soil remediation, two years.",
    description: "Restores contaminated land for use.",
    lore: "Chicago has dozens of brownfield sites, mostly from industrial uses on the South and West Sides. The federal Brownfields program funds cleanup. Once cleaned, the sites can host housing, parks, or commercial use.",
    source: "U.S. EPA Brownfields Program",
    category: "environment",
    rarity: "uncommon",
    cost: { capital: 4, knowledge: 1 },
    fromYear: 1985,
    toYear: 2040,
    effect: {
      sustainability: 4,
      transformParcels: [
        { selector: "type:industrial", set: { type: "vacant" } },
      ],
    },
  },
  {
    id: "rooftop-solar",
    name: "Rooftop solar incentives",
    flavor: "Federal tax credit plus city rebate.",
    description: "Lowers utility bills, cuts emissions.",
    lore: "The Inflation Reduction Act of 2022 expanded federal solar incentives substantially. Chicago has historically lagged Sunbelt cities on adoption. Rebates and bulk-buy programs have accelerated installations on the West Side.",
    source: "Inflation Reduction Act, 2022",
    category: "environment",
    rarity: "common",
    cost: { capital: 2, knowledge: 1 },
    fromYear: 2020,
    toYear: 2040,
    effect: { sustainability: 3, equity: 1 },
  },
  {
    id: "lead-pipe-replacement",
    name: "Replace lead service lines",
    flavor: "Federal Lead Service Line Replacement program.",
    description: "Replaces lead pipes to homes. Long-term health win.",
    lore: "Chicago has the most lead service lines of any U.S. city, an estimated 400,000. Federal lead-pipe replacement funding from the 2021 infrastructure law has begun a multi-decade program.",
    source: "Bipartisan Infrastructure Law (2021)",
    category: "environment",
    rarity: "uncommon",
    cost: { capital: 3 },
    fromYear: 2022,
    toYear: 2040,
    effect: { sustainability: 4, equity: 3 },
  },

  /* ============================================================== *
   *  RESEARCH                                                       *
   * ============================================================== */
  {
    id: "publish-disparity-study",
    name: "Publish a disparity study",
    flavor: "Numbers in print. Hard to ignore.",
    description: "Quantifies racial disparities in lending, contracting, schools.",
    lore: "Disparity studies are required for cities to defend race-conscious contracting programs after Croson v. City of Richmond (1989). Chicago publishes one every few years.",
    source: "City of Chicago Department of Procurement Services disparity studies",
    category: "research",
    rarity: "uncommon",
    cost: { capital: 1, knowledge: 2 },
    fromYear: 1990,
    toYear: 2040,
    effect: { equity: 2, knowledge: 2 },
  },
  {
    id: "document-history",
    name: "Document the neighborhood history",
    flavor: "Oral histories, archived photos, walking-tour scripts.",
    description: "Builds heritage durably. Slow-burn equity gain.",
    lore: "The Chicago Public Library's StoryCorps initiative and the South Side Home Movie Project have preserved oral and visual histories that would otherwise be lost.",
    source: "Chicago Public Library StoryCorps; South Side Home Movie Project",
    category: "research",
    rarity: "common",
    cost: { trust: 1, knowledge: 1 },
    fromYear: 1990,
    toYear: 2040,
    effect: { heritage: 3, knowledge: 2 },
  },

  /* ============================================================== *
   *  AGGRESSIVE / SHADOW PLAYS                                       *
   * ============================================================== */
  {
    id: "speculator-buyout",
    name: "Court a speculator",
    flavor: "Quietly invite outside capital. Watch values rise.",
    description: "Speculator buys 5 parcels. Capital gain. Trust loss.",
    lore: "Tax-lien speculators have bought thousands of South and West Side parcels since the 2008 crisis, often holding them empty until prices rise. The Cook County Land Bank Authority was created in 2013 in part to push back on this practice.",
    source: "Cook County Land Bank Authority annual reports",
    category: "finance",
    rarity: "common",
    cost: { capital: 0 },
    fromYear: 2010,
    toYear: 2040,
    effect: {
      capital: 4,
      equity: -3,
      heritage: -2,
      transformParcels: [
        { selector: "random:5", set: { owner: "speculator" } },
      ],
    },
  },
  {
    id: "luxury-tower-deal",
    name: "Approve a luxury tower",
    flavor: "Gleaming glass, 80 units, no affordability.",
    description: "Big tax bump. Catalyzes gentrification of adjacent blocks.",
    lore: "Luxury towers without affordability requirements were the default outcome of Chicago's pre-2015 zoning regime. The 2021 ARO update addressed this in displacement-risk zones.",
    source: "Chicago Department of Housing market-rate development data",
    category: "housing",
    rarity: "common",
    cost: { power: 2 },
    fromYear: 2010,
    toYear: 2040,
    effect: {
      capital: 3,
      growth: 4,
      equity: -3,
      heritage: -2,
      transformParcels: [
        { selector: "first-of-type:vacant", set: { type: "tower", residents: 80, owner: "developer" } },
      ],
    },
  },
  {
    id: "evict-noncompliant-tenants",
    name: "Aggressive code enforcement",
    flavor: "Issue building citations. Push out absentee landlords.",
    description: "Drives renovation. Some legitimate landlords lose buildings too.",
    lore: "Aggressive code enforcement is a documented gentrification tactic. It can accelerate displacement under the cover of public-safety concerns. Code-enforcement displacement was a major theme in 1980s gentrification studies of Park Slope, Brooklyn.",
    source: "Smith, The New Urban Frontier (1996)",
    category: "zoning",
    rarity: "uncommon",
    cost: { power: 2 },
    fromYear: 1980,
    toYear: 2040,
    effect: {
      growth: 2,
      equity: -2,
      capital: 2,
    },
  },
  {
    id: "sign-summit-agreement",
    name: "Sign the Summit Agreement",
    flavor: "Daley calls it a victory. The marches stop.",
    description: "Quiet on the streets, no enforcement teeth.",
    lore: "The 1966 Summit Agreement ended the Chicago Open Housing Movement marches. The agreement contained vague language and no enforcement mechanism. Daley signed and then did not enforce it.",
    source: "Garrow, Bearing the Cross (1986); Ralph, Northern Protest (1993)",
    category: "organizing",
    rarity: "rare",
    cost: { power: 1 },
    fromYear: 1966,
    toYear: 1968,
    effect: { capital: 2, equity: -2, heritage: -1 },
  },

  /* ============================================================== *
   *  RARE / LATE GAME                                               *
   * ============================================================== */
  {
    id: "preservation-overlay-rle",
    name: "Lock in preservation before the RLE",
    flavor: "Pass the overlays. Then announce the train.",
    description: "Rights of first refusal, demolition holds, anti-flipping. Then transit.",
    lore: "Pre-emptive preservation before transit announcements is the most effective known anti-displacement tactic. Few American cities have done it. Boston's Fairmount Indigo CDC partnerships and the LA Metro Transit-Oriented Communities program are partial examples.",
    source: "Pollack and Bluestone, 'Maintaining Diversity in America's Transit-Rich Neighborhoods' (2010)",
    category: "preservation",
    rarity: "legendary",
    cost: { power: 4, trust: 4, knowledge: 2 },
    fromYear: 2020,
    toYear: 2035,
    effect: {
      equity: 6,
      heritage: 4,
      sustainability: 3,
      setFlag: "preservation-overlay",
    },
  },
  {
    id: "regional-fair-share",
    name: "Regional fair-share housing",
    flavor: "Suburbs absorb their share of affordable units.",
    description: "Spreads the affordability burden across the metro.",
    lore: "New Jersey's Mount Laurel doctrine, established 1975 and codified in 1985, requires every municipality to plan for its 'fair share' of regional affordable housing. The Chicago metro has nothing comparable.",
    source: "Mount Laurel Doctrine, NJ Supreme Court",
    category: "finance",
    rarity: "legendary",
    cost: { power: 5, knowledge: 3 },
    fromYear: 2000,
    toYear: 2040,
    effect: { equity: 7, growth: 1 },
  },
  {
    id: "reparations-fund",
    name: "Local reparations fund",
    flavor: "Targeted compensation for descendants of contract buyers and demolished blocks.",
    description: "Cash transfers and homeownership support.",
    lore: "Evanston, Illinois, established the country's first municipal reparations program in 2021, offering $25,000 housing grants to qualifying Black residents. Chicago has discussed but not enacted a similar program.",
    source: "City of Evanston Restorative Housing Program",
    category: "finance",
    rarity: "legendary",
    cost: { power: 5, capital: 5, knowledge: 2 },
    fromYear: 2020,
    toYear: 2040,
    effect: { equity: 8, heritage: 4 },
  },

  /* ============================================================== *
   *  CONTINUE - more cards                                           *
   * ============================================================== */
  {
    id: "ban-source-discrimination",
    name: "Ban source-of-income discrimination",
    flavor: "Landlords cannot refuse Section 8 vouchers.",
    description: "Expands voucher usability across the city.",
    lore: "Chicago passed source-of-income protection in 1990, one of the earliest such ordinances. Enforcement remains a challenge. The 2020 federal HUD rule clarified that source-of-income discrimination disparately impacts protected classes.",
    source: "Chicago Human Rights Ordinance, 1990 amendment",
    category: "organizing",
    rarity: "common",
    cost: { power: 2 },
    fromYear: 1990,
    toYear: 2040,
    effect: { equity: 3 },
    glossary: ["Section8"],
  },
  {
    id: "co-op-conversion",
    name: "Co-op conversion grants",
    flavor: "Help tenants buy their building together.",
    description: "Converts rental buildings to limited-equity co-ops.",
    lore: "Chicago has a smaller cooperative housing sector than New York or San Francisco. Limited-equity co-ops cap resale prices to maintain affordability across generations.",
    source: "Cooperative Development Foundation; Chicago co-op studies",
    category: "housing",
    rarity: "uncommon",
    cost: { capital: 3, trust: 2 },
    fromYear: 1980,
    toYear: 2040,
    effect: { equity: 4, heritage: 3 },
  },
  {
    id: "missing-middle-housing",
    name: "Missing middle housing",
    flavor: "Two-flats, three-flats, courtyards, fourplexes.",
    description: "Add gentle density. Adds capacity without towers.",
    lore: "The 'missing middle' framework, popularized by architect Daniel Parolek, refers to building types between single-family and high-rise. Chicago historically had abundant missing-middle stock; downzoning in the 1950s removed much of it.",
    source: "Parolek, Missing Middle Housing (2020)",
    category: "housing",
    rarity: "uncommon",
    cost: { capital: 3, power: 2 },
    fromYear: 2010,
    toYear: 2040,
    effect: { growth: 3, sustainability: 2, equity: 2 },
  },
  {
    id: "neighborhood-grocer",
    name: "Recruit a grocery store",
    flavor: "Full-service supermarket fills a food desert.",
    description: "Health and quality-of-life gain. Anchor for the commercial strip.",
    lore: "South and West Side Chicago has been documented as one of the largest urban food deserts in the country. The Healthy Food Financing Initiative provides federal funds to recruit grocers to underserved areas.",
    source: "USDA Healthy Food Financing Initiative",
    category: "commerce",
    rarity: "uncommon",
    cost: { capital: 3, trust: 1 },
    fromYear: 2010,
    toYear: 2040,
    effect: { equity: 3, sustainability: 2, growth: 1 },
  },
  {
    id: "block-club-revival",
    name: "Block club revival",
    flavor: "Front-yard meetings, gardening days, holiday parties.",
    description: "Builds resident ties. Slow but compounding equity.",
    lore: "Chicago's block club tradition dates to the early 20th century. The Chicago Department of Family and Support Services has maintained block-club registration through every administration since the 1960s.",
    source: "City of Chicago Block Club registration data",
    category: "organizing",
    rarity: "common",
    cost: { trust: 2 },
    fromYear: 1940,
    toYear: 2040,
    effect: { heritage: 2, equity: 1, trust: 2 },
  },
  {
    id: "participatory-budgeting",
    name: "Participatory budgeting",
    flavor: "Residents decide how to spend the menu money.",
    description: "Spends $1M on resident-chosen projects.",
    lore: "Chicago alderman Joe Moore (49th Ward) introduced the city's first participatory budgeting process in 2009. About a dozen wards have used it since. The process is associated with measurable increases in civic trust.",
    source: "Participatory Budgeting Project Chicago case study",
    category: "organizing",
    rarity: "uncommon",
    cost: { trust: 2, power: 1 },
    fromYear: 2009,
    toYear: 2040,
    effect: { equity: 2, heritage: 2, trust: 2 },
  },
  {
    id: "public-safety-investment",
    name: "Community safety investment",
    flavor: "Violence interrupters, after-school programs, mental health teams.",
    description: "Non-police safety strategies.",
    lore: "Cure Violence (originally CeaseFire), founded by Gary Slutkin in Chicago in 2000, treats violence as a public-health problem. The model has been replicated in dozens of cities and is associated with double-digit reductions in shootings in target areas.",
    source: "Cure Violence outcome studies",
    category: "organizing",
    rarity: "uncommon",
    cost: { capital: 3, trust: 2 },
    fromYear: 2000,
    toYear: 2040,
    effect: { equity: 3, heritage: 2, sustainability: 1 },
  },
  {
    id: "mortgage-counseling",
    name: "First-time homebuyer counseling",
    flavor: "Eight-hour course, certified counselors.",
    description: "Improves loan terms, reduces foreclosure risk.",
    lore: "Pre-purchase homebuyer counseling, required for many subsidized mortgage programs, is associated with significantly lower foreclosure rates. The Neighborhood Housing Services of Chicago has been a major provider since the 1970s.",
    source: "Neighborhood Housing Services of Chicago program data",
    category: "finance",
    rarity: "common",
    cost: { capital: 1, knowledge: 1 },
    fromYear: 1975,
    toYear: 2040,
    effect: { equity: 2 },
  },
  {
    id: "challenge-tax-assessment",
    name: "Challenge property assessments",
    flavor: "Cook County over-assesses Black neighborhoods. Dispute it.",
    description: "Lowers property tax burden for Black homeowners.",
    lore: "A 2017 ProPublica investigation found that Cook County's property tax assessments systematically over-assessed homes in Black and Latino neighborhoods relative to white ones. The county began reform after the report.",
    source: "ProPublica, 'The Tax Divide' (2017)",
    category: "research",
    rarity: "uncommon",
    cost: { knowledge: 2, power: 1 },
    fromYear: 2015,
    toYear: 2040,
    effect: { equity: 3 },
  },
  {
    id: "ai-disclosure-ordinance",
    name: "AI tenant-screening disclosure",
    flavor: "Algorithms that deny rentals must explain themselves.",
    description: "Reduces opaque algorithmic discrimination.",
    lore: "Tenant-screening algorithms have been documented to systematically discriminate against Black applicants and voucher holders. NYC Local Law 144 (2021) requires algorithmic-employment audits; tenant screening has lagged.",
    source: "Reveal CIR investigation of tenant-screening algorithms (2020)",
    category: "research",
    rarity: "rare",
    cost: { knowledge: 3, power: 2 },
    fromYear: 2022,
    toYear: 2040,
    effect: { equity: 3, knowledge: 1 },
  },
  {
    id: "community-energy-project",
    name: "Community solar project",
    flavor: "Residents subscribe to a shared solar array.",
    description: "Lowers utility bills. Builds renewable capacity.",
    lore: "Illinois passed the Future Energy Jobs Act in 2016 and the Climate and Equitable Jobs Act in 2021, which authorized and expanded community solar. Chicago participation has been slower than expected.",
    source: "Illinois Climate and Equitable Jobs Act (2021)",
    category: "environment",
    rarity: "uncommon",
    cost: { capital: 2, knowledge: 1 },
    fromYear: 2018,
    toYear: 2040,
    effect: { sustainability: 4, equity: 2 },
  },
  {
    id: "youth-employment",
    name: "Youth summer employment",
    flavor: "10,000 summer jobs.",
    description: "Pays young residents to work in the neighborhood.",
    lore: "Chicago's One Summer Chicago program has placed tens of thousands of young people in paid summer work. Studies have linked participation to large reductions in violent-crime arrests for participants.",
    source: "One Summer Chicago program evaluations",
    category: "schools",
    rarity: "common",
    cost: { capital: 2 },
    fromYear: 2011,
    toYear: 2040,
    effect: { equity: 3, heritage: 1 },
  },
  {
    id: "transit-fare-equity",
    name: "Free transit for low-income riders",
    flavor: "Reduced or free Ventra cards.",
    description: "Removes the fare barrier for the most cost-burdened.",
    lore: "Boston's MBTA piloted free buses on the Route 28 corridor in 2022; ridership rose, fare evasion fell, dwell times shortened. Chicago has discussed but not adopted free transit for low-income riders.",
    source: "MBTA Route 28 Free Bus Pilot evaluation (2022)",
    category: "transit",
    rarity: "rare",
    cost: { capital: 4, power: 2 },
    fromYear: 2022,
    toYear: 2040,
    effect: { equity: 4, sustainability: 2 },
  },
  {
    id: "restorative-zoning",
    name: "Restorative zoning",
    flavor: "Zoning bonuses tied to local hiring and affordable units.",
    description: "Aligns developer incentives with community needs.",
    lore: "Restorative-zoning frameworks tie any zoning bonus (height, density, FAR) to verified community benefits. Variants exist in Cambridge, Massachusetts and Pittsburgh, Pennsylvania.",
    source: "Cambridge inclusionary housing program documentation",
    category: "zoning",
    rarity: "rare",
    cost: { knowledge: 2, power: 3 },
    fromYear: 2015,
    toYear: 2040,
    effect: { equity: 4, growth: 1, sustainability: 1 },
  },
  {
    id: "art-in-public-housing",
    name: "Art-in-public-housing program",
    flavor: "Murals, sculpture, music in CHA developments.",
    description: "Builds heritage in housing the city often treats as disposable.",
    lore: "The CHA's percent-for-art program has commissioned dozens of works since the 1990s. The murals at the former Stateway Gardens and at Lathrop Homes are notable.",
    source: "CHA Percent-for-Art program",
    category: "culture",
    rarity: "common",
    cost: { capital: 1, trust: 1 },
    fromYear: 1990,
    toYear: 2040,
    effect: { heritage: 3, equity: 1 },
  },
  {
    id: "mutual-aid-network",
    name: "Mutual aid network",
    flavor: "Block-by-block, neighbor-to-neighbor support.",
    description: "Builds informal safety net.",
    lore: "Chicago saw a major expansion of mutual-aid networks during the COVID-19 pandemic in 2020. Pilsen Mutual Aid and Logan Square Mutual Aid have continued past the pandemic emergency.",
    source: "Pilsen Mutual Aid; Logan Square Mutual Aid public reports",
    category: "organizing",
    rarity: "common",
    cost: { trust: 2 },
    fromYear: 2020,
    toYear: 2040,
    effect: { heritage: 2, equity: 2, trust: 2 },
  },
  {
    id: "green-infrastructure-bond",
    name: "Green infrastructure bond",
    flavor: "$50M general obligation bond for green works.",
    description: "Funds bioswales, permeable surfaces, urban forestry.",
    lore: "Philadelphia's Green City, Clean Waters program, launched 2011, is the most cited urban green-infrastructure case in the U.S. The program meets EPA stormwater requirements without traditional gray infrastructure.",
    source: "Philadelphia Water Department Green City, Clean Waters reports",
    category: "environment",
    rarity: "uncommon",
    cost: { capital: 4, power: 2 },
    fromYear: 2010,
    toYear: 2040,
    effect: { sustainability: 5, growth: 1 },
  },
  {
    id: "no-net-loss-policy",
    name: "No net loss of affordability",
    flavor: "Every affordable unit demolished must be replaced.",
    description: "Prevents losing affordable units to redevelopment.",
    lore: "San Francisco's no-net-loss housing policies date to the late 1970s and have shaped how the city approves market-rate development. Chicago has discussed but not enacted no-net-loss for affordable housing.",
    source: "San Francisco Planning Department no-net-loss documentation",
    category: "housing",
    rarity: "rare",
    cost: { power: 4, knowledge: 1 },
    fromYear: 2010,
    toYear: 2040,
    effect: { equity: 4, heritage: 3 },
  },
  {
    id: "maker-space",
    name: "Public maker space",
    flavor: "Tools, training, micro-fabrication.",
    description: "Lowers the cost of starting a small business.",
    lore: "Chicago's Manufacturing Renaissance has worked since the 1980s to maintain industrial jobs in the city. Maker spaces and micro-manufacturing facilities have been a recent component.",
    source: "Manufacturing Renaissance Chicago program reports",
    category: "commerce",
    rarity: "common",
    cost: { capital: 2, knowledge: 1 },
    fromYear: 2010,
    toYear: 2040,
    effect: { growth: 2, equity: 2 },
  },
  {
    id: "ban-no-knock-warrants",
    name: "Ban no-knock warrants",
    flavor: "Police must announce themselves.",
    description: "Reduces violent encounters during searches.",
    lore: "Chicago restricted no-knock warrants in 2021 after the death of Anjanette Young in a wrong-address raid. The reform built on a longer national debate after the killing of Breonna Taylor in Louisville.",
    source: "City of Chicago Department of Police search warrant reform 2021",
    category: "organizing",
    rarity: "common",
    cost: { power: 2, trust: 1 },
    fromYear: 2021,
    toYear: 2040,
    effect: { equity: 3, trust: 1 },
  },

  /* ============================================================== *
   *  EXPANSION PACK: TRADE-OFF AND DELAYED-COST CARDS               *
   * ============================================================== */

  /* ---------- Trap cards: look strong, hurt later ---------- */
  {
    id: "tax-abatement-bait",
    name: "Tax abatement for big tenants",
    flavor: "Twenty-year break to keep the headquarters in town.",
    description: "Big short-term Capital, but starves the property-tax base for two decades.",
    lore: "Chicago's 6b property tax incentive for industrial properties cuts assessments to 10% for the first 10 years, doubling at year 11, full at 13. Critics argue these abatements transfer billions out of the school fund.",
    source: "Cook County 6b classification rules; Civic Federation analyses",
    category: "finance",
    rarity: "uncommon",
    cost: { power: 2 },
    fromYear: 1980,
    toYear: 2040,
    effect: { capital: 4, growth: 2, equity: -2, sustainability: -1, setFlag: "tax-abatement-active", triggerEvent: "schools-defunded" },
  },
  {
    id: "fast-permit-luxury",
    name: "Fast-track luxury permits",
    flavor: "Cut the review timeline. Shovels go in by Q3.",
    description: "Rapid Growth and Capital. Sets a gentrification flag that hits adjacent blocks later.",
    lore: "When Chicago waived 90-day environmental reviews for a 2018 luxury tower, displacement pressure on the adjacent rental blocks measurably accelerated within 18 months.",
    source: "Chicago Cityscape permit-tracking reports",
    category: "zoning",
    rarity: "common",
    cost: { power: 1, capital: 1 },
    fromYear: 1990,
    toYear: 2040,
    effect: { growth: 4, capital: 3, equity: -3, heritage: -2, setFlag: "fast-track-permits" },
  },
  {
    id: "convention-bid",
    name: "Bid for a major convention",
    flavor: "Big show, big build, big hotel rooms.",
    description: "Boom now, hangover later. Capital up, displacement risk up.",
    lore: "Chicago has spent hundreds of millions chasing the Olympics, the DNC, and other mega-events. McCormick Place expansions displaced 15,000 people in the South Loop between 1958 and 1996.",
    source: "Crain's Chicago Business convention spend coverage",
    category: "infrastructure",
    rarity: "uncommon",
    cost: { capital: 3, power: 2 },
    fromYear: 1985,
    toYear: 2040,
    effect: { growth: 4, capital: 3, heritage: -3, equity: -2 },
  },
  {
    id: "police-expansion",
    name: "Expand the police district",
    flavor: "Two new stations, three hundred new officers.",
    description: "Order rises short-term, trust collapses long-term.",
    lore: "Studies of large-scale policing investments find short-term reductions in some crime types but long-term erosion of community trust, especially in over-policed neighborhoods.",
    source: "Sherman et al., 'The Effects of Increased Police Strength' (2014)",
    category: "infrastructure",
    rarity: "common",
    cost: { capital: 3, power: 2 },
    fromYear: 1965,
    toYear: 2040,
    effect: { growth: 1, sustainability: 1, equity: -3, trust: -2, setFlag: "policing-heavy" },
  },
  {
    id: "casino-license",
    name: "Approve a riverside casino",
    flavor: "Tax revenue, jobs, and a steady stream of late-night noise.",
    description: "Huge Capital influx with social costs that show up later.",
    lore: "Bally's Chicago Casino, opened in stages 2023-2026, was projected to generate $200M annual tax revenue. Public-health researchers flagged increased gambling addiction and household financial stress.",
    source: "City of Chicago Casino RFP 2022; American Gaming Association data",
    category: "commerce",
    rarity: "rare",
    cost: { power: 4 },
    fromYear: 2020,
    toYear: 2040,
    effect: { capital: 6, growth: 3, equity: -3, sustainability: -2, heritage: -1 },
  },
  {
    id: "remove-ada-curb-ramps",
    name: "Defer ADA curb-ramp upgrades",
    flavor: "Save the line item. Cite budget pressure.",
    description: "Saves Capital now. Future events will exact a much higher cost.",
    lore: "Cities deferring ADA compliance face costly federal lawsuits. The 2020 Chicago consent decree on accessibility is funded at $2 billion over 30 years.",
    source: "U.S. Department of Justice ADA Title II enforcement actions",
    category: "infrastructure",
    rarity: "common",
    cost: {},
    fromYear: 1990,
    toYear: 2040,
    effect: { capital: 2, equity: -2, sustainability: -1, setFlag: "ada-deferred" },
  },

  /* ---------- Slow-burn winners: look modest, pay off long ---------- */
  {
    id: "small-grants-program",
    name: "Tiny-grant residency program",
    flavor: "$5K to anyone with a Saturday-morning idea.",
    description: "Small effects each turn. Compounds over the run.",
    lore: "Awesome Foundation chapters give $1,000/month no-strings-attached to local micro-projects. Long-term studies show strong ripple effects in social capital.",
    source: "Awesome Foundation impact reports",
    category: "organizing",
    rarity: "common",
    cost: { capital: 1, trust: 1 },
    fromYear: 1990,
    toYear: 2040,
    effect: { trust: 1, heritage: 1, sustainability: 1 },
  },
  {
    id: "longitudinal-study",
    name: "Commission a 25-year longitudinal study",
    flavor: "Track what happens. Unglamorous. Necessary.",
    description: "Knowledge-only card, but knowledge unlocks everything else.",
    lore: "The Project on Human Development in Chicago Neighborhoods (PHDCN), running since 1994, has published over 700 peer-reviewed articles and shifted multiple policy debates.",
    source: "PHDCN; Sampson, Great American City (2012)",
    category: "research",
    rarity: "uncommon",
    cost: { capital: 2, knowledge: 2 },
    fromYear: 1990,
    toYear: 2040,
    effect: { knowledge: 4, sustainability: 1, heritage: 1 },
  },
  {
    id: "public-bank-charter",
    name: "Charter a public bank",
    flavor: "Lend the city's deposits to the city's businesses.",
    description: "Slow start. Ten turns in, the bank funds projects others won't.",
    lore: "The Bank of North Dakota (founded 1919) is the only state-owned bank in the U.S. and consistently outperforms peer commercial banks. Chicago activists have pushed for a similar public bank since 2018.",
    source: "Bank of North Dakota annual reports; Public Bank Coalition Chicago",
    category: "finance",
    rarity: "rare",
    cost: { capital: 4, power: 3, knowledge: 2 },
    fromYear: 2018,
    toYear: 2040,
    effect: { capital: 2, equity: 3, growth: 2, sustainability: 2 },
  },

  /* ---------- High-risk high-reward ---------- */
  {
    id: "alderman-recall",
    name: "Recall the aldermanic veto",
    flavor: "Strip aldermen of their downzoning power.",
    description: "Massive long-term equity gain. Massive political cost up front.",
    lore: "Chicago's aldermanic prerogative lets a single alderman block all developments in their ward, including affordable housing. Reformers have argued it is the single biggest blocker of fair-share housing.",
    source: "Berry et al., 'Aldermanic Prerogative and Affordable Housing' (2019)",
    category: "zoning",
    rarity: "legendary",
    cost: { power: 6, knowledge: 2 },
    fromYear: 2010,
    toYear: 2040,
    effect: { equity: 6, growth: 3, sustainability: 2, capital: -3 },
  },
  {
    id: "land-bank-bulk-acquisition",
    name: "Bulk acquire from the Land Bank",
    flavor: "Buy 30 distressed parcels in one go.",
    description: "Permanent neighborhood control. Big up-front price tag.",
    lore: "The Cook County Land Bank Authority has acquired over 5,000 distressed properties since 2013 and resold them to community-aligned buyers at substantial discounts.",
    source: "Cook County Land Bank Authority annual reports",
    category: "housing",
    rarity: "rare",
    cost: { capital: 5, power: 3, trust: 2 },
    fromYear: 2013,
    toYear: 2040,
    effect: {
      equity: 4,
      heritage: 4,
      capital: -2,
      transformParcels: [
        { selector: "type:vacant", set: { owner: "land-trust", protected: true } },
      ],
    },
  },

  /* ---------- More zoning ---------- */
  {
    id: "remove-parking-minimums",
    name: "Remove parking minimums",
    flavor: "Builders pick how much parking they actually need.",
    description: "Cuts construction costs. Changes the streetscape over decades.",
    lore: "Buffalo, Minneapolis, and parts of Chicago have removed parking minimums. Studies show 10-15% reductions in unit construction costs and modest reductions in vehicle ownership.",
    source: "Shoup, The High Cost of Free Parking (2005)",
    category: "zoning",
    rarity: "uncommon",
    cost: { power: 2, knowledge: 1 },
    fromYear: 2018,
    toYear: 2040,
    effect: { growth: 3, sustainability: 3, capital: 1 },
  },
  {
    id: "mansion-tax",
    name: "Mansion tax for affordable housing",
    flavor: "$1M+ home sales pay a transfer-tax surcharge.",
    description: "Steady Capital flow. Real-estate industry hates it.",
    lore: "Los Angeles voters passed Measure ULA in 2022, taxing $5M+ sales at 4% to fund affordable housing. Chicago voters narrowly rejected a similar measure (Bring Chicago Home) in 2024.",
    source: "Los Angeles Measure ULA; Bring Chicago Home campaign records",
    category: "finance",
    rarity: "rare",
    cost: { power: 4, trust: 1 },
    fromYear: 2020,
    toYear: 2040,
    effect: { capital: 4, equity: 4 },
  },
  {
    id: "single-stair-reform",
    name: "Single-stair construction reform",
    flavor: "Allow one staircase up to six floors.",
    description: "Lets small developers build affordably. Slow but real Growth.",
    lore: "Most U.S. cities require two staircases above three stories, which makes small/medium apartments uneconomical. Seattle and New York are reconsidering. Reform is gaining national traction in 2024-25.",
    source: "Smart Growth America stair-reform briefings",
    category: "zoning",
    rarity: "uncommon",
    cost: { knowledge: 2, power: 2 },
    fromYear: 2023,
    toYear: 2040,
    effect: { growth: 3, sustainability: 2, equity: 1 },
  },
  {
    id: "hold-the-zoning-map",
    name: "Refuse to update the zoning map",
    flavor: "What we have works.",
    description: "Stability now. Quiet stagnation later.",
    lore: "Chicago has not done a comprehensive zoning rewrite since 2004. Critics argue this freezes restrictive 20th-century patterns. Defenders say it protects neighborhood character.",
    source: "Chicago zoning code revision history",
    category: "zoning",
    rarity: "common",
    cost: {},
    fromYear: 1990,
    toYear: 2040,
    effect: { heritage: 2, growth: -2, equity: -1 },
  },

  /* ---------- More housing ---------- */
  {
    id: "eminent-domain-affordable",
    name: "Eminent domain for affordable housing",
    flavor: "Take vacant blocks. Pay fair market. Build.",
    description: "Powerful tool. Equally powerful political backlash.",
    lore: "Kelo v. City of New London (2005) confirmed eminent domain can be used for economic development. Backlash led to 47 states limiting the practice. Some cities still use it for explicit public housing.",
    source: "Kelo v. City of New London, 545 U.S. 469 (2005)",
    category: "housing",
    rarity: "rare",
    cost: { power: 4, capital: 4 },
    fromYear: 1960,
    toYear: 2040,
    effect: {
      equity: 4,
      growth: 3,
      heritage: -2,
      transformParcels: [
        { selector: "type:vacant", set: { type: "courtyard", residents: 30, owner: "city" } },
      ],
    },
  },
  {
    id: "sro-rehab",
    name: "Single-room occupancy rehab",
    flavor: "Cheap private rooms with shared kitchens. The original cheap housing.",
    description: "Fast cheap units. Politically unpopular with neighbors.",
    lore: "Chicago lost roughly 2/3 of its SRO units between 1960 and 2000 to demolition or conversion. Activists argue this drove the modern homelessness crisis.",
    source: "Hopper, Reckoning with Homelessness (2003)",
    category: "housing",
    rarity: "uncommon",
    cost: { capital: 2 },
    fromYear: 1990,
    toYear: 2040,
    effect: { equity: 4, sustainability: 1, heritage: 1 },
  },
  {
    id: "right-to-shelter",
    name: "Right to shelter ordinance",
    flavor: "Anyone unhoused gets a bed by 6 p.m.",
    description: "Massive equity gain. Massive ongoing capital cost.",
    lore: "New York City has had a right to shelter since 1979. The city spends ~$2B/year on the system. Boston and Newark have similar policies.",
    source: "Callahan v. Carey, NY Supreme Court 1979",
    category: "housing",
    rarity: "rare",
    cost: { capital: 4, power: 3, trust: 2 },
    fromYear: 1980,
    toYear: 2040,
    effect: { equity: 5, sustainability: 2 },
  },
  {
    id: "repeal-source-of-income",
    name: "Repeal source-of-income protection",
    flavor: "Property managers can refuse vouchers again.",
    description: "Reverses a key Fair Housing tool. Big equity loss.",
    lore: "Source-of-income protection passed in Chicago in 1990. Repeal proposals have surfaced from landlord lobbies repeatedly since.",
    source: "Chicago Human Rights Ordinance, 1990",
    category: "zoning",
    rarity: "uncommon",
    cost: { power: 2 },
    fromYear: 1995,
    toYear: 2040,
    effect: { equity: -4, capital: 2, growth: 1 },
  },

  /* ---------- More transit / infrastructure ---------- */
  {
    id: "free-fare-pilot",
    name: "Free transit fare pilot",
    flavor: "One year, no fares on three bus routes.",
    description: "Big sustainability win. Big sustained Capital cost.",
    lore: "Boston, Kansas City, and Olympia have run free-fare pilots. Ridership rose 20-40% in the pilots, fare evasion fell, dwell times shortened. Sustainability and equity dividends.",
    source: "MBTA Route 28 pilot; Olympia Transit Free Fare data",
    category: "transit",
    rarity: "uncommon",
    cost: { capital: 3, power: 2 },
    fromYear: 2020,
    toYear: 2040,
    effect: { sustainability: 4, equity: 3 },
  },
  {
    id: "circulator-bus",
    name: "Neighborhood circulator bus",
    flavor: "Frequent small bus connecting key blocks to transit.",
    description: "Modest Sustainability and Equity boost. Cheap to start.",
    lore: "Pace's Pulse circulator buses on the suburban and South Side networks have been a quiet success since 2017.",
    source: "Pace Suburban Bus annual reports",
    category: "transit",
    rarity: "common",
    cost: { capital: 2 },
    fromYear: 2010,
    toYear: 2040,
    effect: { sustainability: 2, equity: 2 },
  },
  {
    id: "complete-streets",
    name: "Complete Streets ordinance",
    flavor: "Streets designed for buses, bikes, and humans, not just cars.",
    description: "Slow rollout, compounding benefits.",
    lore: "Chicago's Complete Streets policy dates to 2006 but enforcement has been uneven. The 2021 bike-network plan accelerated implementation.",
    source: "City of Chicago Complete Streets Policy 2006",
    category: "infrastructure",
    rarity: "common",
    cost: { power: 2, knowledge: 1 },
    fromYear: 2006,
    toYear: 2040,
    effect: { sustainability: 3, growth: 1 },
  },
  {
    id: "viaduct-cleanup",
    name: "Viaduct underpass renovations",
    flavor: "Lights, drainage, paint, paint, paint.",
    description: "Small heritage and sustainability win. Cheap.",
    lore: "Chicago has hundreds of railroad viaduct underpasses, most in poor condition. The CDOT viaduct program upgrades 4-6 per year.",
    source: "Chicago Department of Transportation viaduct improvement program",
    category: "infrastructure",
    rarity: "common",
    cost: { capital: 1 },
    fromYear: 2000,
    toYear: 2040,
    effect: { sustainability: 1, heritage: 1 },
  },
  {
    id: "freight-rail-mitigation",
    name: "Freight rail mitigation",
    flavor: "Underground a freight track, cap with parkland.",
    description: "Heritage and sustainability transformation. Steep capital cost.",
    lore: "The CREATE program (Chicago Region Environmental and Transportation Efficiency) has invested $4B+ since 2003 to reduce the rail-related quality-of-life burden on adjacent neighborhoods.",
    source: "CREATE Program annual reports",
    category: "infrastructure",
    rarity: "rare",
    cost: { capital: 5, power: 2 },
    fromYear: 2005,
    toYear: 2040,
    effect: { heritage: 3, sustainability: 4, growth: 1 },
  },

  /* ---------- More finance ---------- */
  {
    id: "issue-revenue-bond",
    name: "Issue a revenue bond",
    flavor: "Borrow against future tax flow. Build now.",
    description: "Big Capital up front. Long ongoing service obligation.",
    lore: "Chicago's revenue bond debt service approaches $1B annually. Issuance lets the city build now but commits future budgets.",
    source: "City of Chicago Annual Comprehensive Financial Report",
    category: "finance",
    rarity: "common",
    cost: { power: 2 },
    fromYear: 1960,
    toYear: 2040,
    effect: { capital: 5, sustainability: -1 },
  },
  {
    id: "pension-obligation-bond",
    name: "Pension obligation bond",
    flavor: "Borrow now to fund pensions. Pray investments outperform interest.",
    description: "Risky. Sets up future Capital pain.",
    lore: "Chicago has used POBs intermittently. The 2003 issuance underperformed expectations. Most public-finance scholars consider POBs high-risk.",
    source: "Center for Retirement Research at Boston College, POB analyses",
    category: "finance",
    rarity: "uncommon",
    cost: { power: 2, knowledge: 1 },
    fromYear: 2000,
    toYear: 2040,
    effect: { capital: 5, sustainability: -3 },
  },
  {
    id: "homestead-exemption",
    name: "Expand homestead exemption",
    flavor: "Lower property tax for owner-occupants.",
    description: "Equity bump for existing owners. Renters and the school fund pay.",
    lore: "Cook County's senior homestead exemption and assessment freeze cap property taxes for qualifying owners. The exemption shifts tax burden to renters and commercial properties.",
    source: "Cook County Assessor exemption guidance",
    category: "finance",
    rarity: "common",
    cost: { power: 2 },
    fromYear: 1970,
    toYear: 2040,
    effect: { equity: 2, capital: -2 },
  },
  {
    id: "bond-rating-upgrade",
    name: "Pursue a bond-rating upgrade",
    flavor: "Show fiscal discipline. Ratings agencies notice.",
    description: "Cheaper future borrowing. Costs flexibility now.",
    lore: "Chicago's general obligation rating bottomed out in the 2010s. The 2021-2024 upgrades cut borrowing costs by hundreds of millions over the next decade.",
    source: "Moody's Investors Service Chicago ratings actions",
    category: "finance",
    rarity: "uncommon",
    cost: { capital: 2, knowledge: 2 },
    fromYear: 2015,
    toYear: 2040,
    effect: { capital: 2, sustainability: 2 },
  },

  /* ---------- More schools ---------- */
  {
    id: "magnet-school",
    name: "Open a magnet school",
    flavor: "Selective enrollment, college prep, neighborhood preference.",
    description: "Boosts equity for some, drains the neighborhood school.",
    lore: "Chicago's selective-enrollment high schools (Northside, Walter Payton, Whitney Young) consistently outperform on test scores. Critics note they pull resources and motivated families from neighborhood schools.",
    source: "Chicago Public Schools selective-enrollment data",
    category: "schools",
    rarity: "uncommon",
    cost: { capital: 3, knowledge: 1 },
    fromYear: 1980,
    toYear: 2040,
    effect: { equity: 2, growth: 2, heritage: -1 },
  },
  {
    id: "vocational-program",
    name: "Vocational training partnership",
    flavor: "Welding, plumbing, healthcare, paid apprenticeships.",
    description: "Direct equity gains for grads. Real workforce pipeline.",
    lore: "The CPS-Chicago Federation of Labor partnership has graduated thousands of apprentices since 2014. Pace and IBEW Local 134 are major partners.",
    source: "Chicago Public Schools career and technical education reports",
    category: "schools",
    rarity: "common",
    cost: { capital: 2, trust: 1 },
    fromYear: 1980,
    toYear: 2040,
    effect: { equity: 3, growth: 2 },
  },
  {
    id: "elected-school-board",
    name: "Push for an elected school board",
    flavor: "Accountability changes hands.",
    description: "Long-term equity gain. Short-term political chaos.",
    lore: "Illinois passed a law in 2021 transitioning Chicago to a fully elected 21-member school board by 2027, the largest in the country.",
    source: "Illinois Public Act 102-0177",
    category: "schools",
    rarity: "rare",
    cost: { power: 4, trust: 2 },
    fromYear: 2018,
    toYear: 2040,
    effect: { equity: 4, heritage: 2, growth: -1 },
  },

  /* ---------- More environment ---------- */
  {
    id: "green-roof-mandate",
    name: "Green roof mandate",
    flavor: "Every flat roof above 50,000 sf requires a planted layer.",
    description: "Sustainability win. Adds construction cost.",
    lore: "Chicago's green-roof program (City Hall, 2001 onward) is the oldest large-scale municipal program in the U.S. The city has over 5.5 million sq ft of green roof.",
    source: "City of Chicago green roof program",
    category: "environment",
    rarity: "uncommon",
    cost: { power: 2, capital: 1 },
    fromYear: 2001,
    toYear: 2040,
    effect: { sustainability: 4, growth: -1 },
  },
  {
    id: "lead-paint-remediation",
    name: "Lead paint remediation grants",
    flavor: "Subsidize abatement in pre-1978 homes.",
    description: "Long-term health and equity gains.",
    lore: "Chicago is among the worst U.S. cities for childhood lead exposure. The CDPH remediation program covers up to $20K per qualifying home.",
    source: "Chicago Department of Public Health Lead Safe Program",
    category: "environment",
    rarity: "common",
    cost: { capital: 2, knowledge: 1 },
    fromYear: 1990,
    toYear: 2040,
    effect: { equity: 3, sustainability: 3 },
  },
  {
    id: "scrap-yard-buyout",
    name: "Scrap-yard buyout and cleanup",
    flavor: "Buy out the metal recyclers. Clean the soil.",
    description: "Removes a major pollution source. Heavy upfront Capital.",
    lore: "The General Iron / RMG scrap yard relocation fight on Chicago's Southeast Side (2018-2022) became a national environmental-justice case.",
    source: "Coverage of the General Iron / RMG environmental justice case",
    category: "environment",
    rarity: "uncommon",
    cost: { capital: 3, power: 3 },
    fromYear: 2010,
    toYear: 2040,
    effect: { sustainability: 4, equity: 3 },
  },

  /* ---------- More commerce ---------- */
  {
    id: "co-op-grocery",
    name: "Open a cooperative grocery",
    flavor: "Member-owned. Sourced locally. Saturday board meetings.",
    description: "Slow-build equity and sustainability.",
    lore: "Chicago's Dill Pickle Food Co-op, Sugar Beet, and others have created member-owned grocery anchors. Park Slope and Berkeley Bowl are bigger national reference points.",
    source: "Cooperative Grocer Network case studies",
    category: "commerce",
    rarity: "uncommon",
    cost: { capital: 2, trust: 2 },
    fromYear: 1990,
    toYear: 2040,
    effect: { equity: 2, sustainability: 2, heritage: 2 },
  },
  {
    id: "business-improvement-district",
    name: "Business Improvement District",
    flavor: "Property owners self-tax for shared services.",
    description: "Cleaner streets, more cameras. Mixed equity record.",
    lore: "Chicago has 50+ Special Service Areas (BIDs). They fund security, marketing, and beautification but have mixed records on rent stability for small businesses.",
    source: "City of Chicago Special Service Area program",
    category: "commerce",
    rarity: "common",
    cost: { power: 2 },
    fromYear: 1990,
    toYear: 2040,
    effect: { growth: 2, capital: 1, equity: -1 },
  },
  {
    id: "incubator-kitchen",
    name: "Shared commercial kitchen",
    flavor: "Hourly rental. Health-code-compliant. Small caterers, food trucks, bakers.",
    description: "Quiet equity win.",
    lore: "Chicago's The Hatchery (2018) has incubated dozens of food businesses on the West Side, several of which have grown to brick-and-mortar.",
    source: "The Hatchery Chicago program reports",
    category: "commerce",
    rarity: "common",
    cost: { capital: 2 },
    fromYear: 2015,
    toYear: 2040,
    effect: { equity: 2, growth: 2 },
  },

  /* ---------- More research ---------- */
  {
    id: "neighborhood-survey",
    name: "Door-to-door neighborhood survey",
    flavor: "What do residents actually want?",
    description: "Short-term Knowledge boost. Compounds over a run.",
    lore: "Participatory neighborhood-needs surveys are standard in equitable-development planning. The Bronzeville Community Action Council has used them since 2009.",
    source: "Bronzeville Community Action Council planning documents",
    category: "research",
    rarity: "common",
    cost: { trust: 2, knowledge: 1 },
    fromYear: 1980,
    toYear: 2040,
    effect: { knowledge: 3, trust: 1 },
  },
  {
    id: "displacement-tracking-tool",
    name: "Displacement tracking dashboard",
    flavor: "A real-time dataset of who is leaving and from where.",
    description: "Knowledge that powers later decisions.",
    lore: "The UC Berkeley Urban Displacement Project maps gentrification and displacement risk across U.S. cities. Chicago's version is maintained by DePaul's Institute for Housing Studies.",
    source: "Urban Displacement Project; DePaul Institute for Housing Studies",
    category: "research",
    rarity: "uncommon",
    cost: { capital: 2, knowledge: 2 },
    fromYear: 2015,
    toYear: 2040,
    effect: { knowledge: 3, equity: 2 },
  },

  /* ---------- More culture ---------- */
  {
    id: "library-late-hours",
    name: "Extend library hours",
    flavor: "Open until 9. Open Sundays.",
    description: "Direct equity gain. Modest capital cost.",
    lore: "Chicago Public Library extended Sunday hours in 2019 after years of advocacy. Use rose by 30% in the first year.",
    source: "Chicago Public Library annual reports",
    category: "culture",
    rarity: "common",
    cost: { capital: 1 },
    fromYear: 1990,
    toYear: 2040,
    effect: { equity: 2, heritage: 2 },
  },
  {
    id: "music-school-partnership",
    name: "Free youth music school",
    flavor: "Trumpet, viola, marimba. Saturday sessions.",
    description: "Heritage and equity slow-burn.",
    lore: "People's Music School, the Merit School of Music, and the Chicago Youth Symphony Orchestra together serve thousands of CPS students at no cost.",
    source: "People's Music School annual reports",
    category: "culture",
    rarity: "common",
    cost: { capital: 1, trust: 1 },
    fromYear: 1990,
    toYear: 2040,
    effect: { heritage: 3, equity: 2 },
  },
  {
    id: "bilingual-signage",
    name: "Bilingual public signage",
    flavor: "Spanish, Polish, Mandarin where the residents are.",
    description: "Modest Heritage gain. Welcoming to immigrants.",
    lore: "Chicago has dual-language signage in several neighborhoods (Pilsen, Little Village, Chinatown). Implementation varies block by block.",
    source: "City of Chicago language access policy",
    category: "culture",
    rarity: "common",
    cost: { capital: 1 },
    fromYear: 1995,
    toYear: 2040,
    effect: { heritage: 2, equity: 1 },
  },

  /* ---------- Late game / 2030s+ ---------- */
  {
    id: "guaranteed-income-pilot",
    name: "Guaranteed income pilot",
    flavor: "$500/month, no strings, two thousand families.",
    description: "Real equity outcomes. Steep ongoing Capital cost.",
    lore: "Chicago's Resilient Communities Pilot (2022-2024) gave $500/month to 5,000 low-income families. Stockton, CA, and several other cities have run similar pilots. Rigorous evaluation showed reduced household financial stress.",
    source: "Stockton SEED, Chicago Resilient Communities Pilot reports",
    category: "finance",
    rarity: "rare",
    cost: { capital: 4, power: 2 },
    fromYear: 2022,
    toYear: 2040,
    effect: { equity: 5, sustainability: 2 },
  },
  {
    id: "open-data-portal",
    name: "Comprehensive open-data portal",
    flavor: "Every dataset the city collects, public, machine-readable.",
    description: "Knowledge gain that powers other cards.",
    lore: "Chicago's open data portal (data.cityofchicago.org), launched 2010, was a national leader. It has been an essential tool for journalists and researchers.",
    source: "City of Chicago Open Data portal",
    category: "research",
    rarity: "common",
    cost: { capital: 1, knowledge: 1 },
    fromYear: 2010,
    toYear: 2040,
    effect: { knowledge: 3, equity: 1, sustainability: 1 },
  },
  {
    id: "ai-zoning-review",
    name: "AI-assisted zoning review",
    flavor: "Use ML to flag inequitable land-use patterns.",
    description: "Speeds work but introduces new risks.",
    lore: "Cities including Boston and Los Angeles have piloted AI tools for permit review. Equity audits of these tools have flagged concerning bias patterns.",
    source: "Brookings AI in Local Government 2024 report",
    category: "research",
    rarity: "uncommon",
    cost: { knowledge: 3, capital: 2 },
    fromYear: 2024,
    toYear: 2040,
    effect: { growth: 2, equity: 1, knowledge: 1 },
  },
  {
    id: "climate-resilience-bond",
    name: "Climate resilience bond",
    flavor: "Float $200M. Underground power. Raise seawalls. Cool roofs.",
    description: "Big sustainability win. Big debt service obligation.",
    lore: "Miami's $400M Miami Forever Bond and similar issuances by NYC and Norfolk fund climate adaptation. Chicago has discussed but not issued one.",
    source: "Miami Forever Bond documentation",
    category: "environment",
    rarity: "rare",
    cost: { capital: 3, power: 3 },
    fromYear: 2025,
    toYear: 2040,
    effect: { sustainability: 6, equity: 2, growth: 2 },
  },
  {
    id: "rent-stabilization-fight",
    name: "Lift the state preemption on rent control",
    flavor: "Statewide ban gone. Cities can finally legislate rents.",
    description: "Massive late-game equity tool. Massive political cost.",
    lore: "Illinois has banned rent control statewide since 1997 (Rent Control Preemption Act). Activists have pushed for repeal in every recent legislative session.",
    source: "Lift the Ban Coalition campaign records",
    category: "organizing",
    rarity: "legendary",
    cost: { power: 6, trust: 3, knowledge: 2 },
    fromYear: 2020,
    toYear: 2040,
    effect: { equity: 7, heritage: 3, growth: -1 },
  },
];

/** Map of card id to card for fast lookup */
export const CARD_BY_ID: Map<string, Card> = new Map(CARDS.map((c) => [c.id, c]));

/** Get cards available in a given year, optionally filtered by required flags */
export function availableCards(year: number, flags: Set<string>): Card[] {
  return CARDS.filter((c) => {
    if (c.fromYear !== undefined && year < c.fromYear) return false;
    if (c.toYear !== undefined && year > c.toYear) return false;
    if (c.requiresFlag && !flags.has(c.requiresFlag)) return false;
    return true;
  });
}
