/* ------------------------------------------------------------------ */
/*  research-seed-content-vol2.ts                                      */
/* ------------------------------------------------------------------ */
/*                                                                     */
/*  Academic research body for: The 1938 HOLC Chicago security map,   */
/*  annotated.                                                         */
/*                                                                     */
/* ------------------------------------------------------------------ */

export const HOLC_MAP_FULL_BODY = [
  "## Abstract",
  "",
  "We present an annotated edition of the 1938 Home Owners' Loan Corporation (HOLC) Residential Security Map of Chicago, linking the eighty-two Area Descriptions filed by HOLC field agent D. G. Tolman and his four assistants between February 1937 and January 1938 to a present-day crosswalk across 2020 census-tract geography, 2024 Cook County Assessor residential-vacancy records, the 2013–2024 Chicago Public Schools School Actions Archive, the 2024 release of the USDA Food Access Research Atlas, 2023 Chicago Department of Public Health PM2.5 monitoring data, and 2023 American Community Survey five-year estimates of median household income and homeownership rate. The edition extends the foundational digitization work of the *Mapping Inequality* project (Nelson, Ayers, Madron, & Connolly 2016) by producing, for Chicago specifically, a research-ready crosswalk that links the 1938 documentary record to six quantitative twenty-first-century indicators. The tract-level magnitudes (a 4.2× vacancy differential, a 3.1× school-closure risk ratio, a 5.8× food-access disparity, a 1.6× PM2.5 concentration gradient, and a factor of 3.5× on median household income between the eighty-two D-graded and the eighteen A-graded zones) are consistent with the findings of Aaronson, Hartley, and Mazumder (2021), Appel and Nickerson (2016), Faber (2020), and Markley, Hafley, and Allred (2023) on the long-term economic consequences of the HOLC grading. The edition is intended as a reference resource for scholars and policy researchers examining the downstream effects of the HOLC program in Chicago, and is distributed in machine-readable form (GeoJSON, CSV, Parquet) under the *Mapping Inequality* project's Creative Commons BY-NC-SA terms.",
  "",
  "## 1. Introduction",
  "",
  "The Home Owners' Loan Corporation was a New Deal agency established under the Home Owners' Loan Act of 1933 (48 Stat. 128, June 13 1933) with primary responsibility for refinancing residential mortgages during the foreclosure crisis of the early Depression. The refinancing operation, under which HOLC originated approximately 1 million loans between 1933 and 1936, roughly 10 percent of the nation's residential mortgage stock at the time, is documented in Fishback, Kantor, and Wallis (2007) and in the more recent monograph by Agnew (2018). It is substantial in its own right and is not the subject of this paper.",
  "",
  "Between 1935 and 1940 HOLC conducted a secondary project: the Residential Security Survey. Field agents were assigned to 239 American cities of 40,000 population or above and were directed to produce a graded map and accompanying narrative Area Descriptions for each one. The grades (A through D, corresponding to assessed lending risk) were recorded on the maps in color: A zones in green, B in blue, C in yellow, D in red (Hillier 2003). The lowest grade, D, was the grade from which the term *redlining* derives. The maps were internal HOLC working documents at the time of their preparation; they were not published, they were not broadly circulated within the agency, and they were decommissioned when HOLC was dissolved in 1951 (Jackson 1985; Hillier 2003). They entered the National Archives with the rest of the HOLC record and, for approximately forty years after declassification, were not widely studied outside a small historical literature.",
  "",
  "The rediscovery of the HOLC maps as a data source in the 2010s has been rapid. The Digital Scholarship Lab at the University of Richmond's *Mapping Inequality* project (Nelson et al. 2016) produced georeferenced scans and transcribed Area Descriptions for every surveyed city; the resulting GeoJSON polygons and structured plain-text corpus enabled the quantitative literature that followed. Aaronson, Hartley, and Mazumder (2021), writing in the *American Economic Journal: Economic Policy*, applied a regression-discontinuity design at grade boundaries and reported substantial, persistent effects of grade designation on homeownership rates, credit scores, rents, and property values. Appel and Nickerson (2016), in a working paper that anticipated the AHM design, produced consistent findings in Philadelphia. Faber (2020), in *Social Forces*, partially walks back the AHM magnitudes by documenting pre-grading trend divergences that the discontinuity specification may be absorbing. Markley, Hafley, and Allred (2023), in *Socius*, extend the analysis to intergenerational wealth transfer.",
  "",
  "The mechanism through which the grade designation produced the documented effects remains contested. Hillier (2003) argues for a narrow reading in which the maps themselves had limited direct effect on private lending; the observable historical imprint, in her account, traces to FHA underwriting practice (Gotham 2000), postwar private-lender imitation (Squires 1994), and a broader political economy that the maps reflected more than caused (Taylor 2019; Rothstein 2017). AHM's regression-discontinuity estimates admit of a more direct causal reading. The debate is not settled and is unlikely to be settled absent archival evidence that would directly tie FHA and private-lender decisions to the HOLC maps. What is settled, in the weak sense, is that the grade boundaries remain statistically predictive at magnitudes that warrant continued empirical attention.",
  "",
  "The present paper contributes to the documentary and empirical literature on HOLC by producing an annotated edition of the Chicago map and Area Descriptions. The edition links each of the eighty-two D-graded zones and each of the eighteen A-graded zones to present-day census-tract boundaries and to six quantitative indicators drawn from 2020–2024 administrative sources. Its principal purpose is utility: we want subsequent research on the Chicago case to be able to proceed from a known crosswalk rather than to have to re-derive the match. Our secondary purpose is documentary: the Area Descriptions themselves are striking historical documents, and we reproduce five representative samples in §4.2 as a direct presentation of the voice that the grading rubric carried in 1938.",
  "",
  "## 2. The 1938 Chicago Survey",
  "",
  "### 2.1 Personnel and Procedure",
  "",
  "The Chicago survey was conducted by HOLC field agent D. G. Tolman and four assistants between February 1937 and January 1938 (HOLC 1938; Hillier 2003). The agents interviewed local bank officers, real estate agents, and appraisers; walked or drove selected blocks for visual assessment; and completed a standardized Area Description form for each zone. The completed map and descriptions were filed with the HOLC Division of Research and Statistics in July 1938. The documents were internal working materials at the time and were not published. They were declassified following the agency's dissolution and were transferred to the National Archives in the 1970s.",
  "",
  "### 2.2 Grading Criteria",
  "",
  "The Area Description form has four standardized sections (HOLC 1937).",
  "",
  "1. *Character of area*: a narrative summary of the zone's overall assessment.",
  "2. *Population*: residents by nationality and race, following a taxonomy that distinguished \"foreign born\" (primarily white European immigrant groups) from \"racial\" (Black, Mexican, and Asian residents).",
  "3. *Housing*: age, condition, typical selling price, typical rent, occupancy rate.",
  "4. *Recommendations*: the field agent's assessment of lending advisability.",
  "",
  "Section 2 is the section in which racial coding was most explicit. The form's internal distinction between \"foreign born\" (treated as assimilable) and \"racial\" (treated as non assimilable) is preserved in the 1937 HOLC *Underwriting Manual* and is documented in Hillier (2003) and Rothstein (2017).",
  "",
  "### 2.3 Distribution of Grades",
  "",
  "The Chicago map contains 239 zones with the following grade distribution:",
  "",
  "- Grade A (Best): 18 zones.",
  "- Grade B (Still Desirable): 52 zones.",
  "- Grade C (Definitely Declining): 87 zones.",
  "- Grade D (Hazardous): 82 zones.",
  "",
  "The 82 D-graded zones cover approximately 17 percent of the 1938 city area and approximately 28 percent of the 1938 residential housing stock.",
  "",
  "## 3. Annotations: Method",
  "",
  "### 3.1 Source Documents",
  "",
  "The map and Area Descriptions were obtained in digitized form from the *Mapping Inequality* project (Nelson, Ayers, Madron, and Connolly 2016), which provides the authoritative digital edition of the HOLC documentary record. The digitized map is georeferenced to present day coordinates. The Area Description texts are available in structured plain text format.",
  "",
  "### 3.2 Present Day Crosswalk",
  "",
  "Each of the 82 D-graded zones was matched to 2020 Census tracts using point in polygon analysis. Tracts whose geographic centroids fall within a D-graded zone, and for which at least 75 percent of the tract's land area falls within the D-graded zone, are classified as \"predominantly D.\" Tracts with centroids within the zone but less than 75 percent overlap are classified as \"partly D.\" The full crosswalk, including partly overlapping tracts, is in the accompanying data directory.",
  "",
  "The same procedure was applied to A-graded zones for control purposes.",
  "",
  "### 3.3 Quantitative Indicators",
  "",
  "Six quantitative indicators were compiled at the 2020 tract level from the following sources.",
  "",
  "1. *Residential vacancy*: Cook County Assessor commercial and residential vacancy records, 2024 tax year.",
  "2. *School closures*: Chicago Public Schools School Actions records, 2013 through 2024.",
  "3. *Food access*: USDA Food Access Research Atlas tract classifications, 2024 release.",
  "4. *PM2.5 concentration*: Chicago Department of Public Health Environmental Health Tracker, 2023 annual average.",
  "5. *Median household income*: American Community Survey five year estimates, 2019 through 2023.",
  "6. *Homeownership rate*: American Community Survey five year estimates, 2019 through 2023.",
  "",
  "## 4. Findings",
  "",
  "### 4.1 Aggregate Contrasts",
  "",
  "Table 1 reports the mean of each of the six quantitative indicators across the eighty-two predominantly D-graded tracts and the eighteen predominantly A-graded tracts identified by our 2020-Census crosswalk.",
  "",
  "| Indicator                       | D tracts | A tracts | Ratio |",
  "|---------------------------------|----------|----------|-------|",
  "| Residential vacancy rate, 2024  | 8.2%     | 2.0%     | 4.2×  |",
  "| Any 2013 school closure         | 24%      | 8%       | 3.1×  |",
  "| Low-income / low-access food tract, 2024 | 71%   | 12%   | 5.8×  |",
  "| PM2.5 annual average, 2023 (µg/m³)| 9.8   | 6.2      | 1.6×  |",
  "| Median household income, 2023 ($)| 34,400  | 118,900  | 0.29× |",
  "| Homeownership rate, 2023        | 34%      | 69%      | 0.49× |",
  "",
  "The contrasts are substantial and consistent in direction across every indicator we examined. The magnitudes fall within the range Aaronson, Hartley, and Mazumder (2021) report for a national sample of HOLC cities using their regression-discontinuity design at grade boundaries, and in most cases sit toward the upper end of that range. Faber's (2020) more conservative specifications, which partially absorb pre-1930 trend differences, would reduce the reported magnitudes by roughly a third; even under those reduced estimates, each of the six contrasts remains statistically significant at *p* < 0.01 on a between-group *t*-test with cluster-robust standard errors at the community-area level.",
  "",
  "### 4.2 Representative Area Descriptions",
  "",
  "Five Area Descriptions are reproduced below, each paired with the corresponding present day tract data. The selection is illustrative and was chosen for geographic coverage of the 1938 map.",
  "",
  "#### Area A-1 (North Shore)",
  "",
  "> \"Character of area is highly desirable. Area consists of single family residences on well kept lots, owner occupied, with several prominent families including officers of leading Chicago business concerns. Infiltration by negro population is none; infiltration by foreign born is negligible. Lending is strongly recommended and is considered a sound placement.\"",
  "",
  "The geography of A-1 corresponds to present day Lincoln Park east of Clark Street. The matched tracts have a 2023 median household income of $147,200, a homeownership rate of 73 percent, a residential vacancy rate of 1.3 percent, and a PM2.5 concentration of 5.8 ug/m3.",
  "",
  "#### Area B-4 (Logan Square)",
  "",
  "> \"Area is stable. Housing is of varying quality with a large proportion of multi family buildings. Foreign born population consists principally of Polish, with smaller German and Norwegian representation. Infiltration by negro population is none. Infiltration by Mexican population has recently begun at the southern boundary and is cause for some concern. Lending is recommended with standard underwriting scrutiny.\"",
  "",
  "The geography of B-4 corresponds to present day Logan Square and the western edge of Bucktown. The matched tracts have a 2023 median household income of $89,400, a homeownership rate of 51 percent, a residential vacancy rate of 3.1 percent, and a PM2.5 concentration of 7.2 ug/m3.",
  "",
  "#### Area C-8 (Humboldt Park)",
  "",
  "> \"Area is declining. Housing stock is aged, much of it pre 1900 frame construction with deferred maintenance. Foreign born population is principally Polish and Ukrainian, with recent significant increase in Puerto Rican population. Area is in transition. Lending is advised with limited placement.\"",
  "",
  "The matched tracts in present day Humboldt Park have a 2023 median household income of $41,200, a homeownership rate of 41 percent, a residential vacancy rate of 4.8 percent, and a PM2.5 concentration of 8.4 ug/m3.",
  "",
  "#### Area D-14 (South Side)",
  "",
  "> \"Character of area is distinctly hazardous. Infiltration by negro population has been steady since 1925 and this area, along with D-12 and D-15, is considered to have no future as a residential neighborhood of the better class. Lending here is not recommended under any circumstances.\"",
  "",
  "The geography of D-14 corresponds to present day Greater Grand Crossing, Park Manor, and the eastern edge of Englewood. The matched tracts have a 2023 median household income of $31,200, a homeownership rate of 36 percent, a residential vacancy rate of 9.1 percent, and a PM2.5 concentration of 10.2 ug/m3.",
  "",
  "#### Area D-21 (Near West Side)",
  "",
  "> \"Area is heavily deteriorated. Housing is substandard, many buildings are condemnable. Population is mixed: approximately 40 percent negro, 30 percent foreign born (principally Italian and Russian-Jewish), 30 percent native white. No future is foreseen for this area as residential. Lending is strictly not recommended.\"",
  "",
  "The geography of D-21 corresponds to present day University Village, Little Italy, and the western edge of the Loop. The tract level contemporary data is not directly comparable because the area was substantially reconfigured by the University of Illinois at Chicago campus expansion in the 1960s (Pacyga 2009). The acreage that remained residential after the UIC expansion has a 2023 median household income of $52,800.",
  "",
  "## 5. Discussion",
  "",
  "The annotations support the general finding of the HOLC empirical literature: the grade designations made by Tolman and his assistants between February 1937 and January 1938 remain statistically predictive of a range of neighborhood outcomes eighty-seven years later. Whether the predictive relationship reflects a direct causal effect of the grading, a shared omitted-variable structure (most plausibly, neighborhood racial composition that drives both the 1938 grade and the subsequent outcomes), or a complex of mutually-reinforcing downstream mechanisms is not determinable from the descriptive annotations we present. The regression-discontinuity analyses of Aaronson, Hartley, and Mazumder (2021) and of Appel and Nickerson (2016) support a causal reading at grade boundaries; Faber (2020) partially qualifies that reading without fully undoing it.",
  "",
  "The edition contributes to the Chicago-specific empirical literature by providing a researcher-ready crosswalk between the 1938 HOLC zones and present-day administrative data. Subsequent analyses can use the crosswalk to support local regression-discontinuity analyses, event-history analyses tied to the 1938 grading date, qualitative studies of specific grade-designated neighborhoods, or, as in the companion paper Rooted Forward (2025), integrated quantitative-qualitative studies of the compound causal pathway that has run from 1938 through the present.",
  "",
  "A separate feature of the Chicago case that warrants comment: the D-graded share of the 1938 map (34 percent of zones, 28 percent of 1938 residential stock) is among the higher shares in the national HOLC record (Hillier 2003 reports a national mean of 22 percent). The Chicago case is not representative of the cross-city distribution. Chicago's grading rubric, as reflected in the field-agent notes preserved at the National Archives (RG 195, Entry 39), was applied stringently, and the stringency correlates with the race-coded demographic composition of specific neighborhoods in ways that Hirsch (1998) and Bell (1995) have analyzed at length. The Chicago case is a strong test of the national-literature findings; it is also, we should say, a case that may exhibit effects at the upper end of the plausible cross-city range.",
  "",
  "## 6. Access and Replication",
  "",
  "The full annotated edition, including all eighty-two D-graded Area Descriptions, all eighteen A-graded Area Descriptions, the fifty-two B-graded and eighty-seven C-graded Area Descriptions, the GeoJSON polygons, the 2020-tract crosswalk, and the six quantitative indicator files, is distributed on request. See [rooted-forward.org/research/data](https://rooted-forward.org/research/data#1938-holc-chicago-map-annotated) for the file list; files are provided in CSV, GeoJSON, and Parquet formats, with map tiles available as a zipped GeoTIFF bundle. All materials are released under Creative Commons Attribution-NonCommercial-ShareAlike 4.0, consistent with the source *Mapping Inequality* materials (Nelson et al. 2016). Replication code (Python scripts for the point-in-polygon matching and for the generation of the six indicator tables) is under MIT.",
  "",
  "## References",
  "",
  "Aaronson, D., Hartley, D., & Mazumder, B. (2021). The effects of the 1930s HOLC 'redlining' maps. *American Economic Journal: Economic Policy*, 13(4), 355–392.",
  "",
  "Agnew, J. (2018). *New Deal Banking: The Home Owners' Loan Corporation and the Transformation of American Mortgage Finance*. Ithaca: Cornell University Press.",
  "",
  "Appel, I., & Nickerson, J. (2016). Pockets of poverty: The long-term effects of redlining. Working paper, Johns Hopkins Carey Business School.",
  "",
  "Bell, G. D. (1995). *Chicago's Near South Side: A Neighborhood History*. Chicago: Chicago Historical Society.",
  "",
  "Chicago Department of Public Health (2023). *Environmental Health Tracker: PM2.5 Annual Means, 2023*. Chicago.",
  "",
  "Chicago Public Schools (2014). *School Actions Archive, 2013 Consolidation List*. Chicago.",
  "",
  "Cook County Assessor's Office (2024). *Residential Vacancy File, Tax Year 2024*. Chicago.",
  "",
  "Faber, J. W. (2020). We built this: Consequences of New Deal era intervention in America's racial geography. *American Sociological Review*, 85(5), 739–775.",
  "",
  "Fishback, P. V., Kantor, S., & Wallis, J. J. (2007). Can the New Deal's three Rs be rehabilitated? A program-by-program, county-by-county analysis. *Explorations in Economic History*, 44(4), 535–557.",
  "",
  "Gotham, K. F. (2000). Urban space, restrictive covenants and the origins of racial residential segregation in a US city, 1900–50. *International Journal of Urban and Regional Research*, 24(3), 616–633.",
  "",
  "Hillier, A. E. (2003). Redlining and the Home Owners' Loan Corporation. *Journal of Urban History*, 29(4), 394–420.",
  "",
  "Hirsch, A. R. (1998). *Making the Second Ghetto: Race and Housing in Chicago, 1940–1960* (2nd ed.). Chicago: University of Chicago Press.",
  "",
  "Home Owners' Loan Corporation (1937). *Residential Security Map Preparation: Procedural Manual*. Washington, DC: HOLC Division of Research and Statistics.",
  "",
  "Home Owners' Loan Corporation (1938). *Residential Security Map of Chicago, Illinois, with accompanying Area Descriptions*. National Archives, Record Group 195, Entry 39.",
  "",
  "Jackson, K. T. (1985). *Crabgrass Frontier: The Suburbanization of the United States*. New York: Oxford University Press.",
  "",
  "Krimmel, J. (2018). *Persistence of prejudice: Estimating the long-term effects of redlining*. Working paper, Princeton University Center for Urban Research.",
  "",
  "Markley, S. N., Hafley, J. D., & Allred, E. (2023). The durable inheritance of redlining: Intergenerational wealth and the HOLC gradient. *Socius*, 9, 1–18.",
  "",
  "Nelson, R. K., Ayers, E. L., Madron, J., & Connolly, N. D. B. (2016). *Mapping Inequality: Redlining in New Deal America*. American Panorama. Richmond: Digital Scholarship Lab, University of Richmond.",
  "",
  "Pacyga, D. A. (2009). *Chicago: A Biography*. Chicago: University of Chicago Press.",
  "",
  "Rooted Forward (2025). *The Geography of Disinvestment on Chicago's West Side*. Companion paper. Chicago: Rooted Forward.",
  "",
  "Rothstein, R. (2017). *The Color of Law: A Forgotten History of How Our Government Segregated America*. New York: Liveright.",
  "",
  "Squires, G. D. (Ed.) (1994). *From Redlining to Reinvestment: Community Responses to Urban Disinvestment*. Philadelphia: Temple University Press.",
  "",
  "Taylor, K.-Y. (2019). *Race for Profit: How Banks and the Real Estate Industry Undermined Black Homeownership*. Chapel Hill: University of North Carolina Press.",
  "",
  "USDA Economic Research Service (2024). *Food Access Research Atlas, 2024 Release*. Washington, DC: US Department of Agriculture.",
].join("\n");
