/* ------------------------------------------------------------------ */
/*  research-seed-content.ts                                           */
/* ------------------------------------------------------------------ */
/*                                                                     */
/*  Long-form body content for placeholder research entries. Kept in  */
/*  a separate file because the main research-constants.ts was        */
/*  getting too tall to navigate.                                      */
/*                                                                     */
/*  These are full, publication-ready paragraphs, written in the     */
/*  voice of Rooted Forward's research team. They are displayed on   */
/*  /research and /research/[slug] whenever Supabase returns no data */
/*  — i.e. local dev, first boot, or any environment where           */
/*  NEXT_PUBLIC_SUPABASE_URL is not configured.                        */
/*                                                                     */
/*  The bodies exercise the full markdown renderer: h2/h3 headings,  */
/*  numbered and bulleted lists, blockquotes, bold, italic, inline  */
/*  links, and footnote-style citations using the [^N] syntax.       */
/*                                                                     */
/* ------------------------------------------------------------------ */

/** Body for the Rent Pressure in the Obama Presidential Center Impact Zone brief. */
export const OBAMA_CENTER_BRIEF_BODY = [
  "## Summary",
  "",
  "Asking rents within a half-mile of the Obama Presidential Center site increased **41 percent** between 2020 and 2025, compared to **18 percent** for the South Side as a whole and **14 percent** for the city of Chicago at large. This brief documents the pattern at a monthly granularity, identifies the likely displacement trajectory for existing renters in the impact zone, and recommends a binding affordable housing covenant modeled on the one adopted by the City of San Francisco for the parcels around the Moscone Center in 2019.",
  "",
  "The analysis covers 12,480 unique rental listings scraped from Zillow, Craigslist Chicago, and the Chicago Rental Registry between January 2020 and December 2025. Methodology is in Section 3. The data underlying every chart and table in this brief is available as a downloadable CSV at the link in Appendix A.",
  "",
  "## Background",
  "",
  "The Obama Presidential Center broke ground on the southeast corner of Jackson Park in the fall of 2021 after a decade of planning, community consultation, and litigation. The University of Chicago, which led the planning effort in partnership with the Obama Foundation, estimates that the center will draw 750,000 visitors annually once it opens.[^1] The economic impact study commissioned by the Foundation projects $3.4 billion in direct and indirect investment across the South Side over the center's first twenty years of operation.",
  "",
  "That kind of investment does not enter a neighborhood without changing it. Property owners in Woodlawn and South Shore — the two community areas most proximate to the center — have treated the 2017 announcement and the 2021 groundbreaking as leading indicators for rent and sale price increases. Our analysis quantifies how much, how fast, and where the increases are concentrated.",
  "",
  "The framing question this brief answers is straightforward: *Are rents in the immediate impact zone rising faster than rents in comparable parts of the South Side?* If the answer is yes, then displacement pressure is measurably higher in that impact zone, which in turn supports a case for targeted, geography-specific tenant protections. That case is the one we make here.",
  "",
  "### What counts as the impact zone",
  "",
  "We define the OPC impact zone as the set of census tracts whose geographic centroids fall within a half-mile radius of the center's southeast corner at 63rd and South Cornell. Using the 2020 Census tract definitions, the zone contains eleven tracts: seven in Woodlawn (community area 42), three in South Shore (community area 43), and one at the northern edge of Greater Grand Crossing (community area 69). The zone has approximately 18,400 housing units, of which roughly 58 percent are renter-occupied based on 2023 ACS five-year estimates.",
  "",
  "A half-mile ring is the standard distance used in urban planning research on the \"footprint effect\" of major institutional investments.[^2] We chose it for direct comparability to studies of university campus expansions, sports venues, and transit hubs.",
  "",
  "## Data",
  "",
  "We scraped monthly asking rents from three sources:",
  "",
  "1. **Zillow**. The Zillow Research Data Portal publishes the Zillow Observed Rent Index (ZORI), a smoothed, seasonally adjusted asking-rent index at the zip code level. We used the 60637 and 60649 zip codes, which together cover the impact zone and a substantial control area.[^2]",
  "2. **Craigslist Chicago**. We used a web-scraping tool to collect the header fields (price, zip, bedrooms, square footage, posting date) of every rental listing in the 60637 and 60649 zips between January 2020 and December 2025. This produced 9,842 listings after de-duplication on (address, bedrooms, price).",
  "3. **Chicago Rental Registry**. Chicago's Department of Housing maintains a registry of all buildings with five or more rental units. The registry does not include asking rents, but it does include building-level metadata (year built, number of units, owner name, lender) that we used to cluster listings and check for coverage gaps.",
  "",
  "### Cleaning",
  "",
  "Raw listings data has well-known quality issues: duplicates across platforms, stale postings that repost at different prices, and obvious typos (a studio listed for $12,000 is either a typo or a luxury penthouse miscategorized; we excluded outliers above the 99.5th percentile). After cleaning we retained 11,983 unique listings for analysis.",
  "",
  "### Geocoding and tract assignment",
  "",
  "Every listing was geocoded using the Chicago Data Portal's address-to-lat/long API. Listings that failed geocoding (approximately 3 percent) were dropped. We then assigned each listing to a 2020 Census tract using point-in-polygon matching against the Census TIGER/Line shapefiles.[^3] The half-mile ring was defined as a buffered geometry around the OPC southeast corner and intersected with the tract polygons.",
  "",
  "## Findings",
  "",
  "### Headline result: a 41 percent increase in the impact zone",
  "",
  "The median asking rent for a two-bedroom unit in the half-mile ring rose from **$1,075 in January 2020** to **$1,516 in December 2025** — a **41 percent** increase over six years, or an effective annual compound rate of **5.9 percent**.",
  "",
  "Over the same period:",
  "",
  "- The same 60637 and 60649 zip codes *outside* the half-mile ring saw a median increase from $1,050 to $1,302 (**+24 percent**, 3.7 percent annualized).",
  "- The South Side as a whole (community areas 36 through 57 and 60 through 77, as defined by the Chicago Department of Planning) saw a median increase from $1,180 to $1,390 (**+18 percent**, 2.8 percent annualized).",
  "- The city of Chicago saw a median increase of 14 percent over the same period (2.2 percent annualized).",
  "",
  "The impact zone is rising nearly three times as fast as the city at large and more than twice as fast as the surrounding zip codes.",
  "",
  "### The gap widens over time",
  "",
  "The differential rate of increase is not constant. From January 2020 through March 2021, rents in the impact zone rose at a rate indistinguishable from the surrounding control — both around 2 percent year-over-year. The divergence begins in Q2 2021, coinciding with the OPC groundbreaking, and accelerates through 2023 and 2024.",
  "",
  "By calendar year:",
  "",
  "- **2020**: impact zone rents rose 2.1 percent; control rose 2.4 percent.",
  "- **2021**: impact zone rose 4.8 percent; control rose 3.1 percent.",
  "- **2022**: impact zone rose 7.2 percent; control rose 4.0 percent.",
  "- **2023**: impact zone rose 8.9 percent; control rose 4.2 percent.",
  "- **2024**: impact zone rose 9.4 percent; control rose 5.1 percent.",
  "- **2025**: impact zone rose 6.8 percent (through Q3); control rose 4.8 percent.",
  "",
  "The 2022-2024 acceleration corresponds with the period of most visible construction activity, media coverage, and secondary investment (new restaurants, coffee shops, a boutique hotel announced in 2023).",
  "",
  "### Unit size matters",
  "",
  "Rent pressure is not uniform across unit sizes. Studios and one-bedrooms have risen fastest:",
  "",
  "- **Studio**: median rose from $825 to $1,240 (**+50 percent**).",
  "- **One-bedroom**: $950 to $1,395 (**+47 percent**).",
  "- **Two-bedroom**: $1,075 to $1,516 (**+41 percent**).",
  "- **Three-bedroom**: $1,395 to $1,830 (**+31 percent**).",
  "- **Four-bedroom and larger**: $1,750 to $2,170 (**+24 percent**).",
  "",
  "This has a direct implication for who is being priced out: young adults, single adults, and childless couples in smaller units. Families in larger units are under less immediate pressure but are not exempt.",
  "",
  "### Concentration within the ring",
  "",
  "Within the half-mile ring, the pressure is concentrated in the northwest sector — the parcels facing the center's main entrance on 62nd Street and along Stony Island Avenue. The four tracts with the highest rates of increase are:",
  "",
  "- Tract 4205 (around 60th and Dorchester): **+54 percent**",
  "- Tract 4204 (around 63rd and Stony Island): **+49 percent**",
  "- Tract 4202 (around 62nd and Kimbark): **+48 percent**",
  "- Tract 4206 (around 65th and University): **+43 percent**",
  "",
  "The tracts at the southern edge of the ring, closest to existing South Shore retail, are rising more slowly — around 30 to 34 percent — but from a higher baseline.",
  "",
  "## What happens next",
  "",
  "Displacement studies in comparable contexts — the Barclays Center in Brooklyn, the San Francisco Giants' Mission Bay ballpark, the Atlanta BeltLine — show that the \"footprint effect\" of major institutional investments typically lasts ten to fifteen years before leveling off into a new baseline.[^4] If the OPC impact zone follows that trajectory, we should expect:",
  "",
  "- Continued rent increases of 6 to 9 percent annually through 2028, tapering to 3 to 4 percent through 2033.",
  "- Accelerated sale prices for multi-unit buildings. We did not analyze sale prices in this brief, but anecdotal evidence from the Institute for Housing Studies' Q3 2025 brief suggests two-to-four unit building sale prices in the impact zone are up more than 60 percent since 2020.",
  "- Displacement of existing tenants through lease non-renewals, rent spikes at renewal, and informal eviction (landlords \"buying out\" tenants to vacate units for rehabilitation and re-rental at market rate).",
  "- New construction of luxury units, which is already occurring at three sites in Woodlawn.",
  "",
  "Absent intervention, the impact zone will look materially different in ten years than it looks today. That is a commonplace observation about any neighborhood undergoing revitalization. The difference here is that the revitalization was publicly subsidized, through a combination of land transfers, infrastructure improvements, tax increment financing in adjacent parcels, and the direct public investment of the center itself. A subsidized investment that produces displacement is, at a policy level, a different thing than displacement produced by private capital alone.",
  "",
  "## Recommendation",
  "",
  "We recommend the Chicago Department of Housing adopt a binding affordable housing covenant attached to all residential properties within the impact zone. The covenant would:",
  "",
  "1. **Cap annual rent increases at the lesser of 3 percent or CPI** for existing tenants in residence as of the covenant's effective date, for a period of fifteen years.",
  "2. **Require landlords of buildings with five or more units who receive any form of city subsidy** — TIF proceeds, property tax abatements, low-income housing tax credits — **to set aside 30 percent of units at or below 60 percent of Area Median Income.**",
  "3. **Establish an independent monitoring body** with equal representation from Rooted Forward, the Woodlawn Community Collaborative, the Chicago Department of Housing, and two tenant representatives selected by lottery from the registry of impact zone renters.",
  "4. **Fund an anti-displacement fund** financed by a 1 percent real estate transfer tax on sales above $500,000 within the impact zone. Revenue would support emergency rental assistance, legal defense in eviction proceedings, and acquisition of multi-unit buildings for permanent affordability.",
  "5. **Require a covenant compliance report** published annually in a machine-readable format.",
  "",
  "This is not a blanket rent control proposal. It is a geography-specific, time-bounded protection, modeled on interventions adopted in comparable circumstances in other cities, for a population of renters facing a displacement pressure generated in significant part by a subsidized public investment.",
  "",
  "## Limitations",
  "",
  "Asking rent is not the same as paid rent. Leases signed before the 2020 baseline, and continuing households who have not moved or renegotiated, are not reflected in this analysis. The American Community Survey's five-year estimates of median contract rent are a partial corrective, but the 2025 release is not yet available as of this brief's publication.",
  "",
  "Craigslist data has known coverage gaps. Small-landlord listings in Woodlawn in particular are under-represented, because the neighborhood has a substantial fraction of two-to-four unit buildings whose owners list through informal channels (word of mouth, local community group bulletin boards). Our scraping of Zillow and the Rental Registry partially compensates but does not close the gap.",
  "",
  "We did not analyze the inverse trajectory: households that have moved *into* the impact zone since the groundbreaking. Displacement is about both who leaves and who arrives. A complete picture would require matched longitudinal data that we do not have access to.",
  "",
  "We recommend the Institute for Housing Studies replicate this analysis in 2027, when the ACS 2025 five-year release becomes available, and expand it to cover a matched dataset of who moved in and who moved out.",
  "",
  "## Appendix A: Data availability",
  "",
  "The cleaned data underlying this brief is available as a CSV at `rootedforward.org/research/data/obama-center-rent-panel-2020-2025.csv`. The code used to scrape, clean, and analyze the data is in our public GitHub repository under `rooted-forward/research-code`. Both are released under a Creative Commons Attribution 4.0 license. Citing as: Rooted Forward Research Team, *Rent Pressure in the Obama Presidential Center Impact Zone, 2020-2025*, Chicago: Rooted Forward, 2026.",
].join("\n");

/** Body for the Pilsen Industrial Corridor Retrospective brief. */
export const PILSEN_INDUSTRIAL_CORRIDOR_BODY = [
  "## Summary",
  "",
  "In early 2025 a group of property owners along the Pilsen Industrial Corridor, led by Corridor Capital Partners LLC, filed a zoning map amendment application to convert sixty-two parcels from M2 (light industry) to B3 (community shopping district). The application, if approved, would have permitted residential development on what had been manufacturing land continuously since the 1910s.",
  "",
  "Rooted Forward coordinated the opposition. The Committee on Zoning, Landmarks and Building Standards received 340 written comments in opposition and fewer than a dozen in support. The committee chair tabled the application pending further community engagement. A year later, the applicant has not refiled.",
  "",
  "This brief documents what the coordination effort actually did, what it did not do, and what the episode tells us about the structural pressure on industrial corridors in near-downtown neighborhoods.",
  "",
  "## The applicant and the ask",
  "",
  "Corridor Capital Partners LLC was incorporated in Delaware in November 2023. Its managing member, according to the Illinois Secretary of State filing, is an individual whose other holdings include a portfolio of roughly thirty multifamily buildings across Lincoln Park, Lakeview, and West Loop. This is not a Pilsen-based owner. It is an investor assembling position in an industrial corridor they intend to convert.",
  "",
  "The application covered sixty-two parcels totaling just over 22 acres. Most of the parcels were vacant or contained low-intensity industrial uses (a paper warehouse, two small machine shops, a metal recycling yard, a handful of truck garages). The parcels form a contiguous L-shape along 21st Street and Western Avenue, the northeast corner of the Pilsen Industrial Corridor as it was defined by the Chicago Department of Planning and Development in the 2006 Pilsen Industrial Corridor Plan.[^1]",
  "",
  "The zoning ask was a reclassification from M2 to B3. M2 is the city's \"light industry\" designation, which permits manufacturing, distribution, warehousing, and limited accessory retail. B3 is a \"community shopping district\" designation that permits a wide range of retail and commercial uses *as well as* residential above the ground floor by-right up to six stories.[^2]",
  "",
  "Because the parcels sit within a quarter-mile of the CTA Pink Line 18th Street station, the rezoning would also have triggered the city's Affordable Requirements Ordinance bonus density provisions for transit-oriented development, potentially allowing buildings of eight to ten stories with only a minimal affordable-unit set-aside.",
  "",
  "## Why the zoning matters",
  "",
  "The Pilsen Industrial Corridor is one of twenty-six designated industrial corridors in Chicago. These corridors were mapped beginning in the 1960s and formally codified in the city's 1988 zoning ordinance. The rationale is straightforward: manufacturing jobs tend to cluster in dense-infrastructure, rail-and-road-adjacent corridors, and preserving those corridors as industrial zones keeps those jobs from being pushed out by higher-margin land uses (primarily residential).",
  "",
  "Industrial jobs in Chicago pay a median of $52,000 per year, compared to $34,000 for retail and $41,000 for lodging and food services. They also have a lower racial wage gap: the median Black worker in Chicago's industrial sector earns 84 percent of what the median white worker in the same sector earns, compared to 67 percent in retail.[^3]",
  "",
  "The corridors' continued viability depends on two things. First, infrastructure — rail spurs, truck access, power and water capacity sized for industrial use. Second, the zoning itself: once a parcel flips to residential, it effectively never flips back, both because residential uses can outbid industrial for land and because adjacent industrial uses become harder to operate next to residents who complain about noise, odor, and truck traffic.",
  "",
  "This is why industrial corridor rezonings are not routine administrative matters. A rezoning is a permanent, one-way change to the long-term economic geography of a community area. The Pilsen corridor has lost 1,400 manufacturing jobs since 2000. A residential conversion of the 21st-and-Western L would accelerate that loss.",
  "",
  "## The public comment campaign",
  "",
  "Rooted Forward's organizing approach was anchored by four groups: the Pilsen Environmental Rights and Reform Organization (PERRO), the Pilsen Alliance, the Resurrection Project, and the Pilsen Neighbors Community Council. Our role was to provide the research backing, draft the shared comment template, coordinate the timing of outreach across the four groups' membership lists, and prepare three witnesses who testified at the committee hearing.",
  "",
  "The comment drive ran from April 14 through May 21, 2025. The committee hearing was held on May 28.",
  "",
  "Key statistics:",
  "",
  "- **340 written comments in opposition** — 287 individually written, 53 using all or part of our shared template.",
  "- **11 written comments in support** — 8 using the applicant's template, 3 individually written.",
  "- **7 witnesses at the hearing** — 6 in opposition (all Pilsen residents), 1 in support (the applicant's attorney).",
  "- **Outreach touched approximately 4,800 households** via PERRO's and the Pilsen Alliance's canvassing efforts.",
  "",
  "### What the comments said",
  "",
  "We read every comment in the public record. The most common arguments against the rezoning were, in descending order of frequency:",
  "",
  "1. **Loss of manufacturing jobs in the neighborhood** (58 percent of comments raised this).",
  "2. **Displacement pressure on existing residents from a speculative luxury residential conversion** (44 percent).",
  "3. **Lack of meaningful community consultation by the applicant** (39 percent).",
  "4. **Environmental concerns about repurposing industrial parcels without remediation** (28 percent).",
  "5. **Concern about downstream rezoning pressure on adjacent parcels** (22 percent).",
  "",
  "The comments in support were largely technical — arguments about the economic case for residential conversion, the affordability benefits of new supply, and the transit-oriented design principles of the proposal.",
  "",
  "### What the hearing itself looked like",
  "",
  "The May 28 committee hearing drew an overflow crowd. The committee room seats 84; on the day of the hearing, the overflow room and the hallway outside held another 120 people. The signup sheet for public testimony had 112 names.",
  "",
  "The committee chair, Alderperson Walter Burnett Jr., opened the hearing by limiting each speaker to ninety seconds. Testimony ran for two hours and twenty minutes. The applicant's attorney presented first, followed by the six community witnesses.",
  "",
  "At the conclusion of testimony, Alderperson Byron Sigcho-Lopez (25th Ward, which covers the corridor) made a motion to table the application. The motion passed 11-0 with two abstentions. The applicant did not reappear at the committee's June or July meetings, and has not refiled as of this brief's publication.",
  "",
  "## What the tabling did not do",
  "",
  "It did not solve the underlying pressure. Industrial corridors in near-downtown neighborhoods are under speculation from developers in every major American city, and the playbook is well understood. Assemble parcels through shell LLCs. Hire a well-connected land-use attorney. Apply for rezoning. If opposition defeats the first attempt, wait twelve to twenty-four months, reshape the application (fewer parcels, phased density, better-branded affordable commitments), and reapply.",
  "",
  "Our prediction is that a revised application will land by summer 2027. We have no specific information to support that prediction — it is inference from the pattern we have observed in comparable corridor rezoning fights in Chicago (the Cermak Road corridor in 2018-2021, the Goose Island rezonings of 2019-2023, the Northwest Corridor work currently underway).",
  "",
  "It also did not establish a generalizable precedent. The committee tabled the application. It did not reject it with findings. A tabled application does not create a binding standard that prevents future applications. It is a temporary deferral.",
  "",
  "## What we recommend",
  "",
  "The Department of Planning and Development should adopt a standing **Industrial Corridor Preservation Framework** that establishes a heightened review standard for rezoning applications in corridors designated as strategically important for manufacturing employment. The framework should:",
  "",
  "1. **Designate a subset of corridors as \"protected\"** based on current manufacturing employment, infrastructure capacity, and adjacency to transit. The Pilsen corridor, along with North Branch, Little Village, and Pullman, would qualify under any reasonable threshold.",
  "2. **Require an economic impact statement** from any applicant seeking to rezone in a protected corridor. The statement would quantify the manufacturing jobs at risk, the displacement pressure the rezoning would create in adjacent residential parcels, and the infrastructure capacity implications.",
  "3. **Trigger an automatic community consultation process** lasting no less than six months before the application is heard by the committee.",
  "4. **Permit the city to refuse to process an application** that does not meet the framework's minimum standards, rather than requiring a committee hearing and vote for every application that lands.",
  "",
  "This is not a moratorium. It is a heightened standard — a signal to the investor community that the city has decided certain corridors are not open for routine conversion. It would reduce the speculation pressure and, with it, the community organizing burden of defending each corridor one rezoning at a time.",
  "",
  "## What happens next",
  "",
  "Rooted Forward is preparing a follow-up research project that will map all twenty-six Chicago industrial corridors against three datasets: present-day manufacturing employment (Longitudinal Employer-Household Dynamics), infrastructure capacity (Chicago Department of Water and Com Ed service records), and ongoing rezoning application volume (the Department of Planning and Development's public docket).",
  "",
  "The goal is to produce a public, updatable dashboard that gives community organizations, alderpersons, and the Department of Planning and Development itself a common view of which corridors are under pressure and which are stable. We expect to publish the first version in late 2026.",
  "",
  "> An industrial corridor rezoning fight is not really about the sixty-two parcels on the application. It is about whether the city treats its manufacturing economy as worth preserving at a strategic level or as available for conversion on a case-by-case basis. The current answer is implicitly the second. The research here is one piece of the argument for making it explicitly the first.",
].join("\n");

/** Body for the CPD Traffic Stop Data Analysis. */
export const CPD_TRAFFIC_STOP_BODY = [
  "## Background",
  "",
  "The CPD Traffic Stop Data Transparency Act, passed by Chicago City Council in late 2024, required the Chicago Police Department to publish quarterly geocoded traffic stop data broken down by race, stop reason, outcome, and contraband recovery. The first data release, covering calendar year 2024, was published in April 2025.",
  "",
  "Rooted Forward was a co-author of the ordinance language along with the Chicago Police Accountability Task Force and the Invisible Institute. We pushed for the transparency requirement because traffic stops are the most common form of direct contact between Chicago residents and sworn police officers — approximately 290,000 stops per year — and because internal CPD data had consistently shown patterns of concentration that the public could not see. This analysis is the first external review of the public release.",
  "",
  "We worked from the publicly released quarterly CSV files, supplemented by census demographic data at the police district level and by the Chicago Police Department's existing public dashboards for contextual validation.[^1][^2]",
  "",
  "## Data",
  "",
  "The 2024 release contains 287,412 traffic stops. Each row includes:",
  "",
  "- Stop date and approximate time (rounded to the nearest fifteen minutes).",
  "- Police district where the stop occurred.",
  "- Beat code within the district.",
  "- Stop reason (pre-coded categories: moving violation, equipment, investigatory, other).",
  "- Driver race, as recorded by the officer conducting the stop.",
  "- Driver age, rounded to the nearest five years.",
  "- Duration of the stop, in minutes.",
  "- Whether a search occurred.",
  "- If a search occurred, whether contraband was recovered.",
  "- Whether an arrest occurred.",
  "- Whether a citation was issued.",
  "",
  "Notably absent from the release: officer badge numbers and the GPS coordinates of the stop itself. The release provides beat-level geography, which in Chicago averages about 0.6 square miles per beat. This is sufficient for district-level and neighborhood-level analysis but not for identifying individual officer patterns or specific intersections.",
  "",
  "We also have no access to the underlying body-worn camera footage associated with each stop. CPD retains this footage for ninety days under current policy; the 2024 stops are all now past the retention window, so independent video review is not possible.",
  "",
  "## Method",
  "",
  "We conducted three parallel analyses:",
  "",
  "1. **Geographic concentration**: for each of the twenty-two police districts, we computed the stop rate per 1,000 residents, using the 2023 ACS five-year estimates for the district's total population. We cross-tabulated this against the racial composition of the district.",
  "2. **Outcome rates**: for each district, we computed (a) the rate at which stops escalate to a search, (b) the rate at which searches recover contraband, and (c) the rate at which stops result in an arrest.",
  "3. **Disparity tests**: we applied the \"outcome test\" method from the Stanford Open Policing Project[^3] to look for statistical evidence that the threshold for initiating a search differs by driver race.",
  "",
  "Method choices we made deliberately:",
  "",
  "- We did not use stop rates alone as evidence of bias. Stop rates reflect both the decisions of individual officers and the geographic concentration of police resources; the latter is itself a policy choice but not necessarily officer-level bias. The outcome test is the cleaner instrument.",
  "- We did not attempt to impute missing or ambiguous race codes. Approximately 2 percent of stops have race coded as \"Unknown\"; these are excluded from race-based analyses.",
  "- We used the district, not the city as a whole, as the denominator for stop rates. This corrects for the concentration of police deployment.",
  "",
  "## Findings",
  "",
  "### Concentration",
  "",
  "**Fifty-eight percent of all 2024 traffic stops occurred in seven of the twenty-two police districts**, all seven of which are majority Black or Latino:",
  "",
  "- District 11 (Harrison): 8.7 percent of all stops; 91 percent Black/Latino residents.",
  "- District 7 (Englewood): 8.3 percent; 96 percent Black.",
  "- District 10 (Ogden): 8.1 percent; 81 percent Latino.",
  "- District 5 (Calumet): 8.0 percent; 95 percent Black.",
  "- District 4 (South Chicago): 8.0 percent; 82 percent Black/Latino.",
  "- District 6 (Gresham): 8.3 percent; 97 percent Black.",
  "- District 3 (Grand Crossing): 7.4 percent; 92 percent Black.",
  "",
  "These seven districts contain 39 percent of the city's population. They account for 58 percent of traffic stops. That is a ratio of 1.5x — stop density is 50 percent higher in these districts than in the rest of the city when adjusted for population.",
  "",
  "Some of this reflects deployment. These districts have higher violent crime rates, more officers per capita, and more proactive traffic enforcement as a matter of departmental strategy. But the deployment decision is itself policy, and its consequences for residents are real: a driver in District 7 was 2.4 times more likely to be stopped for a traffic violation in 2024 than a driver in, for example, District 16 (Jefferson Park).",
  "",
  "### Contraband recovery rates",
  "",
  "The stop-level contraband recovery rate — the percentage of stops that result in recovered contraband of any kind — was not meaningfully different between majority-white districts and majority-Black districts:",
  "",
  "- Majority-white districts: 6.1 percent.",
  "- Majority-Black districts: 6.4 percent.",
  "- Majority-Latino districts: 5.8 percent.",
  "- Mixed or majority-Asian districts: 5.9 percent.",
  "",
  "This is a critical finding. Contraband recovery is the operational justification for a traffic stop escalating to a search, and ultimately for the theory that proactive traffic enforcement generates public safety value. If the recovery rate is roughly the same across districts, it means the marginal stop in a majority-Black district is no more likely to produce public safety value than the marginal stop in a majority-white district. The concentration of stops in majority-Black districts therefore cannot be justified on contraband recovery grounds alone.",
  "",
  "### Post-stop outcomes",
  "",
  "Once a stop occurred, the escalation trajectory differed sharply by district demographic:",
  "",
  "- **Rate of search**: stops in majority-Black districts were **2.3x** more likely to result in a search than stops in majority-white districts (9.4 percent vs 4.1 percent).",
  "- **Rate of arrest**: **3.1x** (8.7 percent vs 2.8 percent).",
  "- **Rate of citation**: 1.4x (42 percent vs 30 percent).",
  "",
  "Even after controlling for stop reason and contraband recovery rate, the rate-of-search disparity persists at a 1.7x multiplier. The rate-of-arrest disparity persists at 2.2x.",
  "",
  "### The outcome test",
  "",
  "The Stanford outcome test examines whether the threshold for initiating a search differs by driver race. If officers apply the same threshold regardless of driver race, we would expect similar contraband recovery rates conditional on a search. If officers apply a lower threshold for Black drivers (i.e., search at weaker evidence), we would expect a lower contraband recovery rate given a search.",
  "",
  "Our outcome test finds:",
  "",
  "- Searches of white drivers: **18.7 percent** recover contraband.",
  "- Searches of Black drivers: **14.1 percent** recover contraband.",
  "- Searches of Latino drivers: **13.8 percent** recover contraband.",
  "- Searches of Asian drivers: **16.2 percent** recover contraband.",
  "",
  "The 4.6 percentage point gap between searches of white drivers and searches of Black drivers is statistically significant at the p < 0.001 level. Under the outcome test logic, this is evidence that the threshold for initiating a search of a Black driver is lower than the threshold for initiating a search of a white driver.",
  "",
  "This is consistent with findings from Stanford's multi-city analysis of traffic stop data.[^3] It is not unique to Chicago.",
  "",
  "## Limitations",
  "",
  "The released data excludes officer badge numbers and does not provide GPS coordinates more granular than beat-level. This has three downstream consequences for accountability:",
  "",
  "1. **We cannot identify individual officers whose stop patterns are outliers.** The body of academic and journalistic work that has been done on traffic stop disparity, from Sacramento to Oakland to Brooklyn, has consistently found that a relatively small share of officers account for a disproportionate share of stops — particularly the stops that escalate to search. Without badge numbers, we cannot check whether that pattern holds in Chicago.",
  "2. **We cannot identify specific intersections or locations that are hotspots for concentrated enforcement.** Beat-level geography is too coarse to surface the specific street corners where stops cluster.",
  "3. **We cannot cross-reference the data against CPD's internal Complaint Register database** to see whether officers named in misconduct complaints are among the heaviest traffic-stop conductors.",
  "",
  "We also have no means of validating the race codes recorded by officers. The Stanford Open Policing Project has noted that officer-recorded race can differ from driver self-identification, and that this difference is non-random.[^3] Chicago's release does not include a comparable validation mechanism.",
  "",
  "## Recommendations",
  "",
  "The Public Safety Committee should introduce amending legislation to the Traffic Stop Data Transparency Act to require:",
  "",
  "1. **Officer badge numbers** in all future releases, subject to a six-month lag to protect active investigations.",
  "2. **Parcel-level GPS coordinates**, in line with the level of granularity the Cincinnati Police Department has released since 2022.",
  "3. **Driver self-identified race**, collected at the time of the stop in addition to the officer's recorded race.",
  "4. **Retention of body-worn camera footage for stops that escalate to a search or arrest** for a minimum of three years, to support independent post-hoc review.",
  "",
  "The data that CPD has currently released is a substantial improvement over nothing. It is not sufficient for meaningful accountability. The gaps in the release are the gaps that prevent external actors — journalists, community organizations, civil rights litigators — from connecting individual officer patterns to departmental policy.",
  "",
  "## A note on methodology",
  "",
  "All the code and intermediate datasets used in this analysis are available in the `rooted-forward/cpd-traffic-analysis` GitHub repository. We have made every effort to document choices that could affect the findings, and we welcome replication and critique.",
  "",
  "The single most important thing an external analyst can do with this data is ask what we have *not* asked. We invite researchers, journalists, and civic technologists to use this release for their own work. The release exists because community organizations, academic researchers, and journalists have been pushing for it for two decades; it will only serve its purpose if people continue to engage with it after the first wave of attention has passed.",
].join("\n");
