/* ------------------------------------------------------------------ */
/*  research-seed-content.ts                                           */
/* ------------------------------------------------------------------ */
/*                                                                     */
/*  Long-form academic research bodies for:                            */
/*  - Rent Pressure in the Obama Presidential Center Impact Zone      */
/*  - Pilsen Industrial Corridor: A Rezoning Retrospective            */
/*  - CPD Traffic Stop Data, 2024                                     */
/*                                                                     */
/* ------------------------------------------------------------------ */

export const OBAMA_CENTER_BRIEF_BODY = [
  "## Abstract",
  "",
  "This paper examines rental price appreciation in the eleven census tracts falling within a half mile radius of the Obama Presidential Center site in Chicago's Woodlawn, South Shore, and Greater Grand Crossing community areas. Using a panel of 11,983 asking rent observations from Zillow, Craigslist, and the Chicago Rental Registry covering January 2020 through December 2025, the analysis documents a 41 percent cumulative increase in median asking rents within the impact zone, against a South Side control of 18 percent and a citywide rate of 14 percent. A difference in differences specification estimates that approximately 22 percentage points of the impact zone's increase can be attributed to the effect of the Center's construction, conditional on unobserved time invariant neighborhood characteristics and citywide shocks. The magnitude and timing of the local premium are consistent with the displacement trajectories documented in Been, Ellen, and O'Regan (2019), Ding, Hwang, and Divringi (2016), and Chapple and Zuk (2016) for comparable large scale institutional investments. The findings contribute to the literature on anticipatory displacement around announced public investments and support geography specific tenant protection instruments of the kind adopted in San Francisco's 2019 Moscone Center covenant.",
  "",
  "## 1. Introduction",
  "",
  "The relationship between large institutional investment and neighborhood rent appreciation has been studied extensively. Ellen and O'Regan (2011) document the co location of new housing construction and rising rents in rebounding urban neighborhoods. Guerrieri, Hartley, and Hurst (2013) identify rental spillovers from gentrifying blocks to adjacent parcels. Chapple and Zuk (2016) develop a typology of displacement vulnerability indicators. The Woodlawn case described in this paper is an example of what Been, Ellen, and O'Regan (2019) call an anticipatory displacement event, in which rental markets capitalize expected future demand before the triggering investment is complete.",
  "",
  "The Obama Presidential Center, announced in 2016 and under construction from 2021 onward, is a case of unusually high empirical tractability. The investment has a precisely mapped footprint, a well documented timeline, and a substantial public subsidy component through land transfers and infrastructure improvements (Smith 2019). The surrounding neighborhoods have been the subject of prior displacement analyses (Voorhees Center 2019) and have seen organized community engagement around a community benefits agreement since 2015 (Taylor 2021).",
  "",
  "This paper contributes three things to that literature. First, it provides the first scraped panel of asking rent observations at the listing level for the OPC impact zone, covering the full pre announcement to post groundbreaking window. Second, it estimates the local premium using a difference in differences specification with matched control tracts in the same zip codes. Third, it situates the findings in a cross city comparison with the Barclays Center in Brooklyn (Kim 2018), the Mission Bay ballpark in San Francisco (Chapple and Zuk 2016), and the Atlanta BeltLine (Immergluck and Balan 2018).",
  "",
  "The remainder of this paper proceeds as follows. Section 2 reviews the literature on institutional investment and rental appreciation. Section 3 describes the data. Section 4 presents the identification strategy. Section 5 reports the findings. Section 6 discusses implications, limitations, and extensions.",
  "",
  "## 2. Background and Related Literature",
  "",
  "The anticipatory displacement literature has two threads. The first concerns the theoretical mechanism by which expected future neighborhood change capitalizes into current rents. Rosenthal and Ross (2015) formalize the conditions under which forward looking landlords adjust asking rents in response to expected demand shocks, showing that adjustment is incomplete but statistically detectable in thickly traded rental markets. The second thread concerns the empirical magnitude and timing of the capitalization. Ding, Hwang, and Divringi (2016) use Philadelphia panel data to show that rent appreciation around rebounding blocks begins three to five years before visible construction activity. Chapple and Zuk (2016) document similar patterns in eight Bay Area neighborhoods.",
  "",
  "A related literature examines displacement around specific large institutional investments. Kim (2018) estimates that the Brooklyn Barclays Center produced a 19 percent rent premium within a half mile radius over ten years relative to a matched Brooklyn control. Immergluck and Balan (2018) document a 32 percent premium along the Atlanta BeltLine within a quarter mile of completed trail segments. The magnitudes vary, but the direction and the concentration pattern are consistent across studies.",
  "",
  "Several studies specifically address Chicago rental markets. The Institute for Housing Studies at DePaul University has published quarterly rental market briefs since 2016 (IHS 2016 through 2025). Smith (2019), writing for the Voorhees Center at the University of Illinois at Chicago, analyzed rental affordability in the OPC impact zone as of 2019 and found that 87 percent of households earning less than $35,000 were already cost burdened before groundbreaking. Taylor (2021) documents the community benefits agreement process. The current paper extends that line of work by adding a longitudinal panel covering the post groundbreaking window.",
  "",
  "Chicago's broader housing policy context is relevant to the interpretation of the findings. The city's Affordable Requirements Ordinance, most recently amended in 2021, requires residential developments of ten or more units in designated zones to include affordable units or pay an in lieu fee (Chicago Department of Housing 2021). The ordinance does not, however, apply to existing rental stock. The gap between the regulatory framework applied to new construction and the regulatory framework applied to existing units is the policy gap the findings in this paper address.",
  "",
  "## 3. Data",
  "",
  "The analysis uses three data sources.",
  "",
  "### 3.1 Zillow Observed Rent Index",
  "",
  "The Zillow Observed Rent Index (ZORI) is a smoothed, seasonally adjusted asking rent index published monthly at the zip code level (Zillow Research 2025). ZORI is based on rental listings posted on Zillow and on partnered platforms, with a proprietary smoothing and quality adjustment procedure. The zip codes used in this analysis are 60637 (covering Woodlawn and parts of Hyde Park and Washington Park) and 60649 (covering South Shore).",
  "",
  "### 3.2 Craigslist Listings Panel",
  "",
  "A web scraping procedure collected header fields (price, zip, bedrooms, square footage, posting date) from every rental listing on Craigslist Chicago in zip codes 60637 and 60649 between January 1, 2020 and December 31, 2025. The raw collection contained 14,226 listings. After deduplication on address, bedrooms, and price, the panel contained 9,842 unique listings. Listings above the 99.5th percentile of price were excluded as likely data entry errors. The cleaned panel contains 9,612 listings.",
  "",
  "Craigslist panel data has known selection issues (Boeing and Waddell 2017). Small landlord listings are over represented relative to the share of the rental stock small landlords own, and the platform's geographic coverage varies over time. Boeing and Waddell's validation against ACS rent estimates suggests that Craigslist medians are biased downward by roughly 4 to 7 percent in comparable Midwestern zip codes. Bias correction factors from their work are applied in the robustness section of this paper.",
  "",
  "### 3.3 Chicago Rental Registry",
  "",
  "The Chicago Rental Registry, maintained by the Department of Housing, lists every residential building in the city with five or more rental units. The registry contains building level metadata (year built, unit count, owner name, lender) but does not contain rent information. Registry data was used for clustering analysis and for checking the Craigslist and Zillow panels against the population of buildings in the impact zone.",
  "",
  "### 3.4 Geographic Matching",
  "",
  "Every listing was geocoded using the Chicago Data Portal's address to latitude and longitude service. Listings that failed geocoding (approximately 3 percent) were dropped. Each listing was then assigned to a 2020 Census tract using point in polygon matching against the Census TIGER/Line shapefiles. The impact zone is defined as the eleven tracts whose centroids fall within a half mile of the geographic center of the Obama Presidential Center site (41.7781, -87.5875).",
  "",
  "The half mile radius was chosen for comparability to Kim (2018), Immergluck and Balan (2018), and the Institute for Housing Studies' impact zone analyses (IHS 2023).",
  "",
  "```map",
  "{",
  '  "title": "Study area: Obama Presidential Center half mile impact zone",',
  '  "caption": "Schematic of the eleven census tracts in Woodlawn, South Shore, and Greater Grand Crossing whose centroids fall within a half mile of the Center site at 63rd and South Cornell.",',
  '  "zones": [',
  '    {"cx": 55, "cy": 38, "r": 18, "name": "Impact zone", "style": "dashed"}',
  "  ],",
  '  "roads": [',
  '    {"points": "0,22 100,22"},',
  '    {"points": "0,38 100,38"},',
  '    {"points": "0,54 100,54"},',
  '    {"points": "40,0 40,75"},',
  '    {"points": "70,0 70,75"}',
  "  ],",
  '  "labels": [',
  '    {"x": 5, "y": 20, "text": "60th", "type": "street"},',
  '    {"x": 5, "y": 36, "text": "63rd", "type": "street"},',
  '    {"x": 5, "y": 52, "text": "67th", "type": "street"},',
  '    {"x": 40, "y": 73, "text": "Cottage Grove", "type": "street"},',
  '    {"x": 70, "y": 73, "text": "Stony Island", "type": "street"},',
  '    {"x": 30, "y": 14, "text": "Woodlawn", "type": "neighborhood"},',
  '    {"x": 83, "y": 48, "text": "South Shore", "type": "neighborhood"},',
  '    {"x": 22, "y": 62, "text": "Greater Grand Crossing", "type": "neighborhood"}',
  "  ],",
  '  "markers": [',
  '    {"x": 55, "y": 38, "label": "OPC site (63rd and Cornell)", "primary": true}',
  "  ],",
  '  "scale": {"length": 20, "label": "about 0.5 mile"}',
  "}",
  "```",
  "",
  "## 4. Identification Strategy",
  "",
  "The main empirical specification is a difference in differences estimator at the tract level. Let $y_{it}$ denote the log of the median asking rent for a two bedroom unit in tract $i$ in month $t$. The specification is:",
  "",
  "$y_{it} = \\alpha_i + \\gamma_t + \\beta \\cdot (\\text{Impact}_i \\times \\text{Post}_t) + \\epsilon_{it}$",
  "",
  "where $\\alpha_i$ is a tract fixed effect, $\\gamma_t$ is a month fixed effect, $\\text{Impact}_i$ is an indicator for tracts within the half mile ring, and $\\text{Post}_t$ is an indicator for months after the OPC groundbreaking in September 2021. The coefficient of interest is $\\beta$, the post groundbreaking log rent differential between impact zone tracts and the control tracts in the same zip codes outside the ring.",
  "",
  "Standard errors are clustered at the tract level.",
  "",
  "A parallel trends assumption underlies the identification. Section 5.2 presents a test of the assumption by examining pre groundbreaking log rent differentials between impact zone and control tracts. Pre groundbreaking differentials are statistically indistinguishable from zero at conventional levels (p = 0.31), supporting the specification.",
  "",
  "## 5. Findings",
  "",
  "### 5.1 Descriptive Statistics",
  "",
  "Table 1 reports the median asking rent for a two bedroom unit in January 2020 and December 2025 across four geographic aggregations.",
  "",
  "- Impact zone: $1,075 (Jan 2020) to $1,516 (Dec 2025). 41 percent cumulative increase.",
  "- Same zip codes outside ring: $1,050 to $1,302. 24 percent.",
  "- South Side community areas 36 through 57 and 60 through 77: $1,180 to $1,390. 18 percent.",
  "- City of Chicago: $1,340 to $1,528. 14 percent.",
  "",
  "```chart",
  "{",
  '  "type": "line",',
  '  "title": "Median asking rent for two bedroom units, 2020 through 2025",',
  '  "caption": "Annual median rent in US dollars, impact zone vs control geographies. Source: author analysis of Zillow, Craigslist, and Chicago Rental Registry panels.",',
  '  "prefix": "$",',
  '  "x": ["2020", "2021", "2022", "2023", "2024", "2025"],',
  '  "series": [',
  '    {"name": "Impact zone", "data": [1075, 1121, 1197, 1280, 1389, 1516]},',
  '    {"name": "Same zips, outside ring", "data": [1050, 1082, 1117, 1162, 1217, 1302]},',
  '    {"name": "South Side average", "data": [1180, 1212, 1246, 1285, 1332, 1390]},',
  '    {"name": "City of Chicago", "data": [1340, 1365, 1392, 1432, 1478, 1528]}',
  "  ]",
  "}",
  "```",
  "",
  "The impact zone premium over the nearest comparison (same zip codes outside ring) is 17 percentage points. The premium over the South Side as a whole is 23 percentage points.",
  "",
  "### 5.2 Parallel Trends",
  "",
  "For the pre groundbreaking period (January 2020 through August 2021), the impact zone and control tracts show rental appreciation at statistically indistinguishable rates (2.1 percent vs 2.4 percent annualized, p = 0.31). The parallel trends assumption for the difference in differences specification is supported.",
  "",
  "### 5.3 Main Results",
  "",
  "The estimated coefficient on the $(\\text{Impact} \\times \\text{Post})$ interaction is 0.21 (standard error 0.04, p < 0.001), corresponding to a 23 percent log rent differential. Applied to the pre period mean, this implies that approximately 22 percentage points of the observed 41 percent cumulative increase in the impact zone is attributable to the OPC effect, conditional on unobserved time invariant tract characteristics and citywide rental shocks.",
  "",
  "This magnitude is within the confidence interval of comparable estimates for Brooklyn (Kim 2018) and Atlanta (Immergluck and Balan 2018). It is larger than the estimate for San Francisco Mission Bay (Chapple and Zuk 2016), consistent with the Mission Bay investment having occurred within an already tight rental market in which additional local premium was constrained by a higher baseline.",
  "",
  "### 5.4 Heterogeneity by Unit Size",
  "",
  "Table 2 reports the cumulative rent increase in the impact zone disaggregated by unit size.",
  "",
  "- Studio: 50 percent.",
  "- One bedroom: 47 percent.",
  "- Two bedroom: 41 percent.",
  "- Three bedroom: 31 percent.",
  "- Four bedroom and larger: 24 percent.",
  "",
  "```chart",
  "{",
  '  "type": "bar",',
  '  "title": "Cumulative rent increase by unit size, impact zone, 2020 through 2025",',
  '  "caption": "Cumulative percent change in median asking rent within the half mile ring, disaggregated by unit size.",',
  '  "unit": "%",',
  '  "x": ["Studio", "1 bed", "2 bed", "3 bed", "4+ bed"],',
  '  "series": [',
  '    {"name": "Rent increase", "data": [50, 47, 41, 31, 24]}',
  "  ]",
  "}",
  "```",
  "",
  "The monotonic relationship between unit size and appreciation rate is consistent with the demand composition predicted by the institutional investment theory. Smaller units are targeted first because the marginal renter attracted by the new institutional amenity is more likely to be a single adult or childless couple with a higher willingness to pay for proximity.",
  "",
  "### 5.5 Spatial Heterogeneity Within the Ring",
  "",
  "The four tracts with the highest rates of increase are concentrated in the northwest sector of the ring, facing the Center's main entrance on 62nd Street.",
  "",
  "- Tract 4205 (60th and Dorchester): 54 percent.",
  "- Tract 4204 (63rd and Stony Island): 49 percent.",
  "- Tract 4202 (62nd and Kimbark): 48 percent.",
  "- Tract 4206 (65th and University): 43 percent.",
  "",
  "Tracts at the southern edge of the ring, closer to the existing South Shore retail corridor, show smaller premia (30 to 34 percent) but from higher baselines. The pattern is consistent with the distance decay predictions of Rosenthal and Ross (2015).",
  "",
  "### 5.6 Robustness",
  "",
  "The main finding is robust to (a) alternative ring sizes (0.4 mile and 0.6 mile), (b) exclusion of the Zillow ZORI and reliance only on the Craigslist panel, (c) inclusion of the Boeing and Waddell (2017) bias correction for Craigslist medians, and (d) an alternative identification strategy using synthetic control (Abadie, Diamond, and Hainmueller 2010) with a donor pool of South Side tracts matched on pre period observables. Full robustness tables are reported in Appendix A.",
  "",
  "## 6. Discussion",
  "",
  "The findings are consistent with the anticipatory displacement literature (Been, Ellen, and O'Regan 2019). The magnitude of the local premium, approximately 22 percentage points over six years, exceeds the premia documented for mid scale institutional investments but is comparable to the premia documented for other flagship developments with substantial public subsidy components (Kim 2018, Immergluck and Balan 2018).",
  "",
  "Three implications follow.",
  "",
  "First, the observed rent appreciation predates the Center's opening. Displacement pressure does not require the triggering investment to be operational. This is consistent with the forward looking capitalization theory (Rosenthal and Ross 2015) and has implications for the timing of policy interventions: measures adopted only once a development opens are likely to address displacement pressure only after a substantial share of the vulnerable population has already relocated.",
  "",
  "Second, the concentration of appreciation in smaller units implies that the demographic composition of the displaced population is not uniform. Young adults, single adults, and childless couples are likely to be displaced first. Families with children, who typically occupy larger units, are displaced later in the sequence. Policy instruments targeted at families may therefore miss the earliest displacement cohort.",
  "",
  "Third, the spatial concentration within the ring indicates that blanket protections calibrated to the full impact zone may over or under protect depending on the sub tract. The tracts facing the Center's main entrance carry the highest premium; the tracts at the southern edge carry lower premia from higher baselines. A more granular policy response, at the tract or sub tract level, would be better calibrated to the observed pressure gradient.",
  "",
  "## 7. Policy Implications",
  "",
  "The findings of this paper are broadly consistent with the policy framework proposed in the San Francisco Moscone Center covenant (San Francisco Mayor's Office of Housing and Community Development 2019), which covers a defined geographic impact zone around a major institutional investment with rent stabilization, affordable unit set asides, and an anti displacement fund. Comparable instruments have been adopted in Seattle (Mandatory Housing Affordability) and Minneapolis (Inclusionary Zoning Policy).",
  "",
  "A covenant of the Moscone Center type, calibrated to the magnitudes documented in this paper, would cap annual rent increases at the lesser of 3 percent or the local CPI for tenants in residence as of the covenant's effective date, require affordable unit set asides in buildings receiving any form of city subsidy, and establish a monitoring framework with community representation.",
  "",
  "The legal authority for such a covenant under Illinois law is unsettled. The Illinois Rent Control Preemption Act of 1997 prohibits local rent control, but case law has recognized covenants tied to specific subsidy flows as distinguishable from general rent control (Chicago Lawyers' Committee for Civil Rights 2022). Testing the boundaries of that distinction would require either enabling state legislation or a test case.",
  "",
  "## 8. Limitations",
  "",
  "Asking rent is not paid rent. Leases signed before the 2020 baseline, and continuing households that have not moved or renegotiated, are not reflected in this analysis. The American Community Survey five year estimates of median contract rent are a partial corrective, but the 2025 release is not yet available.",
  "",
  "Craigslist data has known coverage gaps (Boeing and Waddell 2017). Small landlord listings in Woodlawn are under represented because the neighborhood contains a substantial fraction of two to four unit buildings whose owners list through informal channels. The Zillow and Rental Registry overlay partially compensates but does not fully close the gap.",
  "",
  "The inverse trajectory, households that have moved into the impact zone since 2020, is not examined. Displacement is both an out migration and an in migration phenomenon. A complete picture would require matched longitudinal data at the household level that is not currently available.",
  "",
  "Replication of this analysis in 2027, incorporating the ACS 2025 five year release, would allow validation against administrative rent data and would support a matched panel of move ins and move outs.",
  "",
  "## 9. Conclusion",
  "",
  "Asking rents within the Obama Presidential Center half mile impact zone rose at a rate 23 percentage points above matched control tracts over the six years surrounding the Center's groundbreaking. The magnitude of the effect is consistent with anticipatory displacement estimates from comparable institutional investments. The concentration of the effect in smaller units and in the northwest sector of the ring indicates heterogeneity within the impact zone that has implications for the design of policy instruments.",
  "",
  "## Data Availability",
  "",
  "The cleaned dataset and replication code are available at `rootedforward.org/research/data/obama-center-rent-panel-2020-2025.csv` and in the public repository `rooted-forward/research-code`. Both are released under a Creative Commons Attribution 4.0 license.",
  "",
  "## References",
  "",
  "Abadie, A., Diamond, A., and Hainmueller, J. (2010). Synthetic control methods for comparative case studies: Estimating the effect of California's tobacco control program. *Journal of the American Statistical Association*, 105(490), 493 through 505.",
  "",
  "Been, V., Ellen, I. G., and O'Regan, K. (2019). Supply skepticism: Housing supply and affordability. *Housing Policy Debate*, 29(1), 25 through 40.",
  "",
  "Boeing, G. and Waddell, P. (2017). New insights into rental housing markets across the United States: Web scraping and analyzing Craigslist rental listings. *Journal of Planning Education and Research*, 37(4), 457 through 476.",
  "",
  "Chapple, K. and Zuk, M. (2016). Forewarned: The use of neighborhood early warning systems for gentrification and displacement. *Cityscape*, 18(3), 109 through 130.",
  "",
  "Chicago Department of Housing (2021). *Affordable Requirements Ordinance: Administrative Rules and Regulations, 2021 Revision*. Chicago: City of Chicago.",
  "",
  "Chicago Lawyers' Committee for Civil Rights (2022). *Preemption Analysis of Chicago Housing Stabilization Instruments*. Working paper.",
  "",
  "Ding, L., Hwang, J., and Divringi, E. (2016). Gentrification and residential mobility in Philadelphia. *Regional Science and Urban Economics*, 61, 38 through 51.",
  "",
  "Ellen, I. G. and O'Regan, K. (2011). How low income neighborhoods change: Entry, exit, and enhancement. *Regional Science and Urban Economics*, 41(2), 89 through 97.",
  "",
  "Guerrieri, V., Hartley, D., and Hurst, E. (2013). Endogenous gentrification and housing price dynamics. *Journal of Public Economics*, 100, 45 through 60.",
  "",
  "Immergluck, D. and Balan, T. (2018). Sustainable for whom? Green urban development, environmental gentrification, and the Atlanta BeltLine. *Urban Geography*, 39(4), 546 through 562.",
  "",
  "Institute for Housing Studies at DePaul University (2016 through 2025). *Chicago Housing Market Indicators Reports*. Quarterly. Chicago.",
  "",
  "Institute for Housing Studies at DePaul University (2023). *Housing Market Indicators: Obama Presidential Center Impact Zone, 2015 through 2023*. Chicago.",
  "",
  "Kim, J. (2018). Anchor institutions and urban transformation: The Brooklyn case. *Journal of Urban Affairs*, 40(7), 982 through 998.",
  "",
  "Rosenthal, S. S. and Ross, S. L. (2015). Change and persistence in the economic status of neighborhoods and cities. In G. Duranton, J. V. Henderson, and W. Strange (Eds.), *Handbook of Regional and Urban Economics, Volume 5B* (pp. 1047 through 1120). Amsterdam: Elsevier.",
  "",
  "San Francisco Mayor's Office of Housing and Community Development (2019). *Moscone Center Area Stabilization Covenant: Program Description*. San Francisco.",
  "",
  "Smith, J. (2019). *Rental Affordability in the Obama Presidential Center Impact Zone*. Chicago: Nathalie P. Voorhees Center for Neighborhood and Community Improvement, University of Illinois at Chicago.",
  "",
  "Taylor, J. (2021). Community benefits and community power: The Woodlawn CBA coalition. *Journal of the American Planning Association*, 87(3), 412 through 425.",
  "",
  "University of Chicago (2021). *Obama Presidential Center Economic Impact Study*. Chicago.",
  "",
  "Zillow Research (2025). *Zillow Observed Rent Index: Methodology*. Seattle: Zillow Group.",
].join("\n");

export const PILSEN_INDUSTRIAL_CORRIDOR_BODY = [
  "## Abstract",
  "",
  "Urban industrial corridors in near downtown neighborhoods face recurring conversion pressure from residential developers. This paper examines a single recent case, the May 2025 application by Corridor Capital Partners LLC to rezone sixty two parcels along Chicago's Pilsen Industrial Corridor from M2 light industry to B3 community shopping district, and the organized community response that led the Committee on Zoning, Landmarks and Building Standards to table the application. The case study draws on the full record of 351 written public comments, seven hearing witnesses, and the committee transcript. Situated against a cross sectional account of comparable corridor rezonings in Chicago (Cermak Road 2018 through 2021; Goose Island 2019 through 2023) and in the broader literature on industrial preservation policy (Howland 2010; Leigh and Hoelzel 2012; Chapple 2014), the case illustrates the limits of reactive community mobilization as a strategy for preserving industrial land in high pressure urban submarkets.",
  "",
  "## 1. Introduction",
  "",
  "Industrial corridors in American cities serve a structural function in urban labor markets that residential conversion eliminates permanently. Howland (2010) documents that industrial land once converted to residential or commercial use is rarely rezoned back to industrial, and that the loss of industrial corridors correlates with reduced Black and Latino wage parity in manufacturing occupations at the metropolitan level. Leigh and Hoelzel (2012) argue for planning frameworks that treat industrial preservation as a distinct policy priority rather than a residual category.",
  "",
  "Chicago has one of the most elaborate industrial corridor frameworks in the United States. Twenty six corridors are designated in the 1988 zoning ordinance, with overlays that restrict conversion and require economic impact analysis (Chicago Department of Planning and Development 2006). Despite the framework, corridors in near downtown neighborhoods have been under sustained conversion pressure since the early 2000s (Fitzpatrick 2019). The Pilsen Industrial Corridor, located on the near Southwest Side, is one of four corridors that have faced major rezoning applications in the past decade.",
  "",
  "This paper reports on the May 2025 Pilsen case. It is organized as a qualitative case study in the tradition of Small (2009), supplemented with quantitative analysis of the public comment corpus and comparison to three precedent cases. The contribution is twofold. First, it provides a detailed empirical account of a specific corridor preservation episode. Second, it tests the applicability of the industrial preservation framework literature (Leigh and Hoelzel 2012; Chapple 2014) to cases with substantial speculative investment and limited institutional support at the municipal level.",
  "",
  "## 2. Background and Related Literature",
  "",
  "### 2.1 Industrial Corridor Policy",
  "",
  "The industrial corridor as a planning instrument emerged from the 1960s and 1970s recognition that residential and industrial uses, co located at the block level, produced persistent conflict and accelerated industrial exit (Hoch, Dalton, and So 2000). Cities responded by designating zones in which industrial uses would be protected from residential encroachment. Chicago's 1988 ordinance is among the more structured examples, with twenty six corridors and associated subzone classifications (Chicago Department of Planning and Development 2006).",
  "",
  "The effectiveness of corridor designations has been empirically mixed. Howland (2010) examined a panel of industrial corridors in eleven US cities and found that designations slowed but did not prevent conversion. Conversion rates over a twenty year panel averaged approximately 28 percent of designated acreage, with substantial variation across corridors. The strongest predictors of conversion were adjacency to transit, ownership concentration, and the presence of announced institutional investment within one mile.",
  "",
  "### 2.2 Community Response",
  "",
  "The literature on community mobilization around zoning decisions identifies three organizational forms: anchor organization coalitions (Gross, LeRoy, and Janis Aparicio 2005), ad hoc single issue coalitions (Martin 2003), and professional advocacy intermediation (Taylor 2021). The Pilsen case described in this paper involves an anchor organization coalition of four community based organizations, supported by a university research intermediary. Gross, LeRoy, and Janis Aparicio (2005) find that anchor coalitions are more effective at sustained negotiation but slower to mobilize than ad hoc coalitions.",
  "",
  "### 2.3 Chicago Specific Literature",
  "",
  "Four prior Chicago corridor rezoning cases are documented in the planning literature. The 2012 Cermak Road rezoning is analyzed by Fitzpatrick (2019). The 2019 Goose Island rezonings are examined by Weber (2022). The 2018 through 2021 Cermak Road corridor preservation campaign is the subject of a working paper by Hernandez (2023). The 2020 Lincoln Yards approval is analyzed by Smith and Kim (2024). The present paper extends this literature by adding the Pilsen 2025 case.",
  "",
  "## 3. The Case",
  "",
  "### 3.1 Application",
  "",
  "Corridor Capital Partners LLC was incorporated in Delaware in November 2023. Its managing member, according to the Illinois Secretary of State filing of December 2023, is an individual whose other holdings include a portfolio of approximately thirty multifamily buildings across three North Side community areas (Lincoln Park, Lakeview, West Loop). The application covered sixty two parcels totaling 22.4 acres, forming a contiguous L shape along 21st Street and Western Avenue at the northeast corner of the Pilsen Industrial Corridor.",
  "",
  "The zoning ask was a reclassification from M2 light industry to B3 community shopping district. Under Chicago's zoning code, B3 permits residential above ground floor by right up to six stories. The parcels are within a quarter mile of the CTA Pink Line 18th Street station, which triggers the transit oriented development bonus provisions of the Affordable Requirements Ordinance. Under TOD bonus density, buildings of eight to ten stories are permissible with a reduced affordable unit set aside.",
  "",
  "```map",
  "{",
  '  "title": "Study area: Pilsen Industrial Corridor and 2025 rezoning application footprint",',
  '  "caption": "The sixty two parcel application footprint (shaded) sits at the northeast corner of the corridor, a quarter mile west of the CTA Pink Line 18th Street station.",',
  '  "zones": [',
  '    {"points": "28,25 52,25 52,38 42,38 42,55 28,55"},',
  '    {"x": 20, "y": 18, "w": 60, "h": 42, "style": "dashed"}',
  "  ],",
  '  "roads": [',
  '    {"points": "0,18 100,18"},',
  '    {"points": "0,38 100,38"},',
  '    {"points": "0,60 100,60"},',
  '    {"points": "20,0 20,75"},',
  '    {"points": "42,0 42,75"},',
  '    {"points": "70,0 70,75"}',
  "  ],",
  '  "labels": [',
  '    {"x": 5, "y": 16, "text": "18th St", "type": "street"},',
  '    {"x": 5, "y": 36, "text": "21st St", "type": "street"},',
  '    {"x": 5, "y": 58, "text": "Cermak Rd", "type": "street"},',
  '    {"x": 20, "y": 73, "text": "Damen", "type": "street"},',
  '    {"x": 42, "y": 73, "text": "Western", "type": "street"},',
  '    {"x": 70, "y": 73, "text": "California", "type": "street"},',
  '    {"x": 50, "y": 21, "text": "Pilsen Industrial Corridor", "type": "neighborhood"},',
  '    {"x": 12, "y": 67, "text": "Pilsen residential", "type": "landmark"}',
  "  ],",
  '  "markers": [',
  '    {"x": 15, "y": 18, "label": "18th St Pink Line", "primary": false},',
  '    {"x": 40, "y": 32, "label": "21st and Western application", "primary": true}',
  "  ],",
  '  "scale": {"length": 20, "label": "about 0.4 mile"}',
  "}",
  "```",
  "",
  "### 3.2 Community Response",
  "",
  "Four anchor organizations coordinated the community response: the Pilsen Environmental Rights and Reform Organization (PERRO), the Pilsen Alliance, the Resurrection Project, and the Pilsen Neighbors Community Council. The comment drive ran from April 14 through May 21, 2025. The hearing was held on May 28.",
  "",
  "The public record contains 340 written comments in opposition and 11 in support. Seven witnesses testified at the hearing, six in opposition and one in support (the applicant's attorney). Outreach through canvassing and faith community networks reached approximately 4,800 households.",
  "",
  "### 3.3 Comment Corpus Analysis",
  "",
  "Every comment in the public record was coded for substantive argument using a multi label coding protocol (Krippendorff's alpha = 0.82 across two coders). The five most common opposition arguments were:",
  "",
  "1. Loss of manufacturing jobs (58 percent of comments).",
  "2. Displacement pressure on existing residents from a speculative luxury residential conversion (44 percent).",
  "3. Lack of meaningful community consultation by the applicant (39 percent).",
  "4. Environmental concerns about repurposing industrial parcels without remediation (28 percent).",
  "5. Concern about downstream rezoning pressure on adjacent parcels (22 percent).",
  "",
  "Comments in support were largely technical, emphasizing the economic case for residential conversion, the affordability benefits of new supply, and the transit oriented design principles of the proposal.",
  "",
  "### 3.4 Hearing Outcome",
  "",
  "The committee room at 121 North LaSalle Street seats eighty four. The overflow room and adjacent hallway held an estimated 120 additional attendees. The signup sheet for public testimony had 112 names; time constraints limited actual testimony to seven speakers.",
  "",
  "Alderperson Walter Burnett Jr., the committee chair, opened the hearing at 10:05 AM with a ninety second per speaker limit. Testimony ran two hours and twenty minutes. At 12:25 PM, Alderperson Byron Sigcho-Lopez (25th Ward, covering the corridor) moved to table the application. The motion passed 11 to 0 with two abstentions. The applicant did not return to the committee's June or July 2025 meetings. As of the close of the public docket in October 2025, the application has not been refiled.",
  "",
  "## 4. Comparative Analysis",
  "",
  "Table 1 compares the Pilsen 2025 case to three prior Chicago corridor rezoning cases.",
  "",
  "| Case                    | Year(s)    | Outcome          | Refiled      |",
  "|-------------------------|------------|------------------|--------------|",
  "| Cermak Road corridor    | 2012       | Approved         | N/A          |",
  "| Goose Island parcels    | 2019-2023  | Approved (PMD lifted) | N/A     |",
  "| Cermak corridor (revisit)| 2018-2021 | Tabled, refiled  | Refiled 2022 |",
  "| Lincoln Yards           | 2020       | Approved         | N/A          |",
  "| Pilsen (current)        | 2025       | Tabled           | Not yet      |",
  "",
  "In three of four prior cases the application was ultimately approved, either on first filing or after a revision. The outlier is the 2018 through 2021 Cermak corridor campaign, where a tabled application was refiled in 2022 in a scaled back form and subsequently approved. The Lincoln Yards case was approved over community opposition (Smith and Kim 2024).",
  "",
  "The modal trajectory for corridor rezoning cases in Chicago is approval. The Pilsen 2025 tabling is consistent with the Cermak 2018 through 2021 precedent, suggesting that a refiled application is likely within twelve to twenty four months of tabling.",
  "",
  "## 5. Discussion",
  "",
  "The tabling of the May 2025 application did not resolve the underlying pressure on the corridor. Three observations follow.",
  "",
  "First, the tabling does not establish a binding precedent. A tabled application is a procedural deferral. It does not create findings against the applicant. Under Chicago zoning procedure, a substantially identical application may be refiled after a twelve month interval. A materially different application (different parcel count, different density, different affordability commitments) may be refiled without the twelve month wait.",
  "",
  "Second, the community response in 2025 was more rapid and more structured than comparable responses in prior Chicago cases. The four anchor coalition model, the coordinated comment drive, and the hearing mobilization are consistent with the framework documented by Gross, LeRoy, and Janis Aparicio (2005) for anchor organization coalitions. Fitzpatrick (2019) documents a less coordinated response to the 2012 Cermak Road rezoning, which was approved. The 2025 coordination is therefore a plausible causal factor in the different outcome.",
  "",
  "Third, the city level framework has not adapted to the pattern of repeated applications. Each application is treated as a novel administrative matter. No standing preservation framework exists. The literature on industrial preservation (Leigh and Hoelzel 2012; Chapple 2014) argues for standing frameworks that treat designated industrial corridors as presumptively off limits for conversion, with the burden of proof on the applicant rather than the community. Chicago does not currently have such a framework.",
  "",
  "## 6. Policy Implications",
  "",
  "The literature on industrial preservation identifies three instruments that would strengthen protection of the Pilsen Industrial Corridor and comparable Chicago corridors.",
  "",
  "1. A preservation framework designating a subset of corridors as protected, based on current manufacturing employment, infrastructure capacity, and adjacency to transit (Leigh and Hoelzel 2012).",
  "2. A required economic impact statement from applicants seeking to rezone in a protected corridor, quantifying manufacturing jobs at risk, adjacent residential displacement pressure, and infrastructure capacity implications (Chapple 2014).",
  "3. A minimum community consultation period of six months before any rezoning application is heard by the zoning committee (Gross, LeRoy, and Janis Aparicio 2005).",
  "",
  "These instruments do not require state legislation. They are within the city's home rule authority and can be adopted by amendment to the municipal zoning ordinance.",
  "",
  "## 7. Limitations",
  "",
  "The case study relies on a single corridor in a single city. Generalization to other corridors and other cities is supported by the comparative analysis in Section 4 but should be treated as hypothesis generating rather than conclusive. The comment corpus coding used a two coder protocol with high reliability (alpha = 0.82), but the single city sample limits external validity. A multi city corpus analysis of corridor rezoning comment records is a promising extension.",
  "",
  "The case predicts a refiled application by summer 2027. That prediction is an inference from the Cermak precedent and the Pilsen market conditions. It has not been validated against subsequent events.",
  "",
  "## 8. Conclusion",
  "",
  "The May 2025 tabling of the Pilsen Industrial Corridor rezoning application is a rare outcome in Chicago's recent history of corridor rezoning cases. It does not, however, resolve the structural pressure on the corridor. The absence of a standing preservation framework means that each application is contested in isolation, placing the burden of corridor defense on community organizations that cannot sustain indefinite mobilization. The policy implication is that without municipal framework reform, corridor preservation in Chicago will be episodic and ultimately partial.",
  "",
  "## References",
  "",
  "Chapple, K. (2014). *Planning Sustainable Cities and Regions: Towards More Equitable Development*. London: Routledge.",
  "",
  "Chicago Department of Planning and Development (2006). *Pilsen Industrial Corridor Plan*. Chicago: City of Chicago.",
  "",
  "Fitzpatrick, M. (2019). Corridor politics: Manufacturing and community in Chicago's Pilsen. *Journal of Urban History*, 45(6), 1132 through 1154.",
  "",
  "Gross, J., LeRoy, G., and Janis Aparicio, M. (2005). *Community Benefits Agreements: Making Development Projects Accountable*. Washington DC: Good Jobs First and the California Partnership for Working Families.",
  "",
  "Hernandez, A. (2023). *The 2018 through 2021 Cermak Road Corridor Preservation Campaign: A Case Study*. Working paper, Urbanism and Planning Program, University of Illinois at Chicago.",
  "",
  "Hoch, C., Dalton, L. C., and So, F. S. (Eds.) (2000). *The Practice of Local Government Planning*. Washington DC: International City/County Management Association.",
  "",
  "Howland, M. (2010). The business of industrial land: Evidence from eleven US cities. *Economic Development Quarterly*, 24(4), 328 through 341.",
  "",
  "Leigh, N. G. and Hoelzel, N. Z. (2012). Smart growth's blind side: Sustainable cities need productive urban industrial land. *Journal of the American Planning Association*, 78(1), 87 through 103.",
  "",
  "Martin, D. G. (2003). Place framing as place making: Constituting a neighborhood for organizing and activism. *Annals of the Association of American Geographers*, 93(3), 730 through 750.",
  "",
  "Small, M. L. (2009). How many cases do I need? On science and the logic of case selection in field based research. *Ethnography*, 10(1), 5 through 38.",
  "",
  "Smith, R. and Kim, J. (2024). Approving Lincoln Yards: TIF, displacement, and the politics of development approval in Chicago. *Journal of Urban Affairs*, 46(8), 1544 through 1561.",
  "",
  "Taylor, J. (2021). Community benefits and community power: The Woodlawn CBA coalition. *Journal of the American Planning Association*, 87(3), 412 through 425.",
  "",
  "Weber, R. (2022). Goose Island: How Chicago's manufacturing district became an innovation corridor. *Urban Affairs Review*, 58(3), 721 through 752.",
].join("\n");

export const CPD_TRAFFIC_STOP_BODY = [
  "## Abstract",
  "",
  "This paper reports findings from the first publicly released year of Chicago Police Department traffic stop data, covering 287,412 stops in calendar year 2024. Three findings are reported. First, 58 percent of stops occurred in seven of twenty two police districts, all seven of which are majority Black or Latino. Second, the stop level contraband recovery rate does not differ meaningfully across district racial composition (6.1 percent in majority white districts, 6.4 percent in majority Black districts, p = 0.54), providing no empirical support for the hypothesis that concentrated enforcement in majority Black districts generates proportionate public safety returns. Third, an outcome test in the tradition of Knowles, Persico, and Todd (2001) and Pierson et al. (2020) rejects the hypothesis that officers apply equivalent search thresholds across driver race: searches of white drivers recover contraband at 18.7 percent; searches of Black drivers at 14.1 percent (p < 0.001). The findings replicate the patterns documented in multi city analyses (Pierson et al. 2020) and are consistent with the theoretical framework of Knowles, Persico, and Todd (2001).",
  "",
  "## 1. Introduction",
  "",
  "The analysis of traffic stop data for evidence of racial bias is a mature empirical literature spanning three decades. Knowles, Persico, and Todd (2001) developed the outcome test as an identification strategy for distinguishing statistical discrimination (in which officers update beliefs based on driver characteristics in a Bayesian sense) from taste based discrimination (in which officers apply different search thresholds across driver race). Pierson et al. (2020), using a national panel covering 95 million traffic stops across twenty one state patrols and thirty five municipal police departments, found consistent evidence of lower search thresholds applied to Black drivers.",
  "",
  "Chicago was notably absent from the Pierson et al. panel. Internal CPD data was not publicly available at the time of the 2020 analysis. The 2024 Chicago Traffic Stop Data Transparency Act, passed in November of that year, required CPD to publish quarterly stop level data beginning with calendar year 2024. This paper presents the first external analysis of the resulting release, which has been available since April 2025.",
  "",
  "The contribution of this paper is twofold. First, it provides a replication of the Pierson et al. methodology on a new high quality dataset from a major American city that had previously been excluded from comparable analyses due to data availability constraints. Second, it documents specific features of the Chicago enforcement pattern that suggest deployment concentration and search threshold disparities operate as compounding rather than substitutive drivers of the observed racial disparity in stop outcomes.",
  "",
  "## 2. Background and Related Literature",
  "",
  "### 2.1 Theoretical Framework",
  "",
  "Knowles, Persico, and Todd (2001) model traffic stops as an interaction between forward looking drivers who choose whether to carry contraband and forward looking officers who choose whether to initiate a search. Under statistical discrimination, officers apply a higher search threshold to drivers from groups with lower historical contraband carrying rates, and a lower threshold to drivers from groups with higher rates. In equilibrium, contraband recovery rates conditional on search are equalized across driver race. Under taste based discrimination, officers apply lower search thresholds to drivers from disfavored groups regardless of contraband carrying rates. In equilibrium, contraband recovery rates conditional on search are lower for the disfavored group.",
  "",
  "The outcome test therefore distinguishes the two mechanisms. Equal conditional recovery rates are consistent with statistical discrimination. Unequal conditional recovery rates, specifically lower rates for the disfavored group, are consistent with taste based discrimination.",
  "",
  "### 2.2 Empirical Evidence",
  "",
  "Sanga (2009) applied the outcome test to Maryland state patrol data and found conditional recovery rates 4.2 percentage points lower for Black drivers than for white drivers, consistent with taste based discrimination. Anwar and Fang (2006) replicated the test on Florida state patrol data with consistent results. Pierson et al. (2020) extended the analysis to twenty one state patrols and thirty five municipal departments, finding lower conditional recovery rates for Black drivers in a majority of jurisdictions.",
  "",
  "### 2.3 Deployment and Enforcement",
  "",
  "A parallel literature examines the geographic concentration of traffic enforcement. Harris (1999) and Epp, Maynard Moody, and Haider Markel (2014) document disproportionate enforcement in majority Black neighborhoods in several American cities. The concentration pattern is consistent with either resource allocation decisions (proactive enforcement in high crime areas) or with officer level bias in the discretionary stop decision. Pierson et al. (2020) find that in most jurisdictions the two mechanisms operate simultaneously, with deployment decisions producing the first order disparity and individual officer decisions producing a second order disparity in stop outcomes.",
  "",
  "### 2.4 Chicago Specific Literature",
  "",
  "The Invisible Institute's 2017 report on CPD traffic stops documented concentration patterns using a subset of internal records obtained through litigation (Invisible Institute 2017). The Chicago Police Accountability Task Force report of 2016 identified the absence of public stop level data as a primary accountability gap (Chicago Police Accountability Task Force 2016). The 2024 Transparency Act responds to that gap. The present paper is the first external analysis of the post Act release.",
  "",
  "## 3. Data",
  "",
  "The 2024 CPD traffic stop release contains 287,412 records. Each record includes stop date and approximate time (rounded to the nearest fifteen minutes), police district, beat code, stop reason (moving violation, equipment, investigatory, other), officer recorded driver race, driver age (rounded to the nearest five years), stop duration in minutes, whether a search occurred, whether contraband was recovered if a search occurred, whether an arrest occurred, and whether a citation was issued.",
  "",
  "The release notably excludes officer badge numbers and GPS coordinates more granular than beat level. Chicago beats average approximately 0.6 square miles; beat level data is sufficient for district level and neighborhood level analysis but not for identifying individual officer patterns or specific intersections.",
  "",
  "Body worn camera footage associated with each stop is retained by CPD for ninety days under current policy. All 2024 stops are now past the retention window at the time of this analysis.",
  "",
  "Supplementary data on district racial composition is drawn from the 2023 American Community Survey five year estimates, matched to police district boundaries using CPD's beat to district crosswalk. District level violent crime rates are drawn from the 2024 Uniform Crime Report (Federal Bureau of Investigation 2024).",
  "",
  "## 4. Methods",
  "",
  "Three analyses are conducted.",
  "",
  "### 4.1 Geographic Concentration",
  "",
  "For each of the twenty two police districts, the stop rate per 1,000 residents is computed using 2023 ACS five year estimates for the district's population. The stop rate is cross tabulated against the racial composition of the district, using four categories: majority white (above 50 percent), majority Black (above 50 percent), majority Latino (above 50 percent), and mixed or majority Asian (neither above 50 percent).",
  "",
  "### 4.2 Outcome Rates",
  "",
  "For each district, three outcome rates are computed: the rate at which stops escalate to a search, the rate at which searches recover contraband, and the rate at which stops result in an arrest. Disparities are tested at the district aggregate level and at the stop level with driver race interactions, controlling for stop reason.",
  "",
  "### 4.3 Outcome Test",
  "",
  "The outcome test of Knowles, Persico, and Todd (2001) is applied in the implementation of Pierson et al. (2020), using conditional contraband recovery rates given that a search was conducted. Under the null hypothesis of equal search thresholds across driver race, conditional recovery rates should be equal. Rejection of the null in the direction of lower recovery for Black drivers is consistent with taste based discrimination.",
  "",
  "Statistical inference uses stop level data with clustering at the beat level. Missing or ambiguous race codes (approximately 2 percent of stops) are excluded from race based analyses rather than imputed, consistent with the practice of Pierson et al. (2020).",
  "",
  "## 5. Findings",
  "",
  "### 5.1 Concentration",
  "",
  "Fifty eight percent of 2024 traffic stops occurred in seven of twenty two police districts, all seven of which are majority Black or Latino.",
  "",
  "| District | Name           | Share of stops | Racial composition |",
  "|----------|----------------|----------------|--------------------|",
  "| 11       | Harrison       | 8.7 percent    | 91% Black/Latino   |",
  "| 7        | Englewood      | 8.3 percent    | 96% Black          |",
  "| 10       | Ogden          | 8.1 percent    | 81% Latino         |",
  "| 5        | Calumet        | 8.0 percent    | 95% Black          |",
  "| 4        | South Chicago  | 8.0 percent    | 82% Black/Latino   |",
  "| 6        | Gresham        | 8.3 percent    | 97% Black          |",
  "| 3        | Grand Crossing | 7.4 percent    | 92% Black          |",
  "",
  "These seven districts contain 39 percent of the city's population. The stop density ratio (stops per capita in these districts, divided by stops per capita in the remaining districts) is 1.50. A driver in District 7 was 2.4 times more likely to be stopped in 2024 than a driver in District 16 (Jefferson Park), which is majority white.",
  "",
  "Some of the concentration reflects deployment. The seven high stop districts have higher violent crime rates (2024 UCR) and more officers per capita. Deployment decisions are policy choices. Whether they are equitable policy choices is not testable from this dataset alone; the outcome test below addresses a related but distinct question.",
  "",
  "### 5.2 Contraband Recovery",
  "",
  "The stop level contraband recovery rate does not differ meaningfully across district racial composition.",
  "",
  "| District type              | Contraband recovery rate |",
  "|---------------------------|--------------------------|",
  "| Majority white             | 6.1 percent              |",
  "| Majority Black             | 6.4 percent              |",
  "| Majority Latino            | 5.8 percent              |",
  "| Mixed or majority Asian    | 5.9 percent              |",
  "",
  "```chart",
  "{",
  '  "type": "bar",',
  '  "title": "Stop level contraband recovery rate by district demographic",',
  '  "caption": "Share of traffic stops that resulted in recovered contraband, averaged across districts within each demographic category. Differences across categories are not statistically significant.",',
  '  "unit": "%",',
  '  "yMax": 10,',
  '  "x": ["Majority white", "Majority Black", "Majority Latino", "Mixed / Asian"],',
  '  "series": [',
  '    {"name": "Contraband recovery rate", "data": [6.1, 6.4, 5.8, 5.9]}',
  "  ]",
  "}",
  "```",
  "",
  "The difference between majority white and majority Black districts is 0.3 percentage points, statistically indistinguishable from zero (p = 0.54, two sided t test on district means). This is the key descriptive finding of the paper. Contraband recovery is the operational justification for a traffic stop escalating to a search, and ultimately for the theory that proactive traffic enforcement generates public safety value. If the recovery rate is not statistically different across districts, the concentration of stops in majority Black districts does not generate a proportionate public safety return.",
  "",
  "### 5.3 Post Stop Outcomes",
  "",
  "Conditional on a stop occurring, escalation trajectories differ substantially across district demographic.",
  "",
  "- Rate of search: stops in majority Black districts are 2.3 times more likely to escalate to a search than stops in majority white districts (9.4 percent vs 4.1 percent, p < 0.001).",
  "- Rate of arrest: 3.1 times (8.7 percent vs 2.8 percent, p < 0.001).",
  "- Rate of citation: 1.4 times (42 percent vs 30 percent, p < 0.001).",
  "",
  "After controlling for stop reason and contraband recovery rate, the rate of search disparity persists at a 1.7 times multiplier. The rate of arrest disparity persists at 2.2 times.",
  "",
  "### 5.4 Outcome Test",
  "",
  "Conditional contraband recovery rates given that a search was conducted:",
  "",
  "- Searches of white drivers: 18.7 percent recover contraband.",
  "- Searches of Black drivers: 14.1 percent.",
  "- Searches of Latino drivers: 13.8 percent.",
  "- Searches of Asian drivers: 16.2 percent.",
  "",
  "```chart",
  "{",
  '  "type": "bar",',
  '  "title": "Outcome test: contraband recovery given a search was conducted",',
  '  "caption": "Conditional contraband recovery rate by driver race. Under the Knowles, Persico, and Todd (2001) outcome test, equal thresholds would produce equal conditional recovery rates. The 4.6 percentage point gap between white and Black drivers is significant at p less than 0.001.",',
  '  "unit": "%",',
  '  "yMax": 25,',
  '  "x": ["White drivers", "Black drivers", "Latino drivers", "Asian drivers"],',
  '  "series": [',
  '    {"name": "Contraband recovery given search", "data": [18.7, 14.1, 13.8, 16.2]}',
  "  ]",
  "}",
  "```",
  "",
  "The 4.6 percentage point gap between searches of white drivers and searches of Black drivers is statistically significant (p < 0.001). The null hypothesis of equal search thresholds across driver race is rejected. The direction of the disparity (lower recovery for Black drivers) is consistent with taste based discrimination in the framework of Knowles, Persico, and Todd (2001). The magnitude is comparable to the 4.2 percentage point gap reported by Sanga (2009) for Maryland, 3.9 points by Anwar and Fang (2006) for Florida, and the median of approximately 4 points across the Pierson et al. (2020) multi city panel.",
  "",
  "## 6. Discussion",
  "",
  "The Chicago 2024 data reproduces the patterns documented in prior outcome test analyses (Sanga 2009, Anwar and Fang 2006, Pierson et al. 2020). Three observations follow.",
  "",
  "First, the concentration pattern and the outcome test disparity are distinct phenomena, and the data supports both. The concentration of stops in majority Black districts reflects deployment choices that are policy decisions; the outcome test disparity reflects individual officer decisions about when to initiate a search conditional on a stop having occurred. The two mechanisms compound: a driver in a majority Black district is more likely to be stopped, and, conditional on being stopped, more likely to be searched, and the search is less likely to yield contraband than a search conducted on a driver in a majority white district.",
  "",
  "Second, the aggregate contraband recovery rate parity across district types is notable. The theoretical model of Knowles, Persico, and Todd (2001) would predict that concentrated enforcement in districts with higher contraband carrying rates would produce aggregate recovery rate disparities. The absence of such disparities indicates either that contraband carrying rates do not differ substantially across districts, or that the concentrated enforcement does not track contraband carrying rates even where they do differ. Either interpretation is difficult to reconcile with a public safety justification for the observed concentration pattern.",
  "",
  "Third, the findings' external validity is supported by the cross city replication (Pierson et al. 2020). Chicago is now the thirty sixth major American jurisdiction in which taste based discrimination in traffic stops has been empirically documented. The probability that Chicago is an outlier in the direction of no disparity is low; the data supports the interpretation that Chicago is a member of a well characterized population of American police departments with similar enforcement patterns.",
  "",
  "## 7. Policy Implications",
  "",
  "Three policy instruments are supported by the findings of this paper.",
  "",
  "First, data transparency should be extended. The current release excludes officer badge numbers and GPS coordinates more granular than beat level. Inclusion of these fields, with an appropriate lag to protect active investigations, would allow external analysis of individual officer patterns and specific intersections. The Cincinnati Police Department's release format (Cincinnati Police Department 2022) is a viable model.",
  "",
  "Second, body worn camera footage for stops that escalate to a search or arrest should be retained for a minimum of three years, rather than the current ninety days. The current retention window precludes independent video review of the stops most relevant to accountability (Harmon 2012).",
  "",
  "Third, the concentration pattern documented in Section 5.1 is a policy decision that should be subject to explicit departmental review. In the framework of Harcourt (2007), deployment decisions that concentrate enforcement in racially identifiable areas without producing proportionate public safety returns are a form of systemic discrimination that can be addressed through administrative reform.",
  "",
  "## 8. Limitations",
  "",
  "Three limitations apply to the analysis.",
  "",
  "First, the dataset excludes officer badge numbers. Prior literature has consistently found that a small share of officers account for a disproportionate share of stops, particularly stops that escalate to a search (Epp, Maynard Moody, and Haider Markel 2014). The pattern cannot be tested in Chicago without badge level data.",
  "",
  "Second, the officer recorded race field may differ from driver self identified race. The Stanford Open Policing Project found that the discrepancy is non random (Pierson et al. 2020). The Chicago release does not include driver self identification.",
  "",
  "Third, the analysis is based on one year of data. Temporal robustness tests will be possible after additional quarterly releases covering 2025 and 2026 are published.",
  "",
  "## 9. Conclusion",
  "",
  "The first publicly released year of Chicago Police Department traffic stop data reproduces the patterns documented in prior outcome test analyses of other jurisdictions. Fifty eight percent of stops concentrate in seven majority Black or Latino districts. Contraband recovery rates do not differ across district racial composition. Searches of Black drivers recover contraband at a rate 4.6 percentage points below searches of white drivers. The combined pattern is inconsistent with a statistical discrimination model and consistent with a taste based discrimination model in the framework of Knowles, Persico, and Todd (2001).",
  "",
  "## References",
  "",
  "Anwar, S. and Fang, H. (2006). An alternative test of racial prejudice in motor vehicle searches. *American Economic Review*, 96(1), 127 through 151.",
  "",
  "Chicago Police Accountability Task Force (2016). *Recommendations for Reform: Restoring Trust between the Chicago Police and the Communities They Serve*. Chicago: City of Chicago.",
  "",
  "Cincinnati Police Department (2022). *Traffic Stop Data Release Methodology, 2022 Revision*. Cincinnati: City of Cincinnati.",
  "",
  "Epp, C. R., Maynard Moody, S., and Haider Markel, D. P. (2014). *Pulled Over: How Police Stops Define Race and Citizenship*. Chicago: University of Chicago Press.",
  "",
  "Federal Bureau of Investigation (2024). *Uniform Crime Report, 2024*. Washington DC: FBI Criminal Justice Information Services.",
  "",
  "Harcourt, B. E. (2007). *Against Prediction: Profiling, Policing, and Punishing in an Actuarial Age*. Chicago: University of Chicago Press.",
  "",
  "Harmon, R. A. (2012). The problem of policing. *Michigan Law Review*, 110(5), 761 through 817.",
  "",
  "Harris, D. A. (1999). The stories, the statistics, and the law: Why driving while black matters. *Minnesota Law Review*, 84, 265 through 326.",
  "",
  "Invisible Institute (2017). *Traffic Stop Data in Chicago: A Case Study in Police Accountability*. Chicago.",
  "",
  "Knowles, J., Persico, N., and Todd, P. (2001). Racial bias in motor vehicle searches: Theory and evidence. *Journal of Political Economy*, 109(1), 203 through 229.",
  "",
  "Pierson, E., Simoiu, C., Overgoor, J., Corbett Davies, S., Jenson, D., Shoemaker, A., Ramachandran, V., Barghouty, P., Phillips, C., Shroff, R., and Goel, S. (2020). A large scale analysis of racial disparities in police stops across the United States. *Nature Human Behaviour*, 4(7), 736 through 745.",
  "",
  "Sanga, S. (2009). Reconsidering racial profiling: A test of the economic model of prejudice. *Yale Law Journal*, 118(5), 1076 through 1098.",
].join("\n");
