/* ------------------------------------------------------------------ */
/*  research-seed-content.ts                                           */
/* ------------------------------------------------------------------ */
/*                                                                     */
/*  Long-form placeholder bodies for:                                  */
/*  - Rent Pressure in the Obama Presidential Center Impact Zone      */
/*  - Pilsen Industrial Corridor: A Rezoning Retrospective            */
/*  - CPD Traffic Stop Data, 2024                                     */
/*                                                                     */
/* ------------------------------------------------------------------ */

export const OBAMA_CENTER_BRIEF_BODY = [
  "Asking rents within a half-mile of the Obama Presidential Center site increased **41 percent** between 2020 and 2025. Over the same period, rents in the rest of the South Side increased 18 percent and rents in the city of Chicago as a whole increased 14 percent.",
  "",
  "This brief documents the pattern at a monthly granularity, identifies the displacement trajectory for existing renters in the impact zone, and recommends a binding affordable housing covenant modeled on the one San Francisco adopted for parcels around the Moscone Center in 2019.",
  "",
  "The underlying dataset — 12,480 unique rental listings scraped from Zillow, Craigslist Chicago, and the Chicago Rental Registry between January 2020 and December 2025 — is downloadable as a CSV at `rootedforward.org/research/data/obama-center-rent-panel-2020-2025.csv`. Method notes are in Section 3.",
  "",
  "## The impact zone",
  "",
  "The Obama Presidential Center broke ground in the fall of 2021, on the southeast corner of Jackson Park, after a decade of planning, community consultation, and litigation. The University of Chicago estimates the Center will draw 750,000 visitors annually once it opens. The 2021 economic impact study projects $3.4 billion in direct and indirect investment across the South Side over the Center's first twenty years of operation.[^1]",
  "",
  "That kind of investment does not enter a neighborhood without changing it. The framing question this brief answers is narrower: *are rents in the immediate impact zone rising faster than rents in comparable parts of the South Side?* If the answer is yes — if the local pressure is distinguishable from the pressure on the surrounding area — then the case for geography-specific tenant protections is stronger than the case for another round of citywide measures.",
  "",
  "The answer is yes.",
  "",
  "### Where the zone is",
  "",
  "I define the OPC impact zone as the set of census tracts whose geographic centroids fall within a half-mile radius of the Center's southeast corner at 63rd and South Cornell. Using the 2020 Census tract definitions, the zone contains eleven tracts: seven in Woodlawn (community area 42), three in South Shore (community area 43), and one at the northern edge of Greater Grand Crossing (community area 69). The zone has roughly 18,400 housing units, of which approximately 58 percent are renter-occupied as of the 2023 ACS five-year estimates.",
  "",
  "A half-mile ring is the standard buffer distance used in urban planning research on the \"footprint effect\" of major institutional investments.[^2] I chose it for direct comparability to prior studies of university campus expansions, sports venues, and transit hubs.",
  "",
  "## Data",
  "",
  "Three sources:",
  "",
  "1. **Zillow**. The Zillow Research Data Portal publishes the Zillow Observed Rent Index (ZORI), a smoothed, seasonally adjusted asking-rent index at the zip code level. I used 60637 and 60649, which together cover the impact zone plus a control area.[^2]",
  "2. **Craigslist Chicago**. A web-scraping tool collected the header fields — price, zip, bedrooms, square footage, posting date — of every rental listing in 60637 and 60649 between January 2020 and December 2025. After de-duplication on (address, bedrooms, price) the panel contains 9,842 listings.",
  "3. **Chicago Rental Registry**. The Department of Housing maintains a registry of all buildings with five or more rental units. The registry does not include asking rents, but it does include building-level metadata — year built, unit count, owner name, lender — that I used to cluster listings and check for coverage gaps.",
  "",
  "### Cleaning",
  "",
  "Raw listings data has well-known quality issues: duplicates across platforms, stale postings that repost at different prices, and obvious typos. I excluded outliers above the 99.5th percentile. After cleaning the panel retained 11,983 unique listings.",
  "",
  "### Geocoding",
  "",
  "Every listing was geocoded using the Chicago Data Portal's address-to-lat-lon API. Listings that failed geocoding — about 3 percent of the raw panel — were dropped. I assigned each listing to a 2020 Census tract using point-in-polygon matching against the Census TIGER/Line shapefiles.[^3]",
  "",
  "## Findings",
  "",
  "### The 41 percent",
  "",
  "The median asking rent for a two-bedroom unit in the half-mile ring rose from **$1,075 in January of 2020** to **$1,516 in December of 2025** — a 41 percent increase over six years, or a compound annual growth rate of 5.9 percent.",
  "",
  "Over the same period:",
  "",
  "- The same 60637 and 60649 zip codes *outside* the half-mile ring saw a median increase from $1,050 to $1,302 — a 24 percent cumulative rise, 3.7 percent annualized.",
  "- The South Side as a whole (community areas 36–57 and 60–77) saw a median increase from $1,180 to $1,390 — an 18 percent cumulative rise, 2.8 percent annualized.",
  "- The city of Chicago as a whole saw a cumulative rise of 14 percent — 2.2 percent annualized.",
  "",
  "The impact zone rose nearly three times as fast as the city and more than twice as fast as the surrounding zip codes outside the ring.",
  "",
  "### The gap widens over time",
  "",
  "The differential rate of increase is not constant. From January 2020 through March 2021, rents in the impact zone rose at a rate indistinguishable from the control — both around 2 percent year-over-year. The divergence begins in Q2 2021, coinciding with the OPC groundbreaking, and accelerates through 2023 and 2024.",
  "",
  "By calendar year:",
  "",
  "- **2020**: impact zone +2.1%, control +2.4%.",
  "- **2021**: impact zone +4.8%, control +3.1%.",
  "- **2022**: impact zone +7.2%, control +4.0%.",
  "- **2023**: impact zone +8.9%, control +4.2%.",
  "- **2024**: impact zone +9.4%, control +5.1%.",
  "- **2025**: impact zone +6.8% (through Q3), control +4.8%.",
  "",
  "The 2022–2024 acceleration coincides with the period of peak construction activity, media coverage, and secondary investment — the new restaurants on 63rd Street, the boutique hotel announcement in 2023, the coffee shops on Stony Island.",
  "",
  "### Unit size",
  "",
  "Rent pressure is not uniform across unit sizes. Studios and one-bedrooms rose fastest:",
  "",
  "- **Studio**: $825 → $1,240 (+50%).",
  "- **One-bedroom**: $950 → $1,395 (+47%).",
  "- **Two-bedroom**: $1,075 → $1,516 (+41%).",
  "- **Three-bedroom**: $1,395 → $1,830 (+31%).",
  "- **Four-bedroom and larger**: $1,750 → $2,170 (+24%).",
  "",
  "The direct implication: the people being priced out first are young adults, single adults, and childless couples in smaller units. Families in larger units are not exempt; they are merely later in the sequence.",
  "",
  "### Concentration within the ring",
  "",
  "Within the half-mile ring, pressure is concentrated in the northwest sector — the parcels facing the Center's main entrance on 62nd Street and along Stony Island Avenue. The four tracts with the highest rates of increase:",
  "",
  "- Tract 4205 (60th and Dorchester): **+54 percent**.",
  "- Tract 4204 (63rd and Stony Island): **+49 percent**.",
  "- Tract 4202 (62nd and Kimbark): **+48 percent**.",
  "- Tract 4206 (65th and University): **+43 percent**.",
  "",
  "Tracts at the southern edge of the ring, closer to existing South Shore retail, are rising more slowly — 30 to 34 percent — but from a higher baseline.",
  "",
  "## What happens next",
  "",
  "Displacement studies in comparable contexts — the Barclays Center in Brooklyn, the San Francisco Giants' Mission Bay ballpark, the Atlanta BeltLine — show that the footprint effect of a major institutional investment typically lasts ten to fifteen years before leveling off into a new baseline.[^4] If the OPC impact zone follows that trajectory, the likely path is:",
  "",
  "- Continued annual rent increases of 6 to 9 percent through 2028, tapering to 3 to 4 percent through 2033.",
  "- Accelerated sale prices for multi-unit buildings. I did not analyze sale prices in this brief, but the Institute for Housing Studies' Q3 2025 brief documents 2–4 unit building sale prices in the impact zone up more than 60 percent since 2020.",
  "- Displacement of existing tenants through lease non-renewals, rent spikes at renewal, and informal eviction — landlords buying out tenants to vacate units for rehabilitation and re-rental at market rate.",
  "- New luxury construction. Already occurring at three sites in Woodlawn.",
  "",
  "Absent intervention, the impact zone will look materially different in ten years. That is a commonplace observation about any neighborhood undergoing revitalization. The difference here is that the revitalization was publicly subsidized, through a combination of land transfers, infrastructure investment, TIF in adjacent parcels, and the direct public investment of the Center itself. Publicly subsidized displacement is, at a policy level, a different thing than displacement produced by private capital alone.",
  "",
  "## Recommendation",
  "",
  "A binding affordable housing covenant attached to all residential properties within the impact zone. The covenant should:",
  "",
  "1. **Cap annual rent increases at the lesser of 3 percent or CPI** for tenants in residence as of the effective date, for fifteen years.",
  "2. **Require landlords in buildings with five or more units who receive any form of city subsidy** — TIF proceeds, property tax abatements, low-income housing tax credits — to set aside 30 percent of units at or below 60 percent of Area Median Income.",
  "3. **Establish an independent monitoring body** with equal representation from Rooted Forward, the Woodlawn Community Collaborative, the Chicago Department of Housing, and two tenant representatives selected by lottery from the registry of impact-zone renters.",
  "4. **Fund an anti-displacement fund** financed by a 1 percent transfer tax on sales above $500,000 within the impact zone. Revenue to support emergency rental assistance, eviction-defense legal aid, and acquisition of multi-unit buildings for permanent affordability.",
  "5. **Require annual compliance reporting** in a machine-readable format.",
  "",
  "This is not a blanket rent control proposal. It is a geography-specific, time-bounded protection, modeled on interventions adopted in comparable circumstances in other cities, for a population of renters facing a displacement pressure generated in significant part by a subsidized public investment.",
  "",
  "## Limitations",
  "",
  "Asking rent is not paid rent. Leases signed before the 2020 baseline, and continuing households that have not moved or renegotiated, are not reflected in this analysis. The ACS five-year estimates of median contract rent are a partial corrective, but the 2025 release is not yet available as of publication.",
  "",
  "Craigslist data has known coverage gaps. Small-landlord listings in Woodlawn are under-represented because the neighborhood has a substantial fraction of two-to-four unit buildings whose owners list through informal channels — word of mouth, local community group bulletin boards, church newsletters. The Zillow and Rental Registry overlay partially compensates. It does not close the gap.",
  "",
  "I did not analyze the inverse trajectory — households that have moved *into* the impact zone since 2020. Displacement is about both who leaves and who arrives. A complete picture would require matched longitudinal data that I do not have access to.",
  "",
  "I recommend the Institute for Housing Studies replicate this analysis in 2027, when the ACS 2025 five-year release becomes available, and expand it to a matched panel of move-ins and move-outs.",
  "",
  "## Data availability",
  "",
  "The cleaned data underlying this brief is at `rootedforward.org/research/data/obama-center-rent-panel-2020-2025.csv`. The code used to scrape, clean, and analyze the data is in the public repository `rooted-forward/research-code`. Both are released under a Creative Commons Attribution 4.0 license.",
  "",
  "---",
  "",
  "*Citing as: Zain Zaidi, \"Rent Pressure in the Obama Presidential Center Impact Zone, 2020–2025,\" Rooted Forward, 2026. Reviewed by Marcus Alvarez of the Institute for Housing Studies at DePaul University and Dr. Rachel Greenstein of the Metropolitan Planning Council.*",
].join("\n");

export const PILSEN_INDUSTRIAL_CORRIDOR_BODY = [
  "On a warm Thursday night in May of 2025, a long line of people trickled into Benito Juárez Community Academy for a committee hearing on a zoning map amendment that, if approved, would have converted sixty-two parcels along the Pilsen Industrial Corridor from M2 light industry to B3 community shopping district. The committee room seats eighty-four. The overflow room and the hallway outside held another hundred and twenty. The signup sheet for public testimony had one hundred and twelve names.",
  "",
  "Two hours and twenty minutes later, the committee chair tabled the application. A year later, the applicant has not refiled.",
  "",
  "This brief documents what the organizing effort actually did, what it did not do, and what the episode tells us about the structural pressure on industrial corridors in near-downtown neighborhoods.",
  "",
  "## The applicant and the ask",
  "",
  "Corridor Capital Partners LLC was incorporated in Delaware in November of 2023. Its managing member, according to the Illinois Secretary of State filing, is an individual whose other holdings include a portfolio of roughly thirty multifamily buildings across Lincoln Park, Lakeview, and West Loop. The applicant is not a Pilsen owner. The applicant is an investor assembling position in an industrial corridor the investor intends to convert.",
  "",
  "The application covered sixty-two parcels totaling just over twenty-two acres. Most were vacant or contained low-intensity industrial uses — a paper warehouse, two small machine shops, a metal recycling yard, a handful of truck garages. The parcels form a contiguous L-shape along 21st Street and Western Avenue, at the northeast corner of the Pilsen Industrial Corridor as defined in the 2006 Pilsen Industrial Corridor Plan.[^1]",
  "",
  "The ask was a reclassification from M2 to B3. M2 is the city's light industry designation, which permits manufacturing, distribution, warehousing, and limited accessory retail. B3 is a community shopping district designation that permits a wide range of retail and commercial uses *as well as* residential above the ground floor by-right up to six stories.[^2]",
  "",
  "Because the parcels sit within a quarter-mile of the CTA Pink Line 18th Street station, the rezoning would also have triggered the transit-oriented development bonus provisions of the Affordable Requirements Ordinance — potentially allowing buildings of eight to ten stories with only a minimal affordable-unit set-aside.",
  "",
  "## Why the zoning matters",
  "",
  "The Pilsen Industrial Corridor is one of twenty-six designated industrial corridors in Chicago. The corridors were first mapped in the 1960s and formally codified in the 1988 zoning ordinance. The rationale: manufacturing jobs tend to cluster in dense-infrastructure, rail-and-road-adjacent corridors. Preserving the corridors as industrial keeps those jobs from being pushed out by higher-margin land uses, primarily residential.",
  "",
  "Industrial jobs in Chicago pay a median of $52,000 per year. Retail pays $34,000; lodging and food services pay $41,000. The racial wage gap is smaller in industrial work than in retail: the median Black industrial worker in Chicago earns 84 cents on the dollar relative to the median white industrial worker, compared to 67 cents in retail.[^3]",
  "",
  "The corridors' continued viability depends on two things. First, the physical infrastructure — rail spurs, truck access, power and water capacity sized for industrial use. Second, the zoning itself: once a parcel flips to residential, it does not flip back. Residential uses can outbid industrial for land, and adjacent industrial uses become harder to operate next to residents who file complaints about noise, odor, and truck traffic.",
  "",
  "This is why industrial corridor rezonings are not routine administrative matters. A rezoning is a permanent, one-way change to the long-term economic geography of a community area. Pilsen has lost 1,400 manufacturing jobs since 2000. A residential conversion of the 21st-and-Western L would accelerate that loss.",
  "",
  "## The comment campaign",
  "",
  "Rooted Forward's role in the organizing effort was to provide the research backing, draft the shared comment template, coordinate the timing of outreach across four community organizations' membership lists, and prepare witnesses for the hearing. The four anchor groups:",
  "",
  "- The Pilsen Environmental Rights and Reform Organization (PERRO).",
  "- The Pilsen Alliance.",
  "- The Resurrection Project.",
  "- The Pilsen Neighbors Community Council.",
  "",
  "The comment drive ran from April 14 through May 21, 2025. The hearing was on May 28.",
  "",
  "Numbers:",
  "",
  "- **340 written comments in opposition** — 287 individually written, 53 using all or part of the shared template.",
  "- **11 written comments in support** — 8 using the applicant's template, 3 individually written.",
  "- **7 witnesses at the hearing** — 6 in opposition (all Pilsen residents), 1 in support (the applicant's attorney).",
  "- **Approximately 4,800 households** touched by outreach via canvassing.",
  "",
  "### What the comments said",
  "",
  "I read every comment in the public record. The most common arguments against the rezoning, in descending order of frequency:",
  "",
  "1. **Loss of manufacturing jobs in the neighborhood** — 58 percent of comments.",
  "2. **Displacement pressure on existing residents from a speculative luxury residential conversion** — 44 percent.",
  "3. **Lack of meaningful community consultation by the applicant** — 39 percent.",
  "4. **Environmental concerns about repurposing industrial parcels without remediation** — 28 percent.",
  "5. **Concern about downstream rezoning pressure on adjacent parcels** — 22 percent.",
  "",
  "The comments in support were largely technical — arguments about the economic case for residential conversion, the affordability benefits of new supply, and the transit-oriented design principles of the proposal.",
  "",
  "### The hearing",
  "",
  "Alderperson Walter Burnett Jr., the committee chair, opened the hearing by limiting each speaker to ninety seconds. Testimony ran two hours and twenty minutes. The applicant's attorney presented first, followed by the six community witnesses.",
  "",
  "At the close of testimony, Alderperson Byron Sigcho-Lopez — the 25th Ward alderperson, whose ward covers the corridor — moved to table the application. The motion passed 11–0 with two abstentions. The applicant did not return to the committee's June or July meetings. The application has not been refiled as of this brief's publication.",
  "",
  "## What the tabling did not do",
  "",
  "It did not solve the underlying pressure. Industrial corridors in near-downtown neighborhoods are under speculation from developers in every major American city, and the playbook is well understood. Assemble parcels through shell LLCs. Hire a well-connected land-use attorney. Apply for rezoning. If opposition defeats the first attempt, wait twelve to twenty-four months, reshape the application — fewer parcels, phased density, better-branded affordable commitments — and reapply.",
  "",
  "My prediction is that a revised application will land by summer of 2027. I have no specific information supporting that prediction; it is an inference from the pattern I have observed in comparable corridor rezoning fights in Chicago (the Cermak Road corridor 2018–2021, the Goose Island rezonings 2019–2023, the Northwest Corridor work currently underway).",
  "",
  "The tabling also did not establish a generalizable precedent. The committee tabled the application. It did not reject it with findings. A tabled application does not create a binding standard. It is a deferral.",
  "",
  "## What I recommend",
  "",
  "The Department of Planning and Development should adopt a standing **Industrial Corridor Preservation Framework** that establishes a heightened review standard for rezoning applications in corridors designated as strategically important for manufacturing employment. The framework should:",
  "",
  "1. **Designate a subset of corridors as \"protected\"** based on current manufacturing employment, infrastructure capacity, and adjacency to transit. The Pilsen corridor, along with North Branch, Little Village, and Pullman, would qualify under any reasonable threshold.",
  "2. **Require an economic impact statement** from any applicant seeking to rezone in a protected corridor. The statement would quantify the manufacturing jobs at risk, the displacement pressure the rezoning would create in adjacent residential parcels, and the infrastructure capacity implications.",
  "3. **Trigger an automatic community consultation process** of no less than six months before the application is heard.",
  "4. **Permit the city to refuse to process an application** that does not meet the framework's minimum standards — rather than requiring a committee hearing and vote for every application that lands.",
  "",
  "This is not a moratorium. It is a heightened standard — a signal to the investor community that the city has decided certain corridors are not open for routine conversion. It would reduce the speculation pressure and, with it, the organizing burden on community coalitions of defending each corridor one rezoning at a time.",
  "",
  "## What happens next",
  "",
  "Rooted Forward's next project on this corridor is a mapping effort. We are assembling, for all twenty-six Chicago industrial corridors, three datasets: present-day manufacturing employment (from the Longitudinal Employer-Household Dynamics data), infrastructure capacity (from Chicago Department of Water and Com Ed service records), and ongoing rezoning application volume (from the DPD public docket).",
  "",
  "The goal is a public, updatable dashboard giving community organizations, alderpersons, and DPD a common view of which corridors are under pressure and which are stable. We expect to publish a first version in late 2026.",
  "",
  "> An industrial corridor rezoning fight is not really about the sixty-two parcels on the application. It is about whether the city treats its manufacturing economy as worth preserving at a strategic level, or as available for conversion on a case-by-case basis. The current answer is implicitly the second. The research here is one piece of the argument for making it explicitly the first.",
  "",
  "---",
  "",
  "*Reviewed by Jerome Pritchett of Pritchett + Olagun Studio and Ibrahim Diallo of Chicago-Kent College of Law. Field-research assistance from the Pilsen Alliance and PERRO. The hearing transcript is public record; I cite it at Chicago Committee on Zoning, Landmarks and Building Standards, \"Hearing Transcript, Application ZC-2025-0074,\" May 28, 2025.*",
].join("\n");

export const CPD_TRAFFIC_STOP_BODY = [
  "In 2024, the Chicago Police Department recorded 287,412 traffic stops. Fifty-eight percent of them occurred in seven of the twenty-two police districts. All seven of those districts are majority Black or Latino. The stop-level contraband recovery rate in those districts — the share of stops that recover anything illegal — was 6.4 percent. In majority-white districts it was 6.1 percent. On the operational justification for the traffic stops, in other words, the two sets of districts are indistinguishable.",
  "",
  "This is an analysis of the first full year of publicly-released CPD traffic stop data. The release was required by the CPD Traffic Stop Data Transparency Act, passed by Chicago City Council in November of 2024. The first quarterly data release — covering calendar year 2024 — was published in April of 2025.",
  "",
  "Rooted Forward was a co-author of the ordinance language, along with the Chicago Police Accountability Task Force and the Invisible Institute. We pushed for the transparency requirement because traffic stops are the most common form of direct contact between Chicago residents and sworn officers — approximately 290,000 per year — and because internal CPD data had consistently shown patterns of concentration that the public could not see. This is the first external review of the public release.[^1]",
  "",
  "## The data",
  "",
  "The 2024 release contains 287,412 records. Each row:",
  "",
  "- Stop date and approximate time (rounded to the nearest fifteen minutes).",
  "- Police district where the stop occurred.",
  "- Beat code within the district.",
  "- Stop reason (pre-coded categories: moving violation, equipment, investigatory, other).",
  "- Driver race, as recorded by the officer conducting the stop.",
  "- Driver age, rounded to the nearest five years.",
  "- Duration of the stop, in minutes.",
  "- Whether a search occurred.",
  "- If searched, whether contraband was recovered.",
  "- Whether an arrest occurred.",
  "- Whether a citation was issued.",
  "",
  "Notably absent from the release: officer badge numbers, and GPS coordinates more precise than beat-level. Chicago beats average about 0.6 square miles. This is sufficient for district-level and neighborhood-level analysis. It is not sufficient for identifying individual officer patterns or specific intersections.",
  "",
  "Body-worn camera footage associated with each stop is retained by CPD for ninety days under current policy. All 2024 stops are now past the retention window, so independent video review is not possible for this analysis.",
  "",
  "## Method",
  "",
  "Three parallel analyses:",
  "",
  "1. **Geographic concentration**: for each of the twenty-two police districts, the stop rate per 1,000 residents, using 2023 ACS five-year estimates for the district's population. Cross-tabulated against the racial composition of the district.",
  "2. **Outcome rates**: for each district, (a) the rate at which stops escalate to a search, (b) the rate at which searches recover contraband, and (c) the rate at which stops result in an arrest.",
  "3. **Disparity tests**: the \"outcome test\" method from the Stanford Open Policing Project,[^3] applied to look for evidence that the threshold for initiating a search differs by driver race.",
  "",
  "Method choices made deliberately:",
  "",
  "- Stop rates alone are not evidence of bias. Stop rates reflect both individual officer decisions and the geographic concentration of police resources. The latter is a policy choice, but not officer-level bias. The outcome test is the cleaner instrument.",
  "- Missing or ambiguous race codes — roughly 2 percent of stops — are excluded from race-based analyses rather than imputed.",
  "- The district, not the city as a whole, is the denominator for stop rates. This corrects for the concentration of police deployment.",
  "",
  "## Findings",
  "",
  "### Concentration",
  "",
  "Fifty-eight percent of all 2024 traffic stops occurred in seven of the twenty-two police districts, all seven of which are majority Black or Latino:",
  "",
  "- District 11 (Harrison): 8.7% of all stops; 91% Black/Latino residents.",
  "- District 7 (Englewood): 8.3%; 96% Black.",
  "- District 10 (Ogden): 8.1%; 81% Latino.",
  "- District 5 (Calumet): 8.0%; 95% Black.",
  "- District 4 (South Chicago): 8.0%; 82% Black/Latino.",
  "- District 6 (Gresham): 8.3%; 97% Black.",
  "- District 3 (Grand Crossing): 7.4%; 92% Black.",
  "",
  "These seven districts contain 39 percent of the city's population and account for 58 percent of traffic stops. The ratio is 1.5× — stop density is 50 percent higher in these districts than in the rest of the city after adjusting for population.",
  "",
  "Some of this reflects deployment. These districts have higher violent crime rates, more officers per capita, and more proactive traffic enforcement as a matter of departmental strategy. Deployment is a policy choice, but its consequences for residents are real: a driver in District 7 was 2.4 times more likely to be stopped in 2024 than a driver in District 16 (Jefferson Park).",
  "",
  "### Contraband recovery",
  "",
  "The stop-level contraband recovery rate was not meaningfully different between majority-white districts and majority-Black districts:",
  "",
  "- Majority-white districts: 6.1%.",
  "- Majority-Black districts: 6.4%.",
  "- Majority-Latino districts: 5.8%.",
  "- Mixed or majority-Asian districts: 5.9%.",
  "",
  "This is the central finding. Contraband recovery is the operational justification for a traffic stop escalating to a search, and ultimately for the theory that proactive traffic enforcement generates public safety value. If the recovery rate is roughly the same across districts, the marginal stop in a majority-Black district is no more likely to produce public safety value than the marginal stop in a majority-white district. The concentration of stops in majority-Black districts therefore cannot be justified on contraband-recovery grounds.",
  "",
  "### Post-stop outcomes",
  "",
  "Once a stop occurred, the escalation trajectory differed sharply:",
  "",
  "- **Rate of search**: stops in majority-Black districts were **2.3×** more likely to result in a search than stops in majority-white districts (9.4% vs 4.1%).",
  "- **Rate of arrest**: **3.1×** (8.7% vs 2.8%).",
  "- **Rate of citation**: 1.4× (42% vs 30%).",
  "",
  "After controlling for stop reason and contraband recovery rate, the rate-of-search disparity persists at a 1.7× multiplier. The rate-of-arrest disparity persists at 2.2×.",
  "",
  "### The outcome test",
  "",
  "The Stanford outcome test examines whether the threshold for initiating a search differs by driver race. If officers apply the same threshold regardless of driver race, we would expect similar contraband recovery rates *conditional on* a search having occurred. If officers apply a lower threshold for Black drivers — meaning they search at weaker evidence — we would expect a lower contraband recovery rate given a search.",
  "",
  "My outcome test finds:",
  "",
  "- Searches of white drivers: **18.7% recover contraband**.",
  "- Searches of Black drivers: **14.1%**.",
  "- Searches of Latino drivers: **13.8%**.",
  "- Searches of Asian drivers: **16.2%**.",
  "",
  "The 4.6 percentage-point gap between searches of white drivers and searches of Black drivers is statistically significant at the p < 0.001 level. Under outcome test logic, this is evidence that the threshold for initiating a search of a Black driver is lower than the threshold for initiating a search of a white driver.",
  "",
  "This is consistent with findings from Stanford's multi-city analysis. It is not unique to Chicago.[^3]",
  "",
  "## Limitations",
  "",
  "The released data excludes officer badge numbers and does not provide GPS coordinates more granular than beat-level. This has three downstream consequences for accountability:",
  "",
  "1. **I cannot identify individual officers whose stop patterns are outliers.** The academic and journalistic work on traffic stop disparity — from Sacramento to Oakland to Brooklyn — has consistently found that a relatively small share of officers account for a disproportionate share of stops, particularly stops that escalate to a search. Without badge numbers, I cannot check whether that pattern holds in Chicago.",
  "2. **I cannot identify specific intersections or locations that are hotspots for concentrated enforcement.** Beat-level geography is too coarse to surface the specific street corners where stops cluster.",
  "3. **I cannot cross-reference the data against CPD's internal Complaint Register database** to see whether officers named in misconduct complaints are among the heaviest traffic-stop conductors.",
  "",
  "I also have no way to validate the race codes recorded by officers. The Stanford Open Policing Project has noted that officer-recorded race can differ from driver self-identification, and that the difference is non-random. Chicago's release does not include a comparable validation mechanism.",
  "",
  "## Recommendations",
  "",
  "The Public Safety Committee should introduce amending legislation to the Traffic Stop Data Transparency Act to require:",
  "",
  "1. **Officer badge numbers** in future releases, subject to a six-month lag to protect active investigations.",
  "2. **Parcel-level GPS coordinates**, in line with the Cincinnati Police Department's releases since 2022.",
  "3. **Driver self-identified race**, collected at the stop in addition to the officer's recorded race.",
  "4. **Retention of body-worn camera footage for stops that escalate to a search or arrest**, for a minimum of three years, to support independent post-hoc review.",
  "",
  "The data CPD has currently released is a substantial improvement over nothing. It is not sufficient for meaningful accountability. The gaps in the release are the gaps that prevent external actors — journalists, community organizations, civil rights litigators — from connecting individual officer patterns to departmental policy.",
  "",
  "## A note on method",
  "",
  "All code and intermediate datasets used in this analysis are in the `rooted-forward/cpd-traffic-analysis` GitHub repository, released under an MIT license. I have tried to document every choice that could affect the findings. I welcome replication and critique.",
  "",
  "The single most important thing an external analyst can do with this data is ask what I have *not* asked. I invite researchers, journalists, and civic technologists to use this release for their own work. The release exists because community organizations, academic researchers, and journalists have been pushing for it for two decades. It will only serve its purpose if people continue to engage with it after the first wave of attention has passed.",
  "",
  "---",
  "",
  "*Reviewed by Ibrahim Diallo of Chicago-Kent College of Law and Dr. Rachel Greenstein of the Metropolitan Planning Council. The Invisible Institute provided dataset validation and access to the Complaint Register metadata I used to cross-check my aggregations.*",
].join("\n");
