/* ------------------------------------------------------------------ */
/*  research-seed-content-vol3.ts                                      */
/* ------------------------------------------------------------------ */
/*                                                                     */
/*  Academic research bodies for:                                      */
/*  - Community Benefits Agreements in Chicago (Austin case analysis) */
/*  - Bronzeville TIF Expenditure Analysis                            */
/*  - West Side Grocery Access oral history                           */
/*  - Cook County Property Tax Appeal Disparity                       */
/*                                                                     */
/* ------------------------------------------------------------------ */

export const AUSTIN_CBA_PLAYBOOK_BODY = [
  "## Abstract",
  "",
  "The community benefits agreement (CBA) — a privately-negotiated contract through which a community coalition secures binding commitments from a developer in exchange for the coalition's non-opposition to a discretionary land-use approval, has emerged over the past twenty-five years as one of the central instruments of equitable-development practice in US cities (Gross, LeRoy, & Janis-Aparicio 2005; Been 2010; Wolf-Powers 2017). This paper examines the instrument's application in Chicago through a structured comparison of eight Chicago CBAs signed between 2005 and 2024, situates the emerging Austin-community-area CBA pipeline against the resulting cross-case pattern, and produces specific negotiation recommendations for the four sites identified in the Austin Coming Together 2026 planning update (Austin Coming Together 2026) as likely near-term CBA targets: the former Brach's candy factory site on Austin Boulevard, the Madison Street vacant-lot cluster between Mason and Central, the three city-owned parcels at the Green Line Oak Park extension terminus, and the Columbus Park Boulevard frontage held by Loretto Hospital. Across the eight Chicago cases we find substantial heterogeneity in post-signing compliance: two cases achieved full compliance with 7+ of 10 commitment categories; three achieved partial compliance (4–6 categories); three achieved compliance with 3 or fewer. Five structural features correlate with compliance in the Chicago sample — three-party enforcement structure including a local-government signatory (Spearman's ρ = 0.77, *p* = 0.04), monitoring-body independence (ρ = 0.82, *p* = 0.02), numerical specificity of commitments (ρ = 0.69, *p* = 0.08), material penalty clauses (ρ = 0.73, *p* = 0.06), and coalition longevity past five years (ρ = 0.86, *p* = 0.01). The pattern extends the findings of Park and Kim (2022) from a nationwide ten-city sample to the Chicago case and informs the Austin-specific recommendations developed in §6.",
  "",
  "## 1. Introduction",
  "",
  "The community benefits agreement emerged in the early 2000s as a practitioner-invented response to a specific gap in the US land-use regulatory framework: the difficulty of binding a developer to neighborhood-specific commitments, on affordable housing, local hiring, community-facing programming, environmental mitigation, that exceed what the standard zoning and permit-approval process requires. The foundational US case is the Staples Center agreement signed in Los Angeles in May 2001 between the Los Angeles Arena Land Company and a coalition of thirty community organizations led by the Los Angeles Alliance for a New Economy (LAANE); the full agreement is reproduced and analyzed in Salkin and Lavine (2008) and contextualized in Marcello (2007). Since 2001, CBAs have been signed in approximately seventy-five documented cases across US cities through 2020 (Saito 2012; Wolf-Powers 2017), with outcomes ranging from substantial realization of committed benefits (the Staples Center case at its tenth anniversary; Saito 2012) to minimal compliance and eventual abandonment of the monitoring structure (Been 2010 analyzes several such cases).",
  "",
  "Chicago has been a secondary but active site of CBA practice. The first documented Chicago CBA was signed in October 2005 between developer Crown Real Estate and a coalition of West Side organizations, the West Side Health Authority, the Westside Community Triangle Association, and Austin Coming Together, covering a mixed-use project at Madison and Pulaski in East Garfield Park (Chicago Lawyers' Committee for Civil Rights Under Law 2008, pp. 43–67). Subsequent CBAs have been adopted for the Wilson Yard mixed-use development in Uptown (2007, led by the Organization of the North East), the Pullman retail expansion (2012, led by the Chicago Neighborhood Initiatives coalition), the 78 mixed-use development at Clark and Roosevelt (2018), the Lincoln Yards development (2019, a partial framework rather than a full CBA; Smith & Kim 2024), and the Obama Presidential Center (2022, technically a Chicago City Council ordinance rather than a CBA in the strict sense; Taylor 2021; City of Chicago Ord. SO2022-1532). The Woodlawn CBA draft of 2017, negotiated over three years by the Coalition for a CBA at the Obama Center, was not signed in its original form and was partially superseded by the 2022 ordinance (Taylor 2021).",
  "",
  "The Austin community area, Chicago's largest community area by land area (7.2 square miles) and one of its largest by population (approximately 93,000 residents; US Census 2020) — is an emerging CBA site. Two forthcoming investment pressures are driving developer interest. The CTA Green Line extension from Harlem Avenue to Oak Park received its Federal Transit Administration Record of Decision in April 2023 (FTA 2023) and is expected to enter construction in 2027. The Illinois Medical District western expansion, announced in September 2024, projects a $490 million capital commitment to the Madison Street corridor between Cicero and Austin Avenues (IMD 2024). The cumulative effect of the two investments is the opening of a land-value gradient in Austin that, absent explicit community-benefits instruments, is likely to produce the kind of displacement documented in the Woodlawn case post-2015 (Taylor 2021).",
  "",
  "Austin community organizations, working through the Austin Coming Together quality-of-life planning process, formed a CBA Planning Committee in January 2026 to prepare for negotiations on identified at-risk parcels. The committee's initial planning document (Austin Coming Together 2026) identifies four sites as likely near-term CBA targets and requests structured analysis of the Chicago CBA precedent as an input to the Austin negotiation framework. The present paper is that analysis.",
  "",
  "What we add runs in three directions. We provide a structured comparison of eight Chicago CBAs, with outcome data through year-end 2024, coded under a schema adapted from Park and Kim's (2022) ten-city framework. We identify five structural features that correlate with post-signing compliance in the Chicago sample — features that extend the Park and Kim findings from their broader US sample to the Chicago subset. And we translate those features into specific negotiation recommendations for the Austin environment, tailored to the four-site configuration the Austin Coming Together 2026 planning document identifies.",
  "",
  "## 2. Background and Related Literature",
  "",
  "### 2.1 Theoretical Framework",
  "",
  "CBAs operate in the discretionary land use approval process as a form of private regulation that supplements public regulation (Been 2010). A developer seeking discretionary approvals (zoning changes, variances, public financing, or land transfers) has a revealed preference for approval, and the coalition controls, through organized mobilization and political relationships, a meaningful share of the political cost of denial. The CBA is the instrument that monetizes and formalizes the coalition's political position.",
  "",
  "The structural critique of CBAs has been developed by Been (2010) and Marcello (2007). Both argue that CBAs are vulnerable to three failure modes: coalition legitimacy questions (who speaks for the community, and with what mandate); enforcement weakness (most CBAs are two party contracts with no independent enforcer); and the substitution of privately negotiated benefits for public regulation, weakening the regulatory baseline over time. Salkin and Lavine (2008) argue that the instrument's net effect depends on the specifics of individual agreements and the institutional support they receive from local government.",
  "",
  "### 2.2 Empirical Outcomes",
  "",
  "The empirical literature on CBA outcomes is smaller than the theoretical literature. Saito (2012) provides a case study of the Staples Center CBA at its tenth anniversary, finding substantial but incomplete realization of commitments. Wolf Powers (2017) examines three East Coast CBAs and finds variable compliance ranging from 38 to 89 percent of committed items implemented within ten years. Park and Kim (2022) study ten CBAs using a structured implementation analysis framework and identify four predictors of compliance: monitoring body independence, numerical specificity of commitments, presence of a local government signatory, and coalition longevity past signing.",
  "",
  "### 2.3 Chicago Specific Evidence",
  "",
  "The Chicago CBA literature is primarily case study and primarily journalistic. Taylor (2021) is the only peer reviewed academic treatment. Chicago Lawyers' Committee for Civil Rights Under Law (2008) provides a document repository without outcome analysis. The present paper extends the Taylor (2021) treatment by adding systematic outcome data for the eight documented Chicago CBAs.",
  "",
  "## 3. Method",
  "",
  "### 3.1 Case Selection",
  "",
  "We identified eight Chicago CBAs signed between October 2005 and June 2024 through a systematic search of three documentary sources: the Chicago Lawyers' Committee for Civil Rights Under Law's CBA Repository (assembled in 2008 and updated through 2023); the Coalition for a Community Benefits Agreement document archive held at the University of Illinois at Chicago Great Cities Institute; and the Chicago City Council legislative record for the 2005–2024 period. We cross-checked the case list against the Good Jobs First CBA database and the Partnership for Working Families archive.",
  "",
  "The eight-case list:",
  "",
  "1. *East Garfield Park Mixed-Use Agreement* (October 2005). Developer: Crown Real Estate. Coalition: West Side Health Authority, Westside Community Triangle Association, Austin Coming Together. Project: 110-unit mixed-use at Madison and Pulaski.",
  "2. *Wilson Yard CBA* (March 2007). Developer: Holsten Real Estate Development. Coalition: Organization of the North East, Uptown Chicago Commission. Project: Wilson Yard mixed-use, Uptown.",
  "3. *Kenwood Academy Addition Agreement* (September 2010). Developer: Chicago Public Schools. Coalition: Kenwood community coalition. Project: high-school addition. Atypical in that the developer was a public entity.",
  "4. *Pullman Walmart CBA* (February 2012). Developer: Chicago Neighborhood Initiatives / Walmart. Coalition: Pullman community alliance. Project: 148,000-sf Walmart retail anchor.",
  "5. *78 Related Midwest CBA* (November 2018). Developer: Related Midwest. Coalition: ad hoc coalition led by Pilsen Alliance. Project: 62-acre mixed-use at Clark and Roosevelt.",
  "6. *Lincoln Yards Partial Framework* (April 2019). Developer: Sterling Bay. Coalition: fragmented; framework not a full CBA. Project: 54-acre North Side mixed-use.",
  "7. *Obama Center Community Protections Ordinance* (October 2022). Developer-substitute: Chicago City Council. Coalition: Coalition for a CBA at the Obama Center (framework superseded prior 2017 draft CBA). Instrument is an ordinance, not a privately-negotiated CBA, and is coded separately in §4.",
  "8. *West Loop Mixed-Use CBA* (June 2024). Developer: Sterling Bay (second agreement in sample). Coalition: West Loop Community Organization. Project: 1.2-million-sf mixed-use.",
  "",
  "### 3.2 Outcome Coding",
  "",
  "For each of the eight cases we coded ten commitment categories for full, partial, or no compliance as of December 31, 2024. The ten categories are drawn from the Park and Kim (2022) framework and refined through a pilot-coding exercise on the Pullman case conducted in March 2024 prior to the full coding run:",
  "",
  "1. Affordable-housing unit share (number or percentage committed versus delivered).",
  "2. Affordability-level AMI targeting (committed versus delivered).",
  "3. Local-hiring percentage on construction phase.",
  "4. Local-hiring enforcement and verification mechanism (presence and activity).",
  "5. Retail-tenant preferences or small-business set-aside provisions.",
  "6. Community-monitoring body: presence, meeting frequency, public reporting.",
  "7. Penalty clauses for non-compliance (liquidated damages, specific performance, or equivalent).",
  "8. Anti-flipping or ownership-stability provisions on affordable units.",
  "9. Annual reporting requirements to the coalition and to the public.",
  "10. Coalition continued existence at year-end 2024 in a form capable of enforcing the agreement.",
  "",
  "Two coders, both with prior experience coding planning documents in the Park and Kim 2022 pilot study — coded each case independently. Discrepancies on the three-way (full / partial / none) scale were resolved through joint review of the source documents; on the binary (compliance / non-compliance) scale, Krippendorff's α was 0.91 before resolution. On the three-way scale α was 0.78, above the 0.67 threshold typically considered acceptable for tentative conclusions (Krippendorff 2018, ch. 9) but below the 0.80 threshold for strong substantive interpretation. Readers should register this caveat.",
  "",
  "### 3.3 Structural Feature Coding",
  "",
  "For each case we coded five structural features drawn from the theoretical literature on CBA failure modes (Been 2010; Marcello 2007; Park & Kim 2022). The features:",
  "",
  "1. *Three-party structure*: whether the agreement is signed by developer, coalition, and a local-government entity (typically the Chicago Department of Housing).",
  "2. *Monitoring-body independence*: whether the designated monitoring body is governed by representation that is not exclusively the developer or the coalition.",
  "3. *Numerical specificity of commitments*: whether the agreement contains specific percentage targets, specific dollar amounts, and specific deadlines; coded binary on the overall document rather than per-commitment.",
  "4. *Material penalty clauses*: whether the agreement contains liquidated-damages provisions, specific-performance rights, or equivalent legal-remedy language in the event of breach.",
  "5. *Coalition longevity*: whether the coalition signing the agreement continues to exist at five years post-signing in an institutional form capable of sustained monitoring (i.e., with staff, budget, and governance structure).",
  "",
  "## 4. Findings",
  "",
  "### 4.1 Compliance Distribution",
  "",
  "Across the eight Chicago cases, compliance as of December 31 2024 distributes into three approximately equal-sized groups. Two cases achieved full compliance on seven or more of the ten commitment categories: Pullman Walmart (7 of 10; the one unmet item is the community-monitoring-body meeting frequency, which has fallen below quarterly since 2020) and West Loop Mixed-Use (7 of 10, with the caveat that the agreement has only a six-month post-signing window at the time of coding and may regress toward the mean over a longer horizon). Three cases achieved full compliance on four to six categories: Wilson Yard (6); Kenwood Academy Addition (5); and the Obama Center Ordinance (4, with the separate caveat that the Ordinance is not strictly a CBA and the categories apply unevenly). Three cases achieved full compliance on three or fewer: East Garfield Park 2005 (2 of 10; the coalition dissolved in 2011 and the annual-reporting mechanism has produced no public report since 2010); 78 Related Midwest (3 of 10; the coalition dissolved within eighteen months); Lincoln Yards (2 of 10; the framework was partial by design and the affordability provisions have been honored in letter but not in the levels the coalition's negotiating position sought). The distribution is broadly consistent with Wolf-Powers's (2017) finding of substantial cross-case outcome variation in the East Coast CBA literature.",
  "",
  "### 4.2 Structural-Feature Correlates",
  "",
  "We computed Spearman rank correlations between each of the five structural features and the compliance score (number of categories fully achieved, out of ten). Across the eight-case sample:",
  "",
  "| Structural feature                  | Spearman ρ | *p*     |",
  "|-------------------------------------|-----------:|--------:|",
  "| Three-party structure               |       0.77 |    0.04 |",
  "| Monitoring-body independence        |       0.82 |    0.02 |",
  "| Numerical specificity               |       0.69 |    0.08 |",
  "| Material penalty clauses            |       0.73 |    0.06 |",
  "| Coalition longevity (5y post-sign)  |       0.86 |    0.01 |",
  "",
  "With eight cases the statistical power is modest, the conventional α = 0.05 threshold is met or exceeded on three of five features, and we treat the magnitudes as directional rather than as precise estimates. That said, the direction and relative magnitude of the five correlations are consistent with Park and Kim's (2022) findings from their ten-case nationwide sample, which lends some external validity to the Chicago pattern. The three features with the strongest Chicago correlations (coalition longevity, monitoring-body independence, three-party structure) are also the three features with the strongest correlations in Park and Kim's broader dataset; the ranking is stable across samples.",
  "",
  "### 4.3 Failure-Mode Analysis",
  "",
  "Three cases scored three or fewer on compliance: East Garfield Park (2005), 78 Related Midwest (2018), Lincoln Yards (2019). All three lacked a three-party structure (the local-government signatory was absent or pro forma). All three lacked material penalty clauses (informal 'best-efforts' language replaced enforceable remedy). In the 78 Related Midwest case, the signing coalition dissolved within eighteen months of the agreement — before the first annual reporting cycle, and no operational entity existed to monitor, let alone enforce, the commitments thereafter. In the East Garfield Park case, the coalition persisted longer but shifted its organizational focus away from CBA-monitoring by 2011. The patterns are consistent with the three failure modes Been (2010, pp. 27–32) identifies: coalition-legitimacy erosion, enforcement-infrastructure absence, and private-negotiation substitution for public regulation. The Chicago cases that failed, failed through exactly the channels the theoretical critique predicted.",
  "",
  "## 5. Discussion",
  "",
  "The Chicago sample is small — eight cases, and therefore limits the statistical power of the structural-feature correlations reported in §4.2. We treat the correlations as directional evidence, consistent with the larger US literature rather than as conclusive findings within Chicago alone. Three observations nonetheless warrant separate comment.",
  "",
  "The first concerns the common feature of the five structural variables that correlate with compliance. They all distribute enforcement capacity across multiple durable institutions rather than concentrating it in a single entity. Three-party structures distribute enforcement to a local-government signatory with independent legal standing and subpoena authority. Monitoring-body independence distributes enforcement to a standing third party with ongoing visibility. Coalition longevity distributes enforcement across time, sustaining pressure past the point at which a developer's initial compliance incentives might otherwise attenuate. Material penalty clauses distribute enforcement to a judicial forum with an established process for remedying breach. Numerical specificity distributes enforcement to a measurement regime with an objective adjudication standard. The common pattern — distribution rather than concentration — echoes the broader insight from the private-regulatory literature (Mattli & Woods 2009; Vogel 2008) that self-enforcement is rare and that durable compliance depends on the design of enforcement infrastructure.",
  "",
  "The second concerns the structural features that did not correlate meaningfully with compliance in our sample. Informal commitments without penalty clauses ('best-efforts' language, 'good-faith consultation' language) performed poorly across the eight cases; the three lowest-compliance cases all relied primarily on this kind of language. Monitoring commitments without an independent monitoring body performed similarly poorly. Commitments to future negotiation — 'the parties will meet annually to discuss implementation' — performed poorly in every case we examined. The general pattern is that commitments which depend on individual-actor goodwill or on vigilance from actors with no institutional incentive to sustain it produce little enforcement pressure over the five-plus-year time horizons we observe.",
  "",
  "The third concerns the Chicago pattern's consistency with the comparative US literature. CBAs are not self-enforcing. This is not a Chicago-specific finding; it is the consensus finding across Saito (2012), Wolf-Powers (2017), Park and Kim (2022), and Been (2010). The instrument's utility in any jurisdiction depends heavily on the design features that support enforcement. Absent those features, the CBA reduces to a reputational statement, which is a meaningful instrument in the political-mobilization context but does not, on the evidence we have reviewed, exert durable pressure on developer behavior past the initial three-to-five-year post-signing window.",
  "",
  "## 6. Application to Austin",
  "",
  "The Austin community area is entering a period of heightened developer interest driven by the Green Line extension and the Illinois Medical District expansion. Four sites have been identified by Austin Coming Together (2026) as likely near term CBA negotiation targets.",
  "",
  "1. The former Brach's candy factory site on Austin Boulevard (approximately twenty nine acres).",
  "2. The Madison Street vacant lots between Mason and Central (approximately 3.4 acres).",
  "3. The three city owned parcels at the southwest corner of the Green Line Oak Park extension terminus.",
  "4. The Columbus Park Boulevard frontage currently held by Loretto Hospital.",
  "",
  "Given the structural feature correlates identified in Section 4.2, Austin coalitions negotiating on these sites should prioritize the following.",
  "",
  "First, three party structures. The Chicago Department of Housing has served as a third party signatory in six agreements since 2019; the pattern is not formalized as policy but is sufficient precedent to cite.",
  "",
  "Second, monitoring body independence. The monitoring body should be governed by a standing agreement with community, developer, and local government representation, with independent budget authority and independent legal standing.",
  "",
  "Third, numerical specificity. Commitments should include specific percentage targets, specific dollar amounts, and specific deadlines. Aspirational language without numerical targets is associated with low compliance in the Chicago sample.",
  "",
  "Fourth, material penalty clauses. Liquidated damages or specific performance clauses are associated with higher compliance. Standard contractual remedies are preferable to reputational or advisory language.",
  "",
  "Fifth, coalition longevity planning. The coalition should plan for a minimum five year post signing operational life, with budget, governance structure, and succession planning in place before signing. Coalitions that dissolve post signing have consistently produced low compliance outcomes.",
  "",
  "## 7. Limitations",
  "",
  "The sample is small. Eight Chicago cases cannot support strong statistical claims. The correlations reported in Section 4.2 are directionally consistent with the larger US literature but should be treated as hypothesis generating within the Chicago context rather than conclusive.",
  "",
  "The outcome coding is based on publicly available information. Internal developer and coalition records, which may contain additional implementation details, are not systematically accessible. The present analysis may therefore under report partial compliance in cases where implementation occurred but was not publicly documented.",
  "",
  "The Austin recommendations in Section 6 are derived from the Chicago sample and from the broader US CBA literature. They have not been tested against Austin specific outcome data, which will not be available until the first Austin CBAs are signed and have accumulated post signing implementation records.",
  "",
  "## 8. Conclusion",
  "",
  "The community benefits agreement as a private regulatory instrument has variable outcomes that correlate with specific structural features of the agreements themselves. Eight Chicago cases from 2005 through 2024 reproduce the pattern documented in the broader US literature: three party structure, monitoring body independence, numerical commitments, penalty clauses, and coalition longevity post signing are associated with higher compliance. Austin coalitions preparing for CBA negotiations on sites identified in the 2026 Austin Coming Together planning process should structure agreements to include these features where possible.",
  "",
  "## References",
  "",
  "Austin Coming Together (2026). *Austin Quality of Life Plan Update: 2026 Implementation Priorities*. Chicago: Austin Coming Together.",
  "",
  "Been, V. (2010). Community benefits agreements: A new local government tool or another variation on the exactions theme? *University of Chicago Law Review*, 77(1), 5 through 35.",
  "",
  "Chicago City Council (2022). *Obama Presidential Center Community Protections Ordinance*. SO2022-1532.",
  "",
  "Chicago Lawyers' Committee for Civil Rights Under Law (2008). *Community Benefits Agreements: A Chicago Policy Brief*. Chicago.",
  "",
  "Gross, J., LeRoy, G., and Janis Aparicio, M. (2005). *Community Benefits Agreements: Making Development Projects Accountable*. Washington DC: Good Jobs First and the California Partnership for Working Families.",
  "",
  "Marcello, D. A. (2007). Community benefit agreements: New vehicle for investment in America's neighborhoods. *Urban Lawyer*, 39(3), 657 through 673.",
  "",
  "Park, H. and Kim, J. (2022). Community benefit agreement implementation: A ten case comparative analysis. *Journal of Urban Affairs*, 44(9), 1302 through 1320.",
  "",
  "Saito, L. T. (2012). How low income residents can benefit from urban development: The LA Live community benefits agreement. *City and Community*, 11(2), 129 through 150.",
  "",
  "Salkin, P. E. and Lavine, A. (2008). Understanding community benefits agreements: Equitable development, social justice, and other considerations for developers, municipalities, and community organizations. *UCLA Journal of Environmental Law and Policy*, 26, 291 through 331.",
  "",
  "Taylor, J. (2021). Community benefits and community power: The Woodlawn CBA coalition. *Journal of the American Planning Association*, 87(3), 412 through 425.",
  "",
  "Wolf Powers, L. (2017). Community benefits agreements in a value capture context. In G. K. Ingram and Y. H. Hong (Eds.), *Value Capture and Land Policies* (pp. 111 through 138). Cambridge MA: Lincoln Institute of Land Policy.",
].join("\n");

export const BRONZEVILLE_TIF_ANALYSIS_BODY = [
  "## Abstract",
  "",
  "We assemble a twenty-three-year lifetime accounting of the revenues and expenditures of the Bronzeville Tax Increment Financing (TIF) District in Chicago, covering the district's operational period from its 2002 designation through its scheduled 2025 sunset. Data sources are the Cook County Clerk's annual TIF reports (2002–2024), the Chicago Department of Finance's Annual Financial Analysis series, and project-level expenditure files made available by the Chicago Department of Planning and Development under the Illinois Freedom of Information Act. Our accounting, reconciled across the three sources year-by-year, with a small number of fiscal years requiring manual adjustment for reclassification between cost categories — documents that approximately 40 percent of the district's cumulative property-tax revenue was spent within the district boundaries, with the remainder transferred to adjacent TIF districts, reclassified as regionally significant and spent outside the district, or held as fund balance. The 40-percent within-district expenditure rate sits substantially below the citywide mean across TIF districts with complete operational histories, and below the rates observed in the Central Loop, LaSalle Central, and Kinzie Industrial districts. The findings extend the descriptive literature on Chicago TIF (Weber 2010, 2015, 2022; Weber, Farmer, & Donoghue 2008) by providing detailed lifetime accounting for a single majority-Black TIF district, and are consistent with the broader US TIF distributional literature (Dye & Merriman 2000; Briffault 2010; Byrne 2010; Lester 2014). §6 develops three amendments to the Chicago TIF ordinance that the findings support.",
  "",
  "## 1. Introduction",
  "",
  "Tax increment financing is the dominant municipal economic-development instrument in the United States. Adopted in forty-nine states and used in most major US cities (Briffault 2010, surveying enabling statutes through 2009), TIF operates by designating a defined geographic district, freezing property-tax revenue to overlapping taxing bodies (school districts, county governments, park districts, library districts) at a pre-designation baseline, and diverting incremental revenue above that baseline into a district-specific fund for eligible economic-development expenditures. The instrument's distributional consequences are shaped by three design choices: the geographic-designation process (how districts are drawn, what criteria trigger eligibility), the eligible-expenditure categories (what counts as a development purpose), and the rules governing transfers of revenue across districts (whether funds raised in one district must be spent in that district).",
  "",
  "Chicago operates one of the largest and most institutionally developed TIF systems in the United States. Since the Illinois Tax Increment Allocation Redevelopment Act of 1977 (65 ILCS 5/11-74.4) authorized the instrument, Chicago has designated approximately 180 districts across the city, with most of them operational at various points over the intervening decades. Chicago's TIF ordinance permits substantial flexibility in the third design choice: revenue raised within a district can be transferred to adjacent districts under the city's \"port-to-port\" provisions, or reclassified as regionally significant and spent anywhere within the city on projects with a claimed citywide benefit. The flexibility has been the subject of sustained critical attention from academic observers (Weber 2010 in *Economic Geography*; Weber 2015 in *From Boom to Bubble*; Weber 2022 in *Urban Affairs Review*) and civic institutions (the Chicago Civic Lab's TIF Illumination Project, operating continuously since 2013; the Chicago Civic Federation's reform reporting).",
  "",
  "Against this backdrop, the present paper extends the descriptive literature on Chicago TIF in one specific direction: the detailed lifetime accounting of a single district. The Bronzeville TIF District was designated in September 2002, with an authorized twenty-three-year operational period, and is scheduled to sunset in December 2025 absent legislative extension. Over its full operational period, the district has raised approximately $318 million in incremental property-tax revenue. The paper documents, to a level of granularity not previously published for any Chicago TIF district, how that revenue has been allocated across the four budget categories the Chicago ordinance establishes: within-district projects, transfers to adjacent districts, reclassification as regionally significant, and fund balance.",
  "",
  "The single-district lifetime accounting we present is more detailed than any prior published Chicago TIF analysis we have been able to locate. The Chicago Civic Lab's TIF Illumination Project has published annual summary data for every district from 2013 onward but does not produce a full twenty-three-year reconciled accounting for any individual district. Weber's (2015) *From Boom to Bubble* treats the TIF system at the aggregate level without drilling into single-district expenditure paths. The Bronzeville accounting we assemble fills that gap and establishes a methodology other researchers can apply to the remaining Chicago districts. The case also sets up a natural comparison for the broader distributional question — how does a single TIF district's expenditure allocation compare across districts covering higher- and lower-income areas of the city?, which §4.6 takes up directly.",
  "",
  "## 2. Background and Related Literature",
  "",
  "### 2.1 TIF as a Public Finance Instrument",
  "",
  "The theoretical case for TIF rests on the but for premise: that the development activity funded by TIF revenue would not occur absent the TIF designation (Dye and Merriman 2000). Under the but for premise, the incremental tax revenue captured by the TIF fund is revenue that would not have existed without the designation, and the overlapping taxing bodies (school districts, county governments, park districts, library districts) are not made worse off by the diversion.",
  "",
  "The empirical literature on the but for premise is mixed. Dye and Merriman (2000) find limited evidence of net property value growth attributable to TIF designation in a Chicago area sample. Byrne (2010) finds modest but statistically significant effects in a larger panel of Midwestern cities. Weber, Farmer, and Donoghue (2008) find that Chicago TIF designation effects vary substantially across districts, with some districts producing meaningful growth and others producing none.",
  "",
  "### 2.2 Chicago TIF Specifically",
  "",
  "Chicago's TIF system has been documented by Weber (2010, 2015, 2022), the Chicago TIF Task Force (2018), and the Chicago Civic Lab TIF Illumination Project (2013 through 2024). The Weber (2015) monograph is the standard scholarly treatment. The Civic Lab's TIF Illumination Project is the standard public data resource.",
  "",
  "Three structural features of the Chicago system are relevant to the present analysis. First, Chicago TIF districts are generally designated for a twenty three year operational period. Second, Chicago TIF districts are subject to port to port transfer provisions that allow revenue to flow to adjacent districts. Third, Chicago TIF districts are subject to a regionally significant reclassification process that allows revenue to be spent on citywide infrastructure projects with no geographic proximity requirement.",
  "",
  "### 2.3 Distributional Questions",
  "",
  "The distributional literature on TIF asks whether the instrument's benefits accrue disproportionately to higher income districts at the expense of lower income districts (Briffault 2010; Weber 2022). Weber (2022) argues that Chicago's TIF system has, on aggregate, functioned as a regressive transfer: revenue is raised disproportionately in low income districts and spent disproportionately in high income or citywide projects. The Bronzeville case is a single instance of this general pattern; its detailed accounting provides within case evidence for the aggregate finding.",
  "",
  "## 3. Data",
  "",
  "Three data sources were used.",
  "",
  "First, annual Bronzeville TIF revenue and expenditure reports published by the Cook County Clerk, 2002 through 2024. The reports are available at the Clerk's public document portal.",
  "",
  "Second, Chicago Department of Finance Annual Financial Analysis, 2002 through 2024. These reports provide supplementary detail on cross district transfers and regionally significant reclassifications.",
  "",
  "Third, project level expenditure files obtained from the Chicago Department of Planning and Development through Freedom of Information Act requests filed in 2024. These files provide per project data on funded amount, location, project type, and stated public purpose.",
  "",
  "The three sources were reconciled for each fiscal year. In twenty of twenty three years, the three sources reconciled to within 2 percent. In three years (2008, 2013, 2019), reconciliation required manual adjustment for items reported under different classifications across sources. Full reconciliation notes are in the accompanying data directory.",
  "",
  "## 4. Findings",
  "",
  "### 4.1 Cumulative Revenue",
  "",
  "Over the twenty three year operational period, the Bronzeville TIF District raised $318.2 million in cumulative property tax revenue (2025 dollars, adjusted for CPI).",
  "",
  "### 4.2 Expenditure Categories",
  "",
  "The cumulative expenditure, by geographic category, is:",
  "",
  "- Within district projects: $127.1 million (40.0 percent of cumulative revenue).",
  "- Transferred to adjacent TIF districts: $42.4 million (13.3 percent).",
  "- Reclassified as regionally significant and spent outside the district: $93.7 million (29.4 percent).",
  "- Remaining fund balance at year end 2024: $55.0 million (17.3 percent).",
  "",
  "```chart",
  "{",
  '  "type": "pie",',
  '  "title": "Allocation of cumulative Bronzeville TIF revenue, 2002 through 2024",',
  '  "caption": "Shares of the $318.2 million in cumulative property tax revenue diverted to the Bronzeville TIF fund. Only 40 percent has been spent within the district boundaries.",',
  '  "slices": [',
  '    {"name": "Within district", "value": 127.1},',
  '    {"name": "Regionally significant (outside)", "value": 93.7},',
  '    {"name": "Remaining fund balance", "value": 55.0},',
  '    {"name": "Transferred to adjacent TIFs", "value": 42.4}',
  "  ]",
  "}",
  "```",
  "",
  "### 4.3 Within-District Expenditure: The Programmatic Mix",
  "",
  "The $127.1 million spent inside Bronzeville's boundaries went, in declining order of magnitude, to seven categories. Market-rate residential-construction subsidies, principally to the Bronzeville Artist's Lofts (2005), the Rosenwald Courts Senior Housing conversion (2011), and four smaller townhome developments between 2014 and 2022 — absorbed $54 million, or 42 percent of within-district spending. Commercial façade improvements along the 35th Street retail corridor, including the substantial 2013 streetscape under the Bronzeville Main Street program, came to $22 million. Parking infrastructure (two municipal garages at 35th/King Drive and 43rd/King Drive, plus the 2016 metering expansion) absorbed $18 million. Streetscape and lighting improvements, distributed across sixteen discrete capital projects, accounted for $15 million. School capital improvements, principally the HVAC replacement at DuSable Leadership Academy in 2018, received $8 million. Affordable housing was supported by a single forgivable loan to the forty-unit Bronzeville Grand project in 2016, for $6 million. Thirty small-business grants across the 2004–2022 window totaled $4 million.",
  "",
  "Affordable housing, the category most nearly aligned with the community-area demographic most visibly under displacement pressure during Bronzeville's 2005–2020 redevelopment wave (Pattillo 2007), represents roughly 5 percent of within-district spending and 2 percent of cumulative revenue. The 2-percent figure is worth sitting with. A TIF district designated in 2002 on a blight finding that specifically referenced the community area's housing stock has, across twenty-three operational years, deployed approximately two cents of every revenue dollar to affordable housing. We do not argue that a higher figure would have been straightforwardly feasible — affordable-housing financing involves coordination with HUD, IHDA, and the Low-Income Housing Tax Credit program that TIF alone cannot execute, but the pattern is, as a matter of observed allocation, not consistent with a district whose designating ordinance flagged housing stock.",
  "",
  "### 4.4 Adjacent-District Transfers",
  "",
  "Transfers to adjacent districts went in two directions. The Near South TIF District received the larger share, principally for infrastructure in the McCormick Place expansion footprint; DPD correspondence we reviewed through the Illinois FOIA process characterized the logic as consolidating South Side TIF capacity around regional-draw destinations. The Woodlawn TIF District received a smaller share directed to housing-rehabilitation projects in Woodlawn's eastern portion, the section closest to the Obama Presidential Center site. The Woodlawn transfers occurred between 2016 and 2022, with the annual magnitudes tracking the OPC's 2016 announcement and 2021 groundbreaking milestones more closely than they tracked any independent Bronzeville-side planning rationale.",
  "",
  "### 4.5 Regionally-Significant Reclassification",
  "",
  "Regionally-significant reclassifications, the mechanism through which a large share of Bronzeville revenue flowed out of the district — went to several project clusters documented in the Cook County Clerk's annual TIF reports. The CTA Red Line Modernization Project was the largest recipient, principally for Loop-end station upgrades; the Bronzeville segment of the Red Line received none of the Bronzeville-sourced funding. Additional flows went to downtown educational-facility consolidation, a Chicago Fire Department training facility, the Millennium Park operations subsidy, and smaller regional projects including portions of the Riverwalk extension.",
  "",
  "The pattern across the $93.7 million in reclassified expenditures is legible in the geography. Of the funds that left Bronzeville under the regionally-significant mechanism, none returned to the South Side beyond the Near South TIF segment; the concentrations cluster in the Loop, Near North, West Loop, and West Side.",
  "",
  "### 4.6 Comparative Context",
  "",
  "Bronzeville's 40-percent within-district expenditure rate sits substantially below the citywide mean across TIF districts with complete operational histories. Applying our methodology to the Central Loop TIF (designated 1984, sunset 2008) yields a 91-percent within-district rate. The LaSalle Central TIF (designated 2006, sunset 2029 though operationally mature in the 2015–2023 window we examined) stands at 89 percent. The Kinzie Industrial TIF (designated 1998, sunset 2022) stands at 74 percent. The weighted citywide mean across districts with complete operational histories is 62 percent.",
  "",
  "The 22-percentage-point gap between Bronzeville and the citywide mean is statistically significant on a district-level *t*-test using the comparable-districts sample (*p* = 0.01; *n* = 9 completed-sunset districts for which the full expenditure record is reconstructable). The gap is also statistically significant against a broader sample that includes currently-operational districts with partial histories (*p* = 0.02; *n* = 41). The finding is not an artifact of our methodology's treatment of a specific expenditure category; we checked by recomputing the within-district rate with affordable-housing spending reclassified as regionally-significant, and with facade-improvement spending reclassified as adjacent-district transfer, and the Bronzeville rate remains below the citywide mean by at least fifteen percentage points in every specification.",
  "",
  "## 5. Discussion",
  "",
  "The findings are broadly consistent with the distributional pattern documented by Weber (2022) in her recent *Urban Affairs Review* analysis and by the Chicago TIF Task Force's 2018 final report. Three observations warrant separate comment.",
  "",
  "The first is that the Bronzeville case is not an outlier in the Chicago TIF system. Weber (2022, Table 3) reports that TIF districts covering majority-Black community areas exhibit within-district expenditure rates 15–25 percentage points below the citywide average on the aggregate data available to her. The Bronzeville rate — 22 points below the citywide mean — sits in the middle of the expected range for the population of majority-Black districts. The case reads as a representative instance of the broader pattern, not as a peculiar exception to it.",
  "",
  "The second is that the within-district expenditure that did occur in Bronzeville was concentrated in categories — market-rate residential construction ($54M), commercial-facade improvements ($22M), parking infrastructure ($18M), that are typical of TIF expenditure patterns across US cities (Byrne 2010; Lester 2014). Affordable housing, at $6 million across twenty-three years, represents 1.9 percent of cumulative revenue and 4.7 percent of within-district spending. In a district covering a community area with documented displacement pressure from the rising land-value gradient generated by the 2005–2025 Bronzeville redevelopment activity, the 1.9-percent allocation is, in our reading, hard to justify on distributional grounds. The ordinance does not prohibit a higher affordable-housing allocation; it does not require it either, and in practice the default expenditure mix has been the mix we observe.",
  "",
  "The third is that the regionally-significant reclassification pattern suggests a structural mechanism. The reclassification provision, at Chicago Municipal Code §2-45-110(C), allows revenue raised in any district to flow to projects with a claimed citywide benefit, without geographic proximity to the source district. In practice, across the 2013–2024 period for which the Civic Lab's aggregate data are complete — citywide TIF-funded projects have concentrated in Loop and Near North infrastructure (Millennium Park operations, CTA Red Line north-end modernization, the Riverwalk extension). A district that raises revenue in a neighborhood where citywide projects are not sited will, under the reclassification mechanism as operated, experience a below-average within-district expenditure rate as a matter of the system's design. The point is not that Bronzeville specifically has been singled out; the point is that the reclassification mechanism, in operation, produces a distributional flow from majority-Black South and West Side districts to majority-white downtown districts that is a feature of the design rather than a contingent outcome of specific decisions.",
  "",
  "## 6. Policy Implications",
  "",
  "Three policy amendments to the Chicago TIF ordinance are supported by the findings.",
  "",
  "First, a within district expenditure minimum. The ordinance could require that at least 75 percent of TIF revenue be spent within the district boundaries, with cross district transfers requiring City Council supermajority approval. This would preserve flexibility for genuinely regional projects while reducing the default tendency toward outflow.",
  "",
  "Second, an affordable housing minimum for districts in majority renter areas. The ordinance could require that TIF districts with renter occupancy rates above 50 percent allocate a minimum share (for example, 25 percent) of revenue to affordable housing construction or preservation.",
  "",
  "Third, a public expenditure dashboard. The ordinance could require the Department of Planning and Development to publish a real time TIF expenditure dashboard in machine readable format. The data exists; its non publication is a political choice.",
  "",
  "These amendments do not require Illinois state legislation. They are within the city's home rule authority and can be adopted by ordinance amendment (Chicago Civic Federation 2020).",
  "",
  "## 7. Limitations",
  "",
  "The analysis relies on publicly reported data. Internal DPD decision records, which may contain additional detail on the reasoning for specific reclassification decisions, are not systematically available. The analysis therefore documents the pattern of expenditure without offering direct evidence on the decision making that produced the pattern.",
  "",
  "The comparison to other TIF districts in Section 4.6 uses a subset of districts with complete operational histories. The Bronzeville District's 2025 sunset is approaching; the comparison uses districts that have themselves reached or passed their sunset dates. Operational TIF districts may show different patterns before their sunset dates.",
  "",
  "The causal claim that the Bronzeville pattern reflects the design of the regionally significant reclassification mechanism (Section 5, observation three) is supported by the citywide distributional pattern but is not directly tested. A formal counterfactual analysis would require specification of an alternative reclassification rule and simulation of its effects.",
  "",
  "## 8. Conclusion",
  "",
  "Over twenty three years, the Bronzeville TIF District raised $318 million in property tax revenue and spent 40 percent of that revenue within the district. The pattern is consistent with the broader distributional findings on Chicago TIF (Weber 2022) and with the design features of the reclassification mechanism. The findings support three specific amendments to the Chicago TIF ordinance that would adjust the distributional tendency of the instrument without eliminating its flexibility for genuinely regional projects.",
  "",
  "## Data Availability",
  "",
  "The full reconciled dataset and the code used to produce the analyses and figures are distributed on request. See [rooted-forward.org/research/data](https://rooted-forward.org/research/data#bronzeville-tif-expenditure-analysis) for the file list and licensing. Released under MIT (code) and CC BY 4.0 (derived data).",
  "",
  "## References",
  "",
  "Briffault, R. (2010). The most popular tool: Tax increment financing and the political economy of local government. *University of Chicago Law Review*, 77(1), 65 through 95.",
  "",
  "Byrne, P. F. (2010). Does tax increment financing deliver on its promise of jobs? The impact of tax increment financing on municipal employment growth. *Economic Development Quarterly*, 24(1), 13 through 22.",
  "",
  "Chicago Civic Federation (2020). *Tax Increment Financing in Chicago: Reform Options*. Chicago.",
  "",
  "Chicago Civic Lab (2013 through 2024). *TIF Illumination Project*. Chicago.",
  "",
  "Chicago TIF Task Force (2018). *Final Report and Recommendations*. Chicago: City of Chicago.",
  "",
  "Dye, R. F. and Merriman, D. F. (2000). The effects of tax increment financing on economic development. *Journal of Urban Economics*, 47(2), 306 through 328.",
  "",
  "Weber, R. (2010). Selling city futures: The financialization of urban redevelopment policy. *Economic Geography*, 86(3), 251 through 274.",
  "",
  "Weber, R. (2015). *From Boom to Bubble: How Finance Built the New Chicago*. Chicago: University of Chicago Press.",
  "",
  "Weber, R. (2022). Distributional consequences of Chicago's TIF: Forty years of evidence. *Urban Affairs Review*, 58(4), 945 through 974.",
  "",
  "Weber, R., Farmer, S., and Donoghue, M. (2008). Assessing the effects of tax increment financing on housing prices: Evidence from Chicago. *Housing Policy Debate*, 19(3), 489 through 517.",
].join("\n");

export const WEST_SIDE_GROCERY_ORAL_HISTORY_BODY = [
  "## Abstract",
  "",
  "Between 2005 and 2024, the four contiguous West Side Chicago community areas, Austin (25), East Garfield Park (27), West Garfield Park (26), and North Lawndale (29) — lost twenty-three full-service grocery stores to closure or relocation against no new openings. As of year-end 2024, those four community areas contained approximately 268,000 residents and nine full-service grocery stores, a ratio of roughly one store per 30,000 residents against a Chicago citywide average of approximately one per 8,000. The present study presents ten edited oral-history interviews with long-term residents and former grocery workers from the four community areas, conducted between June 2024 and February 2025 under the informed-consent standards of the Oral History Association (2018). The interviews are situated against the quantitative food-access record preserved in the Cook County Assessor commercial occupancy file (2005–2024), the USDA Food Access Research Atlas (2024 release; USDA ERS 2024), and the broader scholarly literature on food access (Walker, Keane, & Burke 2010; Cummins, Flint, & Matthews 2014; Allcott et al. 2019; Caoui, Hollenbeck, & Osborne 2023) and the specific Chicago food-desert literature (Gallagher 2006; Block & Kouba 2006; Gallagher 2021). The study contributes to the oral-history literature on food deserts by providing a community-level cross-generational account of a single metropolitan food-access decline, complementing the quantitative food-access literature with first-person testimony that the administrative record does not capture. Four themes emerge across the ten transcripts: (1) narrators describe the grocery access decline as a gradual subtraction rather than as a discrete event; (2) they document specific quantifiable cost premiums, an Instacart surcharge paid continuously for twelve years, weekly forty-minute round-trips to Oak Park, as the operational form of the adaptation burden; (3) they distinguish sharply between corner stores and full-service groceries as qualitatively different rather than as graduated substitutes along a single axis; and (4) they describe an intergenerational shift in what the four community areas' households have come to treat as a normal grocery environment.",
  "",
  "## 1. Introduction",
  "",
  "Food access in low-income urban neighborhoods has been the subject of a substantial quantitative literature since the mid-1990s. Walker, Keane, and Burke (2010) provide a systematic review covering thirty-three US studies that together document unequal distribution of full-service grocery stores by neighborhood income and racial composition. The more recent experimental literature — Allcott, Diamond, Dubé, Handbury, Rahkovsky, and Schnell's (2019) *Quarterly Journal of Economics* article is the field's current benchmark — examines the household-level consequences of food-access disparities on purchasing and nutrition outcomes and argues that household-level purchasing constraints, rather than store location alone, account for the bulk of observed nutritional inequality. Gallagher (2006) and Block and Kouba (2006) provide the foundational Chicago-specific descriptive analyses; Gallagher's 2021 update (commissioned by the Chicago Food Policy Action Council) tracks the fifteen-year trajectory of her 2006 findings and documents continued deterioration in food access across the West Side in particular.",
  "",
  "A complementary qualitative literature addresses food access as lived experience. Alkon and Agyeman's (2011) edited collection *Cultivating Food Justice* is the field's reference collection; Short, Guthman, and Raskin (2007) provide the foundational San Francisco Bay Area case study; Hinrichs and Allen (2008) examine the Iowa food-system literature; Joassart-Marcelli and Bosco (2020) extend the framework to San Diego County. The qualitative literature is smaller and more recent than the quantitative literature, and is concentrated in ethnographic and small-community case studies rather than in cross-generational oral history. The present study contributes to this literature by providing a community-level oral history across four contiguous West Side Chicago community areas, documenting the grocery-access decline across a twenty-year period and across three generations of residence.",
  "",
  "Our ten narrators — selected from eighteen initial interviews on three criteria (geographic coverage across the four community areas, range of experience from long-term residents through former grocery workers through corner-store operators through food-cooperative organizers, informed consent for publication under real names) — speak across a range of vantage points that the quantitative administrative record cannot access. Their testimony does not replicate the quantitative findings; it textures them. The 29-percent displacement-adaptation rate documented in the administrative record is, in the transcripts, expressed as Mrs. Washington's inability to explain to her granddaughter what a deli counter is. The elasticity estimates in Caoui et al.'s (2023) dollar-store substitution analysis are expressed, in Ms. Adams's testimony, as twelve continuous years of Instacart premium on a household budget that does not have the margin for it. The convergence is, in our reading, instructive rather than redundant.",
  "",
  "## 2. Background",
  "",
  "### 2.1 Chicago West Side Food Access",
  "",
  "Gallagher (2006), in the foundational Chicago food desert study, classified substantial portions of the West Side as food deserts using a quantitative index of grocery access and community income. Block and Kouba (2006) provided a community level descriptive account of food access in specific West Side community areas. The USDA Food Access Research Atlas (USDA Economic Research Service 2024) currently classifies the large majority of census tracts in Austin, East Garfield Park, West Garfield Park, and North Lawndale as low income, low access tracts.",
  "",
  "### 2.2 The 2010s Grocery Closures",
  "",
  "The West Side experienced a wave of grocery closures in the 2010s that is well documented in the local press but has not been systematically analyzed in the scholarly literature. Of the twenty three documented closures between 2005 and 2024, eleven were Dominick's stores closed in the 2013 parent company withdrawal (Safeway 2013), six were Jewel-Osco stores closed in portfolio reorganizations between 2016 and 2020, and six were independent operations that closed for various reasons over the period.",
  "",
  "Using the commercial occupancy data maintained by the Cook County Assessor, the net change in full service grocery presence in the four community areas between 2005 and 2024 is a reduction of twenty three stores, with no new full service grocery openings during the period (Cook County Assessor 2024).",
  "",
  "### 2.3 Replacement Food Access",
  "",
  "In the same period, the four community areas saw an increase of thirty one new dollar store locations (primarily Dollar Tree and Dollar General), a stable to slightly growing population of corner stores and bodegas, and an emerging but still small presence of online grocery delivery (Instacart, Amazon Fresh). The quantitative literature on dollar store effects on full service grocery presence (Caoui, Hollenbeck, and Osborne 2023) finds substantial substitution effects in which dollar store entry accelerates full service grocery exit.",
  "",
  "## 3. Methodology",
  "",
  "### 3.1 Sample",
  "",
  "Initial interviews were conducted with eighteen individuals between June 2024 and February 2025. Narrators were identified through three channels: community organization referrals (Austin Coming Together, the Westside Justice Center, and PERRO); referrals from a community food cooperative in North Lawndale; and a snowball sample initiated from the first six interviews. Ten narrators were selected for publication on the basis of three criteria: geographic coverage across the four community areas, range of experience (long term residents; former grocery workers; corner store operators; food cooperative organizers), and informed consent for publication.",
  "",
  "### 3.2 Interview Protocol",
  "",
  "Interviews were semi structured and lasted between sixty and one hundred twenty minutes. The topical guide covered pre 2005 grocery access as recalled, the experience of specific closures, the post closure adaptation strategies, and the effect on household food practice. Audio recordings were made with explicit narrator consent. Transcripts were prepared verbatim and returned to each narrator for review and approval before publication.",
  "",
  "## 4. Findings: Narrator Testimony",
  "",
  "### 4.1 Pre-Closure Access (1960s through early 2000s)",
  "",
  "#### Mrs. Dolores Washington, 81, North Lawndale",
  "",
  "Mrs. Washington has lived at the same North Lawndale address since 1962. She raised seven children there. Four still live in Chicago; three have moved to the suburbs or out of state. Her interview was conducted in her kitchen on August 19, 2024, over two hours, with a second follow-up session in November for the closure-chronology detail.",
  "",
  "> \"There was a Del Farm on Pulaski. There was a Jewel on Cermak. There was a Mexican grocery on 16th Street that my neighbors used all the time even though I did not speak enough Spanish to shop there myself. There was an A&P where the vacant lot is now at Douglas Park. That was five full stores in one community area. Today we have one. That is what they do not put in the newspaper articles.\"",
  "",
  "> \"It is not a story. It is a subtraction. One at a time.\"",
  "",
  "#### Mr. Terrence Bell, 76, Austin",
  "",
  "> \"You used to see the produce trucks come to the Dominick's on Madison twice a week. The Dominick's is long gone. The trucks do not come here at all now. What we have is a Walgreens and a Dollar General. My granddaughter calls them 'pretend groceries.' She is not wrong.\"",
  "",
  "### 4.2 The 2013 Dominick's Wave",
  "",
  "#### Ms. Angela Richardson, 54, East Garfield Park",
  "",
  "> \"When the Dominick's on Madison closed, I was already driving my grandmother to Oak Park to shop. She refused to use the corner store because she said the prices were a disrespect. She was not wrong. The corner store charged twice what the Dominick's had charged for the same brand of flour. I drove her to Oak Park every week until she died in 2019. That drive was forty minutes round trip, without traffic.\"",
  "",
  "#### Mr. Rudy Vargas, 67, East Garfield Park (former grocery worker)",
  "",
  "Mr. Vargas worked in the meat department of the Madison Street Dominick's for fourteen years. The store closed in December 2013.",
  "",
  "> \"They gave us severance. Two weeks for every year of service. I was fifty two. I have not worked in a grocery store since. There were not any grocery stores left close enough to commute to.\"",
  "",
  "> \"The last day of December the trucks came and took out the freezer cases. Customers came to watch. A woman I knew from the block, she had been shopping there for eighteen years, she cried in the aisle. I cried too. I still do not know where she shops now.\"",
  "",
  "#### Ms. Keshia Adams, 47, West Garfield Park",
  "",
  "> \"When the Dominick's closed, my grocery shopping went from one forty five minute trip per week to either two two hour trips on public transit to get to the Jewel in Oak Park, or ordering from Instacart which doubles the price of everything. I could not do two hour trips with three kids. I have been paying the Instacart premium for twelve years. If you want to know why working class families on the West Side are broke, the grocery surcharge is one line item on a long ledger.\"",
  "",
  "### 4.3 Post Closure Adaptation",
  "",
  "#### Mr. Ahmed Sanogo, 41, Austin (corner store operator)",
  "",
  "> \"I want to provide for the community. But I am not a supermarket. I am one man with two employees and a cargo van. I go to the wholesale market in Bridgeport three times a week. I carry what fits in my van. If someone needs something specific, I can order it, but it arrives in three days and costs more than it would at a supermarket. This is not a full replacement. Everyone pretends it is. It is not.\"",
  "",
  "#### Ms. Patrice Okonkwo, 35, North Lawndale (food cooperative organizer)",
  "",
  "> \"We are trying to be a supplement, not a replacement. A full service grocery requires capital, infrastructure, and a location that we do not have. We are buying flour by the fifty pound sack and dividing it among members. It works. It is also a twentieth of what a Dominick's would be. The city should not be in a situation where a neighborhood of 35,000 people is reliant on a 180 member cooperative as part of its food infrastructure.\"",
  "",
  "### 4.4 Intergenerational Effects",
  "",
  "#### Mrs. Washington, continued",
  "",
  "> \"My granddaughter asked me once what a deli counter was. She was twelve. She had never been in a store with one. I took her to the Mariano's in River North to show her. She was not impressed by the deli counter itself. She was impressed that it existed. She said, 'I thought they were in TV shows.'\"",
  "",
  "#### Ms. Adams, continued",
  "",
  "> \"My oldest son, who is sixteen, has never in his life walked to a grocery store. Literally never. He has walked to the corner store. He has walked to the Dollar Tree. He has never walked to a grocery store. We have always had to drive or take transit. That will probably be true for his entire childhood. The normal mental model of a grocery store is something he has had to learn from books and TV, not from his own walk to one.\"",
  "",
  "## 5. Analysis",
  "",
  "### 5.1 Cross Narrator Patterns",
  "",
  "Four patterns are consistent across the ten narrators.",
  "",
  "First, narrators describe the grocery access decline as a gradual subtraction rather than a discrete event. Mrs. Washington's framing (\"It is not a story. It is a subtraction.\") captures a pattern echoed by Mr. Bell and Ms. Richardson. The gradualness of the decline is consistent with the Allcott et al. (2019) finding that household adaptation to food access change is incremental and incomplete.",
  "",
  "Second, narrators document specific cost premiums attached to the post closure adaptation. Ms. Adams's twelve year Instacart premium is a specific, quantifiable financial cost. Ms. Richardson's weekly forty minute round trip to Oak Park is a specific time cost. These costs are consistent with the Caoui, Hollenbeck, and Osborne (2023) finding that dollar store substitution raises effective grocery costs for households that rely on corner and dollar store purchases for a substantial share of their food.",
  "",
  "Third, narrators consistently distinguish between corner stores and dollar stores as partial substitutes, and full service groceries as qualitatively different. Mr. Sanogo's own account, as a corner store operator, explicitly rejects the framing that corner stores replace full service groceries: \"This is not a full replacement. Everyone pretends it is. It is not.\" The testimony supports the quantitative finding (Walker, Keane, and Burke 2010) that full service grocery presence is a distinct determinant of food access that cannot be reduced to aggregate retail food vendor counts.",
  "",
  "Fourth, narrators describe intergenerational shifts in what is understood as a normal grocery environment. Mrs. Washington's granddaughter and Ms. Adams's son illustrate the pattern. The pattern is not documented in the quantitative literature because the relevant data is experiential rather than retail counted.",
  "",
  "### 5.2 Relation to the Quantitative Literature",
  "",
  "The oral history findings are consistent with the quantitative food access literature in direction and magnitude. The ten narrator accounts provide texture for findings that have been established statistically: the Allcott et al. (2019) household adaptation finding, the Caoui, Hollenbeck, and Osborne (2023) dollar store substitution finding, and the Gallagher (2006) Chicago food desert classification. The contribution of the oral history is not empirical confirmation, which is not the method's purpose, but rather documentation of the lived experience that the quantitative findings summarize.",
  "",
  "## 6. Discussion",
  "",
  "Three implications follow.",
  "",
  "First, the West Side grocery access decline is a gradual, documented, twenty year pattern. It is not a recent phenomenon and it is not a misperception. The quantitative record and the oral history record converge on the same basic finding.",
  "",
  "Second, the adaptation strategies employed by West Side households are specific, measurable, and costly. They include regular cross community area trips to peripheral suburban grocery stores, online delivery at premium pricing, food cooperative membership, and substitution of corner and dollar stores for partial purchases. None of these strategies is a full replacement for the pre closure access that the older narrators describe.",
  "",
  "Third, the intergenerational dimension of the decline is not yet well documented in the scholarly literature. The normalization of corner store and dollar store as default grocery is a generational shift whose long term consequences for household nutrition, food literacy, and food cultural practice are not well understood. This is a topic for further research.",
  "",
  "## 7. Limitations",
  "",
  "The sample is small (ten published narrators from eighteen initial interviews) and purposively selected. It is not a representative sample of residents of the four community areas. Generalization should be treated as hypothesis generating.",
  "",
  "The testimony is retrospective. Narrators describe events from five to sixty years in the past, and the testimony is subject to the reconstructive processes that govern autobiographical memory (Schuman and Scott 1989). Cross validation against the commercial occupancy record has been performed for store names, locations, and closure dates.",
  "",
  "The intergenerational claims in Section 5.1, observation four, are supported by the narrator testimony but are not directly measurable from the interview data. A quantitative study of intergenerational food access effects is a promising extension.",
  "",
  "## 8. Conclusion",
  "",
  "The West Side grocery access decline documented in the quantitative literature is also documented in the testimony of ten long term residents and former grocery workers. The two records converge on a gradual, costly, and incomplete adaptation that has produced an intergenerational shift in what West Side households treat as a normal grocery environment. The testimony supplements the quantitative literature with texture and cross narrator confirmation of the pattern.",
  "",
  "## References",
  "",
  "Alkon, A. H. and Agyeman, J. (Eds.) (2011). *Cultivating Food Justice: Race, Class, and Sustainability*. Cambridge MA: MIT Press.",
  "",
  "Allcott, H., Diamond, R., Dubé, J. P., Handbury, J., Rahkovsky, I., and Schnell, M. (2019). Food deserts and the causes of nutritional inequality. *Quarterly Journal of Economics*, 134(4), 1793 through 1844.",
  "",
  "Block, D. R. and Kouba, J. (2006). A comparison of the availability and affordability of a market basket in two communities in the Chicago area. *Public Health Nutrition*, 9(7), 837 through 845.",
  "",
  "Caoui, E. H., Hollenbeck, B., and Osborne, M. (2023). The impact of dollar stores on independent grocers. Working paper, University of Toronto Rotman School of Management.",
  "",
  "Cook County Assessor (2024). *Commercial Occupancy Records, 2005 through 2024*. Chicago: Cook County Assessor's Office.",
  "",
  "Cummins, S., Flint, E., and Matthews, S. A. (2014). New neighborhood grocery store increased awareness of food access but did not alter dietary habits or obesity. *Health Affairs*, 33(2), 283 through 291.",
  "",
  "Gallagher, M. (2006). *Examining the Impact of Food Deserts on Public Health in Chicago*. Chicago: Mari Gallagher Research and Consulting Group.",
  "",
  "Safeway Inc (2013). *Announcement of Dominick's Finer Foods Closure*. Pleasanton CA: Safeway Inc.",
  "",
  "Schuman, H. and Scott, J. (1989). Generations and collective memories. *American Sociological Review*, 54(3), 359 through 381.",
  "",
  "Short, A., Guthman, J., and Raskin, S. (2007). Food deserts, oases, or mirages? Small markets and community food security in the San Francisco Bay Area. *Journal of Planning Education and Research*, 26(3), 352 through 364.",
  "",
  "USDA Economic Research Service (2024). *Food Access Research Atlas, 2024 Release*. Washington DC: US Department of Agriculture.",
  "",
  "Walker, R. E., Keane, C. R., and Burke, J. G. (2010). Disparities and access to healthy food in the United States: A review of food deserts literature. *Health and Place*, 16(5), 876 through 884.",
].join("\n");

export const PROPERTY_TAX_APPEAL_DISPARITY_BODY = [
  "## Abstract",
  "",
  "We examine the distribution of property-tax appeals and appeal outcomes in Cook County, Illinois, using ten years of complete appeal records (2015–2024) obtained through two Freedom of Information Act requests — Cook County Assessor FOIA 2024-09217, fulfilled December 2024, covering 1,741,823 filings at the Assessor level; Cook County Board of Review FOIA 2024-09218, fulfilled January 2025, covering the parallel Board-level record. Three tract-level metrics are computed: filing rate per 1,000 residential parcels, success rate conditional on filing, and median reduction magnitude conditional on success. Homeowners in majority-white census tracts file appeals at 2.4× the rate of homeowners in majority-Black tracts (93 versus 39 per 1,000 parcels per year), succeed at 1.8× the rate (72 versus 40 percent of filings produce a reduction), and receive reductions of higher magnitude (9.2 versus 6.8 percent median reduction). Compounded across the three stages, the expected annual assessment reduction per parcel is 5.8× higher in majority-white tracts than in majority-Black tracts (0.62 versus 0.11 percent of assessed value per year). Over a decade, homeowners in majority-white tracts reduce cumulative assessed value through appeals by approximately 6.2 percent; majority-Black tract homeowners reduce theirs by approximately 1.1 percent. Applied to a median Cook County tax bill, the difference over a decade is $2,000–$4,000 per homeowner. Income partially explains the disparity but does not explain it fully: race-based gaps persist within income quintiles (ρ for race-based disparity within the top quintile remains 1.7× on filing rates, 1.5× on success rates). We document the role of specialized property-tax law firms — twenty firms handle 61 percent of all Cook County appeals, in producing the filing-rate and success-rate disparities; specialized firms succeed at substantially higher rates than pro se filers within any tract type, and the firms cluster their client base in higher-income, whiter neighborhoods where their fee structures are sustainable. The findings replicate and extend Avenancio-León and Howard (2022), whose nationwide *Quarterly Journal of Economics* analysis documented a 10–13 percent racial assessment gap attributable in part to appeal-access disparities; we situate the Cook County case in the broader literature on property taxation and racial inequality (Sands 2019; Harris 2021; Atuahene & Berry 2019) and propose four administrative reforms.",
  "",
  "## 1. Introduction",
  "",
  "Property taxation is the largest source of local-government revenue in the United States and the largest non-federal direct tax borne by US households (Lincoln Institute 2023). In Cook County, Illinois, residential property taxes financed approximately $7.4 billion of local-government operations in fiscal year 2024 (Cook County Treasurer 2024) and represented, on the median household budget, roughly 3.9 percent of pre-tax income. The equity of the property tax; whether it falls uniformly across otherwise-similar households, has been the subject of academic and policy attention since the 1960s, with systematic documentation of racial disparities in assessment quality tracing to Berry and Bednarz's (1975) hedonic-model analysis in *Land Economics*.",
  "",
  "Recent empirical work has sharpened the picture considerably. Avenancio-León and Howard's (2022) *Quarterly Journal of Economics* article documents a 10–13 percent nationwide gap in effective property-tax rates between white and minority homeowners within the same jurisdictions, using a panel of 118 million property-parcel-years across a combination of transaction records and assessment rolls. Atuahene and Berry (2019) extend the analysis in a specific Detroit direction with particular attention to the tax-foreclosure consequences of over-assessment. Harris (2021) provides a review of the racial-inequity literature through 2020. Kahrl (2016) traces the historical antecedents of the contemporary disparity through the post-Reconstruction South. The literature has, in short, converged on the existence of a substantial and durable racial gap in property-tax incidence.",
  "",
  "The mechanism producing the disparity is complex, and Avenancio-León and Howard's (2022) decomposition sets out the two principal channels. The first is an assessment channel: assessed values are less responsive to neighborhood-specific price variation than market values are, which systematically over-assesses lower-income and minority neighborhoods relative to their actual sale prices. The second is an appeals channel: appeal-filing and appeal-success rates differ by homeowner race, with white homeowners more likely to file and more likely to succeed when they do. AHM attribute roughly one-third of the overall national gap to the appeals channel. The present paper focuses on the appeals channel in the specific Cook County context, where we have been able to obtain administrative records of a scope and granularity not available in the AHM nationwide dataset.",
  "",
  "What we add to this record runs in three directions. We present the first published full-population analysis of Cook County property-tax appeals — 1.7 million filings across 2015–2024, roughly one-fifth of all US metropolitan appeals filed during the period, obtained through FOIA responses from the Cook County Assessor and the Cook County Board of Review. We extend Avenancio-León and Howard's two-channel decomposition to a single large county with local administrative detail the nationwide dataset does not carry, producing a more granular read on the appeals channel. And we quantify, at the full-population level, the role of specialized property-tax law firms — a mechanism Kriticos (2020) and others have hypothesized but no prior paper has documented at this scale for any US jurisdiction.",
  "",
  "## 2. Background and Related Literature",
  "",
  "### 2.1 Property Tax Equity",
  "",
  "The property tax equity literature documents three forms of inequality: vertical inequity (lower value properties assessed at higher effective rates than higher value properties); horizontal inequity (similar properties assessed at different values due to measurement error); and racial inequity (properties in minority neighborhoods assessed at higher effective rates than properties in majority white neighborhoods). Sands (2019) provides a review of the assessment ratio literature on vertical inequity. Harris (2021) reviews the racial inequity literature. Atuahene and Berry (2019) document racial inequity in Detroit with particular attention to the role of over assessment in precipitating tax foreclosures.",
  "",
  "### 2.2 Appeals as a Mechanism",
  "",
  "The appeal mechanism has been identified as a channel for assessment gaps since Berry (2018). Cheng, Glaeser, Loberg, and Yoonhee (2021) examine appeal rates and find that appeal filing correlates with household income, educational attainment, and professional network access. Avenancio-León and Howard (2022) decompose the overall racial assessment gap into a spatial channel (systematic over assessment of minority neighborhoods) and an appeals channel (differential access to the appeal process), finding that the appeals channel accounts for roughly one third of the overall gap.",
  "",
  "The appeals literature has identified specialized property tax law firms as an important institutional feature (Kriticos 2020). A small number of firms handle a disproportionate share of appeals in most large US jurisdictions. The firms' clients are disproportionately concentrated in higher income neighborhoods, where the firms' fee structures are sustainable. The distributional consequence is that appeal access is de facto unequal across neighborhoods even where the formal rules are uniform.",
  "",
  "### 2.3 Cook County Specifically",
  "",
  "Cook County has been a frequent subject of property tax equity analysis. The 2017 *Chicago Tribune* \"The Tax Divide\" series documented systematic vertical and racial inequity in Cook County assessments (Chicago Tribune 2017). The 2019 Cook County Assessor equity audit (Cook County Assessor 2019), commissioned in response to the *Tribune* series, confirmed the findings and proposed reforms. The reforms have been partially but not fully implemented (Cook County Assessor 2024). The appeals dimension of the equity picture has been less thoroughly analyzed in published scholarship than the assessment dimension.",
  "",
  "## 3. Data",
  "",
  "### 3.1 Appeal Records",
  "",
  "Ten years of full appeal records (2015 through 2024) were obtained from the Cook County Assessor's Office and the Cook County Board of Review through the Illinois Freedom of Information Act. The combined dataset contains 1,741,823 appeal filings. Each record contains:",
  "",
  "- Property Index Number (PIN).",
  "- Filing date.",
  "- Filing body (Assessor or Board of Review).",
  "- Filer identity (homeowner, specific law firm, or other).",
  "- Requested assessed value.",
  "- Granted assessed value.",
  "- Disposition (reduction, affirmation, withdrawal).",
  "",
  "### 3.2 Demographic Data",
  "",
  "The 2023 American Community Survey five year estimates provide census tract level demographic data. Tracts were classified as majority white, majority Black, majority Latino, or mixed/other based on the plurality racial/ethnic group. Median household income at the tract level was used for income stratification into quintiles.",
  "",
  "### 3.3 Parcel to Tract Matching",
  "",
  "Each appeal was matched to the property's 2020 census tract using the Illinois Department of Revenue parcel to tract crosswalk (Illinois Department of Revenue 2023) and, where the crosswalk was ambiguous, a direct point in polygon match against the Census TIGER/Line shapefiles. Matching succeeded for 99.1 percent of appeals. The remaining 0.9 percent were excluded from the analysis.",
  "",
  "## 4. Methods",
  "",
  "Three tract level metrics were computed.",
  "",
  "1. Filing rate: appeals filed per 1,000 residential parcels, averaged across the ten year window.",
  "2. Success rate: percentage of filed appeals resulting in any reduction in assessed value.",
  "3. Reduction magnitude: median percentage reduction in assessed value, conditional on a successful appeal.",
  "",
  "Each metric was cross tabulated against tract racial composition and median household income quintile. Significance tests use the tract as the unit of analysis, with standard errors clustered at the township level (the administrative unit above census tract and below county in the Cook County assessment system).",
  "",
  "The combined effect on expected annual assessment reduction was computed by multiplying the three metrics at the tract level.",
  "",
  "A subsidiary analysis used filer identity to examine the role of specialized law firms. Filers were classified as (a) specialized firm (among the top twenty law firms by appeal volume), (b) homeowner pro se, or (c) other representative (general practice attorneys, accountants, notaries).",
  "",
  "## 5. Findings",
  "",
  "### 5.1 Filing Rate",
  "",
  "The ten-year Cook County appeal record contains 1,741,823 filings across 2,144,000 residential parcels, an overall filing rate of roughly 81 per 1,000 parcels per year. Disaggregated by tract racial composition the rate is uneven: majority-white tracts file at 93 per 1,000 parcels per year; majority-Latino tracts at 51; mixed or other tracts at 68; and majority-Black tracts at 39. The majority-white to majority-Black ratio is 2.4. That gap is not a function of any single year's anomaly; it is present in every year of the 2015–2024 panel, with the year-to-year variation in the ratio staying inside a band of 2.2 to 2.6.",
  "",
  "```chart",
  "{",
  '  "type": "bar",',
  '  "title": "Property tax appeal filing rate by tract racial composition",',
  '  "caption": "Appeals filed per 1,000 residential parcels per year, 2015 through 2024 average. Source: Cook County Assessor and Cook County Board of Review administrative records, released under the Illinois FOIA.",',
  '  "x": ["Majority white", "Majority Black", "Majority Latino", "Mixed or other"],',
  '  "series": [',
  '    {"name": "Filings per 1,000 parcels", "data": [93, 39, 51, 68]}',
  "  ]",
  "}",
  "```",
  "",
  "### 5.2 Success Rate",
  "",
  "The fraction of filed appeals that produce any reduction in assessed value, the simplest measure of success, and the measure least subject to discretion in how one defines 'success', stands at 72 percent for majority-white tracts, 40 percent for majority-Black tracts, 48 percent for majority-Latino tracts, and 58 percent for mixed or other tracts. The majority-white to majority-Black ratio is 1.8. The gap is narrowest when both sides are filing through specialized representation (majority-white tracts: 78 percent via specialized firms; majority-Black tracts: 65 percent via specialized firms — a 1.2× ratio) and widest when the filing is pro se (majority-white tracts: 44 percent pro se success; majority-Black tracts: 22 percent — a 2.0× ratio). The specialized-representation channel closes part of the disparity; pro se filing does not.",
  "",
  "### 5.3 Reduction Magnitude",
  "",
  "Among the appeals that do produce a reduction, the median reduction in assessed value is 9.2 percent in majority-white tracts, 6.8 percent in majority-Black tracts, 7.1 percent in majority-Latino tracts, and 8.0 percent in mixed or other tracts. This third-stage disparity is smaller than the filing-rate or success-rate disparities, but it compounds with them: a majority-white-tract homeowner who files, succeeds, and secures the median reduction realizes a 9.2-percent cut, while the majority-Black-tract counterpart realizes a 6.8-percent cut — a 35-percent gap at the final stage that sits on top of the earlier-stage gaps rather than substituting for them.",
  "",
  "### 5.4 Compounded Expected Reduction",
  "",
  "Multiplying the three metrics gives the expected annual assessment reduction per parcel:",
  "",
  "- Majority white tracts: 0.093 x 0.72 x 0.092 = 0.616 percent of assessed value per year.",
  "- Majority Black tracts: 0.039 x 0.40 x 0.068 = 0.106 percent.",
  "- Majority Latino tracts: 0.051 x 0.48 x 0.071 = 0.174 percent.",
  "",
  "```chart",
  "{",
  '  "type": "bar",',
  '  "title": "Expected annual assessment reduction through appeals, by tract",',
  '  "caption": "Filing rate times success rate times reduction magnitude, expressed as expected annual reduction of assessed value. The compounded gap over ten years is approximately 5.8 times between majority white and majority Black tracts.",',
  '  "unit": "%",',
  '  "x": ["Majority white", "Majority Latino", "Majority Black"],',
  '  "series": [',
  '    {"name": "Annual reduction", "data": [0.616, 0.174, 0.106]}',
  "  ]",
  "}",
  "```",
  "",
  "Over a decade, homeowners in majority white tracts reduce cumulative assessed value through appeals by approximately 6.2 percent. Homeowners in majority Black tracts reduce theirs by approximately 1.1 percent. Applied to a median Cook County tax bill, the difference over a decade is on the order of two to four thousand dollars per homeowner.",
  "",
  "### 5.5 Income Stratification",
  "",
  "Within the top quintile of median household income, filing rates remain racially differentiated: 108 per 1,000 in majority white tracts, 64 per 1,000 in majority Black tracts (ratio 1.7). Success rates are also racially differentiated: 76 percent in majority white tracts, 52 percent in majority Black tracts (ratio 1.5).",
  "",
  "Within the bottom quintile, the ratios are similar. Income partially explains the racial disparity but does not explain it fully. What remains after income stratification is most plausibly explained by differential access to the institutional infrastructure of appeal professionals, which is examined in Section 5.6.",
  "",
  "### 5.6 Filer Identity",
  "",
  "Share of appeals filed by specialized firms, homeowners pro se, and others, by tract racial composition:",
  "",
  "| Tract type         | Specialized firm | Pro se | Other |",
  "|-------------------|------------------|--------|-------|",
  "| Majority white    | 78 percent       | 9%     | 13%   |",
  "| Majority Black    | 31 percent       | 24%    | 45%   |",
  "| Majority Latino   | 44 percent       | 18%    | 38%   |",
  "| Mixed or other    | 58 percent       | 14%    | 28%   |",
  "",
  "Specialized firm success rates are consistently higher than pro se or general practice success rates within any tract type. The compounding of filing rate differences (majority white tracts use specialized firms more often) and success rate differences within filer type (specialized firms succeed more often) accounts for a substantial share of the overall racial disparity in appeal outcomes.",
  "",
  "## 6. Discussion",
  "",
  "The findings replicate and extend Avenancio-León and Howard (2022). The pattern we document is consistent with their theoretical mechanism: a facially race-neutral appeal system produces racially disparate outcomes through differential access to the institutional infrastructure the system runs on. The Cook County administrative data — because it contains the full filer-identity field, which the AHM nationwide panel does not — allows a more detailed examination of the specialized-firm channel than has previously been possible in any published treatment of the appeals disparity.",
  "",
  "Three observations warrant separate comment.",
  "",
  "The first is that the disparity we document is not primarily a function of individual-homeowner choice. Homeowners in majority-Black tracts face the same formal appeal procedures as homeowners in majority-white tracts; the difference is not a difference in what the system asks of them but a difference in the distribution of the professional infrastructure the system runs on. Specialized firms cluster their client base in neighborhoods where their fee structures, typically contingency-based, 30–40 percent of the realized tax savings — are sustainable. The sustainability is a function of the baseline tax bill (higher in higher-assessed-value neighborhoods), the likelihood of success (higher where the firms have standing professional relationships with assessment staff), and the volume of appealable parcels per square mile. Once the clustering pattern is established, it reinforces itself: the firms' standing relationships raise their success rates, which attracts further clients, which consolidates the clustering. The feedback loop is not anything the firms deliberately engineered; it is a property of the market structure. But its consequence is that the facially-neutral appeal system becomes, in practice, a mechanism through which the tax burden is differentially reduced for homeowners who happen to live in neighborhoods where specialized representation is sustainable.",
  "",
  "The second observation is that the income-stratification results matter for policy design. A reform that subsidized appeal filings for low-income homeowners — a natural first-move intervention, implemented in abbreviated form in Cook County's 2020 low-income homeowner outreach program (Cook County Assessor 2020), would address a portion of the gap but would not address the specialized-firm clustering pattern. The race-based gap persists within income quintiles, with the top quintile itself showing a 1.7× filing-rate ratio and a 1.5× success-rate ratio between majority-white and majority-Black tracts. Reforms that target income without addressing the representation-infrastructure pattern will, by the arithmetic of our data, close less than half of the observed disparity.",
  "",
  "The third observation is that the pattern we document is observable and correctable through administrative reform. Several Illinois counties outside Cook have adopted proactive-reassessment procedures that identify over-assessed parcels through statistical review and reduce values without requiring a filing — Lake County's 2017 program (Lake County Assessor 2022, reviewing the five-year implementation record), DuPage County's 2019 program (DuPage County Assessor 2023), and more recently Kane County's 2022 pilot (Kane County Assessor 2024). The procedures eliminate the filing-rate dimension of the disparity by removing the filing requirement for systematically over-assessed parcels. They do not eliminate the representation-infrastructure pattern — specialized firms remain active for the parcels that proactive reassessment does not identify, but they substantially reduce the disparity's magnitude. Lake County's five-year review reports a 62 percent reduction in the race-based assessment-reduction gap over the program's implementation period.",
  "",
  "## 7. Policy Implications",
  "",
  "Four policy instruments are supported by the findings.",
  "",
  "First, pro active reassessment. The Cook County Assessor could identify over assessed parcels through statistical review and reduce their assessed values without requiring an appeal, following the model adopted in Lake and DuPage counties.",
  "",
  "Second, publicly funded appeal assistance. A property tax clinic, operated at community colleges or legal aid organizations, could provide free or low cost appeal assistance in majority Black and majority Latino community areas. The clinic model has been successfully adopted in Detroit (Detroit Property Tax Appeal Clinic 2020) and New Orleans.",
  "",
  "Third, simplified pro se procedures. The appeal process could be simplified to reduce the professional infrastructure advantage. Reforms would include standardized comparable property databases, simplified forms, and pre populated documentation.",
  "",
  "Fourth, data transparency. The full appeal record should be published annually in a machine readable format, with demographic cross tabulations, as a standing public accountability mechanism. This recommendation was made in the 2019 Cook County Assessor equity audit (Cook County Assessor 2019) and has been partially but not fully implemented.",
  "",
  "## 8. Limitations",
  "",
  "The dataset is a full population administrative record. Within the Cook County context, it is not a sample. The limitations of the analysis are therefore primarily limitations of what the administrative data captures rather than limitations of sampling.",
  "",
  "First, the dataset does not include demographic data at the individual filer level. Individual level race is inferred from tract level composition, which introduces ecological inference error for households that differ demographically from their tract.",
  "",
  "Second, the dataset does not distinguish between appeals filed by the homeowner's agent with authorization and appeals filed by a third party without homeowner knowledge. The distinction matters for interpreting the filer identity analysis but is not available in the administrative record.",
  "",
  "Third, the analysis is confined to Cook County. Generalization to other jurisdictions is supported by the consistency with Avenancio-León and Howard (2022) nationwide results but would benefit from comparable analyses in additional counties.",
  "",
  "## 9. Conclusion",
  "",
  "The Cook County property tax appeal record from 2015 through 2024 documents a substantial and persistent racial disparity in appeal filing, success, and reduction magnitude. The compounded effect over a decade is approximately 5.8 times higher for homeowners in majority white tracts than for homeowners in majority Black tracts. The disparity is only partially explained by income and is primarily explained by differential access to the specialized professional infrastructure of property tax appeal representation. The findings are consistent with Avenancio-León and Howard (2022) and support administrative reforms that would reduce the role of appeal filing in producing the overall racial assessment gap.",
  "",
  "## Data Availability",
  "",
  "The cleaned dataset and the code used to produce the analyses and figures are distributed on request. See [rooted-forward.org/research/data](https://rooted-forward.org/research/data#cook-county-property-tax-appeal-disparity) for the file list and licensing. Code is released under MIT; derived data under CC BY 4.0.",
  "",
  "## References",
  "",
  "Atuahene, B. and Berry, C. (2019). Taxed out: Illegal property tax assessments and the epidemic of tax foreclosures in Detroit. *UC Irvine Law Review*, 9(4), 847 through 886.",
  "",
  "Avenancio-León, C. F. and Howard, T. (2022). The assessment gap: Racial inequalities in property taxation. *Quarterly Journal of Economics*, 137(3), 1383 through 1434.",
  "",
  "Berry, B. J. L. and Bednarz, R. S. (1975). A hedonic model of prices and assessments for single family homes: Does the assessor follow the market or the market follow the assessor? *Land Economics*, 51(1), 21 through 40.",
  "",
  "Berry, C. (2018). Reassessing the property tax. Working paper, University of Chicago Harris School of Public Policy.",
  "",
  "Cheng, E., Glaeser, E. L., Loberg, M., and Yoonhee, L. (2021). Appealing to equity: The role of property tax appeals in assessment outcomes. NBER Working Paper 29274.",
  "",
  "Chicago Tribune (2017). *The Tax Divide: Investigation of Cook County Property Tax Inequity*. Multi part investigative series.",
  "",
  "Cook County Assessor (2019). *Residential Property Assessment Equity Audit*. Chicago.",
  "",
  "Cook County Assessor (2024). *Implementation Report on 2019 Equity Audit Recommendations*. Chicago.",
  "",
  "Detroit Property Tax Appeal Clinic (2020). *Annual Report, 2020*. Detroit.",
  "",
  "DuPage County Assessor (2023). *Pro Active Reassessment Program: Annual Report*. Wheaton IL.",
  "",
  "Harris, A. D. (2021). Racial inequity in property taxation: A review. *Housing Policy Debate*, 31(5), 785 through 806.",
  "",
  "Illinois Department of Revenue (2023). *Parcel to Census Tract Crosswalk, 2023 Update*. Springfield IL.",
  "",
  "Kriticos, S. (2020). Specialized representation in property tax appeals: Evidence from six large US counties. *Public Finance Review*, 48(5), 603 through 632.",
  "",
  "Lake County Assessor (2022). *Pro Active Reassessment Program: Five Year Review*. Waukegan IL.",
  "",
  "Lincoln Institute of Land Policy (2023). *50 State Property Tax Comparison Study*. Cambridge MA.",
  "",
  "Sands, G. (2019). *The Property Tax Under Siege: Regressivity, Equity, and the Assessment Ratio*. Boca Raton FL: CRC Press.",
].join("\n");
