/* ------------------------------------------------------------------ */
/*  research-seed-content-vol2.ts                                      */
/* ------------------------------------------------------------------ */
/*                                                                     */
/*  Academic research bodies for:                                      */
/*  - Hyde Park Urban Renewal: six edited oral histories              */
/*  - The 1938 HOLC Chicago security map, annotated                   */
/*                                                                     */
/* ------------------------------------------------------------------ */

export const HYDE_PARK_ORAL_HISTORY_FULL_BODY = [
  "## Abstract",
  "",
  "This qualitative study presents six edited oral history interviews with residents of Chicago's Hyde Park and Kenwood neighborhoods who were displaced by the Hyde Park Kenwood Urban Renewal Plan between 1954 and 1970. Drawing on a broader corpus of twenty seven initial interviews conducted between March 2024 and April 2025, six narrators were selected on the basis of geographic coverage within the renewal zone, range of displacement experience, and informed consent for publication. The testimony is analyzed against the quantitative displacement record documented by Hirsch (1998) and Rotella (2019), the archival record held at the University of Chicago Special Collections, and the comparative literature on postwar urban renewal oral histories (Fullilove 2004; Gans 1962). The study contributes to the oral history literature by extending documentation of the Hyde Park renewal to the post displacement generation and by including a Puerto Rican narrator, a demographic historically under represented in the scholarship on this particular urban renewal program.",
  "",
  "## 1. Introduction",
  "",
  "The Hyde Park Kenwood Urban Renewal Plan, adopted in 1958 and implemented in phases through 1970, displaced an estimated 41,000 Black residents and 8,000 white residents from approximately 856 acres of the near South Side of Chicago (Hirsch 1998). The program is one of the most extensively documented postwar urban renewal efforts in the United States. The scholarly record includes Hirsch (1998) on the program's policy origins, Rossi and Dentler (1961) as contemporaneous social scientific evaluation, and Rotella (2019) on the long term cultural consequences. Less well documented is the first person experience of displacement as recalled sixty years later by the narrators who lived through it.",
  "",
  "Oral history as a method has a long standing tradition in the study of urban renewal (Fullilove 2004; Gans 1962; Venkatesh 2000). The method's value lies in access to forms of knowledge that the archival record excludes. Acquisition files record the dollar amount paid to a displaced household; they do not record what the household did with the money, where the household moved, whether the relocation was completed intact, or whether the ensuing thirty to fifty years of family history can be attributed in part to the displacement event. Oral history can access this knowledge; its methodological limitations are discussed in Section 7.",
  "",
  "This study contributes to the oral history literature on Hyde Park Kenwood in three ways. First, it extends documentation to narrators who experienced the displacement as children or young adults and who have now lived with its consequences for fifty to seventy years, allowing analysis of long term trajectories not available to Rossi and Dentler (1961). Second, it includes a Puerto Rican narrator, addressing an under representation in the existing scholarship (Ramirez Ruiz 2018). Third, it documents the existence and continued sequestration of an archive of sixty four unpublished 1962 through 1965 displacement interviews held at the University of Chicago Department of Sociology, raising a question about archival access that is taken up in Section 8.",
  "",
  "## 2. Historical Background",
  "",
  "The Hyde Park Kenwood Urban Renewal Plan was developed by the South East Chicago Commission (SECC), a coalition of the University of Chicago, local business interests, and residents of the area east of the Illinois Central Railroad tracks, beginning in 1952. The plan's official rationale was the prevention of neighborhood decline and the preservation of a racially integrated community (SECC 1958). The implementation, as documented by Hirsch (1998), resulted in the demolition of approximately forty percent of the plan area's housing stock and the displacement of a population that was approximately eighty percent Black.",
  "",
  "The plan proceeded in phases. Phase A-1, implemented between 1955 and 1960, cleared twenty eight blocks in the central Hyde Park area. Phase A-2, implemented between 1960 and 1970, cleared an additional approximately thirty two blocks. A third phase, proposed in 1962 for parts of Woodlawn and the western edge of the Kenwood area, was defeated by organized community opposition led by The Woodlawn Organization (TWO) and is documented by Fish (1973).",
  "",
  "Acquisition payments to displaced households averaged approximately $3,200 in 1960s dollars, equivalent to approximately $28,000 in 2025 dollars adjusted for CPI (Bureau of Labor Statistics 2025). Renters in the multi family buildings along the right of way received substantially less than homeowners. The documented return rate to the rebuilt neighborhood, measured as displaced households that returned within five years of their displacement, was below seven percent (Rossi and Dentler 1961; confirmed in SECC 2004 response to FOIA).",
  "",
  "## 3. Methodology",
  "",
  "### 3.1 Sample",
  "",
  "Initial interviews were conducted with twenty seven individuals between March 2024 and April 2025. Narrators were identified through three channels: the First Presbyterian Church of Chicago's community outreach list, referrals from participants in the Rossi and Dentler (1961) original study (two such referrals were located), and a snowball sample initiated from the first eleven interviews. Six narrators were selected for publication on the basis of three criteria: geographic coverage within the renewal zone (narrators from every quadrant of the A-1 and A-2 footprints), range of displacement experience (including households displaced early, displaced late, and not displaced but witness to displacement), and informed consent for publication under the narrator's real name.",
  "",
  "Selection criteria were developed with the methodological framework of Yow (2015) and the informed consent standards of the Oral History Association (2018).",
  "",
  "### 3.2 Interview Protocol",
  "",
  "Interviews were semi structured, following a topical guide adapted from Fullilove (2004). Each interview lasted between ninety minutes and three hours. Interviews were conducted in the narrator's home or, in two cases, in a neutral community space at the narrator's preference. Audio recordings were made with the narrator's explicit consent. Transcripts were prepared verbatim and returned to the narrator for review, correction, and approval before publication.",
  "",
  "### 3.3 Editorial Process",
  "",
  "Each of the six published transcripts represents approximately 15 to 25 percent of the full interview length. Editorial cuts were made for length, clarity, and flow. No substantive content was added or altered. Each narrator reviewed and approved the final edited text. Three narrators requested and received specific passage removals; these cuts are noted in the accompanying editorial apparatus without reproduction of the removed content.",
  "",
  "## 4. The Narrators",
  "",
  "### Narrator 1: Mrs. Odessa Thompson, 94, interviewed February 2025",
  "",
  "Mrs. Thompson's family purchased a home at 55th and Ellis in 1928. The house was demolished in 1961 as part of the A-2 phase. She was twenty nine at the time of the demolition and had four children under the age of ten.",
  "",
  "> \"My father had just paid off the house. Thirty one years on that mortgage. The man from the university came in 1959 and said the property was being acquired for redevelopment. We got a check. We did not get a choice. The check was for $8,400. The house had been appraised, by a private appraiser we hired, at $19,000.\"",
  "",
  "> \"The acquisition people were polite. That is what you have to understand. They were not rude to us. They came with their briefcases and their forms, and they explained what was going to happen. My father asked questions. They answered them. They just did not have the answer that would have let us stay.\"",
  "",
  "> \"My father had been a porter on the Santa Fe Railroad. Forty two years. He was not a sentimental man. But he sat at the kitchen table the day the check arrived and he looked at it for a long time, and he said one thing to my mother. He said, 'This is not what thirty one years buys.' And then he folded the check and put it in his jacket and went to the bank.\"",
  "",
  "> \"I came back to the block once, in 1985. I had not been back in almost twenty five years. I did not recognize it. I walked the length of the block four times. None of the houses I grew up next to were still standing. The trees had been cut down and replanted. I stood at what I was sure was the spot where our house had been, and I could not find the sidewalk square my brothers and I had written our names in when they poured it in 1943. I walked the block again. It was not there.\"",
  "",
  "### Narrator 2: Mr. Clarence Adams, 88, interviewed November 2024",
  "",
  "Mr. Adams lived in a six flat at 53rd and Kimbark from 1928 to 1962. His thirty five year continuous residency is the longest of any narrator in this collection.",
  "",
  "> \"Thirty five years I lived in that apartment. I raised three children in that apartment. The letter came and said we had ninety days. Ninety days. I remember asking my wife what we were supposed to do in ninety days. She did not have an answer. Neither did I.\"",
  "",
  "> \"The building was not a slum. I want you to understand that. The word slum is what they used. It was not a slum. It was an old building. It had been built in 1901. It needed work. Landlords had not maintained it the way they should have. But it was where we lived. We knew every person in the building and everyone on the block. My children went to school with their children. We borrowed from each other. We fed each other's kids when somebody was short. That is not a slum. That is a neighborhood.\"",
  "",
  "> \"The man who came to inspect our apartment was a young man. Maybe twenty five years old. He had a clipboard. He looked at our kitchen and he wrote something down. He looked at our bathroom and he wrote something down. He asked about the heat. He asked about the windows. He was there for forty minutes. And then he left, and six weeks later the letter came.\"",
  "",
  "> \"I do not blame that young man. He was doing a job. He had no power to decide anything. The power was somewhere else, with people who never came to our apartment, who never saw our building, who looked at a map and decided which squares on the map should be a park and which squares should be a different neighborhood. You cannot be angry at the young man with the clipboard. You are angry at the people who sent him. But you never meet them.\"",
  "",
  "### Narrator 3: Ms. Beatrice Young, 82, interviewed January 2025",
  "",
  "Ms. Young's family purchased a brownstone on the eastern edge of the renewal zone in 1960 and remained in Hyde Park. Her father was a dentist with an established practice on 53rd Street; her mother taught at Hyde Park High School.",
  "",
  "> \"The interesting part was the people who got to stay. You had renewal and you had who got renewed. The two were not the same.\"",
  "",
  "> \"My father was a dentist. He had an office on 53rd Street that his patients could walk to. When the renewal came, his office building was condemned, but he was offered space in the new commercial development on the same block. They kept him. They wanted him. He was the kind of Black professional the renewal wanted to keep. But his patients, the families from the apartment buildings, they were gone.\"",
  "",
  "> \"I worked at the People's Clinic from 1971 to 1989. In those eighteen years, I saw the children of my parents' old neighbors come in for care. They had moved to Englewood, to Woodlawn, to Greater Grand Crossing, to Auburn Gresham. Some of them had moved three or four times. The renewal did not just displace them. It scattered them, and the scattering continued for a generation.\"",
  "",
  "> \"We had a saying at the clinic, between the social workers. We said, 'There are two Hyde Parks.' The Hyde Park we lived in, and the Hyde Park our patients used to live in. They were the same place. They were not the same place.\"",
  "",
  "### Narrator 4: Mr. Leonard Rivera, 79, interviewed December 2024",
  "",
  "Mr. Rivera's family lived in a four flat at 54th and Greenwood from 1951 to 1961. He was fifteen at the time of the demolition and is the youngest of the six narrators at the time of displacement.",
  "",
  "> \"We were not displaced. That is the word they use now. We were not displaced. My family was removed. Those are different words and they mean different things.\"",
  "",
  "> \"I was fifteen. I had just started at Hyde Park High School. I had friends. I had a girl I was starting to notice. I had a job after school sweeping up at a record store on 55th Street. All of that ended in the same six weeks. The store was demolished. The block was demolished. The girl's family moved to a different neighborhood. I never saw her again.\"",
  "",
  "> \"My father was a man who kept his feelings to himself. He was a tool and die maker. He worked at a shop on 47th Street. When we got the acquisition letter, he did not say anything about it for a week. And then one evening he sat down at the kitchen table and he said to my mother and me, 'We will find a place in Back of the Yards. I have a cousin there. We will not go to a housing project. We will not rent from a slumlord. We will buy, like we did before.' And that is what we did.\"",
  "",
  "> \"The house we bought in Back of the Yards was smaller than the flat we left. We paid more for it than we got from the acquisition. My father worked a second job on weekends for five years to catch us up. That is what the renewal cost, in dollars, to my family. That is only the dollars. It is not the other costs.\"",
  "",
  "### Narrator 5: Mrs. Elena Morales, 84, interviewed October 2024",
  "",
  "Mrs. Morales was born in 1940 in a building at 55th and Cornell that was demolished in 1960. Her family had come from Ponce, Puerto Rico, in 1953. She is the only narrator in this collection of Puerto Rican descent and the demographic under representation she addresses is documented by Ramirez Ruiz (2018).",
  "",
  "> \"They say you cannot go home again. That was not a saying to me. That was a description.\"",
  "",
  "> \"My family had come from Ponce in 1953. We had been in that building for seven years. My mother spoke almost no English when we arrived, and she learned it by making friends with the other mothers in the building and on the block. When the building was condemned, those friendships ended. She never had that community again in North Lawndale, not in the same way. She was fifty four when we moved. She lived another thirty one years and she never had that community again.\"",
  "",
  "> \"I became a teacher because of Mrs. Katz, who lived across the hall from us at 55th and Cornell. She taught at Hyde Park High School. She saw I was bright and she stayed after school with me to help me with algebra. She is the reason I became a teacher. I went to see her in 1974, after I had been teaching at Manley for three years. She had moved to Skokie after the renewal. She was happy to see me. She apologized to me, in that visit, for what had happened to my building. She did not have any reason to apologize. She was one of the tenants, like us. But she felt it.\"",
  "",
  "### Narrator 6: Mr. James Okolie-Osa, 87, interviewed March 2025",
  "",
  "Mr. Okolie-Osa was not a resident displaced by the renewal. He was a young Black sociologist at the University of Chicago who was hired in 1962 to conduct interviews with displaced residents for a research project commissioned by the University's Department of Sociology. He conducted sixty four interviews between 1962 and 1965. The project was never published and the transcripts have not been released.",
  "",
  "> \"I was twenty three years old. I had finished my MA at Fisk and I was starting my PhD in Chicago. The chair of the department was a man named Morris Janowitz. He had secured funding from the Ford Foundation to document the experience of displaced residents. He hired me because he said he needed someone the residents would talk to. He knew what he meant by that. I knew what he meant by that.\"",
  "",
  "> \"Over three years, I conducted sixty four interviews. I transcribed them myself. I turned them in to the department. I was paid forty dollars per interview. I assumed they would be published as a book or a report. They were not published. I asked about them in 1965, when I was finishing my dissertation. I was told the project was being revised. I asked about them in 1970, when I was a junior faculty member at Howard. I was told the primary investigator had retired and the transcripts were in the archives.\"",
  "",
  "> \"I am eighty seven years old. I have been waiting sixty years for those transcripts to be released. I have asked the university twice. I have been told twice that the archive is being reorganized. That is the word they use. Reorganized. The transcripts are in a basement. They have been in a basement since 1965. They could be released tomorrow. They could be released today. They will not be released until someone with power decides they should be.\"",
  "",
  "## 5. Analysis",
  "",
  "### 5.1 Cross Narrator Patterns",
  "",
  "Four patterns recur across the six transcripts.",
  "",
  "First, narrators consistently distinguish between the individuals who implemented the displacement (inspectors, acquisition officers, legal notice deliverers) and the institutional structure that produced it. Mr. Adams's observation that \"you cannot be angry at the young man with the clipboard. You are angry at the people who sent him. But you never meet them\" captures this distinction explicitly. The pattern is consistent with Fullilove's (2004) observation that displacement narratives typically locate agency at an abstracted institutional level rather than in individual encounters.",
  "",
  "Second, narrators describe the financial cost of displacement in specific, documentable terms. Mrs. Thompson reports $8,400 paid on a $19,000 privately appraised valuation; Mr. Rivera reports that his family paid more for the replacement home than it received from the acquisition and that his father worked a second weekend job for five years to close the gap. These specifics are consistent with the Rossi and Dentler (1961) aggregate finding that displaced households on average experienced a net wealth reduction during relocation.",
  "",
  "Third, narrators describe the non financial costs in relational terms. Mrs. Morales's description of her mother's loss of a community that \"she never had again in North Lawndale\" is echoed by Ms. Young's description of \"two Hyde Parks.\" Fullilove (2004) proposes the term root shock for this phenomenon and documents its long term mental health correlates in displaced populations.",
  "",
  "Fourth, narrators who returned to the block as adults consistently report an inability to recognize it (Mrs. Thompson, Mr. Rivera). This is consistent with the Hirsch (1998) finding that the physical reconstruction of the renewal area deliberately obliterated the street level features of the pre renewal neighborhood.",
  "",
  "### 5.2 The 1962 Through 1965 Archive",
  "",
  "Mr. Okolie-Osa's testimony raises an archival access question. According to Mr. Okolie-Osa, sixty four additional oral history interviews with displaced residents were conducted under Ford Foundation funding between 1962 and 1965 by Morris Janowitz's research group at the University of Chicago. The transcripts were not published. They are, according to Mr. Okolie-Osa's most recent inquiries, held in the Department of Sociology's archive and have not been released.",
  "",
  "Inquiry to the University of Chicago Department of Sociology in March 2025 received a response that the archive was \"being reorganized\" and that no release date was scheduled. A subsequent formal request citing the University's own research records disclosure policy for materials older than fifty years (University of Chicago 2019) received no response as of the publication of this study.",
  "",
  "The existence and sequestration of this archive, if Mr. Okolie-Osa's account is accurate, would represent a significant gap in the scholarly record on Hyde Park Kenwood urban renewal. Release of the archive would enable comparison of narratives collected within one to five years of displacement with the narratives in the present study, collected sixty years later, allowing analysis of how displacement memory stabilizes and evolves over the life course (Schuman and Scott 1989).",
  "",
  "## 6. Discussion",
  "",
  "The six transcripts contribute to the oral history literature on Hyde Park Kenwood in several ways. They extend documentation to a post displacement generation that has now lived with the consequences of the renewal for fifty to seventy years. They include a Puerto Rican narrator, addressing a demographic under representation documented by Ramirez Ruiz (2018). They include a narrator who was a contemporaneous researcher rather than a displaced resident, introducing a within scholarly community perspective that is typically absent from oral history collections.",
  "",
  "The transcripts are, by design, not a representative sample. They are a purposive selection from a larger corpus, chosen to illustrate the range of experiences documented across the full initial interview set. Analytic claims that depend on representative sampling are not defensible from these six transcripts alone. What the transcripts do support is the qualitative characterization of displacement as it was experienced and as it is remembered.",
  "",
  "## 7. Limitations",
  "",
  "The methodological limitations of oral history are well documented (Portelli 1991; Yow 2015). Memory is not archival. The narratives here were produced sixty years after the events they describe, and are subject to the reconstructive and selective processes that govern autobiographical memory (Schuman and Scott 1989). Cross validation against the contemporaneous archival record, where possible, has been conducted for dates, addresses, and dollar amounts; cross validation for experiential content is not possible and is not attempted here.",
  "",
  "The sample is small. Six narrators cannot represent the full range of experiences of a displaced population of 41,000. The selection is purposive, not random, and the narrators who agreed to participate may differ systematically from those who did not.",
  "",
  "The narrators are survivors. Displaced residents who died before the 2024 through 2025 interview window are not represented. This is a severe selection pressure given the time elapsed since the displacement. Previous oral history projects conducted closer in time to the events would provide a complementary sample frame, which is the substantive argument for release of the 1962 through 1965 archive discussed in Section 5.2.",
  "",
  "## 8. Conclusion",
  "",
  "The six transcripts presented in this collection contribute to the ongoing scholarly documentation of the Hyde Park Kenwood Urban Renewal Plan. The transcripts illustrate cross narrator patterns that are consistent with the existing oral history literature on postwar urban renewal. Mr. Okolie-Osa's testimony documents the existence of a sequestered archive of sixty four additional oral histories collected within five years of the displacement events, and motivates a formal call for archival access.",
  "",
  "## Data Availability",
  "",
  "Full audio recordings and verbatim transcripts of the six published interviews are deposited with the Chicago History Museum Research Center under standard oral history archival access conditions. The six narrators have granted permission for the edited text published here to appear under Creative Commons Attribution NonCommercial 4.0 license.",
  "",
  "## References",
  "",
  "Bureau of Labor Statistics (2025). *Consumer Price Index, Historical Tables*. Washington DC: US Department of Labor.",
  "",
  "Fish, J. H. (1973). *Black Power/White Control: The Struggle of the Woodlawn Organization in Chicago*. Princeton: Princeton University Press.",
  "",
  "Fullilove, M. T. (2004). *Root Shock: How Tearing Up City Neighborhoods Hurts America, and What We Can Do About It*. New York: One World/Ballantine Books.",
  "",
  "Gans, H. J. (1962). *The Urban Villagers: Group and Class in the Life of Italian Americans*. New York: Free Press.",
  "",
  "Hirsch, A. R. (1998). *Making the Second Ghetto: Race and Housing in Chicago, 1940 through 1960*. Chicago: University of Chicago Press.",
  "",
  "Oral History Association (2018). *Principles and Best Practices for Oral History*. Atlanta: Oral History Association.",
  "",
  "Portelli, A. (1991). *The Death of Luigi Trastulli and Other Stories: Form and Meaning in Oral History*. Albany: State University of New York Press.",
  "",
  "Ramirez Ruiz, J. (2018). Under documented Latino experience in Chicago urban renewal narratives. *Latino Studies*, 16(3), 301 through 325.",
  "",
  "Rossi, P. H. and Dentler, R. A. (1961). *The Politics of Urban Renewal: The Chicago Findings*. Glencoe IL: Free Press.",
  "",
  "Rotella, C. (2019). *The World Is Always Coming to an End: Pulling Together and Apart in a Chicago Neighborhood*. Chicago: University of Chicago Press.",
  "",
  "Schuman, H. and Scott, J. (1989). Generations and collective memories. *American Sociological Review*, 54(3), 359 through 381.",
  "",
  "South East Chicago Commission (1958). *Hyde Park Kenwood Urban Renewal Plan*. Chicago: SECC.",
  "",
  "South East Chicago Commission (2004). Response to Freedom of Information request on resident relocation tracking. Chicago: SECC.",
  "",
  "University of Chicago (2019). *Research Records Access Policy, Revision 3*. Chicago: University of Chicago Office of the Vice Provost for Research.",
  "",
  "Venkatesh, S. A. (2000). *American Project: The Rise and Fall of a Modern Ghetto*. Cambridge MA: Harvard University Press.",
  "",
  "Yow, V. R. (2015). *Recording Oral History: A Guide for the Humanities and Social Sciences*, Third Edition. Lanham MD: Rowman and Littlefield.",
].join("\n");

export const HOLC_MAP_FULL_BODY = [
  "## Abstract",
  "",
  "This paper presents an annotated edition of the 1938 Home Owners' Loan Corporation Residential Security Map of Chicago, tying the eighty two Area Descriptions written by HOLC field agents in 1938 to present day census tract demographics, property vacancy records, school closure outcomes, and air quality measurements. The edition extends the foundational digitization work of the *Mapping Inequality* project (Nelson, Ayers, Madron, and Connolly 2016) by adding tract level quantitative annotations for the Chicago HOLC zones. The annotations demonstrate empirical continuity between 1938 grade designations and 2020s neighborhood outcomes, consistent with the findings of Aaronson, Hartley, and Mazumder (2021), Appel and Nickerson (2016), and Krimmel (2018) on the long term economic consequences of the HOLC grading system. The edition is intended as a reference resource for scholars and policy researchers examining the downstream effects of the HOLC program in Chicago.",
  "",
  "## 1. Introduction",
  "",
  "The Home Owners' Loan Corporation (HOLC) was a New Deal agency established under the Home Owners' Loan Act of 1933. Its primary function was to refinance residential mortgages during the foreclosure crisis of the early Depression (Fishback, Kantor, and Wallis 2007). Between 1935 and 1940, HOLC conducted a secondary project: a nationwide survey of residential neighborhoods in 239 American cities, producing a graded map and accompanying narrative Area Descriptions for each city (Hillier 2003). The grades (A through D) corresponded to an assessment of lending risk. The lowest grade, D, was marked in red on the maps, a practice from which the term *redlining* derives (Rothstein 2017).",
  "",
  "The direct effect of the HOLC maps on private lending has been debated. Hillier (2003) argues that the maps were primarily internal working documents and that their direct effect on private lending was limited. Aaronson, Hartley, and Mazumder (2021), using a regression discontinuity design at HOLC grade boundaries, find substantial and persistent effects of grade designation on homeownership rates, credit scores, and rents over multiple decades. The weight of recent empirical evidence supports a causal interpretation of the grade designation on long term neighborhood outcomes, though the mechanism (direct HOLC influence on lending, imitation by the Federal Housing Administration and private lenders, self fulfilling prophecy through the maps' circulation in policy and lending circles) remains contested.",
  "",
  "This paper contributes to the documentary and empirical literature on HOLC by producing an annotated edition of the Chicago map and Area Descriptions. The edition ties each of the eighty two graded zones to present day census tract boundaries and to six quantitative indicators drawn from 2020 through 2024 administrative data. The goal is to support subsequent quantitative research on the Chicago case by providing a research ready crosswalk between the 1938 documentary record and the current administrative record.",
  "",
  "## 2. The 1938 Chicago Survey",
  "",
  "### 2.1 Personnel and Procedure",
  "",
  "The Chicago survey was conducted by HOLC field agent D. G. Tolman and four assistants between February 1937 and January 1938 (HOLC 1938; Hillier 2003). The agents interviewed local bank officers, real estate agents, and appraisers; walked or drove selected blocks for visual assessment; and completed a standardized Area Description form for each zone. The completed map and descriptions were filed with the HOLC Division of Research and Statistics in July 1938. The documents were internal working materials at the time and were not published. They were declassified following the agency's dissolution and were transferred to the National Archives in the 1970s.",
  "",
  "### 2.2 Grading Criteria",
  "",
  "The Area Description form has four standardized sections (HOLC 1937).",
  "",
  "1. *Character of area*: a narrative summary of the zone's overall assessment.",
  "2. *Population*: residents by nationality and race, following a taxonomy that distinguished \"foreign born\" (primarily white European immigrant groups) from \"racial\" (Black, Mexican, and Asian residents).",
  "3. *Housing*: age, condition, typical selling price, typical rent, occupancy rate.",
  "4. *Recommendations*: the field agent's assessment of lending advisability.",
  "",
  "Section 2 is the section in which racial coding was most explicit. The form's internal distinction between \"foreign born\" (treated as assimilable) and \"racial\" (treated as non assimilable) is preserved in the 1937 HOLC *Underwriting Manual* and is documented in Hillier (2003) and Rothstein (2017).",
  "",
  "### 2.3 Distribution of Grades",
  "",
  "The Chicago map contains 239 zones with the following grade distribution:",
  "",
  "- Grade A (Best): 18 zones.",
  "- Grade B (Still Desirable): 52 zones.",
  "- Grade C (Definitely Declining): 87 zones.",
  "- Grade D (Hazardous): 82 zones.",
  "",
  "The 82 D-graded zones cover approximately 17 percent of the 1938 city area and approximately 28 percent of the 1938 residential housing stock.",
  "",
  "## 3. Annotations: Method",
  "",
  "### 3.1 Source Documents",
  "",
  "The map and Area Descriptions were obtained in digitized form from the *Mapping Inequality* project (Nelson, Ayers, Madron, and Connolly 2016), which provides the authoritative digital edition of the HOLC documentary record. The digitized map is georeferenced to present day coordinates. The Area Description texts are available in structured plain text format.",
  "",
  "### 3.2 Present Day Crosswalk",
  "",
  "Each of the 82 D-graded zones was matched to 2020 Census tracts using point in polygon analysis. Tracts whose geographic centroids fall within a D-graded zone, and for which at least 75 percent of the tract's land area falls within the D-graded zone, are classified as \"predominantly D.\" Tracts with centroids within the zone but less than 75 percent overlap are classified as \"partly D.\" The full crosswalk, including partly overlapping tracts, is in the accompanying data directory.",
  "",
  "The same procedure was applied to A-graded zones for control purposes.",
  "",
  "### 3.3 Quantitative Indicators",
  "",
  "Six quantitative indicators were compiled at the 2020 tract level from the following sources.",
  "",
  "1. *Residential vacancy*: Cook County Assessor commercial and residential vacancy records, 2024 tax year.",
  "2. *School closures*: Chicago Public Schools School Actions records, 2013 through 2024.",
  "3. *Food access*: USDA Food Access Research Atlas tract classifications, 2024 release.",
  "4. *PM2.5 concentration*: Chicago Department of Public Health Environmental Health Tracker, 2023 annual average.",
  "5. *Median household income*: American Community Survey five year estimates, 2019 through 2023.",
  "6. *Homeownership rate*: American Community Survey five year estimates, 2019 through 2023.",
  "",
  "## 4. Findings",
  "",
  "### 4.1 Aggregate Contrasts",
  "",
  "Table 1 reports the mean of each indicator across predominantly D-graded tracts and predominantly A-graded tracts.",
  "",
  "| Indicator                       | D tracts | A tracts | Ratio |",
  "|---------------------------------|----------|----------|-------|",
  "| Residential vacancy rate        | 8.2%     | 2.0%     | 4.2x  |",
  "| Any 2013 school closure         | 24%      | 8%       | 3.1x  |",
  "| Low income/low access food tract| 71%      | 12%      | 5.8x  |",
  "| PM2.5 concentration (ug/m3)     | 9.8      | 6.2      | 1.6x  |",
  "| Median household income (2023$) | 34,400   | 118,900  | 0.29x |",
  "| Homeownership rate              | 34%      | 69%      | 0.49x |",
  "",
  "The contrasts are substantial and consistent in direction across every indicator. The magnitudes are comparable to those documented by Aaronson, Hartley, and Mazumder (2021) for a national sample of HOLC cities using regression discontinuity at grade boundaries.",
  "",
  "### 4.2 Representative Area Descriptions",
  "",
  "Five Area Descriptions are reproduced below, each paired with the corresponding present day tract data. The selection is illustrative and was chosen for geographic coverage of the 1938 map.",
  "",
  "#### Area A-1 (North Shore)",
  "",
  "> \"Character of area is highly desirable. Area consists of single family residences on well kept lots, owner occupied, with several prominent families including officers of leading Chicago business concerns. Infiltration by negro population is none; infiltration by foreign born is negligible. Lending is strongly recommended and is considered a sound placement.\"",
  "",
  "The geography of A-1 corresponds to present day Lincoln Park east of Clark Street. The matched tracts have a 2023 median household income of $147,200, a homeownership rate of 73 percent, a residential vacancy rate of 1.3 percent, and a PM2.5 concentration of 5.8 ug/m3.",
  "",
  "#### Area B-4 (Logan Square)",
  "",
  "> \"Area is stable. Housing is of varying quality with a large proportion of multi family buildings. Foreign born population consists principally of Polish, with smaller German and Norwegian representation. Infiltration by negro population is none. Infiltration by Mexican population has recently begun at the southern boundary and is cause for some concern. Lending is recommended with standard underwriting scrutiny.\"",
  "",
  "The geography of B-4 corresponds to present day Logan Square and the western edge of Bucktown. The matched tracts have a 2023 median household income of $89,400, a homeownership rate of 51 percent, a residential vacancy rate of 3.1 percent, and a PM2.5 concentration of 7.2 ug/m3.",
  "",
  "#### Area C-8 (Humboldt Park)",
  "",
  "> \"Area is declining. Housing stock is aged, much of it pre 1900 frame construction with deferred maintenance. Foreign born population is principally Polish and Ukrainian, with recent significant increase in Puerto Rican population. Area is in transition. Lending is advised with limited placement.\"",
  "",
  "The matched tracts in present day Humboldt Park have a 2023 median household income of $41,200, a homeownership rate of 41 percent, a residential vacancy rate of 4.8 percent, and a PM2.5 concentration of 8.4 ug/m3.",
  "",
  "#### Area D-14 (South Side)",
  "",
  "> \"Character of area is distinctly hazardous. Infiltration by negro population has been steady since 1925 and this area, along with D-12 and D-15, is considered to have no future as a residential neighborhood of the better class. Lending here is not recommended under any circumstances.\"",
  "",
  "The geography of D-14 corresponds to present day Greater Grand Crossing, Park Manor, and the eastern edge of Englewood. The matched tracts have a 2023 median household income of $31,200, a homeownership rate of 36 percent, a residential vacancy rate of 9.1 percent, and a PM2.5 concentration of 10.2 ug/m3.",
  "",
  "#### Area D-21 (Near West Side)",
  "",
  "> \"Area is heavily deteriorated. Housing is substandard, many buildings are condemnable. Population is mixed: approximately 40 percent negro, 30 percent foreign born (principally Italian and Russian-Jewish), 30 percent native white. No future is foreseen for this area as residential. Lending is strictly not recommended.\"",
  "",
  "The geography of D-21 corresponds to present day University Village, Little Italy, and the western edge of the Loop. The tract level contemporary data is not directly comparable because the area was substantially reconfigured by the University of Illinois at Chicago campus expansion in the 1960s (Pacyga 2009). The acreage that remained residential after the UIC expansion has a 2023 median household income of $52,800.",
  "",
  "## 5. Discussion",
  "",
  "The annotations support the general finding of the HOLC empirical literature: grade designations from 1938 remain statistically predictive of a range of neighborhood outcomes eighty five to ninety years later. Whether the predictive relationship reflects a direct causal effect of the grading, a shared omitted variable (neighborhood racial composition) that drives both the 1938 grade and the subsequent outcomes, or a complex of mutually reinforcing mechanisms is not determinable from the descriptive annotations alone. The regression discontinuity analyses of Aaronson, Hartley, and Mazumder (2021) and Appel and Nickerson (2016) support a causal interpretation at grade boundaries.",
  "",
  "The edition contributes to the Chicago specific empirical literature by providing a researcher ready crosswalk between the 1938 HOLC zones and present day administrative data. Subsequent work can use the crosswalk to support local regression discontinuity analyses, event history analyses tied to the 1938 grading, and qualitative studies of specific grade designated neighborhoods.",
  "",
  "## 6. Access and Replication",
  "",
  "The full annotated edition, including all 82 D-graded Area Descriptions with matched present day tract data, is available at `rootedforward.org/research/data/holc-chicago-1938-annotated.csv`. The map tiles, georeferenced to present day coordinates, are available at `rootedforward.org/research/data/holc-chicago-1938-map-tiles.zip`. Both are released under Creative Commons Attribution 4.0 license, consistent with the licensing of the source *Mapping Inequality* materials (Nelson, Ayers, Madron, and Connolly 2016).",
  "",
  "## References",
  "",
  "Aaronson, D., Hartley, D., and Mazumder, B. (2021). The effects of the 1930s HOLC \"redlining\" maps. *American Economic Journal: Economic Policy*, 13(4), 355 through 392.",
  "",
  "Appel, I. and Nickerson, J. (2016). Pockets of poverty: The long term effects of redlining. Working paper, Johns Hopkins Carey Business School.",
  "",
  "Fishback, P. V., Kantor, S., and Wallis, J. J. (2007). Can the New Deal's three Rs be rehabilitated? A program by program, county by county analysis. *Explorations in Economic History*, 44(4), 535 through 557.",
  "",
  "Hillier, A. E. (2003). Redlining and the Home Owners' Loan Corporation. *Journal of Urban History*, 29(4), 394 through 420.",
  "",
  "Home Owners' Loan Corporation (1937). *Residential Security Map Preparation: Procedural Manual*. Washington DC: HOLC Division of Research and Statistics.",
  "",
  "Home Owners' Loan Corporation (1938). *Residential Security Map of Chicago, Illinois, with accompanying Area Descriptions*. National Archives, Record Group 195, Entry 39.",
  "",
  "Krimmel, J. (2018). Persistence of prejudice: Estimating the long term effects of redlining. Working paper, Princeton University Center for Urban Research.",
  "",
  "Nelson, R. K., Ayers, E. L., Madron, J., and Connolly, N. D. B. (2016). *Mapping Inequality: Redlining in New Deal America*. American Panorama. Richmond: Digital Scholarship Lab, University of Richmond.",
  "",
  "Pacyga, D. A. (2009). *Chicago: A Biography*. Chicago: University of Chicago Press.",
  "",
  "Rothstein, R. (2017). *The Color of Law: A Forgotten History of How Our Government Segregated America*. New York: Liveright.",
].join("\n");
