/* ------------------------------------------------------------------ */
/*  research-seed-content-vol4.ts                                      */
/* ------------------------------------------------------------------ */
/*                                                                     */
/*  Fourth volume: multi-city placeholder research.                    */
/*                                                                     */
/*  Rooted Forward's research portfolio extends beyond Chicago. This */
/*  file holds seed content for entries covering New York, Dallas,   */
/*  and San Francisco — the other three cities where Rooted Forward  */
/*  operates walking tours and conducts community research.          */
/*                                                                     */
/* ------------------------------------------------------------------ */

export const CROSS_BRONX_EXPRESSWAY_BODY = [
  "## Introduction",
  "",
  "The Cross-Bronx Expressway is the most-studied road in American urban planning. It has been the subject of three major academic works, two PBS documentaries, a chapter of Robert Caro's *The Power Broker*, and dozens of journalistic retrospectives. The basic story is well-known: Robert Moses's expressway, constructed between 1948 and 1963, cut a trench through the East Tremont and Morrisania neighborhoods of the Bronx, displacing an estimated 60,000 residents and creating a permanent physical and environmental barrier that contributed to decades of disinvestment in the South Bronx.[^1]",
  "",
  "This report revisits the Cross-Bronx not for the narrative but for the numbers. We take the 2024 release of the New York Department of Transportation's modernized corridor dataset, overlay it against 1945 property acquisition records, 1980 census tract data, and 2023 air quality and asthma hospitalization records, and ask: *what can we say with fresh data about the long-term consequences of the corridor's construction that we could not say with the datasets available to earlier researchers?*",
  "",
  "The framing question is specific. It is not whether the Cross-Bronx should have been built — that question has been settled in the consensus of three generations of planners, which is overwhelmingly that it should not have been built. It is what the continuing cost of the decision has been, measured against the lived experience of present-day residents.",
  "",
  "## Data",
  "",
  "We assembled:",
  "",
  "1. **1945 property acquisition records.** The condemnation and acquisition files from the Triborough Bridge and Tunnel Authority, held at the New York City Municipal Archives. We digitized the parcel-by-parcel acquisition records for every property taken between 1948 and 1955.",
  "2. **1950 and 1960 Decennial Census tract data.** Used to reconstruct pre-expressway demographics at the census tract level for the neighborhoods the corridor passes through.",
  "3. **1980 Census tract data.** Used to measure the twenty-year downstream effect on population, income, and racial composition.",
  "4. **2023 air quality records.** The New York Department of Health's Environmental Public Health Tracking system publishes tract-level PM2.5 and ozone concentration data.[^2]",
  "5. **2023 asthma hospitalization records.** Medicaid claims data (aggregated and de-identified) showing tract-level asthma hospitalization rates for children under 18.",
  "6. **2024 DOT corridor noise data.** The New York DOT's acoustic monitoring network, installed in 2022, provides continuous decibel readings at twenty-six points along the corridor.",
  "",
  "## Findings",
  "",
  "### The 1945-1963 displacement",
  "",
  "The property acquisition records show that the expressway's construction displaced **61,340 residents** — close to the 60,000 figure Caro cited, which was based on planning documents rather than final acquisition records. The displaced population was **72 percent Black, Puerto Rican, or Italian American** — the three groups that predominated in East Tremont and Morrisania before the construction.",
  "",
  "The acquisition payments to displaced households averaged **$1,840** (approximately $22,000 in 2025 dollars). Relocation assistance, where provided, averaged an additional **$280** per household. A substantial fraction of displaced households, particularly renters in the six-flats and tenements along the future right-of-way, received nothing.",
  "",
  "### The 1960-1980 downstream effect",
  "",
  "The corridor's construction was not a single-year shock but a two-decade trauma that unfolded through the neighborhoods the expressway passed through. Between 1960 and 1980:",
  "",
  "- Population in tracts within a quarter-mile of the corridor fell **37 percent**. The adjacent borough as a whole grew 2 percent over the same period.",
  "- Median household income (in constant 1980 dollars) fell **44 percent** in the corridor tracts, compared to a 6 percent decline boroughwide.",
  "- The share of housing stock classified as \"deteriorated\" or \"dilapidated\" by the 1980 Census rose from 14 percent to 51 percent.",
  "- The share of Black and Puerto Rican residents rose from 58 percent to 81 percent, driven by the departure of white residents who had stayed through construction and the arrival of displaced residents from urban renewal elsewhere in the Bronx.",
  "",
  "These statistics are familiar from earlier accounts. What this analysis adds is tract-level specificity. The 37 percent population decline is not distributed evenly; it is concentrated in tracts 125, 127, 149, and 151, which lie immediately adjacent to the corridor. Tracts a quarter-mile to a half-mile away saw declines of 15 to 22 percent — substantial but smaller.",
  "",
  "### The 2023 environmental and health data",
  "",
  "Our central new finding is the tract-level environmental and health profile of the corridor in 2023, sixty years after the expressway's completion.",
  "",
  "**PM2.5 concentration**: tracts within a quarter-mile of the corridor have 2.1x the PM2.5 concentration of the Bronx average and 2.8x the New York City average. The corridor-adjacent tracts are in the top 3 percent of all US census tracts for PM2.5 exposure.",
  "",
  "**Ozone**: the pattern is similar but attenuated. Corridor-adjacent tracts have 1.4x the Bronx average ozone concentration.",
  "",
  "**Asthma hospitalization**: children under 18 in corridor-adjacent tracts are hospitalized for asthma at a rate of **18.4 per 1,000 per year**, compared to a Bronx average of **10.1** and a citywide average of **6.7**. The corridor-adjacent rate is 2.7x the citywide average.",
  "",
  "**Traffic-related noise**: the DOT's acoustic monitoring network records daytime decibel averages of 72-78 dB along the corridor, with overnight averages of 58-62 dB. WHO guidelines recommend overnight exposures below 40 dB for sleep quality and long-term cardiovascular health.[^3] The overnight exposures along the Cross-Bronx corridor are, on average, 18 to 22 decibels above the WHO recommendation — a difference that corresponds to roughly 16x the sound energy.",
  "",
  "### The compound pattern",
  "",
  "Taken together, the 1945 acquisition records, the 1960-1980 downstream effects, and the 2023 environmental and health data form a single continuous causal chain. The 1948 planning decision to route the expressway through East Tremont and Morrisania produced:",
  "",
  "1. Immediate displacement of 61,000 residents.",
  "2. Two decades of population loss, income decline, and housing stock deterioration.",
  "3. A permanent physical and environmental barrier with elevated air pollution, elevated noise, and downstream health effects that are measurable in 2023 data.",
  "",
  "This is not abstract. A child born today in tract 125, whose parents were born in the same tract, is breathing air that the WHO and EPA consider hazardous for long-term exposure, sleeping through overnight noise levels that peer-reviewed research links to cardiovascular risk, and presenting at the emergency room for asthma at a rate nearly three times the citywide average.",
  "",
  "## What to do about it",
  "",
  "The conventional recommendation is to cap the Cross-Bronx — that is, to build a deck over the trenched sections of the expressway, effectively creating a linear park above the roadway. Boston's Big Dig established the technical template; the 2021 federal Reconnecting Communities Pilot Program established federal funding.",
  "",
  "Proposals to cap the Cross-Bronx have been floated since the late 1990s. A 2016 study by the New York DOT estimated the cost at $8 billion to $14 billion depending on the extent of the cap. A 2023 proposal from the Bronx Borough President's office scaled the proposal back to capping a 1.7-mile segment at a cost of $2.8 billion.",
  "",
  "This report does not take a position on the cost-benefit of capping. We note only that the environmental and health burdens documented in this report are a standing public health problem that will persist until some intervention addresses them. Capping is one intervention. Reduced truck traffic, vehicle-speed reductions, and electrification of the heavy-duty fleet are others. The choice among them is a policy question.",
  "",
  "We recommend that the New York DOT, the New York City Department of Health, and the Bronx Borough President's office commission a formal cost-benefit analysis of the three alternatives — cap, traffic reduction, fleet electrification — using the health burden data we have documented here and the willingness-to-pay methodology from the EPA's Environmental Justice Screening Tool.",
  "",
  "## A note on the history",
  "",
  "The story of the Cross-Bronx is by now so thoroughly told that there is a temptation to treat it as a closed chapter — a cautionary tale of mid-century planning, superseded by more enlightened practice. This report's purpose is to resist that framing. The cautionary tale is not in the past. It is in the air quality monitor on 174th Street that reads 26 micrograms per cubic meter of PM2.5 in the morning rush hour every weekday. It is in the emergency room at Montefiore Medical Center that admits children from tract 125 at three times the citywide rate. It is in the overnight acoustic reading that keeps residents of the Park Towers complex awake at sixty decibels.",
  "",
  "The lesson of the Cross-Bronx, in 2026, is that the consequences of a 1948 planning decision are still being paid in health and life quality by people who had no voice in the decision and no ability to leave the neighborhood afterward. That is not history. That is a current policy question.",
].join("\n");

export const FILLMORE_REDEVELOPMENT_BODY = [
  "## Background",
  "",
  "Between 1948 and 1973, the San Francisco Redevelopment Agency (SFRA) acquired and demolished approximately 60 square blocks of the Western Addition and Fillmore districts, displacing an estimated 20,000 residents under the banner of federal urban renewal. The displaced population was predominantly Black, Japanese American, and Filipino — a deliberately diverse working-class neighborhood that the 1947 redevelopment plan characterized as a \"blighted area\" warranting comprehensive demolition.[^1]",
  "",
  "The Fillmore redevelopment is a well-documented case, but the available scholarship has largely focused on the demolition period. This report examines what came after: the forty years of rebuilt neighborhood, the ways the SFRA tried to compensate displaced residents, and the question of what the trajectory of the post-redevelopment Fillmore tells us about the possibility of doing redevelopment differently than the 1948 plan did.",
  "",
  "## What was lost",
  "",
  "The Fillmore before the demolition was, per virtually every source from the 1940s through the 1960s, a thriving commercial and cultural district. It had:",
  "",
  "- **A Black-owned commercial strip** on Fillmore between Geary and Divisadero, with approximately 400 Black-owned businesses at peak.",
  "- **The Harlem of the West.** The highest concentration of jazz venues outside of Harlem — Bop City, Jimbo's Bop City (the later venue), the Booker T. Washington Hotel ballroom, and more than a dozen smaller clubs.",
  "- **The pre-internment Japanese American community.** Japantown — Nihonmachi — had been San Francisco's primary Japanese American neighborhood since the 1890s. The wartime internment displaced the Japanese American residents temporarily; many returned after 1945 to find their homes and businesses intact.",
  "- **A substantial Filipino enclave** along Webster Street.",
  "- **Integrated working-class residential blocks**, with stable communities of Black, Japanese American, Filipino, and white (predominantly Jewish) residents living side-by-side.",
  "",
  "The SFRA's own 1947 survey characterized the area's housing stock as obsolete. The same survey noted, in language that revealed the framework operating behind the \"blight\" designation, that the neighborhood had an \"unusually high\" proportion of what the survey called \"racially mixed\" residential blocks.",
  "",
  "## The demolition",
  "",
  "The redevelopment was implemented in three phases:",
  "",
  "- **Western Addition Project A-1** (1949-1960): demolished 28 square blocks. Displaced approximately 8,000 residents. The demolished area became, after a decade of vacancy, the current Geary Boulevard corridor.",
  "- **Western Addition Project A-2** (1964-1973): demolished 32 square blocks. Displaced approximately 12,000 residents. The demolished area became the current Fillmore retail corridor, the Japantown Peace Plaza, and the blocks around the Fillmore Center.",
  "- **Western Addition Project A-2 Extensions** (1966-1973): targeted approximately 8 additional blocks that were ultimately only partially demolished due to community opposition led by the Western Addition Community Organization.",
  "",
  "Total acquisition payments to displaced households averaged **$3,200** per household in 1960s dollars. Very few displaced residents returned to the rebuilt neighborhood; the SFRA's own tracking data, belatedly released in 2004 in response to a Freedom of Information request, documented a return rate of under 7 percent.",
  "",
  "## The post-demolition neighborhood",
  "",
  "What was built on the cleared land, and what happened to it over the subsequent forty years, is the part of this story that has been less studied.",
  "",
  "**Geary Boulevard** (A-1 footprint): built as a six-lane arterial road with a subterranean median and occasional vehicle-oriented commercial developments. It is now one of the city's busier transit corridors, serving the 38 Geary bus line which is San Francisco's highest-ridership route. The Geary corridor is functional infrastructure. It is not a neighborhood.",
  "",
  "**Fillmore retail corridor** (central A-2 footprint): rebuilt between 1973 and 1995 in a series of smaller developments. Most of the original ground-floor retail was claimed by chain tenants. Some of the Black-owned and Japanese American businesses that existed before the demolition were eventually able to re-establish, but most did not return.",
  "",
  "**Japantown Peace Plaza and commercial area** (eastern A-2 footprint): one of the more successful rebuilds. The Peace Plaza was designed by Yoshiro Taniguchi and opened in 1968. It has served as the anchor of Japantown ever since. Current Japantown has roughly 600 Japanese American residents — a fraction of pre-war levels, but a meaningful cultural and commercial district.",
  "",
  "**Fillmore Center** (central A-2 footprint): a 1,114-unit residential complex completed in 1992 on roughly eight blocks of cleared land. Half of the units were dedicated to seniors. None were dedicated to the descendants of displaced Fillmore residents, despite community proposals during the planning period to do so.",
  "",
  "**Fillmore Heritage Center** (late A-2 footprint): a mixed-use building opened in 2007, anchored by a Yoshi's jazz club and a parking garage. The club closed in 2014. The building has been in and out of city control ever since.",
  "",
  "## The Certificates of Preference program",
  "",
  "Following decades of community pressure, the SFRA established in 2008 a **Certificate of Preference** program that offered displaced Fillmore residents and their descendants priority access to affordable housing opportunities in the Western Addition and Fillmore.[^2]",
  "",
  "As of 2025, the program has issued **4,800 Certificates of Preference** to verified descendants of displaced Fillmore residents. Of those, **2,100** have been placed in housing under the program — a success rate of about 44 percent, nearly all in deeply affordable rental units in the Fillmore Center and adjacent developments.",
  "",
  "The 2,100-placement figure is, depending on framing, a meaningful partial remedy or a disappointing under-delivery. Twenty-one hundred placements against twenty thousand original displacements is a ratio of roughly 10 percent — a number roughly comparable to the direct-return rate of the original redevelopment era.",
  "",
  "## What the post-Fillmore story tells us",
  "",
  "The Fillmore is a long case study in the question of whether redevelopment can be made right, decades after the fact, through subsequent compensatory programs. The partial answer the forty-year arc gives us is: not easily, not quickly, and not without continued pressure from the affected community.",
  "",
  "The Certificates of Preference program is real, and the residents placed under it are real, and the program is a better remedy than no remedy. It is also, on every measurable dimension, a partial remedy: fewer than half of certificate-holders have actually been placed; the placements are concentrated in a few buildings rather than in a restored neighborhood; the cultural infrastructure — the jazz clubs, the Black-owned businesses, the interwoven working-class communities — has not been rebuilt and is largely unrebuilt-able on the geography the redevelopment left.",
  "",
  "## Implications for other cities",
  "",
  "The lesson we draw from the Fillmore is not that redevelopment was a mistake — that conclusion is long settled. It is that the redevelopment era's costs are not straightforwardly reversible. Compensatory programs decades later can make partial amends. They cannot restore the pre-redevelopment neighborhood. They cannot return the 11,000 displaced Black residents who are now in their eighties and nineties and living in Antioch or Fairfield or Stockton, more than fifty miles from where they grew up.",
  "",
  "This matters for Chicago. The CHA Plan for Transformation, the 2013 school closure wave, the Bronzeville redevelopment, and the planned transit-oriented developments around the Obama Presidential Center all have the potential to produce Fillmore-scale displacement over the next twenty years. The Fillmore case tells us that the cost of a displacement is paid over generations, and that the compensatory programs that communities subsequently extract from the city are at best a partial restoration of what was lost.",
  "",
  "The policy recommendation we draw from the Fillmore is therefore structural rather than compensatory: **the less displacement a policy produces in the first place, the less the subsequent compensation has to do.** That sounds like a truism. The Fillmore's forty years of post-redevelopment work tells us it is not a truism that has been operating in practice.",
  "",
  "## A final note on the archive",
  "",
  "The SFRA's own internal records from the 1948-1973 redevelopment period are held at the San Francisco Public Library's History Center. They include the parcel-by-parcel acquisition records, the resident surveys the SFRA conducted in 1946 and 1958, and the internal correspondence that documents the planning decisions. The archive is public and searchable. It is the single most valuable resource for anyone researching the Fillmore redevelopment and its aftermath.",
  "",
  "We note this because the analogous Chicago archives — the Chicago Department of Urban Renewal files from the Hyde Park-Kenwood program — remain held at the University of Chicago and are not fully public. The Fillmore precedent suggests that full public archiving, even of records documenting decisions that many now regard as mistakes, serves the public interest of learning from them.",
].join("\n");

export const DALLAS_FAIR_PARK_BODY = [
  "## Introduction",
  "",
  "Fair Park in south Dallas is, by any measurement, one of the most historically significant sites in Texas. It is the home of the State Fair of Texas. It hosts the Cotton Bowl stadium. It contains the nation's largest collection of Art Deco architecture, designated a National Historic Landmark in 1986. It is also surrounded by neighborhoods — South Dallas, Fair Park, Lower Greenville — that have carried the cost of Fair Park's existence and expansion for ninety years.",
  "",
  "This brief documents the seven-decade history of Fair Park's land acquisitions, the neighborhoods that were cleared or partitioned to accommodate them, and the current (2025) push to redevelop the park under the Fair Park First nonprofit governance model. Our purpose is to put the contemporary redevelopment conversation in its proper historical frame.",
  "",
  "## The 1936 expansion",
  "",
  "Fair Park's current footprint was largely established during the run-up to the 1936 Texas Centennial Exposition. The city annexed approximately **42 additional blocks** of predominantly Black residential neighborhood immediately south and east of the existing fairgrounds, using a combination of condemnation, eminent domain, and aggressive informal pressure. An estimated **3,800 residents** were displaced. Acquisition payments averaged between $400 and $650 per lot — substantially below the comparable price per lot in white residential areas of Dallas during the same period.[^1]",
  "",
  "The displaced residents had limited housing alternatives. Dallas's racial covenants, enforced by the Dallas Real Estate Board until their formal rescission in 1948 and informally for decades after, restricted Black homebuyers to a small set of neighborhoods south and east of downtown. The 3,800 displaced Fair Park residents concentrated into the already-overcrowded South Dallas blocks immediately south of the new Fair Park boundaries, driving up rents and accelerating the decline of housing stock quality in those blocks.",
  "",
  "## The 1958-1966 expansion",
  "",
  "A second round of expansion occurred between 1958 and 1966 in connection with two simultaneous projects: the construction of the R.L. Thornton Freeway, and a further Fair Park parking and access expansion funded by the 1956 and 1962 Dallas parks bonds. This round displaced an additional **2,400 residents**, almost all Black, across approximately 28 blocks.",
  "",
  "Acquisition payments in the 1958-1966 round averaged between $2,100 and $2,800 per lot — somewhat closer to market rates than the 1936 acquisitions, but still below the comparable price per lot in contemporaneous white residential condemnations.",
  "",
  "## The compounding effect",
  "",
  "The two rounds of Fair Park expansion, plus the Thornton Freeway cut, plus the subsequent construction of Central Expressway along the park's western boundary, left the neighborhoods around Fair Park permanently walled off from the rest of Dallas. South Dallas today is bounded on the north by the fairgrounds, on the east by the Trinity River floodplain, on the south by Love Field industrial parcels, and on the west by a pair of freeway berms. The resulting geographic isolation compounds every other dimension of the neighborhood's challenges: transit connectivity, retail access, school enrollment, employment access, and public investment.",
  "",
  "Present-day South Dallas census tracts rank in the bottom fifth nationally on multiple dimensions of the Neighborhood Atlas Area Deprivation Index.[^2] The boundary of the Fair Park parcel is a visible line on any composite map of Dallas disinvestment.",
  "",
  "## The 2019 handoff to Fair Park First",
  "",
  "In 2019, the City of Dallas handed day-to-day management of Fair Park to **Fair Park First**, a newly-created 501(c)(3) nonprofit with representation from the State Fair of Texas, the City, and a set of community appointees. The stated rationale was that nonprofit governance could bring professional park management expertise and new philanthropic revenue that the City's Parks Department could not match.",
  "",
  "Fair Park First's 2020-2030 master plan promises, among other things:",
  "",
  "- $500 million in capital investment across the park.",
  "- A substantial expansion of community-accessible programming outside the State Fair's three-week period.",
  "- New east-side entrances designed to connect the park to the surrounding neighborhoods.",
  "- A Community Benefits Agreement with South Dallas and Fair Park community organizations.",
  "",
  "As of 2025, the plan is five years into execution. The capital investment is tracking behind schedule — approximately $140 million of the $500 million has been deployed. The Community Benefits Agreement has been drafted but not finalized. The new east-side entrances are in design.",
  "",
  "## What the Fair Park First model should be held accountable to",
  "",
  "The Fair Park First experiment is being watched in other cities that operate comparable large public parks adjacent to disinvested neighborhoods. The central accountability question is whether the nonprofit governance model produces substantively different outcomes than the long history of Fair Park-adjacent city decisions produced.",
  "",
  "We recommend the following metrics be tracked and published annually as part of any Community Benefits Agreement:",
  "",
  "1. **Capital investment in the park relative to capital investment in the surrounding neighborhoods.** A Fair Park First that invests $500 million in the park while the neighborhoods outside the fence receive a fraction of that amount in comparable infrastructure investment would replicate the existing pattern.",
  "2. **Local hiring in park construction and operations.** Fair Park First has committed to 30 percent local hiring. The verifiable rate over the first five years has been closer to 11 percent.",
  "3. **Displaced-family participation in governance.** Descendants of the 1936 and 1958-1966 displacements have a standing historical claim on Fair Park's governance. The Community Benefits Agreement should establish reserved seats for those families on Fair Park First's board or its Community Advisory Committee.",
  "4. **Acquisition protection for adjacent parcels.** Rising land values around the rebuilt Fair Park are already producing speculative investment in the surrounding residential blocks. Fair Park First should formally commit, via the Community Benefits Agreement, that the nonprofit will not support or coordinate any future expansion of the Fair Park parcel into existing residential blocks.",
  "",
  "## Fair Park is not an isolated case",
  "",
  "Comparable histories exist at Houston's Memorial Park, New Orleans's Audubon Park, Atlanta's Piedmont Park expansion, and other large urban parks that grew through mid-twentieth-century acquisition from Black neighborhoods. In each case, the contemporary redevelopment conversation is in dialogue with a history of acquisition that is partially documented and partially forgotten.",
  "",
  "Our purpose in this brief is not to litigate the 1936 or 1958 decisions. It is to insist that contemporary decisions about Fair Park be made in full knowledge of the decisions that preceded them, and in full accountability to the communities that carried the cost.",
].join("\n");
