/* ------------------------------------------------------------------ */
/*  research-seed-content-vol3.ts                                      */
/* ------------------------------------------------------------------ */
/*                                                                     */
/*  Third volume of placeholder research bodies. Covers:              */
/*  - Austin Community Benefits Agreement playbook                    */
/*  - Bronzeville TIF expenditure analysis                            */
/*  - West Side Grocery Access oral history                           */
/*  - Cook County Property Tax Appeal Disparity Report                */
/*                                                                     */
/* ------------------------------------------------------------------ */

export const AUSTIN_CBA_PLAYBOOK_BODY = [
  "Austin Coming Together has been running the Austin Quality-of-Life planning process since 2017. I have sat in on fourteen of those meetings over the past two years. The meeting that produced this playbook was on a Tuesday night in February, at By The Hand Club on West Side Boulevard, and it ran until 10:41 PM.",
  "",
  "The question on the table was not abstract. A developer had filed a letter of intent for a 180-unit residential building on the vacant former Brach's candy factory site. The planning committee of ACT wanted to know, before the developer's first community meeting, what a responsible community coalition should be ready to ask for. By 10:41 PM they had most of an answer. The rest is this playbook.",
  "",
  "## Who this is for",
  "",
  "Austin is one of Chicago's seventy-seven community areas. It has 96,000 residents and, as of the 2023 ACS five-year estimates, a median household income of $38,200 — about 47 percent of the citywide figure. Its housing stock is 63 percent renter-occupied. Between 2015 and 2024 the community area lost eleven full-service grocery stores and gained nineteen dollar stores.[^1]",
  "",
  "It is also entering a period of intensifying developer interest. The Green Line extension to Oak Park, approved in its final form in 2023, has land-use implications that are starting to show up in the predevelopment pipeline. The Auxiliary CTA hub investment, the announced Illinois Medical District expansion west toward Garfield Park, and the stalled-but-not-dead Kennedy Expressway reconfiguration are all pressures that will show up on Austin's parcels within the next forty-eight months.",
  "",
  "Community benefits agreements — **CBAs** — are the instrument that community coalitions have used since the 2001 Staples Center deal in Los Angeles to negotiate binding commitments from developers in exchange for community support.[^2] The form has evolved and the results have been uneven. What is not in dispute, among the practitioners I have interviewed for this report, is that the moment an Austin coalition most needs to be ready is the moment before the first application lands. This playbook is for that moment.",
  "",
  "It is not a legal document. CBA negotiations require qualified real estate and community development attorneys. The Westside Justice Center and the Sargent Shriver National Center on Poverty Law are the two Chicago-based legal practices with the most relevant experience, and both have indicated a willingness to take on Austin CBA work on contingency or low-fee basis. Names and direct contacts are in the appendix.",
  "",
  "## Part 1: Before the first application",
  "",
  "### Mapping the sites",
  "",
  "Every community area has a small set of parcels that are strategically attractive to developers. For Austin, as of early 2026, the inventory is:",
  "",
  "- **The former Brach's candy factory site on Austin Boulevard.** Vacant since 2003. Approximately 29 acres, in multiple parcels. Owner of record is a Delaware LLC whose managing member is a private equity firm based in Naperville.",
  "- **The Madison Street vacant lots between Mason and Central.** Eight contiguous parcels totaling about 3.4 acres. Owner of record is a family trust; the trust has been approached by at least two different developers since 2022, according to the lawyer who administers it.",
  "- **The three city-owned parcels at the southwest corner of the Green Line Oak Park extension terminus.** Total about 1.1 acres. Control sits with the Chicago Department of Planning and Development, which has not yet issued a request for proposals.",
  "- **The Columbus Park Boulevard frontage** currently held by Loretto Hospital. Reported by the *Chicago Sun-Times* in August of 2025 to be part of a hospital capital plan that is under review by the board.",
  "- **The pre-rezoning parcels at Cicero and Lake** that our research team identified in a September 2025 corridor brief.",
  "",
  "These sites are the likeliest near-term candidates. Organizing should start on them before an application lands, not after.",
  "",
  "### Assembling the coalition",
  "",
  "A CBA is negotiated by a community coalition. A one-organization CBA is generally not enforceable as a CBA in any meaningful sense — the developer will negotiate with the one organization, make token commitments, and extract a signature that later turns out to mean less than the coalition thought. The coalition is what produces the leverage.",
  "",
  "A workable Austin coalition, as of early 2026, would include at minimum:",
  "",
  "1. **Austin Coming Together.** The primary community planning body; holds the Austin Quality-of-Life Plan. The plan is the closest document Austin has to a neighborhood master plan, and any serious CBA negotiation should be anchored to its commitments.",
  "2. **BUILD.** A direct-service organization with deep relationships in the northern half of the community area.",
  "3. **Westside Health Authority.** A community development organization with programming across Austin and Garfield Park.",
  "4. **At least two tenant organizations.** Austin Tenants United and the Westside Justice Center's housing legal program.",
  "5. **At least one faith community.** Third Unitarian Church on Chicago Avenue has anchored prior CBA work. Greater Institutional AME Church on Jackson Boulevard has comparable reach.",
  "",
  "Five to seven organizations is typical for a mid-sized project — fifty to two hundred residential units. Larger projects warrant broader coalitions. Smaller projects, below fifty units, are usually better served by a single community organization negotiating on behalf of the block it serves, rather than a formal coalition.",
  "",
  "### Defining the floor",
  "",
  "Before any specific project lands, the coalition should define the **floor** — the minimum acceptable set of community benefits for any project above a threshold size. The floor is not the negotiating position. It is the walk-away.",
  "",
  "A reasonable Austin floor for a land-acquisition project of fifty units or more:",
  "",
  "- **At least 30 percent of units affordable** at 60 percent of Area Median Income.",
  "- **At least 10 percent of units affordable** at 30 percent AMI — the deep-subsidy tier the standard Affordable Requirements Ordinance does not cover.",
  "- **First right of refusal** for existing tenants on displaced units, with lease-takeover rights and a rent-increase cap for the first seven years.",
  "- **Local hiring commitment** of at least 40 percent of construction and operations jobs to Austin residents, with verification mechanisms and penalty clauses for non-compliance.",
  "- **Neighborhood-serving retail commitment** for ground-floor commercial space, with a preference for Austin-based businesses and a prohibition on chain pharmacy, big-box retail, and national fast-food tenants for the first ten years.",
  "- **Community monitoring body** with at least three seats reserved for community-selected representatives, two of whom should be existing tenants of the displaced blocks.",
  "- **Anti-flipping covenant** preventing the sale of the property for at least seven years after completion.",
  "",
  "These are minimum terms. Larger projects, more profitable pro formas, or sites with significant public subsidy should produce more.",
  "",
  "### Research backing",
  "",
  "Every term in a CBA requires research backing. An affordability percentage that is not tied to the actual income distribution of the neighborhood is easier to characterize as arbitrary. A local hiring commitment that is not tied to labor market conditions is easier to characterize as infeasible. The developer's lawyer will characterize them that way if you let her.",
  "",
  "The coalition should assemble, before the first community meeting:",
  "",
  "- Current income distribution by census tract.",
  "- Current renter demographic data.",
  "- Comparable affordability percentages in CBAs in other Chicago neighborhoods. Our research team maintains a public dataset of comparable CBAs at `rootedforward.org/research/data/chicago-cbas.csv`.",
  "- Construction labor market data showing that local hiring is feasible at the committed percentage.",
  "- Retail market study showing that neighborhood-serving retail is viable in the project's commercial footprint.",
  "",
  "Rooted Forward provides research support for Austin coalitions negotiating CBAs. The inquiry address is `research@rootedforward.org`.",
  "",
  "## Part 2: When the application lands",
  "",
  "### First contact",
  "",
  "The first contact with the developer is typically an invitation to a community meeting at which the developer presents an initial concept. The meeting is the developer's opportunity to set the frame. The coalition's job is to refuse the frame.",
  "",
  "Specifically:",
  "",
  "1. **Attend. Listen. Ask clarifying questions.** Do not commit to a position at the first meeting. The pressure to do so is substantial and intentional.",
  "2. **Request the developer's full project pro forma** — construction costs, projected rents, projected return on investment. This is the document that tells the coalition how much room is in the deal for community benefits. Developers frequently refuse. Record the refusal in writing.",
  "3. **Request a written scope of community consultation** — a schedule of meetings, a clear decision-making timeline, a commitment that the developer will not file with the City until the consultation is complete.",
  "4. **Announce the coalition publicly.** Send a formal letter to the developer, the local alderperson's office, and the Department of Planning and Development. State the coalition's intent to negotiate a CBA as a condition of community support.",
  "",
  "The letter is a legal-adjacent instrument. It does not have binding effect. It does create a paper trail and signal to the developer and the City that the coalition is organized.",
  "",
  "### What the negotiation looks like",
  "",
  "A full CBA negotiation runs three to six months. Weekly meetings with the developer, with published agendas and minutes, work better than ad hoc scheduling. A designated lead negotiator speaks for the coalition as agreed in coalition meetings — not unilaterally. A designated lead attorney reviews every draft.",
  "",
  "The community meetings that run parallel to the developer meetings are the source of the coalition's mandate. The mandate has to be refreshed continuously. A coalition that stops meeting with the wider community between developer sessions loses its authority to speak in the developer's room within about six weeks.",
  "",
  "### The tactical moves to expect",
  "",
  "Developers in CBA negotiations have a consistent playbook. The five moves most commonly seen in Chicago negotiations over the past ten years, in descending order of frequency:",
  "",
  "1. **The alternative coalition.** The developer identifies or creates a parallel community organization willing to accept weaker terms. Sometimes a single person with legitimate community ties but no organizational mandate. The response: continue to operate on the basis of the coalition's broader mandate. Do not engage with the alternative's terms.",
  "2. **The timeline squeeze.** The developer claims the project's timeline requires a signed CBA within thirty days or the project is gone. The timeline is the developer's problem. A CBA that cannot be negotiated on an honest schedule is not a CBA the coalition should sign.",
  "3. **The pro forma obscuration.** The developer refuses to share the project pro forma, or shares a sanitized version. Request the pro forma formally, in writing. Include the refusal in the public record.",
  "4. **The alderperson-direct maneuver.** The developer bypasses the coalition and works directly with the alderperson's office to secure zoning approval in exchange for weaker commitments. Maintain a strong parallel relationship with the alderperson's office. Make clear that coalition opposition will be visible and organized.",
  "5. **The last-minute ask.** In the final days, the developer introduces a new ask — a density bonus, a setback variance, a parking exemption — that was not on the table earlier. Do not grant last-minute concessions without renegotiating the trade-offs in the rest of the agreement.",
  "",
  "### The three-party structure",
  "",
  "A CBA is a contract. Like any contract, it is worth what the enforcement mechanism is worth. The most common failure pattern in CBAs that have been signed and then not honored is that the enforcement mechanism was weak.",
  "",
  "A three-party CBA — developer, coalition, and a local government entity — is substantially more enforceable than a two-party CBA without a government signatory. The local government has an independent enforcement interest; its attorneys can sue without requiring the coalition to fund the litigation; and the government's signature makes the agreement part of the project's approval conditions, which means a material breach can trigger revocation of zoning relief.",
  "",
  "The Chicago Department of Housing has, in six separate agreements since 2019, been willing to sign as the third party. The pattern has not been formally adopted as a department policy, but the track record is now long enough to cite as precedent. Coalitions should request a three-party structure as their default.",
  "",
  "## Part 3: After the signing",
  "",
  "### Monitoring",
  "",
  "CBAs fail most often at monitoring, not at negotiation. The developer signs, builds, and the community benefits never fully materialize because nobody with standing is watching.",
  "",
  "A **CBA monitoring body** should include:",
  "",
  "- Quarterly meetings with the developer.",
  "- Access to the developer's rent rolls, for affordability verification.",
  "- Access to the developer's employment records, for local hiring verification.",
  "- Access to the developer's leasing records, for neighborhood-serving retail verification.",
  "- Annual public reporting of CBA compliance.",
  "",
  "Monitoring requires resources. The coalition should secure a budget line as part of the CBA itself — a direct contribution from the developer, a foundation grant, or an appropriation from the local government party. The Woodlawn CBA draft of 2018 proposed a 0.25 percent annual contribution from project revenue; that figure is a reasonable floor for negotiations in Austin.",
  "",
  "### Renewal",
  "",
  "CBAs are living documents. Economic cycles, zoning code updates, ownership transfers — conditions change. The coalition should expect to renegotiate or amend the agreement at least once over its lifetime.",
  "",
  "Maintain the coalition past the initial signing. The coalition's continued existence is what keeps the CBA enforceable in practice. Coalitions that disband after signing find the agreement slowly loses force — not because the document is gone, but because the organizations that could enforce it are gone.",
  "",
  "## Part 4: When the CBA does not happen",
  "",
  "Not every development will be amenable to a CBA. Some developers refuse to negotiate. Some projects are small enough that a full CBA is disproportionate. Some move through the approval process faster than a coalition can organize.",
  "",
  "In those cases the coalition's job shifts: from CBA negotiation to public opposition. Public opposition is a different set of tools — written comment campaigns, alderperson pressure, media coverage, public hearings, litigation. Our policy page documents those tools at `rootedforward.org/policy`.",
  "",
  "This playbook exists to prepare Austin coalitions to negotiate a CBA when the option is available. It does not promise that every project will end in a signed agreement. It helps the coalition know the difference.",
  "",
  "## Reference CBAs",
  "",
  "The five CBAs below are public documents that provide useful precedent:",
  "",
  "- **Staples Center CBA**, Los Angeles, 2001. The foundational modern CBA. Thirty years of ongoing monitoring.",
  "- **Atlantic Yards CBA**, Brooklyn, 2005. A cautionary tale on monitoring weakness.",
  "- **Kingsbridge Armory CBA**, Bronx, 2013. Strong local hiring and living wage provisions.",
  "- **Woodlawn CBA draft**, Chicago, 2017. The draft that preceded the 2022 Obama Center ordinance. Never signed in its original form; annotated with our notes on why.",
  "- **Mount Hope CBA**, Boston, 2019. A transit-oriented development CBA with strong affordable housing and retail provisions.",
  "",
  "Copies of each, with Rooted Forward annotations, are available in our research archive at `rootedforward.org/research`.",
  "",
  "---",
  "",
  "*Prepared for Austin Coming Together's planning committee, February 2026. Revised after community review on March 17, 2026.*",
].join("\n");

export const BRONZEVILLE_TIF_ANALYSIS_BODY = [
  "The Bronzeville Tax Increment Financing district was designated in 2002. It will sunset in 2025 unless extended by City Council. Over its twenty-three-year life it has raised $318 million in property tax revenue that would otherwise have flowed to the general city budget.",
  "",
  "This report is a line-by-line accounting of where that $318 million went. I assembled it from the Cook County Clerk's annual TIF reports and the Chicago Department of Finance's Annual Financial Analysis, cross-referenced against the project-level expenditure files that the Department of Planning and Development publishes — or in some cases does not publish, and that I recovered via FOIA.",
  "",
  "The headline: of the $318 million raised in Bronzeville, $127 million — about 40 percent — was spent in Bronzeville. The rest was transferred to adjacent districts, reclassified as \"regionally significant,\" or remains in the district's fund as of the latest reporting year.",
  "",
  "## How Chicago TIF actually works",
  "",
  "When the City designates a TIF district, property tax revenue above a baseline frozen at the designation year is diverted from the regular city budget into a dedicated TIF fund. The fund can be spent on eligible projects within the district. It can also — and this is where most of the controversy lives — be spent on eligible projects in adjacent districts, or on projects that the Department of Planning and Development designates as regionally significant.",
  "",
  "The legal framework permitting cross-district expenditure is the \"port-to-port\" provision of the Illinois TIF statute, modified by Chicago's own TIF ordinance to allow broader use. In practice, a TIF district's fund can be spent almost anywhere in Chicago if the DPD can articulate a public purpose.",
  "",
  "This means a TIF district drawing its tax revenue from a disinvested community area can fund projects in a wealthier one. The Bronzeville district is, among the ninety-plus Chicago TIF districts now active or recently expired, one of the clearest examples of that pattern.[^1]",
  "",
  "## The raw numbers",
  "",
  "**Revenue**, 2002–2025: $318.2 million.",
  "",
  "**Expenditure by geography**:",
  "",
  "- Within district: **$127.1 million** (40 percent).",
  "- Transferred to adjacent TIFs: **$42.4 million** (13 percent). Primarily the Near South TIF and the Woodlawn TIF.",
  "- Reclassified as \"regionally significant\" and spent outside the district: **$93.7 million** (29 percent).",
  "- Remaining in the fund: **$55 million** (17 percent).",
  "",
  "The 40 percent within-district rate is lower than the citywide average of 62 percent and substantially lower than the rate in TIF districts covering wealthier areas. For comparison: the Central Loop TIF's within-district rate is 91 percent.",
  "",
  "## What the within-district spending funded",
  "",
  "Of the $127 million spent within Bronzeville, the breakdown is:",
  "",
  "- **$54 million** for new construction of market-rate residential units.",
  "- **$22 million** for commercial facade improvements along the 35th Street retail corridor.",
  "- **$18 million** for parking infrastructure — two garages and on-street metering upgrades.",
  "- **$15 million** for streetscape and lighting improvements.",
  "- **$8 million** for three schools, including the HVAC replacement at DuSable Leadership Academy.",
  "- **$6 million** for affordable housing. One forgivable loan to a forty-unit project completed in 2016.",
  "- **$4 million** distributed across roughly thirty small grants to local businesses.",
  "",
  "Affordable housing is five percent of within-district spending and 1.9 percent of the district's total revenue over twenty-three years.",
  "",
  "## What was transferred",
  "",
  "The $42 million transferred to adjacent districts funded:",
  "",
  "- Infrastructure improvements around McCormick Place, via the Near South TIF.",
  "- Housing rehabilitation in the eastern portion of Woodlawn.",
  "",
  "The $94 million reclassified as regionally significant and spent outside the district funded:",
  "",
  "- **$31 million** of the CTA Red Line Modernization Project, primarily Loop-end upgrades.",
  "- **$24 million** of the CityPASS educational facility consolidation in the West Loop.",
  "- **$18 million** of the Chicago Fire Department training academy in Garfield Park.",
  "- **$15 million** of Millennium Park's operations subsidy over a five-year period ending in 2019.",
  "- **$6 million** distributed across assorted smaller regional projects.",
  "",
  "## The reading",
  "",
  "Over twenty-three years, the Bronzeville TIF raised $318 million from property taxes on parcels in Bronzeville — taxes that would otherwise have flowed to the general city budget and been available for citywide spending. Of that $318 million, only $127 million — 40 percent — was reinvested in the community area that generated it. A substantial portion of that 40 percent funded market-rate housing and commercial infrastructure that accelerates neighborhood change rather than stabilizing existing residents.",
  "",
  "This pattern is consistent with broader critiques of Chicago's TIF system from the Civic Lab Chicago (via the TIF Illumination Project), the Grassroots Collaborative, and the City's own 2018 TIF Task Force report.[^2][^3] It is, to my knowledge, the first detailed analysis of a single majority-Black TIF district's full lifetime expenditure pattern.",
  "",
  "> \"The TIF was supposed to be for us,\" Mrs. Margaret Burroughs, whose family has lived on Indiana Avenue since 1956, told me when I showed her the spreadsheet. \"It turns out we made the money and somebody else got the money. That is not news to me. It's only news that somebody finally wrote it down.\"",
  "",
  "## Recommendations",
  "",
  "The following are amendments to Chicago's municipal TIF ordinance. They do not require amending Illinois state law; they can be implemented by the City Council alone.",
  "",
  "1. **Within-district expenditure minimum.** The TIF ordinance should require that at least 75 percent of TIF revenue be spent within the district's boundaries. Cross-district transfers should require a City Council supermajority approval.",
  "2. **Affordable housing minimum for majority-renter districts.** Any TIF district whose renter share exceeds 50 percent should allocate at least 25 percent of its revenue to affordable housing construction or preservation.",
  "3. **Community review board.** TIF districts should have a community review board with binding authority to approve or block large project allocations within the district.",
  "4. **Real-time public dashboard.** DPD should publish a public, real-time TIF expenditure dashboard showing every project funded, its geography, its stated public purpose, and its completion status. The data already exists. It has not been published in a usable form.",
  "",
  "## Method note",
  "",
  "The TIF revenue and expenditure data in this report is drawn from public sources. The categorization of projects by geography and project type is my own, based on the Department of Planning and Development's file documentation. I have tried to categorize consistently; disagreements are possible and welcome, and I will issue corrections with attribution if errors are brought to my attention.",
  "",
  "The full dataset, with every categorization visible, is downloadable as a CSV at `rootedforward.org/research/data/bronzeville-tif-expenditures-2002-2025.csv`. The Jupyter notebook that produced the aggregations is in the accompanying GitHub repository under `rooted-forward/bronzeville-tif-analysis`, released under an MIT license. Replicate it. Argue with me about the categorizations. The point of publishing the code is so that the argument can be specific rather than general.",
  "",
  "---",
  "",
  "*Prepared in consultation with the Bronzeville community planning council. Reviewed by Mrs. Burroughs, Reverend Otis Moss III of Trinity United Church of Christ, and Dr. Amina Khatri of the University of Illinois Chicago's College of Urban Planning and Public Affairs.*",
].join("\n");

export const WEST_SIDE_GROCERY_ORAL_HISTORY_BODY = [
  "Mrs. Dolores Washington is eighty-one. She has lived in North Lawndale since 1962. In the course of our April interview she named, from memory, fourteen grocery stores that used to sit within walking distance of her front door on Pulaski Road.",
  "",
  "There are two left.",
  "",
  "This collection is about the thirteen that are gone, and the other nine that closed, relocated, or downsized across the four West Side community areas that surround her: Austin, East Garfield Park, West Garfield Park, and North Lawndale. Twenty-three full-service grocery stores between 2005 and 2024, according to the Cook County Assessor's commercial occupancy records, cross-referenced with the USDA Food Access Research Atlas.[^1]",
  "",
  "As of 2025, those four community areas contain 268,000 residents and nine full-service grocery stores. That is one store per roughly 30,000 residents. The citywide average is one store per 8,000.",
  "",
  "The numbers alone do not communicate what has happened. They do not answer the question of what it is actually like to raise a family across a twenty-year period in which the number of grocery stores within walking distance falls from five, to three, to two, to zero. That is the question this collection answers.",
  "",
  "## Part 1: Before the 2010 wave",
  "",
  "### Mrs. Dolores Washington, 81, North Lawndale — interviewed June 2024",
  "",
  "> \"There was a Del Farm on Pulaski. There was a Jewel on Cermak. There was a Mexican grocery on 16th Street that my neighbors used all the time even though I didn't speak enough Spanish to shop there myself. There was an A&P where the vacant lot is now at Douglas Park. That was five full stores in one community area. Today we have one. That's what they don't put in the newspaper articles.\"",
  "",
  "Mrs. Washington has lived in North Lawndale since 1962. She raised seven children in the community area. She has watched the grocery landscape go from abundant to barren over her sixty-three years in the neighborhood.",
  "",
  "> \"It is not a story,\" she said. \"It is a subtraction. One at a time.\"",
  "",
  "### Mr. Terrence Bell, 76, Austin — interviewed August 2024",
  "",
  "Mr. Bell is a retired CTA bus operator. His family has been in Austin since 1958.",
  "",
  "> \"You used to see the produce trucks come to the Dominick's on Madison twice a week. The Dominick's is long gone. The trucks don't come here at all now. What we have is a Walgreens and a Dollar General. My granddaughter calls them 'pretend groceries.' She's not wrong.\"",
  "",
  "He notes that his three adult children all live in suburbs where full-service groceries are routine — and where his grandchildren, visiting him in Austin, are sometimes surprised by what is not available.",
  "",
  "## Part 2: The Dominick's wave",
  "",
  "The 2013 Dominick's closure was not specific to the West Side. Safeway, the chain's parent, announced the closure of all seventy-two Chicago-area Dominick's stores in October of 2013, citing competitive pressure. The closures were complete by December. The effect of the closures, though, was not distributed uniformly across the city. Stores in the Loop, Lincoln Park, and on the North Side were absorbed by successor chains within eighteen months. Stores on the West and South Sides mostly were not.[^2]",
  "",
  "### Ms. Angela Richardson, 54, East Garfield Park — interviewed July 2024",
  "",
  "> \"When the Dominick's on Madison closed, I was already driving my grandmother to Oak Park to shop. She refused to use the corner store because she said the prices were a disrespect. She was not wrong. The corner store charged twice what the Dominick's had charged for the same brand of flour. I drove her to Oak Park every week until she died in 2019. That drive was forty minutes round trip, without traffic.\"",
  "",
  "### Mr. Rudy Vargas, 67, East Garfield Park — interviewed July 2024",
  "",
  "Mr. Vargas worked in the meat department of the Madison Street Dominick's for fourteen years. The store closed in December of 2013.",
  "",
  "> \"They gave us severance — two weeks for every year of service. I was fifty-two. I have not worked in a grocery store since. There were not any grocery stores left close enough to commute to.\"",
  "",
  "He is one of two former grocery workers in this collection. His account is the most detailed we have of the closure from inside the store.",
  "",
  "> \"The last day of December the trucks came and took out the freezer cases. Customers came to watch. A woman I knew from the block, she had been shopping there for eighteen years, she cried in the aisle. I cried too. I still don't know where she shops now.\"",
  "",
  "### Ms. Keshia Adams, 47, West Garfield Park — interviewed September 2024",
  "",
  "Ms. Adams is raising three children and works full time as a medical biller.",
  "",
  "> \"When the Dominick's closed, my grocery shopping went from one forty-five-minute trip per week to either two two-hour trips on public transit to get to the Jewel in Oak Park, or ordering from Instacart which doubles the price of everything. I couldn't do two-hour trips with three kids. I have been paying the Instacart premium for twelve years. If you want to know why working-class families on the West Side are broke, the grocery surcharge is one line item on a long ledger.\"",
  "",
  "## Part 3: The post-Dominick's improvisation",
  "",
  "The replacements for Dominick's, Jewel, and the other departed full-service groceries — corner stores, dollar stores, bodegas, pharmacy shelves, online delivery — do not provide the same mix of fresh produce, dry goods, meat, and dairy at comparable prices. Every narrator in this collection had some version of the same observation. The precision with which they had come to understand the price gap was, uniformly, impressive.",
  "",
  "### Mr. Ahmed Sanogo, 41, Austin — interviewed October 2024",
  "",
  "Mr. Sanogo owns and operates a corner grocery on Madison Street. He arrived in Chicago from Mali in 2007 and opened his store in 2014.",
  "",
  "> \"I want to provide for the community. But I am not a supermarket. I am one man with two employees and a cargo van. I go to the wholesale market in Bridgeport three times a week. I carry what fits in my van. If someone needs something specific, I can order it, but it arrives in three days and costs more than it would at a supermarket. This is not a full replacement. Everyone pretends it is. It is not.\"",
  "",
  "### Ms. Patrice Okonkwo, 35, North Lawndale — interviewed September 2024",
  "",
  "Ms. Okonkwo founded a community food cooperative in 2019 in response to the grocery gap. The cooperative has roughly 180 members who pay a monthly fee for access to bulk buys.",
  "",
  "> \"We are trying to be a supplement, not a replacement. A full-service grocery requires capital, infrastructure, and a location that we do not have. We are buying flour by the fifty-pound sack and dividing it among members. It works. It is also a twentieth of what a Dominick's would be. The city should not be in a situation where a neighborhood of 35,000 people is reliant on a 180-member cooperative as part of its food infrastructure.\"",
  "",
  "## Part 4: The children",
  "",
  "The interview team asked each narrator to reflect on what their grandchildren, or their students, or their younger neighbors have come to understand as normal for grocery access.",
  "",
  "### Mrs. Washington, continued",
  "",
  "> \"My granddaughter asked me once what a deli counter was. She was twelve. She had never been in a store with one. I took her to the Mariano's in River North to show her. She was not impressed by the deli counter itself. She was impressed that it existed. She said, 'I thought they were in TV shows.'\"",
  "",
  "### Ms. Adams, continued",
  "",
  "> \"My oldest son, who is sixteen, has never in his life walked to a grocery store. Literally never. He has walked to the corner store. He has walked to the Dollar Tree. He has never walked to a grocery store. We have always had to drive or take transit. That will probably be true for his entire childhood. The normal mental model of a grocery store is something he has had to learn from books and TV, not from his own walk to one.\"",
  "",
  "## Editor's reflection",
  "",
  "Oral history is not the same as policy analysis. What it does is make a policy question specific.",
  "",
  "The policy question here is whether the combination of market forces and zoning decisions that produced the West Side grocery gap over the past two decades is one that residents of the affected community areas should be expected to accommodate, adapt to, or fight.",
  "",
  "The testimony in this collection suggests a third option. The narrators are not passive. They are adapting — driving to Oak Park, paying Instacart premiums, running cooperatives, operating corner stores that gesture at groceries without being groceries. They are also, to a person, clear that the adaptation is partial, expensive, and a tax on their daily lives that people in other parts of Chicago simply do not pay.",
  "",
  "The policy implication is not a single grant to a single chain to open a single store. It is a framework for treating grocery access as public infrastructure — measurable, auditable, as much a municipal responsibility as water, sewer, and transit. The accompanying analytical report develops that framework.[^3]",
  "",
  "Meanwhile, the testimony above is on the record. Mrs. Washington named fourteen stores. Eleven of them are closed. She remembers the names. She remembers where the front doors were. She remembers who worked the registers. She is not the only one who remembers.",
  "",
  "---",
  "",
  "*Ten interviews conducted across Austin, East Garfield Park, West Garfield Park, and North Lawndale between June 2024 and February 2025. Narrators were compensated for their time at the prevailing Illinois oral-history rate ($125). All narrators reviewed and approved their quoted passages prior to publication.*",
].join("\n");

export const PROPERTY_TAX_APPEAL_DISPARITY_BODY = [
  "In 2024, the median homeowner in a majority-white census tract in Cook County filed a property tax appeal at a rate of ninety-three per thousand parcels per year, and those appeals succeeded at a rate of 72 percent. The median homeowner in a majority-Black tract filed at thirty-nine per thousand, and succeeded at 40 percent.",
  "",
  "Multiplied through, that is a 2.4× gap in filing rates and a 1.8× gap in success rates. It produces, over a decade, an effective 5× gap in cumulative reductions in assessed value.",
  "",
  "This is a data analysis of ten years of Cook County property tax appeal records — 2015 through 2024, 1.74 million appeal filings in total. The underlying data was obtained via Freedom of Information request and is published as a CSV in the accompanying data directory. The analysis code is in a public GitHub repository. Neither the data nor the code has been published in this form before, to the best of my knowledge. The gap itself has been documented, most rigorously by Avenancio-León and Howard in their 2022 *Quarterly Journal of Economics* paper, which the current Cook County Assessor's office cites as the motivating evidence for its 2019 equity audit.[^1]",
  "",
  "## How property tax appeals work in Cook County",
  "",
  "A property owner in Cook County who believes their assessment is too high can file an appeal with the Cook County Assessor during the triennial reassessment year, or with the Board of Review in any year. A successful appeal reduces the assessed value, which reduces the property tax bill.",
  "",
  "The appeal system is available to any homeowner. The practical access to it, as the pattern below will show, is not uniform.",
  "",
  "Appeals have costs. Filing requires paperwork, documentation of comparable properties, and — in practice, for most successful appeals — a professional property tax attorney or appraiser. The system runs on the social and professional networks that make appeal filing routine in some neighborhoods and unusual in others.",
  "",
  "## The data",
  "",
  "I obtained ten years (2015–2024) of full appeal records from the Cook County Assessor and the Cook County Board of Review, via FOIA #2024-09217 and FOIA #2024-09218 respectively. The full dataset contains 1,741,823 appeal filings, each with a Property Index Number, filing date, disposition (reduction, affirmation, or withdrawal), and requested-vs-granted assessed value.",
  "",
  "I matched each appeal to the property's 2020 census tract using the Illinois Department of Revenue's parcel-to-tract crosswalk and a point-in-polygon match against the Census TIGER/Line shapefiles.[^2] I then merged with the 2023 American Community Survey five-year estimates to obtain racial composition and median household income for each tract.",
  "",
  "## The three metrics",
  "",
  "I computed, at the tract level, three metrics:",
  "",
  "1. **Filing rate**: appeals filed per 1,000 residential parcels, averaged across the ten-year window.",
  "2. **Success rate**: percentage of filed appeals that resulted in any reduction in assessed value.",
  "3. **Reduction magnitude**: median percentage reduction in assessed value, among successful appeals.",
  "",
  "Each metric was cross-tabulated against the tract's racial composition (majority-white, majority-Black, majority-Latino, mixed/other) and median household income quintile.",
  "",
  "## Filing rate",
  "",
  "Homeowners in majority-white tracts filed appeals at a rate of **93 per 1,000 residential parcels per year** on average over the ten-year window. The corresponding rates for other tract groups:",
  "",
  "- Majority-Black tracts: **39 per 1,000**.",
  "- Majority-Latino tracts: **51 per 1,000**.",
  "- Mixed or other tracts: **68 per 1,000**.",
  "",
  "The majority-white to majority-Black ratio is **2.4×**.",
  "",
  "## Success rate",
  "",
  "Of filed appeals, the share resulting in a reduction:",
  "",
  "- Majority-white tracts: **72 percent**.",
  "- Majority-Black tracts: **40 percent**.",
  "- Majority-Latino tracts: **48 percent**.",
  "- Mixed or other tracts: **58 percent**.",
  "",
  "The majority-white to majority-Black success ratio is **1.8×**.",
  "",
  "## Reduction magnitude",
  "",
  "When appeals did succeed, the median reduction:",
  "",
  "- Majority-white tracts: **9.2 percent**.",
  "- Majority-Black tracts: **6.8 percent**.",
  "- Majority-Latino tracts: **7.1 percent**.",
  "- Mixed or other tracts: **8.0 percent**.",
  "",
  "The reduction magnitude gap is smaller than the other two, but it compounds with them.",
  "",
  "## The compound effect",
  "",
  "Multiplying filing rate by success rate by reduction magnitude gives an expected annual assessment reduction per parcel:",
  "",
  "- Majority-white tracts: 0.093 × 0.72 × 0.092 = **0.616 percent of assessed value per year**.",
  "- Majority-Black tracts: 0.039 × 0.40 × 0.068 = **0.106 percent**.",
  "- Majority-Latino tracts: 0.051 × 0.48 × 0.071 = **0.174 percent**.",
  "",
  "Over a decade, homeowners in majority-white tracts reduce their cumulative assessed value by roughly **6.2 percent** through the appeal process. Homeowners in majority-Black tracts reduce theirs by **1.1 percent**. That difference, applied to a typical tax bill, is worth several hundred to several thousand dollars per homeowner per decade.",
  "",
  "## Does income explain this?",
  "",
  "Some of it. Not all.",
  "",
  "Among tracts in the top quintile of median household income, the filing and success rate differences by race persist at attenuated magnitudes:",
  "",
  "- Filing rate: white 108 per 1,000, Black 64 per 1,000. Ratio 1.7×.",
  "- Success rate: white 76 percent, Black 52 percent. Ratio 1.5×.",
  "",
  "Among tracts in the bottom quintile, the differences look similar. Income is not the primary driver of the gap. What remains after controlling for income is most plausibly explained by differential access to the social and professional networks that make appeal filing routine — a finding consistent with Avenancio-León and Howard's decomposition of the national assessment gap into a spatial channel and an appeals channel.",
  "",
  "## Who files for whom",
  "",
  "A subsidiary analysis of who actually files the appeals tells a parallel story.",
  "",
  "In majority-white tracts, **78 percent of appeals are filed by a small number of property tax law firms** — the top twenty firms file 65 percent of all appeals in those tracts. The firms specialize. They have relationships with Assessor and Board of Review staff. They file at scale, sometimes thousands of appeals per reassessment cycle.",
  "",
  "In majority-Black tracts, **only 31 percent of appeals are filed by the same pool of firms**. The rest are filed by the homeowner directly (24 percent) or by a much wider set of less-specialized attorneys, notaries, and tax preparers (45 percent).",
  "",
  "Specialized firms succeed at a much higher rate than direct filings. Within any given tract, an appeal filed by one of the top twenty specialized firms is twice as likely to succeed as an appeal filed by the homeowner pro se.",
  "",
  "The access gap is not knowledge of whether to appeal. It is access to the specialized appeal infrastructure that routinely serves some neighborhoods and not others.",
  "",
  "## The pattern is not the law",
  "",
  "The property tax appeal system produces a racial disparity in tax burden. It does so not through discriminatory statute — the appeal rules are the same for every homeowner — but through unequal access to the practical infrastructure the system runs on.",
  "",
  "This is a classic facially-neutral, disparately-applied pattern. The same pattern has been documented in Chicago's tax scavenger sale system, in the FHA loan program's historical redlining operations, and in policing outcomes documented elsewhere in this research portfolio.",
  "",
  "## Recommendations",
  "",
  "The Cook County Assessor and Board of Review should, in order of administrative feasibility:",
  "",
  "1. **Proactively identify over-assessed parcels** — through statistical review of the assessment rolls — and reduce their assessed values without requiring an appeal. This is standard practice in several Illinois counties outside Cook, including Lake County and DuPage County.",
  "2. **Fund a property tax clinic** — at community colleges or legal aid organizations — providing free or low-cost appeal assistance in majority-Black and majority-Latino community areas.",
  "3. **Simplify the pro se appeal process** — the forms, the documentation requirements, the comparable-property criteria — to reduce the professional infrastructure gap.",
  "4. **Publish the full appeal record annually** in a machine-readable format, with demographic cross-tabulations, as a standing public accountability mechanism.",
  "",
  "The 2019 equity audit commissioned by the previous Cook County Assessor identified the same pattern this analysis confirms. The current administration has publicly committed to addressing it and has not, as of this writing, fully implemented that commitment.[^3]",
  "",
  "## Method note and data access",
  "",
  "The full dataset, the code used to process it, and the figures reproduced in this report are available at `rooted-forward/cook-property-tax-appeal-analysis` in the public GitHub repository, released under an MIT license. I welcome replication. This is a politically sensitive analysis; the best response to challenges to its methodology is open data and reproducible code.",
  "",
  "---",
  "",
  "*Prepared with research support from the Chicago-Kent College of Law's Institute for Policy and Law, and reviewed by Dr. Amina Khatri of UIC, Marcus Alvarez of the Institute for Housing Studies at DePaul, and Ibrahim Diallo of Chicago-Kent. All errors are mine.*",
].join("\n");
