/* ------------------------------------------------------------------ */
/*  research-seed-content-vol3.ts                                      */
/* ------------------------------------------------------------------ */
/*                                                                     */
/*  Academic research bodies for:                                      */
/*  - Community Benefits Agreements in Chicago (Austin case analysis) */
/*  - Bronzeville TIF Expenditure Analysis                            */
/*  - West Side Grocery Access oral history                           */
/*  - Cook County Property Tax Appeal Disparity                       */
/*                                                                     */
/* ------------------------------------------------------------------ */

export const AUSTIN_CBA_PLAYBOOK_BODY = [
  "## Abstract",
  "",
  "This paper examines the application of the community benefits agreement (CBA) instrument in Chicago's Austin community area, situating the emerging Austin CBA pipeline against a twenty five year evidence base on CBA outcomes in US cities. Using a case comparison of eight Chicago CBAs adopted between 2005 and 2024, supplemented by the comparative literature on CBA implementation (Gross, LeRoy, and Janis Aparicio 2005; Marcello 2007; Salkin and Lavine 2008; Been 2010), the paper identifies five structural features that correlate with post signing compliance: three party enforcement structure, monitoring body independence, specific numerical commitments, material penalty clauses, and coalition longevity past signing. The findings inform recommendations for Austin community organizations preparing to negotiate CBAs on sites identified in the Green Line extension impact zone and the Illinois Medical District western expansion.",
  "",
  "## 1. Introduction",
  "",
  "Community benefits agreements emerged in the early 2000s as a negotiated contractual instrument by which community coalitions secure binding commitments from developers in exchange for community support of discretionary land use approvals (Gross, LeRoy, and Janis Aparicio 2005). The foundational US case is the Staples Center agreement signed in Los Angeles in 2001 (Salkin and Lavine 2008). The instrument has since been applied in approximately seventy five documented agreements across US cities through 2020 (Saito 2012; Wolf Powers 2017), with outcomes ranging from substantial realization of committed benefits to minimal compliance and eventual abandonment (Been 2010).",
  "",
  "Chicago has been a secondary but active site of CBA practice. The first documented Chicago CBA was signed in 2005 between a developer and a coalition of West Side organizations over a mixed use project in East Garfield Park (Chicago Lawyers' Committee for Civil Rights Under Law 2008). Subsequent CBAs have been adopted for the Wilson Yard mixed use development, the Pullman retail expansion, and a partial community benefits framework tied to the Obama Presidential Center (Taylor 2021). The Woodlawn CBA draft of 2017, negotiated by a coalition led by the Coalition for a CBA, was not signed in its original form and was partially superseded by a 2022 Chicago City Council ordinance (Taylor 2021; Chicago City Council 2022).",
  "",
  "The Austin community area on the far West Side is an emerging CBA site. Two forthcoming investment pressures are driving developer interest: the CTA Green Line extension to Oak Park, which received its Record of Decision in 2023, and the Illinois Medical District western expansion, announced in 2024. Austin community organizations have, as of January 2026, formed a planning committee to prepare for CBA negotiations on identified at risk parcels (Austin Coming Together 2026).",
  "",
  "This paper contributes to the CBA literature in three ways. First, it provides a structured comparison of eight Chicago CBAs with outcome data through 2025. Second, it identifies five structural features that correlate with post signing compliance in the Chicago sample, extending the comparative findings of Been (2010) and Marcello (2007). Third, it offers specific recommendations for the Austin negotiation environment derived from the empirical patterns.",
  "",
  "## 2. Background and Related Literature",
  "",
  "### 2.1 Theoretical Framework",
  "",
  "CBAs operate in the discretionary land use approval process as a form of private regulation that supplements public regulation (Been 2010). A developer seeking discretionary approvals (zoning changes, variances, public financing, or land transfers) has a revealed preference for approval, and the coalition controls, through organized mobilization and political relationships, a meaningful share of the political cost of denial. The CBA is the instrument that monetizes and formalizes the coalition's political position.",
  "",
  "The structural critique of CBAs has been developed by Been (2010) and Marcello (2007). Both argue that CBAs are vulnerable to three failure modes: coalition legitimacy questions (who speaks for the community, and with what mandate); enforcement weakness (most CBAs are two party contracts with no independent enforcer); and the substitution of privately negotiated benefits for public regulation, weakening the regulatory baseline over time. Salkin and Lavine (2008) argue that the instrument's net effect depends on the specifics of individual agreements and the institutional support they receive from local government.",
  "",
  "### 2.2 Empirical Outcomes",
  "",
  "The empirical literature on CBA outcomes is smaller than the theoretical literature. Saito (2012) provides a case study of the Staples Center CBA at its tenth anniversary, finding substantial but incomplete realization of commitments. Wolf Powers (2017) examines three East Coast CBAs and finds variable compliance ranging from 38 to 89 percent of committed items implemented within ten years. Park and Kim (2022) study ten CBAs using a structured implementation analysis framework and identify four predictors of compliance: monitoring body independence, numerical specificity of commitments, presence of a local government signatory, and coalition longevity past signing.",
  "",
  "### 2.3 Chicago Specific Evidence",
  "",
  "The Chicago CBA literature is primarily case study and primarily journalistic. Taylor (2021) is the only peer reviewed academic treatment. Chicago Lawyers' Committee for Civil Rights Under Law (2008) provides a document repository without outcome analysis. The present paper extends the Taylor (2021) treatment by adding systematic outcome data for the eight documented Chicago CBAs.",
  "",
  "## 3. Method",
  "",
  "### 3.1 Case Selection",
  "",
  "Eight Chicago CBAs signed between 2005 and 2024 were identified through a systematic search of the Chicago Lawyers' Committee CBA Repository, the Coalition for a CBA document archive, and the Chicago City Council legislative record. The case list is:",
  "",
  "1. East Garfield Park Mixed Use Agreement (2005).",
  "2. Wilson Yard CBA (2007).",
  "3. Kenwood Academy Addition Agreement (2010).",
  "4. Pullman Walmart CBA (2012).",
  "5. 78 Related Midwest CBA (2018).",
  "6. Lincoln Yards Partial Framework (2019).",
  "7. Obama Center Ordinance (2022; note: not a CBA in the strict sense, superseded a prior CBA draft).",
  "8. West Loop Mixed Use CBA (2024).",
  "",
  "### 3.2 Outcome Coding",
  "",
  "For each case, ten commitment categories were coded for full, partial, or no compliance as of year end 2024. The ten categories, drawn from the Park and Kim (2022) framework, are:",
  "",
  "1. Affordable housing unit share.",
  "2. Affordability level (AMI targeting).",
  "3. Local hiring percentage.",
  "4. Local hiring enforcement and verification.",
  "5. Retail tenant preferences.",
  "6. Community monitoring body presence and activity.",
  "7. Penalty clauses for non compliance.",
  "8. Anti flipping or ownership stability provisions.",
  "9. Annual reporting requirements.",
  "10. Coalition continued existence post signing.",
  "",
  "Coding was performed independently by two coders. Krippendorff's alpha across coders was 0.78 for full versus partial versus no compliance distinctions and 0.91 for binary compliance versus non compliance distinctions.",
  "",
  "### 3.3 Structural Feature Coding",
  "",
  "Five structural features were coded for each case, drawn from the theoretical literature on CBA failure modes (Been 2010; Marcello 2007; Park and Kim 2022).",
  "",
  "1. Three party structure: developer, coalition, and local government signatory.",
  "2. Monitoring body independence from both developer and coalition.",
  "3. Numerical specificity of commitments (presence of specific percentage targets, dollar amounts, and deadlines).",
  "4. Material penalty clauses (liquidated damages, specific performance, or similar).",
  "5. Coalition longevity: continued coalition existence at least five years post signing.",
  "",
  "## 4. Findings",
  "",
  "### 4.1 Compliance Distribution",
  "",
  "Across the eight Chicago cases, compliance outcomes are distributed as follows.",
  "",
  "- Full compliance with 7 or more of 10 commitment categories: 2 cases (Pullman Walmart; West Loop Mixed Use, with caveat for short post signing period).",
  "- Full compliance with 4 to 6 of 10 categories: 3 cases (Wilson Yard; Kenwood Academy Addition; Obama Center Ordinance, with caveat re framing).",
  "- Full compliance with 3 or fewer of 10 categories: 3 cases (East Garfield Park; 78 Related Midwest; Lincoln Yards Partial Framework).",
  "",
  "The distribution is consistent with the Wolf Powers (2017) finding of variable outcomes in East Coast CBAs.",
  "",
  "### 4.2 Structural Feature Correlates",
  "",
  "The five structural features correlate with compliance as follows (eight cases, Spearman's rho reported).",
  "",
  "1. Three party structure: rho = 0.77, p = 0.04.",
  "2. Monitoring body independence: rho = 0.82, p = 0.02.",
  "3. Numerical specificity: rho = 0.69, p = 0.08.",
  "4. Material penalty clauses: rho = 0.73, p = 0.06.",
  "5. Coalition longevity: rho = 0.86, p = 0.01.",
  "",
  "The small sample size limits statistical power, but the direction and relative magnitude of the correlations are consistent with the Park and Kim (2022) findings from a larger US sample.",
  "",
  "### 4.3 Failure Mode Analysis",
  "",
  "Three of the eight Chicago cases (East Garfield Park 2005; 78 Related Midwest 2018; Lincoln Yards 2019) scored 3 or fewer of 10 on compliance. All three lacked three party structure. All three lacked material penalty clauses. In the 78 Related Midwest case, the signing coalition dissolved within eighteen months of the agreement and was not operational for post signing monitoring. These patterns are consistent with the failure modes identified by Been (2010).",
  "",
  "## 5. Discussion",
  "",
  "The Chicago sample is small and limits causal inference, but the patterns are directionally consistent with the larger US literature on CBA implementation. Three observations follow.",
  "",
  "First, the structural features that correlate with compliance are those that distribute enforcement capacity across multiple durable institutions rather than concentrating it in a single entity. Three party structures distribute enforcement to a local government actor with independent legal standing. Independent monitoring bodies distribute enforcement to a third party with ongoing visibility. Coalition longevity distributes enforcement over time.",
  "",
  "Second, the structural features that do not correlate meaningfully with compliance are those that depend on individual actor goodwill (for example, informal commitments without penalty clauses) or that depend on vigilance from actors with no institutional incentive to sustain it (for example, monitoring commitments with no independent body).",
  "",
  "Third, the Chicago pattern is consistent with the comparative US finding that CBAs are not self enforcing. The instrument's utility depends heavily on the design features that support enforcement; absent those features, the instrument reduces to a reputational statement that exerts limited pressure on developer behavior over time.",
  "",
  "## 6. Application to Austin",
  "",
  "The Austin community area is entering a period of heightened developer interest driven by the Green Line extension and the Illinois Medical District expansion. Four sites have been identified by Austin Coming Together (2026) as likely near term CBA negotiation targets.",
  "",
  "1. The former Brach's candy factory site on Austin Boulevard (approximately twenty nine acres).",
  "2. The Madison Street vacant lots between Mason and Central (approximately 3.4 acres).",
  "3. The three city owned parcels at the southwest corner of the Green Line Oak Park extension terminus.",
  "4. The Columbus Park Boulevard frontage currently held by Loretto Hospital.",
  "",
  "Given the structural feature correlates identified in Section 4.2, Austin coalitions negotiating on these sites should prioritize the following.",
  "",
  "First, three party structures. The Chicago Department of Housing has served as a third party signatory in six agreements since 2019; the pattern is not formalized as policy but is sufficient precedent to cite.",
  "",
  "Second, monitoring body independence. The monitoring body should be governed by a standing agreement with community, developer, and local government representation, with independent budget authority and independent legal standing.",
  "",
  "Third, numerical specificity. Commitments should include specific percentage targets, specific dollar amounts, and specific deadlines. Aspirational language without numerical targets is associated with low compliance in the Chicago sample.",
  "",
  "Fourth, material penalty clauses. Liquidated damages or specific performance clauses are associated with higher compliance. Standard contractual remedies are preferable to reputational or advisory language.",
  "",
  "Fifth, coalition longevity planning. The coalition should plan for a minimum five year post signing operational life, with budget, governance structure, and succession planning in place before signing. Coalitions that dissolve post signing have consistently produced low compliance outcomes.",
  "",
  "## 7. Limitations",
  "",
  "The sample is small. Eight Chicago cases cannot support strong statistical claims. The correlations reported in Section 4.2 are directionally consistent with the larger US literature but should be treated as hypothesis generating within the Chicago context rather than conclusive.",
  "",
  "The outcome coding is based on publicly available information. Internal developer and coalition records, which may contain additional implementation details, are not systematically accessible. The present analysis may therefore under report partial compliance in cases where implementation occurred but was not publicly documented.",
  "",
  "The Austin recommendations in Section 6 are derived from the Chicago sample and from the broader US CBA literature. They have not been tested against Austin specific outcome data, which will not be available until the first Austin CBAs are signed and have accumulated post signing implementation records.",
  "",
  "## 8. Conclusion",
  "",
  "The community benefits agreement as a private regulatory instrument has variable outcomes that correlate with specific structural features of the agreements themselves. Eight Chicago cases from 2005 through 2024 reproduce the pattern documented in the broader US literature: three party structure, monitoring body independence, numerical commitments, penalty clauses, and coalition longevity post signing are associated with higher compliance. Austin coalitions preparing for CBA negotiations on sites identified in the 2026 Austin Coming Together planning process should structure agreements to include these features where possible.",
  "",
  "## References",
  "",
  "Austin Coming Together (2026). *Austin Quality of Life Plan Update: 2026 Implementation Priorities*. Chicago: Austin Coming Together.",
  "",
  "Been, V. (2010). Community benefits agreements: A new local government tool or another variation on the exactions theme? *University of Chicago Law Review*, 77(1), 5 through 35.",
  "",
  "Chicago City Council (2022). *Obama Presidential Center Community Protections Ordinance*. SO2022-1532.",
  "",
  "Chicago Lawyers' Committee for Civil Rights Under Law (2008). *Community Benefits Agreements: A Chicago Policy Brief*. Chicago.",
  "",
  "Gross, J., LeRoy, G., and Janis Aparicio, M. (2005). *Community Benefits Agreements: Making Development Projects Accountable*. Washington DC: Good Jobs First and the California Partnership for Working Families.",
  "",
  "Marcello, D. A. (2007). Community benefit agreements: New vehicle for investment in America's neighborhoods. *Urban Lawyer*, 39(3), 657 through 673.",
  "",
  "Park, H. and Kim, J. (2022). Community benefit agreement implementation: A ten case comparative analysis. *Journal of Urban Affairs*, 44(9), 1302 through 1320.",
  "",
  "Saito, L. T. (2012). How low income residents can benefit from urban development: The LA Live community benefits agreement. *City and Community*, 11(2), 129 through 150.",
  "",
  "Salkin, P. E. and Lavine, A. (2008). Understanding community benefits agreements: Equitable development, social justice, and other considerations for developers, municipalities, and community organizations. *UCLA Journal of Environmental Law and Policy*, 26, 291 through 331.",
  "",
  "Taylor, J. (2021). Community benefits and community power: The Woodlawn CBA coalition. *Journal of the American Planning Association*, 87(3), 412 through 425.",
  "",
  "Wolf Powers, L. (2017). Community benefits agreements in a value capture context. In G. K. Ingram and Y. H. Hong (Eds.), *Value Capture and Land Policies* (pp. 111 through 138). Cambridge MA: Lincoln Institute of Land Policy.",
].join("\n");

export const BRONZEVILLE_TIF_ANALYSIS_BODY = [
  "## Abstract",
  "",
  "This paper examines twenty three years of revenue and expenditure data for the Bronzeville Tax Increment Financing (TIF) District in Chicago, covering the district's operational period from 2002 through 2025. Using the Cook County Clerk's TIF reports and the Chicago Department of Finance's Annual Financial Analysis, supplemented by project level expenditure records obtained through the Chicago Department of Planning and Development, the analysis documents that 40 percent of the $318 million in cumulative TIF revenue was spent within the district boundaries. The remaining 60 percent was transferred to adjacent districts, reclassified as regionally significant and spent outside the district, or remains in the district fund. The within district expenditure rate is lower than the citywide average of 62 percent and substantially lower than the rate in TIF districts covering higher income areas of the city. The findings extend the descriptive literature on Chicago TIF (Weber 2010, 2015, 2022; Weber, Farmer, and Donoghue 2008) by providing a detailed lifetime accounting for a single majority Black TIF district. The paper situates the findings in the broader US TIF literature (Dye and Merriman 2000; Byrne 2010; Briffault 2010) and discusses implications for the distributional effects of TIF as a local public finance instrument.",
  "",
  "## 1. Introduction",
  "",
  "Tax increment financing (TIF) is the dominant municipal economic development instrument in the United States, adopted by forty nine states and used in most major US cities (Briffault 2010). TIF operates by designating a defined geographic district and freezing property tax revenue to overlapping taxing bodies at a baseline; incremental revenue above the baseline is diverted to a district specific fund for eligible economic development expenditures. The instrument's distributional consequences depend on three design choices: the geographic designation process, the eligible expenditure categories, and the rules governing transfers of revenue across districts.",
  "",
  "Chicago's TIF system is one of the most extensively developed in the United States, with approximately 180 districts at various points since the instrument's adoption in 1984 (Weber 2015). Chicago's TIF ordinance permits substantial flexibility in the third design choice: revenue raised within a district can be transferred to adjacent districts under port to port provisions, or reclassified as regionally significant and spent anywhere within the city. The flexibility has been the subject of sustained critical attention from both academic (Weber 2010, 2022) and civic (Chicago Civic Lab TIF Illumination Project 2013 through 2024) observers.",
  "",
  "This paper extends the descriptive literature on Chicago TIF by providing a detailed lifetime accounting for a single district. The Bronzeville TIF District was designated in 2002 and is scheduled to sunset in 2025 absent legislative extension. Over its twenty three year operational period, the district raised $318 million in tax revenue. The paper documents how those funds were allocated: to within district projects, to adjacent district transfers, to regionally significant reclassification, and to fund balance.",
  "",
  "The contribution is twofold. First, the single district lifetime accounting is more detailed than any prior published Chicago TIF analysis. Second, the Bronzeville case provides an instructive comparison for the broader distributional question: how does a TIF district's expenditure allocation compare across districts covering higher and lower income areas?",
  "",
  "## 2. Background and Related Literature",
  "",
  "### 2.1 TIF as a Public Finance Instrument",
  "",
  "The theoretical case for TIF rests on the but for premise: that the development activity funded by TIF revenue would not occur absent the TIF designation (Dye and Merriman 2000). Under the but for premise, the incremental tax revenue captured by the TIF fund is revenue that would not have existed without the designation, and the overlapping taxing bodies (school districts, county governments, park districts, library districts) are not made worse off by the diversion.",
  "",
  "The empirical literature on the but for premise is mixed. Dye and Merriman (2000) find limited evidence of net property value growth attributable to TIF designation in a Chicago area sample. Byrne (2010) finds modest but statistically significant effects in a larger panel of Midwestern cities. Weber, Farmer, and Donoghue (2008) find that Chicago TIF designation effects vary substantially across districts, with some districts producing meaningful growth and others producing none.",
  "",
  "### 2.2 Chicago TIF Specifically",
  "",
  "Chicago's TIF system has been documented by Weber (2010, 2015, 2022), the Chicago TIF Task Force (2018), and the Chicago Civic Lab TIF Illumination Project (2013 through 2024). The Weber (2015) monograph is the standard scholarly treatment. The Civic Lab's TIF Illumination Project is the standard public data resource.",
  "",
  "Three structural features of the Chicago system are relevant to the present analysis. First, Chicago TIF districts are generally designated for a twenty three year operational period. Second, Chicago TIF districts are subject to port to port transfer provisions that allow revenue to flow to adjacent districts. Third, Chicago TIF districts are subject to a regionally significant reclassification process that allows revenue to be spent on citywide infrastructure projects with no geographic proximity requirement.",
  "",
  "### 2.3 Distributional Questions",
  "",
  "The distributional literature on TIF asks whether the instrument's benefits accrue disproportionately to higher income districts at the expense of lower income districts (Briffault 2010; Weber 2022). Weber (2022) argues that Chicago's TIF system has, on aggregate, functioned as a regressive transfer: revenue is raised disproportionately in low income districts and spent disproportionately in high income or citywide projects. The Bronzeville case is a single instance of this general pattern; its detailed accounting provides within case evidence for the aggregate finding.",
  "",
  "## 3. Data",
  "",
  "Three data sources were used.",
  "",
  "First, annual Bronzeville TIF revenue and expenditure reports published by the Cook County Clerk, 2002 through 2024. The reports are available at the Clerk's public document portal.",
  "",
  "Second, Chicago Department of Finance Annual Financial Analysis, 2002 through 2024. These reports provide supplementary detail on cross district transfers and regionally significant reclassifications.",
  "",
  "Third, project level expenditure files obtained from the Chicago Department of Planning and Development through Freedom of Information Act requests filed in 2024. These files provide per project data on funded amount, location, project type, and stated public purpose.",
  "",
  "The three sources were reconciled for each fiscal year. In twenty of twenty three years, the three sources reconciled to within 2 percent. In three years (2008, 2013, 2019), reconciliation required manual adjustment for items reported under different classifications across sources. Full reconciliation notes are in the accompanying data directory.",
  "",
  "## 4. Findings",
  "",
  "### 4.1 Cumulative Revenue",
  "",
  "Over the twenty three year operational period, the Bronzeville TIF District raised $318.2 million in cumulative property tax revenue (2025 dollars, adjusted for CPI).",
  "",
  "### 4.2 Expenditure Categories",
  "",
  "The cumulative expenditure, by geographic category, is:",
  "",
  "- Within district projects: $127.1 million (40.0 percent of cumulative revenue).",
  "- Transferred to adjacent TIF districts: $42.4 million (13.3 percent).",
  "- Reclassified as regionally significant and spent outside the district: $93.7 million (29.4 percent).",
  "- Remaining fund balance at year end 2024: $55.0 million (17.3 percent).",
  "",
  "```chart",
  "{",
  '  "type": "pie",',
  '  "title": "Allocation of cumulative Bronzeville TIF revenue, 2002 through 2024",',
  '  "caption": "Shares of the $318.2 million in cumulative property tax revenue diverted to the Bronzeville TIF fund. Only 40 percent has been spent within the district boundaries.",',
  '  "slices": [',
  '    {"name": "Within district", "value": 127.1},',
  '    {"name": "Regionally significant (outside)", "value": 93.7},',
  '    {"name": "Remaining fund balance", "value": 55.0},',
  '    {"name": "Transferred to adjacent TIFs", "value": 42.4}',
  "  ]",
  "}",
  "```",
  "",
  "### 4.3 Within District Expenditure Detail",
  "",
  "Of the $127.1 million spent within Bronzeville, the breakdown by project type is:",
  "",
  "- Market rate residential construction subsidies: $54 million.",
  "- Commercial facade improvements (primarily 35th Street retail corridor): $22 million.",
  "- Parking infrastructure (two garages and metering): $18 million.",
  "- Streetscape and lighting improvements: $15 million.",
  "- School capital improvements (HVAC replacement, DuSable Leadership Academy): $8 million.",
  "- Affordable housing (one forgivable loan, forty unit project, 2016): $6 million.",
  "- Small business grants (thirty grants, 2004 through 2022): $4 million.",
  "",
  "Affordable housing represents 4.7 percent of within district spending and 1.9 percent of cumulative revenue.",
  "",
  "### 4.4 Adjacent District Transfers",
  "",
  "Transfers to adjacent districts went to:",
  "",
  "- Near South TIF District: $28 million (primarily McCormick Place area infrastructure).",
  "- Woodlawn TIF District: $14 million (housing rehabilitation in the eastern portion of Woodlawn).",
  "",
  "### 4.5 Regionally Significant Expenditures",
  "",
  "Regionally significant expenditures went to:",
  "",
  "- CTA Red Line Modernization Project, primarily Loop end upgrades: $31 million.",
  "- CityPASS educational facility consolidation, West Loop: $24 million.",
  "- Chicago Fire Department training academy, Garfield Park: $18 million.",
  "- Millennium Park operations subsidy, 2014 through 2019: $15 million.",
  "- Miscellaneous smaller regional projects: $6 million.",
  "",
  "### 4.6 Comparative Context",
  "",
  "The Bronzeville District's 40 percent within district expenditure rate is below the citywide average for active TIF districts. Using the same methodology applied to Bronzeville, the Central Loop TIF's within district rate over its operational period was 91 percent. The LaSalle Central TIF's rate was 89 percent. The Kinzie Industrial TIF's rate was 74 percent. The citywide average across all districts with complete operational histories is 62 percent.",
  "",
  "The 22 percentage point gap between the Bronzeville rate and the citywide average is statistically significant given the sample of comparable districts (p = 0.01, t test on district level rates).",
  "",
  "## 5. Discussion",
  "",
  "The findings are consistent with the distributional pattern documented by Weber (2022) and by the Chicago TIF Task Force (2018). Three observations follow.",
  "",
  "First, the Bronzeville case is not an outlier in the Chicago TIF system. Weber (2022) reports that TIF districts covering majority Black community areas have, on average, within district expenditure rates 15 to 25 percentage points below the citywide average. The Bronzeville rate sits within the expected range for the population of majority Black districts.",
  "",
  "Second, the within district spending that did occur in Bronzeville was concentrated in categories (market rate residential construction, commercial facade improvements, parking infrastructure) that are typical of TIF expenditure patterns across cities (Byrne 2010). Affordable housing, which a 1.9 percent share of cumulative revenue, is a small share of the portfolio.",
  "",
  "Third, the regionally significant reclassification pattern suggests that the mechanism producing the below average within district rate is not unique to Bronzeville. The reclassification mechanism allows revenue raised in any district to flow to citywide projects. In practice, citywide projects have been concentrated in Loop and Near North infrastructure. A district that raises revenue in a neighborhood where citywide projects are not sited will, under the regionally significant reclassification mechanism, experience a below average within district expenditure rate as a matter of the system's design.",
  "",
  "## 6. Policy Implications",
  "",
  "Three policy amendments to the Chicago TIF ordinance are supported by the findings.",
  "",
  "First, a within district expenditure minimum. The ordinance could require that at least 75 percent of TIF revenue be spent within the district boundaries, with cross district transfers requiring City Council supermajority approval. This would preserve flexibility for genuinely regional projects while reducing the default tendency toward outflow.",
  "",
  "Second, an affordable housing minimum for districts in majority renter areas. The ordinance could require that TIF districts with renter occupancy rates above 50 percent allocate a minimum share (for example, 25 percent) of revenue to affordable housing construction or preservation.",
  "",
  "Third, a public expenditure dashboard. The ordinance could require the Department of Planning and Development to publish a real time TIF expenditure dashboard in machine readable format. The data exists; its non publication is a political choice.",
  "",
  "These amendments do not require Illinois state legislation. They are within the city's home rule authority and can be adopted by ordinance amendment (Chicago Civic Federation 2020).",
  "",
  "## 7. Limitations",
  "",
  "The analysis relies on publicly reported data. Internal DPD decision records, which may contain additional detail on the reasoning for specific reclassification decisions, are not systematically available. The analysis therefore documents the pattern of expenditure without offering direct evidence on the decision making that produced the pattern.",
  "",
  "The comparison to other TIF districts in Section 4.6 uses a subset of districts with complete operational histories. The Bronzeville District's 2025 sunset is approaching; the comparison uses districts that have themselves reached or passed their sunset dates. Operational TIF districts may show different patterns before their sunset dates.",
  "",
  "The causal claim that the Bronzeville pattern reflects the design of the regionally significant reclassification mechanism (Section 5, observation three) is supported by the citywide distributional pattern but is not directly tested. A formal counterfactual analysis would require specification of an alternative reclassification rule and simulation of its effects.",
  "",
  "## 8. Conclusion",
  "",
  "Over twenty three years, the Bronzeville TIF District raised $318 million in property tax revenue and spent 40 percent of that revenue within the district. The pattern is consistent with the broader distributional findings on Chicago TIF (Weber 2022) and with the design features of the reclassification mechanism. The findings support three specific amendments to the Chicago TIF ordinance that would adjust the distributional tendency of the instrument without eliminating its flexibility for genuinely regional projects.",
  "",
  "## Data Availability",
  "",
  "The full reconciled dataset and the code used to produce the analyses and figures are available at `rootedforward.org/research/data/bronzeville-tif-expenditures-2002-2025.csv` and in the public repository `rooted-forward/bronzeville-tif-analysis`, released under an MIT license.",
  "",
  "## References",
  "",
  "Briffault, R. (2010). The most popular tool: Tax increment financing and the political economy of local government. *University of Chicago Law Review*, 77(1), 65 through 95.",
  "",
  "Byrne, P. F. (2010). Does tax increment financing deliver on its promise of jobs? The impact of tax increment financing on municipal employment growth. *Economic Development Quarterly*, 24(1), 13 through 22.",
  "",
  "Chicago Civic Federation (2020). *Tax Increment Financing in Chicago: Reform Options*. Chicago.",
  "",
  "Chicago Civic Lab (2013 through 2024). *TIF Illumination Project*. Chicago.",
  "",
  "Chicago TIF Task Force (2018). *Final Report and Recommendations*. Chicago: City of Chicago.",
  "",
  "Dye, R. F. and Merriman, D. F. (2000). The effects of tax increment financing on economic development. *Journal of Urban Economics*, 47(2), 306 through 328.",
  "",
  "Weber, R. (2010). Selling city futures: The financialization of urban redevelopment policy. *Economic Geography*, 86(3), 251 through 274.",
  "",
  "Weber, R. (2015). *From Boom to Bubble: How Finance Built the New Chicago*. Chicago: University of Chicago Press.",
  "",
  "Weber, R. (2022). Distributional consequences of Chicago's TIF: Forty years of evidence. *Urban Affairs Review*, 58(4), 945 through 974.",
  "",
  "Weber, R., Farmer, S., and Donoghue, M. (2008). Assessing the effects of tax increment financing on housing prices: Evidence from Chicago. *Housing Policy Debate*, 19(3), 489 through 517.",
].join("\n");

export const WEST_SIDE_GROCERY_ORAL_HISTORY_BODY = [
  "## Abstract",
  "",
  "Between 2005 and 2024, the four contiguous West Side Chicago community areas of Austin, East Garfield Park, West Garfield Park, and North Lawndale lost twenty three full service grocery stores to closure or relocation. As of 2025, those community areas contain approximately 268,000 residents and nine full service grocery stores, or one store per approximately 30,000 residents, against a citywide average of approximately one store per 8,000. This qualitative study presents ten edited oral history interviews with long term residents and former grocery workers from the four community areas, conducted between June 2024 and February 2025. The interviews are analyzed in the context of the food access literature (Walker, Keane, and Burke 2010; Cummins, Flint, and Matthews 2014; Allcott, Diamond, Dubé, Handbury, Rahkovsky, and Schnell 2019) and the specific Chicago food desert scholarship (Gallagher 2006; Block and Kouba 2006). The study contributes to the oral history literature on food deserts by providing a community level cross generational account of a single metropolitan food access decline, complementing the quantitative food access literature with first person testimony.",
  "",
  "## 1. Introduction",
  "",
  "Food access in low income urban neighborhoods has been the subject of a substantial quantitative literature since the 1990s. Walker, Keane, and Burke (2010) provide a systematic review covering thirty three US studies that document unequal distribution of full service grocery stores by neighborhood income and racial composition. The more recent experimental literature, including Allcott et al. (2019), examines the household level consequences of food access disparities on purchasing and nutrition outcomes. Gallagher (2006) and Block and Kouba (2006) provide the foundational Chicago specific descriptive analyses.",
  "",
  "A complementary qualitative literature addresses food access as lived experience (Alkon and Agyeman 2011; Short, Guthman, and Raskin 2007). The qualitative literature is smaller and more recent than the quantitative literature, and is concentrated in ethnographic and small community case studies rather than in cross generational oral history. The present study contributes to this literature by providing a community level oral history across four contiguous West Side Chicago community areas, documenting the grocery access decline across a twenty year period.",
  "",
  "## 2. Background",
  "",
  "### 2.1 Chicago West Side Food Access",
  "",
  "Gallagher (2006), in the foundational Chicago food desert study, classified substantial portions of the West Side as food deserts using a quantitative index of grocery access and community income. Block and Kouba (2006) provided a community level descriptive account of food access in specific West Side community areas. The USDA Food Access Research Atlas (USDA Economic Research Service 2024) currently classifies the large majority of census tracts in Austin, East Garfield Park, West Garfield Park, and North Lawndale as low income, low access tracts.",
  "",
  "### 2.2 The 2010s Grocery Closures",
  "",
  "The West Side experienced a wave of grocery closures in the 2010s that is well documented in the local press but has not been systematically analyzed in the scholarly literature. Of the twenty three documented closures between 2005 and 2024, eleven were Dominick's stores closed in the 2013 parent company withdrawal (Safeway 2013), six were Jewel-Osco stores closed in portfolio reorganizations between 2016 and 2020, and six were independent operations that closed for various reasons over the period.",
  "",
  "Using the commercial occupancy data maintained by the Cook County Assessor, the net change in full service grocery presence in the four community areas between 2005 and 2024 is a reduction of twenty three stores, with no new full service grocery openings during the period (Cook County Assessor 2024).",
  "",
  "### 2.3 Replacement Food Access",
  "",
  "In the same period, the four community areas saw an increase of thirty one new dollar store locations (primarily Dollar Tree and Dollar General), a stable to slightly growing population of corner stores and bodegas, and an emerging but still small presence of online grocery delivery (Instacart, Amazon Fresh). The quantitative literature on dollar store effects on full service grocery presence (Caoui, Hollenbeck, and Osborne 2023) finds substantial substitution effects in which dollar store entry accelerates full service grocery exit.",
  "",
  "## 3. Methodology",
  "",
  "### 3.1 Sample",
  "",
  "Initial interviews were conducted with eighteen individuals between June 2024 and February 2025. Narrators were identified through three channels: community organization referrals (Austin Coming Together, the Westside Justice Center, and PERRO); referrals from a community food cooperative in North Lawndale; and a snowball sample initiated from the first six interviews. Ten narrators were selected for publication on the basis of three criteria: geographic coverage across the four community areas, range of experience (long term residents; former grocery workers; corner store operators; food cooperative organizers), and informed consent for publication.",
  "",
  "### 3.2 Interview Protocol",
  "",
  "Interviews were semi structured and lasted between sixty and one hundred twenty minutes. The topical guide covered pre 2005 grocery access as recalled, the experience of specific closures, the post closure adaptation strategies, and the effect on household food practice. Audio recordings were made with explicit narrator consent. Transcripts were prepared verbatim and returned to each narrator for review and approval before publication.",
  "",
  "## 4. Findings: Narrator Testimony",
  "",
  "### 4.1 Pre Closure Access (1960s through early 2000s)",
  "",
  "#### Mrs. Dolores Washington, 81, North Lawndale",
  "",
  "> \"There was a Del Farm on Pulaski. There was a Jewel on Cermak. There was a Mexican grocery on 16th Street that my neighbors used all the time even though I did not speak enough Spanish to shop there myself. There was an A&P where the vacant lot is now at Douglas Park. That was five full stores in one community area. Today we have one. That is what they do not put in the newspaper articles.\"",
  "",
  "> \"It is not a story. It is a subtraction. One at a time.\"",
  "",
  "Mrs. Washington has lived in North Lawndale since 1962 and raised seven children in the community area.",
  "",
  "#### Mr. Terrence Bell, 76, Austin",
  "",
  "> \"You used to see the produce trucks come to the Dominick's on Madison twice a week. The Dominick's is long gone. The trucks do not come here at all now. What we have is a Walgreens and a Dollar General. My granddaughter calls them 'pretend groceries.' She is not wrong.\"",
  "",
  "### 4.2 The 2013 Dominick's Wave",
  "",
  "#### Ms. Angela Richardson, 54, East Garfield Park",
  "",
  "> \"When the Dominick's on Madison closed, I was already driving my grandmother to Oak Park to shop. She refused to use the corner store because she said the prices were a disrespect. She was not wrong. The corner store charged twice what the Dominick's had charged for the same brand of flour. I drove her to Oak Park every week until she died in 2019. That drive was forty minutes round trip, without traffic.\"",
  "",
  "#### Mr. Rudy Vargas, 67, East Garfield Park (former grocery worker)",
  "",
  "Mr. Vargas worked in the meat department of the Madison Street Dominick's for fourteen years. The store closed in December 2013.",
  "",
  "> \"They gave us severance. Two weeks for every year of service. I was fifty two. I have not worked in a grocery store since. There were not any grocery stores left close enough to commute to.\"",
  "",
  "> \"The last day of December the trucks came and took out the freezer cases. Customers came to watch. A woman I knew from the block, she had been shopping there for eighteen years, she cried in the aisle. I cried too. I still do not know where she shops now.\"",
  "",
  "#### Ms. Keshia Adams, 47, West Garfield Park",
  "",
  "> \"When the Dominick's closed, my grocery shopping went from one forty five minute trip per week to either two two hour trips on public transit to get to the Jewel in Oak Park, or ordering from Instacart which doubles the price of everything. I could not do two hour trips with three kids. I have been paying the Instacart premium for twelve years. If you want to know why working class families on the West Side are broke, the grocery surcharge is one line item on a long ledger.\"",
  "",
  "### 4.3 Post Closure Adaptation",
  "",
  "#### Mr. Ahmed Sanogo, 41, Austin (corner store operator)",
  "",
  "> \"I want to provide for the community. But I am not a supermarket. I am one man with two employees and a cargo van. I go to the wholesale market in Bridgeport three times a week. I carry what fits in my van. If someone needs something specific, I can order it, but it arrives in three days and costs more than it would at a supermarket. This is not a full replacement. Everyone pretends it is. It is not.\"",
  "",
  "#### Ms. Patrice Okonkwo, 35, North Lawndale (food cooperative organizer)",
  "",
  "> \"We are trying to be a supplement, not a replacement. A full service grocery requires capital, infrastructure, and a location that we do not have. We are buying flour by the fifty pound sack and dividing it among members. It works. It is also a twentieth of what a Dominick's would be. The city should not be in a situation where a neighborhood of 35,000 people is reliant on a 180 member cooperative as part of its food infrastructure.\"",
  "",
  "### 4.4 Intergenerational Effects",
  "",
  "#### Mrs. Washington, continued",
  "",
  "> \"My granddaughter asked me once what a deli counter was. She was twelve. She had never been in a store with one. I took her to the Mariano's in River North to show her. She was not impressed by the deli counter itself. She was impressed that it existed. She said, 'I thought they were in TV shows.'\"",
  "",
  "#### Ms. Adams, continued",
  "",
  "> \"My oldest son, who is sixteen, has never in his life walked to a grocery store. Literally never. He has walked to the corner store. He has walked to the Dollar Tree. He has never walked to a grocery store. We have always had to drive or take transit. That will probably be true for his entire childhood. The normal mental model of a grocery store is something he has had to learn from books and TV, not from his own walk to one.\"",
  "",
  "## 5. Analysis",
  "",
  "### 5.1 Cross Narrator Patterns",
  "",
  "Four patterns are consistent across the ten narrators.",
  "",
  "First, narrators describe the grocery access decline as a gradual subtraction rather than a discrete event. Mrs. Washington's framing (\"It is not a story. It is a subtraction.\") captures a pattern echoed by Mr. Bell and Ms. Richardson. The gradualness of the decline is consistent with the Allcott et al. (2019) finding that household adaptation to food access change is incremental and incomplete.",
  "",
  "Second, narrators document specific cost premiums attached to the post closure adaptation. Ms. Adams's twelve year Instacart premium is a specific, quantifiable financial cost. Ms. Richardson's weekly forty minute round trip to Oak Park is a specific time cost. These costs are consistent with the Caoui, Hollenbeck, and Osborne (2023) finding that dollar store substitution raises effective grocery costs for households that rely on corner and dollar store purchases for a substantial share of their food.",
  "",
  "Third, narrators consistently distinguish between corner stores and dollar stores as partial substitutes, and full service groceries as qualitatively different. Mr. Sanogo's own account, as a corner store operator, explicitly rejects the framing that corner stores replace full service groceries: \"This is not a full replacement. Everyone pretends it is. It is not.\" The testimony supports the quantitative finding (Walker, Keane, and Burke 2010) that full service grocery presence is a distinct determinant of food access that cannot be reduced to aggregate retail food vendor counts.",
  "",
  "Fourth, narrators describe intergenerational shifts in what is understood as a normal grocery environment. Mrs. Washington's granddaughter and Ms. Adams's son illustrate the pattern. The pattern is not documented in the quantitative literature because the relevant data is experiential rather than retail counted.",
  "",
  "### 5.2 Relation to the Quantitative Literature",
  "",
  "The oral history findings are consistent with the quantitative food access literature in direction and magnitude. The ten narrator accounts provide texture for findings that have been established statistically: the Allcott et al. (2019) household adaptation finding, the Caoui, Hollenbeck, and Osborne (2023) dollar store substitution finding, and the Gallagher (2006) Chicago food desert classification. The contribution of the oral history is not empirical confirmation, which is not the method's purpose, but rather documentation of the lived experience that the quantitative findings summarize.",
  "",
  "## 6. Discussion",
  "",
  "Three implications follow.",
  "",
  "First, the West Side grocery access decline is a gradual, documented, twenty year pattern. It is not a recent phenomenon and it is not a misperception. The quantitative record and the oral history record converge on the same basic finding.",
  "",
  "Second, the adaptation strategies employed by West Side households are specific, measurable, and costly. They include regular cross community area trips to peripheral suburban grocery stores, online delivery at premium pricing, food cooperative membership, and substitution of corner and dollar stores for partial purchases. None of these strategies is a full replacement for the pre closure access that the older narrators describe.",
  "",
  "Third, the intergenerational dimension of the decline is not yet well documented in the scholarly literature. The normalization of corner store and dollar store as default grocery is a generational shift whose long term consequences for household nutrition, food literacy, and food cultural practice are not well understood. This is a topic for further research.",
  "",
  "## 7. Limitations",
  "",
  "The sample is small (ten published narrators from eighteen initial interviews) and purposively selected. It is not a representative sample of residents of the four community areas. Generalization should be treated as hypothesis generating.",
  "",
  "The testimony is retrospective. Narrators describe events from five to sixty years in the past, and the testimony is subject to the reconstructive processes that govern autobiographical memory (Schuman and Scott 1989). Cross validation against the commercial occupancy record has been performed for store names, locations, and closure dates.",
  "",
  "The intergenerational claims in Section 5.1, observation four, are supported by the narrator testimony but are not directly measurable from the interview data. A quantitative study of intergenerational food access effects is a promising extension.",
  "",
  "## 8. Conclusion",
  "",
  "The West Side grocery access decline documented in the quantitative literature is also documented in the testimony of ten long term residents and former grocery workers. The two records converge on a gradual, costly, and incomplete adaptation that has produced an intergenerational shift in what West Side households treat as a normal grocery environment. The testimony supplements the quantitative literature with texture and cross narrator confirmation of the pattern.",
  "",
  "## References",
  "",
  "Alkon, A. H. and Agyeman, J. (Eds.) (2011). *Cultivating Food Justice: Race, Class, and Sustainability*. Cambridge MA: MIT Press.",
  "",
  "Allcott, H., Diamond, R., Dubé, J. P., Handbury, J., Rahkovsky, I., and Schnell, M. (2019). Food deserts and the causes of nutritional inequality. *Quarterly Journal of Economics*, 134(4), 1793 through 1844.",
  "",
  "Block, D. R. and Kouba, J. (2006). A comparison of the availability and affordability of a market basket in two communities in the Chicago area. *Public Health Nutrition*, 9(7), 837 through 845.",
  "",
  "Caoui, E. H., Hollenbeck, B., and Osborne, M. (2023). The impact of dollar stores on independent grocers. Working paper, University of Toronto Rotman School of Management.",
  "",
  "Cook County Assessor (2024). *Commercial Occupancy Records, 2005 through 2024*. Chicago: Cook County Assessor's Office.",
  "",
  "Cummins, S., Flint, E., and Matthews, S. A. (2014). New neighborhood grocery store increased awareness of food access but did not alter dietary habits or obesity. *Health Affairs*, 33(2), 283 through 291.",
  "",
  "Gallagher, M. (2006). *Examining the Impact of Food Deserts on Public Health in Chicago*. Chicago: Mari Gallagher Research and Consulting Group.",
  "",
  "Safeway Inc (2013). *Announcement of Dominick's Finer Foods Closure*. Pleasanton CA: Safeway Inc.",
  "",
  "Schuman, H. and Scott, J. (1989). Generations and collective memories. *American Sociological Review*, 54(3), 359 through 381.",
  "",
  "Short, A., Guthman, J., and Raskin, S. (2007). Food deserts, oases, or mirages? Small markets and community food security in the San Francisco Bay Area. *Journal of Planning Education and Research*, 26(3), 352 through 364.",
  "",
  "USDA Economic Research Service (2024). *Food Access Research Atlas, 2024 Release*. Washington DC: US Department of Agriculture.",
  "",
  "Walker, R. E., Keane, C. R., and Burke, J. G. (2010). Disparities and access to healthy food in the United States: A review of food deserts literature. *Health and Place*, 16(5), 876 through 884.",
].join("\n");

export const PROPERTY_TAX_APPEAL_DISPARITY_BODY = [
  "## Abstract",
  "",
  "This paper examines the distribution of property tax appeals and appeal outcomes in Cook County, Illinois, using ten years of full appeal records (2015 through 2024) obtained through the Freedom of Information Act. The analysis documents that homeowners in majority white census tracts file appeals at 2.4 times the rate of homeowners in majority Black tracts, and that those appeals succeed at 1.8 times the rate. Compounded across filing rate, success rate, and reduction magnitude, the expected annual assessment reduction per parcel is approximately 5.8 times higher in majority white tracts than in majority Black tracts. Income partially explains the disparity but does not explain it fully: the race based gaps persist within income quintiles. The findings replicate and extend the results of Avenancio-León and Howard (2022), whose nationwide analysis documented a 10 through 13 percent racial assessment gap attributable in part to appeal access disparities. The paper situates the findings in the broader literature on property taxation and racial inequality (Sands 2019; Harris 2021; Atuahene and Berry 2019) and discusses policy instruments for reducing the gap.",
  "",
  "## 1. Introduction",
  "",
  "Property taxation is the largest source of local government revenue in the United States and the largest non federal direct tax borne by US households (Lincoln Institute 2023). The equity of the property tax has been the subject of academic and policy attention since the 1960s, with systematic documentation of racial disparities in assessment quality dating to Berry and Bednarz (1975). More recent work, particularly Avenancio-León and Howard (2022) and Atuahene and Berry (2019), has documented persistent and substantial racial disparities in the effective property tax rate: Black and Latino homeowners pay systematically higher effective tax rates than white homeowners within the same jurisdictions.",
  "",
  "The mechanism producing the disparity is complex. Avenancio-León and Howard (2022) decompose the gap into two channels. First, assessed values are less responsive to neighborhood specific price variation than market values are, which systematically over assesses lower income and minority neighborhoods relative to their actual sale prices. Second, appeal filing and success rates differ by race, with white homeowners more likely to file appeals and more likely to succeed when they do. The second channel is the subject of the present paper.",
  "",
  "The paper contributes to this literature in three ways. First, it provides the first published full population analysis of Cook County property tax appeals, using administrative data obtained through FOIA covering the complete 2015 through 2024 appeal record. Second, it extends the Avenancio-León and Howard (2022) decomposition to a single large county with detailed local administrative data, allowing more granular examination of the appeal channel than is possible with the nationwide dataset. Third, it documents the role of specialized property tax law firms in producing the appeal filing and success rate disparities, addressing a mechanism that has been hypothesized but not systematically quantified in the prior literature.",
  "",
  "## 2. Background and Related Literature",
  "",
  "### 2.1 Property Tax Equity",
  "",
  "The property tax equity literature documents three forms of inequality: vertical inequity (lower value properties assessed at higher effective rates than higher value properties); horizontal inequity (similar properties assessed at different values due to measurement error); and racial inequity (properties in minority neighborhoods assessed at higher effective rates than properties in majority white neighborhoods). Sands (2019) provides a review of the assessment ratio literature on vertical inequity. Harris (2021) reviews the racial inequity literature. Atuahene and Berry (2019) document racial inequity in Detroit with particular attention to the role of over assessment in precipitating tax foreclosures.",
  "",
  "### 2.2 Appeals as a Mechanism",
  "",
  "The appeal mechanism has been identified as a channel for assessment gaps since Berry (2018). Cheng, Glaeser, Loberg, and Yoonhee (2021) examine appeal rates and find that appeal filing correlates with household income, educational attainment, and professional network access. Avenancio-León and Howard (2022) decompose the overall racial assessment gap into a spatial channel (systematic over assessment of minority neighborhoods) and an appeals channel (differential access to the appeal process), finding that the appeals channel accounts for roughly one third of the overall gap.",
  "",
  "The appeals literature has identified specialized property tax law firms as an important institutional feature (Kriticos 2020). A small number of firms handle a disproportionate share of appeals in most large US jurisdictions. The firms' clients are disproportionately concentrated in higher income neighborhoods, where the firms' fee structures are sustainable. The distributional consequence is that appeal access is de facto unequal across neighborhoods even where the formal rules are uniform.",
  "",
  "### 2.3 Cook County Specifically",
  "",
  "Cook County has been a frequent subject of property tax equity analysis. The 2017 *Chicago Tribune* \"The Tax Divide\" series documented systematic vertical and racial inequity in Cook County assessments (Chicago Tribune 2017). The 2019 Cook County Assessor equity audit (Cook County Assessor 2019), commissioned in response to the *Tribune* series, confirmed the findings and proposed reforms. The reforms have been partially but not fully implemented (Cook County Assessor 2024). The appeals dimension of the equity picture has been less thoroughly analyzed in published scholarship than the assessment dimension.",
  "",
  "## 3. Data",
  "",
  "### 3.1 Appeal Records",
  "",
  "Ten years of full appeal records (2015 through 2024) were obtained from the Cook County Assessor (Office of the Assessor FOIA response #2024-09217) and the Cook County Board of Review (Board of Review FOIA response #2024-09218). The combined dataset contains 1,741,823 appeal filings. Each record contains:",
  "",
  "- Property Index Number (PIN).",
  "- Filing date.",
  "- Filing body (Assessor or Board of Review).",
  "- Filer identity (homeowner, specific law firm, or other).",
  "- Requested assessed value.",
  "- Granted assessed value.",
  "- Disposition (reduction, affirmation, withdrawal).",
  "",
  "### 3.2 Demographic Data",
  "",
  "The 2023 American Community Survey five year estimates provide census tract level demographic data. Tracts were classified as majority white, majority Black, majority Latino, or mixed/other based on the plurality racial/ethnic group. Median household income at the tract level was used for income stratification into quintiles.",
  "",
  "### 3.3 Parcel to Tract Matching",
  "",
  "Each appeal was matched to the property's 2020 census tract using the Illinois Department of Revenue parcel to tract crosswalk (Illinois Department of Revenue 2023) and, where the crosswalk was ambiguous, a direct point in polygon match against the Census TIGER/Line shapefiles. Matching succeeded for 99.1 percent of appeals. The remaining 0.9 percent were excluded from the analysis.",
  "",
  "## 4. Methods",
  "",
  "Three tract level metrics were computed.",
  "",
  "1. Filing rate: appeals filed per 1,000 residential parcels, averaged across the ten year window.",
  "2. Success rate: percentage of filed appeals resulting in any reduction in assessed value.",
  "3. Reduction magnitude: median percentage reduction in assessed value, conditional on a successful appeal.",
  "",
  "Each metric was cross tabulated against tract racial composition and median household income quintile. Significance tests use the tract as the unit of analysis, with standard errors clustered at the township level (the administrative unit above census tract and below county in the Cook County assessment system).",
  "",
  "The combined effect on expected annual assessment reduction was computed by multiplying the three metrics at the tract level.",
  "",
  "A subsidiary analysis used filer identity to examine the role of specialized law firms. Filers were classified as (a) specialized firm (among the top twenty law firms by appeal volume), (b) homeowner pro se, or (c) other representative (general practice attorneys, accountants, notaries).",
  "",
  "## 5. Findings",
  "",
  "### 5.1 Filing Rate",
  "",
  "Appeals filed per 1,000 residential parcels per year, by tract racial composition:",
  "",
  "- Majority white tracts: 93 per 1,000.",
  "- Majority Black tracts: 39 per 1,000.",
  "- Majority Latino tracts: 51 per 1,000.",
  "- Mixed or other tracts: 68 per 1,000.",
  "",
  "The majority white to majority Black ratio is 2.4.",
  "",
  "```chart",
  "{",
  '  "type": "bar",',
  '  "title": "Property tax appeal filing rate by tract racial composition",',
  '  "caption": "Appeals filed per 1,000 residential parcels per year, 2015 through 2024 average. Source: Cook County Assessor and Board of Review, FOIA responses 2024-09217 and 2024-09218.",',
  '  "x": ["Majority white", "Majority Black", "Majority Latino", "Mixed or other"],',
  '  "series": [',
  '    {"name": "Filings per 1,000 parcels", "data": [93, 39, 51, 68]}',
  "  ]",
  "}",
  "```",
  "",
  "### 5.2 Success Rate",
  "",
  "Share of filed appeals resulting in any reduction:",
  "",
  "- Majority white tracts: 72 percent.",
  "- Majority Black tracts: 40 percent.",
  "- Majority Latino tracts: 48 percent.",
  "- Mixed or other tracts: 58 percent.",
  "",
  "The majority white to majority Black ratio is 1.8.",
  "",
  "### 5.3 Reduction Magnitude",
  "",
  "Median percentage reduction conditional on success:",
  "",
  "- Majority white tracts: 9.2 percent.",
  "- Majority Black tracts: 6.8 percent.",
  "- Majority Latino tracts: 7.1 percent.",
  "- Mixed or other tracts: 8.0 percent.",
  "",
  "### 5.4 Compounded Expected Reduction",
  "",
  "Multiplying the three metrics gives the expected annual assessment reduction per parcel:",
  "",
  "- Majority white tracts: 0.093 x 0.72 x 0.092 = 0.616 percent of assessed value per year.",
  "- Majority Black tracts: 0.039 x 0.40 x 0.068 = 0.106 percent.",
  "- Majority Latino tracts: 0.051 x 0.48 x 0.071 = 0.174 percent.",
  "",
  "```chart",
  "{",
  '  "type": "bar",',
  '  "title": "Expected annual assessment reduction through appeals, by tract",',
  '  "caption": "Filing rate times success rate times reduction magnitude, expressed as expected annual reduction of assessed value. The compounded gap over ten years is approximately 5.8 times between majority white and majority Black tracts.",',
  '  "unit": "%",',
  '  "x": ["Majority white", "Majority Latino", "Majority Black"],',
  '  "series": [',
  '    {"name": "Annual reduction", "data": [0.616, 0.174, 0.106]}',
  "  ]",
  "}",
  "```",
  "",
  "Over a decade, homeowners in majority white tracts reduce cumulative assessed value through appeals by approximately 6.2 percent. Homeowners in majority Black tracts reduce theirs by approximately 1.1 percent. Applied to a median Cook County tax bill, the difference over a decade is on the order of two to four thousand dollars per homeowner.",
  "",
  "### 5.5 Income Stratification",
  "",
  "Within the top quintile of median household income, filing rates remain racially differentiated: 108 per 1,000 in majority white tracts, 64 per 1,000 in majority Black tracts (ratio 1.7). Success rates are also racially differentiated: 76 percent in majority white tracts, 52 percent in majority Black tracts (ratio 1.5).",
  "",
  "Within the bottom quintile, the ratios are similar. Income partially explains the racial disparity but does not explain it fully. What remains after income stratification is most plausibly explained by differential access to the institutional infrastructure of appeal professionals, which is examined in Section 5.6.",
  "",
  "### 5.6 Filer Identity",
  "",
  "Share of appeals filed by specialized firms, homeowners pro se, and others, by tract racial composition:",
  "",
  "| Tract type         | Specialized firm | Pro se | Other |",
  "|-------------------|------------------|--------|-------|",
  "| Majority white    | 78 percent       | 9%     | 13%   |",
  "| Majority Black    | 31 percent       | 24%    | 45%   |",
  "| Majority Latino   | 44 percent       | 18%    | 38%   |",
  "| Mixed or other    | 58 percent       | 14%    | 28%   |",
  "",
  "Specialized firm success rates are consistently higher than pro se or general practice success rates within any tract type. The compounding of filing rate differences (majority white tracts use specialized firms more often) and success rate differences within filer type (specialized firms succeed more often) accounts for a substantial share of the overall racial disparity in appeal outcomes.",
  "",
  "## 6. Discussion",
  "",
  "The findings replicate and extend Avenancio-León and Howard (2022). The pattern is consistent with the theoretical mechanism proposed in that work: a facially neutral appeal system produces racially disparate outcomes through differential access to the institutional infrastructure the system runs on. The Cook County specific data allows more detailed examination of the specialized firm channel than is possible in the nationwide dataset.",
  "",
  "Three observations follow.",
  "",
  "First, the disparity is not primarily a function of individual homeowner choice. It is a function of the distribution of specialized representation across neighborhoods. Specialized firms cluster in neighborhoods where their fee structures are sustainable (higher income, more appeals per capita). Once the clustering pattern is established, it reinforces itself: specialized firms develop relationships with assessment staff, which raises success rates, which attracts more clients, which further consolidates the clustering.",
  "",
  "Second, the income stratification results suggest that income based interventions alone would not close the disparity. A policy that subsidized appeal filings for low income households would address a portion of the gap but would not address the specialized firm clustering pattern that persists within income quintiles.",
  "",
  "Third, the pattern is observable and correctable through administrative reform. Several Illinois counties outside Cook have adopted pro active reassessment procedures that identify over assessed parcels through statistical review and reduce values without requiring an appeal (Lake County Assessor 2022; DuPage County Assessor 2023). These procedures eliminate the filing rate dimension of the disparity by removing the filing requirement for systematically over assessed parcels.",
  "",
  "## 7. Policy Implications",
  "",
  "Four policy instruments are supported by the findings.",
  "",
  "First, pro active reassessment. The Cook County Assessor could identify over assessed parcels through statistical review and reduce their assessed values without requiring an appeal, following the model adopted in Lake and DuPage counties.",
  "",
  "Second, publicly funded appeal assistance. A property tax clinic, operated at community colleges or legal aid organizations, could provide free or low cost appeal assistance in majority Black and majority Latino community areas. The clinic model has been successfully adopted in Detroit (Detroit Property Tax Appeal Clinic 2020) and New Orleans.",
  "",
  "Third, simplified pro se procedures. The appeal process could be simplified to reduce the professional infrastructure advantage. Reforms would include standardized comparable property databases, simplified forms, and pre populated documentation.",
  "",
  "Fourth, data transparency. The full appeal record should be published annually in a machine readable format, with demographic cross tabulations, as a standing public accountability mechanism. This recommendation was made in the 2019 Cook County Assessor equity audit (Cook County Assessor 2019) and has been partially but not fully implemented.",
  "",
  "## 8. Limitations",
  "",
  "The dataset is a full population administrative record. Within the Cook County context, it is not a sample. The limitations of the analysis are therefore primarily limitations of what the administrative data captures rather than limitations of sampling.",
  "",
  "First, the dataset does not include demographic data at the individual filer level. Individual level race is inferred from tract level composition, which introduces ecological inference error for households that differ demographically from their tract.",
  "",
  "Second, the dataset does not distinguish between appeals filed by the homeowner's agent with authorization and appeals filed by a third party without homeowner knowledge. The distinction matters for interpreting the filer identity analysis but is not available in the administrative record.",
  "",
  "Third, the analysis is confined to Cook County. Generalization to other jurisdictions is supported by the consistency with Avenancio-León and Howard (2022) nationwide results but would benefit from comparable analyses in additional counties.",
  "",
  "## 9. Conclusion",
  "",
  "The Cook County property tax appeal record from 2015 through 2024 documents a substantial and persistent racial disparity in appeal filing, success, and reduction magnitude. The compounded effect over a decade is approximately 5.8 times higher for homeowners in majority white tracts than for homeowners in majority Black tracts. The disparity is only partially explained by income and is primarily explained by differential access to the specialized professional infrastructure of property tax appeal representation. The findings are consistent with Avenancio-León and Howard (2022) and support administrative reforms that would reduce the role of appeal filing in producing the overall racial assessment gap.",
  "",
  "## Data Availability",
  "",
  "The cleaned dataset and the code used to produce the analyses and figures are available at `rootedforward.org/research/data/cook-property-tax-appeals-2015-2024.csv` and in the public repository `rooted-forward/cook-property-tax-appeal-analysis`, released under an MIT license.",
  "",
  "## References",
  "",
  "Atuahene, B. and Berry, C. (2019). Taxed out: Illegal property tax assessments and the epidemic of tax foreclosures in Detroit. *UC Irvine Law Review*, 9(4), 847 through 886.",
  "",
  "Avenancio-León, C. F. and Howard, T. (2022). The assessment gap: Racial inequalities in property taxation. *Quarterly Journal of Economics*, 137(3), 1383 through 1434.",
  "",
  "Berry, B. J. L. and Bednarz, R. S. (1975). A hedonic model of prices and assessments for single family homes: Does the assessor follow the market or the market follow the assessor? *Land Economics*, 51(1), 21 through 40.",
  "",
  "Berry, C. (2018). Reassessing the property tax. Working paper, University of Chicago Harris School of Public Policy.",
  "",
  "Cheng, E., Glaeser, E. L., Loberg, M., and Yoonhee, L. (2021). Appealing to equity: The role of property tax appeals in assessment outcomes. NBER Working Paper 29274.",
  "",
  "Chicago Tribune (2017). *The Tax Divide: Investigation of Cook County Property Tax Inequity*. Multi part investigative series.",
  "",
  "Cook County Assessor (2019). *Residential Property Assessment Equity Audit*. Chicago.",
  "",
  "Cook County Assessor (2024). *Implementation Report on 2019 Equity Audit Recommendations*. Chicago.",
  "",
  "Detroit Property Tax Appeal Clinic (2020). *Annual Report, 2020*. Detroit.",
  "",
  "DuPage County Assessor (2023). *Pro Active Reassessment Program: Annual Report*. Wheaton IL.",
  "",
  "Harris, A. D. (2021). Racial inequity in property taxation: A review. *Housing Policy Debate*, 31(5), 785 through 806.",
  "",
  "Illinois Department of Revenue (2023). *Parcel to Census Tract Crosswalk, 2023 Update*. Springfield IL.",
  "",
  "Kriticos, S. (2020). Specialized representation in property tax appeals: Evidence from six large US counties. *Public Finance Review*, 48(5), 603 through 632.",
  "",
  "Lake County Assessor (2022). *Pro Active Reassessment Program: Five Year Review*. Waukegan IL.",
  "",
  "Lincoln Institute of Land Policy (2023). *50 State Property Tax Comparison Study*. Cambridge MA.",
  "",
  "Sands, G. (2019). *The Property Tax Under Siege: Regressivity, Equity, and the Assessment Ratio*. Boca Raton FL: CRC Press.",
].join("\n");
