/* ------------------------------------------------------------------ */
/*  research-seed-content-vol4.ts                                      */
/* ------------------------------------------------------------------ */
/*                                                                     */
/*  Multi-city placeholder research bodies.                           */
/*                                                                     */
/*  Rooted Forward's research portfolio covers Chicago, New York,    */
/*  Dallas, and San Francisco. This file holds the long-form bodies  */
/*  for the non-Chicago entries, split out to keep each module       */
/*  navigable.                                                         */
/*                                                                     */
/* ------------------------------------------------------------------ */

export const CROSS_BRONX_EXPRESSWAY_BODY = [
  "Edmundo Martinez has lived on Washington Avenue his entire life. He is sixty-one. The Cross Bronx Expressway was already there when he was born.",
  "",
  "His apartment is on the fourth floor of a six-story walkup, a block and a half from the expressway's eastbound lanes. He has, at my count, four inhalers in rotation. The one in the kitchen is an albuterol rescue; the one by the bed is a maintenance steroid; the two by the front door are backups. He does not apologize for the count. \"If you live here,\" he said, \"this is what you have.\"",
  "",
  "This report is about what Mr. Martinez has. It is also about the 1948 decision that produced it.",
  "",
  "## The 1948 decision",
  "",
  "Robert Moses's Cross Bronx Expressway was not the earliest urban freeway built in the United States. It is the one the profession came to regret first, and the one that a consensus of planning scholarship now treats as the paradigm case of what mid-twentieth-century highway construction did to American cities.[^1]",
  "",
  "The route, as approved by the Triborough Bridge and Tunnel Authority in 1948 and constructed in phases through 1963, cuts a seven-mile trench east-to-west through the South Bronx. It displaced an estimated 61,000 residents — the figure comes from the acquisition files held at the New York City Municipal Archives, not from the 60,000 estimate that circulated in the planning press of the 1950s and that Robert Caro cited in *The Power Broker*. We digitized the parcel-level acquisition records from the Archives in 2024. The 61,340 figure is the count of human beings named on HOLC-category acquisition forms between 1948 and 1955.[^2]",
  "",
  "The racial composition of that displaced population was 72 percent Black, Puerto Rican, or Italian American. The acquisition payments averaged $1,840 per household in 1950s dollars — about $22,000 in 2025 dollars. Renters in the six-flats along the right-of-way, where the density was highest, received the least. Many received nothing at all.",
  "",
  "## What came after the displacement",
  "",
  "The Cross Bronx did not finish its work when the last house fell. It kept working — on population, on property values, on the housing stock that remained, for twenty years.",
  "",
  "Census tracts within a quarter-mile of the trench lost **37 percent** of their population between 1960 and 1980. The adjacent borough as a whole grew two percent over the same period. In constant dollars, median household income in the corridor tracts fell 44 percent; borough-wide it fell six percent. The share of housing stock classified by the 1980 Census as \"deteriorated\" or \"dilapidated\" rose from 14 percent to 51 percent. These are not ambiguous numbers. They describe a neighborhood that lost more than a third of its people in twenty years, and that was coded, by the census enumerator, as visibly wrecked.",
  "",
  "This is the part of the Cross Bronx story that is best known — the fires of the 1970s, the abandonment, the pivot point when \"The Bronx Is Burning\" entered the national lexicon.[^3] We are not retelling it here. We are skipping ahead.",
  "",
  "## What Mr. Martinez's inhalers track",
  "",
  "In April of 2024, the New York Department of Health published tract-level air quality and respiratory hospitalization data for all five boroughs. We merged the release with the New York DOT's acoustic monitoring network — twenty-six continuous microphones installed along the expressway in 2022 — and with the pre-expressway demographic profile we reconstructed from the 1950 and 1960 census microdata.",
  "",
  "The pattern is unambiguous.",
  "",
  "Tracts within a quarter-mile of the trench have 2.1 times the PM2.5 concentration of the Bronx average, and 2.8 times the citywide average. They are in the top three percent of all U.S. census tracts for PM2.5 exposure.[^4] Children under eighteen in those tracts are hospitalized for asthma at 18.4 per 1,000 per year — 2.7 times the citywide rate of 6.7.[^5]",
  "",
  "Overnight traffic noise, measured by the DOT microphones, averages 58 to 62 decibels. The WHO's 2018 environmental-noise guideline for the European region recommends overnight exposures below 40 dB for sleep quality and long-term cardiovascular health.[^6] Sixty decibels is roughly sixteen times the sound energy of forty. That is the number that sits outside Mr. Martinez's bedroom window, eight hours a night, six nights a week. On Sundays the truck traffic is lighter and the number drops to fifty-four.",
  "",
  "These are not downstream effects in the soft sense. They are ongoing, measurable, publicly recorded conditions that affect the people who live next to them every night.",
  "",
  "## The people who live next to them",
  "",
  "A neighborhood tract-level profile, in the aggregate, is not a person. We interviewed eleven residents of the corridor tracts over the spring and summer of 2025, across four extended visits. Their testimony is in an appendix to this report; a few passages are reproduced here, because the numbers above are meaningless without the texture they describe.",
  "",
  "Mrs. Lourdes Santiago, seventy-four, has lived on Morris Avenue for forty-one years. Her granddaughter sleeps in the back bedroom, which faces an interior courtyard. Her grandson sleeps in the front bedroom, which faces the expressway. The grandson uses an inhaler. The granddaughter does not. The two children share most of their genetics and almost all of their diet. The variable that differs between them is which bedroom they sleep in.",
  "",
  "Mr. David Brooks, sixty-seven, is a retired MTA bus driver. He takes a diuretic, a statin, and an ACE inhibitor. He lives on the fifth floor of a building at the corner of Webster and 174th. He has not slept through a full night in four decades.",
  "",
  "> \"People talk about the expressway like it's a thing of the past,\" Mr. Brooks said when I visited him in May. \"It's a thing of right now. Come sit in my apartment for an hour. Come sit here at three in the morning. Tell me if it's the past.\"",
  "",
  "These interviews are not rhetorical embroidery on the data. They are the evidence the data was assembled to support.",
  "",
  "## What is on the table",
  "",
  "The 2021 federal Reconnecting Communities Pilot Program created an explicit authorization for communities to apply for funding to cap, reroute, or dismantle freeways that had split their neighborhoods. The New York DOT's 2016 cost estimate for capping the Cross Bronx was $8 billion to $14 billion. The Bronx Borough President's 2023 counter-proposal — capping a 1.7-mile segment only, at a smaller but still substantial cost of $2.8 billion — is a more immediately feasible version of the same idea.[^7]",
  "",
  "As of April 2025, the Reconnecting Communities funding was under threat. The House Transportation and Infrastructure Committee proposed to rescind \"permanently\" all unobligated funds in the Neighborhood Access and Equity Program, which includes the Cross Bronx cap among seventy-eight awarded projects nationwide.[^8] If the rescission goes through, the Bronx cap goes back to being an idea without a budget.",
  "",
  "We do not take a position here on which intervention — cap, traffic reduction, heavy-duty-fleet electrification, or some combination — best addresses the standing burden documented above. The cost-benefit work that would settle that question has not yet been commissioned in a form rigorous enough to decide between the options. We recommend the New York DOT, the NYC Department of Health, and the Bronx Borough President's office commission such an analysis, drawing on the 2024 health data and the 2022–2024 acoustic monitoring record.",
  "",
  "What we do take a position on is the standing nature of the burden itself. The PM2.5 number is not falling. The asthma hospitalization rate is not falling. The overnight decibel reading is not falling. These conditions are the continuing present tense of a 1948 decision that the planning profession has, in every other respect, moved past.",
  "",
  "## What is in the air, at three in the morning",
  "",
  "Mr. Brooks keeps his windows shut year-round. He installed a second-layer storm window over each one in 2011. He has a HEPA filter in the living room. He replaces the filter every four months, and the dust on the prefilter comes off black.",
  "",
  "He does not own the building. He cannot cap the trench. He cannot reroute the fleet.",
  "",
  "What he can do is keep a log, which he has, and which he showed me. It runs from 1984 to the present. He has recorded his peak-flow meter readings at seven in the morning and eleven at night, every day, on a spiral-bound notebook. The readings on weekends are higher.",
  "",
  "The lesson of the Cross Bronx, in 2026, is not a lesson about mid-century planning. It is that a 1948 planning decision is in Mr. Brooks's lungs, and in his log, and in the prefilter in his living room, every night. It is the overnight reading from the microphone at Webster and 174th. It is the 18.4 per 1,000 that appears in the Department of Health's tract-level tables. It is what is on the table when the Reconnecting Communities rescission comes up for a vote.",
  "",
  "The question the House committee will answer on April 30 is not, as their markup agenda frames it, a question about deficit reduction. It is a question about whether the cost of a 1948 decision is a cost this country intends to continue paying.",
  "",
  "---",
  "",
  "*Interviews conducted in the Morris Heights, East Tremont, and Tremont tracts between March and August of 2025. Eleven narrators; all consented to the use of their names and quotations. Full transcripts are available in the accompanying appendix.*",
].join("\n");

export const FILLMORE_REDEVELOPMENT_BODY = [
  "Lynette Mackey's family was displaced from their two homes in the Fillmore in 1975. She was fifteen. The homes were taken by eminent domain and the family was paid $28,000 for the two of them combined. Eighteen people had lived in those two homes.",
  "",
  "She showed me the certificate of preference she received in 2009 in lieu of the homes. It is a single sheet of paper. It is not a house. It confers priority access to subsidized rental units that come available in the Fillmore and Western Addition. As of her seventy-fifth birthday this year, the certificate has not produced a unit.",
  "",
  "Forty-eight years after the demolition, Ms. Mackey has a piece of paper. Her cousins have three houses in Antioch. Two of her aunts have died.",
  "",
  "## What was there",
  "",
  "The San Francisco Redevelopment Agency (SFRA) began acquiring property in the Western Addition in 1948 and completed its Fillmore-area demolitions in 1973. Over that quarter-century the Agency cleared approximately sixty square blocks and displaced an estimated 20,000 residents. The displaced population was predominantly Black, Japanese American, and Filipino. The Fillmore before the demolition had, by the SFRA's own 1947 survey count, 386 Black-owned businesses along the Fillmore Street commercial strip and between fourteen and nineteen functioning jazz venues, depending on which year of the survey you use.[^1]",
  "",
  "The neighborhood was called, in the San Francisco press of the 1940s, \"the Harlem of the West.\" This was not entirely a compliment; it was also a marker for the class of neighborhood the SFRA was, at the same time, coding as \"blighted.\"",
  "",
  "The Western Addition A-1 project, completed in phases between 1949 and 1960, demolished twenty-eight square blocks. The A-2 project, which began in 1964 and wound down in 1973, demolished another thirty-two. Mackey's family was displaced in the late-A-2 phase. The acquisition payments to displaced households averaged $3,200 in 1960s dollars — about $28,000 today, which is why her family check looks like that.",
  "",
  "The return rate, measured as families who made it back to the rebuilt neighborhood within five years of their displacement, was under seven percent. The Agency's own tracking data, released belatedly in 2004 in response to a Freedom of Information request, confirms the figure.[^2]",
  "",
  "## What was built",
  "",
  "Geary Boulevard — the footprint of A-1 — is a six-lane arterial. It is not a neighborhood. It is functional infrastructure. The 38 Geary bus runs along it and is the highest-ridership route in the San Francisco Muni system.",
  "",
  "The central A-2 footprint, along the Fillmore Street corridor, was rebuilt in fragments between 1973 and 1995. Chain tenants dominated the ground-floor retail from the outset. A small number of the original Black-owned businesses, perhaps seventeen by one count, were eventually able to re-establish in the rebuilt blocks. The jazz clubs did not return.",
  "",
  "Japantown Peace Plaza, designed by Yoshiro Taniguchi and completed in 1968, anchors the eastern A-2 footprint. It has a viable Japanese American commercial district around it — roughly six hundred Japanese American residents live in the surrounding tracts today, a fraction of the pre-internment figure but a recognizable community. It is the most successful of the SFRA's rebuilds, and also the smallest.",
  "",
  "The Fillmore Center, a 1,114-unit residential complex completed in 1992, sits on eight blocks of what used to be homes Mackey's aunts lived in. Half the units are reserved for seniors. None were reserved, at the time of construction, for descendants of displaced Fillmore residents. A community proposal to include such a reservation was rejected during the planning period, according to a 1989 memo in the SFRA files.",
  "",
  "The Fillmore Heritage Center, which opened in 2007 with a Yoshi's jazz club as its anchor tenant, closed in 2014 and has cycled through three management structures since. It is, in 2026, essentially vacant.",
  "",
  "## The Certificates of Preference",
  "",
  "The Certificates of Preference program was not on anyone's horizon for the first thirty years after the demolition. It was adopted in 2008, formalizing a partial remedy that community organizations — the Fillmore Heritage Plaza Collective, the Western Addition Community Congress, and the Geneva Towers tenants' association among them — had been demanding for more than two decades.[^3]",
  "",
  "The program issues certificates to verified descendants of SFRA-displaced families. A certificate confers priority in the waiting lists for affordable rental units that come available in the Fillmore and Western Addition. As of August 2025, the San Francisco Mayor's Office of Housing and Community Development reported:",
  "",
  "- **7,400 certificates** issued since the program's inception.",
  "- **2,100 certificate holders** placed in housing under the program.",
  "- **5,300** certificates currently held by families who have not been placed.",
  "- An **estimated 50,000 living descendants** of displaced families are believed to be eligible for certificates. Most have not applied.",
  "",
  "Twenty-one hundred placements against the original twenty thousand displacements is a ratio of a little over ten percent. Depending on how you frame it, that is either a meaningful partial remedy for a population that would otherwise have received nothing, or a rate of return that looks remarkably like the 1970s return rate of under seven percent the SFRA's own data documents.",
  "",
  "> \"A certificate is not a house,\" Ms. Mackey said. \"But it's not nothing. I don't know what to call it. I don't know if there's a word for what it is.\"",
  "",
  "## What the Fillmore tells us",
  "",
  "The lesson is not that redevelopment was a mistake. That conclusion is long settled and has been the consensus position of American planning scholarship since the 1970s.[^4] The lesson is about what happens after the consensus arrives.",
  "",
  "The Fillmore is forty years into a post-demolition period. A compensatory program exists. It is administered by a successor agency — the Office of Community Investment and Infrastructure, which took over most of the SFRA's remaining portfolio when the Agency was formally dissolved in 2012. The program has produced 2,100 placements. It has not produced anything resembling a restored neighborhood.",
  "",
  "The thing that cannot be restored is not the geography. The geography is still there; the buildings on it are different. The thing that cannot be restored is the set of relationships — the friendships between mothers in the same building, the informal credit at the Fillmore Street hardware store, the jazz club that knew which musician had not eaten, the network of people who knew where to find the lawyer who would take a case on contingency. The SFRA did not know how to count those things because the SFRA's surveys were not designed to count them. They were counted, instead, as the \"blight\" the Agency was authorized to clear.",
  "",
  "A certificate of preference, issued forty-eight years after the fact, cannot put you back into a relationship with a mother who has died. It cannot replace the hardware store. It cannot remember the jazz club.",
  "",
  "It can get you into an affordable rental unit in the Fillmore Center. Two thousand one hundred families have done that. It is something.",
  "",
  "## The applicable lesson",
  "",
  "I am writing this report for Rooted Forward, a Chicago-based research organization, and Chicago has its own redevelopment history. The CHA Plan for Transformation demolished 25,000 units of public housing and rebuilt approximately 7,700 as of 2025. The 2013 Chicago Public Schools closures shuttered 49 schools, the largest single closure action in American public education. The Obama Presidential Center is generating rent pressure in a half-mile impact zone that we have documented separately.[^5]",
  "",
  "The Fillmore case matters to Chicago because it tells us what compensation looks like at the forty-year mark. Twenty-one hundred placements against twenty thousand displacements. A certificate, a piece of paper, not a house. An Agency dissolved and replaced by a successor that administers a remedy for a harm the successor did not cause.",
  "",
  "The policy implication we draw is not about Certificates of Preference, which are a known partial instrument. It is that the best time to prevent what happened in the Fillmore is before the demolition. The second-best time is during the demolition. The third-best time is in the first five years after. Forty years after, you are doing damage control with paper.",
  "",
  "## On the archive",
  "",
  "The SFRA's internal records — parcel acquisition forms, resident survey instruments, internal correspondence — are held at the San Francisco Public Library's History Center. They are public, searchable, and freely available. The analogous Chicago archives from the Hyde Park–Kenwood Urban Renewal program are held at the University of Chicago and are not fully public.",
  "",
  "We note this because a fully public archive is not a minor technical matter. It is the precondition for anyone outside the agency — journalist, community organization, descendant — to tell the story the agency chose not to tell about itself. The SFRA archive is what lets me write this paragraph. The analogous Chicago archive is why I cannot write its equivalent.",
  "",
  "---",
  "",
  "*Interviews with Ms. Mackey, Mr. Marvin Ellison, Mrs. Opal Ridley, and four additional narrators were conducted in the Fillmore between April and September of 2025. Full transcripts and the parcel-level acquisition dataset are available in the accompanying appendix.*",
].join("\n");

export const DALLAS_FAIR_PARK_BODY = [
  "There's a happy ending. But we don't start there.",
  "",
  "First we have to get through what happened on the blocks south of Exposition Avenue between 1966 and 1968, which is where the city of Dallas acquired forty-two acres of residential land by condemnation to build a parking lot for the State Fair of Texas. An estimated twelve hundred residents — almost all Black — were displaced. Most of the acquired parcels were never built on for the announced \"park and green space\" purpose. Most of them were paved as surface lots, which they remain, as of the weekend I walked them in October of 2025.[^1]",
  "",
  "## The 1936 predecessor",
  "",
  "The 1966–1968 parking-lot acquisition was not the first time Fair Park grew into a residential neighborhood. It was the second. The first was in 1935 and 1936, in the run-up to the Texas Centennial Exposition, when the city annexed approximately forty-two additional blocks of predominantly Black residential neighborhood immediately south and east of the existing fairgrounds.",
  "",
  "The acquisition used a mixture of condemnation, eminent domain, and informal pressure. An estimated 3,800 residents were displaced. Acquisition payments averaged between $400 and $650 per lot — materially below the comparable price per lot in white residential condemnations during the same period, as documented in the Dallas Historical Society's 2018 compilation of 1930s condemnation records.[^2]",
  "",
  "The displaced residents had almost no housing alternatives. Dallas's racial covenants, enforced by the Dallas Real Estate Board until their formal rescission in 1948 — and informally for another two decades after — restricted Black homebuyers to a small set of neighborhoods south and east of downtown. The displaced households concentrated into the already-overcrowded South Dallas blocks immediately south of the new Fair Park boundaries. Rents rose. Housing stock deteriorated. The boundary of the Fair Park parcel became, over the subsequent thirty years, the boundary of a neighborhood in durable decline.",
  "",
  "## What the numbers look like ninety years later",
  "",
  "As of the 2023 American Community Survey five-year estimates, the census tracts immediately south of the Fair Park fence are in the bottom fifth nationally on the Neighborhood Atlas Area Deprivation Index — a composite score of income, education, housing, and employment developed at the University of Wisconsin that is the standard instrument for comparing neighborhood-level disadvantage across US census geography.[^3]",
  "",
  "They have been in that bottom fifth continuously since the ADI began publishing tract-level scores in 2013.",
  "",
  "A 2017 report by the Foundation for Community Empowerment found that between 1970 and 2013, the number of housing units in Dallas as a whole rose 72 percent. In the census tracts adjacent to Fair Park, over the same period, housing units fell by more than 50 percent. Between 1999 and 2014, city-wide property values rose roughly four times as fast as property values in the tracts adjacent to the park.[^4]",
  "",
  "Those comparisons are the frame that matters. The Fair Park tracts are not \"below average.\" They are the negative image of the rest of the city, which grew and appreciated while they emptied and lost value.",
  "",
  "## The current governance experiment",
  "",
  "In 2019 the City of Dallas handed day-to-day management of Fair Park to **Fair Park First**, a newly-created 501(c)(3) nonprofit with representation from the State Fair of Texas, the City, and a panel of community appointees. The stated rationale was that a nonprofit could bring professional park management expertise and new philanthropic revenue that the City's Parks Department could not match.[^5]",
  "",
  "I reviewed Fair Park First's 2020–2030 master plan in full. It commits the nonprofit to:",
  "",
  "- $500 million in capital investment across the park.",
  "- Substantial expansion of community-accessible programming outside the State Fair's three-week operating window.",
  "- Three new east-side entrances designed to connect the park to surrounding neighborhoods.",
  "- A Community Benefits Agreement with South Dallas and Fair Park community organizations.",
  "",
  "As of the five-year mark in 2024, the plan is tracking behind schedule. Approximately $140 million of the $500 million had been deployed by the end of the reporting year. The Community Benefits Agreement had been drafted but not finalized. The east-side entrances were in design.",
  "",
  "## The accountability question",
  "",
  "Fair Park First is being watched. Houston's Memorial Park Conservancy, the Audubon Commission in New Orleans, and the Piedmont Park Conservancy in Atlanta all run comparable nonprofit governance structures over parks with comparable displacement histories. The operational question is whether the nonprofit model produces materially different outcomes than the pattern of adjacent-neighborhood disinvestment that has accompanied every previous phase of Fair Park's growth.",
  "",
  "The Community Benefits Agreement, if and when it is finalized, should in our view be held to five measurable commitments, each published annually as a machine-readable compliance report:",
  "",
  "1. **Capital investment parity.** The Agreement should establish a target for combined public-and-Fair-Park-First capital investment in the tracts immediately adjacent to the park. A $500 million investment inside the fence alongside a fraction of that amount outside the fence would replicate the ninety-year pattern.",
  "2. **Local hiring.** Fair Park First's current hiring target is 30 percent local. The verifiable rate, in a sample we audited across the first five years of construction contracts, is closer to 11 percent.",
  "3. **Displaced-family governance.** Descendants of the 1936 and 1966–1968 displacements have a standing historical claim on the park's governance. The Agreement should reserve seats for them on either the board or the Community Advisory Committee.",
  "4. **Acquisition non-expansion.** Rising land values around the rebuilt park are already producing speculative investment in the surrounding residential blocks. The Agreement should commit Fair Park First, in writing, to neither support nor coordinate any future expansion of the Fair Park parcel into existing residential blocks.",
  "5. **Revenue transparency.** State Fair of Texas financial reports currently do not separate State Fair of Texas revenue from Fair Park First revenue. The Agreement should require consolidated audited statements, released annually, that allow the public to see how much money flows in and out of the park and its surrounding neighborhoods.",
  "",
  "## What happens in June",
  "",
  "The 2026 FIFA World Cup is bringing games to AT&T Stadium in Arlington, fifteen miles west of Fair Park. The Dallas Convention and Visitors Bureau is marketing Fair Park as a cultural anchor for visiting fans, with tours of the National Historic Landmark Art Deco architecture and evening concerts at the Music Hall. The marketing push is expected to draw significant supplementary foot traffic to the park.",
  "",
  "The accompanying pressure on the surrounding neighborhoods is easy to predict. It is the fifth phase of the same century-long pattern, and the one the Fair Park First model is, by its own stated purpose, supposed to interrupt.",
  "",
  "The question the next twenty-four months will answer is whether the interruption will hold, or whether it will be the fourth consecutive expansion of the park into the neighborhoods that host it.",
  "",
  "## There's a happy ending",
  "",
  "I have promised a happy ending. The ending is this: I am writing this piece, in 2026, in a Dallas where a Community Benefits Agreement exists in draft form, where a nonprofit park governance structure has written promises on paper about things that no comparable structure has ever written about any other Dallas park, and where a panel of descendants of the displaced is at the table for the first time since 1968.",
  "",
  "That panel has not yet gotten what it asked for. It might not get it. But it is at the table. In 1968 there was no table. In 1936 there was no question that there would ever be a table.",
  "",
  "That is not a happy ending in the sense of a settled one. It is a happy ending in the narrow and specific sense that the fight, this time, is being fought in daylight. Whether the fight is won is a question for 2028, when the Agreement comes up for its first compliance review. This report is a contribution to the record that compliance review will consult.",
  "",
  "---",
  "",
  "*Fieldwork conducted in South Dallas and Fair Park between October of 2024 and November of 2025. Eighteen interviews; eleven of them are quoted in the accompanying appendix. Archival research used the Dallas Historical Society, the Dallas Public Library's Texas/Dallas History and Archives Division, and the SMU DeGolyer Library.*",
].join("\n");
