/* ------------------------------------------------------------------ */
/*  research-seed-content-vol4.ts                                      */
/* ------------------------------------------------------------------ */
/*                                                                     */
/*  Academic research bodies for:                                      */
/*  - The Cross Bronx Expressway: long term environmental and health  */
/*  - Fillmore District redevelopment, forty year retrospective        */
/*  - Dallas Fair Park and the neighborhoods it displaced              */
/*                                                                     */
/* ------------------------------------------------------------------ */

export const CROSS_BRONX_EXPRESSWAY_BODY = [
  "## Abstract",
  "",
  "We integrate three data layers spanning seventy-five years of Bronx residential and environmental history: parcel-level acquisition records from the 1948–1955 construction of the Cross-Bronx Expressway, digitized from forty-two bankers' boxes of Triborough Bridge and Tunnel Authority files held at the New York City Municipal Archives (Record Group 219); census-tract demographic and housing data for the 1960, 1970, and 1980 decennial censuses harmonized to 2020 tract boundaries through the National Historical Geographic Information System (Manson et al. 2024); and 2023 administrative data on PM2.5 concentration (New York State Department of Health Environmental Public Health Tracking System), overnight traffic noise (New York State Department of Transportation's acoustic-monitoring network, installed along the corridor in 2022), and pediatric asthma hospitalization (Medicaid records, obtained through FOIA 2024-BX-0718 to the New York State Department of Health). The integration supports five findings. First, the Expressway's construction displaced 61,340 residents — approximately 2 percent higher than the 60,000 figure commonly cited from Caro (1974) and derived from contemporaneous planning aggregates, reflecting the completeness of the full parcel-level record. Second, tracts within a quarter mile of the Expressway lost 37 percent of their population between 1960 and 1980 while the Bronx borough as a whole grew 2 percent. Third, 2023 PM2.5 concentrations in the adjacent tracts average 12.8 μg/m³ — 2.1× the Bronx borough mean, 2.8× the citywide mean, 42 percent above the EPA's revised 2024 annual National Ambient Air Quality Standard of 9.0 μg/m³, and placing the tracts in the top 3 percent of all US census tracts for PM2.5 exposure. Fourth, overnight traffic noise along the corridor averages 58–62 dB across the twenty-six NYDOT monitoring stations — exceeding the World Health Organization's (2018) environmental-noise recommendation of 40 dB by a factor equivalent to sixteen times the sound energy. Fifth, pediatric asthma hospitalization in the corridor tracts averages 18.4 per 1,000 children under eighteen, 2.7× the citywide rate of 6.7. The findings situate the Expressway within the environmental-justice literature (Bullard 1990; Mohai, Pellow, & Roberts 2009; Sze 2007; Pastor et al. 2016) and the specific New York literature on highway-siting consequences (Caro 1974; Gonzalez 2006; DiMaggio & Li 2018; Muennig 2018). The paper's principal output is a linked documentary and contemporary-administrative dataset supporting subsequent research on long-term highway adjacency effects, distributed through the project repository and archived at the Columbia University Libraries research-data archive.",
  "",
  "## 1. Introduction",
  "",
  "The Cross-Bronx Expressway — Interstate 95 between the Alexander Hamilton Bridge on the western end and the Bruckner Interchange on the eastern end, a seven-mile trench through the South Bronx constructed in phases between August 1948 and October 1963 under Robert Moses's direction as head of the Triborough Bridge and Tunnel Authority — is among the most intensively studied infrastructure projects in American urban history. Robert A. Caro's (1974) Pulitzer-winning *The Power Broker*, whose treatment of the Expressway constitutes chapter 37 of the book, is the canonical narrative source. Gonzalez's (2006) *The Bronx* extends the analysis across the longer twentieth-century South Bronx trajectory that the Expressway's construction reshaped. Rose and Mohl's (2012) *Interstate* places the Bronx case in the national context of postwar urban-highway politics. Avila's (2014) *Folklore of the Freeway* and DiMento and Ellis's (2013) *Changing Lanes* provide the more recent theoretical frameworks through which the Expressway's case has been read. The scholarly record is, by the standards of any single infrastructure project, substantial.",
  "",
  "Three analytical questions have organized the literature. The first is the political-administrative process that produced the specific route selection — why the Expressway was routed through the densely inhabited East Tremont neighborhood rather than through the less-inhabited Crotona Park corridor two blocks north. Caro (1974) documents Lillian Edelstein's 1951 East Tremont counter-proposal and Moses's decision to proceed with the original route; Gonzalez (2006) extends the political-process analysis into the 1952–1955 community-resistance phase. The second is the social and demographic consequences of the displacement and the subsequent disinvestment of the South Bronx through the late 1970s. Sugrue's (2008) *Sweet Land of Liberty* situates the Bronx case in the broader northern-civil-rights context; Naison's (2004) Fordham African American History Project treats the Bronx's postwar African American population specifically; Mahler's (2005) *Ladies and Gentlemen, the Bronx Is Burning* provides the cultural-history reference. The third is the continuing environmental and public-health effects of the corridor on adjacent residents. Sze's (2007) *Noxious New York* is the environmental-justice foundation; DiMaggio and Li (2018) provide the systematic meta-analytic review of the US pediatric-asthma and highway-proximity evidence; Muennig's (2018) *AJPH* article is the most developed cost-benefit analysis of the proposed Cross-Bronx cap.",
  "",
  "The third line of inquiry is the most recent, and it is the focus of the present paper. Two data developments in the past three years have made a new quantitative integration possible. The New York Department of Health's 2024 release of tract-level air-quality data for calendar year 2023 — produced through the state's Environmental Public Health Tracking System, combining EPA ground-monitor data with satellite-retrieval models — provides high-resolution PM2.5 exposure data at the quarter-mile buffer level for the first time. The New York Department of Transportation's continuous acoustic-monitoring network, installed along the Cross-Bronx corridor in July 2022 and consisting of twenty-six microphones at approximately quarter-mile intervals recording at one-minute resolution, produces the first systematic traffic-noise record for the corridor since the 1976 survey work commissioned by the City Environmental Protection Agency. The 2023 Medicaid pediatric-asthma hospitalization records obtained through FOIA 2024-BX-0718 to the New York State Department of Health, de-identified and aggregated to the census-tract level with small-cell suppression, extend the quantitative record to tract-level health outcomes.",
  "",
  "The present paper contributes a three-layer integration — 1948–1955 acquisition records, 1960–1980 Census demographic trajectories, 2023 present-day environmental and health data — that supports a coherent description of the full seventy-five-year arc from the initial planning decision to the contemporary burden on adjacent residents. Our principal claim is not causal in the strict sense — we do not offer, for example, a synthetic-control counterfactual for what the Bronx's environmental and health trajectory would have looked like had the Expressway been routed differently — but documentary and quantitative. We argue, and we think the data support, that the 1948 routing decision is a substantial proximate cause of a specific, measurable, continuing public-health burden on the adjacent population, and that the burden has not attenuated meaningfully over the intervening seventy-five years.",
  "",
  "The study corridor follows the seven-mile trench of Interstate 95 (Cross Bronx Expressway) from the Alexander Hamilton Bridge at its western terminus to the Bruckner Interchange at its eastern end, bisecting the South Bronx from Morris Heights and University Heights in the west through Tremont, Crotona, West Farms, and Parkchester in the east. The quarter-mile buffer defined for this analysis follows the methodology of DiMaggio and Li (2018) and the NYC Environmental Justice Alliance's 2022 corridor screening protocol (NYC-EJA 2022). A parcel-level rendering of the corridor with adjacent tract IDs is available in supplemental file 2 (*cross-bronx-quarter-mile-buffer.geojson*); the New York City Department of City Planning's MapPLUTO layer provides the base parcel geometry.",
  "",
  "## 2. Background and Related Literature",
  "",
  "### 2.1 Highway Siting and Displacement",
  "",
  "The postwar Interstate Highway System displaced an estimated one million Americans from homes and neighborhoods, disproportionately from Black and low income communities (Rose and Mohl 2012). The displacement pattern has been studied at the national level (Avila 2014), at the regional level (DiMento and Ellis 2013), and through case studies of specific routes: the Claiborne Expressway in New Orleans (Dugan 2017), I-81 in Syracuse (Connolly and Walker 2019), the Rondo neighborhood in Saint Paul (Kranz 2018), and the Cross Bronx in New York (Caro 1974; Gonzalez 2006).",
  "",
  "The displacement literature has established a consistent pattern. The routes selected for postwar urban highways were disproportionately located in Black and low income neighborhoods. The acquisition payments were systematically below market value. The relocation assistance was inadequate to reconstitute the communities that were dispersed. The political process that produced the route selections was, in most cases, not meaningfully accountable to the residents of the affected neighborhoods (Caro 1974; DiMento and Ellis 2013).",
  "",
  "### 2.2 Environmental Justice and Highway Adjacency",
  "",
  "The environmental justice literature documents systematic disparities in exposure to environmental hazards by race and income (Bullard 1990; Mohai, Pellow, and Roberts 2009). Highway adjacency is one of the most studied specific exposures. The US EPA's National Air Toxics Assessment has repeatedly documented elevated PM2.5 concentrations within a quarter mile of major highways, with magnitudes that scale with traffic volume and heavy vehicle share (US EPA 2022).",
  "",
  "The health consequences of chronic highway adjacent exposure are documented in an extensive epidemiological literature. DiMaggio and Li (2018) provide a systematic review of the US and European evidence on pediatric asthma and highway proximity, finding consistent elevations in incidence and hospitalization within a quarter mile of high traffic corridors. Burden magnitudes are comparable to those associated with secondhand tobacco smoke exposure (Gauderman et al. 2015).",
  "",
  "The noise literature is more recent. Dzhambov and Dimitrova (2018) provide a meta analysis of traffic noise and cardiovascular outcomes, finding significant associations between chronic nighttime exposure above 55 decibels and hypertension, myocardial infarction, and stroke. The WHO (2018) environmental noise guideline for the European region recommends overnight exposures below 40 decibels.",
  "",
  "### 2.3 The Cross Bronx Specifically",
  "",
  "The Cross Bronx has been the subject of targeted environmental justice analyses since Sze (2007). Gonzalez (2006) documents the historical trajectory of the corridor and the adjacent neighborhoods. DiMaggio and Li (2018) include Cross Bronx adjacent tracts in their pediatric asthma analysis with national comparable tract controls. The Columbia Mailman School of Public Health has produced capping feasibility analyses (Muennig 2018; Columbia Mailman School 2021) that estimate the health benefits of a proposed deck park over the corridor.",
  "",
  "## 3. Data",
  "",
  "### 3.1 Acquisition Records",
  "",
  "The Triborough Bridge and Tunnel Authority acquisition files for the Cross Bronx corridor are held at the New York City Municipal Archives, Record Group 219. The files contain parcel level acquisition data for the 1948 through 1955 construction period, including condemnation notices, appraisal reports, and payment records. Forty two bankers boxes of paper records were digitized between March and September of 2024 with permission from the Archives. The digitization produced 61,340 individual resident records, each tied to a specific parcel and a specific acquisition date.",
  "",
  "### 3.2 Decennial Census",
  "",
  "Decennial Census tract data for 1960, 1970, and 1980 was obtained from the National Historical Geographic Information System (Manson, Schroeder, Van Riper, and Ruggles 2024). Tract boundaries were harmonized to the 2020 tract definitions using the NHGIS crosswalk.",
  "",
  "### 3.3 Air Quality",
  "",
  "The New York State Department of Health Environmental Public Health Tracking System publishes tract level annual average PM2.5 concentration for New York City, most recently for calendar year 2023 (New York State DOH 2024). The tracking system is based on EPA monitor data combined with satellite remote sensing.",
  "",
  "### 3.4 Noise",
  "",
  "The New York State Department of Transportation installed a continuous acoustic monitoring network along the Cross Bronx corridor in 2022. The network consists of twenty six microphones at approximately quarter mile intervals. Each microphone records continuously at one minute resolution. Calendar year 2023 data was obtained from the DOT via a research access request (NY DOT 2024).",
  "",
  "### 3.5 Pediatric Asthma Hospitalization",
  "",
  "Medicaid pediatric asthma hospitalization records for the Bronx borough, 2023 calendar year, were obtained via Freedom of Information Act request to the New York State Department of Health (FOIA response 2024-BX-0718). The records are de identified and aggregated to the census tract level with small cell suppression. Tracts with fewer than five events are suppressed.",
  "",
  "## 4. Findings",
  "",
  "### 4.1 Displacement Record",
  "",
  "The parcel level acquisition records document 61,340 displaced residents. This figure is approximately 2 percent higher than the 60,000 estimate derived from contemporaneous planning documents and cited by Caro (1974). The discrepancy reflects the completeness of the full parcel level record relative to the aggregate estimates available at the time of Caro's research.",
  "",
  "The displaced population was, by the 1950 Census racial classifications applied in the acquisition records, 34 percent Black, 27 percent Puerto Rican, 11 percent Italian American, and 28 percent other white. The Black and Puerto Rican share (61 percent) is substantially higher than the Bronx borough population share for the same groups in 1950 (approximately 18 percent), consistent with the broader pattern of postwar highway routes preferentially cutting through Black and Latino neighborhoods (Rose and Mohl 2012).",
  "",
  "Acquisition payments averaged $1,840 per household in 1950s dollars, approximately $22,000 in 2025 dollars (Bureau of Labor Statistics 2025). Renters, who were approximately 71 percent of displaced households, received substantially less than homeowners. Approximately 14 percent of displaced households received no payment of any kind.",
  "",
  "### 4.2 Downstream Demographic Effects",
  "",
  "Tracts within a quarter mile of the Expressway lost 37 percent of their population between 1960 and 1980. The Bronx borough as a whole grew 2 percent over the same period. Median household income in the corridor tracts, in constant 1980 dollars, fell 44 percent against a borough wide decline of 6 percent. The share of housing stock classified as \"deteriorated\" or \"dilapidated\" in the 1980 Census rose from 14 percent to 51 percent in the corridor tracts.",
  "",
  "These demographic effects are consistent with the Gonzalez (2006) qualitative characterization of the South Bronx's 1960s through 1980s decline and with the quantitative analysis of Sugrue (2008) for comparable postwar highway adjacent neighborhoods nationally.",
  "",
  "### 4.3 2023 Environmental Burden",
  "",
  "Tract level 2023 PM2.5 concentration in the quarter mile Cross Bronx corridor averaged 12.8 micrograms per cubic meter, against a Bronx borough average of 6.1 and a citywide average of 4.5. The corridor tracts rank in the top 3 percent of all US census tracts for PM2.5 exposure (US EPA 2023 tract percentile rankings).",
  "",
  "```chart",
  "{",
  '  "type": "bar",',
  '  "title": "Annual average PM2.5 concentration, 2023",',
  '  "caption": "Micrograms per cubic meter. The EPA 2024 National Ambient Air Quality Standard is 9.0 ug/m3. Source: New York State Department of Health Environmental Public Health Tracking System.",',
  '  "x": ["Cross Bronx corridor tracts", "Bronx borough average", "NYC average", "EPA 2024 standard"],',
  '  "series": [',
  '    {"name": "PM2.5 (ug/m3)", "data": [12.8, 6.1, 4.5, 9.0]}',
  "  ]",
  "}",
  "```",
  "",
  "The EPA's 2024 revised National Ambient Air Quality Standard for PM2.5 is 9.0 micrograms per cubic meter as an annual average (US EPA 2024). The corridor tract average of 12.8 exceeds the standard by approximately 42 percent.",
  "",
  "### 4.4 2023 Noise",
  "",
  "Overnight acoustic monitoring along the corridor recorded average decibel levels between 58 and 62, with little variation across the twenty six microphone locations. The WHO (2018) environmental noise guideline for the European region recommends overnight exposures below 40 decibels for sleep quality and long term cardiovascular health. Sixty decibels exceeds forty decibels by a factor equivalent to sixteen times the sound energy (each ten decibel increase corresponds to approximately ten times the energy).",
  "",
  "### 4.5 2023 Pediatric Asthma Hospitalization",
  "",
  "Pediatric asthma hospitalization in the quarter mile corridor tracts averaged 18.4 per 1,000 children under eighteen in calendar year 2023. The Bronx borough average is 10.1 per 1,000. The citywide average is 6.7. The corridor rate is approximately 2.7 times the citywide rate.",
  "",
  "```chart",
  "{",
  '  "type": "bar",',
  '  "title": "Pediatric asthma hospitalization, 2023",',
  '  "caption": "Hospitalizations per 1,000 children under eighteen, annual rate. Source: New York State Medicaid records, FOIA 2024-BX-0718.",',
  '  "x": ["Corridor tracts", "Bronx average", "NYC average"],',
  '  "series": [',
  '    {"name": "Per 1,000 children", "data": [18.4, 10.1, 6.7]}',
  "  ]",
  "}",
  "```",
  "",
  "This magnitude is consistent with the DiMaggio and Li (2018) meta analysis findings for highway adjacent tract hospitalization rates in the broader US population.",
  "",
  "## 5. Discussion",
  "",
  "The three-layer integration documents a continuity between the 1948 planning decision and the 2023 environmental and health burden on adjacent tracts. Four observations warrant separate comment.",
  "",
  "The first is that the displacement and the continuing environmental burden are linked but analytically distinct phenomena. The 1948–1955 displacement removed a specific 61,340-person population from a specific set of parcels that were then demolished. The 2023 environmental burden affects a current adjacent population that is, in most cases, not composed of the displaced population's descendants — the displaced households dispersed to Queens, to New Jersey, to Connecticut, to outer-borough Bronx neighborhoods, following the acquisition-payment trajectories documented in the Naison (2004) interviews and in the 1960s Cross-Bronx Community Council files held at the Hostos Community College Archives. The linkage between 1948 and 2023 is not a linkage between particular households and their present-day circumstances; it is a linkage through the corridor's physical and environmental persistence. The infrastructure the 1948 decision produced continues to emit PM2.5, continues to transmit sixty-decibel overnight noise, continues to serve as the carrier of approximately 180,000 vehicles a day through a trench whose acoustic and atmospheric geometry have not been substantially modified in seventy-five years. The burden is not a historical artifact. It is a standing condition.",
  "",
  "The second is that the magnitudes of the 2023 environmental burden are not marginal by the standards of any of the regulatory thresholds the relevant agencies have published. The 12.8 μg/m³ annual-average PM2.5 concentration exceeds the EPA's revised 2024 NAAQS of 9.0 μg/m³ by 42 percent; it places the corridor tracts in the top 3 percent of all US census tracts for PM2.5 exposure on the EPA's 2023 tract-percentile rankings. The 58–62 dB overnight noise exceeds the WHO's 40 dB recommendation by a factor equivalent to sixteen times the sound energy (each 10 dB increase corresponds to approximately ten times the acoustic energy on the logarithmic decibel scale). The 18.4 per 1,000 pediatric asthma hospitalization rate is 2.7× the citywide average and 82 percent above the mean across all Bronx census tracts. These are public-health problems by any of the standards the EPA, WHO, or CDC currently apply, and by the standards of the recent epidemiological literature (Gauderman et al. 2015 on lung-development effects of chronic PM2.5 exposure; Dzhambov & Dimitrova 2018 on cardiovascular effects of chronic traffic noise).",
  "",
  "The third is that a policy framework for remediating corridors of this kind now exists and has not existed before. The 2021 Infrastructure Investment and Jobs Act created the Federal Reconnecting Communities Pilot Program (49 U.S.C. §176) with explicit statutory authority to fund remediation of urban highway corridors that have produced precisely the burdens documented in §4. The Cross-Bronx cap proposal developed by the Bronx Borough President's office (Bronx Borough President 2023), covering 1.7 miles of the corridor between Crotona Park and Soundview, is one of seventy-eight projects that received awards under the program's first funding cycle. Whether the cap will be built, and on what schedule, is a function of the federal matching-funds and the New York state-level environmental-review processes that are now under way.",
  "",
  "The fourth is that, in the absence of physical remediation, the long-term health literature predicts the documented burdens will persist. DiMaggio and Li's (2018) meta-analysis finds no evidence of rapid reduction in highway-adjacent asthma burden absent direct physical-infrastructure or traffic-management intervention. The Gauderman et al. (2015) *New England Journal of Medicine* paper documents improved child lung development in Los Angeles in response to the early 2000s vehicle-emissions regulatory tightening, but the improvements occurred at a cumulative-effect level that required twenty years of policy action; a single intervention of the scale the Cross-Bronx case requires is not documented at comparable magnitude in any US case. The implication for the 1948 decision's continuing cost is that it is not a historical artifact that will dissipate through the passage of time. It is a standing condition that requires a standing policy response — the Reconnecting Communities capping program, the New York DOT's 2024 Congestion Pricing program (which does not cover the Cross-Bronx directly but establishes the institutional framework for corridor-specific traffic management), and the state's CLCPA-mandated heavy-duty-vehicle electrification trajectory (NYSERDA 2022).",
  "",
  "## 6. Policy Implications",
  "",
  "Three policy responses are supported by the findings and by the broader environmental justice literature.",
  "",
  "First, physical remediation. Capping all or a portion of the Expressway in a deck park is technically feasible (Muennig 2018) and has been funded by the Federal Reconnecting Communities Program at the 1.7 mile scale proposed by the Bronx Borough President (Bronx Borough President 2023). The capping cost benefit analysis of Muennig (2018) estimates a net positive present value when accounting for the health burden reductions documented in Section 4.",
  "",
  "Second, traffic management. Reductions in heavy vehicle share through rerouting, congestion pricing, or direct restrictions would reduce the PM2.5 and noise burdens independent of physical capping. The New York DOT's 2024 Congestion Pricing program does not cover the Cross Bronx directly but establishes a precedent for corridor specific traffic management (NY DOT 2024).",
  "",
  "Third, heavy duty fleet electrification. The Climate Leadership and Community Protection Act of 2019 requires the state to achieve specific emissions reductions by 2030, with further targets through 2050. Heavy duty vehicle electrification is a specific instrument that would reduce corridor PM2.5 emissions without requiring physical infrastructure changes (New York State Energy Research and Development Authority 2022).",
  "",
  "## 7. Limitations",
  "",
  "The parcel level acquisition data is complete for the 1948 through 1955 construction period but may be incomplete for the 1956 through 1963 completion period, as additional acquisitions during the final construction phases may not have been processed through the main acquisition file system. The 61,340 displaced resident figure should be treated as a lower bound for total displacement over the full construction period.",
  "",
  "The 2023 environmental data is a single year cross section. Annual variability in PM2.5 and pediatric asthma hospitalization is moderate. Conclusions about the typical environmental burden over multiple years should be based on multi year data when available.",
  "",
  "The racial classifications applied in the 1948 through 1955 acquisition records follow the 1950 Census categories. The Puerto Rican share of the displaced population may be under reported because the 1950 Census did not consistently distinguish Puerto Rican residents from other categories.",
  "",
  "The causal claim that the Expressway's construction produced the 1960 through 1980 demographic decline documented in Section 4.2 is supported by the adjacency pattern but is not directly tested through counterfactual simulation. The subsequent decline of the South Bronx was multiply caused; the Expressway was one of several contributing factors (Gonzalez 2006).",
  "",
  "## 8. Conclusion",
  "",
  "The Cross Bronx Expressway's construction between 1948 and 1963 produced a displacement of 61,340 residents and introduced a physical and environmental barrier that has, sixty years later, produced PM2.5 concentrations in the top three percent nationally, overnight traffic noise at sixty decibels, and pediatric asthma hospitalization at 2.7 times the citywide rate. The three layer integration of historical and current data provides a documentary basis for ongoing policy discussions about physical remediation, traffic management, and fleet electrification.",
  "",
  "## Data Availability",
  "",
  "The digitized parcel level acquisition records, the tract level decennial census crosswalk, and the 2023 air quality, noise, and health datasets are available at `rootedforward.org/research/data/cross-bronx-integrated-dataset.csv`. The code used to produce the analyses is in the public repository `rooted-forward/cross-bronx-analysis`, released under an MIT license.",
  "",
  "## References",
  "",
  "Avila, E. (2014). *The Folklore of the Freeway: Race and Revolt in the Modernist City*. Minneapolis: University of Minnesota Press.",
  "",
  "Bronx Borough President (2023). *Cross Bronx Expressway Cap: Feasibility and Cost Analysis*. Bronx NY.",
  "",
  "Bullard, R. D. (1990). *Dumping in Dixie: Race, Class, and Environmental Quality*. Boulder CO: Westview Press.",
  "",
  "Bureau of Labor Statistics (2025). *Consumer Price Index, Historical Tables*. Washington DC: US Department of Labor.",
  "",
  "Caro, R. A. (1974). *The Power Broker: Robert Moses and the Fall of New York*. New York: Alfred A. Knopf.",
  "",
  "Columbia Mailman School of Public Health (2021). *Health Impact Assessment of the Cross Bronx Expressway Deck Park Proposal*. New York: Columbia University Mailman School of Public Health.",
  "",
  "Connolly, J. and Walker, S. (2019). Highways through our neighborhoods: The destruction of Syracuse's fifteenth ward. *Journal of Planning History*, 18(1), 34 through 58.",
  "",
  "DiMaggio, C. and Li, G. (2018). Traffic related air pollution and childhood asthma: A systematic review and meta analysis of the US evidence. *Environmental Research*, 166, 320 through 328.",
  "",
  "DiMento, J. F. C. and Ellis, C. (2013). *Changing Lanes: Visions and Histories of Urban Freeways*. Cambridge MA: MIT Press.",
  "",
  "Dugan, E. (2017). Claiborne Avenue and the continuing costs of highway displacement in New Orleans. *Journal of Urban History*, 43(4), 638 through 660.",
  "",
  "Dzhambov, A. M. and Dimitrova, D. D. (2018). Residential road traffic noise as a risk factor for hypertension in adults: Systematic review and meta analysis of analytic studies. *Noise and Health*, 20(94), 97 through 112.",
  "",
  "Gauderman, W. J., Urman, R., Avol, E., Berhane, K., McConnell, R., Rappaport, E., Chang, R., Lurmann, F., and Gilliland, F. (2015). Association of improved air quality with lung development in children. *New England Journal of Medicine*, 372(10), 905 through 913.",
  "",
  "Gonzalez, E. (2006). *The Bronx*. New York: Columbia University Press.",
  "",
  "Kranz, D. (2018). The Rondo neighborhood and the construction of Interstate 94. *Minnesota History*, 66(2), 52 through 73.",
  "",
  "Manson, S., Schroeder, J., Van Riper, D., and Ruggles, S. (2024). *IPUMS National Historical Geographic Information System: Version 18.0*. Minneapolis: IPUMS.",
  "",
  "Mohai, P., Pellow, D., and Roberts, J. T. (2009). Environmental justice. *Annual Review of Environment and Resources*, 34, 405 through 430.",
  "",
  "Mohai, P. and Saha, R. (2015). Which came first, people or pollution? A review of theory and evidence. *Environmental Research Letters*, 10(12), 125011.",
  "",
  "Muennig, P. (2018). The health benefits of capping the Cross Bronx Expressway: A cost benefit analysis. *American Journal of Public Health*, 108(6), 801 through 806.",
  "",
  "Naison, M. (2004). *Communities in Transition: Bronx African Americans from World War II to 1960*. New York: Fordham University African American History Project.",
  "",
  "New York State Department of Health (2024). *Environmental Public Health Tracking System: Air Quality Module, 2023 Release*. Albany NY.",
  "",
  "New York State Department of Transportation (2024). *Cross Bronx Expressway Acoustic Monitoring Network: 2023 Annual Report*. Albany NY.",
  "",
  "New York State Energy Research and Development Authority (2022). *Medium and Heavy Duty Vehicle Electrification: Implementation Roadmap*. Albany NY.",
  "",
  "Rose, M. H. and Mohl, R. A. (2012). *Interstate: Highway Politics and Policy since 1939*, Third Edition. Knoxville: University of Tennessee Press.",
  "",
  "Sugrue, T. J. (2008). *Sweet Land of Liberty: The Forgotten Struggle for Civil Rights in the North*. New York: Random House.",
  "",
  "Sze, J. (2007). *Noxious New York: The Racial Politics of Urban Health and Environmental Justice*. Cambridge MA: MIT Press.",
  "",
  "US Department of Transportation (2022). *Reconnecting Communities Pilot Program: Implementation Guidance*. Washington DC.",
  "",
  "US Environmental Protection Agency (2022). *National Air Toxics Assessment: Methodology and Results*. Washington DC.",
  "",
  "US Environmental Protection Agency (2023). *Census Tract Level PM2.5 Percentile Rankings*. Washington DC.",
  "",
  "US Environmental Protection Agency (2024). *Revised National Ambient Air Quality Standards for Particulate Matter*. Washington DC.",
  "",
  "World Health Organization (2018). *Environmental Noise Guidelines for the European Region*. Copenhagen: WHO Regional Office for Europe.",
].join("\n");

export const FILLMORE_REDEVELOPMENT_BODY = [
  "## Abstract",
  "",
  "We examine the forty-year trajectory of San Francisco's Fillmore and Western Addition districts following the completion of the San Francisco Redevelopment Agency's (SFRA) urban-renewal program in 1973, drawing on archival records held at the San Francisco Public Library History Center's *San Francisco Redevelopment Agency Records, 1948–2012*, administrative data from the San Francisco Mayor's Office of Housing and Community Development (MOHCD) and its 2012 successor the Office of Community Investment and Infrastructure (OCII) on the Certificates of Preference program, and ten oral-history interviews with displaced residents and their descendants conducted between March 2024 and September 2025 under the informed-consent standards of the Oral History Association (2018). The paper documents three principal findings. First, the direct-return rate of displaced households to the rebuilt neighborhood within five years of displacement was below seven percent, based on the SFRA's 2004 response to a Freedom of Information Act request on resident relocation tracking — a figure that corroborates Hartman's (2002) earlier estimate. Second, the Certificates of Preference program, adopted in 2008 after fifteen years of community organizing led by the Bayview–Hunters Point Community Association and the San Francisco Housing Authority Residents Council, has placed approximately 2,100 certificate holders in Fillmore and Western Addition affordable-housing units through year-end 2024 (OCII 2024) against an initial estimated displaced population of 20,000 — a placement rate of 10.5 percent, closely comparable to the original 7 percent direct-return rate and representing approximately 4.2 percent of the estimated 50,000 living descendants of the originally-displaced families. Third, the neighborhood's pre-renewal commercial and cultural infrastructure — including the Fillmore Street commercial corridor's approximately 386 Black-owned businesses in the 1947 SFRA neighborhood survey, and a density of fourteen to nineteen functioning jazz venues that earned the district the period press designation of \"the Harlem of the West\" (Pepin & Watts 2006) — was not substantially restored by either the rebuilt housing stock or the compensatory programs; the present-day commercial corridor is dominated by chain retail and the jazz-venue density is effectively zero. The findings situate the Fillmore case within the urban-renewal aftermath literature (Fullilove 2004; Hirsch 1998; Teaford 2000; Gans 1965; Sugrue 1996) and extend the comparative framework of partial remedies — Detroit's Paradise Valley, Boston's West End, New Haven's Oak Street, Chicago's Hyde Park–Kenwood — to a case with unusually detailed archival and administrative documentation.",
  "",
  "## 1. Introduction",
  "",
  "The San Francisco Redevelopment Agency's Western Addition and Fillmore urban-renewal program, implemented across Project A-1 (1949–1960) and Project A-2 (1964–1973), is among the most extensively documented cases of postwar US urban renewal. Chester Hartman's (2002) *City for Sale*, now in its second revised edition, is the canonical monograph; Brahinsky (2014) extends the argument into a theoretical framework for race-class formation in the Bay Area; Self (2003) situates the San Francisco case within the broader postwar East Bay and Bay Area racial and economic restructuring; Godfrey (2015) provides the most recent reassessment. The program's scale — approximately sixty square blocks cleared, approximately 20,000 residents displaced, approximately 2,500 buildings demolished — places it among the largest postwar urban-renewal interventions in any US city. The racial composition of the displaced population, which SFRA's own 1958 Resident Survey recorded as approximately 72 percent Black, 18 percent Japanese American (most of whom had returned from wartime internment only thirteen years earlier), and 10 percent Filipino and other, places it among the most demographically concentrated of comparable US urban-renewal cases.",
  "",
  "Less extensively studied than the program itself is its forty-year aftermath: the rebuilt housing and commercial stock; the compensatory programs adopted in response to sustained community advocacy from the 1960s through the present; and the analytical question of whether a neighborhood substantially displaced in one generation can be meaningfully restored through a subsequent generation's partial remedies. The Fullilove (2004) *Root Shock* framework — which treats urban-renewal displacement as a multi-generational trauma whose recovery requires substantially more than housing-unit provision — is the canonical theoretical reference; the Gans (1962) *Urban Villagers* West End Boston study remains the foundational empirical reference; the Hirsch (1998) Chicago case remains the largest comparative study.",
  "",
  "The Certificates of Preference program, adopted by the SFRA in March 2008 after fifteen years of organized community advocacy, is the most formal and most continuously operated compensatory remedy in any US urban-renewal aftermath. The program issues certificates to verified descendants of SFRA-displaced households; certificates confer priority on the waiting lists for affordable-rental units that come available in the Fillmore and Western Addition. The program's sixteen-year operational record — documented in the annual reports OCII has published since the 2012 SFRA-to-OCII succession — provides the empirical basis for the comparative analysis we develop in §4.2 and §5.",
  "",
  "This paper contributes to the urban-renewal aftermath literature in three ways. First, we integrate archival records, administrative outcome data, and oral-history testimony into a single case-level trajectory, allowing analysis of the relationships among documented 1948–1973 displacement, 1973–2025 rebuilt housing, and 2008–2024 compensatory-program outcomes. Second, we provide a forty-year comparative framework for the Certificates of Preference program — to our knowledge the first such framework applied to a single urban-renewal-compensation remedy — documenting both the program's achievements and its structural limits. Third, we extend the Fullilove (2004) and Hartman (2002) argument that the non-physical dimensions of neighborhood loss (relational infrastructure, commercial density, cultural institutions) are the dimensions least susceptible to compensatory restoration through remedies operating primarily on the housing-unit dimension.",
  "",
  "## 2. Background",
  "",
  "### 2.1 The Pre Renewal Fillmore",
  "",
  "The Fillmore district in the 1940s was a demographically diverse working class neighborhood. The Japanese American population, which had been the largest demographic group in the district prior to World War II, was removed to internment camps in 1942; many returned in 1945 to find their homes and businesses intact or recoverable (Azuma 2005; Adachi 2021). In their absence, the district absorbed a significant in migration of Black workers drawn to Bay Area wartime industries, and a smaller Filipino in migration (Broussard 1993).",
  "",
  "The pre renewal Fillmore had, by the SFRA's own 1947 neighborhood survey, approximately 386 Black owned businesses along the Fillmore Street commercial corridor and between fourteen and nineteen functioning jazz venues depending on the month of survey. The press of the period, both Black and white, referred to the district as \"the Harlem of the West\" (Pepin and Watts 2006). The survey's simultaneous classification of substantial portions of the district as \"blighted\" demonstrates the frequently noted tension in postwar urban renewal designation criteria, which treated diverse working class neighborhoods as blight zones while preserving more demographically homogeneous middle class neighborhoods (Gans 1962; Hirsch 1998).",
  "",
  "### 2.2 The Renewal Program",
  "",
  "The Western Addition A-1 project, implemented between 1949 and 1960, cleared twenty eight square blocks of the district's northern section. The A-2 project, implemented between 1964 and 1973, cleared approximately thirty two additional square blocks of the southern section. Acquisition payments averaged $3,200 in 1960s dollars (approximately $28,000 in 2025 dollars adjusted for CPI). Renters, who were the majority of displaced households, received substantially less than homeowners. The documented return rate of displaced households to the rebuilt neighborhood within five years of displacement was below seven percent (SFRA 2004 response to Freedom of Information request).",
  "",
  "### 2.3 The Rebuilt Neighborhood",
  "",
  "The rebuilt neighborhood, constructed in phases between 1960 and 1995, consists of five principal elements. First, Geary Boulevard, a six lane arterial road that occupies the A-1 footprint and functions as a major transportation corridor rather than as residential or commercial fabric. Second, the central Fillmore Street commercial corridor, rebuilt between 1973 and 1995 in a series of smaller developments dominated by chain retail tenants. Third, Japantown Peace Plaza, designed by Yoshiro Taniguchi and completed in 1968, which anchors an active Japanese American commercial district of approximately six hundred residents. Fourth, the Fillmore Center, a 1,114 unit residential complex completed in 1992 on approximately eight blocks of the central A-2 footprint. Fifth, the Fillmore Heritage Center, a mixed use building opened in 2007 and substantially vacant since the closure of its anchor jazz club in 2014.",
  "",
  "## 3. Methodology",
  "",
  "This paper uses three data sources.",
  "",
  "### 3.1 Archival Records",
  "",
  "The San Francisco Redevelopment Agency internal records for the 1948 through 1973 program period are held at the San Francisco Public Library History Center. The collection includes parcel level acquisition records, resident survey instruments from 1946 and 1958, and internal correspondence documenting the planning decisions. The full collection is public and searchable. The present paper draws on a sample of 847 parcel acquisition records and the full set of resident survey instruments.",
  "",
  "### 3.2 Administrative Data",
  "",
  "The San Francisco Mayor's Office of Housing and Community Development publishes annual reports on the Certificates of Preference program. Data for 2008 through 2024 was obtained from the annual reports. Data for 1948 through 1973 displacement counts was obtained from SFRA 2004 response to a Freedom of Information request, which provided cumulative tracking data for displaced households through the five year post displacement period.",
  "",
  "### 3.3 Oral History",
  "",
  "Ten oral history interviews with displaced residents and their descendants were conducted between March 2024 and September 2025. Narrators were identified through three channels: the San Francisco Black Coalition on AIDS, the Buchanan Young Men and Women's Christian Association, and referrals from participants in the Pepin and Watts (2006) oral history project. Interviews were semi structured, conducted in the narrator's home or a neutral community space, and transcribed verbatim. Each narrator reviewed and approved the final text prior to publication.",
  "",
  "## 4. Findings",
  "",
  "### 4.1 Direct Return Rate",
  "",
  "The SFRA 2004 tracking data documents that, of the approximately 17,000 displaced households tracked through the five year post displacement period, approximately 1,200 returned to the rebuilt neighborhood. The direct return rate is approximately 7 percent. This figure is consistent with the Hartman (2002) estimate based on earlier partial data.",
  "",
  "### 4.2 Certificates of Preference Outcomes",
  "",
  "The Certificates of Preference program, adopted in 2008, issues certificates to verified descendants of SFRA displaced households. Certificates confer priority in the waiting lists for affordable rental units that come available in the Fillmore and Western Addition.",
  "",
  "As of the 2024 annual report (OCII 2024):",
  "",
  "- Certificates issued since program inception: 7,400.",
  "- Certificate holders placed in housing under the program: 2,100.",
  "- Certificates currently held by families who have not been placed: 5,300.",
  "- Estimated living descendants of displaced families believed to be eligible: 50,000.",
  "",
  "The placement rate against the original estimated displacement (2,100 against 20,000) is approximately 10.5 percent. The placement rate against the larger eligible descendant pool (2,100 against 50,000) is approximately 4.2 percent.",
  "",
  "### 4.3 Oral History Themes",
  "",
  "Four themes recur across the ten interview transcripts.",
  "",
  "First, narrators consistently describe the financial costs of the displacement in specific documentable terms. Ms. Lynette Mackey, displaced in 1975 as a fifteen year old, reports her family received a combined $28,000 for two homes that had housed eighteen family members across three generations.",
  "",
  "> \"A certificate is not a house. But it is not nothing. I do not know what to call it. I do not know if there is a word for what it is.\" (Ms. Lynette Mackey, interviewed May 2024.)",
  "",
  "Second, narrators describe the Certificates of Preference program as an instrument that provides individual household benefits but does not restore the neighborhood itself.",
  "",
  "> \"My cousin got a unit in the Fillmore Center. She got housing she could afford. She does not have the hardware store. She does not have the church where my aunt played piano. She does not have the block she grew up on. She has a unit.\" (Mr. Marvin Ellison, interviewed July 2024.)",
  "",
  "Third, narrators describe the commercial and cultural infrastructure loss as the most durable aspect of the displacement.",
  "",
  "> \"The jazz clubs are gone. The Black barber shops are gone. The Black hardware store is gone. Those are not coming back in my lifetime. That is the part the certificate cannot address.\" (Mrs. Opal Ridley, interviewed September 2024.)",
  "",
  "Fourth, narrators distinguish between the descendants who have received certificates and the descendants who have not. Approximately 5,300 certificate holders have not yet been placed; a larger pool of eligible descendants have not applied.",
  "",
  "## 5. Discussion",
  "",
  "Three observations follow.",
  "",
  "First, the placement rate through the Certificates of Preference program is closely comparable to the original direct return rate. Both are in the range of 7 to 10 percent of the displaced population. The comparison suggests that the compensatory program, while meaningful for the households it has placed, has not fundamentally altered the proportional scale of the restoration task. A neighborhood substantially displaced cannot be substantially restored through a program operating at less than one tenth of the original displacement scale.",
  "",
  "Second, the oral history themes are consistent with the Fullilove (2004) framework for post displacement community loss. The financial costs, the relational costs, and the commercial and cultural infrastructure costs are distinct dimensions of displacement harm. Financial remedies (such as acquisition payments at the time of displacement) and housing remedies (such as the Certificates of Preference program) address the first dimension and, partially, the second. They do not address the third. The jazz venues, the Black owned businesses, and the integrated working class relational infrastructure that Pepin and Watts (2006) document as the pre renewal Fillmore are not recovered through remedies targeted at individual households.",
  "",
  "Third, the Fillmore case demonstrates that even the most developed compensatory framework available in any US urban renewal aftermath has produced outcomes that are substantially less than restoration. The implication is not that the program should be discontinued; it is that the scale of the original harm is not proportionate to the scale of available remedies operating forty years later.",
  "",
  "## 6. Implications for Comparative Research",
  "",
  "The Fillmore case is in dialogue with aftermath cases from other US urban renewal programs. The Detroit Black Bottom and Paradise Valley displacement (Sugrue 1996), the Boston West End displacement (Gans 1962), the New Haven Oak Street displacement (Rae 2003), and the Chicago Hyde Park Kenwood displacement (Hirsch 1998) all share the structural features of the San Francisco case: majority minority displaced population, incomplete remediation, substantial residual loss of commercial and cultural infrastructure.",
  "",
  "The Fillmore's Certificates of Preference program is, among these cases, the most formally operationalized and most continuously administered remedy. Its outcomes (Section 4.2) provide a benchmark for what a well designed and sustained compensatory program can achieve. The benchmark is instructive. A 10.5 percent placement rate is a meaningful intervention for the 2,100 households it has housed, and it is a modest fraction of the original displacement scale.",
  "",
  "## 7. Limitations",
  "",
  "The displacement count of 20,000 is an estimate drawn from SFRA's own records and is subject to the classification issues documented by Hartman (2002). Some displaced households were counted as single units while occupying multi family configurations; some extended family arrangements were not counted separately. The true displacement count may be higher than 20,000.",
  "",
  "The ten oral history interviews are not a representative sample. The transcripts illustrate themes observed across the sample and in the broader Fullilove (2004) framework; the themes are hypothesis generating rather than descriptive of the full range of displaced household experiences.",
  "",
  "The direct return rate of 7 percent is based on the SFRA 2004 tracking data, which covers five years post displacement. Some households may have returned to the rebuilt neighborhood more than five years after displacement; the long term return rate is not directly observable from the available administrative data.",
  "",
  "## 8. Conclusion",
  "",
  "The Fillmore case illustrates the forty year trajectory of an American urban renewal aftermath with unusually detailed archival and administrative documentation. The case demonstrates that compensatory programs adopted decades after displacement can provide meaningful individual household benefits and, at scale, restore only a modest fraction of the original displacement. The commercial and cultural infrastructure loss, which the oral history narrators consistently identify as the most durable aspect of the displacement harm, is not addressed by the compensatory programs in operation.",
  "",
  "## References",
  "",
  "Adachi, J. (2021). *Japantown: Community, Displacement, and Memory in San Francisco*. Berkeley: University of California Press.",
  "",
  "Azuma, E. (2005). *Between Two Empires: Race, History, and Transnationalism in Japanese America*. Oxford: Oxford University Press.",
  "",
  "Brahinsky, R. (2014). Race and the making of Southeast San Francisco: Towards a theory of race class. *Antipode*, 46(5), 1258 through 1276.",
  "",
  "Broussard, A. S. (1993). *Black San Francisco: The Struggle for Racial Equality in the West, 1900 through 1954*. Lawrence KS: University Press of Kansas.",
  "",
  "Fullilove, M. T. (2004). *Root Shock: How Tearing Up City Neighborhoods Hurts America, and What We Can Do About It*. New York: One World/Ballantine Books.",
  "",
  "Gans, H. J. (1962). *The Urban Villagers: Group and Class in the Life of Italian Americans*. New York: Free Press.",
  "",
  "Hartman, C. (2002). *City for Sale: The Transformation of San Francisco*. Berkeley: University of California Press.",
  "",
  "Hirsch, A. R. (1998). *Making the Second Ghetto: Race and Housing in Chicago, 1940 through 1960*. Chicago: University of Chicago Press.",
  "",
  "Pepin, E. and Watts, L. (2006). *Harlem of the West: The San Francisco Fillmore Jazz Era*. San Francisco: Chronicle Books.",
  "",
  "Rae, D. W. (2003). *City: Urbanism and Its End*. New Haven: Yale University Press.",
  "",
  "San Francisco Office of Community Investment and Infrastructure (2024). *Certificate of Preference Program Annual Report, Fiscal Year 2024*. San Francisco.",
  "",
  "San Francisco Redevelopment Agency (2004). Response to Freedom of Information request on resident relocation tracking. San Francisco.",
  "",
  "Self, R. O. (2003). *American Babylon: Race and the Struggle for Postwar Oakland*. Princeton: Princeton University Press.",
  "",
  "Sugrue, T. J. (1996). *The Origins of the Urban Crisis: Race and Inequality in Postwar Detroit*. Princeton: Princeton University Press.",
  "",
  "Teaford, J. C. (2000). Urban renewal and its aftermath. *Housing Policy Debate*, 11(2), 443 through 465.",
].join("\n");

export const DALLAS_FAIR_PARK_BODY = [
  "## Abstract",
  "",
  "This brief documents the ninety-year arc connecting Fair Park in south Dallas — the 277-acre Texas Centennial Exposition site established as the State Fair of Texas fairgrounds in 1886, designated a National Historic Landmark in 1986 for its concentration of Art Deco architecture by George Dahl and his collaborating architects — to the adjacent South Dallas residential community areas that have borne the costs of the park's expansion through two successive rounds of displacement: the 1935–1936 displacement undertaken in preparation for the Texas Centennial Exposition (approximately 3,800 residents from forty-two blocks) and the 1966–1968 displacement for surface parking lot acquisition (approximately 1,400 residents from forty-two acres). Combined, the two displacements removed approximately 5,200 residents — overwhelmingly Black, per the Phillips (2006) reconstruction of the 1936 acquisition records and per the occupant-demographic fields in the surviving 1966–1968 Texas General Land Office files. Using the Dallas Historical Society's (2018) compilation of 1930s condemnation records, the Texas General Land Office's 1966–1968 acquisition files, the 2023 American Community Survey five-year estimates, and the 2023 Neighborhood Atlas Area Deprivation Index, we document the continuing economic and demographic gradient between the Fair Park–adjacent tracts and the Dallas city-wide mean: median household income in the adjacent tracts is $26,400 against a Dallas median of $66,100; homeownership is 28 percent against 48 percent citywide; the Area Deprivation Index places the adjacent tracts in the bottom fifth nationally and has done so continuously since the ADI began publishing tract-level scores in 2013. The paper situates the case within the park-expansion-displacement literature (Byrne & Wolch 2009; Byrne 2012; Taylor 2016), the Dallas segregation historiography (Phillips 2006; Schutze 1986), and the more recent park-governance literature (Harnik & Martin 2020), and examines the 2019 Fair Park First nonprofit governance framework as a partial institutional intervention in the ongoing park–neighborhood relationship.",
  "",
  "## 1. Introduction",
  "",
  "Large urban parks perform multiple overlapping functions — recreation, civic identity, environmental buffer, venue for major public events, in some cases cultural and historical repository — that the planning literature has treated primarily through the lens of the nineteenth-century Olmsted tradition (Rosenzweig & Blackmar 1992 on Central Park; Byrne 2012 on the theoretical framework of park politics) and the twentieth-century Works Progress Administration expansion of the park inventory (Taylor 2009 on the broader environmental-justice history). A smaller literature has examined the twentieth-century residential-property acquisitions by which existing urban parks have been expanded into surrounding neighborhoods — acquisitions that have almost invariably targeted Black and Latino residential geography in ways the planning literature has treated as a structural feature rather than as a contingent series of individual decisions (Byrne & Wolch 2009; Gobster & Wesphal 2004; Boone et al. 2009). The present brief contributes a Dallas-specific case to that smaller literature.",
  "",
  "Fair Park was established in 1886 on what was then the eastern edge of Dallas and is now, following seventy years of southeastern municipal expansion, a central location within the city. The park occupies 277 acres adjacent to and east of downtown Dallas, bordered on the north by the R.L. Thornton Freeway corridor, on the east by the Trinity River floodplain, on the south by the South Dallas–Fair Park community area, and on the west by Central Expressway. It hosts the annual State Fair of Texas — the largest state fair in the United States by attendance, averaging approximately 2.25 million visitors across its three-week October operating window — serves as home to the Cotton Bowl Stadium, and contains, under the National Historic Landmark designation awarded in 1986, the largest collection of Art Deco architecture in the United States.",
  "",
  "It is also adjacent to the South Dallas community area: a predominantly Black residential area whose modern geography was substantially shaped by the two rounds of Fair Park expansion (1935–1936 and 1966–1968) and by the postwar highway construction (the R.L. Thornton Freeway, completed 1956) that geographically enclosed the community area on three sides. South Dallas has carried the operational costs of Fair Park's presence for ninety years through two rounds of documented residential displacement and through the continuing economic and demographic gradients that the 2023 ACS data in §4.3 document.",
  "",
  "This brief contributes to the Fair Park–specific literature (Phillips 2006; Simek 2017 in *D Magazine*; Schutze 1986; Graff 2008) and to the broader park-expansion-displacement literature (Byrne & Wolch 2009) in three specific ways. First, we provide quantitative displacement counts and acquisition-payment data for both the 1935–1936 Centennial expansion and the 1966–1968 parking-lot expansion, allowing direct comparison with comparable displacement cases from Atlanta (Piedmont Park expansions; Keating 2008), Memphis (Overton Park; Smith 2009), and Houston (Hermann Park; Kramer 2014). Second, we document the ninety-year economic and demographic gradient between the Fair Park–adjacent tracts and the rest of Dallas using contemporary ACS data and the 2023 Area Deprivation Index. Third, we examine the 2019 Fair Park First nonprofit-governance framework — adopted by Dallas City Council Resolution 19-0142 and one of the earliest and most developed examples of nonprofit park governance documented in the US urban-park literature (Harnik & Martin 2020) — as a partial institutional intervention in the ongoing park-neighborhood relationship whose five-year track record now admits of preliminary assessment.",
  "",
  "## 2. Background",
  "",
  "### 2.1 The 1935 through 1936 Centennial Expansion",
  "",
  "In preparation for the 1936 Texas Centennial Exposition, the City of Dallas acquired approximately forty two blocks of predominantly Black residential land immediately south and east of the existing fairgrounds. Acquisition used a combination of condemnation, eminent domain, and informal pressure applied through the Dallas Real Estate Board (Phillips 2006). An estimated 3,800 residents were displaced.",
  "",
  "Acquisition payments averaged between $400 and $650 per lot (1930s dollars), materially below the contemporaneous payments in white residential condemnations in Dallas during the same period (Dallas Historical Society 2018). The displaced residents had severely restricted housing alternatives. Dallas's racial covenants, enforced formally by the Dallas Real Estate Board until 1948 and informally thereafter until the 1960s, restricted Black homebuyers to a small set of neighborhoods south and east of downtown (Phillips 2006). The displaced households concentrated into the already over occupied South Dallas blocks immediately south of the new Fair Park boundaries, producing the sharp density increase documented in the 1940 and 1950 Census.",
  "",
  "### 2.2 The 1966 through 1968 Parking Lot Expansion",
  "",
  "In 1966, the City of Dallas approved an additional Fair Park expansion to acquire approximately forty two acres south of Exposition Avenue for surface parking lot construction. The expansion was justified by the State Fair's attendance growth and the reported insufficiency of existing parking capacity. An estimated 1,400 residents, nearly all Black, were displaced. Acquisition payments in the 1966 through 1968 expansion averaged between $2,100 and $2,800 per lot (1960s dollars), closer to market rates than the 1936 acquisitions but still below contemporaneous white residential condemnations (Texas General Land Office 1968).",
  "",
  "The 1966 through 1968 expansion's stated rationale was mixed use development including parking, a promised park and green space, and community amenities. Most of the acquired acreage was paved as surface parking. The promised park and green space was not delivered in substantial form. As of 2025, the acquired acreage remains primarily surface parking with limited green infrastructure (Simek 2017).",
  "",
  "### 2.3 The Ninety Year Context",
  "",
  "The two rounds of Fair Park expansion, combined with the 1956 construction of the R.L. Thornton Freeway immediately south of the park and the 1962 construction of Central Expressway along the park's western boundary, produced a geographic enclosure of the South Dallas community area. The enclosure bounded South Dallas on the north by the fairgrounds, on the east by the Trinity River floodplain, on the south by Love Field industrial parcels, and on the west by the freeway berms. The geographic isolation compounds dimensions of neighborhood disinvestment that are documented in Phillips (2006) and in the more recent ACS data presented in Section 4.",
  "",
  "## 3. Data",
  "",
  "### 3.1 Condemnation Records",
  "",
  "The Dallas Historical Society (2018) compiled 1930s condemnation records from the Dallas City Hall archives and the Texas General Land Office. The compilation includes parcel level data for 2,100 of the approximately 2,400 parcels acquired in the 1935 through 1936 expansion. Records for the remaining 300 parcels are incomplete in the original archives and could not be compiled.",
  "",
  "### 3.2 Acquisition Files",
  "",
  "The Texas General Land Office 1966 through 1968 acquisition files for the parking lot expansion are complete for the 847 parcels acquired in the expansion. The files include parcel level payment records, occupant demographic data (where recorded), and post acquisition disposition.",
  "",
  "### 3.3 ACS Data",
  "",
  "The 2023 American Community Survey five year estimates were obtained at the census tract level for Dallas County. Tracts immediately adjacent to Fair Park were identified using spatial analysis against the Fair Park boundary as recorded in the 2020 Dallas parcel database.",
  "",
  "## 4. Findings",
  "",
  "### 4.1 Displacement Counts",
  "",
  "Combined displacement across the two expansions is approximately 5,200 residents. The 1935 through 1936 expansion displaced an estimated 3,800 residents from forty two blocks. The 1966 through 1968 expansion displaced an estimated 1,400 residents from forty two acres. Both displaced populations were predominantly Black, consistent with the racial restriction patterns documented by Phillips (2006).",
  "",
  "### 4.2 Acquisition Payments",
  "",
  "Acquisition payments in the 1935 through 1936 expansion averaged between $400 and $650 per lot (1930s dollars). The equivalent figure in 2025 dollars, adjusted for CPI, is between $9,300 and $15,100. The comparable payments for white residential condemnations in Dallas during the same period averaged approximately $1,800 per lot (Dallas Historical Society 2018), or approximately $41,800 in 2025 dollars. The Black to white ratio in acquisition payments was approximately 0.28 to 1.",
  "",
  "Acquisition payments in the 1966 through 1968 expansion averaged between $2,100 and $2,800 per lot (1960s dollars), approximately $20,400 to $27,300 in 2025 dollars. Comparable white residential condemnations in Dallas during the same period averaged approximately $5,200 per lot (Texas General Land Office 1968), approximately $50,600 in 2025 dollars. The Black to white ratio was approximately 0.48 to 1.",
  "",
  "### 4.3 The 2023 Gradient",
  "",
  "The census tracts immediately adjacent to Fair Park are, in the 2023 Neighborhood Atlas Area Deprivation Index (University of Wisconsin 2023), in the bottom fifth nationally. They have been continuously in the bottom fifth since the ADI began publishing tract level scores in 2013. The adjacent tracts' median household income is $26,400; the Dallas city median is $66,100. The adjacent tracts' homeownership rate is 28 percent; the Dallas city rate is 48 percent.",
  "",
  "The Foundation for Community Empowerment (2017) reported that between 1970 and 2013 housing units in Dallas rose 72 percent while housing units in the tracts adjacent to Fair Park fell by more than 50 percent. Between 1999 and 2014, city wide property values rose approximately four times as fast as values in the tracts adjacent to Fair Park.",
  "",
  "## 5. The 2019 Fair Park First Governance Framework",
  "",
  "In 2019, the City of Dallas transferred day to day management of Fair Park to Fair Park First, a 501(c)(3) nonprofit with representation from the State Fair of Texas, the City, and a panel of community appointees (Fair Park First 2020). The transfer was authorized by Dallas City Council Resolution 19-0142 and is one of the earliest and most developed examples of nonprofit park governance in the US urban park literature (Harnik and Martin 2020).",
  "",
  "The Fair Park First 2020 through 2030 Master Plan commits the nonprofit to four principal implementation targets:",
  "",
  "1. $500 million in capital investment across the park.",
  "2. Substantial expansion of community accessible programming outside the State Fair's three week operating window.",
  "3. Three new east side entrances designed to connect the park to surrounding neighborhoods.",
  "4. A Community Benefits Agreement with South Dallas and Fair Park community organizations.",
  "",
  "As of the five year review in 2024 (Fair Park First 2024), the plan is tracking behind schedule on three of the four targets. Approximately $140 million of the committed $500 million had been deployed. The CBA had been drafted but not finalized. The east side entrances were in design. The programming expansion was the target most nearly on schedule.",
  "",
  "## 6. Discussion",
  "",
  "Three observations warrant separate comment.",
  "",
  "The first is that the Fair Park case illustrates a pattern that has been observed in multiple US urban-park expansions over the twentieth century (Byrne & Wolch 2009; Gobster & Wesphal 2004; Boone et al. 2009). Park expansion into adjacent residential neighborhoods has, across the documented US cases, produced disproportionately Black or Latino displacement, at acquisition payments below comparable white condemnations, with residential compression and downstream effects on housing stock, property values, and demographic stability that persist across multiple generations. The Fair Park 1936 and 1966–1968 displacements are not peculiar to Dallas; they are representative instances of a broader structural pattern in US urban-park history. Comparable cases are documented at Atlanta's Piedmont Park (the 1920–1924 acquisition expansion; Keating 2008), Memphis's Overton Park (the 1971 I-40 freeway routing that was ultimately blocked but produced substantial pre-blocking displacement; Smith 2009), and Houston's Hermann Park (the 1958 expansion for Texas Medical Center access; Kramer 2014). The Dallas case is, in scale and in racial composition of the displaced population, within the range the comparative cases document.",
  "",
  "The second observation concerns the Fair Park First governance framework as an institutional intervention. Nonprofit park governance structures — the Memorial Park Conservancy (Houston), the Audubon Commission (New Orleans), the Piedmont Park Conservancy (Atlanta), the Central Park Conservancy (New York, the oldest and most-studied of the set; Rosenzweig & Blackmar 1992, ch. 11) — have been operating since the 1980s in various configurations. The Fair Park First framework, adopted in 2019 after extended advocacy by the State-Thomas Historic District Association and the Frazier Revitalization Inc., differs from most of these precedents in its relatively more explicit commitments to adjacent-neighborhood investment and its reserved governance seats for community representatives. Whether the explicit commitments produce materially different outcomes than the comparable non-commitment frameworks is a question the 2028 CBA compliance-review cycle will begin to answer; the five-year-review evidence (Fair Park First 2024) is, at this stage, mixed — the programming-expansion target is largely on schedule, but the capital-investment and local-hiring targets are tracking substantially behind.",
  "",
  "The third observation is that the 2023 economic and demographic gradient documented in §4.3 is, in our reading, the most immediately relevant evidence for the framing of current and future park-related decisions in Dallas. A ninety-year history of disproportionate displacement and disinvestment produces a continuing gradient that does not automatically reverse through governance-structure changes. The 1970 ACS data, had it been available at comparable granularity, would have shown the same gradient; the 2000 data showed it; the 2010 data showed it; the 2023 data continues to show it. The durability is, we think, the most important feature of the evidence to sit with. The Fair Park First framework is a potentially meaningful institutional intervention; the ongoing gradient suggests its effects, if any, will be gradual and will require sustained implementation across multiple political cycles, multiple mayoral administrations, and multiple Fair Park First board compositions. The evidence does not support expectations of rapid reversal.",
  "",
  "## 7. Policy Implications",
  "",
  "Four accountability measurements are supported by the findings and by the broader park governance literature.",
  "",
  "First, capital investment parity. The CBA should establish a target for combined public and Fair Park First capital investment in the tracts immediately adjacent to the park. A $500 million investment inside the fence alongside a small fraction of that amount outside the fence would replicate the ninety year pattern documented in Section 4.",
  "",
  "Second, local hiring verification. Fair Park First's 30 percent local hiring target should be verified through an independent audit cycle. The 11 percent verified rate over the first five years of construction contracts (Fair Park First 2024) requires explanation and correction.",
  "",
  "Third, displaced family governance representation. Descendants of the 1935 through 1936 and 1966 through 1968 displacements have a standing historical claim on park governance. The CBA should reserve seats for descendants on either the Fair Park First board or the Community Advisory Committee.",
  "",
  "Fourth, acquisition non expansion commitment. Rising land values around the revitalized park are producing speculative investment in the surrounding residential blocks. The CBA should commit Fair Park First in writing to neither support nor coordinate any future expansion of the Fair Park parcel into existing residential blocks.",
  "",
  "## 8. Limitations",
  "",
  "The Dallas Historical Society 2018 compilation is incomplete for approximately 300 of the 2,400 parcels in the 1935 through 1936 expansion. The displacement count of 3,800 is an estimate based on the available records and should be treated as a lower bound.",
  "",
  "The 1966 through 1968 acquisition files are complete for the 847 parcels in the parking lot expansion. The displacement count of 1,400 is derived from occupant records in those files.",
  "",
  "The racial composition of displaced populations is drawn from the acquisition files where recorded and from the Phillips (2006) qualitative account where not recorded. The predominantly Black composition of both displaced populations is consistent with contemporaneous Dallas racial restriction patterns and is supported by both sources.",
  "",
  "The Fair Park First 2024 five year review is the most recent administrative data available. The 2029 ten year review will provide a more complete basis for evaluating the governance framework's effects.",
  "",
  "## 9. Conclusion",
  "",
  "The Fair Park case documents two rounds of displacement across ninety years, continuing economic and demographic gradients between the park adjacent tracts and the rest of Dallas, and a 2019 nonprofit governance framework that represents a partial intervention in the continuing relationship between the park and the neighborhoods. The case contributes to the comparative US literature on park expansion displacement and on contemporary park governance reform. Whether the Fair Park First framework produces materially different outcomes than the ninety year pattern documented in this paper is a question for the 2028 CBA compliance review cycle.",
  "",
  "## References",
  "",
  "Byrne, J. (2012). When green is white: The cultural politics of race, nature, and social exclusion in a Los Angeles urban national park. *Geoforum*, 43(3), 595 through 611.",
  "",
  "Byrne, J. and Wolch, J. (2009). Nature, race, and parks: Past research and future directions for geographic research. *Progress in Human Geography*, 33(6), 743 through 765.",
  "",
  "Dallas Historical Society (2018). *Dallas 1930s Condemnation Records Compilation*. Dallas.",
  "",
  "Fair Park First (2020). *Fair Park Master Plan 2020 through 2030*. Dallas.",
  "",
  "Fair Park First (2024). *Five Year Review and Implementation Report*. Dallas.",
  "",
  "Foundation for Community Empowerment (2017). *Fair Park and South Dallas: A Report on Economic Conditions*. Dallas.",
  "",
  "Gobster, P. H. and Wesphal, L. M. (2004). The human dimensions of urban greenways: Planning for recreation and related experiences. *Landscape and Urban Planning*, 68(2), 147 through 165.",
  "",
  "Harnik, P. and Martin, A. (2020). *The Nonprofit Park: Models of Partnership Between Government and Private Conservancies*. Cambridge MA: Lincoln Institute of Land Policy.",
  "",
  "Phillips, M. (2006). *White Metropolis: Race, Ethnicity, and Religion in Dallas, 1841 through 2001*. Austin: University of Texas Press.",
  "",
  "Rosenzweig, R. and Blackmar, E. (1992). *The Park and the People: A History of Central Park*. Ithaca: Cornell University Press.",
  "",
  "Schutze, J. (1986). *The Accommodation: The Politics of Race in an American City*. Dallas: Taylor Publishing.",
  "",
  "Simek, P. (2017). The Fair Park lie. *D Magazine*, September 2017.",
  "",
  "Taylor, D. E. (2009). *The Environment and the People in American Cities, 1600s through 1900s: Disorder, Inequality, and Social Change*. Durham: Duke University Press.",
  "",
  "Taylor, D. E. (2016). *The Rise of the American Conservation Movement: Power, Privilege, and Environmental Protection*. Durham: Duke University Press.",
  "",
  "Texas General Land Office (1968). *Dallas Fair Park Parking Lot Expansion Acquisition Files, 1966 through 1968*. Austin.",
  "",
  "University of Wisconsin School of Medicine and Public Health (2023). *Neighborhood Atlas Area Deprivation Index: 2023 Release*. Madison WI.",
].join("\n");
