/* ------------------------------------------------------------------ */
/*  research-seed-content-vol2.ts                                      */
/* ------------------------------------------------------------------ */
/*                                                                     */
/*  Academic research bodies for:                                      */
/*  - Hyde Park Urban Renewal: six edited oral histories              */
/*  - The 1938 HOLC Chicago security map, annotated                   */
/*                                                                     */
/* ------------------------------------------------------------------ */

export const HYDE_PARK_ORAL_HISTORY_FULL_BODY = [
  "## Abstract",
  "",
  "This qualitative study presents six edited oral-history interviews with long-term residents of Chicago's Hyde Park and Kenwood neighborhoods who were displaced by the Hyde Park–Kenwood Urban Renewal Plan, Project A-1 (1955–1960) and Project A-2 (1960–1970). The six narrators were selected from a larger initial corpus of twenty-seven semi-structured interviews conducted between March 2024 and April 2025, purposively sampled for geographic coverage of the renewal zone, range of displacement experience, and willingness to appear under their real names under Oral History Association (2018) informed-consent standards. Testimony is analyzed against the quantitative displacement record preserved in the South East Chicago Commission administrative files (SECC 1955–1970; UChicago Library Special Collections), the 1962–1965 Ford Foundation–funded displacement-interview project whose transcripts remain sequestered in the University of Chicago Department of Sociology archive, and the comparative literature on postwar urban-renewal oral histories (Fullilove 2004; Gans 1962; Venkatesh 2000; Rae 2003). The study contributes to the Hyde Park–Kenwood scholarly record in three ways: by extending documentation to the post-displacement generation living at the sixty-year mark; by including a Puerto Rican narrator whose demographic cohort is systematically under-represented in the existing scholarship (Ramírez Ruiz 2018); and by presenting first-person testimony from a former research-project interviewer whose account raises substantive questions about the 1962–1965 archival record. The paper closes with a formal request for the release of the sequestered Janowitz archive.",
  "",
  "## 1. Introduction",
  "",
  "The Hyde Park–Kenwood Urban Renewal Plan, approved by the Chicago City Council on November 7, 1958 and implemented in phases through 1970, remains among the most extensively documented urban-renewal programs in the postwar United States. The scholarly record includes Hirsch's (1998) authoritative treatment of the plan's policy origins within the South East Chicago Commission's 1952–1958 internal deliberations; Rossi and Dentler's (1961) contemporaneous social-scientific evaluation, published under Ford Foundation funding by the Free Press; Rotella's (2019) cultural history of the post-renewal neighborhood; and more recently, Pattillo's (2007) comparative analysis with the Black middle-class districts of the near South Side. The plan displaced, by the most widely-cited estimates, approximately 41,000 Black and 8,000 white residents from some 856 acres of housing stock (Hirsch 1998, pp. 135–170), though scholars including Abbott (1995) and Rotella (2019) have questioned the precision of these figures and have argued that the aggregate counts understate the extended-family configurations that Project A-1 and A-2 displaced in practice.",
  "",
  "What the scholarly record has documented less extensively is the first-person experience of displacement as recalled by the narrators who lived through it. Acquisition files at the SECC and the Chicago Land Clearance Commission, accessible at the University of Chicago Library Special Collections and the Chicago History Museum Research Center, record the dollar amount paid to each displaced household; they do not record what the household did with the money, where the household moved, whether the relocation was completed intact, or whether the ensuing thirty to fifty years of family history can be causally attributed, in whole or part — to the displacement event. Oral history is the methodology that can access these forms of knowledge, and it has been central to the broader postwar-urban-renewal literature from Gans (1962) on the West End of Boston through Fullilove (2004) on multiple displaced neighborhoods through Venkatesh (2000) on the Robert Taylor Homes. It has been unevenly applied to Hyde Park–Kenwood specifically.",
  "",
  "This study contributes to the Hyde Park–Kenwood scholarly record in three principal ways. First, it extends oral-history documentation to a post-displacement generation that has now lived with the consequences of the renewal for fifty to seventy years — a duration that allows analysis of life-course trajectories that were not available to Rossi and Dentler (1961) when their contemporaneous evaluation was conducted. Second, it includes a Puerto Rican narrator (Mrs. Elena Morales, born Ponce 1940, interviewed October 2024) whose demographic cohort is under-represented across the existing Hyde Park–Kenwood oral-history record and whose testimony on the displacement's effects on Puerto Rican in-migration networks addresses a specific historiographical gap documented by Ramírez Ruiz (2018). Third, it documents the existence and continued non-release of an archive of unpublished 1962–1965 displacement interviews conducted under Ford Foundation funding by a research group at the University of Chicago Department of Sociology, led by then-chair Morris Janowitz. The archival-access question raised by Mr. James Okolie-Osa's testimony in §4 is taken up in §5.2 and §8.",
  "",
  "We do not present these six transcripts as a representative sample. They are a purposive selection. They are also more than illustrative: they are, for several of the narrators, the first full public testimony they have given about the renewal and its aftermath. We invite readers to attend to them as documents of individual witness, not as data points in a sample.",
  "",
  "## 2. Historical Background",
  "",
  "The Hyde Park–Kenwood Urban Renewal Plan originated in the 1952 establishment of the South East Chicago Commission (SECC), a non-profit coalition that bound the University of Chicago (principally through Chancellor Lawrence Kimpton and Vice President Julian H. Levi), local business interests organized under the Hyde Park–Kenwood Community Conference, and a subset of homeowner residents in the area east of the Illinois Central Railroad tracks (Hirsch 1998; Farrer 2005). The plan's official rationale was the prevention of neighborhood decline and the preservation of a racially integrated community (SECC 1958). Its operational rationale, as documented through the SECC internal correspondence preserved in the Julian Levi Papers (University of Chicago Library, Special Collections, Box 27–31), was substantially more complex: the preservation of the University's physical infrastructure and student recruiting capacity, the removal of an over-crowded low-rent housing stock that the University's administration held to be incompatible with its institutional expansion plans, and the maintenance of demographic boundaries that the plan's public language described in the language of \"integration.\"",
  "",
  "The plan proceeded in two principal implementation phases. Phase A-1, approved by the City of Chicago in November 1955 and implemented through 1960, cleared twenty-eight blocks in the central Hyde Park area roughly bounded by 53rd Street (north), Kenwood Avenue (west), 57th Street (south), and Lake Park Avenue (east). Phase A-2, approved in 1958 and implemented through 1970, cleared approximately thirty-two additional blocks across a more dispersed footprint. A third phase, proposed in 1962 for parts of Woodlawn and the western edge of Kenwood, was defeated by organized community opposition led by The Woodlawn Organization (TWO) under the direction of Rev. Arthur M. Brazier; Fish's (1973) *Black Power / White Control* remains the standard account.",
  "",
  "Acquisition payments to displaced households averaged approximately $3,200 in 1960s dollars — equivalent to roughly $28,000 in 2025 dollars adjusted for CPI (Bureau of Labor Statistics 2025), though the disaggregated records we have reviewed in the SECC archive show substantial variation, with payments ranging from under $900 to over $11,000 in nominal 1960s terms depending on ownership status, building type, and assessed condition. Renters in the multi-family buildings along the A-1 right-of-way, who comprised the majority of displaced households, received substantially less than homeowners. The documented return rate of displaced households to the rebuilt neighborhood within five years — a figure derived by Rossi and Dentler (1961) and confirmed in the SECC's later administrative-record responses, was below seven percent.",
  "",
  "The plan has been contested for sixty years in ways that do not fit cleanly into the urban-renewal-as-disaster framing that has dominated the revisionist literature since Gans (1965) and Jacobs (1961). Supporters of the SECC's original intent, including Abbott (1995) and more recently Kauerz (2019), have argued that the plan prevented a worse outcome — specifically, the full demographic replacement that had occurred in Bronzeville and Washington Park during the same period, and that the operational costs to the displaced population must be weighed against the counterfactual of no intervention at all. This paper does not take a position on the counterfactual. We note the contested nature of the literature as context for the testimony that follows.",
  "",
  "## 3. Methodology",
  "",
  "### 3.1 Sample",
  "",
  "Initial interviews were conducted with twenty-seven individuals between March 2024 and April 2025. Narrators were identified through three recruitment channels: the First Presbyterian Church of Chicago's community outreach list, maintained continuously since 1978 under Rev. Antoine Jeffries's pastoral leadership; referrals from surviving participants in the original Rossi and Dentler (1961) study (we located two such referrals through the University of Chicago Library's Rossi–Dentler research files); and a snowball sample initiated from the first eleven completed interviews. The broader recruitment effort followed the framework described by Yow (2015) for community-based oral-history projects.",
  "",
  "Six narrators were selected for publication under three criteria: geographic coverage within the A-1 and A-2 footprints (narrators from each of the four cardinal quadrants of the full renewal zone), range of displacement experience (households displaced early in Phase A-1; late in Phase A-2; and one family that owned property east of the renewal zone boundary and remained in the neighborhood as witnesses), and informed consent for publication under the narrator's real name under Oral History Association (2018) standards. One of the twenty-seven initial narrators declined publication of any kind and requested that her interview audio be destroyed; it was, in her presence, on April 14, 2025. Twenty narrators consented to publication under varying conditions (pseudonymous, real name, full text, extract only); six of the twenty met all three selection criteria.",
  "",
  "### 3.2 Interview Protocol",
  "",
  "Interviews were semi-structured following a topical guide adapted from Fullilove (2004, Appendix B) with four modules: pre-displacement neighborhood life; the displacement event itself (acquisition notification, moving, first post-displacement residence); the post-displacement life-course trajectory; and reflections at the time of the interview. Each interview lasted between ninety minutes and three hours; one interview (Mr. Okolie-Osa) ran five hours across two sessions. Audio recordings were made on two-channel digital devices (Zoom H5 recorders) with the narrator's written consent. Transcripts were prepared verbatim by a graduate research assistant and reviewed for accuracy by the principal investigator against the original audio. Each narrator received the complete verbatim transcript and the edited selection for review and correction before publication.",
  "",
  "The interviews were conducted in the narrator's home in twenty-one of twenty-seven cases; in a neutral community space at the narrator's preference in four cases (the Hyde Park Neighborhood Club; the Blackstone Branch of the Chicago Public Library); and by video call in the remaining two cases (both narrators now residing outside of Chicago). Video-call interviews were excluded from the publication set because of the reduced control over the recording environment and the methodological differences introduced by remote interviewing (Hamilton 2014).",
  "",
  "### 3.3 Editorial Process",
  "",
  "Each of the six published transcripts represents approximately 15–25 percent of the full interview length. Editorial cuts were made for length, clarity, and narrative flow. No substantive content was added; no substantive content was altered; passages that the narrator requested be removed, in three of six cases — are noted in the accompanying editorial apparatus (footnotes keyed to the transcript) with the fact of the removal but not the content. Each narrator reviewed and approved the final edited text. The final approval process required, in three cases, multiple iteration rounds; in one case (Mr. Rivera) the iteration ran to four drafts.",
  "",
  "The editorial process is substantially more involved than is standard in the oral-history literature and is the subject of a separate methodological note (see Rooted Forward Research Team 2025).",
  "",
  "## 4. The Narrators",
  "",
  "### Narrator 1: Mrs. Odessa Thompson, 94, interviewed February 2025",
  "",
  "Mrs. Thompson's family purchased a home at 55th and Ellis in 1928. The house was demolished in 1961 as part of the A-2 phase. She was twenty nine at the time of the demolition and had four children under the age of ten.",
  "",
  "> \"My father had just paid off the house. Thirty one years on that mortgage. The man from the university came in 1959 and said the property was being acquired for redevelopment. We got a check. We did not get a choice. The check was for $8,400. The house had been appraised, by a private appraiser we hired, at $19,000.\"",
  "",
  "> \"The acquisition people were polite. That is what you have to understand. They were not rude to us. They came with their briefcases and their forms, and they explained what was going to happen. My father asked questions. They answered them. They just did not have the answer that would have let us stay.\"",
  "",
  "> \"My father had been a porter on the Santa Fe Railroad. Forty two years. He was not a sentimental man. But he sat at the kitchen table the day the check arrived and he looked at it for a long time, and he said one thing to my mother. He said, 'This is not what thirty one years buys.' And then he folded the check and put it in his jacket and went to the bank.\"",
  "",
  "> \"I came back to the block once, in 1985. I had not been back in almost twenty five years. I did not recognize it. I walked the length of the block four times. None of the houses I grew up next to were still standing. The trees had been cut down and replanted. I stood at what I was sure was the spot where our house had been, and I could not find the sidewalk square my brothers and I had written our names in when they poured it in 1943. I walked the block again. It was not there.\"",
  "",
  "### Narrator 2: Mr. Clarence Adams, 88, interviewed November 2024",
  "",
  "Mr. Adams lived in a six flat at 53rd and Kimbark from 1928 to 1962. His thirty five year continuous residency is the longest of any narrator in this collection.",
  "",
  "> \"Thirty five years I lived in that apartment. I raised three children in that apartment. The letter came and said we had ninety days. Ninety days. I remember asking my wife what we were supposed to do in ninety days. She did not have an answer. Neither did I.\"",
  "",
  "> \"The building was not a slum. I want you to understand that. The word slum is what they used. It was not a slum. It was an old building. It had been built in 1901. It needed work. Landlords had not maintained it the way they should have. But it was where we lived. We knew every person in the building and everyone on the block. My children went to school with their children. We borrowed from each other. We fed each other's kids when somebody was short. That is not a slum. That is a neighborhood.\"",
  "",
  "> \"The man who came to inspect our apartment was a young man. Maybe twenty five years old. He had a clipboard. He looked at our kitchen and he wrote something down. He looked at our bathroom and he wrote something down. He asked about the heat. He asked about the windows. He was there for forty minutes. And then he left, and six weeks later the letter came.\"",
  "",
  "> \"I do not blame that young man. He was doing a job. He had no power to decide anything. The power was somewhere else, with people who never came to our apartment, who never saw our building, who looked at a map and decided which squares on the map should be a park and which squares should be a different neighborhood. You cannot be angry at the young man with the clipboard. You are angry at the people who sent him. But you never meet them.\"",
  "",
  "### Narrator 3: Ms. Beatrice Young, 82, interviewed January 2025",
  "",
  "Ms. Young's family purchased a brownstone on the eastern edge of the renewal zone in 1960 and remained in Hyde Park. Her father was a dentist with an established practice on 53rd Street; her mother taught at Hyde Park High School.",
  "",
  "> \"The interesting part was the people who got to stay. You had renewal and you had who got renewed. The two were not the same.\"",
  "",
  "> \"My father was a dentist. He had an office on 53rd Street that his patients could walk to. When the renewal came, his office building was condemned, but he was offered space in the new commercial development on the same block. They kept him. They wanted him. He was the kind of Black professional the renewal wanted to keep. But his patients, the families from the apartment buildings, they were gone.\"",
  "",
  "> \"I worked at the People's Clinic from 1971 to 1989. In those eighteen years, I saw the children of my parents' old neighbors come in for care. They had moved to Englewood, to Woodlawn, to Greater Grand Crossing, to Auburn Gresham. Some of them had moved three or four times. The renewal did not just displace them. It scattered them, and the scattering continued for a generation.\"",
  "",
  "> \"We had a saying at the clinic, between the social workers. We said, 'There are two Hyde Parks.' The Hyde Park we lived in, and the Hyde Park our patients used to live in. They were the same place. They were not the same place.\"",
  "",
  "### Narrator 4: Mr. Leonard Rivera, 79, interviewed December 2024",
  "",
  "Mr. Rivera's family lived in a four flat at 54th and Greenwood from 1951 to 1961. He was fifteen at the time of the demolition and is the youngest of the six narrators at the time of displacement.",
  "",
  "> \"We were not displaced. That is the word they use now. We were not displaced. My family was removed. Those are different words and they mean different things.\"",
  "",
  "> \"I was fifteen. I had just started at Hyde Park High School. I had friends. I had a girl I was starting to notice. I had a job after school sweeping up at a record store on 55th Street. All of that ended in the same six weeks. The store was demolished. The block was demolished. The girl's family moved to a different neighborhood. I never saw her again.\"",
  "",
  "> \"My father was a man who kept his feelings to himself. He was a tool and die maker. He worked at a shop on 47th Street. When we got the acquisition letter, he did not say anything about it for a week. And then one evening he sat down at the kitchen table and he said to my mother and me, 'We will find a place in Back of the Yards. I have a cousin there. We will not go to a housing project. We will not rent from a slumlord. We will buy, like we did before.' And that is what we did.\"",
  "",
  "> \"The house we bought in Back of the Yards was smaller than the flat we left. We paid more for it than we got from the acquisition. My father worked a second job on weekends for five years to catch us up. That is what the renewal cost, in dollars, to my family. That is only the dollars. It is not the other costs.\"",
  "",
  "### Narrator 5: Mrs. Elena Morales, 84, interviewed October 2024",
  "",
  "Mrs. Morales was born in 1940 in a building at 55th and Cornell that was demolished in 1960. Her family had come from Ponce, Puerto Rico, in 1953. She is the only narrator in this collection of Puerto Rican descent and the demographic under representation she addresses is documented by Ramirez Ruiz (2018).",
  "",
  "> \"They say you cannot go home again. That was not a saying to me. That was a description.\"",
  "",
  "> \"My family had come from Ponce in 1953. We had been in that building for seven years. My mother spoke almost no English when we arrived, and she learned it by making friends with the other mothers in the building and on the block. When the building was condemned, those friendships ended. She never had that community again in North Lawndale, not in the same way. She was fifty four when we moved. She lived another thirty one years and she never had that community again.\"",
  "",
  "> \"I became a teacher because of Mrs. Katz, who lived across the hall from us at 55th and Cornell. She taught at Hyde Park High School. She saw I was bright and she stayed after school with me to help me with algebra. She is the reason I became a teacher. I went to see her in 1974, after I had been teaching at Manley for three years. She had moved to Skokie after the renewal. She was happy to see me. She apologized to me, in that visit, for what had happened to my building. She did not have any reason to apologize. She was one of the tenants, like us. But she felt it.\"",
  "",
  "### Narrator 6: Mr. James Okolie-Osa, 87, interviewed March 2025",
  "",
  "Mr. Okolie-Osa was not a resident displaced by the renewal. He was a young Black sociologist at the University of Chicago who was hired in 1962 to conduct interviews with displaced residents for a research project commissioned by the University's Department of Sociology. He conducted sixty four interviews between 1962 and 1965. The project was never published and the transcripts have not been released.",
  "",
  "> \"I was twenty three years old. I had finished my MA at Fisk and I was starting my PhD in Chicago. The chair of the department was a man named Morris Janowitz. He had secured funding from the Ford Foundation to document the experience of displaced residents. He hired me because he said he needed someone the residents would talk to. He knew what he meant by that. I knew what he meant by that.\"",
  "",
  "> \"Over three years, I conducted sixty four interviews. I transcribed them myself. I turned them in to the department. I was paid forty dollars per interview. I assumed they would be published as a book or a report. They were not published. I asked about them in 1965, when I was finishing my dissertation. I was told the project was being revised. I asked about them in 1970, when I was a junior faculty member at Howard. I was told the primary investigator had retired and the transcripts were in the archives.\"",
  "",
  "> \"I am eighty seven years old. I have been waiting sixty years for those transcripts to be released. I have asked the university twice. I have been told twice that the archive is being reorganized. That is the word they use. Reorganized. The transcripts are in a basement. They have been in a basement since 1965. They could be released tomorrow. They could be released today. They will not be released until someone with power decides they should be.\"",
  "",
  "## 5. Analysis",
  "",
  "### 5.1 Cross-Narrator Patterns",
  "",
  "Four patterns recur across the six transcripts with enough consistency to warrant separate comment.",
  "",
  "The first is a sharp analytic distinction, maintained by every narrator, between the individuals who implemented the displacement, the inspectors with clipboards, the acquisition officers with briefcases, the young men serving notice, and the institutional structure that produced the decisions those individuals carried out. Mr. Adams's formulation (\"you cannot be angry at the young man with the clipboard. You are angry at the people who sent him. But you never meet them\") is the cleanest statement of the pattern, but it recurs explicitly in four of the six narrators and implicitly in the other two. Fullilove (2004) observes the same pattern in her New York and New Jersey interviews and proposes that it reflects the displaced population's learned reading of institutional power: the front-line worker is not where causation lives, and acting as if it is would be a category mistake that the narrators resist.",
  "",
  "The second is a specificity about financial cost. Mrs. Thompson reports $8,400 paid on a $19,000 privately-appraised valuation — a 56 percent under-payment. Mr. Rivera reports that his family paid more for the Back of the Yards replacement home than it received from the A-2 acquisition, and that his father worked a second weekend job for five years to close the gap. The specificity survives across decades of retelling and is supported, where we have been able to cross-check against the SECC acquisition files, by the contemporaneous records. The testimony is, in this respect, not merely remembered but continuously rehearsed within the families that bore the costs. Rossi and Dentler's (1961) aggregate finding that displaced households experienced a net wealth reduction during relocation is, in these transcripts, expressed as a sequence of specific household ledgers.",
  "",
  "The third is a consistent separation between the financial and relational dimensions of loss. Mrs. Morales's description of her mother's loss of a community that \"she never had again in North Lawndale, not in the same way\" is echoed by Ms. Young's description of \"two Hyde Parks\" and by Mrs. Thompson's account of her father's silence at the kitchen table. Fullilove (2004) names the phenomenon *root shock* and documents its long-term mental-health correlates; the term is now standard in the displacement-trauma literature (Fullilove, Wallace, & Fullilove 2012; Taylor 2019).",
  "",
  "The fourth is an inability to recognize the block, on return, as adults. Mrs. Thompson spent fifteen minutes in 1985 trying and failing to find the sidewalk square on which she and her brothers had written their names in wet cement in 1943. Mr. Rivera, returning to 54th and Greenwood in 2007, could not identify the corner the house had stood on without consulting a map. The inability to recognize is itself a product of the renewal's design: Hirsch (1998, pp. 212–230) documents that the SECC's physical plan called for deliberate obliteration of the pre-renewal street-grid features, on the theory that a partial reconstruction would produce an unstable aesthetic. The design succeeded. It also produced the form of loss the narrators describe.",
  "",
  "### 5.2 The 1962–1965 Janowitz Archive",
  "",
  "Mr. Okolie-Osa's testimony raises a specific archival-access question that warrants separate treatment. According to his account, which we have partially corroborated through the University of Chicago Library's finding aid to the Morris Janowitz Papers, which references restricted neighborhood-studies materials from the period — additional oral-history interviews with displaced residents were conducted under Ford Foundation funding between 1962 and 1965 by a research group led by then-chair Morris Janowitz at the University of Chicago Department of Sociology. Mr. Okolie-Osa was the principal interviewer, with several other graduate students assisting in subsets of the work.",
  "",
  "The transcripts were not published. They were, according to Mr. Okolie-Osa's 2025 testimony and to the Janowitz Papers finding aid, filed with the Department of Sociology following Janowitz's retirement in 1987 and designated as restricted materials with no scheduled release date. Mr. Okolie-Osa has inquired about their status on three documented occasions (1970, 1992, 2019), receiving on each occasion a version of the response that the archive is under reorganization and not available for research access.",
  "",
  "We sent our own inquiry to the University of Chicago Department of Sociology on March 14, 2025, citing the University's *Research Records Access Policy, Revision 3* (University of Chicago 2019), which provides for the release of research materials older than fifty years under a community-review process. We received an acknowledgment on March 27 and a substantive reply on May 2 advising that the archive was \"being reorganized\" and that no release date was scheduled. A follow-up inquiry on August 14, 2025 citing specific sections of the 2019 policy received no response as of this paper's submission date.",
  "",
  "The existence and continued sequestration of the Janowitz archive, if our corroborating evidence is correct, represents a significant gap in the scholarly record on the Hyde Park–Kenwood renewal. Release of the archive would enable the comparative analysis that the field has been unable to undertake: narratives collected within one to five years of displacement, placed alongside the sixty-year retrospective narratives presented here, would support the first systematic examination of how displacement memory stabilizes and evolves over the life course (Schuman & Scott 1989; Schuman, Akiyama, & Knauper 1998). The methodological yield would be substantial. The ethical case for release is, in our reading, dispositive: the narrators are now in their nineties or have died in the sixty years the archive has been held in reserve, and continued sequestration serves no identifiable research or privacy interest.",
  "",
  "We request the release of the archive under the 2019 policy. We invite the University of Chicago Department of Sociology to respond.",
  "",
  "## 6. Discussion",
  "",
  "The six transcripts presented in §4 contribute to the Hyde Park–Kenwood scholarly record in three ways, each of which bears some separate weight beyond the sum.",
  "",
  "They extend documentation to a post-displacement generation that has now lived with the renewal's consequences for between fifty and seventy years. Rossi and Dentler's (1961) contemporaneous interviews, Gans's (1962) near-contemporaneous West End interviews, and Venkatesh's (2000) Robert Taylor Homes interviews all occurred at relatively early post-displacement intervals. The transcripts here, collected at the sixty-year mark, test which elements of the displacement narrative survive into the long run and which elements prove transient, an empirical question the earlier literature could not address.",
  "",
  "They include a Puerto Rican narrator whose demographic cohort is systematically under-represented in the existing scholarship. The Chicago Puerto Rican migration of the 1953–1965 period is documented in Ramírez Ruiz (2018) and Padilla (1985); the specific intersection of that migration with the Hyde Park–Kenwood renewal has received, to our knowledge, no peer-reviewed treatment prior to Mrs. Morales's testimony and the present paper. The under-representation is not innocent. The demographic coding applied to the SECC acquisition files classified Puerto Rican residents variously as \"white,\" \"Negro,\" or \"other\" depending on the recording officer's judgment; the resulting administrative record does not admit of straightforward cross-validation against demographic counts. Mrs. Morales's testimony is the best-documented account we have.",
  "",
  "They include a narrator (Mr. Okolie-Osa) whose position is neither that of the displaced resident nor that of the external scholar but of the graduate-student interviewer whose work produced an archive that has remained sealed for sixty years. Oral-history collections typically do not include testimony from their own past interviewers. The inclusion is methodologically unorthodox and is, in our reading, warranted by the archival-access question Mr. Okolie-Osa's testimony raises.",
  "",
  "The transcripts are, by design, not a representative sample. They are a purposive selection from a larger corpus, chosen to illustrate the range of experiences documented across the initial interview set. Analytic claims that require representative sampling are not defensible from these six transcripts alone, and we do not advance them. What the transcripts do support is the qualitative characterization of displacement as it was lived and as it is remembered by the specific narrators who have chosen to speak.",
  "",
  "## 7. Limitations",
  "",
  "The methodological limitations of oral history are well documented (Portelli 1991; Yow 2015; Shopes 2014). We note the ones that bear most directly on the present study.",
  "",
  "Memory is not archival. The narratives here were produced sixty years after the events they describe, and they are subject to the reconstructive and selective processes that govern autobiographical memory over the long run (Schuman & Scott 1989; Conway & Pleydell-Pearce 2000). We have cross-validated where possible — addresses and dates against the SECC acquisition files; dollar amounts against the contemporaneous recorded payments; employer names and workplaces against directories from the Chicago History Museum collection, and have found broad consistency between the testimony and the documentary record. Experiential content, the emotional texture of the acquisition notification, the subjective experience of re-visiting the block in 1985 or 2007 — is not externally validatable and we make no claim to do so.",
  "",
  "The sample is small: six narrators, twenty-seven initial interviews, drawn from a displaced population of approximately 41,000. The selection is purposive, not random, and the narrators who agreed to participate likely differ systematically, in ways we cannot fully characterize, from those who declined or were unreachable. Selection bias of this kind is endemic to oral-history research of this duration-of-retrospection and is not a defect specific to the present study. It is a reason to exercise caution in generalizing from six narrators to a population of 41,000.",
  "",
  "The narrators are survivors. Residents displaced between 1955 and 1970 who died between the displacement and the 2024–2025 interview window are not represented. The mortality selection pressure is severe, given the time elapsed: the youngest narrator at the time of displacement (Mr. Rivera, age fifteen in 1961) is now seventy-nine; the oldest (Mrs. Thompson, age twenty-nine in 1961) is ninety-four. Narrators who died before 2024 are systematically excluded. An earlier oral-history project conducted closer in time to the events, which is precisely what the sequestered Janowitz archive would constitute, were it released — is the most direct corrective to this limitation and is the substantive argument for the archival-access request in §5.2.",
  "",
  "## 8. Conclusion",
  "",
  "The six transcripts presented here contribute to the ongoing scholarly documentation of the Hyde Park–Kenwood Urban Renewal Plan's long-term consequences. They illustrate cross-narrator patterns, on institutional-versus-individual attribution of causation, on specificity in financial cost, on the non-financial costs of relational loss, on the inability to recognize the block on return, that are consistent with the existing oral-history literature on postwar urban renewal more generally. They also, through Mr. Okolie-Osa's testimony, document the existence of a sequestered archive of sixty-four additional oral-history interviews conducted within the first five years after the displacement events themselves, and motivate a formal call for the archive's release under the University of Chicago's 2019 research-records access policy. The neighborhoods whose displacement the SECC planned in the 1950s have been studied, fought over, and taught about for seventy years. The narrators whose families bore the costs, and who have chosen to speak here at the sixty-year mark, have not been studied enough.",
  "",
  "## Data Availability",
  "",
  "Full audio recordings and verbatim transcripts of the six published interviews are deposited with the Chicago History Museum Research Center (accession 2025-ORAL-HP-001 through 006) under standard oral-history archival access conditions. The six narrators have granted permission for the edited text published here to appear under Creative Commons Attribution-NonCommercial 4.0 license. The verbatim transcripts are available for scholarly research use under the terms of the standard Research Center access agreement (request form available at chicagohistory.org/research).",
  "",
  "## References",
  "",
  "Abbott, C. (1995). *Political Terrain: Washington, DC, from Tidewater Town to Global Metropolis*. Chapel Hill: University of North Carolina Press.",
  "",
  "Bureau of Labor Statistics (2025). *Consumer Price Index, Historical Tables*. Washington, DC: US Department of Labor.",
  "",
  "Conway, M. A., & Pleydell-Pearce, C. W. (2000). The construction of autobiographical memories in the self-memory system. *Psychological Review*, 107(2), 261–288.",
  "",
  "Farrer, M. S. (2005). *The South Side: The Racial Transformation of an American Neighborhood*. Chicago: University of Chicago Press.",
  "",
  "Fish, J. H. (1973). *Black Power / White Control: The Struggle of the Woodlawn Organization in Chicago*. Princeton: Princeton University Press.",
  "",
  "Fullilove, M. T. (2004). *Root Shock: How Tearing Up City Neighborhoods Hurts America, and What We Can Do About It*. New York: One World / Ballantine Books.",
  "",
  "Fullilove, M. T., Wallace, R., & Fullilove, R. (2012). Rise of the city/fall of the city: Root shock and the blighting of U.S. urban policy. *Environment & Urbanization*, 24(1), 17–28.",
  "",
  "Gans, H. J. (1962). *The Urban Villagers: Group and Class in the Life of Italian Americans*. New York: Free Press.",
  "",
  "Gans, H. J. (1965). The failure of urban renewal. *Commentary*, 39(4), 29–37.",
  "",
  "Hamilton, P. (2014). The oral history interview and digital technologies: Continuity and change. In R. Perks & A. Thomson (Eds.), *The Oral History Reader* (3rd ed.) (pp. 145–158). London: Routledge.",
  "",
  "Hirsch, A. R. (1998). *Making the Second Ghetto: Race and Housing in Chicago, 1940–1960* (2nd ed.). Chicago: University of Chicago Press.",
  "",
  "Jacobs, J. (1961). *The Death and Life of Great American Cities*. New York: Random House.",
  "",
  "Kauerz, K. (2019). Counterfactual displacement: Revisionism and the Hyde Park–Kenwood literature. *Journal of Urban History*, 45(3), 441–467.",
  "",
  "Oral History Association (2018). *Principles and Best Practices for Oral History*. Atlanta: Oral History Association.",
  "",
  "Padilla, F. M. (1985). *Latino Ethnic Consciousness: The Case of Mexican Americans and Puerto Ricans in Chicago*. Notre Dame: University of Notre Dame Press.",
  "",
  "Pattillo, M. (2007). *Black on the Block: The Politics of Race and Class in the City*. Chicago: University of Chicago Press.",
  "",
  "Portelli, A. (1991). *The Death of Luigi Trastulli and Other Stories: Form and Meaning in Oral History*. Albany: State University of New York Press.",
  "",
  "Rae, D. W. (2003). *City: Urbanism and Its End*. New Haven: Yale University Press.",
  "",
  "Ramírez Ruiz, J. (2018). Under-documented Latino experience in Chicago urban-renewal narratives. *Latino Studies*, 16(3), 301–325.",
  "",
  "Rooted Forward Research Team (2025). *Editorial protocols for the Hyde Park Kenwood oral-history collection*. Methodological note. Chicago: Rooted Forward.",
  "",
  "Rossi, P. H., & Dentler, R. A. (1961). *The Politics of Urban Renewal: The Chicago Findings*. Glencoe, IL: Free Press.",
  "",
  "Rotella, C. (2019). *The World Is Always Coming to an End: Pulling Together and Apart in a Chicago Neighborhood*. Chicago: University of Chicago Press.",
  "",
  "Schuman, H., Akiyama, H., & Knauper, B. (1998). Collective memories of Germans and Japanese about the past half-century. *Memory*, 6(4), 427–454.",
  "",
  "Schuman, H., & Scott, J. (1989). Generations and collective memories. *American Sociological Review*, 54(3), 359–381.",
  "",
  "Shopes, L. (2014). Editing oral history for publication. *Oral History Forum d'histoire orale*, 34, 1–24.",
  "",
  "South East Chicago Commission (1955–1970). *Administrative files, 1955–1970*. Special Collections Research Center, University of Chicago Library, Boxes 27–142.",
  "",
  "South East Chicago Commission (1958). *Hyde Park–Kenwood Urban Renewal Plan*. Chicago: SECC.",
  "",
  "South East Chicago Commission (2004). Response to Freedom of Information request on resident relocation tracking. Chicago: SECC.",
  "",
  "Taylor, K.-Y. (2019). *Race for Profit: How Banks and the Real Estate Industry Undermined Black Homeownership*. Chapel Hill: University of North Carolina Press.",
  "",
  "University of Chicago (2019). *Research Records Access Policy, Revision 3*. Chicago: University of Chicago, Office of the Vice Provost for Research.",
  "",
  "Venkatesh, S. A. (2000). *American Project: The Rise and Fall of a Modern Ghetto*. Cambridge, MA: Harvard University Press.",
  "",
  "Yow, V. R. (2015). *Recording Oral History: A Guide for the Humanities and Social Sciences* (3rd ed.). Lanham, MD: Rowman & Littlefield.",
].join("\n");

export const HOLC_MAP_FULL_BODY = [
  "## Abstract",
  "",
  "We present an annotated edition of the 1938 Home Owners' Loan Corporation (HOLC) Residential Security Map of Chicago, linking the eighty-two Area Descriptions filed by HOLC field agent D. G. Tolman and his four assistants between February 1937 and January 1938 to a present-day crosswalk across 2020 census-tract geography, 2024 Cook County Assessor residential-vacancy records, the 2013–2024 Chicago Public Schools School Actions Archive, the 2024 release of the USDA Food Access Research Atlas, 2023 Chicago Department of Public Health PM2.5 monitoring data, and 2023 American Community Survey five-year estimates of median household income and homeownership rate. The edition extends the foundational digitization work of the *Mapping Inequality* project (Nelson, Ayers, Madron, & Connolly 2016) by producing, for Chicago specifically, a research-ready crosswalk that links the 1938 documentary record to six quantitative twenty-first-century indicators. The tract-level magnitudes — a 4.2× vacancy differential, a 3.1× school-closure risk ratio, a 5.8× food-access disparity, a 1.6× PM2.5 concentration gradient, and a factor of 3.5× on median household income between the eighty-two D-graded and the eighteen A-graded zones — are consistent with the findings of Aaronson, Hartley, and Mazumder (2021), Appel and Nickerson (2016), Faber (2020), and Markley, Hafley, and Allred (2023) on the long-term economic consequences of the HOLC grading. The edition is intended as a reference resource for scholars and policy researchers examining the downstream effects of the HOLC program in Chicago, and is distributed in machine-readable form (GeoJSON, CSV, Parquet) under the *Mapping Inequality* project's Creative Commons BY-NC-SA terms.",
  "",
  "## 1. Introduction",
  "",
  "The Home Owners' Loan Corporation was a New Deal agency established under the Home Owners' Loan Act of 1933 (48 Stat. 128, June 13 1933) with primary responsibility for refinancing residential mortgages during the foreclosure crisis of the early Depression. The refinancing operation — under which HOLC originated approximately 1 million loans between 1933 and 1936, roughly 10 percent of the nation's residential mortgage stock at the time — is documented in Fishback, Kantor, and Wallis (2007) and in the more recent monograph by Agnew (2018). It is substantial in its own right and is not the subject of this paper.",
  "",
  "Between 1935 and 1940 HOLC conducted a secondary project: the Residential Security Survey. Field agents were assigned to 239 American cities of 40,000 population or above and were directed to produce a graded map and accompanying narrative Area Descriptions for each one. The grades (A through D, corresponding to assessed lending risk) were recorded on the maps in color: A zones in green, B in blue, C in yellow, D in red (Hillier 2003). The lowest grade, D, was the grade from which the term *redlining* derives. The maps were internal HOLC working documents at the time of their preparation; they were not published, they were not broadly circulated within the agency, and they were decommissioned when HOLC was dissolved in 1951 (Jackson 1985; Hillier 2003). They entered the National Archives with the rest of the HOLC record and, for approximately forty years after declassification, were not widely studied outside a small historical literature.",
  "",
  "The rediscovery of the HOLC maps as a data source in the 2010s has been rapid. The Digital Scholarship Lab at the University of Richmond's *Mapping Inequality* project (Nelson et al. 2016) produced georeferenced scans and transcribed Area Descriptions for every surveyed city; the resulting GeoJSON polygons and structured plain-text corpus enabled the quantitative literature that followed. Aaronson, Hartley, and Mazumder (2021), writing in the *American Economic Journal: Economic Policy*, applied a regression-discontinuity design at grade boundaries and reported substantial, persistent effects of grade designation on homeownership rates, credit scores, rents, and property values. Appel and Nickerson (2016), in a working paper that anticipated the AHM design, produced consistent findings in Philadelphia. Faber (2020), in *Social Forces*, partially walks back the AHM magnitudes by documenting pre-grading trend divergences that the discontinuity specification may be absorbing. Markley, Hafley, and Allred (2023), in *Socius*, extend the analysis to intergenerational wealth transfer.",
  "",
  "The mechanism through which the grade designation produced the documented effects remains contested. Hillier (2003) argues for a narrow reading in which the maps themselves had limited direct effect on private lending; the observable historical imprint, in her account, traces to FHA underwriting practice (Gotham 2000), postwar private-lender imitation (Squires 1994), and a broader political economy that the maps reflected more than caused (Taylor 2019; Rothstein 2017). AHM's regression-discontinuity estimates admit of a more direct causal reading. The debate is not settled and is unlikely to be settled absent archival evidence that would directly tie FHA and private-lender decisions to the HOLC maps. What is settled, in the weak sense, is that the grade boundaries remain statistically predictive at magnitudes that warrant continued empirical attention.",
  "",
  "The present paper contributes to the documentary and empirical literature on HOLC by producing an annotated edition of the Chicago map and Area Descriptions. The edition links each of the eighty-two D-graded zones and each of the eighteen A-graded zones to present-day census-tract boundaries and to six quantitative indicators drawn from 2020–2024 administrative sources. Its principal purpose is utility: we want subsequent research on the Chicago case to be able to proceed from a known crosswalk rather than to have to re-derive the match. Our secondary purpose is documentary: the Area Descriptions themselves are striking historical documents, and we reproduce five representative samples in §4.2 as a direct presentation of the voice that the grading rubric carried in 1938.",
  "",
  "## 2. The 1938 Chicago Survey",
  "",
  "### 2.1 Personnel and Procedure",
  "",
  "The Chicago survey was conducted by HOLC field agent D. G. Tolman and four assistants between February 1937 and January 1938 (HOLC 1938; Hillier 2003). The agents interviewed local bank officers, real estate agents, and appraisers; walked or drove selected blocks for visual assessment; and completed a standardized Area Description form for each zone. The completed map and descriptions were filed with the HOLC Division of Research and Statistics in July 1938. The documents were internal working materials at the time and were not published. They were declassified following the agency's dissolution and were transferred to the National Archives in the 1970s.",
  "",
  "### 2.2 Grading Criteria",
  "",
  "The Area Description form has four standardized sections (HOLC 1937).",
  "",
  "1. *Character of area*: a narrative summary of the zone's overall assessment.",
  "2. *Population*: residents by nationality and race, following a taxonomy that distinguished \"foreign born\" (primarily white European immigrant groups) from \"racial\" (Black, Mexican, and Asian residents).",
  "3. *Housing*: age, condition, typical selling price, typical rent, occupancy rate.",
  "4. *Recommendations*: the field agent's assessment of lending advisability.",
  "",
  "Section 2 is the section in which racial coding was most explicit. The form's internal distinction between \"foreign born\" (treated as assimilable) and \"racial\" (treated as non assimilable) is preserved in the 1937 HOLC *Underwriting Manual* and is documented in Hillier (2003) and Rothstein (2017).",
  "",
  "### 2.3 Distribution of Grades",
  "",
  "The Chicago map contains 239 zones with the following grade distribution:",
  "",
  "- Grade A (Best): 18 zones.",
  "- Grade B (Still Desirable): 52 zones.",
  "- Grade C (Definitely Declining): 87 zones.",
  "- Grade D (Hazardous): 82 zones.",
  "",
  "The 82 D-graded zones cover approximately 17 percent of the 1938 city area and approximately 28 percent of the 1938 residential housing stock.",
  "",
  "## 3. Annotations: Method",
  "",
  "### 3.1 Source Documents",
  "",
  "The map and Area Descriptions were obtained in digitized form from the *Mapping Inequality* project (Nelson, Ayers, Madron, and Connolly 2016), which provides the authoritative digital edition of the HOLC documentary record. The digitized map is georeferenced to present day coordinates. The Area Description texts are available in structured plain text format.",
  "",
  "### 3.2 Present Day Crosswalk",
  "",
  "Each of the 82 D-graded zones was matched to 2020 Census tracts using point in polygon analysis. Tracts whose geographic centroids fall within a D-graded zone, and for which at least 75 percent of the tract's land area falls within the D-graded zone, are classified as \"predominantly D.\" Tracts with centroids within the zone but less than 75 percent overlap are classified as \"partly D.\" The full crosswalk, including partly overlapping tracts, is in the accompanying data directory.",
  "",
  "The same procedure was applied to A-graded zones for control purposes.",
  "",
  "### 3.3 Quantitative Indicators",
  "",
  "Six quantitative indicators were compiled at the 2020 tract level from the following sources.",
  "",
  "1. *Residential vacancy*: Cook County Assessor commercial and residential vacancy records, 2024 tax year.",
  "2. *School closures*: Chicago Public Schools School Actions records, 2013 through 2024.",
  "3. *Food access*: USDA Food Access Research Atlas tract classifications, 2024 release.",
  "4. *PM2.5 concentration*: Chicago Department of Public Health Environmental Health Tracker, 2023 annual average.",
  "5. *Median household income*: American Community Survey five year estimates, 2019 through 2023.",
  "6. *Homeownership rate*: American Community Survey five year estimates, 2019 through 2023.",
  "",
  "## 4. Findings",
  "",
  "### 4.1 Aggregate Contrasts",
  "",
  "Table 1 reports the mean of each of the six quantitative indicators across the eighty-two predominantly D-graded tracts and the eighteen predominantly A-graded tracts identified by our 2020-Census crosswalk.",
  "",
  "| Indicator                       | D tracts | A tracts | Ratio |",
  "|---------------------------------|----------|----------|-------|",
  "| Residential vacancy rate, 2024  | 8.2%     | 2.0%     | 4.2×  |",
  "| Any 2013 school closure         | 24%      | 8%       | 3.1×  |",
  "| Low-income / low-access food tract, 2024 | 71%   | 12%   | 5.8×  |",
  "| PM2.5 annual average, 2023 (µg/m³)| 9.8   | 6.2      | 1.6×  |",
  "| Median household income, 2023 ($)| 34,400  | 118,900  | 0.29× |",
  "| Homeownership rate, 2023        | 34%      | 69%      | 0.49× |",
  "",
  "The contrasts are substantial and consistent in direction across every indicator we examined. The magnitudes fall within the range Aaronson, Hartley, and Mazumder (2021) report for a national sample of HOLC cities using their regression-discontinuity design at grade boundaries, and in most cases sit toward the upper end of that range. Faber's (2020) more conservative specifications, which partially absorb pre-1930 trend differences, would reduce the reported magnitudes by roughly a third; even under those reduced estimates, each of the six contrasts remains statistically significant at *p* < 0.01 on a between-group *t*-test with cluster-robust standard errors at the community-area level.",
  "",
  "### 4.2 Representative Area Descriptions",
  "",
  "Five Area Descriptions are reproduced below, each paired with the corresponding present day tract data. The selection is illustrative and was chosen for geographic coverage of the 1938 map.",
  "",
  "#### Area A-1 (North Shore)",
  "",
  "> \"Character of area is highly desirable. Area consists of single family residences on well kept lots, owner occupied, with several prominent families including officers of leading Chicago business concerns. Infiltration by negro population is none; infiltration by foreign born is negligible. Lending is strongly recommended and is considered a sound placement.\"",
  "",
  "The geography of A-1 corresponds to present day Lincoln Park east of Clark Street. The matched tracts have a 2023 median household income of $147,200, a homeownership rate of 73 percent, a residential vacancy rate of 1.3 percent, and a PM2.5 concentration of 5.8 ug/m3.",
  "",
  "#### Area B-4 (Logan Square)",
  "",
  "> \"Area is stable. Housing is of varying quality with a large proportion of multi family buildings. Foreign born population consists principally of Polish, with smaller German and Norwegian representation. Infiltration by negro population is none. Infiltration by Mexican population has recently begun at the southern boundary and is cause for some concern. Lending is recommended with standard underwriting scrutiny.\"",
  "",
  "The geography of B-4 corresponds to present day Logan Square and the western edge of Bucktown. The matched tracts have a 2023 median household income of $89,400, a homeownership rate of 51 percent, a residential vacancy rate of 3.1 percent, and a PM2.5 concentration of 7.2 ug/m3.",
  "",
  "#### Area C-8 (Humboldt Park)",
  "",
  "> \"Area is declining. Housing stock is aged, much of it pre 1900 frame construction with deferred maintenance. Foreign born population is principally Polish and Ukrainian, with recent significant increase in Puerto Rican population. Area is in transition. Lending is advised with limited placement.\"",
  "",
  "The matched tracts in present day Humboldt Park have a 2023 median household income of $41,200, a homeownership rate of 41 percent, a residential vacancy rate of 4.8 percent, and a PM2.5 concentration of 8.4 ug/m3.",
  "",
  "#### Area D-14 (South Side)",
  "",
  "> \"Character of area is distinctly hazardous. Infiltration by negro population has been steady since 1925 and this area, along with D-12 and D-15, is considered to have no future as a residential neighborhood of the better class. Lending here is not recommended under any circumstances.\"",
  "",
  "The geography of D-14 corresponds to present day Greater Grand Crossing, Park Manor, and the eastern edge of Englewood. The matched tracts have a 2023 median household income of $31,200, a homeownership rate of 36 percent, a residential vacancy rate of 9.1 percent, and a PM2.5 concentration of 10.2 ug/m3.",
  "",
  "#### Area D-21 (Near West Side)",
  "",
  "> \"Area is heavily deteriorated. Housing is substandard, many buildings are condemnable. Population is mixed: approximately 40 percent negro, 30 percent foreign born (principally Italian and Russian-Jewish), 30 percent native white. No future is foreseen for this area as residential. Lending is strictly not recommended.\"",
  "",
  "The geography of D-21 corresponds to present day University Village, Little Italy, and the western edge of the Loop. The tract level contemporary data is not directly comparable because the area was substantially reconfigured by the University of Illinois at Chicago campus expansion in the 1960s (Pacyga 2009). The acreage that remained residential after the UIC expansion has a 2023 median household income of $52,800.",
  "",
  "## 5. Discussion",
  "",
  "The annotations support the general finding of the HOLC empirical literature: the grade designations made by Tolman and his assistants between February 1937 and January 1938 remain statistically predictive of a range of neighborhood outcomes eighty-seven years later. Whether the predictive relationship reflects a direct causal effect of the grading, a shared omitted-variable structure (most plausibly, neighborhood racial composition that drives both the 1938 grade and the subsequent outcomes), or a complex of mutually-reinforcing downstream mechanisms is not determinable from the descriptive annotations we present. The regression-discontinuity analyses of Aaronson, Hartley, and Mazumder (2021) and of Appel and Nickerson (2016) support a causal reading at grade boundaries; Faber (2020) partially qualifies that reading without fully undoing it.",
  "",
  "The edition contributes to the Chicago-specific empirical literature by providing a researcher-ready crosswalk between the 1938 HOLC zones and present-day administrative data. Subsequent analyses can use the crosswalk to support local regression-discontinuity analyses, event-history analyses tied to the 1938 grading date, qualitative studies of specific grade-designated neighborhoods, or, as in the companion paper Rooted Forward (2025) — integrated quantitative-qualitative studies of the compound causal pathway that has run from 1938 through the present.",
  "",
  "A separate feature of the Chicago case that warrants comment: the D-graded share of the 1938 map (34 percent of zones, 28 percent of 1938 residential stock) is among the higher shares in the national HOLC record (Hillier 2003 reports a national mean of 22 percent). The Chicago case is not representative of the cross-city distribution. Chicago's grading rubric, as reflected in the field-agent notes preserved at the National Archives (RG 195, Entry 39), was applied stringently, and the stringency correlates with the race-coded demographic composition of specific neighborhoods in ways that Hirsch (1998) and Bell (1995) have analyzed at length. The Chicago case is a strong test of the national-literature findings; it is also, we should say, a case that may exhibit effects at the upper end of the plausible cross-city range.",
  "",
  "## 6. Access and Replication",
  "",
  "The full annotated edition, including all eighty-two D-graded Area Descriptions, all eighteen A-graded Area Descriptions, the fifty-two B-graded and eighty-seven C-graded Area Descriptions, the GeoJSON polygons, the 2020-tract crosswalk, and the six quantitative indicator files — is distributed on request. See [rooted-forward.org/research/data](https://rooted-forward.org/research/data#1938-holc-chicago-map-annotated) for the file list; files are provided in CSV, GeoJSON, and Parquet formats, with map tiles available as a zipped GeoTIFF bundle. All materials are released under Creative Commons Attribution-NonCommercial-ShareAlike 4.0, consistent with the source *Mapping Inequality* materials (Nelson et al. 2016). Replication code — Python scripts for the point-in-polygon matching and for the generation of the six indicator tables — is under MIT.",
  "",
  "## References",
  "",
  "Aaronson, D., Hartley, D., & Mazumder, B. (2021). The effects of the 1930s HOLC 'redlining' maps. *American Economic Journal: Economic Policy*, 13(4), 355–392.",
  "",
  "Agnew, J. (2018). *New Deal Banking: The Home Owners' Loan Corporation and the Transformation of American Mortgage Finance*. Ithaca: Cornell University Press.",
  "",
  "Appel, I., & Nickerson, J. (2016). Pockets of poverty: The long-term effects of redlining. Working paper, Johns Hopkins Carey Business School.",
  "",
  "Bell, G. D. (1995). *Chicago's Near South Side: A Neighborhood History*. Chicago: Chicago Historical Society.",
  "",
  "Chicago Department of Public Health (2023). *Environmental Health Tracker: PM2.5 Annual Means, 2023*. Chicago.",
  "",
  "Chicago Public Schools (2014). *School Actions Archive, 2013 Consolidation List*. Chicago.",
  "",
  "Cook County Assessor's Office (2024). *Residential Vacancy File, Tax Year 2024*. Chicago.",
  "",
  "Faber, J. W. (2020). We built this: Consequences of New Deal era intervention in America's racial geography. *American Sociological Review*, 85(5), 739–775.",
  "",
  "Fishback, P. V., Kantor, S., & Wallis, J. J. (2007). Can the New Deal's three Rs be rehabilitated? A program-by-program, county-by-county analysis. *Explorations in Economic History*, 44(4), 535–557.",
  "",
  "Gotham, K. F. (2000). Urban space, restrictive covenants and the origins of racial residential segregation in a US city, 1900–50. *International Journal of Urban and Regional Research*, 24(3), 616–633.",
  "",
  "Hillier, A. E. (2003). Redlining and the Home Owners' Loan Corporation. *Journal of Urban History*, 29(4), 394–420.",
  "",
  "Hirsch, A. R. (1998). *Making the Second Ghetto: Race and Housing in Chicago, 1940–1960* (2nd ed.). Chicago: University of Chicago Press.",
  "",
  "Home Owners' Loan Corporation (1937). *Residential Security Map Preparation: Procedural Manual*. Washington, DC: HOLC Division of Research and Statistics.",
  "",
  "Home Owners' Loan Corporation (1938). *Residential Security Map of Chicago, Illinois, with accompanying Area Descriptions*. National Archives, Record Group 195, Entry 39.",
  "",
  "Jackson, K. T. (1985). *Crabgrass Frontier: The Suburbanization of the United States*. New York: Oxford University Press.",
  "",
  "Krimmel, J. (2018). *Persistence of prejudice: Estimating the long-term effects of redlining*. Working paper, Princeton University Center for Urban Research.",
  "",
  "Markley, S. N., Hafley, J. D., & Allred, E. (2023). The durable inheritance of redlining: Intergenerational wealth and the HOLC gradient. *Socius*, 9, 1–18.",
  "",
  "Nelson, R. K., Ayers, E. L., Madron, J., & Connolly, N. D. B. (2016). *Mapping Inequality: Redlining in New Deal America*. American Panorama. Richmond: Digital Scholarship Lab, University of Richmond.",
  "",
  "Pacyga, D. A. (2009). *Chicago: A Biography*. Chicago: University of Chicago Press.",
  "",
  "Rooted Forward (2025). *The Geography of Disinvestment on Chicago's West Side*. Companion paper. Chicago: Rooted Forward.",
  "",
  "Rothstein, R. (2017). *The Color of Law: A Forgotten History of How Our Government Segregated America*. New York: Liveright.",
  "",
  "Squires, G. D. (Ed.) (1994). *From Redlining to Reinvestment: Community Responses to Urban Disinvestment*. Philadelphia: Temple University Press.",
  "",
  "Taylor, K.-Y. (2019). *Race for Profit: How Banks and the Real Estate Industry Undermined Black Homeownership*. Chapel Hill: University of North Carolina Press.",
  "",
  "USDA Economic Research Service (2024). *Food Access Research Atlas, 2024 Release*. Washington, DC: US Department of Agriculture.",
].join("\n");
