"use client";
/* ------------------------------------------------------------------ */
/*  Fetch-once hooks for the exhibit's pre-projected map data. The     */
/*  JSONs under public/exhibit-data are generated by scripts run in    */
/*  parallel with this code, so both hooks are resilient by design.    */
/*  A missing file resolves to { data: null, error }, never a throw,   */
/*  and every consumer renders a quiet placeholder path instead of     */
/*  dead-ending the tour. A module-level promise cache guarantees at   */
/*  most one network request per file per page load, shared across     */
/*  every MapStage, HolcLayer, and interactive on the page.            */
/* ------------------------------------------------------------------ */
import { useEffect, useState } from "react";
import type { MapFrame, RingPoints } from "./projection";

export type FrameId = "hydePark" | "citywide";
export type HolcGrade = "A" | "B" | "C" | "D";

export interface HolcArea {
  id: number | string;
  /** "A" | "B" | "C" | "D" in practice, plus "ungraded" areas in the source data */
  grade: HolcGrade | string;
  label: string;
  name?: string | null;
  centroid: Partial<Record<FrameId, [number, number]>>;
  rings: Partial<Record<FrameId, RingPoints[]>>;
}

export interface HolcFramesDoc {
  attribution?: string;
  frames: Partial<Record<FrameId, MapFrame>>;
  areas: HolcArea[];
}

export interface FrameLayerPark {
  name?: string | null;
  ring: RingPoints;
}

/**
 * Neighborhood label. The generator has shipped two spellings of this
 * record ({text,x,y} and {t,xy,role}); both are accepted and normalized
 * by the stage so a data regeneration never crashes the map.
 */
export interface FrameLayerLabel {
  text?: string;
  x?: number;
  y?: number;
  t?: string;
  xy?: [number, number];
  role?: string;
}

export interface FrameLayersDoc {
  frame?: MapFrame;
  attribution?: string;
  /** tolerated as a single ring or a list of rings */
  lake?: RingPoints | RingPoints[];
  parks?: FrameLayerPark[];
  boundary?: RingPoints | RingPoints[];
  labels?: FrameLayerLabel[];
}

export interface MapDataState<T> {
  data: T | null;
  error: string | null;
  loading: boolean;
}

export const HOLC_FRAMES_URL = "/exhibit-data/holc-frames.json";
export const FRAME_LAYERS_URL = "/exhibit-data/hp-frame-layers.json";

interface CacheEntry {
  promise: Promise<void>;
  data: unknown;
  error: string | null;
  done: boolean;
}

const cache = new Map<string, CacheEntry>();

function load(url: string): CacheEntry {
  const hit = cache.get(url);
  if (hit) return hit;
  const entry: CacheEntry = { promise: Promise.resolve(), data: null, error: null, done: false };
  entry.promise = fetch(url)
    .then((res) => {
      if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
      return res.json();
    })
    .then((json) => {
      entry.data = json;
    })
    .catch((err: unknown) => {
      entry.error = err instanceof Error ? err.message : String(err);
    })
    .finally(() => {
      entry.done = true;
    });
  cache.set(url, entry);
  return entry;
}

function useCachedJson<T>(url: string): MapDataState<T> {
  const [state, setState] = useState<MapDataState<T>>(() => {
    // Synchronous cache peek so later mounts skip the loading flash.
    if (typeof window !== "undefined") {
      const hit = cache.get(url);
      if (hit?.done) return { data: hit.data as T | null, error: hit.error, loading: false };
    }
    return { data: null, error: null, loading: true };
  });

  useEffect(() => {
    let alive = true;
    const entry = load(url);
    const publish = () => {
      if (alive) setState({ data: entry.data as T | null, error: entry.error, loading: false });
    };
    if (entry.done) publish();
    else entry.promise.then(publish);
    return () => {
      alive = false;
    };
  }, [url]);

  return state;
}

/** HOLC polygons pre-projected into both exhibit frames, plus the frame defs. */
export function useHolcFrames(): MapDataState<HolcFramesDoc> {
  return useCachedJson<HolcFramesDoc>(HOLC_FRAMES_URL);
}

/** Hyde Park base geometry (lake, parks, boundary, labels) in hydePark frame pixels. */
export function useFrameLayers(): MapDataState<FrameLayersDoc> {
  return useCachedJson<FrameLayersDoc>(FRAME_LAYERS_URL);
}
