"use client";
/* ------------------------------------------------------------------ */
/*  Playhead-driven captions. Whisper-aligned cues are generated by    */
/*  scripts/exhibit-align-cues.py into narration_cues.json and fetched */
/*  once per page load through a module-level promise cache (same      */
/*  pattern as useExhibitMapData). A block uses its aligned cues only  */
/*  when the live block duration agrees with the cue timeline, so the  */
/*  debug audio stub (16x timer) and a stale cue file fall back to     */
/*  splitting the block text proportionally by word count. Text is    */
/*  written through a ref on playhead ticks, never React state, and    */
/*  the bar is aria-hidden: the transcript is the accessible path.     */
/* ------------------------------------------------------------------ */
import { useEffect, useMemo, useRef } from "react";
import { useExhibitState, usePlayheadBus } from "@/lib/exhibit/ExhibitProvider";
import { narrationBlock } from "@/lib/exhibit/content";

interface Cue {
  startFrac: number; // 0..1 of block duration
  text: string;
}

interface AlignedCue {
  startSec: number;
  endSec: number;
  text: string;
}

const ALIGNED_CUES_URL = "/exhibit-data/narration_cues.json";

/* Module-level promise cache: at most one fetch per page load, shared
   across mounts. A missing or malformed file leaves alignedBlocks null
   and every block stays on the proportional fallback below. */
let alignedBlocks: Record<string, AlignedCue[]> | null = null;
let alignedFetch: Promise<void> | null = null;

function isAlignedCueList(v: unknown): v is AlignedCue[] {
  if (!Array.isArray(v) || v.length === 0) return false;
  return v.every((c) => {
    const cue = c as Partial<AlignedCue> | null;
    return (
      typeof cue?.startSec === "number" &&
      typeof cue?.endSec === "number" &&
      typeof cue?.text === "string"
    );
  });
}

function loadAlignedCues(): Promise<void> {
  if (!alignedFetch) {
    alignedFetch = fetch(ALIGNED_CUES_URL)
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status} for ${ALIGNED_CUES_URL}`);
        return res.json() as Promise<{ blocks?: Record<string, unknown> }>;
      })
      .then((doc) => {
        if (!doc || typeof doc !== "object" || !doc.blocks) return;
        const clean: Record<string, AlignedCue[]> = {};
        for (const [blockId, cues] of Object.entries(doc.blocks)) {
          if (isAlignedCueList(cues)) clean[blockId] = cues;
        }
        if (Object.keys(clean).length > 0) alignedBlocks = clean;
      })
      .catch(() => {
        alignedBlocks = null;
      });
  }
  return alignedFetch;
}

function deriveCues(text: string): Cue[] {
  // sentence split with initials/abbreviation tolerance kept simple; the
  // narration was written in plain declarative sentences
  const sentences = text.match(/[^.!?]+[.!?]+(\s|$)/g)?.map((s) => s.trim()) ?? [text];
  const chunks: string[] = [];
  for (const s of sentences) {
    // keep caption cards to roughly 14 words; split long sentences at commas
    const words = s.split(/\s+/);
    if (words.length <= 16) {
      chunks.push(s);
      continue;
    }
    let current: string[] = [];
    for (const part of s.split(/(,)/)) {
      current.push(part);
      const joined = current.join("");
      if (joined.split(/\s+/).length >= 12 && part === ",") {
        chunks.push(joined.trim());
        current = [];
      }
    }
    if (current.join("").trim()) chunks.push(current.join("").trim());
  }
  const totalWords = chunks.reduce((n, c) => n + c.split(/\s+/).length, 0) || 1;
  let acc = 0;
  return chunks.map((c) => {
    const start = acc / totalWords;
    acc += c.split(/\s+/).length;
    return { startFrac: start, text: c };
  });
}

export default function CaptionBar() {
  const state = useExhibitState();
  const bus = usePlayheadBus();
  const textRef = useRef<HTMLDivElement>(null);
  const cuesRef = useRef<{ blockId: string; cues: Cue[] } | null>(null);

  const visible = state.captionsOn && state.mode === "guided" && state.playState === "playing";

  const cueFor = useMemo(
    () => (blockId: string) => {
      if (cuesRef.current?.blockId !== blockId) {
        const block = narrationBlock(blockId);
        cuesRef.current = { blockId, cues: block ? deriveCues(block.text) : [] };
      }
      return cuesRef.current.cues;
    },
    []
  );

  useEffect(() => {
    void loadAlignedCues();
  }, []);

  useEffect(() => {
    if (!visible) return;
    return bus.subscribe(({ blockId, msIntoBlock, blockDurationMs }) => {
      const el = textRef.current;
      if (!el || !blockId || blockDurationMs <= 0) return;
      const aligned = alignedBlocks?.[blockId];
      // the cue timeline ends at the mp3 duration; when the live block clock
      // runs on another timescale (audio stub, stale cues after a re-record)
      // the mismatch pushes this block onto the proportional fallback
      if (aligned && Math.abs(aligned[aligned.length - 1].endSec * 1000 - blockDurationMs) <= 1500) {
        const sec = msIntoBlock / 1000;
        let active = aligned[0];
        for (const c of aligned) {
          if (c.startSec <= sec) active = c;
          else break;
        }
        if (el.textContent !== active.text) el.textContent = active.text;
        return;
      }
      const cues = cueFor(blockId);
      if (!cues.length) return;
      const frac = Math.min(1, msIntoBlock / blockDurationMs);
      let active = cues[0];
      for (const c of cues) {
        if (c.startFrac <= frac) active = c;
        else break;
      }
      if (el.textContent !== active.text) el.textContent = active.text;
    });
  }, [bus, cueFor, visible]);

  if (!visible) return null;

  return (
    <div
      aria-hidden="true"
      className="pointer-events-none fixed inset-x-0 bottom-16 z-30 flex justify-center px-4 md:bottom-[4.5rem]"
      data-testid="caption-bar"
    >
      <div
        ref={textRef}
        className="max-w-2xl rounded-sm bg-exh-linen/95 px-4 py-2 text-center font-display text-base leading-snug text-exh-ink shadow-[0_1px_6px_rgba(28,26,23,0.18)] md:text-lg"
      />
    </div>
  );
}
