import type { WalkTour } from "./walk-types";

// ------------------------------------------------------------------
// The Hyde Park walk. Thirteen stops on how the neighborhood was
// built and who it was built for, from Paul Cornell's stone at 53rd
// Street through the fair, the university, and the machinery of
// exclusion, closing the circle at the Obama Presidential Center,
// with two optional detours west along 63rd Street. The narration is
// written from the founder's family oral history (a recorded
// conversation outlining the tour), corrected and deepened against
// the sources listed on every stop; nothing in the transcript should
// outrun them. Key print source for the 2026 expansion: Susan
// O'Connor Davis, Chicago's Historic Hyde Park (University of
// Chicago Press, 2013), plus the documentary series The Shame of
// Chicago, Shame of the Nation. The six red plates are page-only and
// are not read into the audio. Audio is generated by
// scripts/walk-tts.mjs --tour hyde-park (OpenAI, voice ash);
// durations.json is the source of audioSeconds.
// ------------------------------------------------------------------

const MEDIA = "/media/hyde-park-walk";

export const HYDE_PARK_WALK: WalkTour = {
  title: "Walk Hyde Park",
  dek: "A free self-guided audio tour from Paul Cornell's stone to the Obama Presidential Center. Thirteen stops, about five miles, and two detours for whoever wants the rest of the story. Hyde Park sold exclusivity from its first day, and a century of paperwork decided who got to live in it.",
  walkMinutes: 103,
  listenMinutes: 49,
  distanceMiles: 5.0,
  startLabel: "Paul Cornell's stone, Harold Washington Park",
  practical: [
    {
      title: "Getting there and timing",
      text: "The walk starts in Harold Washington Park at 53rd Street, across from the Hampton House at 5300 South Shore Drive, and ends at the Obama Presidential Center. The 53rd Street Metra stop is a few blocks from the start, and the 6 and 28 buses run nearby. Plan on about three and a half hours with the stops. Short on time? End at Harper Court and save the last leg for another day. Two optional detours continue west along 63rd Street afterward, to Daley's Restaurant and the Hansberry house; the number 63 bus covers that stretch if your feet are done.",
    },
    {
      title: "The ground",
      text: "Flat city sidewalks the whole way, about five miles on the main line. The busiest crossings are on 57th Street, along Stony Island, and at Lake Park; use the marked crosswalks. The university quadrangles are open to walk through every day. Going inside Robie House takes a timed ticket, but this tour only needs the outside.",
    },
    {
      title: "Listening",
      text: "Headphones are nicest, but a phone speaker works fine. Every stop's audio is also printed on the page, so you can read instead of listen. If you share your location, it is used only to draw your dot on the map. It never leaves your phone.",
    },
  ],
  route: [
    [41.7996, -87.5812],
    [41.7992, -87.5824],
    [41.799, -87.5833],
    [41.7992, -87.5852],
    [41.79946, -87.58734],
    [41.7976, -87.5875],
    [41.7957, -87.5877],
    [41.7938, -87.5878],
    [41.792, -87.5879],
    [41.7912, -87.5872],
    [41.7911, -87.585],
    [41.791, -87.5831],
    [41.7912, -87.5859],
    [41.7913, -87.5871],
    [41.7893, -87.5872],
    [41.7872, -87.5873],
    [41.78725, -87.5891],
    [41.7877, -87.5917],
    [41.7878, -87.5937],
    [41.78785, -87.596],
    [41.78805, -87.5961],
    [41.7885, -87.5962],
    [41.7899, -87.5959],
    [41.7898, -87.5978],
    [41.7897, -87.5999],
    [41.7888, -87.6003],
    [41.7897, -87.6004],
    [41.7907, -87.6002],
    [41.7913, -87.5999],
    [41.79225, -87.5999],
    [41.7931, -87.6008],
    [41.794, -87.6006],
    [41.7947, -87.599],
    [41.7948, -87.5962],
    [41.7949, -87.5935],
    [41.79495, -87.5918],
    [41.7951, -87.59],
    [41.7952, -87.5884],
    [41.7963, -87.5884],
    [41.7981, -87.5885],
    [41.79945, -87.58845],
    [41.7981, -87.5888],
    [41.7952, -87.5887],
    [41.7953, -87.5872],
    [41.7938, -87.5875],
    [41.792, -87.5878],
    [41.79, -87.5872],
    [41.788, -87.5873],
    [41.7862, -87.5874],
    [41.7859, -87.5857],
  ],
  detourRoutes: [
    [
      [41.7859, -87.5857],
      [41.7855, -87.5872],
      [41.783, -87.5873],
      [41.7802, -87.5872],
      [41.7802, -87.5989],
      [41.7802, -87.6057],
      [41.7806, -87.6064],
      [41.7838, -87.606],
      [41.7838, -87.6121],
      [41.7827, -87.6123],
    ],
  ],
  stops: [
    {
      id: "cornells-stone",
      number: 1,
      title: "Paul Cornell's stone",
      dek: "A boulder in the grass marks where the whole neighborhood started",
      mapLabel: "Cornell's stone",
      lat: 41.7996,
      lng: -87.5812,
      audioSrc: `${MEDIA}/audio/stop-01.mp3`,
      audioSeconds: 223,
      transcript: [
        "Find the boulder in Harold Washington Park near 53rd Street, across from the tall brick building with the red awning. That building matters in a few minutes. The stone marks roughly where Hyde Park began, and before the story starts, take one slow look around. The towers, the park, the trains behind the trees. All of it traces back to a single land deal.",
        "Paul Cornell was a young lawyer from upstate New York who reached Chicago in 1847 with a dollar and fifty cents in his pocket, and a thief relieved him of his belongings his very first night in town. He rebuilt from nothing, and along the way he met Stephen Douglas, the Illinois senator, who gave him a piece of advice. Invest south of the city, because that is where Chicago is going to grow. So one day Cornell got on a horse and rode down the lake shore, through marsh grass and sand ridges, until he reached a small farm and tavern near what is now 53rd Street, a stopping place for travelers making the last push into the city.",
        "In August 1853 he bought **sixty acres from Electa Watson Garnsey**, the tavern keeper's widow, and he kept buying until he held about **300 acres of lakefront** between roughly 51st and 55th. Then he gave it a name that promised gentility. Hyde Park. Chicago at the time pumped its sewage into the river and the lake and smelled like it. What Cornell was selling was escape, clean air and cool water for families rich enough to leave the city behind.",
        "The whole plan depended on getting those families here, so in 1856 Cornell handed the Illinois Central sixty acres of his land for free. In exchange the railroad built him a **station at 53rd Street and guaranteed daily trains downtown**. The first run, on June 1, 1856, carried what the station agent wired downtown as nary a passenger up or down. Regular service started that July anyway, four trains a day at a fare of seven and a half cents, and the bet paid off so completely that by 1929 this line ran more than five hundred trains a day. Cornell cut the land into large lots, eighteen to a block with fifty feet of frontage, and kept the pace deliberately rural. Early buyers kept gardens, stables, even a few animals.",
        "Right here on the shore he raised the resort's centerpiece, the **Hyde Park House**, a five-story hotel with the water at its porch and the trains at its back. It hosted concerts, parties, and political dinners, and Mary Todd Lincoln stayed there for two and a half months after her husband was killed. After it burned in 1877, this stretch of shore eventually got the Sisson Hotel, the brick tower in front of you, known today as the Hampton House.",
        "The Sisson deserves one more minute, because the pretty tower made an ugly promise. Its builder, **Harry Sisson, advertised that his guests would never encounter a Black person** under his roof, and hired no Black staff. In the 1920s, when the Klan ran openly in Hyde Park and printed its weekly paper on 55th Street, Sisson hosted a reception for the Klan's Imperial Wizard. A Catholic weekly over on 52nd Street started publishing local members' names, the chapter collapsed, and Sisson's trade collapsed with it. He sold, and the hotel changed names. Remember him when you admire the architecture on this walk. Cornell built a place that chose its neighbors, and for a hundred years, choosing kept meaning the same thing.",
      ],
      images: [
        {
          src: `${MEDIA}/sisson-1920s.jpg`,
          alt: "The Sisson Hotel rising over the Hyde Park lakefront around 1920, with sailboats on the water in front of it",
          credit:
            "The Sisson Hotel on the old Hyde Park House grounds, around 1920. From Early Chicago Hotels. Public domain, via Wikimedia Commons.",
          label: "c. 1920",
        },
        {
          src: `${MEDIA}/hyde-park-house-1870s.jpg`,
          alt: "The Hyde Park House hotel, a long clapboard resort building on the open lakefront in the 1870s",
          credit:
            "The Hyde Park House, Cornell's resort centerpiece, before it burned in 1877. Reproduced in Susan O'Connor Davis, Chicago's Historic Hyde Park. Public domain.",
          label: "c. 1870s",
        },
      ],
      nowImage: {
        src: `${MEDIA}/hampton-house-today.jpg`,
        alt: "The Hampton House today, a red brick tower with a red entrance awning behind park trees",
        credit:
          "The same building today, the Hampton House. Photograph by TonyTheTiger, 2006, via Wikimedia Commons. CC BY-SA 3.0.",
        label: "Today",
      },
      toNext: {
        text: "Walk to the corner of 53rd Street and Hyde Park Boulevard, one short block in from the lake. The tall hotel building on the corner, with carved faces in its terra cotta, is the Del Prado.",
        distanceMeters: 200,
        minutes: 3,
      },
      sources: [
        { label: "Hyde Park Historical Society, Paul Cornell", url: "https://www.hydeparkhistory.org/paul-cornell" },
        { label: "Susan O'Connor Davis, Chicago's Historic Hyde Park (University of Chicago Press, 2013)", url: "https://press.uchicago.edu/ucp/books/book/chicago/C/bo8844257.html" },
        { label: "Hyde Park Herald, Hyde Park Stories on Paul Cornell", url: "https://www.hpherald.com/evening_digest/hyde-park-stories-paul-cornell/article_18568fa6-4ca5-4dfc-8d36-d90aa574ceda.html" },
        { label: "Hyde Park Historical Society, Harold Washington Park", url: "https://www.hydeparkhistory.org/blog/hyde-park-stories-harold-washington-park" },
        { label: "Hyde Park House, Wikipedia", url: "https://en.wikipedia.org/wiki/Hyde_Park_House" },
        { label: "Hampton House, Wikipedia", url: "https://en.wikipedia.org/wiki/Hampton_House_(Chicago)" },
      ],
    },
    {
      id: "del-prado",
      number: 2,
      title: "The Del Prado",
      dek: "The resort era's front porch still stands on its corner",
      mapLabel: "Del Prado",
      lat: 41.799,
      lng: -87.5833,
      audioSrc: `${MEDIA}/audio/stop-02.mp3`,
      audioSeconds: 129,
      transcript: [
        "The apartment tower on this corner opened in 1918 as the **Cooper-Carlton Hotel**. Look up and you can see carved faces in the terra cotta near the top, put there by owners who claimed a family line back to the novelist James Fenimore Cooper. In 1930 it took the name **Del Prado**, inherited from an older hotel out on the Midway that was being torn down to make room for International House.",
        "Hyde Park in those decades ran as a resort, and this corner was its front porch. Families checked in for the whole summer. They took big suites, sometimes a whole floor. The men rode Cornell's trains downtown to their offices every morning, and everyone else had the day. The beach, the parks, sailing off the Point, restaurants, concerts in the hotel ballrooms. Remember that this was the time before air travel. When people wanted to get away, they traveled close to home, and the railroads sold the getaway hard.",
        "That sales pitch reached a long way. The Illinois Central's main line does not end downtown. Follow it the other direction and it runs through the whole length of Mississippi, and its ads told families across the Midwest and the South to come spend the summer by the lake in Chicago. The train was the only fast way anywhere, and Hyde Park sat right on it.",
        "The building is apartments now, restored inside. If the door staff will let you, step into the lobby and look at the ceilings, or just study the arches from the sidewalk and picture check-in day in July. Trunks stacked on the curb, porters hauling a season's worth of luggage, a band playing somewhere upstairs.",
        "Before you walk on, hold one detail. The families on this porch were white. So were the names on every deed along the boulevards. The people hauling the trunks and cooking the meals often were not, and Hyde Park's own small Black community lived two blocks west, pressed against the railroad embankment. That street is the next stop.",
      ],
      images: [
        {
          src: `${MEDIA}/del-prado-1900s.jpg`,
          alt: "A linen postcard of the Del Prado Hotel by the lake at Hyde Park Boulevard and 53rd Street, with sailboats on the water beyond",
          credit:
            "The Del Prado as a hotel, from a linen postcard calling it the finest residential and transient hotel in the Middle West. Newberry Library collection. Public domain, via Wikimedia Commons.",
          label: "1930s",
        },
        {
          src: `${MEDIA}/cooper-carlton-postcard-1924.jpg`,
          alt: "The handwritten back of a Cooper-Carlton Hotel postcard, postmarked Chicago, September 1924, addressed to Cleveland, Ohio",
          credit:
            "The back of a Cooper-Carlton postcard mailed September 4, 1924. The printed header calls it one of Chicago's beautiful hotels located on Hyde Park Boulevard. Newberry Library collection. Public domain, via Wikimedia Commons.",
          label: "1924",
        },
      ],
      nowImage: {
        src: `${MEDIA}/del-prado-today.jpg`,
        alt: "The Del Prado building today at 53rd and Hyde Park Boulevard, red brick with white terra cotta trim",
        credit:
          "The Del Prado today, apartments now. Photograph by TonyTheTiger, 2008, via Wikimedia Commons. CC BY-SA 3.0.",
        label: "Today",
      },
      toNext: {
        text: "Walk west on 53rd Street toward the railroad embankment. Stop at Lake Park Avenue where you can see the station stairs and the tracks running above the street.",
        distanceMeters: 350,
        minutes: 5,
      },
      sources: [
        { label: "Hotel Del Prado, Wikipedia", url: "https://en.wikipedia.org/wiki/Hotel_Del_Prado" },
        { label: "Julia Bachrach, Chicago's apartment hotels of the 1910s", url: "https://www.jbachrach.com/blog/2019/11/26/chicagos-apartment-hotels-of-the-1910s" },
        { label: "International House, exploring our history", url: "https://ihouse.uchicago.edu/90th-anniversary/90th-anniversary-explore-our-history/" },
      ],
    },
    {
      id: "lake-park-tracks",
      number: 3,
      title: "The tracks and Lake Park",
      dek: "The railroad that built the resort ran both directions",
      mapLabel: "53rd St tracks",
      lat: 41.79946,
      lng: -87.58734,
      audioSrc: `${MEDIA}/audio/stop-03.mp3`,
      audioSeconds: 174,
      transcript: [
        "These tracks are why everything else on this walk exists. Cornell's deal put a station at 53rd Street in 1856, and suburban trains have stopped here ever since, a hundred and seventy years without a break. The Illinois Central electrified the line in 1926, after the city ordered its four hundred daily coal-burning engines cleaned up, and Metra runs the same embankment today. We tend to picture this railroad as a shuttle between Hyde Park and downtown. It never was. The main line keeps going south, through the small towns of Mississippi, all the way to New Orleans.",
        "During the **Great Migration** that geography changed America. Black southerners rode the Illinois Central north in two great waves, the first around the World Wars, the second after, hundreds of thousands of people moving toward factory jobs and away from the terror of the South. The Chicago Defender, the city's great Black newspaper, rode the same rails south in the porters' bags, telling readers to leave what it called the land of suffering. Many stepped off IC trains within a few miles of where you are standing. They built this city's industry with their hands. And nearly every neighborhood in the city, this one very much included, refused to let them live in it.",
        "Which brings us to the street you are on. Lake Park Avenue was the working back of Cornell's stage set. The strip along the tracks fell under railroad jurisdiction, outside the village's dry laws, so this is where the saloons went. In one year in the 1870s the village issued forty-nine saloon licenses and turned down exactly one. Add the coal yards, the liveries, and the cheap frame buildings, and you have the unglamorous machinery that kept a resort running.",
        "It is also where Hyde Park put its Black neighbors. In the early 1900s a small **middle-class Black community lived along Lake Park and Harper avenues**, close against the tracks. There was an AME church on Lake Park, a colored Republican Club, and a social column in the Defender. The 1900 census along this street lists the Black cooks and waiters who staffed the hotels, most of them born in Kentucky, Tennessee, and Mississippi, boarding next to white pipe welders and Chinese laundry owners. In 1914 the neighborhood's Half Century Club held a reception at the Rosalie Music Hall for Booker T. Washington, the most famous Black man in America. Meanwhile the rest of Hyde Park stayed almost entirely white, and worked to keep itself that way.",
        "Stand here a second and read the pattern, because it repeats all afternoon. The front door on the boulevards, the Black community beside the tracks. Geography doing the work of policy, decades before the policy got written down. When we reach the university and 55th Street, you will watch it get written down.",
      ],
      images: [
        {
          src: `${MEDIA}/lake-park-tavern-1892.jpg`,
          alt: "Charles Friedrich's Family Resort, a wooden tavern on Lake Avenue in 1892, with staff posed on the porch under brewery signs",
          credit:
            "A Lake Avenue tavern in 1892, one of dozens licensed along the tracks. Reproduced in Susan O'Connor Davis, Chicago's Historic Hyde Park. Public domain.",
          label: "1892",
        },
        {
          src: `${MEDIA}/ic-electric-1967.jpg`,
          alt: "An Illinois Central Electric commuter train pulling into a wooden platform station in 1967",
          credit:
            "An Illinois Central Electric train at the 63rd Street station, 1967. Photograph by Lawrence and David Barera, via Wikimedia Commons. CC BY-SA 2.0.",
          label: "1967",
        },
      ],
      nowImage: {
        src: `${MEDIA}/metra-53rd-today.jpg`,
        alt: "A Metra Electric train approaching the 53rd Street station platforms on the Hyde Park embankment today",
        credit:
          "A train coming into the 53rd Street station today. Photograph by David Wilson, 2013, via Wikimedia Commons. CC BY 2.0.",
        label: "Today",
      },
      toNext: {
        text: "Follow Lake Park Avenue south beside the embankment, all the way to 57th Street. Cross toward the park and walk to the north face of the huge domed museum, by the water.",
        distanceMeters: 1300,
        minutes: 16,
      },
      sources: [
        { label: "51st/53rd Street Hyde Park station, Wikipedia", url: "https://en.wikipedia.org/wiki/51st/53rd_Street/Hyde_Park_station" },
        { label: "Susan O'Connor Davis, Chicago's Historic Hyde Park (University of Chicago Press, 2013)", url: "https://press.uchicago.edu/ucp/books/book/chicago/C/bo8844257.html" },
        { label: "Cook County African American Heritage Trail, the railroad", url: "https://ccafricanamericanheritage.org/trail-stop/railroad/" },
        { label: "Hyde Park Herald, the Villas survive (the Half Century Club)", url: "https://www.hpherald.com/evening_digest/hyde-park-stories-the-villas-survive/article_1d5c91c8-bbf2-11ef-aa3d-d36c34ffc52c.html" },
        { label: "Hyde Park Herald, Lost Hyde Park's commercial core", url: "https://www.hpherald.com/news/local/lost-hyde-park-the-commercial-core/article_d282cc80-14ba-11ec-b846-f786cbbb9339.html" },
      ],
    },
    {
      id: "white-city",
      number: 4,
      title: "The White City",
      dek: "The fair that made Hyde Park famous also drew its hardest line",
      mapLabel: "White City",
      lat: 41.791,
      lng: -87.5831,
      audioSrc: `${MEDIA}/audio/stop-04.mp3`,
      audioSeconds: 274,
      transcript: [
        "The building across the water is the Museum of Science and Industry, and it is the last of the great palaces of the **1893 World's Columbian Exposition** still standing where the fair put it. To understand why the fair landed here, of all places, you have to go back to Cornell again. He had spent decades trying to will great parks into existence on this end of the city. In 1866 he and his allies began pushing a parks bill, and Cornell rode to Springfield two winters running to fight for it. In 1869 the state finally created the **South Park Commission** and told it to buy more than a thousand acres of marsh and dune, including all the ground around you.",
        "The commission hired **Frederick Law Olmsted and Calvert Vaux**, the designers of Central Park. They drew a plan for two great parks, one here by the water and one a mile west, joined by a green channel you will walk shortly. Then the 1871 Great Fire burned their drawings, along with most of the city, and the money went elsewhere. For twenty years this stayed mostly rough ground, sketched as a garden and never built. Which is exactly why the fair chose it. When Chicago beat New York, Washington, and St. Louis for the World's Fair, the planners needed hundreds of open lakefront acres, already publicly owned, close to rail lines. Daniel Burnham looked at Jackson Park's unbuilt emptiness and saw a blank page. Olmsted, now an old man, came back to shape the ground he had planned a generation earlier. Land prices around the site started climbing the moment the decision was announced.",
        "Put the fair in scale. The last great exposition, in Paris, had produced the Eiffel Tower. Chicago, barely twenty years past its fire, meant to answer it and to announce itself as the young country's big shoulders. Burnham directed an army of architects who threw up a city of palaces in about two years. They look like carved stone in the photographs. They were mostly **steel frames skinned in plaster**, and the fastest way to make them match was paint. The painters chose a single white, and the newspapers did the rest. The White City. At night it was lit with electricity on a scale almost nobody had seen, and the crowds came as much for the glow as for the exhibits.",
        "It ran six months and drew some **27 million visits, in a country of 65 million people**. Visitors met the dishwasher, the zipper, Juicy Fruit gum, and a wheel built by a bridge engineer named Ferris. The fair also planted a lie that would outlive it. A food company hired **Nancy Green, a Chicago woman born into slavery in Kentucky**, to flip pancakes in costume as Aunt Jemima, a smiling plantation cook invented to sell flour. The image charmed the crowds and sold the Old South as a warm memory, at the exact moment the fair was doing something colder.",
        "Because Black Americans were shut out of this fair. Shut out of its planning, its exhibit halls, and nearly all of its jobs. **Ida B. Wells and Frederick Douglass** answered from the gates with a pamphlet, The Reason Why the Colored American Is Not in the World's Columbian Exposition, printed with prefaces in English, French, and German so any visitor on earth could read it. Wells counted the copies she handed out in the thousands. Douglass, then in his seventies, worked from the Haiti Pavilion, the one building where Black excellence was on display, because Haiti, not America, had made him its commissioner.",
        "The fair's answer was a single Colored American Day, late in the summer. Douglass gave the speech of the summer anyway. And then the White City died fast. The season closed into a depression winter, and over the next year most of the plaster palaces burned, some in fires that broke out during the summer of the great Pullman strike, while crowds stood and watched. Almost nothing survived except the brick-cored palace in front of you, and the idea. Keep the pamphlet's title with you as you walk, because the rest of this tour watches the same exclusion move from the fairgrounds into deeds, maps, and city plans. The fair made Hyde Park famous, filled it with hotels and workers, and handed the young neighborhood its central question. Who is all this actually for?",
      ],
      images: [
        {
          src: `${MEDIA}/palace-fine-arts-1893.jpg`,
          alt: "The domed Palace of Fine Arts reflected in the North Pond during the 1893 World's Fair",
          credit:
            "The Palace of Fine Arts, 1893, today's Museum of Science and Industry. C. D. Arnold, Official Views of the World's Columbian Exposition. Public domain, via Wikimedia Commons.",
          label: "1893",
        },
        {
          src: `${MEDIA}/court-night-1893.jpg`,
          alt: "The Grand Court of the 1893 fair at night, its domes and fountains outlined in electric light before a crowd",
          credit:
            "The Grand Court lit at night, drawn by Charles Graham, 1893. Library of Congress Prints and Photographs Division. Public domain.",
        },
        {
          src: `${MEDIA}/white-city-burning-1894.jpg`,
          alt: "The abandoned fair palaces burning in 1894, flames and smoke towering over the Court of Honor",
          credit:
            "The White City burning, 1894. Reproduced in Susan O'Connor Davis, Chicago's Historic Hyde Park. Public domain.",
          label: "1894",
        },
      ],
      nowImage: {
        src: `${MEDIA}/columbia-basin-today.jpg`,
        alt: "The Museum of Science and Industry today, seen straight on across the still water of the Columbia Basin",
        credit:
          "The same building today, across the Columbia Basin. Photograph by Warren LeMay, 2024, via Wikimedia Commons. CC BY-SA 2.0.",
        label: "Today",
      },
      toNext: {
        text: "Walk west on 57th Street to Stony Island Avenue and cross at the light. Turn left and follow Stony Island south to 59th Street, where the long sunken green of the Midway opens west. Turn right along its north side. The huge Gothic building facing the green, two blocks along, is International House.",
        distanceMeters: 1250,
        minutes: 16,
      },
      sources: [
        { label: "World's Columbian Exposition, Wikipedia", url: "https://en.wikipedia.org/wiki/World%27s_Columbian_Exposition" },
        { label: "Susan O'Connor Davis, Chicago's Historic Hyde Park (University of Chicago Press, 2013)", url: "https://press.uchicago.edu/ucp/books/book/chicago/C/bo8844257.html" },
        { label: "The Reason Why the Colored American Is Not in the World's Columbian Exposition, full text", url: "https://digital.library.upenn.edu/women/wells/exposition/exposition.html" },
        { label: "Chicago Park District, Jackson Park history", url: "https://www.chicagoparkdistrict.com/parks-facilities/jackson-andrew-park" },
        { label: "Nancy Green, Wikipedia", url: "https://en.wikipedia.org/wiki/Nancy_Green" },
      ],
    },
    {
      id: "old-del-prado",
      number: 5,
      title: "The first Del Prado",
      dek: "A fair hotel's ground became the university's front door to the world",
      mapLabel: "Int'l House",
      lat: 41.7877,
      lng: -87.5917,
      audioSrc: `${MEDIA}/audio/stop-05.mp3`,
      audioSeconds: 141,
      transcript: [
        "The Gothic tower facing the Midway is International House, and under it lies the hotel this tour has already mentioned twice. In April 1893, with the fair about to open, a buff brick hotel called the **Raymond and Whitcomb Grand** was rushed to completion right here. Four stories, 325 rooms, another 62 in an annex, and its best feature ran the full length of the building. A **250-foot verandah facing the Midway**, so guests could take breakfast watching the strangest street on earth. It soon took a grander name, the Del Prado.",
        "The fair minted hotels like this all along the neighborhood's edges. The Del Prado, the Chicago Beach, the Windermere, all opened for 1893 with wonders the guests wrote home about. Hot and cold running water, steam heat, electric light, telephones. The Illinois Central raised its tracks onto the embankment you crossed earlier just to move the crowds, an estimated four million riders in one summer. When the fair ended, the hotels stayed, and for a generation this stretch ran as one of the most famous resort hotel districts in the country.",
        "It did not last. By 1930 the Del Prado was, in one writer's words, worn and tired, its great verandah long since enclosed. The university bought the ground, pulled the hotel down, and raised **International House**, a residence built with Rockefeller money to board students from around the world. Its name moved up to 53rd Street, where the Cooper-Carlton wears it still.",
        "Notice what happened on this block, because it happens again and again from here on. A neighborhood institution ages, the university buys the land, and something in Gothic stone replaces it. In the decades ahead the university would absorb the Piccadilly, the Broadview, and the Shoreland the same way. There is a real irony in the particular swap made here. The hotel had been a private pleasure palace for white travelers. The house that replaced it was built so students from around the world could live under one roof, in a neighborhood that was at that very moment sealing itself shut against Black Chicagoans a mile west. Both things are true on this ground. Hold them both, and walk on up the Midway.",
      ],
      images: [
        {
          src: `${MEDIA}/del-prado-midway-1900s.jpg`,
          alt: "A postcard of the first Del Prado Hotel seen across the tree-lined Midway Plaisance, an early automobile on the drive",
          credit:
            "The first Del Prado across the Midway Plaisance, from an early postcard. Newberry Library collection. Public domain, via Wikimedia Commons.",
          label: "c. 1910",
        },
      ],
      nowImage: {
        src: `${MEDIA}/ihouse-today.jpg`,
        alt: "International House today, a tall Collegiate Gothic building on the Midway at 59th and Dorchester",
        credit:
          "International House on the same ground today. Photograph by Warren LeMay, 2025, via Wikimedia Commons. CC BY-SA 2.0.",
        label: "Today",
      },
      toNext: {
        text: "Keep west along the north edge of the Midway, a couple of hundred paces, to anywhere with a long view down the lawn in both directions.",
        distanceMeters: 170,
        minutes: 2,
      },
      sources: [
        { label: "Susan O'Connor Davis, Chicago's Historic Hyde Park (University of Chicago Press, 2013)", url: "https://press.uchicago.edu/ucp/books/book/chicago/C/bo8844257.html" },
        { label: "International House, exploring our history", url: "https://ihouse.uchicago.edu/90th-anniversary/90th-anniversary-explore-our-history/" },
        { label: "Hotel Del Prado, Wikipedia", url: "https://en.wikipedia.org/wiki/Hotel_Del_Prado" },
      ],
    },
    {
      id: "midway-line",
      number: 6,
      title: "The Midway line",
      dek: "A canal that never came, and a border that did",
      mapLabel: "The Midway",
      lat: 41.7878,
      lng: -87.5937,
      audioSrc: `${MEDIA}/audio/stop-06.mp3`,
      audioSeconds: 185,
      transcript: [
        "This mile of green was the fair's pleasure strip. The White City behind you was the exhibition, dignified and ticketed. Out here was the fun. Beer gardens, bands, sideshows, restaurants from a dozen countries, and rising over the middle of it the first **Ferris wheel**, 264 feet tall, America's answer to the Eiffel Tower. Fifty cents bought two slow revolutions, about twenty minutes in the air. The shows out here took in millions, and every carnival midway in America has been named for this lawn ever since. The wheel outlived the fair by only a little. Crews spent 86 days taking it apart, it limped through two more engagements, and its company went bankrupt while Ferris himself died young in 1896.",
        "It had a darker draw too. The Midway's so-called villages put human beings on display, people brought from Africa, Asia, the Middle East, and the Americas, presented under the banner of anthropology for paying crowds who stared at them like exhibits. The Tribune recommended the exhibit as a chance to descend the spiral of evolution. That happened here, on this grass, and the fair sold tickets to it all summer.",
        "Now look at the ground itself. The lawn sits sunken below the streets because **Olmsted planned a canal here**, a waterway linking the Jackson Park lagoons behind you to Washington Park a mile west, so you could move through the whole South Side park system by boat. Crews started digging, the money ran out, and the water never came. The ditch stayed a lawn.",
        "But the empty channel found another job. **The Midway became a border.** North of this grass, the university and white Hyde Park. South of it, Woodlawn. And when the Great Migration filled the Black Belt to bursting, that narrow strip of housing along State Street, now flanked by the Dan Ryan, families started looking for rooms anywhere they could find them. The blocks south of the Midway were the pressure line. For most of a century, which side of this lawn you lived on decided your mortgage, your rent, and what the city thought your block was worth. The numbers stayed blunt for decades. As late as 1980, the blocks just northeast of here ran about 86 percent white, and the blocks northwest of campus about 88 percent Black. Cross the lawn today and you can still feel the seam.",
        "The neighborhood's answer to that pressure was paper. A mile southwest of here, in 1937, a family named **Hansberry** bought a brick three-flat across one of those paper lines, and a mob gathered outside their window the first evening. Their daughter Lorraine grew up to put that year on Broadway as A Raisin in the Sun. The red plate below explains the paperwork behind the mob, and if you have the legs for it, this tour ends with an optional detour to the house itself.",
      ],
      interrupts: [
        {
          title: "Restrictive covenants",
          body: [
            "A racial covenant was **a ban written into a property deed**, a clause in which the owner promised never to sell or rent to a Black person. It bound every later owner of the land, so one signing campaign could seal a block for generations. Through the 1910s the idea spread quietly, and in **1926 the Supreme Court, in Corrigan v. Buckley, let covenants stand** because they were private contracts between neighbors. That was the green light.",
            "In **1927 the Chicago Real Estate Board circulated a model covenant**, drafted by the national association's counsel Nathan William MacChesney, and pushed it block by block through churches, clubs, and property owners' associations. More than **220 Cook County subdivisions** adopted its language, one study counted **40 square miles of Chicago** under covenant, and people at the time claimed the paper covered as much as **three-quarters of the city's residential property**. By 1925 a realtor could brag to the Hyde Park Herald that the covenants ringing this neighborhood were **\"like marvelous delicately woven chain armor.\"**",
            "The University of Chicago helped pay for the armor. It gave money to the **Hyde Park Protective Club** to spread covenants on the blocks around campus, quietly financed the 1933 lawsuit that kept Black families out of the blocks near Washington Park, and spent **$83,597 defending covenants in court**, over the objection of its own sociologist Louis Wirth, who called them morally repulsive.",
            "When **Carl Hansberry bought at 6140 South Rhodes** in 1937 anyway, a chunk of concrete thrown through the window nearly hit seven-year-old Lorraine. The Supreme Court let the family stay in **1940** on a technicality, and in **1948, in Shelley v. Kraemer, it made every racial covenant in America unenforceable**. Nobody erased them. The words still sit on Cook County deeds today.",
          ],
        },
      ],
      images: [
        {
          src: `${MEDIA}/midway-1893.jpg`,
          alt: "The Midway Plaisance in 1893, crowded with visitors between the attractions, minarets and the Moorish Palace sign overhead",
          credit:
            "The Midway mid-fair, 1893, seen from the Ferris wheel. Public domain, via Wikimedia Commons.",
          label: "1893",
        },
        {
          src: `${MEDIA}/ferris-wheel-1895.jpg`,
          alt: "The first Ferris wheel's bare steel spokes rising over a North Side street in 1895, mid-reassembly",
          credit:
            "The wheel between lives, being rebuilt on the North Side in 1895 after its 86-day disassembly on the Midway. Reproduced in Susan O'Connor Davis, Chicago's Historic Hyde Park. Public domain.",
          label: "1895",
        },
      ],
      nowImage: {
        src: `${MEDIA}/midway-today.jpg`,
        alt: "The Midway Plaisance today, a long open sunken lawn lined with trees, with University of Chicago towers in the distance",
        credit:
          "The same ground today, a mile of open green. Photograph by Joe Passe, 2021, via Wikimedia Commons. CC BY-SA 2.0.",
        label: "Today",
      },
      toNext: {
        text: "Continue west along the Midway to Woodlawn Avenue. The great limestone tower on the corner ahead, tallest thing on the skyline, is Rockefeller Chapel.",
        distanceMeters: 230,
        minutes: 3,
      },
      sources: [
        { label: "Midway Plaisance, Wikipedia", url: "https://en.wikipedia.org/wiki/Midway_Plaisance" },
        { label: "Encyclopedia of Chicago, Restrictive Covenants", url: "http://www.encyclopedia.chicagohistory.org/pages/1067.html" },
        { label: "Susan O'Connor Davis, Chicago's Historic Hyde Park (University of Chicago Press, 2013)", url: "https://press.uchicago.edu/ucp/books/book/chicago/C/bo8844257.html" },
        { label: "The Shame of Chicago, Shame of the Nation, episode 2, The Chicago Plan", url: "https://vimeo.com/1039725670" },
        { label: "WBEZ, Chicago home records still contain racist covenants", url: "https://www.wbez.org/race-class-communities/2021/11/21/chicago-home-records-still-contain-racist-covenants" },
        { label: "Chicago History Today, the Hansberrys move in, June 15, 1937", url: "https://chicagohistorytoday.wordpress.com/2014/06/15/restrictive-covenant-6-15-1937/" },
      ],
    },
    {
      id: "rockefeller-chapel",
      number: 7,
      title: "Rockefeller Chapel",
      dek: "The tallest building on campus stands where houses used to",
      mapLabel: "Rockefeller",
      lat: 41.78805,
      lng: -87.5961,
      audioSrc: `${MEDIA}/audio/stop-07.mp3`,
      audioSeconds: 126,
      transcript: [
        "This is Rockefeller Chapel, finished in 1928, and it is still the tallest thing the university owns. That is not an accident. When John D. Rockefeller made his final gift to the school he had bankrolled, he asked that a chapel be its **central and dominant feature**, so that anyone looking at the skyline would read the university's priorities in stone. The architect, Bertram Goodhue, gave it a 207-foot tower, and a later Rockefeller filled that tower with one of the largest carillons on earth, 72 bells cast in England.",
        "Now look at the photograph from the year it rose. At the bottom edge of the construction site you can see houses coming down. Building the chapel meant **demolishing a row of homes on Woodlawn Avenue**, and the chapel was only one project among many. Between 1926 and 1933 the campus nearly doubled, twenty-one new Gothic buildings, and the land under them had rarely been empty. The university was becoming the biggest landowner on the South Side one block at a time, and it had learned to buy quietly, once even parking a title under its own architect's name so sellers would not know who was assembling the ground.",
        "Keep that habit in mind, because this walk keeps meeting it. A chapel takes a row of houses in 1928. Veterans' prefabs fill the Midway in 1946. A forty-one-acre campus expansion pushes south of the Midway in the 1950s, over the objections of the families living there. Hospitals take more blocks in the 1990s and 2000s. None of these projects was evil on its face, and some were genuinely good. The point is simpler. For a century, when this institution needed ground, it got the ground. The people on it moved. Remember the scale of that power when we reach 55th Street, where it was turned on an entire neighborhood at once.",
      ],
      images: [
        {
          src: `${MEDIA}/rockefeller-construction-1928.jpg`,
          alt: "Rockefeller Chapel under construction in October 1928, scaffolding around the tower and houses visible being cleared at the site's edge",
          credit:
            "The chapel rising, October 1928, houses coming down at the edge of the site. Chicago Architectural Photographing Company. Public domain.",
          label: "1928",
        },
      ],
      nowImage: {
        src: `${MEDIA}/rockefeller-today.jpg`,
        alt: "Rockefeller Chapel today, a Gothic limestone tower and long nave at 59th and Woodlawn",
        credit:
          "The chapel today. Photograph by Warren LeMay, via Wikimedia Commons. CC BY-SA 2.0.",
        label: "Today",
      },
      toNext: {
        text: "Walk north on Woodlawn Avenue one block to 58th Street. The long brick house with the flying roof on the corner is the Robie House.",
        distanceMeters: 160,
        minutes: 2,
      },
      sources: [
        { label: "Rockefeller Memorial Chapel, University of Chicago", url: "https://rockefeller.uchicago.edu/about/our-history" },
        { label: "Susan O'Connor Davis, Chicago's Historic Hyde Park (University of Chicago Press, 2013)", url: "https://press.uchicago.edu/ucp/books/book/chicago/C/bo8844257.html" },
        { label: "Rockefeller Chapel, Wikipedia", url: "https://en.wikipedia.org/wiki/Rockefeller_Chapel" },
      ],
    },
    {
      id: "robie-house",
      number: 8,
      title: "The Robie House",
      dek: "What the professors' quarter built when money was no object",
      mapLabel: "Robie House",
      lat: 41.78985,
      lng: -87.59585,
      audioSrc: `${MEDIA}/audio/stop-08.mp3`,
      audioSeconds: 157,
      transcript: [
        "Frederick Robie made bicycle parts. He ran his father's supply company, he was twenty-eight, and in 1908 he went to **Frank Lloyd Wright** with an engineer's brief. No boxy rooms, no drafts, and he wanted to see his neighbors without his neighbors seeing him. By 1910 he had this. Long Roman brick, roofs that hang far past their walls, a house that seems to be gliding while standing still. Wright called the style Prairie. Plenty of the neighbors just called it strange.",
        "For this walk, though, the house is really about money, and about the street it sits on. When the university opened in 1892, the blocks around it filled with big houses for professors, deans, and executives, many built on lots bought from Marshall Field himself. Woodlawn Avenue became the street where the money showed. Walk a block in either direction after this stop and look at the porches and the stonework. Hiring the most radical architect in America was simply what this street could afford, and it is exactly the class of resident Paul Cornell had imagined from the beginning.",
        "The house itself was nearly lost twice. The seminary next door announced demolition in 1941, and a letter campaign saved it. It tried again in 1957, and this time the rescue came from an unexpected direction. Wright, ninety years old, declared it the finest house he ever designed, Carl Sandburg compared the wreckers to book burners, and the man who actually wrote the check was **William Zeckendorf, the developer then building the new 55th Street on the urban renewal land**. He bought the house, used it as his site office, and passed it to the university. The man profiting most from the neighborhood's demolition saved its most famous house. Today it is a World Heritage Site.",
        "Now hold the two halves of this block in your head at once, because this is the turn in the whole story. Money confident enough to build this house was also confident enough to write rules about who could never own one. In 1909, one year after Robie hired Wright, a Hyde Park lawyer founded an improvement club whose stated purpose was keeping Black families out. Within a generation, the real estate profession had made that project official ethics. The red plate below is the rulebook itself.",
      ],
      interrupts: [
        {
          title: "The improvement associations",
          body: [
            "An improvement association was **a homeowners' club organized to control who could live on its blocks**. The clubs came before the paperwork, and this neighborhood built the prototype. In **August 1909** a Hyde Park attorney named Francis Harper organized the **Hyde Park Improvement Protective Club**, 350 members strong, with a stated mission of maintaining the color line. Its targets were not newcomers. Black doctors, teachers, and shopkeepers had lived in Hyde Park for fifteen years. The club pledged to **blacklist any realtor who sold to a Black buyer**, to buy out Black homeowners, and to replace Black workers with whites. A decade on, the neighborhood's Property Owners' Journal was still putting the theory plainly. **\"Every colored man who moves into Hyde Park knows that he is damaging his white neighbors' property. Therefore, he is making war on the white man.\"** The educator Fannie Barrier Williams, a Hyde Parker of fifteen years, answered for her neighbors. \"I've lived here for 15 years. What you trying to drive me out of my community?\"",
            "Where the paper failed, dynamite followed. Between **1917 and 1921 white Chicagoans bombed more than fifty Black homes** and the offices of the Black banker **Jesse Binga**, who kept writing mortgages anyway and told the papers, \"If they can make me move, they will say, we made Jesse Binga move. No, I will not run.\" Of the forty bombed families, two moved. In 1918 Baltimore's mayor wrote his realty board about \"a plan they have\" in Chicago for keeping Black families out of white blocks. Around the country, the association method became known simply as **the Chicago plan**.",
            "Then the profession absorbed it. In **1917 the Chicago Real Estate Board adopted block-by-block segregation as policy**, in **1921 it voted to expel any member who broke the line**, and in **1924 the national realtors' association wrote it into the code of ethics**. Article 34 read, \"A Realtor should never be instrumental in introducing into a neighborhood a character of property or occupancy, members of any race or nationality, or any individuals whose presence will clearly be detrimental to property values in that neighborhood.\" Selling a house to a Black family in a white neighborhood was, by the profession's own written standard, an ethics violation. **The race language stayed in the code until 1950.**",
          ],
        },
      ],
      images: [
        {
          src: `${MEDIA}/robie-1911.jpg`,
          alt: "The Robie House shortly after completion, from a 1911 architectural print",
          credit:
            "The Robie House new, from the 1911 Wasmuth portfolio. Historic American Buildings Survey. Public domain, via Wikimedia Commons.",
          label: "1911",
        },
      ],
      nowImage: {
        src: `${MEDIA}/robie-today.jpg`,
        alt: "The Robie House today, long Roman brick walls and cantilevered roofs in autumn light",
        credit:
          "The house today, run by the Frank Lloyd Wright Trust. Photograph by Warren LeMay, 2023, via Wikimedia Commons. CC BY-SA 2.0.",
        label: "Today",
      },
      toNext: {
        text: "Walk west on 58th Street, away from the lake, two blocks to the stone buildings. Enter the main quadrangle through the gateway and cross toward its west side. The long Gothic building with the pointed arch entrance is Cobb Hall.",
        distanceMeters: 420,
        minutes: 6,
      },
      sources: [
        { label: "Frank Lloyd Wright Trust, Robie House", url: "https://flwright.org/explore/frederick-c-robie-house" },
        { label: "Susan O'Connor Davis, Chicago's Historic Hyde Park (University of Chicago Press, 2013)", url: "https://press.uchicago.edu/ucp/books/book/chicago/C/bo8844257.html" },
        { label: "The Shame of Chicago, Shame of the Nation, episode 2, The Chicago Plan", url: "https://vimeo.com/1039725670" },
        { label: "NAREB Code of Ethics, 1924 (Article 34)", url: "https://www.nar.realtor/sites/default/files/documents/COE1924.pdf" },
        { label: "Inman, when the Realtor code required discrimination", url: "https://www.inman.com/2014/04/17/realtor-code-of-ethics-once-required-discrimination/" },
      ],
    },
    {
      id: "cobb-hall",
      number: 9,
      title: "Cobb Hall and the quad",
      dek: "A brand new university dressed up to look five hundred years old",
      mapLabel: "Cobb Hall",
      lat: 41.78875,
      lng: -87.60035,
      audioSrc: `${MEDIA}/audio/stop-09.mp3`,
      audioSeconds: 181,
      transcript: [
        "The building in front of you, with the pointed arch over its doors, is **Cobb Hall, the university's first building**. Classes started inside it on October 1, 1892, with 594 students, while the fair's palaces were still going up a mile east. It was paid for by Silas Cobb, a Chicago harness maker who had arrived nearly penniless sixty years earlier, and designed by an architect named Henry Ives Cobb. No relation. The university simply had that kind of luck with names.",
        "This is actually Chicago's second University of Chicago. The first was a Baptist school founded in the 1850s a few miles north, at 35th and Cottage Grove, on ten acres donated by Senator Stephen Douglas. The same Douglas who tipped off Paul Cornell, and a man whose fortune ran partly on a Mississippi plantation worked by enslaved people. That first school went bankrupt in 1886. When the Baptists set out to build a successor, they aimed much higher. **John D. Rockefeller pledged $600,000**, on the condition that others raise $400,000 more, and Marshall Field, the department store king, put in the first ten acres of land right here. Rockefeller's gifts eventually passed $35 million, and a seminary project became one of the richest universities on earth.",
        "Now look hard at the architecture, because the architecture is a confession. Everything around you was brand new in the 1890s, but the trustees ordered **English Gothic, modeled on Oxford and Cambridge**, precisely so the campus would look like it had stood for five centuries. They planted ivy at the feet of the walls to hurry the illusion along. A new school in a new city bought itself instant ancestry.",
        "The university's relationship to its neighbors was more complicated than its walls suggest. In 1942 it hired **William Allison Davis, the first Black scholar to hold full faculty rank at a majority-white American university**, with a Rosenwald grant paying his salary. Then it let the neighborhood it had helped seal shut do the rest. Davis and his family could not rent in Hyde Park or Kenwood. One of the most distinguished professors on this quad went home at night to Washington Park, on the far side of the covenant line his own employer had helped pay to defend. The faculty club denied him membership for years. The ivy caught up with the walls in a few seasons, and the university's welcome took a good deal longer.",
        "One more thing before you move on. To make its name fast, the young university bet on football. It was a founding member of the conference that became the Big Ten, and its coach, Amos Alonzo Stagg, was the first in America hired with faculty rank. The team practiced on the Midway you just left. The stadium, and what happened underneath it, is the next stop.",
      ],
      images: [
        {
          src: `${MEDIA}/cobb-hall-1900s.jpg`,
          alt: "A linen postcard of ivy-covered Cobb Hall at the University of Chicago",
          credit:
            "Cobb Hall under its ivy, from a linen postcard, around the 1930s. Tichnor Brothers collection. Public domain, via Wikimedia Commons.",
          label: "c. 1935",
        },
      ],
      nowImage: {
        src: `${MEDIA}/cobb-hall-today.jpg`,
        alt: "Cobb Hall today, gray Gothic stone with red roofs, seen across the main quadrangle lawn",
        credit:
          "Cobb Hall today, still holding classes. Photograph by Warren LeMay, via Wikimedia Commons. CC BY-SA 2.0.",
        label: "Today",
      },
      toNext: {
        text: "Leave the quad on its north side, through the gate onto 57th Street. Turn left, and at Ellis Avenue stop by the big ribbed concrete library on the corner.",
        distanceMeters: 350,
        minutes: 5,
      },
      sources: [
        { label: "University of Chicago, Cobb Lecture Hall", url: "https://architecture.uchicago.edu/locations/cobb_lecture_hall" },
        { label: "University of Chicago, the main quadrangle", url: "https://architecture.uchicago.edu/locations/main_quadrangle" },
        { label: "Susan O'Connor Davis, Chicago's Historic Hyde Park (University of Chicago Press, 2013)", url: "https://press.uchicago.edu/ucp/books/book/chicago/C/bo8844257.html" },
        { label: "UChicago Library, the Old University of Chicago", url: "https://www.lib.uchicago.edu/e/scrc/findingaids/view.php?eadid=ICU.SPCL.OLDUOFC" },
        { label: "Allison Davis, Wikipedia", url: "https://en.wikipedia.org/wiki/Allison_Davis" },
      ],
    },
    {
      id: "stagg-field",
      number: 10,
      title: "Stagg Field and the pile",
      dek: "Football crowds, then the atomic age, on one city block",
      mapLabel: "Stagg Field",
      lat: 41.79225,
      lng: -87.5999,
      audioSrc: `${MEDIA}/audio/stop-10.mp3`,
      audioSeconds: 179,
      transcript: [
        "The concrete library filling this block is the Regenstein, and under your feet is one of the strangest double histories in America. This was **Stagg Field**. The old stadium looked like a castle, notched stone walls and towers, and on big fall Saturdays crowds pressing fifty thousand poured off the trains and into these streets to watch the Maroons, one of the first powers of college football. The 1905 team went unbeaten and outscored its opponents 271 to 5. Football fame is what first made this university a household name.",
        "Then the university fired its own myth. **Robert Maynard Hutchins**, the young president who arrived in 1929, thought big-time sports had no business at a serious university, and in December 1939 he abolished varsity football outright. Chicago walked out of the Big Ten a few years later. Understand what that cost, because the bill comes due later on this walk. Alumni walked away and took their checkbooks. Undergraduate enrollment collapsed from about five thousand to about twelve hundred, applications fell by more than half, and the university started eating its endowment to stay open. Hutchins built a different identity instead, the great-books Core that still shapes every undergraduate here, and on race he settled for half measures, quietly tolerating the covenants his own faculty called repulsive. A broke university convinced its neighborhood was the problem. Hold that thought for 55th Street.",
        "The abandoned stadium then got the twentieth century's most consequential second act. In 1942 the Manhattan Project was building its first reactor out in a forest preserve southwest of the city, precisely because the experiment was so dangerous. Then a builders' strike stalled the site, and rather than wait, Enrico Fermi convinced his chiefs he could run it safely in a **squash court under the west stands of the empty stadium**. On the afternoon of December 2, 1942, his team slid the control rods out of a pile of graphite and uranium and ran the **first self-sustaining nuclear chain reaction in history**, for four and a half minutes, in secret, in a residential neighborhood of a city of more than three million people. Even the mayor was never told.",
        "The stands came down after the war. The Regenstein rose on the footprint in 1970, the glass dome next door followed, and on Ellis Avenue a dark bronze sculpture by Henry Moore marks the exact spot of the pile. Physics made this university's name global. But while its scientists were remaking the world, its lawyers and planners were remaking the neighborhood, and that story picks back up two blocks north on 55th Street.",
      ],
      images: [
        {
          src: `${MEDIA}/stagg-field-1942.jpg`,
          alt: "A drawing of Chicago Pile-1, the graphite reactor stacked under the Stagg Field stands in 1942, with a ladder leaning against it",
          credit:
            "Chicago Pile-1 under the west stands. No photograph of the finished pile was ever taken; this drawing is the only image of it. Melvin A. Miller, Argonne National Laboratory. Public domain.",
          label: "1942",
        },
      ],
      nowImage: {
        src: `${MEDIA}/regenstein-today.jpg`,
        alt: "The Regenstein Library today, ribbed concrete towers on the block where Stagg Field stood",
        credit:
          "The Regenstein Library on the old Stagg Field block today. Photograph by Warren LeMay, via Wikimedia Commons. CC BY-SA 2.0.",
        label: "Today",
      },
      toNext: {
        text: "Walk north on Ellis Avenue to 55th Street, then turn right and head east. After Greenwood, low townhouses with small fenced courts line the street. Stop anywhere along that row.",
        distanceMeters: 1050,
        minutes: 13,
      },
      sources: [
        { label: "University of Chicago, the first nuclear reactor explained", url: "https://news.uchicago.edu/explainer/first-nuclear-reactor-explained" },
        { label: "Chicago Maroon, how football found its place at UChicago", url: "https://chicagomaroon.com/39731/grey-city/brains-over-brawn-how-football-found-its-place-at-uchicago/" },
        { label: "Susan O'Connor Davis, Chicago's Historic Hyde Park (University of Chicago Press, 2013)", url: "https://press.uchicago.edu/ucp/books/book/chicago/C/bo8844257.html" },
        { label: "1905 Chicago Maroons football team, Wikipedia", url: "https://en.wikipedia.org/wiki/1905_Chicago_Maroons_football_team" },
        { label: "Atomic Archive, the first pile", url: "https://www.atomicarchive.com/history/first-pile/firstpile_01.html" },
      ],
    },
    {
      id: "fifty-fifth",
      number: 11,
      title: "Fifty-Fifth Street",
      dek: "When the covenants fell, the speculators arrived",
      mapLabel: "55th Street",
      lat: 41.79495,
      lng: -87.5918,
      audioSrc: `${MEDIA}/audio/stop-11.mp3`,
      audioSeconds: 213,
      transcript: [
        "In 1948 the Supreme Court made racial covenants unenforceable, and Hyde Park's paper wall came down. After decades boxed inside the overcrowded Black Belt, Black families could finally buy on blocks like this one, and they did. In 1940 Hyde Park was one and a half percent nonwhite. By 1956 it was almost thirty-seven percent, with twenty thousand white residents leaving and twenty-four thousand Black residents arriving in six years. What met the newcomers was not a welcome. It was a business model, and it worked both sides of the street.",
        "Here is the play. A speculator sells one building on an all-white block to a Black family. Then he knocks on every white door on the block with a warning. Your house is worth real money today, but the neighborhood is finished, and next year it will bring less. Frightened owners sold cheap. The speculator then resold the very same buildings to Black buyers at nearly **double the price, on contract**, because no bank would write them a mortgage. The white seller lost, the Black buyer paid brutally, and the man in the middle kept the difference. They called it **blockbusting**, and it turned over block after block on the South Side in a few short years.",
        "The overcrowding was part of the machine too. Buildings that started as fair-era hotels and one-family flats were carved into **kitchenettes**, single rooms with a hot plate and a shared bathroom down the hall. More tenants meant more rent from the same walls. Then the crowding and the wear were pointed at as proof that Black neighbors ruined property, by the very interests collecting the rents.",
        "The same arc had already run once, a mile northwest of here, and it is worth telling because the owner of every mansion in this city knew it. **Drexel Boulevard** was laid out on the ruins of a dream called Egandale, four hundred acres a doctor drained and enclosed for grand gardens that never got built. The parkway cut through it became the most exclusive boulevard on the South Side, castles and chateaux behind formal plantings, with the oldest public fountain in Chicago anchoring its foot. Then the elevated train arrived in 1909, the wealthy drifted north, and the mansions were cut into flats, six units becoming twelve becoming thirty-six. The color line settled into the alley behind Cottage Grove, one block over. When the money left, it took the boulevard's name off the society pages, and decades of redlining and disinvestment did the rest. The fountain still runs. Walk Drexel today and you can read this whole tour in one street.",
        "And understand what this street was before the wreckers came. Dozens of bars, clubs, and shops ran along 55th and Lake Park, the tavern count climbing every year the covenants aged. The Compass Players opened in a storefront at 1152 East 55th in 1955, the troupe that grew into Second City. It was crowded, loud, newly integrated, a little rough, and more alive than almost any street in the city. The university two blocks south looked at all that life and saw a threat to its future. What it did about it is the next stop. First, the red plates here name the machinery that made the whole cycle turn.",
      ],
      interrupts: [
        {
          title: "Redlining",
          body: [
            "Redlining was **the color-coding of neighborhoods by race, for the purpose of lending**. In 1939 and 1940 a federal agency, the **Home Owners' Loan Corporation**, graded every Chicago neighborhood for mortgage risk. Green was best, then blue, then yellow, then red. The grades were not invented in Washington. **Local realtors and lenders filled out the surveys**, men trained on the industry's race-based appraisal manuals, and the government inked their judgments onto maps. As few as **three or four Black families could get a whole neighborhood stamped hazardous**. Most of the Black Belt was drawn red. Hyde Park and Kenwood were drawn yellow, definitely declining, in part because Black Chicago lived next door.",
            "The **Federal Housing Administration** pointed lenders the same way. Its underwriting manual, written by the same **Frederick Babcock** whose 1924 appraisal textbook taught that race drives property decline, warned against insuring mortgages where there was, in its words, **the infiltration of inharmonious racial groups**. A red or yellow grade meant no ordinary mortgage, no home improvement loan, and no business loan, for every address on the block at once. And when the NAACP pressed Franklin Roosevelt to act, the answer that came back, as the historians in The Shame of Chicago retell it, was that this was the market, and the market had to be respected.",
            "The results were absolute. When the Black realtor **Dempsey Travis** led a survey of Chicago's 243 white-owned banks, **exactly one would lend to a Black family moving into a white neighborhood**. Hyde Parkers eventually built their own answer, a **savings and loan raised in 1952 from 750 small donors** so Black neighbors could get ordinary mortgages and rehab loans. That vacuum, and who moved into it, is the next plate.",
          ],
        },
        {
          title: "Blockbusting",
          body: [
            "Blockbusting was **the business of turning white panic into profit**. The speculator's opening move was fear at the dinner hour, **phone calls night after night and flyers under every door**, telling white owners a Black family had bought on the block and their equity was about to vanish. A house worth **$15,000 went for $14,000** to the speculator. Within days the same house sold to a Black family for **$27,000, on contract**, because the redlined banks had left them no other way to buy.",
            "The trade depended on **both prejudices at once**. It needed white owners who believed a Black neighbor destroyed value, and it needed Black buyers desperate enough to pay double for what the city refused to sell them honestly. Hyde Park's **block clubs**, more than sixty of them at the peak, fought it house by house, reporting illegal conversions, meeting the panic calls, and on at least one block quietly **passing the hat so a Black family trapped in a punitive contract could keep their home**.",
          ],
        },
        {
          title: "Buying on contract",
          body: [
            "A contract sale was **rent with none of rent's protections, dressed up as ownership**. The buyer put money down and paid monthly, but **owned nothing until the final payment**. Miss one month and the seller could evict, keep every dollar already paid, and sell the house again on a fresh contract. Researchers at Duke found that **75 to 95 percent of the homes sold to Black families in 1950s and 60s Chicago were sold on contract**, at an average markup of **84 percent**. A city commission study of one just-changed neighborhood found 82 percent of sales to Black families were on contract at nearly twice the home's value. The sellers were often syndicates of downtown professionals, and the financing came from **the same banks that had refused the buyers a mortgage**.",
            "The lawyer **Mark Satter** spent the 1950s dragging the scheme into the light after two clients, Sally and Albert Bolton, paid faithfully for two years, went late once, and got an eviction notice. He found they had paid **three times what their seller had**, and he spent the rest of his short life naming the operators, writing that banking policy and \"the wicked speculators exacted a fearful tribute from the Negro man and his family.\" He died at forty-nine, and the Daily News wrote that he fought the money lenders when other lawyers shied away.",
            "The buyers finally beat the system themselves. In the late 1960s, families on the West Side organized the **Contract Buyers League**, confronted their sellers together, and held payments in escrow like a rent strike through the coldest days of January 1970. **Over 400 contracts were renegotiated**, worth about six million dollars back then. The Duke study put the total wealth taken from Black Chicago families through contract sales at **$3.2 to $4 billion**. Payments that steep left nothing for repairs, and the disrepair was then cited as proof that Black neighbors lowered property values.",
          ],
        },
      ],
      images: [
        {
          src: `${MEDIA}/kitchenette-1941.jpg`,
          alt: "A grand corner apartment building in the Black Belt in 1941 with a sign reading Park-Vista Kitchenettes, people and cars on the street below",
          credit:
            "A Black Belt apartment house cut into one-room kitchenettes. Russell Lee, April 1941, Farm Security Administration, Library of Congress. Public domain.",
          label: "1941",
        },
        {
          src: `${MEDIA}/drexel-fountain-1890.jpg`,
          alt: "The Drexel Fountain around 1890, an ornate bronze fountain on the boulevard's landscaped median",
          credit:
            "The Drexel Fountain around 1890, from Picturesque Kenwood, when the boulevard was the South Side's grandest address. Public domain.",
          label: "c. 1890",
        },
      ],
      nowImage: {
        src: `${MEDIA}/55th-street-today.jpg`,
        alt: "The 1961 urban renewal townhouses on 55th Street today, flat-roofed rows behind small fenced front courts",
        credit:
          "The renewal-era townhouses on 55th Street today. Photograph by Warren LeMay, via Wikimedia Commons. CC BY-SA 4.0.",
        label: "Today",
      },
      toNext: {
        text: "Keep east on 55th Street to Harper Avenue, then turn north. Two blocks up, 53rd Street opens into a plaza with a glass tower above the shops. That is Harper Court.",
        distanceMeters: 790,
        minutes: 10,
      },
      sources: [
        { label: "The Plunder of Black Wealth in Chicago, Duke report, 2019", url: "https://www.fhcci.org/wp-content/uploads/2019/05/Plunder-of-Black-Wealth-Chicago-Report-2019.pdf" },
        { label: "The Shame of Chicago, Shame of the Nation, episode 1, The Color Tax", url: "https://vimeo.com/1039717887" },
        { label: "WBEZ, contract buying robbed Black families of billions", url: "https://www.wbez.org/money/2019/05/30/contract-buying-robbed-black-families-in-chicago-of-billions" },
        { label: "Mapping Inequality, the HOLC maps of Chicago", url: "https://dsl.richmond.edu/panorama/redlining/" },
        { label: "Ta-Nehisi Coates, The Case for Reparations", url: "https://www.theatlantic.com/magazine/archive/2014/06/the-case-for-reparations/361631/" },
        { label: "Susan O'Connor Davis, Chicago's Historic Hyde Park (University of Chicago Press, 2013)", url: "https://press.uchicago.edu/ucp/books/book/chicago/C/bo8844257.html" },
      ],
    },
    {
      id: "harper-court",
      number: 12,
      title: "Harper Court",
      dek: "Urban renewal rebuilt the neighborhood, and chose its neighbors again",
      mapLabel: "Harper Court",
      lat: 41.79945,
      lng: -87.58845,
      audioSrc: `${MEDIA}/audio/stop-12.mp3`,
      audioSeconds: 393,
      transcript: [
        "Start with why. By 1950 the university was in real trouble. The Hutchins reforms had cut undergraduate enrollment to about twelve hundred, the endowment was draining, and the trustees seriously discussed moving the whole institution out of Chicago. They stayed for the plainest of reasons. Nobody buys a used campus. So the new president, Lawrence Kimpton, drew the other conclusion. If the university could not leave the neighborhood, the neighborhood would have to change. In 1952, after the wife of a faculty member was kidnapped from her home and a thousand residents packed a protest meeting, the university created the **South East Chicago Commission** and handed it to a lawyer named Julian Levi. Levi ran it for almost thirty years and described it himself, in a university publication, as the political wing of the university.",
        "Levi helped write the state and federal renewal laws he needed, then used them. An Illinois law the university lobbied through Springfield in 1953 went further than anything before it. A private body could now target blocks that merely **might become blighted**. One of the first areas so designated sat right by campus, where the residents were largely Japanese American families, many of them resettled from wartime internment camps, and Black families whose buildings were, by their own block clubs' accounting, in good shape. St. Clair Drake, the Black sociologist who co-wrote Black Metropolis, lived there and joined the lawsuit against the plan. It went ahead anyway. Hyde Park and Kenwood became the site of the **first great federally backed urban renewal scheme in the country**.",
        "The mechanics were blunt. Blocks were declared blighted. Public money bought them by eminent domain and cleared them. The land, bought for about forty million dollars, was resold to approved developers for four, with the public eating the difference, and the university put in millions of its own besides. Demolition started along 55th and Lake Park in 1955, and the full plan passed City Council in 1958. By the summer of 1962, 564 of the 856 buildings marked for demolition were already down. When it was over, nearly **four thousand dwelling units were gone and about twenty-one hundred had replaced them**, and close to **twenty thousand people had been displaced**. Under the final plan, the great majority of displaced families were Black. Of the families steered into subsidized housing, 484 were Black and 15 were white. The neighborhood lost more than a quarter of its population in the 1960s alone. James Baldwin, watching the same program at work in San Francisco, gave it the name that stuck. Urban renewal, he said, \"means Negro removal.\" Planners had a different phrase, and in 1958 the comedians Mike Nichols and Elaine May tried out a joke about it at a Hyde Park fundraiser. Here we stand, black and white, shoulder to shoulder, against the lower classes. The Herald reported nervous laughter.",
        "Look at the two photographs on this page, taken from the same spot on the tracks in 1955 and 1961. That is a working commercial street becoming a shopping center with a parking lot. **641 businesses disappeared** in the clearance. Renting families got moving money. Renting businesses got nothing. Anderson Hardware was pushed off 55th three separate times, and once, when the notice came too fast, its customers loaded the stock into shopping carts and moved the store themselves. What could rebuild was what a mortgage would approve, and the mortgage wanted chains. Woolworth, Walgreens, a candy shop, a burger bar. Jane Jacobs was writing The Death and Life of Great American Cities at that exact moment and used Hyde Park as a warning, a neighborhood surrendered to a single landlord's idea of order. The twin towers you passed on 55th are that idea in concrete, I. M. Pei's University Apartments, 540 units parked on an island in the middle of the street, with closed-circuit television at the doors.",
        "This particular corner is the gentler part of the story. When the wreckers took the 57th Street art colony, the shacks left over from the fair that had housed Chicago's bohemia for half a century, neighbors raised money, took Small Business Administration loans, and built **Harper Court** in 1965 to rehouse the displaced artisans at rents under a hundred dollars. The old cast-iron horse trough from the colony came along as a planter. It worked for a generation, became the neighborhood's living room, and then the university-backed redevelopment of the 2000s tore that down too, for the glass tower above you.",
        "Two things are true at once about what happened here, and the honest version of this tour holds both. Hyde Park after renewal became one of the few Chicago neighborhoods where integration more or less held, roughly a third Black and half white for decades, and residents who fought for that outcome meant it. The Herald called it worth whatever price must be paid. And the price was paid mostly by people who never got a vote, in a plan built on the theory, stated almost openly, that integration was acceptable so long as the poor were removed. In 1962 students sat in at the administration building for two weeks after proving, with paired Black and white test couples, that the university was refusing Black tenants in its own apartment buildings. The chairman of the campus chapter that ran the test was a twenty-year-old named Bernie Sanders. The university negotiated an end to the sit-in and, in time, the policy. The instinct it confessed to, choosing the neighborhood's residents to protect an institution, is Cornell's founding idea wearing a twentieth-century suit. The red plate below is the last piece of machinery, and then the final stop closes the circle.",
      ],
      interrupts: [
        {
          title: "Urban renewal",
          body: [
            "Urban renewal was **the legal power to declare blocks blighted, clear them with public money, and choose what replaced them**. The **Hyde Park-Kenwood plan, approved November 7, 1958, was the nation's first large federally supported renewal scheme**, driven by the university's **South East Chicago Commission**, and Illinois's 1953 conservation law, which the university helped write, went further, letting planners condemn blocks that only **might decline someday**. The cleared land cost the public about **$40 million and was resold to developers for $4 million**.",
            "What it built is all around this corner, the townhouses, the mid-street towers, the shopping court. What it removed was the housing poor families could afford and **641 businesses**, from the bars and taverns of 55th Street to the corner hardware store. Nearly **4,000 dwelling units came down and about 2,100 went up**, priced for a different class of neighbor. The university opposed public housing in the plan area, and **only 34 units were ever built**. Planners called it conservation. The displaced, and Baldwin, had a shorter word for it. The tools changed over this walk, from a code of ethics to a deed clause to a color on a map to a wrecking ball. **The incentives never did.**",
          ],
        },
      ],
      images: [
        {
          src: `${MEDIA}/fifty-fifth-1955.jpg`,
          alt: "55th Street at Lake Park in 1955, a dense commercial street of storefronts, signs, and streetcar tracks seen from the railroad embankment",
          credit:
            "55th Street looking west from the IC tracks in 1955, before the wreckers. Reproduced in Susan O'Connor Davis, Chicago's Historic Hyde Park (University of Chicago Press).",
          label: "1955",
        },
        {
          src: `${MEDIA}/harper-court-today.jpg`,
          alt: "Harper Court's 53rd Street frontage today in falling snow, chain storefronts under a glass office tower",
          credit:
            "Harper Court's 53rd Street front today. Photograph by TonyTheTiger, 2025, via Wikimedia Commons. CC0.",
          label: "Today",
        },
      ],
      nowImage: {
        src: `${MEDIA}/fifty-fifth-1961.jpg`,
        alt: "The same view of 55th Street in 1961, the storefronts replaced by a shopping center, parking lot, and the twin University Apartments towers",
        credit:
          "The same view in 1961, the shopping center and Pei's towers in place. Reproduced in Susan O'Connor Davis, Chicago's Historic Hyde Park (University of Chicago Press).",
        label: "1961",
      },
      toNext: {
        text: "The last leg is the longest, about twenty minutes. Take Harper Avenue south back to 55th, jog east to Lake Park, and follow Lake Park and then Stony Island south. Past the Midway, the granite tower rising out of Jackson Park is the Obama Presidential Center. Enter the campus from Stony Island.",
        distanceMeters: 1750,
        minutes: 22,
      },
      sources: [
        { label: "UChicago CEGU, university-led urban renewal", url: "https://cegu.uchicago.edu/2023/11/30/university-led-renewal/" },
        { label: "Susan O'Connor Davis, Chicago's Historic Hyde Park (University of Chicago Press, 2013)", url: "https://press.uchicago.edu/ucp/books/book/chicago/C/bo8844257.html" },
        { label: "Hyde Park Herald, Lost Hyde Park's land clearance", url: "https://www.hpherald.com/news/local/lost-hyde-park-land-clearance/article_64703e2e-7240-11ec-b986-ebf650131a4d.html" },
        { label: "University of Chicago sit-ins, Wikipedia", url: "https://en.wikipedia.org/wiki/University_of_Chicago_sit-ins" },
        { label: "Docomomo, the Hyde Park A and B renewal project", url: "https://docomomo-us.org/news/hyde-park-a-b-urban-renewal-project" },
        { label: "James Baldwin in Take This Hammer, 1963", url: "https://scalar.usc.edu/works/housing-inequality/urban-renewalmeans-negro-removal--james-baldwin-1963" },
        { label: "South Side Weekly, the fight over Chicago's largest private police force", url: "https://southsideweekly.com/the-fight-over-chicagos-largest-private-police-force-university-of-chicago-ucpd/" },
      ],
    },
    {
      id: "obama-center",
      number: 13,
      title: "The Obama Center",
      dek: "The circle closes where the White City stood",
      mapLabel: "Obama Center",
      lat: 41.7859,
      lng: -87.5857,
      audioSrc: `${MEDIA}/audio/stop-13.mp3`,
      audioSeconds: 164,
      transcript: [
        "End on the plaza, where you can see the whole tower. Near the top, the granite wall turns into carved letters, lines from the speech Barack Obama gave at Selma in 2015. The museum opened on **June 19, 2026. Juneteenth.** It took almost five years to build, cost about 850 million dollars, and the Obamas chose this park, this exact ground, where Chicago staged the World's Fair you saw across the water at stop four. There is a lineage in that choice. The blocks you just walked launched Harold Washington, the city's first Black mayor, and Carol Moseley Braun, the first Black woman in the United States Senate, before they launched a president. The first Black president's words now wrap a 225-foot tower over the fairgrounds that shut Black Americans out.",
        "Hold the two summers side by side, because the contrast is the point. The White City went up fast, for one season of ticketed crowds, and its planners kept Black Americans out of its halls and out of its jobs. This tower was raised by **Lakeside Alliance, a construction team in which four Black-owned Chicago firms hold the controlling stake**, with a pledge that at least half the subcontracts go to diverse businesses. And where the fair was fenced, this is a park. Around you sit a **new branch of the Chicago Public Library**, a fruit and vegetable garden, a playground, and a hill built for winter sledding because Michelle Obama asked for one. The people the fair kept out are the people this place was made for.",
        "So stand here and run the whole line once. Cornell buys the marsh and picks his buyers. The fair dazzles the world while Wells and Douglass hand out the truth at its gates. The professors' quarter writes its rules, the realtors write theirs, the government colors the maps, the speculators write the contracts, and the bulldozers finish the job. Every stage of it had authors who signed their names. None of it just happened.",
        "In 1893 this ground told Black Chicagoans there was no room for them in the future. This summer, on Juneteenth, it said the opposite. A neighborhood that spent a century having its future decided by other people got a monument raised by its own hands, on its own ground, open to whoever walks in. Thanks for walking with us. The museum is worth the ticket, and if you are hungry, two optional detours continue the story, west along 63rd Street to the oldest restaurant in Chicago, then north to the house where the covenants started to fall.",
      ],
      images: [
        {
          src: `${MEDIA}/woodlawn-63rd-1973.jpg`,
          alt: "63rd Street in Woodlawn in 1973, with the elevated tracks crossing overhead and pedestrians on the sidewalks",
          credit:
            "63rd Street under the L, 1973, in the Woodlawn this story keeps returning to. John H. White, EPA DOCUMERICA, National Archives. Public domain.",
          label: "1973",
        },
      ],
      nowImage: {
        src: `${MEDIA}/opc-opening-2026.jpg`,
        alt: "The granite museum tower of the Obama Presidential Center on its opening day, with crowds filling the plaza below",
        credit:
          "The museum tower on opening day, June 19, 2026. Photograph by AlphaBeta135, via Wikimedia Commons. CC0.",
        label: "Today",
      },
      toNext: {
        text: "The main walk ends here, and the last two stops are a true detour rather than part of the route. Daley's Restaurant sits well west along 63rd Street at Cottage Grove, about half an hour on foot, and the Hansberry house is a short walk beyond it, so the two pair naturally. The number 63 bus covers the stretch, and there is parking nearby if you drove.",
        distanceMeters: 2300,
        minutes: 29,
      },
      sources: [
        { label: "Obama Foundation, grand opening FAQ", url: "https://www.obama.org/visit/grand-opening/faq/" },
        { label: "Obama Foundation, Lakeside Alliance named construction manager", url: "https://www.obama.org/press-releases/construction-manager/" },
        { label: "CBS Chicago, the Center's outdoor spaces ahead of the Juneteenth opening", url: "https://www.cbsnews.com/chicago/news/obama-presidential-center-outdoor-spaces-amenities-year-round/" },
        { label: "Time Out Chicago, what the Center offers without a ticket", url: "https://www.timeout.com/chicago/news/11-things-you-can-do-at-the-obama-presidential-center-without-a-ticket-071726" },
      ],
    },
    {
      id: "daleys",
      number: 14,
      title: "Daley's Restaurant",
      dek: "The oldest restaurant in Chicago has watched this whole story from one corner",
      mapLabel: "Daley's",
      lat: 41.7806,
      lng: -87.6064,
      optional: true,
      audioSrc: `${MEDIA}/audio/stop-14.mp3`,
      audioSeconds: 144,
      transcript: [
        "First, plainly. This stop is not on the walking route. It sits about a mile and a half west of where the walk ends, so come by bus, by car, or on fresh legs, and know that the Hansberry house, the last stop, waits a short walk from here. Second, just as plainly. Nobody paid for this stop, and nobody at Daley's knows it exists. It is here because after five miles of this story you have earned a good breakfast plate, and because no business in Chicago has watched the story longer from one corner.",
        "In 1892 an Irish immigrant ironworker named **John Daley opened a lunchroom here at 63rd and Cottage Grove**, feeding the crews building the elevated railroad above the street, with the World's Fair rising a mile east. That makes it, by most accounts, **the oldest restaurant in Chicago**, older than the L trains it fed. In 1918 Daley sold to two Greek immigrants who worked in the place, a waiter named Tom Kyros and a cook named Paul Emmanuel, and the same extended family has run it ever since. They kept the Daley name. It was already worth something.",
        "Think about what has passed this corner since. 63rd Street became one of the busiest commercial streets in Black Chicago as the Great Migration remade Woodlawn, and the restaurant stayed put and fed its neighborhood while so much else moved away or burned. The menu turned toward smothered pork chops, catfish, and biscuits because that is what the neighborhood wanted. **Muhammad Ali ate here between training sessions** in the 1960s. Disinvestment hit 63rd as hard as any street in the city, the L overhead was even torn back, and Daley's kept the griddle on. In 2019 it moved into a new building directly across the street, at 6257 South Cottage Grove, and kept serving.",
        "A restaurant is a small thing to set against covenants and bulldozers. But notice what it proves. A business that stayed, served whoever walked in, and changed with its neighbors instead of fleeing them has outlived nearly every business in this story. Get the breakfast. Then, if you have one more stop in you, the house where the paper wall started to crack is a short walk northwest.",
      ],
      images: [
        {
          src: `${MEDIA}/sixty-third-1973.jpg`,
          alt: "63rd Street in 1973, vacant lots and fire-scarred buildings along the once-busy commercial street",
          credit:
            "63rd Street in 1973, when fires and disinvestment were emptying one of Black Chicago's busiest streets. John H. White, EPA DOCUMERICA, National Archives. Public domain.",
          label: "1973",
        },
      ],
      toNext: {
        text: "Walk north on Cottage Grove to 61st Street, turn left, and go west to Rhodes Avenue. Turn left again. The brick three-flat partway down the block, 6140 South Rhodes, is the Hansberry house. It is a private home, so look from the sidewalk.",
        distanceMeters: 980,
        minutes: 13,
      },
      sources: [
        { label: "Daley's Restaurant, our history", url: "https://www.daleysrestaurant.com/history" },
        { label: "Daley's Restaurant, menus", url: "https://www.daleysrestaurant.com/menus" },
      ],
    },
    {
      id: "hansberry-house",
      number: 15,
      title: "The Hansberry house",
      dek: "One family's move into this three-flat cracked the covenant wall",
      mapLabel: "Hansberry house",
      lat: 41.7827,
      lng: -87.6123,
      optional: true,
      audioSrc: `${MEDIA}/audio/stop-15.mp3`,
      audioSeconds: 206,
      transcript: [
        "At first glance this is just a brick three-flat on a quiet block. But in 1937 this building became one of the most important addresses in the legal fight against housing segregation in America, and the little girl who lived behind that window grew up to put what happened here on Broadway.",
        "**Carl Hansberry** came up from Mississippi in the Great Migration, one of the hundreds of thousands the Defender called north. He became a real estate broker, and he watched his people pay double for half. The covenant wall this walk has traced ran right through here. This block sits in the **Washington Park Subdivision**, the northwest corner of Woodlawn, and its covenant was the very one the University of Chicago had helped defend in court four years earlier. Hansberry chose it deliberately. He wrote later, in the Defender, \"I figured the most vulnerable spot to attack the restrictive covenants was where the pressure was the greatest.\"",
        "In the spring of 1937 he bought this building and moved in his family. A white mob gathered. Something came through the window, a brick by some accounts, a chunk of concrete by others, and it barely missed the head of his seven-year-old daughter, **Lorraine**. A neighbor named Anna Lee sued to enforce the covenant, and the case, **Hansberry v. Lee**, went all the way to the Supreme Court. In 1940 the family won. It was a technicality, not a verdict on covenants themselves, but it voided the paper on this neighborhood, and the Defender reported that the ruling opened up hundreds of homes to Black Chicagoans. The full wall did not come down for eight more years, but this is where it cracked.",
        "The honest version of Carl Hansberry is complicated, and this tour owes it to him. He fought the covenants, sued a railroad over segregated cars, printed know-your-rights pamphlets, and founded a business league to bankroll Black enterprise. He also made part of his fortune carving buildings into the cramped kitchenettes this tour described at 55th Street. City officials called the family slumlords while inspectors buried them in fines. The Black press called him a race man. Both were describing the same cage from different sides, a market where a Black landlord could sell his people nothing better because the city allowed nothing better. Worn down and disillusioned, he was preparing a move to Mexico when he died there in 1946.",
        "Lorraine carried this house with her. In 1959 her play **A Raisin in the Sun**, about a Black family deciding whether to move into a white neighborhood that does not want them, became the first play by a Black woman produced on Broadway. The mob outside these windows is in it. So is the arithmetic of the kitchenettes. It opened while the bulldozers you heard about at Harper Court were rolling, and a letter writer to the Defender in 1962 caught the whole century in one line. If the bomb doesn't get him, the bulldozer will.",
        "This is the end of the walk. A boulder, a fair, a university, five kinds of paperwork, and one family's front window. The struggle you have been tracing all afternoon was fought at addresses like this one, and this one held. Thanks for walking the whole way with us. The rest of Rooted Forward's work lives at rooted-forward.org.",
      ],
      images: [
        {
          src: `${MEDIA}/hansberry-house-today.jpg`,
          alt: "The Hansberry house today, a brick three-flat at 6140 South Rhodes Avenue with a small front yard",
          credit:
            "The house today, a Chicago Landmark since 2010 and still a private home. Photograph by Legimet, via Wikimedia Commons. CC BY-SA 4.0.",
          label: "Today",
        },
      ],
      sources: [
        { label: "Hansberry v. Lee, 311 U.S. 32 (1940)", url: "https://supreme.justia.com/cases/federal/us/311/32/" },
        { label: "Lorraine Hansberry House, Wikipedia", url: "https://en.wikipedia.org/wiki/Lorraine_Hansberry_House" },
        { label: "Chicago Public Library, Lorraine Hansberry biography", url: "https://www.chipublib.org/lorraine-hansberry-biography/" },
        { label: "Chicago History Today, the Hansberrys move in, June 15, 1937", url: "https://chicagohistorytoday.wordpress.com/2014/06/15/restrictive-covenant-6-15-1937/" },
        { label: "Susan O'Connor Davis, Chicago's Historic Hyde Park (University of Chicago Press, 2013)", url: "https://press.uchicago.edu/ucp/books/book/chicago/C/bo8844257.html" },
      ],
    },
  ],
};
