import type { WalkTour } from "./walk-types";

// ------------------------------------------------------------------
// The Hyde Park walk. Nine stops on how the neighborhood was built
// and who it was built for, from Paul Cornell's stone at 53rd Street
// through the fair, the university, and the machinery of exclusion,
// ending at Harper Court. The route and stop coordinates were checked
// against the street grid in July 2026. The narration is written from
// the founder's family oral history, corrected against the sources
// listed on each stop; nothing in the transcript should outrun them.
// The five red "instruments" plates are page-only and are not read
// into the audio. Audio is generated by scripts/walk-tts-eleven.mjs
// --tour hyde-park; durations.json is the source of audioSeconds.
// ------------------------------------------------------------------

const MEDIA = "/media/hyde-park-walk";

export const HYDE_PARK_WALK: WalkTour = {
  title: "Walk Hyde Park",
  dek: "A free self-guided audio tour that starts and ends near Paul Cornell's stone by 53rd Street. Nine stops, about two hours on foot. Hyde Park sold exclusivity from its first day, and a century of paperwork decided who got to live in it.",
  walkMinutes: 76,
  listenMinutes: 12,
  distanceMiles: 3.7,
  startLabel: "Paul Cornell's stone, Harold Washington Park",
  practical: [
    {
      title: "Getting there and timing",
      text: "The walk starts in Harold Washington Park at 53rd Street, across from the Hampton House at 5300 South Shore Drive. The 53rd Street Metra stop is a few blocks west, and the 6 and 28 buses run nearby. Plan on about two hours with the stops. When you finish, Valois on 53rd serves cafeteria breakfast all day and the Medici on 57th has fed students for decades.",
    },
    {
      title: "The ground",
      text: "Flat city sidewalks the whole way, about three and a half miles. The busiest crossings are on 57th Street and along Lake Park Avenue; use the marked crosswalks. The university quadrangles are open to walk through every day. Going inside Robie House takes a timed ticket, but this tour only needs the outside.",
    },
    {
      title: "Listening",
      text: "Headphones are nicest, but a phone speaker works fine. Every stop's audio is also printed on the page, so you can read instead of listen. If you share your location, it is used only to draw your dot on the map. It never leaves your phone.",
    },
  ],
  route: [
    [41.7996, -87.5812],
    [41.7992, -87.5824],
    [41.799, -87.5833],
    [41.7992, -87.5852],
    [41.79946, -87.58734],
    [41.7976, -87.5875],
    [41.7957, -87.5877],
    [41.7938, -87.5878],
    [41.792, -87.5879],
    [41.7912, -87.5872],
    [41.7911, -87.585],
    [41.791, -87.5831],
    [41.7912, -87.586],
    [41.7913, -87.5885],
    [41.7914, -87.5921],
    [41.7916, -87.5945],
    [41.7917, -87.5962],
    [41.7907, -87.5961],
    [41.78985, -87.59585],
    [41.7887, -87.5964],
    [41.78855, -87.5966],
    [41.7888, -87.5978],
    [41.79, -87.598],
    [41.7911, -87.5983],
    [41.7913, -87.5999],
    [41.79225, -87.5999],
    [41.7931, -87.6008],
    [41.794, -87.6006],
    [41.7947, -87.599],
    [41.7948, -87.5962],
    [41.7949, -87.5935],
    [41.79495, -87.5918],
    [41.7951, -87.59],
    [41.7952, -87.5884],
    [41.7963, -87.5884],
    [41.7981, -87.5885],
    [41.79945, -87.58845],
  ],
  stops: [
    {
      id: "cornells-stone",
      number: 1,
      title: "Paul Cornell's stone",
      dek: "A boulder in the grass marks where the whole neighborhood started",
      mapLabel: "Cornell's stone",
      lat: 41.7996,
      lng: -87.5812,
      audioSrc: `${MEDIA}/audio/stop-01.mp3`,
      audioSeconds: 79,
      transcript: [
        "Find the boulder in Harold Washington Park near 53rd Street, across from the tall brick building with the red awning. That building matters in a minute. The stone marks roughly where Hyde Park began, and it began as one man's real estate play.",
        "Paul Cornell was a young lawyer who reached Chicago in 1847 and had his savings stolen his first night in town. Senator Stephen Douglas told him the smart money was south of the city. So Cornell rode down the lake shore, found a tavern keeper's farm near what is now 53rd Street, and in 1853 bought **sixty acres from the tavern keeper's widow**, Electa Watson. He kept buying until he held about **300 acres of lakefront**.",
        "The land was marsh and sand ridge. What he sold was escape. Chicago's sewage still ran into the river and the lake, and Cornell pitched clean air by the water to people who could afford to leave. In 1856 he gave the Illinois Central sixty acres, and in return the railroad built a **53rd Street station with six daily trains**. A resort hotel rose right here on the shore, the Hyde Park House. Mary Todd Lincoln stayed there the summer after her husband was killed. From the first sale, this neighborhood was designed to choose its neighbors.",
      ],
      lookFor:
        "The boulder itself, then the Hampton House across the drive. The old hotel's waterfront ran where the park grass is now.",
      images: [
        {
          src: `${MEDIA}/sisson-1920s.jpg`,
          alt: "The Sisson Hotel rising over the Hyde Park lakefront around 1920, with sailboats on the water in front of it",
          credit:
            "The Sisson Hotel on the old Hyde Park House grounds, around 1920. From Early Chicago Hotels. Public domain, via Wikimedia Commons.",
          label: "c. 1920",
        },
      ],
      nowImage: {
        src: `${MEDIA}/hampton-house-today.jpg`,
        alt: "The Hampton House today, a red brick tower with a red entrance awning behind park trees",
        credit:
          "The same building today, the Hampton House. Photograph by TonyTheTiger, 2006, via Wikimedia Commons. CC BY-SA 3.0.",
        label: "Today",
      },
      toNext: {
        text: "Walk to the corner of 53rd Street and Hyde Park Boulevard, one short block in from the lake. The tall hotel building on the corner, with carved faces in its terra cotta, is the Del Prado.",
        distanceMeters: 200,
        minutes: 3,
      },
      sources: [
        { label: "Hyde Park Historical Society, Paul Cornell", url: "https://www.hydeparkhistory.org/paul-cornell" },
        { label: "Hyde Park Herald, Hyde Park Stories on Paul Cornell", url: "https://www.hpherald.com/evening_digest/hyde-park-stories-paul-cornell/article_18568fa6-4ca5-4dfc-8d36-d90aa574ceda.html" },
        { label: "Hyde Park Historical Society, Harold Washington Park", url: "https://www.hydeparkhistory.org/blog/hyde-park-stories-harold-washington-park" },
        { label: "Hyde Park House, Wikipedia", url: "https://en.wikipedia.org/wiki/Hyde_Park_House" },
        { label: "Hampton House, Wikipedia", url: "https://en.wikipedia.org/wiki/Hampton_House_(Chicago)" },
      ],
    },
    {
      id: "del-prado",
      number: 2,
      title: "The Del Prado",
      dek: "The last of the grand resort hotels still stands on its corner",
      mapLabel: "Del Prado",
      lat: 41.799,
      lng: -87.5833,
      audioSrc: `${MEDIA}/audio/stop-02.mp3`,
      audioSeconds: 54,
      transcript: [
        "The apartment tower on this corner opened in 1918 as the **Cooper-Carlton Hotel** and took the name Del Prado in 1930, inherited from an older hotel out on the Midway. Look up at the carved faces in the terra cotta, then picture the lobby behind those doors full of trunks and porters.",
        "Hyde Park ran as a resort. Families checked in for whole summers. The men rode Cornell's trains downtown to work, and everyone else had the beach, the parks, sailboats, and concerts. Before air travel, a vacation happened close to home, and the railroad advertised this shore hard. Hotels like this one and the Sisson behind you were the product, grand suites with the lake at the door.",
        "Hold one detail from this porch. The guests were white, and so were the property deeds. Hyde Park's small Black community lived two blocks west, beside the railroad embankment. That is the next stop.",
      ],
      lookFor:
        "The terra cotta faces near the top of the Del Prado, and the ghost of a resort in its ground floor arches.",
      images: [
        {
          src: `${MEDIA}/del-prado-1900s.jpg`,
          alt: "A linen postcard of the Del Prado Hotel by the lake at Hyde Park Boulevard and 53rd Street, with sailboats on the water beyond",
          credit:
            "The Del Prado as a hotel, from a linen postcard calling it the finest residential hotel in the Middle West. Newberry Library collection. Public domain, via Wikimedia Commons.",
          label: "1930s",
        },
      ],
      nowImage: {
        src: `${MEDIA}/del-prado-today.jpg`,
        alt: "The Del Prado building today at 53rd and Hyde Park Boulevard, red brick with white terra cotta trim",
        credit:
          "The Del Prado today, apartments now. Photograph by TonyTheTiger, 2008, via Wikimedia Commons. CC BY-SA 3.0.",
        label: "Today",
      },
      toNext: {
        text: "Walk west on 53rd Street toward the railroad embankment. Stop at Lake Park Avenue where you can see the station stairs and the tracks running above the street.",
        distanceMeters: 350,
        minutes: 5,
      },
      sources: [
        { label: "Hotel Del Prado, Wikipedia", url: "https://en.wikipedia.org/wiki/Hotel_Del_Prado" },
        { label: "Julia Bachrach, Chicago's apartment hotels of the 1910s", url: "https://www.jbachrach.com/blog/2019/11/26/chicagos-apartment-hotels-of-the-1910s" },
        { label: "International House, exploring our history", url: "https://ihouse.uchicago.edu/90th-anniversary/90th-anniversary-explore-our-history/" },
      ],
    },
    {
      id: "lake-park-tracks",
      number: 3,
      title: "The tracks and Lake Park",
      dek: "The railroad that built the resort ran both directions",
      mapLabel: "53rd St tracks",
      lat: 41.79946,
      lng: -87.58734,
      audioSrc: `${MEDIA}/audio/stop-03.mp3`,
      audioSeconds: 65,
      transcript: [
        "These tracks are why everything else here exists. Cornell's deal put a station at 53rd Street in 1856, and suburban trains have stopped there ever since. The Illinois Central electrified the line in 1926, and Metra runs it now. The same main line keeps going south, through Mississippi, all the way to New Orleans.",
        "During the **Great Migration** that geography mattered. Black southerners rode the IC north by the hundreds of thousands, toward jobs and away from the terror of the South. The railroad that carried Cornell's summer guests out of the city carried a new Chicago into it.",
        "Lake Park Avenue, under the embankment, was the working back of the stage set, taverns and coal yards and cheap frame buildings. In the early 1900s a small **middle-class Black community lived along Lake Park and Harper**, holding a reception for Booker T. Washington at the Rosalie Music Hall in 1914, while the rest of Hyde Park stayed almost entirely white. The neighborhood kept its front door on the boulevards and its Black neighbors beside the tracks.",
      ],
      lookFor:
        "The embankment itself. Everything on the lake side of it was Cornell's resort; the strip beneath it was where the neighborhood put everyone the resort depended on.",
      images: [
        {
          src: `${MEDIA}/ic-electric-1967.jpg`,
          alt: "An Illinois Central Electric commuter train pulling into a wooden platform station in 1967",
          credit:
            "An Illinois Central Electric train at the 63rd Street station, 1967. Photograph by Lawrence and David Barera, via Wikimedia Commons. CC BY-SA 2.0.",
          label: "1967",
        },
      ],
      nowImage: {
        src: `${MEDIA}/metra-53rd-today.jpg`,
        alt: "A Metra Electric train approaching the 53rd Street station platforms on the Hyde Park embankment today",
        credit:
          "A train coming into the 53rd Street station today. Photograph by David Wilson, 2013, via Wikimedia Commons. CC BY 2.0.",
        label: "Today",
      },
      toNext: {
        text: "Follow Lake Park Avenue south beside the embankment, all the way to 57th Street. Cross toward the park and walk to the north face of the huge domed museum, by the water.",
        distanceMeters: 1300,
        minutes: 16,
      },
      sources: [
        { label: "51st/53rd Street Hyde Park station, Wikipedia", url: "https://en.wikipedia.org/wiki/51st/53rd_Street/Hyde_Park_station" },
        { label: "Cook County African American Heritage Trail, the railroad", url: "https://ccafricanamericanheritage.org/trail-stop/railroad/" },
        { label: "Hyde Park Herald, the Villas survive (the Half Century Club)", url: "https://www.hpherald.com/evening_digest/hyde-park-stories-the-villas-survive/article_1d5c91c8-bbf2-11ef-aa3d-d36c34ffc52c.html" },
        { label: "Hyde Park Herald, Lost Hyde Park's commercial core", url: "https://www.hpherald.com/news/local/lost-hyde-park-the-commercial-core/article_d282cc80-14ba-11ec-b846-f786cbbb9339.html" },
      ],
    },
    {
      id: "white-city",
      number: 4,
      title: "The White City",
      dek: "The fair that made Hyde Park famous also drew its hardest line",
      mapLabel: "White City",
      lat: 41.791,
      lng: -87.5831,
      audioSrc: `${MEDIA}/audio/stop-04.mp3`,
      audioSeconds: 64,
      transcript: [
        "The building across the water is the Museum of Science and Industry, the last of the 1893 World's Columbian Exposition's great palaces still standing where the fair put it. That summer this end of the park was the **White City**. Plaster palaces on steel frames, painted white because that was the cheapest way to make them match, and lit at night with more electricity than most visitors had ever seen in one place.",
        "The fair ran six months and drew some **27 million visits** while Chicago was still rebuilding from the Great Fire. It made Hyde Park famous, filled it with new hotels, and brought in thousands of workers the resort had never planned to house.",
        "It also drew a line. Black Americans were shut out of the fair's jobs and its exhibits. **Ida B. Wells and Frederick Douglass** answered from the gates with a pamphlet, The Reason Why the Colored American Is Not in the World's Columbian Exposition, and Wells counted the copies she handed out in the thousands. Keep that title with you. The rest of this walk is about how the same exclusion got written into the streets.",
      ],
      lookFor:
        "The 1893 facade across the basin, then the caryatids up close. Every other building this size at the fair was gone within a few years.",
      images: [
        {
          src: `${MEDIA}/palace-fine-arts-1893.jpg`,
          alt: "The domed Palace of Fine Arts reflected in the North Pond during the 1893 World's Fair",
          credit:
            "The Palace of Fine Arts, 1893, today's Museum of Science and Industry. C. D. Arnold, Official Views of the World's Columbian Exposition. Public domain, via Wikimedia Commons.",
          label: "1893",
        },
        {
          src: `${MEDIA}/court-night-1893.jpg`,
          alt: "The Grand Court of the 1893 fair at night, its domes and fountains outlined in electric light before a crowd",
          credit:
            "The Grand Court lit at night, drawn by Charles Graham, 1893. Library of Congress Prints and Photographs Division. Public domain.",
        },
      ],
      nowImage: {
        src: `${MEDIA}/columbia-basin-today.jpg`,
        alt: "The Museum of Science and Industry today, seen straight on across the still water of the Columbia Basin",
        credit:
          "The same building today, across the Columbia Basin. Photograph by Warren LeMay, 2024, via Wikimedia Commons. CC BY-SA 2.0.",
        label: "Today",
      },
      toNext: {
        text: "Walk west on 57th Street, away from the lake. Cross Stony Island at the light and keep going on 57th, past the bookstores, to Woodlawn Avenue. Turn left one block. The long brick house with the flying roof is on the corner at 58th.",
        distanceMeters: 1220,
        minutes: 16,
      },
      sources: [
        { label: "World's Columbian Exposition, Wikipedia", url: "https://en.wikipedia.org/wiki/World%27s_Columbian_Exposition" },
        { label: "The Reason Why the Colored American Is Not in the World's Columbian Exposition, full text", url: "https://digital.library.upenn.edu/women/wells/exposition/exposition.html" },
        { label: "Chicago Park District, Jackson Park history", url: "https://www.chicagoparkdistrict.com/parks-facilities/jackson-andrew-park" },
      ],
    },
    {
      id: "robie-house",
      number: 5,
      title: "The Robie House",
      dek: "What the professors' quarter built when money was no object",
      mapLabel: "Robie House",
      lat: 41.78985,
      lng: -87.59585,
      audioSrc: `${MEDIA}/audio/stop-05.mp3`,
      audioSeconds: 62,
      transcript: [
        "Frederick Robie made bicycle parts. In 1908 he hired **Frank Lloyd Wright**, and by 1910 he had this, a house that seems to be moving while it stands still. Wright called the style Prairie. Plenty of neighbors just called it strange.",
        "For this walk, the house is about money. When the university opened in 1892, these blocks filled with mansions for professors and executives, and streets like Woodlawn became the neighborhood's showcase. Hiring the most radical architect in America was something you did here to show you could.",
        "The seminary next door tried to demolish the house twice, in 1941 and again in 1957, when Wright, then ninety, came back to protest in person. A developer bought it, the university eventually took it over, and today it is a World Heritage Site. Saving the building turned out to be easier than sharing the street. While houses like this went up, the neighborhood was also organizing to decide exactly who could never own one, and that machinery had a rulebook.",
      ],
      lookFor:
        "Stand across Woodlawn and let the long roof lines run. Then look down the block. This is the product Cornell imagined, seventy years on.",
      interrupts: [
        {
          title: "The Chicago Real Estate Board",
          body: [
            "In 1917 the Chicago Real Estate Board adopted a policy of block-by-block segregation, confining Black residents to blocks that already had Black neighbors. In 1924 the national realtors' association wrote the idea into its code of ethics. Article 34 read, \"A Realtor should never be instrumental in introducing into a neighborhood a character of property or occupancy, members of any race or nationality, or any individuals whose presence will clearly be detrimental to property values in that neighborhood.\"",
            "An agent who broke the rule could be expelled from the board, which could end a career. Selling a house to a Black family in a white neighborhood was, by the profession's own written standard, an ethics violation. The race language stayed in the code until 1950.",
          ],
        },
      ],
      images: [
        {
          src: `${MEDIA}/robie-1911.jpg`,
          alt: "The Robie House shortly after completion, from a 1911 architectural print",
          credit:
            "The Robie House new, from the 1911 Wasmuth portfolio. Historic American Buildings Survey. Public domain, via Wikimedia Commons.",
          label: "1911",
        },
      ],
      nowImage: {
        src: `${MEDIA}/robie-today.jpg`,
        alt: "The Robie House today, long Roman brick walls and cantilevered roofs in autumn light",
        credit:
          "The house today, run by the Frank Lloyd Wright Trust. Photograph by Warren LeMay, 2023, via Wikimedia Commons. CC BY-SA 2.0.",
        label: "Today",
      },
      toNext: {
        text: "Continue south on Woodlawn Avenue one block to 59th Street. Cross to the edge of the long sunken green. That strip is the Midway Plaisance.",
        distanceMeters: 300,
        minutes: 4,
      },
      sources: [
        { label: "Frank Lloyd Wright Trust, Robie House", url: "https://flwright.org/explore/frederick-c-robie-house" },
        { label: "Robie House, Wikipedia", url: "https://en.wikipedia.org/wiki/Robie_House" },
        { label: "NAREB Code of Ethics, 1924 (Article 34)", url: "https://www.nar.realtor/sites/default/files/documents/COE1924.pdf" },
        { label: "Inman, when the Realtor code required discrimination", url: "https://www.inman.com/2014/04/17/realtor-code-of-ethics-once-required-discrimination/" },
      ],
    },
    {
      id: "midway-line",
      number: 6,
      title: "The Midway line",
      dek: "A canal that never came, and a border that did",
      mapLabel: "The Midway",
      lat: 41.78855,
      lng: -87.5966,
      audioSrc: `${MEDIA}/audio/stop-06.mp3`,
      audioSeconds: 61,
      transcript: [
        "This mile of green was the fair's carnival strip. Ticketed shows, beer gardens, and the first **Ferris wheel**, 264 feet tall. It also held the fair's so-called villages, where people brought from Africa, Asia, and the Americas were put on display for paying crowds. That happened on this lawn.",
        "The lawn sits sunken because Olmsted's plan called for a canal here, joining the Jackson Park lagoons to Washington Park. The digging started and the money ran out, so the water never came. Something else did. **The Midway became a border.**",
        "North of this grass, Hyde Park and the university. South of it, Woodlawn. For most of the last century that line divided investment from disinvestment, and none of it was chance. A mile southwest of here in 1937, a Black family named **Hansberry** bought a house across a line like this one, and a mob gathered the first evening. Their daughter Lorraine put that year on stage in A Raisin in the Sun. The red plate below explains the paperwork behind the mob.",
      ],
      lookFor:
        "Look east and west and feel the length of the strip. Then stand at the curb and look south into Woodlawn. The border is still legible in the buildings.",
      interrupts: [
        {
          title: "Restrictive covenants",
          body: [
            "A covenant is a promise written into a property deed. Chicago's version barred an owner from ever selling or renting to a Black person. In 1927 the Chicago Real Estate Board circulated a model covenant, drafted by the national association's counsel Nathan William MacChesney, and pushed it block by block through churches, clubs, and property owners' associations. More than 220 Cook County subdivisions adopted its language, and people at the time claimed covenants covered as much as three-quarters of the city's residential property.",
            "Hyde Park signed up with enthusiasm. In 1928 the Hyde Park Herald praised the covenants ringing the neighborhood as \"a marvelous delicately woven chain of armor.\" The University of Chicago spent $83,597 defending covenants in court. When Carl Hansberry bought at 6140 South Rhodes anyway, a chunk of concrete thrown through the window nearly hit seven-year-old Lorraine. The Supreme Court let the family stay in 1940 on a technicality, and in 1948 it made every racial covenant unenforceable. Nobody erased them. The words still sit on Cook County deeds today.",
          ],
        },
      ],
      images: [
        {
          src: `${MEDIA}/midway-1893.jpg`,
          alt: "The Midway Plaisance in 1893, crowded with visitors between the attractions, minarets and the Moorish Palace sign overhead",
          credit:
            "The Midway mid-fair, 1893, seen from the Ferris wheel. Public domain, via Wikimedia Commons.",
          label: "1893",
        },
      ],
      nowImage: {
        src: `${MEDIA}/midway-today.jpg`,
        alt: "The Midway Plaisance today, a long open sunken lawn lined with trees, with University of Chicago towers in the distance",
        credit:
          "The same ground today, a mile of open green. Photograph by Joe Passe, 2021, via Wikimedia Commons. CC BY-SA 2.0.",
        label: "Today",
      },
      toNext: {
        text: "Walk north into campus on University Avenue and pass through the gates into the main quadrangle. Notice how small the old gateways are; the quads were built to feel enclosed. Come out the far side onto 57th Street, turn left, and stop at Ellis Avenue by the big concrete library.",
        distanceMeters: 750,
        minutes: 10,
      },
      sources: [
        { label: "WTTW, how Chicago invented modern segregation", url: "https://www.wttw.com/firsthand/segregation/how-did-chicago-become-so-segregated-by-inventing-modern-segregation" },
        { label: "WBEZ, Chicago home records still contain racist covenants", url: "https://www.wbez.org/race-class-communities/2021/11/21/chicago-home-records-still-contain-racist-covenants" },
        { label: "Chicago History Today, the Hansberrys move in, June 15, 1937", url: "https://chicagohistorytoday.wordpress.com/2014/06/15/restrictive-covenant-6-15-1937/" },
        { label: "Chicago Public Library, Lorraine Hansberry biography", url: "https://www.chipublib.org/lorraine-hansberry-biography/" },
        { label: "Midway Plaisance, Wikipedia", url: "https://en.wikipedia.org/wiki/Midway_Plaisance" },
      ],
    },
    {
      id: "stagg-field",
      number: 7,
      title: "Stagg Field and the pile",
      dek: "Football, then the atomic age, on one city block",
      mapLabel: "Stagg Field",
      lat: 41.79225,
      lng: -87.5999,
      audioSrc: `${MEDIA}/audio/stop-07.mp3`,
      audioSeconds: 67,
      transcript: [
        "You just walked through quadrangles built to look ancient. They were brand new in 1892, Gothic on purpose, modeled on Oxford so a university funded by **Rockefeller's oil money and Marshall Field's land** would feel five hundred years old on opening day.",
        "This block held Stagg Field, and on big fall Saturdays crowds up to fifty thousand watched the Maroons, one of the powers of early college football. President Robert Hutchins wanted a university known for its classroom, not its backfield, and killed varsity football in 1939.",
        "Three years later the abandoned stadium got a second life. In a squash court under the west stands, on December 2, 1942, **Enrico Fermi's team ran the first self-sustaining nuclear chain reaction**, in secret, in the middle of a city of three and a half million. The library in front of you sits on the stadium's footprint. The university anchors this whole story twice over. It made Hyde Park a company town for scholars, and for decades its lawyers and planners worked the other side of the ledger, deciding who could live around it. The last two stops show how.",
      ],
      lookFor:
        "The Regenstein's rough concrete where the stands once stood, and the bronze marker on Ellis Avenue for the pile. The glass dome next door is the newer library.",
      images: [
        {
          src: `${MEDIA}/stagg-field-1942.jpg`,
          alt: "A drawing of Chicago Pile-1, the graphite reactor stacked under the Stagg Field stands in 1942, with a ladder leaning against it",
          credit:
            "Chicago Pile-1 under the west stands, the only visual record of the first reactor. Drawing by Melvin A. Miller, Argonne National Laboratory. Public domain.",
          label: "1942",
        },
      ],
      nowImage: {
        src: `${MEDIA}/regenstein-today.jpg`,
        alt: "The Regenstein Library today, ribbed concrete towers on the block where Stagg Field stood",
        credit:
          "The Regenstein Library on the old Stagg Field block today. Photograph by Warren LeMay, via Wikimedia Commons. CC BY-SA 2.0.",
        label: "Today",
      },
      toNext: {
        text: "Walk north on Ellis Avenue to 55th Street, then turn right and head east. After Greenwood, low townhouses with small fenced courts line the street. Stop anywhere along that row.",
        distanceMeters: 1050,
        minutes: 13,
      },
      sources: [
        { label: "University of Chicago, the first nuclear reactor explained", url: "https://news.uchicago.edu/explainer/first-nuclear-reactor-explained" },
        { label: "Chicago Maroon, how football found its place at UChicago", url: "https://chicagomaroon.com/39731/grey-city/brains-over-brawn-how-football-found-its-place-at-uchicago/" },
        { label: "University of Chicago, Cobb Lecture Hall", url: "https://architecture.uchicago.edu/locations/cobb_lecture_hall" },
        { label: "History of the University of Chicago, Wikipedia", url: "https://en.wikipedia.org/wiki/History_of_the_University_of_Chicago" },
      ],
    },
    {
      id: "fifty-fifth",
      number: 8,
      title: "Fifty-Fifth Street",
      dek: "When the covenants fell, the speculators arrived",
      mapLabel: "55th Street",
      lat: 41.79495,
      lng: -87.5918,
      audioSrc: `${MEDIA}/audio/stop-08.mp3`,
      audioSeconds: 69,
      transcript: [
        "In 1948 the Supreme Court made racial covenants unenforceable, and Hyde Park's paper wall came down. Black families, boxed for decades into the overcrowded Black Belt beginning a mile west, could finally buy here. What met them was not a welcome. It was a business model.",
        "Speculators worked both sides of the line. They frightened white owners into selling cheap, warning that prices were about to collapse, then resold the same buildings to Black families at close to **double the price, on contract**. Apartments built for one family were carved into kitchenettes, one room and a hot plate. By the mid 1950s this street was crowded, profitable for a few, and falling apart.",
        "Nearly **fifty bars, clubs, and shops** stood along 55th and Lake Park then, including the storefront at 1152 East 55th where the Compass Players opened in 1955 and Second City's founders got their start. Look around. Almost nothing you can see is older than 1961, and the last stop explains why. First, the two red plates here name the machinery that made the whole cycle turn.",
      ],
      lookFor:
        "The 1961 townhouses' little courts, then any older graystone that survived. The gaps in age between buildings are the renewal map, drawn in brick.",
      interrupts: [
        {
          title: "Redlining",
          body: [
            "In 1939 and 1940 a federal agency, the Home Owners' Loan Corporation, graded every Chicago neighborhood for mortgage risk. Green was best, then blue, then yellow, then red. The colors tracked race almost exactly. Most of the Black Belt was drawn red, hazardous. Hyde Park and Kenwood were drawn yellow, definitely declining, in part because Black Chicago lived next door.",
            "The Federal Housing Administration's underwriting manual pointed lenders the same way, favoring covenanted, all-white neighborhoods. Banks followed the maps and the manual, so a Black family with steady income and savings could not get an ordinary mortgage on these blocks. That vacuum is exactly what the contract sellers moved into.",
          ],
        },
        {
          title: "Buying on contract",
          body: [
            "A contract sale worked like rent with none of rent's protections. Researchers at Duke found that 75 to 95 percent of the homes sold to Black families in 1950s and 60s Chicago were sold on contract, at an average markup of 84 percent. A speculator might buy a building for $12,000 and resell it within months for $22,000 or more.",
            "The buyer owned nothing until the final payment. Miss one month and the seller could evict, keep every dollar already paid, and sell the house again on a fresh contract. The same study put the wealth taken from Black Chicago families this way at $3.2 to $4 billion. Payments that steep left nothing for repairs, and the disrepair was then cited as proof that Black neighbors lowered property values.",
          ],
        },
      ],
      images: [
        {
          src: `${MEDIA}/kitchenette-1941.jpg`,
          alt: "A grand corner apartment building in the Black Belt in 1941 with a sign reading Park-Vista Kitchenettes, people and cars on the street below",
          credit:
            "A Black Belt apartment house cut into one-room kitchenettes. Russell Lee, April 1941, Farm Security Administration, Library of Congress. Public domain.",
          label: "1941",
        },
      ],
      nowImage: {
        src: `${MEDIA}/55th-street-today.jpg`,
        alt: "The 1961 urban renewal townhouses on 55th Street today, flat-roofed rows behind small fenced front courts",
        credit:
          "The renewal-era townhouses on 55th Street today. Photograph by Warren LeMay, via Wikimedia Commons. CC BY-SA 4.0.",
        label: "Today",
      },
      toNext: {
        text: "Keep east on 55th Street to Harper Avenue, then turn north. Two blocks up, 53rd Street opens into a plaza with a glass tower above the shops. That is Harper Court.",
        distanceMeters: 790,
        minutes: 10,
      },
      sources: [
        { label: "The Plunder of Black Wealth in Chicago, Duke report, 2019", url: "https://www.fhcci.org/wp-content/uploads/2019/05/Plunder-of-Black-Wealth-Chicago-Report-2019.pdf" },
        { label: "WBEZ, contract buying robbed Black families of billions", url: "https://www.wbez.org/money/2019/05/30/contract-buying-robbed-black-families-in-chicago-of-billions" },
        { label: "Mapping Inequality, the HOLC maps of Chicago", url: "https://dsl.richmond.edu/panorama/redlining/" },
        { label: "Ta-Nehisi Coates, The Case for Reparations", url: "https://www.theatlantic.com/magazine/archive/2014/06/the-case-for-reparations/361631/" },
        { label: "Institute for Housing Studies, following the yellowlined road", url: "https://www.housingstudies.org/news/following-yellowlined-road/" },
      ],
    },
    {
      id: "harper-court",
      number: 9,
      title: "Harper Court",
      dek: "Urban renewal rebuilt the neighborhood, and chose its neighbors again",
      mapLabel: "Harper Court",
      lat: 41.79945,
      lng: -87.58845,
      audioSrc: `${MEDIA}/audio/stop-09.mp3`,
      audioSeconds: 91,
      transcript: [
        "In 1952 the university created the **South East Chicago Commission**, run by a lawyer named Julian Levi, to manage the neighborhood's change. The chancellor put it plainly. The university would buy, control, and rebuild its surroundings, and it spent **29 million dollars** doing it. The tool was urban renewal, and Hyde Park got the first big federally backed program in the country.",
        "Demolition began along 55th and Lake Park in 1955, and the full plan passed City Council in 1958. Before it was over, **638 buildings on 856 acres** came down and about **4,000 families were displaced, most of them Black and poor**. Nearly half the displaced white families found new homes in the neighborhood. Among Black families, roughly one in six did. James Baldwin, watching the same program at work in San Francisco, said urban renewal \"means Negro removal.\"",
        "Harper Court was built in 1965 to rehouse the artisans the bulldozers had scattered. Three displaced businesses actually moved in. Today the university is the biggest landowner in sight, and the storefronts are chains. Your starting stone is a ten-minute walk east down 53rd. On the way, remember that home prices across the Midway have doubled since 2019 with the Obama Center rising, and ask the question this neighborhood has never stopped asking. Who is this place for, and who signs the paperwork that decides?",
      ],
      lookFor:
        "The 2013 tower over Harper Court, then any pre-1960 storefront left on 53rd. Count the national chains against the local names as you walk back east.",
      interrupts: [
        {
          title: "Urban renewal",
          body: [
            "Urban renewal let a city declare blocks blighted, clear them with public money, and hand the land to approved new uses. The Hyde Park-Kenwood plan, approved November 7, 1958, was the nation's first large federally supported renewal scheme, driven by the university's South East Chicago Commission with federal grants behind it.",
            "What it built is all around this corner, the townhouses, the mid-street apartments, the shopping court. What it removed was the housing poor families could afford and nearly fifty bars and shops along 55th alone. Planners called it conservation. The displaced, and Baldwin, had a shorter word for it. The tools changed over this walk, from a code of ethics to a deed clause to a color on a map to a wrecking ball. The incentives never did.",
          ],
        },
      ],
      images: [
        {
          src: `${MEDIA}/hyde-park-aerial-1927.jpg`,
          alt: "A 1927 aerial photograph labeled Hyde Park Hotel District, dense hotel towers along the beach and neighborhood stretching inland",
          credit:
            "The Hyde Park hotel district from the air, 1927, before the covenant fights and the bulldozers. Chicago Aerial Survey, Newberry Library. Public domain.",
          label: "1927",
        },
      ],
      nowImage: {
        src: `${MEDIA}/harper-court-today.jpg`,
        alt: "Harper Court's 53rd Street frontage today in falling snow, chain storefronts under a glass office tower",
        credit:
          "Harper Court's 53rd Street front today. Photograph by TonyTheTiger, 2025, via Wikimedia Commons. CC0.",
        label: "Today",
      },
      sources: [
        { label: "UChicago CEGU, university-led urban renewal", url: "https://cegu.uchicago.edu/2023/11/30/university-led-renewal/" },
        { label: "Hyde Park Herald, Lost Hyde Park's land clearance", url: "https://www.hpherald.com/news/local/lost-hyde-park-land-clearance/article_64703e2e-7240-11ec-b986-ebf650131a4d.html" },
        { label: "Docomomo, the Hyde Park A and B renewal project", url: "https://docomomo-us.org/news/hyde-park-a-b-urban-renewal-project" },
        { label: "James Baldwin in Take This Hammer, 1963", url: "https://scalar.usc.edu/works/housing-inequality/urban-renewalmeans-negro-removal--james-baldwin-1963" },
        { label: "Illinois Answers Project, Woodlawn affordability five years on", url: "https://illinoisanswers.org/2026/05/07/affordability-woodlawn-obama-center-housing-costs/" },
      ],
    },
  ],
};
