import type { WalkTour } from "./walk-types";

// ------------------------------------------------------------------
// The Hyde Park walk. Eleven stops on how the neighborhood was built
// and who it was built for, from Paul Cornell's stone at 53rd Street
// through the fair, the university, and the machinery of exclusion,
// closing the circle at the Obama Presidential Center. The narration
// is written from the founder's family oral history (a recorded
// conversation outlining the tour), corrected and deepened against
// the sources listed on every stop; nothing in the transcript should
// outrun them. The five red plates are page-only and are not read
// into the audio. Audio is generated by scripts/walk-tts.mjs --tour
// hyde-park (OpenAI, voice ash); durations.json is the source of
// audioSeconds.
// ------------------------------------------------------------------

const MEDIA = "/media/hyde-park-walk";

export const HYDE_PARK_WALK: WalkTour = {
  title: "Walk Hyde Park",
  dek: "A free self-guided audio tour from Paul Cornell's stone to the Obama Presidential Center. Eleven stops, about five miles. Hyde Park sold exclusivity from its first day, and a century of paperwork decided who got to live in it.",
  walkMinutes: 102,
  listenMinutes: 28,
  distanceMiles: 4.9,
  startLabel: "Paul Cornell's stone, Harold Washington Park",
  practical: [
    {
      title: "Getting there and timing",
      text: "The walk starts in Harold Washington Park at 53rd Street, across from the Hampton House at 5300 South Shore Drive, and ends at the Obama Presidential Center. The 53rd Street Metra stop is a few blocks from the start, and the 6 and 28 buses run nearby. Plan on about three hours with the stops. Short on time? End at Harper Court and save the last leg for another day. For lunch after, Valois on 53rd serves cafeteria breakfast all day and the Medici on 57th has fed students for decades.",
    },
    {
      title: "The ground",
      text: "Flat city sidewalks the whole way, just under five miles. The busiest crossings are on 57th Street, along Lake Park Avenue, and at Stony Island; use the marked crosswalks. The university quadrangles are open to walk through every day. Going inside Robie House takes a timed ticket, but this tour only needs the outside.",
    },
    {
      title: "Listening",
      text: "Headphones are nicest, but a phone speaker works fine. Every stop's audio is also printed on the page, so you can read instead of listen. If you share your location, it is used only to draw your dot on the map. It never leaves your phone.",
    },
  ],
  route: [
    [41.7996, -87.5812],
    [41.7992, -87.5824],
    [41.799, -87.5833],
    [41.7992, -87.5852],
    [41.79946, -87.58734],
    [41.7976, -87.5875],
    [41.7957, -87.5877],
    [41.7938, -87.5878],
    [41.792, -87.5879],
    [41.7912, -87.5872],
    [41.7911, -87.585],
    [41.791, -87.5831],
    [41.7912, -87.586],
    [41.7913, -87.5885],
    [41.7914, -87.5921],
    [41.7916, -87.5945],
    [41.7917, -87.5962],
    [41.7907, -87.5961],
    [41.78985, -87.59585],
    [41.7887, -87.5964],
    [41.78855, -87.5966],
    [41.7888, -87.5978],
    [41.789, -87.598],
    [41.7889, -87.5992],
    [41.78875, -87.60035],
    [41.7897, -87.6003],
    [41.7907, -87.6002],
    [41.7913, -87.5999],
    [41.79225, -87.5999],
    [41.7931, -87.6008],
    [41.794, -87.6006],
    [41.7947, -87.599],
    [41.7948, -87.5962],
    [41.7949, -87.5935],
    [41.79495, -87.5918],
    [41.7951, -87.59],
    [41.7952, -87.5884],
    [41.7963, -87.5884],
    [41.7981, -87.5885],
    [41.79945, -87.58845],
    [41.7957, -87.5884],
    [41.7956, -87.5875],
    [41.7938, -87.5877],
    [41.792, -87.5878],
    [41.7913, -87.5869],
    [41.7894, -87.5868],
    [41.7876, -87.5867],
    [41.786, -87.5862],
    [41.7859, -87.5857],
  ],
  stops: [
    {
      id: "cornells-stone",
      number: 1,
      title: "Paul Cornell's stone",
      dek: "A boulder in the grass marks where the whole neighborhood started",
      mapLabel: "Cornell's stone",
      lat: 41.7996,
      lng: -87.5812,
      audioSrc: `${MEDIA}/audio/stop-01.mp3`,
      audioSeconds: 183,
      transcript: [
        "Find the boulder in Harold Washington Park near 53rd Street, across from the tall brick building with the red awning. That building matters in a few minutes. The stone marks roughly where Hyde Park began, and before the story starts, take one slow look around. The towers, the park, the trains behind the trees. All of it traces back to a single land deal.",
        "Paul Cornell was a young lawyer from upstate New York who reached Chicago in 1847 and had his savings stolen his very first night in town. He rebuilt from nothing, and along the way he met Stephen Douglas, the Illinois senator, who gave him a piece of advice. Invest south of the city, because that is where Chicago is going to grow. So one day Cornell got on a horse and rode down the lake shore, through marsh grass and sand ridges, until he reached a small farm and tavern near what is now 53rd Street, a stopping place for travelers making the last push into the city.",
        "In August 1853 he bought **sixty acres from Electa Watson**, the tavern keeper's widow, and he kept buying until he held about **300 acres of lakefront** between roughly 51st and 55th. Then he gave it a name that promised gentility. Hyde Park. Chicago at the time pumped its sewage into the river and the lake and smelled like it. What Cornell was selling was escape, clean air and cool water for families rich enough to leave the city behind.",
        "The whole plan depended on getting those families here, so in 1856 Cornell handed the Illinois Central sixty acres of his land for free. In exchange the railroad built him a **station at 53rd Street and guaranteed daily trains downtown**, six a day as the deal is remembered. More stops followed at 47th and 57th. He cut the land into large lots and kept the pace deliberately rural. Early buyers kept gardens, stables, even a few animals.",
        "Right here on the shore he raised the resort's centerpiece, the **Hyde Park House**, a four-story hotel with the water at its porch and the trains at its back. It hosted concerts, parties, and political dinners, and Mary Todd Lincoln stayed there for a summer after her husband was killed. After it burned in the 1870s, this ground eventually got the Sisson Hotel, the brick tower in front of you, known today as the Hampton House. Find an old postcard and it is the same building on the same corner, with the waterfront running nearly to its door.",
        "So notice what this stone actually marks. Not a wilderness tamed, but a product launched. From the first sale, Hyde Park was designed to choose its neighbors. The rest of this walk is about how far that idea traveled, and what it cost the people on the wrong side of it.",
      ],
      images: [
        {
          src: `${MEDIA}/sisson-1920s.jpg`,
          alt: "The Sisson Hotel rising over the Hyde Park lakefront around 1920, with sailboats on the water in front of it",
          credit:
            "The Sisson Hotel on the old Hyde Park House grounds, around 1920. From Early Chicago Hotels. Public domain, via Wikimedia Commons.",
          label: "c. 1920",
        },
      ],
      nowImage: {
        src: `${MEDIA}/hampton-house-today.jpg`,
        alt: "The Hampton House today, a red brick tower with a red entrance awning behind park trees",
        credit:
          "The same building today, the Hampton House. Photograph by TonyTheTiger, 2006, via Wikimedia Commons. CC BY-SA 3.0.",
        label: "Today",
      },
      toNext: {
        text: "Walk to the corner of 53rd Street and Hyde Park Boulevard, one short block in from the lake. The tall hotel building on the corner, with carved faces in its terra cotta, is the Del Prado.",
        distanceMeters: 200,
        minutes: 3,
      },
      sources: [
        { label: "Hyde Park Historical Society, Paul Cornell", url: "https://www.hydeparkhistory.org/paul-cornell" },
        { label: "Hyde Park Herald, Hyde Park Stories on Paul Cornell", url: "https://www.hpherald.com/evening_digest/hyde-park-stories-paul-cornell/article_18568fa6-4ca5-4dfc-8d36-d90aa574ceda.html" },
        { label: "Hyde Park Historical Society, Harold Washington Park", url: "https://www.hydeparkhistory.org/blog/hyde-park-stories-harold-washington-park" },
        { label: "Hyde Park House, Wikipedia", url: "https://en.wikipedia.org/wiki/Hyde_Park_House" },
        { label: "Hampton House, Wikipedia", url: "https://en.wikipedia.org/wiki/Hampton_House_(Chicago)" },
      ],
    },
    {
      id: "del-prado",
      number: 2,
      title: "The Del Prado",
      dek: "The last of the grand resort hotels still stands on its corner",
      mapLabel: "Del Prado",
      lat: 41.799,
      lng: -87.5833,
      audioSrc: `${MEDIA}/audio/stop-02.mp3`,
      audioSeconds: 126,
      transcript: [
        "The apartment tower on this corner opened in 1918 as the **Cooper-Carlton Hotel**. Look up and you can see carved faces in the terra cotta near the top, put there by owners who claimed a family line back to the novelist James Fenimore Cooper. In 1930 it took the name **Del Prado**, inherited from an older hotel out on the Midway that was being torn down to make room for International House.",
        "Hyde Park in those decades ran as a resort, and this corner was its front porch. Families checked in for the whole summer. They took big suites, sometimes a whole floor. The men rode Cornell's trains downtown to their offices every morning, and everyone else had the day. The beach, the parks, sailing off the Point, restaurants, concerts in the hotel ballrooms. Remember that this was the time before air travel. When people wanted to get away, they traveled close to home, and the railroads sold the getaway hard.",
        "That sales pitch reached a long way. The Illinois Central's main line does not stop downtown. Follow it the other direction and it runs through the whole length of Mississippi, and its ads told families across the Midwest and the South to come spend the summer by the lake in Chicago. The train was the only fast way anywhere, and Hyde Park sat right on it.",
        "The building is apartments now, restored inside. If the door staff will let you, step into the lobby and look at the ceilings, or just study the arches from the sidewalk and picture check-in day in July. Trunks stacked on the curb, porters hauling a season's worth of luggage, a band playing somewhere upstairs.",
        "Before you walk on, hold one detail. The families on this porch were white. So were the names on every deed along the boulevards. The people hauling the trunks and cooking the meals often were not, and Hyde Park's own small Black community lived two blocks west, pressed against the railroad embankment. That street is the next stop.",
      ],
      images: [
        {
          src: `${MEDIA}/del-prado-1900s.jpg`,
          alt: "A linen postcard of the Del Prado Hotel by the lake at Hyde Park Boulevard and 53rd Street, with sailboats on the water beyond",
          credit:
            "The Del Prado as a hotel, from a linen postcard calling it the finest residential hotel in the Middle West. Newberry Library collection. Public domain, via Wikimedia Commons.",
          label: "1930s",
        },
      ],
      nowImage: {
        src: `${MEDIA}/del-prado-today.jpg`,
        alt: "The Del Prado building today at 53rd and Hyde Park Boulevard, red brick with white terra cotta trim",
        credit:
          "The Del Prado today, apartments now. Photograph by TonyTheTiger, 2008, via Wikimedia Commons. CC BY-SA 3.0.",
        label: "Today",
      },
      toNext: {
        text: "Walk west on 53rd Street toward the railroad embankment. Stop at Lake Park Avenue where you can see the station stairs and the tracks running above the street.",
        distanceMeters: 350,
        minutes: 5,
      },
      sources: [
        { label: "Hotel Del Prado, Wikipedia", url: "https://en.wikipedia.org/wiki/Hotel_Del_Prado" },
        { label: "Julia Bachrach, Chicago's apartment hotels of the 1910s", url: "https://www.jbachrach.com/blog/2019/11/26/chicagos-apartment-hotels-of-the-1910s" },
        { label: "International House, exploring our history", url: "https://ihouse.uchicago.edu/90th-anniversary/90th-anniversary-explore-our-history/" },
      ],
    },
    {
      id: "lake-park-tracks",
      number: 3,
      title: "The tracks and Lake Park",
      dek: "The railroad that built the resort ran both directions",
      mapLabel: "53rd St tracks",
      lat: 41.79946,
      lng: -87.58734,
      audioSrc: `${MEDIA}/audio/stop-03.mp3`,
      audioSeconds: 147,
      transcript: [
        "These tracks are why everything else on this walk exists. Cornell's deal put a station at 53rd Street in 1856, and suburban trains have stopped here ever since, a hundred and seventy years without a break. The Illinois Central electrified the line in 1926, and Metra runs the same embankment today. We tend to picture this railroad as a shuttle between Hyde Park and downtown. It never was. The main line keeps going south, through the small towns of Mississippi, all the way to New Orleans.",
        "During the **Great Migration** that geography changed America. Black southerners rode the Illinois Central north in two great waves, the first around the World Wars, the second after, hundreds of thousands of people moving toward factory jobs and away from the terror of the South. Many stepped off IC trains within a few miles of where you are standing. They built this city's industry with their hands. And nearly every neighborhood in the city, this one very much included, refused to let them live in it.",
        "Which brings us to the street you are on. Lake Park Avenue was the working back of Cornell's stage set. While the boulevards behind you got the hotels and the lake views, this strip under the embankment got the coal yards, the taverns, the liveries, and the cheap frame buildings, the unglamorous machinery that kept a resort running.",
        "It is also where Hyde Park put its Black neighbors. In the early 1900s a small **middle-class Black community lived along Lake Park and Harper avenues**, close against the tracks. They organized social clubs, and in 1914 the neighborhood's Half Century Club held a reception at the Rosalie Music Hall for Booker T. Washington, the most famous Black man in America. Meanwhile the rest of Hyde Park stayed almost entirely white, and worked to keep itself that way.",
        "Stand here a second and read the pattern, because it repeats all afternoon. The front door on the boulevards, the Black community beside the tracks. Geography doing the work of policy, decades before the policy got written down. When we reach the university and 55th Street, you will watch it get written down.",
      ],
      images: [
        {
          src: `${MEDIA}/ic-electric-1967.jpg`,
          alt: "An Illinois Central Electric commuter train pulling into a wooden platform station in 1967",
          credit:
            "An Illinois Central Electric train at the 63rd Street station, 1967. Photograph by Lawrence and David Barera, via Wikimedia Commons. CC BY-SA 2.0.",
          label: "1967",
        },
      ],
      nowImage: {
        src: `${MEDIA}/metra-53rd-today.jpg`,
        alt: "A Metra Electric train approaching the 53rd Street station platforms on the Hyde Park embankment today",
        credit:
          "A train coming into the 53rd Street station today. Photograph by David Wilson, 2013, via Wikimedia Commons. CC BY 2.0.",
        label: "Today",
      },
      toNext: {
        text: "Follow Lake Park Avenue south beside the embankment, all the way to 57th Street. Cross toward the park and walk to the north face of the huge domed museum, by the water.",
        distanceMeters: 1300,
        minutes: 16,
      },
      sources: [
        { label: "51st/53rd Street Hyde Park station, Wikipedia", url: "https://en.wikipedia.org/wiki/51st/53rd_Street/Hyde_Park_station" },
        { label: "Cook County African American Heritage Trail, the railroad", url: "https://ccafricanamericanheritage.org/trail-stop/railroad/" },
        { label: "Hyde Park Herald, the Villas survive (the Half Century Club)", url: "https://www.hpherald.com/evening_digest/hyde-park-stories-the-villas-survive/article_1d5c91c8-bbf2-11ef-aa3d-d36c34ffc52c.html" },
        { label: "Hyde Park Herald, Lost Hyde Park's commercial core", url: "https://www.hpherald.com/news/local/lost-hyde-park-the-commercial-core/article_d282cc80-14ba-11ec-b846-f786cbbb9339.html" },
      ],
    },
    {
      id: "white-city",
      number: 4,
      title: "The White City",
      dek: "The fair that made Hyde Park famous also drew its hardest line",
      mapLabel: "White City",
      lat: 41.791,
      lng: -87.5831,
      audioSrc: `${MEDIA}/audio/stop-04.mp3`,
      audioSeconds: 177,
      transcript: [
        "The building across the water is the Museum of Science and Industry, and it is the last of the great palaces of the **1893 World's Columbian Exposition** still standing where the fair put it. Cornell had pushed for grand parks here for decades. Frederick Law Olmsted, the designer of Central Park, drew plans for this ground back in 1871, when it was still marsh you could barely cross without soaking your boots. But the money to build his vision only arrived when Chicago won the World's Fair.",
        "Put the fair in scale. The last great exposition, in Paris, had produced the Eiffel Tower. Chicago, barely twenty years past its Great Fire, wanted to answer it. Daniel Burnham directed an army of architects who threw up a city of palaces in about two years. They look like carved stone in the photographs. They were mostly **steel frames skinned in plaster**, and the cheapest way to make them match was to paint everything white. The White City. At night it was lit with electricity on a scale almost nobody had seen, and the crowds came as much for the glow as for the exhibits.",
        "It ran six months and drew some **27 million visits, in a country of 65 million people**. Visitors met the dishwasher, the zipper, Juicy Fruit gum, and a wheel built by a bridge engineer named Ferris. The fair also planted a lie that would outlive it. A food company hired **Nancy Green, a Chicago woman born into slavery in Kentucky**, to flip pancakes in costume as Aunt Jemima, a smiling plantation cook invented to sell flour. The image charmed the crowds and sold the Old South as a warm memory, at the exact moment the fair was doing something colder.",
        "Because Black Americans were shut out of this fair. Shut out of its planning, its exhibit halls, and nearly all of its jobs. **Ida B. Wells and Frederick Douglass** answered from the gates with a pamphlet, The Reason Why the Colored American Is Not in the World's Columbian Exposition, printed with prefaces in English, French, and German so any visitor on earth could read it. Wells counted the copies she handed out in the thousands. Douglass, then in his seventies, worked from the Haiti Pavilion, the one building where Black excellence was on display, because Haiti, not America, had made him its commissioner.",
        "The fair's answer was a single Colored American Day near the end of the season. Douglass gave the speech of the summer anyway. Keep the pamphlet's title with you as you walk, because the rest of this tour watches the same exclusion move from the fairgrounds into deeds, maps, and city plans. The fair made Hyde Park famous, filled it with hotels and workers, and handed the young neighborhood its central question. Who is all this actually for?",
      ],
      images: [
        {
          src: `${MEDIA}/palace-fine-arts-1893.jpg`,
          alt: "The domed Palace of Fine Arts reflected in the North Pond during the 1893 World's Fair",
          credit:
            "The Palace of Fine Arts, 1893, today's Museum of Science and Industry. C. D. Arnold, Official Views of the World's Columbian Exposition. Public domain, via Wikimedia Commons.",
          label: "1893",
        },
        {
          src: `${MEDIA}/court-night-1893.jpg`,
          alt: "The Grand Court of the 1893 fair at night, its domes and fountains outlined in electric light before a crowd",
          credit:
            "The Grand Court lit at night, drawn by Charles Graham, 1893. Library of Congress Prints and Photographs Division. Public domain.",
        },
      ],
      nowImage: {
        src: `${MEDIA}/columbia-basin-today.jpg`,
        alt: "The Museum of Science and Industry today, seen straight on across the still water of the Columbia Basin",
        credit:
          "The same building today, across the Columbia Basin. Photograph by Warren LeMay, 2024, via Wikimedia Commons. CC BY-SA 2.0.",
        label: "Today",
      },
      toNext: {
        text: "Walk west on 57th Street, away from the lake. Cross Stony Island at the light and keep going on 57th, past the bookstores, to Woodlawn Avenue. Turn left one block. The long brick house with the flying roof is on the corner at 58th.",
        distanceMeters: 1220,
        minutes: 16,
      },
      sources: [
        { label: "World's Columbian Exposition, Wikipedia", url: "https://en.wikipedia.org/wiki/World%27s_Columbian_Exposition" },
        { label: "The Reason Why the Colored American Is Not in the World's Columbian Exposition, full text", url: "https://digital.library.upenn.edu/women/wells/exposition/exposition.html" },
        { label: "Chicago Park District, Jackson Park history", url: "https://www.chicagoparkdistrict.com/parks-facilities/jackson-andrew-park" },
        { label: "Nancy Green, Wikipedia", url: "https://en.wikipedia.org/wiki/Nancy_Green" },
      ],
    },
    {
      id: "robie-house",
      number: 5,
      title: "The Robie House",
      dek: "What the professors' quarter built when money was no object",
      mapLabel: "Robie House",
      lat: 41.78985,
      lng: -87.59585,
      audioSrc: `${MEDIA}/audio/stop-05.mp3`,
      audioSeconds: 131,
      transcript: [
        "Frederick Robie made bicycle parts. He ran his father's supply company, he was twenty-eight, and in 1908 he went to **Frank Lloyd Wright** with an engineer's brief. No boxy rooms, no drafts, and he wanted to see his neighbors without his neighbors seeing him. By 1910 he had this. Long Roman brick, roofs that hang far past their walls, a house that seems to be gliding while standing still. Wright called the style Prairie. Plenty of the neighbors just called it strange.",
        "For this walk, though, the house is really about money, and about the street it sits on. When the university opened in 1892, the blocks around it filled with big houses for professors, deans, and executives. Woodlawn Avenue became a showcase. Walk a block in either direction after this stop and look at the porches and the stonework. Hiring the most radical architect in America was simply what this street could afford, and it is exactly the class of resident Paul Cornell had imagined from the beginning.",
        "The house itself was nearly lost twice. The seminary next door tried to demolish it for a dormitory in 1941 and again in 1957, and the second time **Wright himself, ninety years old, came back to stand in front of it** and shame them out of it. A developer bought the house to save it, the university eventually took it over, and today it is a World Heritage Site, one of the most studied buildings in America.",
        "Now hold the two halves of this block in your head at once, because this is the turn in the whole story. Money confident enough to build this house was also confident enough to write rules about who could never own one. By 1908, the same year Robie hired Wright, Hyde Park had an improvement club whose stated purpose was keeping Black families out, blacklisting agents who sold across the line and boycotting merchants who served Black customers. And within a generation, the real estate profession had made that practice official ethics. The red plate below is the rulebook itself.",
      ],
      interrupts: [
        {
          title: "The Chicago Real Estate Board",
          body: [
            "In 1917 the Chicago Real Estate Board adopted a policy of block-by-block segregation, confining Black residents to blocks that already had Black neighbors. In 1924 the national realtors' association wrote the idea into its code of ethics. Article 34 read, \"A Realtor should never be instrumental in introducing into a neighborhood a character of property or occupancy, members of any race or nationality, or any individuals whose presence will clearly be detrimental to property values in that neighborhood.\"",
            "An agent who broke the rule could be expelled from the board, which could end a career. Selling a house to a Black family in a white neighborhood was, by the profession's own written standard, an ethics violation. The race language stayed in the code until 1950.",
          ],
        },
      ],
      images: [
        {
          src: `${MEDIA}/robie-1911.jpg`,
          alt: "The Robie House shortly after completion, from a 1911 architectural print",
          credit:
            "The Robie House new, from the 1911 Wasmuth portfolio. Historic American Buildings Survey. Public domain, via Wikimedia Commons.",
          label: "1911",
        },
      ],
      nowImage: {
        src: `${MEDIA}/robie-today.jpg`,
        alt: "The Robie House today, long Roman brick walls and cantilevered roofs in autumn light",
        credit:
          "The house today, run by the Frank Lloyd Wright Trust. Photograph by Warren LeMay, 2023, via Wikimedia Commons. CC BY-SA 2.0.",
        label: "Today",
      },
      toNext: {
        text: "Continue south on Woodlawn Avenue one block to 59th Street. Cross to the edge of the long sunken green. That strip is the Midway Plaisance.",
        distanceMeters: 300,
        minutes: 4,
      },
      sources: [
        { label: "Frank Lloyd Wright Trust, Robie House", url: "https://flwright.org/explore/frederick-c-robie-house" },
        { label: "Robie House, Wikipedia", url: "https://en.wikipedia.org/wiki/Robie_House" },
        { label: "NAREB Code of Ethics, 1924 (Article 34)", url: "https://www.nar.realtor/sites/default/files/documents/COE1924.pdf" },
        { label: "Inman, when the Realtor code required discrimination", url: "https://www.inman.com/2014/04/17/realtor-code-of-ethics-once-required-discrimination/" },
        { label: "Preservation Chicago, Woodlawn Avenue", url: "https://www.preservationchicago.org/woodlawn-avenue/" },
      ],
    },
    {
      id: "midway-line",
      number: 6,
      title: "The Midway line",
      dek: "A canal that never came, and a border that did",
      mapLabel: "The Midway",
      lat: 41.78855,
      lng: -87.5966,
      audioSrc: `${MEDIA}/audio/stop-06.mp3`,
      audioSeconds: 154,
      transcript: [
        "This mile of green was the fair's pleasure strip. The White City behind you was the exhibition, dignified and ticketed. Out here was the fun. Beer gardens, bands, sideshows, restaurants from a dozen countries, and rising over the middle of it the first **Ferris wheel**, 264 feet tall, America's answer to the Eiffel Tower. Fifty cents bought two slow revolutions, about twenty minutes in the air. The shows out here took in millions, and every carnival midway in America has been named for this lawn ever since.",
        "It had a darker draw too. The Midway's so-called villages put human beings on display, people brought from Africa, Asia, the Middle East, and the Americas, presented under the banner of anthropology for paying crowds who stared at them like exhibits. That happened here, on this grass, and the fair sold tickets to it all summer.",
        "Now look at the ground itself. The lawn sits sunken below the streets because **Olmsted planned a canal here**, a waterway linking the Jackson Park lagoons behind you to Washington Park a mile west, so you could move through the whole South Side park system by boat. Crews started digging, the money ran out, and the water never came. The ditch stayed a lawn.",
        "But the empty channel found another job. **The Midway became a border.** North of this grass, the university and white Hyde Park. South of it, Woodlawn. And when the Great Migration filled the Black Belt to bursting, that narrow strip of housing along State Street, now flanked by the Dan Ryan, families started looking for rooms anywhere they could find them. The blocks south of the Midway were the pressure line. For most of a century, which side of this lawn you lived on decided your mortgage, your rent, and what the city thought your block was worth. Cross it today and you can still feel the seam.",
        "The neighborhood's answer to that pressure was paper. A mile southwest of here, in 1937, a family named **Hansberry** bought a brick three-flat across one of those paper lines, and a mob gathered outside their window the first evening. Their daughter Lorraine grew up to put that year on Broadway as A Raisin in the Sun, the first play by a Black woman ever produced there. The red plate below explains the paperwork behind the mob.",
      ],
      interrupts: [
        {
          title: "Restrictive covenants",
          body: [
            "A covenant is a promise written into a property deed. Chicago's version barred an owner from ever selling or renting to a Black person. In 1927 the Chicago Real Estate Board circulated a model covenant, drafted by the national association's counsel Nathan William MacChesney, and pushed it block by block through churches, clubs, and property owners' associations. More than 220 Cook County subdivisions adopted its language, and people at the time claimed covenants covered as much as three-quarters of the city's residential property.",
            "Hyde Park signed up with enthusiasm. In 1928 the Hyde Park Herald praised the covenants ringing the neighborhood as \"a marvelous delicately woven chain of armor.\" The University of Chicago spent $83,597 defending covenants in court. When Carl Hansberry bought at 6140 South Rhodes anyway, a chunk of concrete thrown through the window nearly hit seven-year-old Lorraine. The Supreme Court let the family stay in 1940 on a technicality, and in 1948 it made every racial covenant unenforceable. Nobody erased them. The words still sit on Cook County deeds today.",
          ],
        },
      ],
      images: [
        {
          src: `${MEDIA}/midway-1893.jpg`,
          alt: "The Midway Plaisance in 1893, crowded with visitors between the attractions, minarets and the Moorish Palace sign overhead",
          credit:
            "The Midway mid-fair, 1893, seen from the Ferris wheel. Public domain, via Wikimedia Commons.",
          label: "1893",
        },
      ],
      nowImage: {
        src: `${MEDIA}/midway-today.jpg`,
        alt: "The Midway Plaisance today, a long open sunken lawn lined with trees, with University of Chicago towers in the distance",
        credit:
          "The same ground today, a mile of open green. Photograph by Joe Passe, 2021, via Wikimedia Commons. CC BY-SA 2.0.",
        label: "Today",
      },
      toNext: {
        text: "Walk north into campus on University Avenue, then turn in through the stone gateways into the main quadrangle. Notice how small and few the old entrances are. Cross the quad toward its west side and stop in front of the long Gothic building with the pointed arch entrance, Cobb Hall.",
        distanceMeters: 600,
        minutes: 8,
      },
      sources: [
        { label: "Midway Plaisance, Wikipedia", url: "https://en.wikipedia.org/wiki/Midway_Plaisance" },
        { label: "WTTW, how Chicago invented modern segregation", url: "https://www.wttw.com/firsthand/segregation/how-did-chicago-become-so-segregated-by-inventing-modern-segregation" },
        { label: "WBEZ, Chicago home records still contain racist covenants", url: "https://www.wbez.org/race-class-communities/2021/11/21/chicago-home-records-still-contain-racist-covenants" },
        { label: "Chicago History Today, the Hansberrys move in, June 15, 1937", url: "https://chicagohistorytoday.wordpress.com/2014/06/15/restrictive-covenant-6-15-1937/" },
        { label: "Chicago Public Library, Lorraine Hansberry biography", url: "https://www.chipublib.org/lorraine-hansberry-biography/" },
      ],
    },
    {
      id: "cobb-hall",
      number: 7,
      title: "Cobb Hall and the quad",
      dek: "A brand new university dressed up to look five hundred years old",
      mapLabel: "Cobb Hall",
      lat: 41.78875,
      lng: -87.60035,
      audioSrc: `${MEDIA}/audio/stop-07.mp3`,
      audioSeconds: 166,
      transcript: [
        "The building in front of you, with the pointed arch over its doors, is **Cobb Hall, the university's first building**. Classes started inside it on October 1, 1892, with 594 students, while the fair's palaces were still going up a mile east. It was paid for by Silas Cobb, a Chicago harness maker who had arrived nearly penniless sixty years earlier, and designed by an architect named Henry Ives Cobb. No relation. The university simply had that kind of luck with names.",
        "This is actually Chicago's second University of Chicago. The first was a Baptist school founded in the 1850s a few miles north, at 35th and Cottage Grove, on ten acres donated by Senator Stephen Douglas. The same Douglas who tipped off Paul Cornell, and a man whose fortune ran partly on a Mississippi plantation worked by enslaved people. That first school went bankrupt in 1886. When the Baptists set out to build a successor, they aimed much higher. **John D. Rockefeller pledged $600,000**, on the condition that others raise $400,000 more, and Marshall Field, the department store king, donated the first ten acres of land right here. Rockefeller's gifts eventually passed $35 million, and a seminary project became one of the richest universities on earth.",
        "Now look hard at the architecture, because the architecture is a confession. Everything around you was brand new in the 1890s, but the trustees ordered **English Gothic, modeled on Oxford and Cambridge**, precisely so the campus would look like it had stood for five centuries. They planted ivy at the feet of the walls to hurry the illusion along. A new school in a new city bought itself instant ancestry.",
        "And notice how the quadrangle holds you. The buildings form a wall around this lawn, and the ways in are few and narrow. The early quads read as a cloister, the city held at arm's length, and for much of the last century the neighbors to the south and west understood the message perfectly. Today anyone can walk through, and you just did. But the instinct to control its surroundings never left this institution, and you will see the proof at 55th Street.",
        "One more thing before you move on. To make its name fast, the young university bet on football. It was a founding member of the conference that became the Big Ten, and its coach, Amos Alonzo Stagg, was the first in America hired with faculty rank. The team practiced on the Midway you just left. The stadium, and what happened underneath it, is the next stop.",
      ],
      images: [
        {
          src: `${MEDIA}/cobb-hall-1900s.jpg`,
          alt: "A linen postcard of ivy-covered Cobb Hall at the University of Chicago",
          credit:
            "Cobb Hall under its ivy, from a linen postcard, around the 1930s. Tichnor Brothers collection. Public domain, via Wikimedia Commons.",
          label: "c. 1935",
        },
      ],
      nowImage: {
        src: `${MEDIA}/cobb-hall-today.jpg`,
        alt: "Cobb Hall today, gray Gothic stone with red roofs, seen across the main quadrangle lawn",
        credit:
          "Cobb Hall today, still holding classes. Photograph by Warren LeMay, via Wikimedia Commons. CC BY-SA 2.0.",
        label: "Today",
      },
      toNext: {
        text: "Leave the quad on its north side, through the gate onto 57th Street. Turn left, and at Ellis Avenue stop by the big ribbed concrete library on the corner.",
        distanceMeters: 350,
        minutes: 5,
      },
      sources: [
        { label: "University of Chicago, Cobb Lecture Hall", url: "https://architecture.uchicago.edu/locations/cobb_lecture_hall" },
        { label: "University of Chicago, the main quadrangle", url: "https://architecture.uchicago.edu/locations/main_quadrangle" },
        { label: "UChicago Library, the Old University of Chicago", url: "https://www.lib.uchicago.edu/e/scrc/findingaids/view.php?eadid=ICU.SPCL.OLDUOFC" },
        { label: "History of the University of Chicago, Wikipedia", url: "https://en.wikipedia.org/wiki/History_of_the_University_of_Chicago" },
      ],
    },
    {
      id: "stagg-field",
      number: 8,
      title: "Stagg Field and the pile",
      dek: "Football crowds, then the atomic age, on one city block",
      mapLabel: "Stagg Field",
      lat: 41.79225,
      lng: -87.5999,
      audioSrc: `${MEDIA}/audio/stop-08.mp3`,
      audioSeconds: 134,
      transcript: [
        "The concrete library filling this block is the Regenstein, and under your feet is one of the strangest double histories in America. This was **Stagg Field**. The old stadium looked like a castle, notched stone walls and towers, and on big fall Saturdays crowds pressing fifty thousand poured off the trains and into these streets to watch the Maroons, one of the first powers of college football. The 1905 team went unbeaten and outscored its opponents 271 to 5. Football fame is what first made this university a household name.",
        "Then the university fired its own myth. **Robert Maynard Hutchins**, the young president who arrived in 1929, thought big-time sports had no business at a serious university, and in December 1939 he abolished varsity football outright. Chicago walked out of the Big Ten a few years later. Alumni howled and enrollment sagged, and Hutchins built a different identity instead, the great-books Core that still shapes every undergraduate here.",
        "The abandoned stadium then got the twentieth century's most consequential second act. In 1942 the Manhattan Project needed somewhere discreet for an experiment too dangerous to risk in a crowded lab. They chose a **squash court under the west stands of the empty stadium**. On the afternoon of December 2, 1942, Enrico Fermi's team slid the control rods out of a pile of graphite and uranium and ran the **first self-sustaining nuclear chain reaction in history**, for four and a half minutes, in secret, in a residential neighborhood of a city of three and a half million people. Even the mayor was never told.",
        "The stands came down after the war. The Regenstein rose on the footprint in 1970, the glass dome next door followed, and on Ellis Avenue a dark bronze sculpture by Henry Moore marks the exact spot of the pile. Physics made this university's name global. But while its scientists were remaking the world, its lawyers and planners were remaking the neighborhood, and that story picks back up two blocks north on 55th Street.",
      ],
      images: [
        {
          src: `${MEDIA}/stagg-field-1942.jpg`,
          alt: "A drawing of Chicago Pile-1, the graphite reactor stacked under the Stagg Field stands in 1942, with a ladder leaning against it",
          credit:
            "Chicago Pile-1 under the west stands, the only visual record of the first reactor. Drawing by Melvin A. Miller, Argonne National Laboratory. Public domain.",
          label: "1942",
        },
      ],
      nowImage: {
        src: `${MEDIA}/regenstein-today.jpg`,
        alt: "The Regenstein Library today, ribbed concrete towers on the block where Stagg Field stood",
        credit:
          "The Regenstein Library on the old Stagg Field block today. Photograph by Warren LeMay, via Wikimedia Commons. CC BY-SA 2.0.",
        label: "Today",
      },
      toNext: {
        text: "Walk north on Ellis Avenue to 55th Street, then turn right and head east. After Greenwood, low townhouses with small fenced courts line the street. Stop anywhere along that row.",
        distanceMeters: 1050,
        minutes: 13,
      },
      sources: [
        { label: "University of Chicago, the first nuclear reactor explained", url: "https://news.uchicago.edu/explainer/first-nuclear-reactor-explained" },
        { label: "Chicago Maroon, how football found its place at UChicago", url: "https://chicagomaroon.com/39731/grey-city/brains-over-brawn-how-football-found-its-place-at-uchicago/" },
        { label: "1905 Chicago Maroons football team, Wikipedia", url: "https://en.wikipedia.org/wiki/1905_Chicago_Maroons_football_team" },
        { label: "Atomic Archive, the first pile", url: "https://www.atomicarchive.com/history/first-pile/firstpile_01.html" },
      ],
    },
    {
      id: "fifty-fifth",
      number: 9,
      title: "Fifty-Fifth Street",
      dek: "When the covenants fell, the speculators arrived",
      mapLabel: "55th Street",
      lat: 41.79495,
      lng: -87.5918,
      audioSrc: `${MEDIA}/audio/stop-09.mp3`,
      audioSeconds: 129,
      transcript: [
        "In 1948 the Supreme Court made racial covenants unenforceable, and Hyde Park's paper wall came down. After decades boxed inside the overcrowded Black Belt, Black families could finally buy on blocks like this one. What met them was not a welcome. It was a business model, and it worked both sides of the street.",
        "Here is the play. A speculator sells one building on an all-white block to a Black family. Then he knocks on every white door on the block with a warning. Your house is worth ten thousand dollars today, but the neighborhood is finished, and next year it might bring seven. Frightened owners sold cheap. The speculator then resold the very same buildings to Black buyers at nearly **double the price, on contract**, because no bank would write them a mortgage. The white seller lost, the Black buyer paid brutally, and the man in the middle kept the difference. They called it **blockbusting**, and it turned over block after block on the South Side in a few short years.",
        "The overcrowding was part of the machine too. Buildings that started as fair-era hotels and one-family flats were carved into **kitchenettes**, single rooms with a hot plate and a shared bathroom down the hall. More tenants meant more rent from the same walls. Then the crowding and the wear were pointed at as proof that Black neighbors ruined property, by the very interests collecting the rents.",
        "And understand what this street was before the wreckers came. Nearly **fifty bars, clubs, and shops** ran along 55th and Lake Park. The Compass Players opened in a storefront at 1152 East 55th in 1955, the troupe that grew into Second City. It was crowded, loud, newly integrated, a little rough, and more alive than almost any street in the city. The university two blocks south looked at all that life and saw a threat to its future. What it did about it is the next stop. First, the two red plates here name the machinery that made the whole cycle turn.",
      ],
      interrupts: [
        {
          title: "Redlining",
          body: [
            "In 1939 and 1940 a federal agency, the Home Owners' Loan Corporation, graded every Chicago neighborhood for mortgage risk. Green was best, then blue, then yellow, then red. The colors tracked race almost exactly. Most of the Black Belt was drawn red, hazardous. Hyde Park and Kenwood were drawn yellow, definitely declining, in part because Black Chicago lived next door.",
            "The Federal Housing Administration's underwriting manual pointed lenders the same way, favoring covenanted, all-white neighborhoods. Banks followed the maps and the manual, so a Black family with steady income and savings could not get an ordinary mortgage on these blocks. That vacuum is exactly what the contract sellers moved into.",
          ],
        },
        {
          title: "Buying on contract",
          body: [
            "A contract sale worked like rent with none of rent's protections. Researchers at Duke found that 75 to 95 percent of the homes sold to Black families in 1950s and 60s Chicago were sold on contract, at an average markup of 84 percent. A speculator might buy a building for $12,000 and resell it within months for $22,000 or more. The sellers were often syndicates of professionals, sometimes including the same bankers who had denied the mortgage.",
            "The buyer owned nothing until the final payment. Miss one month and the seller could evict, keep every dollar already paid, and sell the house again on a fresh contract. The same study put the wealth taken from Black Chicago families this way at $3.2 to $4 billion. Payments that steep left nothing for repairs, and the disrepair was then cited as proof that Black neighbors lowered property values.",
          ],
        },
      ],
      images: [
        {
          src: `${MEDIA}/kitchenette-1941.jpg`,
          alt: "A grand corner apartment building in the Black Belt in 1941 with a sign reading Park-Vista Kitchenettes, people and cars on the street below",
          credit:
            "A Black Belt apartment house cut into one-room kitchenettes. Russell Lee, April 1941, Farm Security Administration, Library of Congress. Public domain.",
          label: "1941",
        },
      ],
      nowImage: {
        src: `${MEDIA}/55th-street-today.jpg`,
        alt: "The 1961 urban renewal townhouses on 55th Street today, flat-roofed rows behind small fenced front courts",
        credit:
          "The renewal-era townhouses on 55th Street today. Photograph by Warren LeMay, via Wikimedia Commons. CC BY-SA 4.0.",
        label: "Today",
      },
      toNext: {
        text: "Keep east on 55th Street to Harper Avenue, then turn north. Two blocks up, 53rd Street opens into a plaza with a glass tower above the shops. That is Harper Court.",
        distanceMeters: 790,
        minutes: 10,
      },
      sources: [
        { label: "The Plunder of Black Wealth in Chicago, Duke report, 2019", url: "https://www.fhcci.org/wp-content/uploads/2019/05/Plunder-of-Black-Wealth-Chicago-Report-2019.pdf" },
        { label: "WBEZ, contract buying robbed Black families of billions", url: "https://www.wbez.org/money/2019/05/30/contract-buying-robbed-black-families-in-chicago-of-billions" },
        { label: "Mapping Inequality, the HOLC maps of Chicago", url: "https://dsl.richmond.edu/panorama/redlining/" },
        { label: "Ta-Nehisi Coates, The Case for Reparations", url: "https://www.theatlantic.com/magazine/archive/2014/06/the-case-for-reparations/361631/" },
        { label: "Hyde Park Herald, Lost Hyde Park's land clearance", url: "https://www.hpherald.com/news/local/lost-hyde-park-land-clearance/article_64703e2e-7240-11ec-b986-ebf650131a4d.html" },
      ],
    },
    {
      id: "harper-court",
      number: 10,
      title: "Harper Court",
      dek: "Urban renewal rebuilt the neighborhood, and chose its neighbors again",
      mapLabel: "Harper Court",
      lat: 41.79945,
      lng: -87.58845,
      audioSrc: `${MEDIA}/audio/stop-10.mp3`,
      audioSeconds: 157,
      transcript: [
        "In 1952 the university, watching its enrollment and its nerves, created the **South East Chicago Commission** and handed it to a lawyer named Julian Levi, with a mandate his chancellor stated flatly. Buy, control, and rebuild the neighborhood. Levi helped shape the state and federal renewal laws he needed, then used them. Hyde Park and Kenwood became the site of the **first great federally backed urban renewal scheme in the country**, with the university putting in $29 million of its own money alongside the government's.",
        "The mechanics were blunt. Blocks were declared blighted. Public money bought them and cleared them. The people living there had to go, wherever they could. Demolition started along 55th and Lake Park in 1955, and the full plan passed City Council in 1958. By the finish it had leveled **638 buildings on 856 acres** and displaced about **4,000 families, most of them Black and poor**. Follow the two groups afterward and the design shows itself. Nearly half of the displaced white families found new homes inside Hyde Park and Kenwood. Among Black families, roughly **one in six** did. James Baldwin, watching the same program at work in San Francisco, gave it the name that stuck. Urban renewal, he said, \"means Negro removal.\"",
        "What rose on the cleared land is all around you. The flat-roofed townhouses you walked past, the twin apartment slabs parked in the middle of 55th Street, and this shopping court, built in 1965 to rehouse the artisans and small businesses the bulldozers had scattered. Three displaced businesses actually made it in. The fifty bars never came back at all. The block that raised Second City eventually got the chains you see around you now.",
        "Two things are true at once about what happened here, and the honest version of this tour holds both. Hyde Park after renewal became one of the few Chicago neighborhoods where integration more or less held, where Black and white families have lived side by side for seventy years now. And it got that way partly by demolishing the poorest blocks and pushing out the people who lived on them, under a university that remains the biggest landowner in sight and runs one of the largest private police forces in the country, patrolling far beyond its campus. Planners called it conservation. Displaced Hyde Parkers had other words. The red plate below is the last piece of machinery, and then the final stop closes the circle.",
      ],
      interrupts: [
        {
          title: "Urban renewal",
          body: [
            "Urban renewal let a city declare blocks blighted, clear them with public money, and hand the land to approved new uses. The Hyde Park-Kenwood plan, approved November 7, 1958, was the nation's first large federally supported renewal scheme, driven by the university's South East Chicago Commission with federal grants behind it.",
            "What it built is all around this corner, the townhouses, the mid-street apartments, the shopping court. What it removed was the housing poor families could afford and nearly fifty bars and shops along 55th alone. Planners called it conservation. The displaced, and Baldwin, had a shorter word for it. The tools changed over this walk, from a code of ethics to a deed clause to a color on a map to a wrecking ball. The incentives never did.",
          ],
        },
      ],
      images: [
        {
          src: `${MEDIA}/hyde-park-aerial-1927.jpg`,
          alt: "A 1927 aerial photograph labeled Hyde Park Hotel District, dense hotel towers along the beach and neighborhood stretching inland",
          credit:
            "The Hyde Park hotel district from the air, 1927, before the covenant fights and the bulldozers. Chicago Aerial Survey, Newberry Library. Public domain.",
          label: "1927",
        },
      ],
      nowImage: {
        src: `${MEDIA}/harper-court-today.jpg`,
        alt: "Harper Court's 53rd Street frontage today in falling snow, chain storefronts under a glass office tower",
        credit:
          "Harper Court's 53rd Street front today. Photograph by TonyTheTiger, 2025, via Wikimedia Commons. CC0.",
        label: "Today",
      },
      toNext: {
        text: "The last leg is the longest, about twenty minutes. Take Harper Avenue south back to 55th, jog east to Lake Park, and follow Lake Park and then Stony Island south. Past the Midway, the granite tower rising out of Jackson Park is the Obama Presidential Center. Enter the campus from Stony Island.",
        distanceMeters: 1750,
        minutes: 22,
      },
      sources: [
        { label: "UChicago CEGU, university-led urban renewal", url: "https://cegu.uchicago.edu/2023/11/30/university-led-renewal/" },
        { label: "Hyde Park Herald, Lost Hyde Park's land clearance", url: "https://www.hpherald.com/news/local/lost-hyde-park-land-clearance/article_64703e2e-7240-11ec-b986-ebf650131a4d.html" },
        { label: "Docomomo, the Hyde Park A and B renewal project", url: "https://docomomo-us.org/news/hyde-park-a-b-urban-renewal-project" },
        { label: "James Baldwin in Take This Hammer, 1963", url: "https://scalar.usc.edu/works/housing-inequality/urban-renewalmeans-negro-removal--james-baldwin-1963" },
        { label: "South Side Weekly, the fight over Chicago's largest private police force", url: "https://southsideweekly.com/the-fight-over-chicagos-largest-private-police-force-university-of-chicago-ucpd/" },
      ],
    },
    {
      id: "obama-center",
      number: 11,
      title: "The Obama Center",
      dek: "The circle closes where the White City stood",
      mapLabel: "Obama Center",
      lat: 41.7859,
      lng: -87.5857,
      audioSrc: `${MEDIA}/audio/stop-11.mp3`,
      audioSeconds: 181,
      transcript: [
        "End on the plaza, where you can see the whole tower. Near the top, the granite wall turns into carved letters, lines from the speech Barack Obama gave at Selma in 2015. The museum opened on **June 19, 2026. Juneteenth.** It took almost five years to build, cost about 850 million dollars, and the Obamas chose this park, this exact ground, where Chicago staged the World's Fair you saw across the water at stop four. The first Black president's words now wrap a 225-foot tower over the fairgrounds that shut Black Americans out. It reads like closure.",
        "It is not closure yet, and this whole walk is the reason why. Watch history rhyme instead. When the fair came in 1893, attention and money flooded these blocks, prices jumped, and the neighborhood began deciding, on paper, exactly who the boom was for. The Center is producing our decade's version of that story. Across the Midway in East Woodlawn, the median home price **doubled between 2019 and 2025, reaching about $440,000**, in a community where most residents rent.",
        "The fight over who benefits has run for a decade. Organizers spent years demanding a signed community benefits agreement. Obama refused, asking at a public meeting who exactly could sign on behalf of a whole community. The city passed a Woodlawn housing ordinance instead, in 2020. Reporters checked five years later and found **three of its seven programs had never launched** and its centerpiece tenant protection had never once been used. A stronger ordinance took effect this spring. And the Chicago Association of Realtors, the renamed descendant of the very board whose 1917 policy opened this walk's red plates, opposed the tenant protections at its core. The instruments changed. The incentives did not.",
        "So stand here and run the whole line once. Cornell buys the marsh and picks his buyers. The fair dazzles the world while Wells and Douglass hand out the truth at its gates. The professors' quarter writes its rules, the realtors write theirs, the government colors the maps, the speculators write the contracts, and the bulldozers finish the job. Every stage had authors. Every instrument had a signature. Nothing in this story was weather.",
        "In 1893 this ground told Black Chicagoans there was no room for them in the future. This summer it said the opposite. Which sentence lasts is not up to the ground. It depends on choices exactly as deliberate as the ones you just spent an afternoon walking through. Exclusion was engineered here. Repair will have to be engineered too. Thanks for walking with us. Valois is ten minutes back up the way you came, and the museum is worth the ticket.",
      ],
      images: [
        {
          src: `${MEDIA}/woodlawn-63rd-1973.jpg`,
          alt: "63rd Street in Woodlawn in 1973, with the elevated tracks crossing overhead and pedestrians on the sidewalks",
          credit:
            "63rd Street under the L, 1973, in the Woodlawn this story keeps returning to. John H. White, EPA DOCUMERICA, National Archives. Public domain.",
          label: "1973",
        },
      ],
      nowImage: {
        src: `${MEDIA}/opc-opening-2026.jpg`,
        alt: "The granite museum tower of the Obama Presidential Center on its opening day, with crowds filling the plaza below",
        credit:
          "The museum tower on opening day, June 19, 2026. Photograph by AlphaBeta135, via Wikimedia Commons. CC0.",
        label: "Today",
      },
      sources: [
        { label: "Obama Foundation, grand opening FAQ", url: "https://www.obama.org/visit/grand-opening/faq/" },
        { label: "Chicago Maroon, Obama on the community benefits agreement, 2017", url: "https://www.chicagomaroon.com/article/2017/9/15/obama-explains-presidential-center-sign-community/" },
        { label: "Illinois Answers Project, Woodlawn affordability five years on", url: "https://illinoisanswers.org/2026/05/07/affordability-woodlawn-obama-center-housing-costs/" },
        { label: "Chicago Lawyers' Committee, how the Obama CBA was won", url: "https://www.clccrul.org/blog/how-the-obama-cba-was-won" },
      ],
    },
  ],
};
