import type { WalkTour } from "./walk-types";

// ------------------------------------------------------------------
// The Jackson Park walk. A nine-stop self-paced audio loop that
// starts and ends at the Obama Presidential Center. Route, stop
// coordinates, and leg times were checked against OpenStreetMap
// foot routing in July 2026; the Darrow Bridge is closed (view-only
// stop) and the island bridge gates lock at dusk, which the copy
// reflects. Narration is written from the sources listed on each
// stop; nothing in the transcript should ever outrun them.
// Audio is generated by scripts/walk-tts.mjs; durations.json from
// that script is the source of audioSeconds.
// ------------------------------------------------------------------

const MEDIA = "/media/jackson-park-walk";

export const JACKSON_PARK_WALK: WalkTour = {
  title: "Walk Jackson Park",
  dek: "A free self-guided audio tour that starts and ends at the Obama Presidential Center. Nine short stops, about an hour on foot. The 1893 World's Fair stood here, and the century since has been a running argument about who the South Side is for.",
  walkMinutes: 55,
  listenMinutes: 11,
  distanceMiles: 2.5,
  startLabel: "Obama Presidential Center",
  practical: [
    {
      title: "Hours and tickets",
      text: "The walk itself is free and needs no ticket. The Center's grounds are open daily from 6 a.m. to 9 p.m.; the museum requires a timed ticket if you want to go inside afterward. The Garden of the Phoenix is closed Mondays, and the bridges onto Wooded Island have been gated from dusk to dawn in recent years, so do this walk in daylight.",
    },
    {
      title: "The ground",
      text: "Almost the whole route is paved and flat. The path down Wooded Island is unpaved but level. The old stone Darrow Bridge is fenced off, so you view it rather than cross it. Stony Island Avenue and Hayes Drive carry real traffic; cross them only at the marked crosswalks.",
    },
    {
      title: "Listening",
      text: "Headphones are nicest, but a phone speaker works fine in the park. Every stop's audio is also printed on the page, so you can read instead of listen. If you share your location, it is used only to draw your dot on the map. It never leaves your phone.",
    },
  ],
  route: [
    [41.7859, -87.5857],
    [41.78625, -87.5865],
    [41.7865, -87.5875],
    [41.7871, -87.5883],
    [41.78655, -87.58745],
    [41.7863, -87.5868],
    [41.7869, -87.586],
    [41.7877, -87.5855],
    [41.7885, -87.5852],
    [41.7891, -87.5849],
    [41.7889, -87.5845],
    [41.78855, -87.58425],
    [41.788, -87.5838],
    [41.7875, -87.5836],
    [41.7869, -87.58365],
    [41.7858, -87.5828],
    [41.7845, -87.5825],
    [41.7832, -87.5823],
    [41.7819, -87.5822],
    [41.781, -87.5817],
    [41.78, -87.5806],
    [41.7796, -87.5799],
    [41.7797, -87.5815],
    [41.7798, -87.5835],
    [41.78, -87.5852],
    [41.7813, -87.5858],
    [41.7828, -87.5861],
    [41.7843, -87.586],
    [41.7852, -87.5856],
  ],
  stops: [
    {
      id: "obama-center",
      number: 1,
      title: "The Obama Presidential Center",
      dek: "Start on the plaza of a museum that opened this summer",
      mapLabel: "Obama Center",
      lat: 41.7859,
      lng: -87.5857,
      audioSrc: `${MEDIA}/audio/stop-01.mp3`,
      audioSeconds: 61,
      transcript: [
        "Find a spot on the plaza where you can see the whole tower. The stone is New Hampshire granite, cut in big flat facets, and near the top the wall turns into letters. Those lines come from the speech Barack Obama gave in Selma, Alabama, in 2015.",
        "All of this is new. The museum opened on June nineteenth, 2026. Juneteenth. It took almost five years to build and cost about 850 million dollars. Fourteen proposals came in, from Hawaii to New York, and the Obamas chose this park on the South Side, where their public lives began.",
        "The land has held big plans before. Illinois set it aside in 1869, and Frederick Law Olmsted and Calvert Vaux, the designers of Central Park, drew the first plan for it two years later. They wanted a park you could move through by boat. What actually shaped the ground under your feet was the World's Fair of 1893. Everything else on this walk goes back to that summer.",
      ],
      keyFacts: ["Opened June 19, 2026", "225-foot granite tower", "Built for about 850 million dollars"],
      lookFor:
        "Look up near the top of the tower. The carved letters spell out lines from Obama's 2015 Selma speech.",
      images: [
        {
          src: `${MEDIA}/opc-opening-2026.jpg`,
          alt: "The granite museum tower of the Obama Presidential Center on its opening day, with crowds filling the plaza below",
          credit:
            "The museum tower on opening day, June 19, 2026. Photograph by AlphaBeta135, via Wikimedia Commons. CC0.",
        },
      ],
      toNext: {
        text: "Walk northwest through the campus toward the corner of Stony Island Avenue and the Midway Plaisance. Cross Stony Island at the light, then keep going west into the green strip, past the playground.",
        distanceMeters: 633,
        minutes: 8,
      },
      sources: [
        { label: "Obama Foundation, grand opening FAQ", url: "https://www.obama.org/visit/grand-opening/faq/" },
        { label: "Obama Foundation, choosing Jackson Park", url: "https://www.obama.org/stories/choosing-jackson-park/" },
        { label: "Tod Williams Billie Tsien Architects, project page", url: "https://twbta.com/work/cultural/the-obama-presidential-center/" },
        { label: "Chicago Park District, Jackson Park history", url: "https://www.chicagoparkdistrict.com/parks-facilities/jackson-andrew-park" },
      ],
    },
    {
      id: "midway-plaisance",
      number: 2,
      title: "The Midway Plaisance",
      dek: "The fair's mile of shows, now the quiet green next door",
      mapLabel: "Midway",
      lat: 41.7865,
      lng: -87.5875,
      audioSrc: `${MEDIA}/audio/stop-02.mp3`,
      audioSeconds: 80,
      transcript: [
        "Stop anywhere on the grass with a clear view west. This strip of lawn is the Midway Plaisance, a mile long and about six hundred feet wide, running all the way to Washington Park. Every carnival midway in America is named after it.",
        "In the summer of 1893 this was the fair's amusement zone. The white palaces stood in the park behind you. Out here were the ticketed shows, which took in over four million dollars in six months. The shows included so-called villages, where people from Africa, Asia, and the Middle East were put on display for paying crowds under the banner of anthropology. That happened on this lawn too. About half a mile down the strip, where the skating rink sits now, rose the first Ferris wheel, built by a bridge engineer named George Ferris as America's answer to the Eiffel Tower. It stood 264 feet tall, and fifty cents bought a twenty-minute ride.",
        "The east end where you are standing was remade this spring. The playground here opened in June 2026, the first in Chicago designed so that disabled and non-disabled kids play on the same equipment, with the four million dollar cost covered by the Obama Foundation. Before you turn back, walk two minutes further west. There is a stone bench most people miss.",
      ],
      keyFacts: ["The fair's amusement mile, 1893", "264-foot original Ferris wheel", "First fully inclusive playground, 2026"],
      lookFor:
        "The new playground beside you, then the unbroken mile of green running west. The skating rink halfway down marks the Ferris wheel's footprint.",
      images: [
        {
          src: `${MEDIA}/ferris-wheel-1893.jpg`,
          alt: "The original 264-foot Ferris Wheel towering over the crowded Midway Plaisance in 1893",
          credit:
            "The first Ferris Wheel on the Midway, 1893. C. D. Arnold, Official Views of the World's Columbian Exposition. Public domain, via Wikimedia Commons.",
        },
      ],
      toNext: {
        text: "Follow the center path west toward the rail embankment. The limestone bench sits just before it, on your right.",
        distanceMeters: 111,
        minutes: 2,
      },
      sources: [
        { label: "Midway Plaisance, Wikipedia", url: "https://en.wikipedia.org/wiki/Midway_Plaisance" },
        { label: "Ferris Wheel of 1893, Wikipedia", url: "https://en.wikipedia.org/wiki/Ferris_Wheel_(1893)" },
        { label: "Chicago Park District, inclusive playground ribbon cutting", url: "https://www.chicagoparkdistrict.com/about-us/news/chicago-park-district-and-obama-foundation-cut-ribbon-citys-first-fully-inclusive" },
      ],
    },
    {
      id: "cheney-goode",
      number: 3,
      title: "The Cheney-Goode Memorial",
      dek: "A stone bench for two women who went to Springfield",
      mapLabel: "Cheney-Goode",
      lat: 41.7871,
      lng: -87.5883,
      audioSrc: `${MEDIA}/audio/stop-03.mp3`,
      audioSeconds: 51,
      transcript: [
        "The long limestone bench here has been in place since 1932. Katherine Goode won a seat in the Illinois legislature in the 1920s and died in office in 1928. Flora Cheney, a suffrage leader who ran the Illinois League of Women Voters, was elected to the seat that November. Within a year she was gone too.",
        "Donors raised this bench in their memory, one of the first monuments in Chicago honoring women's public work. It has not had an easy century. Its sundial was stolen, and at one point the stone was painted gray just to bury the graffiti. When the Park District rebuilt this end of the Midway, the bench was finally restored, and it was unveiled again on June eighth, 2026, days before the Center opened its doors.",
        "Sit for a minute if you like. The bench was built for exactly that. Then the walk turns back into the park.",
      ],
      keyFacts: ["Dedicated 1932", "Two pioneering women legislators", "Restored June 2026"],
      lookFor:
        "The long limestone bench itself, cleaned and reset this June after decades under gray paint, with the rail embankment rising behind it.",
      images: [],
      toNext: {
        text: "Head back east the way you came and recross Stony Island Avenue at the same light. Inside Jackson Park, follow the paths northeast, keeping the big domed museum ahead on your left. When you reach water with the museum across it, you are at the Columbia Basin.",
        distanceMeters: 467,
        minutes: 6,
      },
      sources: [
        { label: "Chicago Park District, Cheney-Goode Memorial", url: "https://www.chicagoparkdistrict.com/parks-facilities/cheney-goode-memorial" },
        { label: "Chicago Park District, Midway east end project", url: "https://www.chicagoparkdistrict.com/about-us/news/chicago-park-district-and-obama-foundation-cut-ribbon-citys-first-fully-inclusive" },
      ],
    },
    {
      id: "columbia-basin",
      number: 4,
      title: "The Columbia Basin",
      dek: "The palace across the water is the fair's last building",
      mapLabel: "Columbia Basin",
      lat: 41.7891,
      lng: -87.5849,
      audioSrc: `${MEDIA}/audio/stop-04.mp3`,
      audioSeconds: 56,
      transcript: [
        "The water in front of you is the Columbia Basin, and the building across it is the Museum of Science and Industry. It is also the last major fair building still standing on the fairgrounds.",
        "That summer it was the Palace of Fine Arts. Most of the White City was plaster over wood frames, built to last a single season. This one held a fortune in borrowed art, so it got a fireproof brick core under the plaster. The brick is why it survived when everything around it burned or came down. The Field Museum lived here until 1920, and then the building sat and rotted.",
        "Julius Rosenwald, the president of Sears, saved it. He pledged three million dollars in 1926 and ended up giving more than five. He refused to put his name on the building. His money had another project in those same years, helping to build about five thousand schoolhouses for Black children across the segregated South.",
      ],
      keyFacts: ["Palace of Fine Arts, 1893", "Rosenwald gave over 5 million dollars", "About 5,000 Rosenwald schools"],
      lookFor:
        "The 1893 facade reflected in the basin. Every other building this size at the fair was gone within a few years.",
      images: [
        {
          src: `${MEDIA}/palace-fine-arts-1893.jpg`,
          alt: "The domed Palace of Fine Arts reflected in the North Pond during the 1893 World's Fair",
          credit:
            "The Palace of Fine Arts, 1893, today's Museum of Science and Industry. C. D. Arnold, Official Views of the World's Columbian Exposition. Public domain, via Wikimedia Commons.",
        },
      ],
      toNext: {
        text: "Keep the water on your left and follow the rim path southeast until you reach a low stone bridge behind a fence.",
        distanceMeters: 195,
        minutes: 3,
      },
      sources: [
        { label: "Museum of Science and Industry origins, Wikipedia", url: "https://en.wikipedia.org/wiki/Rosenwald_Industrial_Museum" },
        { label: "National Park Service, the Rosenwald schools", url: "https://www.nps.gov/articles/the-rosenwald-schools-progressive-era-philanthropy-in-the-segregated-south-teaching-with-historic-places.htm" },
        { label: "World's Columbian Exposition, Wikipedia", url: "https://en.wikipedia.org/wiki/World%27s_Columbian_Exposition" },
      ],
    },
    {
      id: "darrow-bridge",
      number: 5,
      title: "The Clarence Darrow Bridge",
      dek: "The park's oldest structure, fenced off since 2013",
      mapLabel: "Darrow Bridge",
      lat: 41.78855,
      lng: -87.58425,
      audioSrc: `${MEDIA}/audio/stop-05.mp3`,
      audioSeconds: 58,
      transcript: [
        "The low stone bridge behind the fence is the oldest structure in Jackson Park. Burnham and Root built it in 1880, before the fair was even an idea, and the park commissioners of the day called it the most important work in the park.",
        "It is named for Clarence Darrow, the defense lawyer, who lived nearby. He liked to pace this span rehearsing his arguments, and to fish in the lagoon under it. When he died in March 1938, his ashes were scattered from the bridge into the water, exactly as he had asked. Every March thirteenth since 1961, people have gathered here to toss a wreath in after him. They still do, fence or no fence.",
        "The bridge was closed to cars in 2009, the fence against walkers went up in 2013, and the rebuild has been promised and postponed ever since. The city's latest word is fall of 2028. Darrow spent his career on causes other people had walked away from. For now, his bridge is one of them.",
      ],
      keyFacts: ["Built 1880 by Burnham and Root", "Oldest structure in the park", "Rebuild promised for 2028"],
      lookFor:
        "The low stone arch behind the fence. In March, look for wreaths on the water; neighbors still toss one in for Darrow every year.",
      images: [
        {
          src: `${MEDIA}/darrow-1913.jpg`,
          alt: "Portrait of Clarence Darrow in 1913, seated with his hand on his chin",
          credit:
            "Clarence Darrow, 1913. Underwood and Underwood, Library of Congress Prints and Photographs Division. Public domain.",
        },
      ],
      toNext: {
        text: "Walk south to the next bridge, the open one, and cross onto the island. Follow the path to the garden gate at the island's north tip.",
        distanceMeters: 219,
        minutes: 3,
      },
      sources: [
        { label: "Preservation Chicago, Darrow Memorial Bridge", url: "https://www.preservationchicago.org/clarence-darrow-memorial-bridge/" },
        { label: "Block Club Chicago, Darrow memorial gathering 2025", url: "https://blockclubchicago.org/2025/03/14/neighbors-honor-clarence-darrow-100-years-after-scopes-monkey-trial-at-his-namesake-bridge/" },
        { label: "Hyde Park Herald, bridge rebuild pushed to fall 2028", url: "https://www.hpherald.com/evening_digest/darrow-bridge-reconstruction-pushed-to-fall-2028-as-cdot-skips-jpac-meeting/article_8d3200d3-5498-47d3-aaa2-b880cf5b1a7c.html" },
      ],
    },
    {
      id: "garden-of-the-phoenix",
      number: 6,
      title: "The Garden of the Phoenix",
      dek: "The garden Japan gave the fair in 1893",
      mapLabel: "Garden of the Phoenix",
      lat: 41.7869,
      lng: -87.58365,
      audioSrc: `${MEDIA}/audio/stop-06.mp3`,
      audioSeconds: 79,
      transcript: [
        "The gate at the island's tip leads into the Garden of the Phoenix. It is closed on Mondays, but you can see a good deal of it from the path even then. It is small, so if the gate is open, give it ten unhurried minutes.",
        "In 1893 Japan built its fair pavilion on this spot. Three linked wooden halls, laid out in the shape of a phoenix and modeled on the Phoenix Hall of a temple in Uji, near Kyoto. The choice of bird was deliberate, for a city that had just rebuilt itself after the Great Fire of 1871. Unlike nearly everything else at the fair, the Ho-o-den was a permanent gift, and it stood here for half a century.",
        "In 1946, months after the war with Japan ended, the pavilion burned in a series of arson fires that most accounts tie to the anti-Japanese feeling of those years. The garden around it was abandoned for decades, then revived piece by piece. In 2016 Yoko Ono set twelve steel lotus petals on the pavilion's footprint, her first permanent public artwork in the Americas. She called it Sky Landing. The cherry trees around you, well over a hundred of them, were planted for the gift's hundred and twentieth anniversary, and in 2019 they bloomed all at once for the first time. The path ahead runs the whole length of the island. Take it slowly.",
      ],
      keyFacts: ["Japan's gift to the fair, 1893", "Burned 1946", "Sky Landing by Yoko Ono, 2016"],
      lookFor:
        "Twelve steel lotus petals rising from earth mounds, set exactly where the Ho-o-den stood. In spring, the cherry trees all around them.",
      images: [
        {
          src: `${MEDIA}/hooden-1893.jpg`,
          alt: "The Ho-o-den, Japan's wooden pavilion of three connected halls, on the Wooded Island in 1893",
          credit:
            "The Ho-o-den, Japan's pavilion on the Wooded Island, 1893. C. D. Arnold, Official Views of the World's Columbian Exposition. Public domain, via Wikimedia Commons.",
        },
      ],
      toNext: {
        text: "Take the single path that runs the length of the island, south through the trees, until you cross the small bridge off the island's far end.",
        distanceMeters: 587,
        minutes: 8,
      },
      sources: [
        { label: "Garden of the Phoenix, Wikipedia", url: "https://en.wikipedia.org/wiki/Garden_of_the_Phoenix" },
        { label: "Chicago Park District, Sky Landing", url: "https://www.chicagoparkdistrict.com/parks-facilities/sky-landing-artwork" },
        { label: "Julia Bachrach, the Japanese garden on Wooded Island", url: "https://www.jbachrach.com/blog/2022/10/28/the-fascinating-story-of-the-japanese-garden-on-jacksons-parks-wooded-island" },
      ],
    },
    {
      id: "wooded-island",
      number: 7,
      title: "Wooded Island",
      dek: "The quiet Olmsted kept at the center of the fair",
      mapLabel: "Wooded Island",
      lat: 41.7819,
      lng: -87.5822,
      audioSrc: `${MEDIA}/audio/stop-07.mp3`,
      audioSeconds: 47,
      transcript: [
        "You have just walked the length of Wooded Island, the ribbon of trees and prairie between the park's two lagoons. Olmsted kept the island itself a natural retreat while the fair rose around it, and Japan's pavilion was nearly the only building allowed on. Look at any bird's-eye print of the White City and you will see it, a dark green island in the middle of the fairgrounds.",
        "Since 1977 this has been the Paul H. Douglas Nature Sanctuary, named for the Illinois senator who championed wild places, and it has become one of the city's best birding spots, especially during the spring warbler migration.",
        "The island's bridge gates have been locked from dusk to dawn in recent years, so this is an afternoon place. What is left of the fair's front door is across the next bridge.",
      ],
      keyFacts: ["Olmsted's natural retreat", "Paul H. Douglas Nature Sanctuary, 1977", "One of the city's best birding spots"],
      lookFor:
        "Birds. Migration seasons fill the island; even in summer, keep your voice low and count the calls you can pick apart.",
      images: [
        {
          src: `${MEDIA}/birdseye-1893.jpg`,
          alt: "An 1893 bird's eye lithograph of the World's Columbian Exposition grounds filling Jackson Park, with the Wooded Island at the center of the lagoons",
          credit:
            "Bird's eye view of the fairgrounds, 1893. Rand McNally and Company, Library of Congress Geography and Map Division. Public domain.",
        },
      ],
      toNext: {
        text: "Follow the lagoon-side path south, cross the channel on the walkway beside Hayes Drive, and the golden statue is ahead at the corner of Hayes and Richards.",
        distanceMeters: 395,
        minutes: 5,
      },
      sources: [
        { label: "Jackson Park Advisory Council, park timeline", url: "https://www.jacksonparkadvisorycouncil.org/about-the-park/history/" },
        { label: "Jackson Park history, Chicago Park District", url: "https://www.chicagoparkdistrict.com/parks-facilities/jackson-andrew-park" },
      ],
    },
    {
      id: "statue-of-the-republic",
      number: 8,
      title: "The Statue of the Republic",
      dek: "The Golden Lady marks the door of the White City",
      mapLabel: "The Republic",
      lat: 41.7796,
      lng: -87.5799,
      audioSrc: `${MEDIA}/audio/stop-08.mp3`,
      audioSeconds: 85,
      transcript: [
        "The Golden Lady has stood at this corner since 1918. Daniel Chester French made her, a one-third scale bronze of the sixty-five-foot statue he built for the fair. She marks the spot where the fair's Administration Building stood, at the head of the Court of Honor. The Grand Basin and its white palaces ran east from here toward the lake, and in six months they drew more than 27 million visits, in a country of 65 million people.",
        "Ida B. Wells spent that summer telling the world what the White City left out. Black Americans were shut out of the fair's jobs, and Black achievement was shut out of its exhibits. Wells asked for a pavilion answering that, and the fair said no. So she published a pamphlet with Frederick Douglass and two other writers. It was called The Reason Why the Colored American Is Not in the World's Columbian Exposition, and it carried prefaces in English, French, and German so that visitors from anywhere could read it. By her own count she handed out some ten thousand copies.",
        "She worked from the Haiti Pavilion, because Douglass, then in his seventies, was Haiti's commissioner to the fair, and his building became Black America's unofficial home that summer. The fair's answer was a single 'Colored American Day' in late August. Douglass gave the keynote. The Haiti Pavilion itself is gone. You can still read the whole pamphlet today.",
      ],
      keyFacts: ["The Golden Lady, 1918", "One-third scale of the 1893 original", "27 million fair visits"],
      lookFor:
        "Her gilding up close, then turn east. The Grand Basin and the Court of Honor filled the ground between you and the lake.",
      images: [
        {
          src: `${MEDIA}/court-of-honor-1893.jpg`,
          alt: "The Court of Honor and Grand Basin in 1893, seen from behind the original Statue of the Republic, with the domed Administration Building across the water",
          credit:
            "The Court of Honor from the Peristyle, 1893, with the original 65-foot Republic in the foreground. C. D. Arnold. Public domain, via Wikimedia Commons.",
        },
        {
          src: `${MEDIA}/ida-b-wells-1893.jpg`,
          alt: "Studio portrait of Ida B. Wells around 1893",
          credit:
            "Ida B. Wells, photographed in Chicago around 1893 by Mary Garrity. Restored by Adam Cuerden. Public domain, via Wikimedia Commons.",
        },
      ],
      toNext: {
        text: "This last leg is the longest of the walk, about eighteen quiet minutes. Take the path west along the north side of Hayes Drive, then turn north onto the wide car-free trail along the lagoon's west shore. Cars ran here until 2023, when Cornell Drive was closed and turned back into parkland. Follow the trail to Stony Island Avenue and enter the Center's campus from the south.",
        distanceMeters: 1415,
        minutes: 18,
      },
      sources: [
        { label: "Chicago Park District, Statue of the Republic", url: "https://www.chicagoparkdistrict.com/parks-facilities/statue-republic" },
        { label: "The Reason Why the Colored American Is Not in the World's Columbian Exposition, full text", url: "https://digital.library.upenn.edu/women/wells/exposition/exposition.html" },
        { label: "Hyde Park Historical Society, Douglass and the Haiti Pavilion plaque", url: "https://www.hydeparkhistory.org/blog/frederick-douglasshaiti-pavilion-memorial-plaque-reinstallationnbsp" },
        { label: "Statue of The Republic, Wikipedia", url: "https://en.wikipedia.org/wiki/Statue_of_The_Republic" },
      ],
    },
    {
      id: "back-at-the-center",
      number: 9,
      title: "Back at the Center",
      dek: "End the walk looking west into Woodlawn",
      mapLabel: "Return",
      lat: 41.7852,
      lng: -87.5856,
      audioSrc: `${MEDIA}/audio/stop-09.mp3`,
      audioSeconds: 107,
      transcript: [
        "You are back where you started, so look west this time, across Stony Island into Woodlawn. A century ago 63rd Street was one of the biggest commercial streets in Chicago outside the Loop, famous for its jazz clubs and the Tivoli theater, under an L line built to carry crowds to the fair in this park.",
        "The century since was shaped by paperwork. In 1928 a property owners' association, quietly financed by the University of Chicago, blanketed blocks about a mile west of here with covenants barring Black families. When Carl Hansberry bought a house inside that boundary in 1937, the fight went to the Supreme Court. His daughter Lorraine later turned that year into A Raisin in the Sun. The covenants died in the courts and the neighborhood became Black. Then the money left. Woodlawn held 81,000 people in 1960 and 24,000 by 2020.",
        "So when the Obama Center picked this corner, Woodlawn's first question was blunt. Who is this for? Organizers spent years pushing for a signed community benefits agreement. Obama refused. Speaking by video at a public meeting in 2017, he asked, \"I would then be signing with who? What particular organizations would end up speaking for everybody in that community?\" The city passed a Woodlawn housing ordinance instead, in 2020. This spring, reporters checked on it. One building had gone up on the 52 city lots the ordinance set aside, and the price of a typical Woodlawn house had climbed from 72,500 dollars in 2016 to 330,000 last year. And on Juneteenth the Center opened, with museum dates selling out weeks ahead. That is the park you just walked.",
      ],
      keyFacts: ["Covenants blanketed Woodlawn, 1928", "81,000 people in 1960, 24,000 by 2020", "Woodlawn housing ordinance, 2020"],
      lookFor:
        "From the campus edge, look west across Stony Island into Woodlawn, and notice how wide and quiet 63rd Street runs without its L.",
      images: [
        {
          src: `${MEDIA}/woodlawn-63rd-1973.jpg`,
          alt: "63rd Street in Woodlawn in 1973, with the elevated tracks crossing overhead and pedestrians on the sidewalks",
          credit:
            "63rd Street under the L, 1973. John H. White, EPA DOCUMERICA, National Archives. Public domain.",
        },
      ],
      sources: [
        { label: "Chicago Maroon, Obama on the community benefits agreement, 2017", url: "https://www.chicagomaroon.com/article/2017/9/15/obama-explains-presidential-center-sign-community/" },
        { label: "Chicago Lawyers' Committee, how the Obama CBA was won", url: "https://www.clccrul.org/blog/how-the-obama-cba-was-won" },
        { label: "Illinois Answers Project, Woodlawn affordability five years on", url: "https://illinoisanswers.org/2026/05/07/affordability-woodlawn-obama-center-housing-costs/" },
        { label: "Washington Park Subdivision covenants, Wikipedia", url: "https://en.wikipedia.org/wiki/Washington_Park_Subdivision" },
      ],
    },
  ],
};
