import type { WalkTour } from "./walk-types";

// ------------------------------------------------------------------
// Walk Columbia and West Harlem. Six stops on the ridge of Morningside
// Heights and in the West Harlem blocks below it, from the year
// Columbia arrived to the year residents opened a park on the river.
// No detours. Every stop is a place you stand and look at, and each
// one carries more than one decade, because the owner asked for six
// deep stops rather than fourteen thin ones (September 2026).
//
// The narration is edited from the September 2026 research manuscript
// (Walk Columbia and West Harlem, with its Research and Image Guide
// and source register S01 to S50) and widened with the sources listed
// on each stop: Columbia's own historical marker on the 1924 cross
// burning, the Columbia Spectator of April 1924, Columbia's 1968
// exhibition, the 1938 federal appraisal forms on Mapping Inequality,
// the Buell Center's Living in America pamphlet on Morningside Gardens
// and Grant Houses, and the Court of Appeals' opinion in Kaur. Nothing
// in the transcript should outrun those sources, and the manuscript's
// list of distinctions to preserve is followed as written.
//
// The six red plates each explain one mechanism, page-only, never read
// into the audio, in teaching order across the walk: the race question
// on a housing form, the appraisal map, the separate entrance, the
// buffer zone, urban renewal, and the civic project.
//
// Photographs are public domain or open licence only. Audio is
// generated by scripts/walk-tts.mjs --tour west-harlem (OpenAI, voice
// ash); durations.json is the source of audioSeconds.
// ------------------------------------------------------------------

const MEDIA = "/media/west-harlem-walk";

export const WEST_HARLEM_WALK: WalkTour = {
  title: "Walk Columbia and West Harlem",
  dek: "A free, self-guided audio tour from Columbia's gate on Broadway to the Hudson at West Harlem Piers. Six stops over about two and a half miles, on how a university, a church and a city decided what would happen to the ground around them, and how the people living beside them answered.",
  walkMinutes: 54,
  listenMinutes: 25,
  distanceMiles: 2.5,
  startLabel: "Columbia's gate, Broadway at West 116th Street",
  practical: [
    {
      title: "Getting there and timing",
      text: "The walk starts on the public sidewalk outside Columbia's gate at Broadway and West 116th Street, one block from the 116th Street station on the 1 train, and ends in West Harlem Piers Park on the Hudson, about a third of a mile from the 125th Street station on the same line. The stops run roughly in the order the history happened, so the route goes around the campus and down to Morningside Park, back up the ridge to Riverside Church, and then north and west to the river. Plan on about an hour and a half with the stops. Short on time? Stop after Riverside Church, three stops in, and save the housing, Manhattanville and the river for another day.",
    },
    {
      title: "The ground",
      text: "City sidewalks the whole way, about two and a half miles, with real slopes. Morningside Drive runs along the top of a cliff and Broadway drops into the Manhattanville valley north of 122nd Street. The route never needs the park stairways. The longest leg is the climb from the park back up Morningside Drive to 120th Street. The busiest crossings are at 125th Street and 12th Avenue on the way to the river. Use the marked crosswalks and follow any posted pedestrian diversions. The route has not been assessed for wheelchair access.",
    },
    {
      title: "Columbia's campus",
      text: "The main campus behind the gates requires a Columbia ID or approved guest access, and the university's visitor center does not admit walk-in self-guided visits. That was checked in September 2026 and can change. **Nothing on this walk needs you to enter the campus.** The route goes around it on Broadway, 114th Street and Morningside Drive, and every stop is on a public sidewalk or in a public park.",
    },
    {
      title: "Listening",
      text: "Headphones are nicest, but a phone speaker works fine. Every stop's audio is also printed on the page, so you can read instead of listen. If you share your location, it is used only to draw your dot on the map. It never leaves your phone.",
    },
  ],
  route: [
    [40.80790, -73.96372],
    [40.80764, -73.96391],
    [40.80731, -73.96415],
    [40.80736, -73.96426],
    [40.80730, -73.96430],
    [40.80739, -73.96449],
    [40.80743, -73.96458],
    [40.80686, -73.96502],
    [40.80680, -73.96506],
    [40.80671, -73.96485],
    [40.80663, -73.96466],
    [40.80669, -73.96461],
    [40.80638, -73.96384],
    [40.80595, -73.96285],
    [40.80563, -73.96209],
    [40.80554, -73.96187],
    [40.80481, -73.96016],
    [40.80475, -73.96017],
    [40.80471, -73.96008],
    [40.80466, -73.96010],
    [40.80467, -73.96017],
    [40.80469, -73.96020],
    [40.80448, -73.96027],
    [40.80413, -73.96039],
    [40.80409, -73.96029],
    [40.80392, -73.96035],
    [40.80389, -73.96023],
    [40.80393, -73.96021],
    [40.80463, -73.95997],
    [40.80464, -73.95997],
    [40.80533, -73.95973],
    [40.80544, -73.95970],
    [40.80600, -73.95931],
    [40.80603, -73.95942],
    [40.80611, -73.95936],
    [40.80612, -73.95936],
    [40.80619, -73.95930],
    [40.80623, -73.95940],
    [40.80740, -73.95856],
    [40.80803, -73.95809],
    [40.80812, -73.95802],
    [40.80859, -73.95778],
    [40.80871, -73.95772],
    [40.80867, -73.95762],
    [40.80871, -73.95772],
    [40.80879, -73.95767],
    [40.80938, -73.95902],
    [40.80929, -73.95908],
    [40.80934, -73.95921],
    [40.80940, -73.95934],
    [40.80949, -73.95927],
    [40.81000, -73.96049],
    [40.81056, -73.96179],
    [40.81046, -73.96186],
    [40.81054, -73.96206],
    [40.81062, -73.96226],
    [40.81092, -73.96297],
    [40.81095, -73.96306],
    [40.81100, -73.96317],
    [40.81130, -73.96295],
    [40.81223, -73.96225],
    [40.81219, -73.96215],
    [40.81226, -73.96210],
    [40.81192, -73.96131],
    [40.81183, -73.96111],
    [40.81192, -73.96131],
    [40.81379, -73.95994],
    [40.81385, -73.95989],
    [40.81378, -73.95968],
    [40.81371, -73.95948],
    [40.81364, -73.95952],
    [40.81363, -73.95954],
    [40.81356, -73.95924],
    [40.81283, -73.95749],
    [40.81261, -73.95700],
    [40.81257, -73.95686],
    [40.81262, -73.95682],
    [40.81268, -73.95695],
    [40.81263, -73.95699],
    [40.81297, -73.95675],
    [40.81337, -73.95645],
    [40.81349, -73.95636],
    [40.81338, -73.95627],
    [40.81350, -73.95618],
    [40.81516, -73.95764],
    [40.81566, -73.95807],
    [40.81554, -73.95815],
    [40.81552, -73.95812],
    [40.81554, -73.95815],
    [40.81618, -73.95766],
    [40.81624, -73.95762],
    [40.81622, -73.95757],
    [40.81624, -73.95762],
    [40.81633, -73.95757],
    [40.81642, -73.95790],
    [40.81644, -73.95797],
    [40.81647, -73.95799],
    [40.81598, -73.95836],
    [40.81580, -73.95819],
    [40.81566, -73.95807],
    [40.81554, -73.95815],
    [40.81552, -73.95812],
    [40.81554, -73.95815],
    [40.81541, -73.95824],
    [40.81563, -73.95843],
    [40.81577, -73.95856],
    [40.81699, -73.95960],
    [40.81741, -73.96060],
    [40.81747, -73.96075],
    [40.81754, -73.96072],
    [40.81766, -73.96102],
    [40.81769, -73.96110],
    [40.81765, -73.96117],
    [40.81793, -73.96184],
    [40.81798, -73.96194],
    [40.81798, -73.96196],
    [40.81816, -73.96182],
    [40.81820, -73.96180],
  ],
  stops: [
    {
      id: "furnald-hall",
      number: 1,
      title: "Furnald Hall",
      dek: "Columbia built its campus above the street in 1897. In 1924 a Black law student kept his room in this dormitory after a cross was burned on the lawn",
      mapLabel: "Furnald Hall",
      lat: 40.807895,
      lng: -73.963723,
      audioSrc: `${MEDIA}/audio/furnald-hall.mp3`,
      audioSeconds: 211,
      lookFor: "The east sidewalk of Broadway at West 116th Street, outside Columbia's main gate. Furnald Hall is the brick dormitory just inside the wall on the south side of the gate. Keep the entrance clear. No campus entry is required.",
      transcript: [
        "Stand on the east side of Broadway at 116th Street, outside Columbia's main gate, and look through it. The building with the dome at the top of the steps is Low Library. You do not need to go in. When this tour was written, in September 2026, the campus required a Columbia ID to get past the gate, so this whole walk stays on public sidewalks. Now look at the brick building just inside the wall on the south side of the gate. That is Furnald Hall, a dormitory. It opened in 1913, and Columbia still houses first-year students in it.",
        "**Columbia moved up here in 1897.** Before that it was in midtown, at Madison Avenue and 49th Street, and it had run out of room. **The university bought eighteen acres on this ridge, the site of the old Bloomingdale Asylum**, and hired McKim, Mead and White to lay out a new campus. Seth Low was president, and in 1895 he gave a million dollars for the library. The guide Columbia printed the year it moved explains something you can see from here. The builders dug out a court along 116th Street and used the earth to raise the ground behind the library, so that people passing on the street would look up at the campus. **It was designed from the start to be looked up at.** Most of this walk is about what the institutions on this ridge decided for the neighborhoods below it, and what the people down there did back.",
        "The first fight over who could live where happened inside these walls. **On March 5, 1924, Frederick W. Wells, a Black law student, moved into room 528 in Furnald Hall.** Some of the white residents wanted him out. The chairman of the hall's building committee, a student named Rucker, went to Herbert Hawkes, the dean in charge of the residence halls, and asked him to expel Wells. **Hawkes refused.** Rucker told him, according to the dean's own account, that he would give the university some publicity and see how it liked that.",
        "**Shortly after midnight on April 3, a cross was burned on South Field**, the lawn behind this building. Accounts of who carried it, and how tall it was, do not agree, and Columbia's historical account says there does not appear to have been any formal investigation. The next morning Wells found a threatening letter that had been slipped under his door. **He stayed in his room.**",
        "The reaction on campus went the other way from what Rucker expected. The Columbia Spectator reported the cross burning that morning. The day after, it reported that 150 residents of Furnald had signed a statement condemning the hall committee. Several members of the committee resigned. **The NAACP wrote to Wells to praise, in its words, the manly stand he had taken**, and his papers at the Schomburg Center hold 61 letters of support, from organizations and from strangers, Black and white. Wells finished the term in Furnald. He later worked on housing issues in California and New York.",
        "The dean protected one student's right to his room. The university's answer to the larger question was different. **In 1925, the year after the cross, Columbia's residence-hall applications began asking students to state their race.** Officials said it helped them group residents who would get along. Wells had kept his room. Every Black applicant after him filled in a form that recorded his race before anyone decided where he would live.",
        "The next stop is the top of Morningside Park, on the far side of the campus. Since you cannot cut through, the route goes around by 114th Street.",
      ],
      images: [
        {
          src: `${MEDIA}/columbia-campus-1897-library.jpg`,
          alt: "An engraved architectural view of Low Library, a domed building fronted by a row of columns, standing above a broad flight of steps, with small figures, lamp standards and young trees in the foreground and the words THE LIBRARY printed beneath",
          credit:
            "Low Library as Columbia presented it in the guide it published the year it moved. Columbia University, 1897 (New York, A. G. Bushnell), page 7. Avery Architectural and Fine Arts Library, Columbia University, via the Internet Archive. Public domain.",
          label: "1897",
          after: 2,
        },
        {
          src: `${MEDIA}/columbia-campus-1897-detroit.jpg`,
          alt: "A black and white photograph of the new Columbia campus from a distance, with Low Library's dome above long brick blocks, open ground and scattered buildings around it and the flat rooftops of the city beyond",
          credit:
            "The new campus on the ridge, photographed for the Detroit Publishing Company around 1897, the year of the move. Library of Congress, Prints and Photographs Division, LC-DIG-det-4a08582. No known restrictions on publication.",
          label: "c. 1897",
          after: 2,
        },
        {
          src: `${MEDIA}/columbia-campus-1897-plan.jpg`,
          alt: "The plan of Columbia's site from the 1897 guide, showing the blocks between Riverside Park and Morningside Park with the library and the first buildings drawn in black at the center and the streets numbered around them",
          credit:
            "The site as the university drew it in 1897. The lawn south of the library, later called South Field, is where the cross was burned in 1924. Columbia University, 1897, page 3. Avery Architectural and Fine Arts Library, Columbia University, via the Internet Archive. Public domain.",
          label: "1897",
          after: 3,
        },
        {
          src: `${MEDIA}/furnald-hall-south-lawn.jpg`,
          alt: "South Lawn at Columbia under snow, seen from the top of the Low Library steps, with bare trees, students crossing the paths and Butler Library closing the far end",
          credit:
            "South Field from the library steps. Butler Library, at the far end, was built across the lawn in 1934, ten years after the cross. Photograph by InSapphoWeTrust, October 2011, via Wikimedia Commons. CC BY-SA 2.0.",
          label: "South Field",
          after: 4,
        },
      ],
      nowImage: {
        src: `${MEDIA}/columbia-campus-today.jpg`,
        alt: "Low Library today, its grey dome and columned front above the wide steps, with people sitting and walking on the steps and the lawn in front",
        credit:
          "Low Library today, seen from inside the gate. Photograph by Magpieturtle, February 2025, via Wikimedia Commons. CC BY 4.0.",
        label: "Today",
        after: 5,
      },
      interrupts: [
        {
          title: "The question on the form",
          body: [
            "**In 1925 Columbia added a question about race to its residence-hall application.** The university said the answer helped it group students who would get along. What the question did in practice was turn the objections of white residents into a rule. A dean had refused to move Frederick Wells out. After 1925 nobody had to be moved, because the form sorted people before they arrived.",
            "This is the smallest tool on the walk and the earliest. **It cost nothing, it named no one, and it worked on paper.** Columbia's own historical account records the change and notes that the form pictured in its files, a 1932 college admission form, is a different document from the 1925 housing application.",
          ],
          after: 6,
        },
      ],
      toNext: {
        text: "Walk south on Broadway two blocks, past Furnald Hall, to West 114th Street. Turn left and follow 114th Street east along the bottom of the campus, across Amsterdam Avenue, to Morningside Drive. Turn right and go one block south to West 113th Street. Stop on the park-side sidewalk at the upper entrance to the park. Stay on the drive rather than taking the stairs down.",
        distanceMeters: 817,
        minutes: 11,
      },
      sources: [
        {
          label: "Columbia University Archives, Seth Low (1890 to 1901), the eighteen acres on the site of the Bloomingdale Asylum and the 1897 move",
          url: "https://library.columbia.edu/libraries/rbml/uarchives/resources/presidents/low_seth.html",
        },
        {
          label: "Columbia University Libraries, History of Collections, Seth Low's gift and the opening of Low Library",
          url: "https://library.columbia.edu/about/policies/collection-development/history_of_collections.html",
        },
        {
          label: "Columbia University, 1897 (New York, A. G. Bushnell), the university's guide to the new campus, via the Internet Archive",
          url: "https://archive.org/details/columbiauniversi00colu_0",
        },
        {
          label: "Columbia University and Slavery, historical marker, The 1924 Cross Burning at Columbia (research by Trey Greenough and Thomas Germain), including Wells's move on March 5, the building committee, the dean's account and the 1925 application",
          url: "https://columbiaandslavery.columbia.edu/historical-markers/furnald-hall-cross-burning.html",
        },
        {
          label: "Columbia Spectator, April 3, 1924, Fiery Cross at Night Points to Protest Against Negro",
          url: "https://archive-publications.library.columbia.edu/?a=d&d=cs19240403-01.2.2",
        },
        {
          label: "Columbia Spectator, April 4, 1924, Columbia Residents Did Not Burn Cross, Authorities Believe, with 150 Furnald men signing a statement backing Wells",
          url: "https://archive-publications.library.columbia.edu/?a=q&hs=1&r=1&results=1&txq=Wells+Furnald&dafyq=1924&datyq=1924",
        },
        {
          label: "Schomburg Center for Research in Black Culture, Frederick W. Wells papers, finding aid, the 61 letters of support",
          url: "https://archives.nypl.org/scm/20602",
        },
        {
          label: "Furnald Hall, Wikipedia, the 1913 opening and the dormitory's use today",
          url: "https://en.wikipedia.org/wiki/Furnald_Hall",
        },
        {
          label: "Columbia Public Safety, Morningside campus access levels, checked September 2026",
          url: "https://publicsafety.columbia.edu/content/morningside-campus-access-levels",
        },
      ],
    },
    {
      id: "morningside-park",
      number: 2,
      title: "Morningside Park",
      dek: "In 1938 a federal map drew its line along this cliff. In 1968 Columbia tried to build a gym across it, and Harlem and its students stopped it",
      mapLabel: "Morningside Park",
      lat: 40.803932,
      lng: -73.960211,
      audioSrc: `${MEDIA}/audio/morningside-park.mp3`,
      audioSeconds: 285,
      lookFor: "Park-side sidewalk at Morningside Drive and West 113th Street, at the top of the park. The pond is below. The route does not require the stairs.",
      transcript: [
        "You are at the top of Morningside Park, at 113th Street. Morningside Drive runs along the top of a rock cliff here, and the park is the slope below you. Harlem starts where the slope ends, at Morningside Avenue. Look down for the pond. It is the one flat, bright thing in the park, and it did not exist in 1968. **It sits in a hole that was dug for a building.** Before we get to the building, look at the drop itself, because in 1938 the federal government drew a line on it.",
        "That year the Home Owners' Loan Corporation, a federal agency, sent appraisers through New York to grade neighborhoods for mortgage risk. They colored their maps in four grades, from A in green to D in red, and filled in a form for each area. **The form for the top of this cliff, the area that includes Columbia, describes it as comparatively high ground dropping abruptly from Morningside Drive to the east.** Under occupation it says white collar. Under the heading for Black residents it says No. **The grade was B.** The form for the blocks below you says Largely negro, old tenement houses, lower rental ranges. Under relief families it says many. **The grade was D.** The map put the park inside the higher-rated area and ran the boundary along the base of the hill. After 1938 a family below this cliff trying to buy or repair a home carried a grade the government had given the whole neighborhood, and it was red.",
        "Thirty years later Columbia decided to build across that line. **The university wanted a gymnasium, and it wanted to build it into this slope, on public parkland.** Columbia College would get pools, gyms and squash courts, and the neighborhood would get a smaller recreation center as part of the deal. The state legislature approved the use of the park in 1960, and then the project sat for years. Columbia's 1967 drawing of it, which is in the university archives, shows the plan from the side. Morningside Drive, where you are standing, is at the upper left. **Columbia's users would have walked into the top of the building from up here. At the bottom of the drawing a separate space is marked as the community gymnasium, with its own door facing the lower park, on the Harlem side.** People called it Gym Crow, and the drawing shows why. A mostly white university would get most of a building on public land, and the mostly Black neighborhood next to it would come in through a smaller door at the bottom.",
        "The neighborhood was organizing before the students were. **Suki Terada Ports and Christiane Collins fought the park plan. The West Harlem Community Organization picketed the site.** Construction started in February 1968. **On April 23, students marched down here from a rally on campus and pulled at the construction fence.** A photograph by Steve Ditlea shows them doing it. Then they went back up the hill and into Hamilton Hall, the college building on the Amsterdam Avenue side of the campus, and sat down.",
        "That lasted one night as a mixed group. **Early on April 24, the Black students asked the white students to leave.** There were eighty-six of them, members of the Students' Afro-American Society, and they wanted to run their own occupation and keep their demands clear. The white students went on to take four more buildings. The Black students renamed Hamilton Hall Malcolm X Liberation College and held it for the rest of the week. Their demands were specific. The gym had to stop. Demonstrators had to be protected from punishment. And Columbia had to leave the Institute for Defense Analyses, which did research for the military. Their press statement tied the gym to the fights this neighborhood had already been having. **The administration, by its own account, was afraid that using force on that building would bring a violent reaction from Harlem.**",
        "**In the early hours of April 30 the police came into Hamilton Hall through the tunnels under the campus.** The students inside had decided not to resist and walked out to the vans. Elsewhere on campus that night it was not calm. By morning the police had cleared all five buildings and made 712 arrests. Columbia's president resigned that summer. **The gym was never built. The trustees gave it up in March 1969.** For years the excavation just sat here. When the park was rebuilt, the hole became the pond and the waterfall you are looking at. **The pond is on the site of the gym that residents and students stopped.**",
        "The next stop is back up on the ridge at Riverside Church, and it is the longest climb on the walk.",
      ],
      images: [
        {
          src: `${MEDIA}/morningside-overlook-today.jpg`,
          alt: "The view east from Morningside Drive over the bare trees of Morningside Park to the rooftops and apartment blocks of Harlem below the cliff",
          credit:
            "Harlem from Morningside Drive, across the park, three blocks north of this stop. Photograph by Petri Krohn, March 2005, via Wikimedia Commons. CC BY-SA 3.0.",
          label: "The view",
          after: 1,
        },
        {
          src: `${MEDIA}/morningside-overlook-1938-holc.jpg`,
          alt: "The 1938 Home Owners' Loan Corporation map of upper Manhattan around Morningside Heights, with the ridge colored blue for grade B, the Harlem blocks east of Morningside Park colored red for grade D, and the park itself inside the blue area",
          credit:
            "The federal appraisers' map around the cliff, 1938. Morningside Heights is blue, grade B, and the blocks below the park are red, grade D. Home Owners' Loan Corporation, Residential Security Map of Manhattan, National Archives, scan via Mapping Inequality, University of Richmond. A federal government record, in the public domain.",
          label: "1938",
          after: 2,
        },
        {
          src: `${MEDIA}/morningside-park-1968-helix.jpg`,
          alt: "Coarse newspaper halftone of a dense crowd of young people filling a campus space, some with raised arms, printed above an account of the Columbia revolt",
          credit:
            "The photograph Helix ran above its account of the Columbia revolt, volume 3, number 7, May 9, 1968. No photographer is credited on the page, and the issue is catalogued to Paul Dorpat. Seattle Public Library via the Digital Public Library of America and Wikimedia Commons. No Copyright, United States.",
          label: "1968",
          after: 4,
        },
        {
          src: `${MEDIA}/hamilton-hall-statue.jpg`,
          alt: "The bronze statue of Alexander Hamilton standing on a stone pedestal before the arched doorway of Hamilton Hall, with the building's tall windows above",
          credit:
            "The door of Hamilton Hall, on the Amsterdam Avenue side of the campus. The students who held the building in 1968 walked out past this statue to the police vans. Photograph by Beyond My Ken, 2014, via Wikimedia Commons. CC BY-SA 4.0.",
          label: "Hamilton Hall",
          after: 5,
        },
      ],
      nowImage: {
        src: `${MEDIA}/morningside-park-today.jpg`,
        alt: "A green pond at the foot of a grey rock cliff in Morningside Park, with trees on the slope above the rock and the pond's still water in front",
        credit:
          "The pond and the cliff today, on the site of the gymnasium excavation Columbia abandoned. Photograph by Epicgenius, August 2019, via Wikimedia Commons. CC BY-SA 4.0.",
        label: "Today",
        after: 6,
      },
      interrupts: [
        {
          title: "Redlining",
          body: [
            "**Between 1935 and 1940 the Home Owners' Loan Corporation graded neighborhoods in more than two hundred cities for mortgage risk.** A is green, B blue, C yellow, D red. The appraisers filled in a form for each area, and the forms had a line for the presence of Black residents. On this ridge the answer was No and the grade was B. Below the cliff the answer was Yes and the grade was D. **A red grade meant that lenders and, later, the Federal Housing Administration treated a whole neighborhood as a bad bet, whatever the condition of any one house on it.**",
            "The Chicago walk shows the same maps at work on the South Side. Here the line was easy to draw. The appraisers used the rock. **The two forms describe the same cliff, once as a favorable influence for the people at the top and once as the edge of a district marked red.** Both forms can be read in full at the links under this stop.",
          ],
          after: 2,
        },
        {
          title: "The separate entrance",
          body: [
            "**Columbia's 1967 cross-section put the university's pools and gyms at the top of the building, entered from Morningside Drive, and a smaller community gymnasium at the bottom, entered from the lower park on the Harlem side.** The university facility was meant for Columbia College, which was then a men's college. Barnard students, Teachers College students and Columbia's own graduate students were not part of that intended use. So university and community describe the two parts of the drawing, not two groups with equal access.",
            "A separate door does not need a law. **It only needs a building designed so that two sets of people never use the same entrance**, and a lease that hands public ground to the institution that designed it. The people who called it Gym Crow were describing the drawing, and the drawing is in Columbia's own archive.",
          ],
          after: 3,
        },
      ],
      toNext: {
        text: "Walk north on Morningside Drive, along the top of the park and past the overlook at 116th Street, to West 120th Street. Turn left and walk west along 120th Street, past Teachers College and across Broadway, to Claremont Avenue. Riverside Church is on the corner ahead of you. Stop on the sidewalk near its Claremont Avenue entrance at 81 Claremont.",
        distanceMeters: 1223,
        minutes: 16,
      },
      sources: [
        {
          label: "Mapping Inequality, the HOLC appraisal form for area B7, Cathedral Heights, Manhattan, the block containing Columbia University",
          url: "https://dsl.richmond.edu/panorama/redlining/map/NY/Manhattan/area_descriptions/B7",
        },
        {
          label: "Mapping Inequality, the HOLC appraisal form for area D22, Morningside Avenue, Manhattan, the Harlem blocks below the cliff",
          url: "https://dsl.richmond.edu/panorama/redlining/map/NY/Manhattan/area_descriptions/D22",
        },
        {
          label: "Mapping Inequality, Redlining in New Deal America (Digital Scholarship Lab, University of Richmond), what the Home Owners' Loan Corporation surveys were",
          url: "https://dsl.richmond.edu/panorama/redlining/introduction",
        },
        {
          label: "NYC Landmarks Preservation Commission, Morningside Park Designation Report, LP-2254 (2008), the terrain, the gym chronology and the later pond",
          url: "https://s-media.nyc.gov/agencies/lpc/lp/2254.pdf",
        },
        {
          label: "Columbia University Libraries, 1968 Columbia in Crisis, The Gymnasium",
          url: "https://exhibitions.library.columbia.edu/exhibits/show/1968/causes/gym",
        },
        {
          label: "Columbia University Archives, The New Columbia Gymnasium (1967), the foldout cross-section, Buildings and Grounds Collection, box 8, folder 11",
          url: "https://exhibitions.library.columbia.edu/exhibits/show/1968/item/5520",
        },
        {
          label: "Columbia University Archives, Stop Columbia's Gym Crow (1968), the organizers' circular",
          url: "https://exhibitions.library.columbia.edu/exhibits/show/1968/item/5519",
        },
        {
          label: "Steve Ditlea, photograph of the construction-fence protest, April 23, 1968, Columbia University Libraries exhibition",
          url: "https://exhibitions.library.columbia.edu/exhibits/show/1968/item/5654",
        },
        {
          label: "Columbia University Libraries, 1968 Columbia in Crisis, timeline of the week of April 22, 1968",
          url: "https://exhibitions.library.columbia.edu/exhibits/show/1968/timeline",
        },
        {
          label: "Columbia University Libraries, 1968 Columbia in Crisis, the Students' Afro-American Society and Hamilton Hall",
          url: "https://exhibitions.library.columbia.edu/exhibits/show/1968/protests/sas",
        },
        {
          label: "Press Statement of Black Students in Hamilton Hall, April 1968, Columbia University Archives",
          url: "https://exhibitions.library.columbia.edu/exhibits/show/1968/item/5536",
        },
        {
          label: "Columbia University Libraries, 1968 Columbia in Crisis, the Bust of April 30, 1968, the tunnels and the 712 arrests",
          url: "https://exhibitions.library.columbia.edu/exhibits/show/1968/bust",
        },
        {
          label: "Columbia University Libraries, 1968 Columbia in Crisis, consequences and legacy, the March 1969 abandonment of the gym",
          url: "https://exhibitions.library.columbia.edu/exhibits/show/1968/consequences/legacy",
        },
        {
          label: "Stefan M. Bradley, Harlem vs. Columbia University, Black Student Power in the Late 1960s (University of Illinois Press, 2009)",
          url: "https://books.google.com/books?id=lHd25eE8Z1UC&printsec=frontcover",
        },
        {
          label: "Schomburg Center, Christiane C. Collins papers relating to the West Harlem Coalition for Morningside Park, finding aid",
          url: "https://archives.nypl.org/scm/20875",
        },
      ],
    },
    {
      id: "riverside-church",
      number: 3,
      title: "Riverside Church",
      dek: "A founder of the corporation that set out to hold the ridge apart from Harlem. King spoke here against the war in 1967, and Forman came in 1969 to ask the church to pay",
      mapLabel: "Riverside Church",
      lat: 40.8113,
      lng: -73.962944,
      audioSrc: `${MEDIA}/audio/riverside-church.mp3`,
      audioSeconds: 220,
      lookFor: "Public sidewalk outside Riverside Church, 81 Claremont Avenue, near West 120th Street. The account works from outside. Going in is optional.",
      transcript: [
        "You are outside Riverside Church on Claremont Avenue, and you have just walked through the middle of what people used to call the Acropolis. Union Theological Seminary is across the avenue, Teachers College and Barnard are back along 120th Street, the Jewish Theological Seminary is two blocks up Broadway, and Columbia is a block east. The tower above you is the tallest thing on the ridge. **Riverside opened in 1930. John D. Rockefeller Jr. paid for most of it and Harry Emerson Fosdick was its first pastor.** The founders wanted a congregation open to people of every denomination, race and nationality. That was the idea.",
        "The church was also a landlord and a planner. **In 1947 David Rockefeller joined with fourteen local institutions, Columbia and Barnard among them, to form a corporation called Morningside Heights, Incorporated**, and Riverside was one of its leaders. The corporation's job was to plan the neighborhood's future. **A Columbia exhibition pamphlet states its aim in one sentence. It was to separate Morningside Heights from Harlem by means of social, demographic and urban planning.** You will stand on what it built at the next stop. So hold both things in your head at once. A church founded to be open to everyone, and a founder of the plan to hold the ridge apart. Both were true, and in this building the argument about that was said out loud twice.",
        "**On April 4, 1967, Martin Luther King Jr. stood in this church and gave the speech called Beyond Vietnam.** An interfaith group, Clergy and Laymen Concerned About Vietnam, had arranged it. King said the war was eating the money that should have gone to fighting poverty at home. He said Black and white young men were being sent to fight together in Vietnam while they could not go to the same schools or live in the same neighborhoods here. He asked his listeners to think about what the war looked like to the Vietnamese. **Major newspapers condemned the speech, and so did some of his allies in the movement.** He gave it here on purpose, in a church with money and a name, to make the argument as public as he could.",
        "Two years later the demand came to the church itself. **On May 4, 1969, James Forman walked into Sunday worship here and read the Black Manifesto.** It had been adopted the week before at the National Black Economic Development Conference in Detroit. It asked white churches and Jewish synagogues across the country for five hundred million dollars in reparations, to fund a land bank, publishing houses and a university under Black control. It said religious institutions had profited from the exploitation of Black people and owed the money. It also said confrontation and force were on the table.",
        "**The organ played over him. The minister led the congregation out.** Riverside did not pay Forman or the conference. Instead it set up its own Fund for Social Justice, with a goal of four hundred and fifty thousand dollars over three years, and kept control of the grants. **Forman had asked for money that Black-led institutions would control. The church chose to give money it would control itself.** That difference is the whole argument, and it did not go away when the fund was set up.",
        "The next stop is up Claremont and Broadway to La Salle Street, to the housing the corporation built. On the way you cross 122nd Street, which the corporation treated as the edge of its ground until it moved that edge itself.",
      ],
      images: [
        {
          src: `${MEDIA}/riverside-church-1930-underhill.jpg`,
          alt: "A black and white photograph of the newly completed Riverside Church, its tall Gothic tower rising above the nave, seen from the street with apartment buildings alongside",
          credit:
            "Riverside Church the year it opened. Photograph by Irving Underhill, 1930. Library of Congress, Prints and Photographs Division. No known restrictions on publication.",
          label: "1930",
          after: 1,
        },
        {
          src: `${MEDIA}/riverside-church-1952-rizzuto.jpg`,
          alt: "A black and white view over rooftops toward the tower of Riverside Church, with Grant's Tomb beyond it and the Hudson River and the Palisades in the distance",
          credit:
            "The tower over Morningside Heights, photographed by Angelo Rizzuto in 1952. Anthony Angel Collection, Library of Congress. No known restrictions on publication.",
          label: "1952",
          after: 1,
        },
        {
          src: `${MEDIA}/institutions-union-theological.jpg`,
          alt: "The grey Gothic tower and courtyard front of Union Theological Seminary at Broadway and 120th Street, with bare trees and a street lamp in front",
          credit:
            "Union Theological Seminary, across Claremont Avenue from the church, one of the institutions in the corporation. Its architects, Allen and Collens, also designed Riverside Church. Photograph by David Merrett, via Wikimedia Commons. CC BY 2.0.",
          label: "Union Theological Seminary",
          after: 2,
        },
        {
          src: `${MEDIA}/riverside-church-1964-king.jpg`,
          alt: "Martin Luther King Jr. speaking with his right hand raised, in a dark suit and tie, beside a lectern with a microphone",
          credit:
            "Martin Luther King Jr. in New York in 1964, three years before he spoke here. Photograph by Dick DeMarsico for the New York World-Telegram and Sun, Library of Congress. No known restrictions on publication.",
          label: "1964",
          after: 3,
        },
      ],
      nowImage: {
        src: `${MEDIA}/riverside-church-today.jpg`,
        alt: "The stone tower of Riverside Church rising against a blue sky, lit by low sun, with the church's Gothic windows and buttresses below",
        credit:
          "Riverside Church today. Photograph by PortableNYCTours, July 2019, via Wikimedia Commons. CC BY-SA 4.0.",
        label: "Today",
        after: 5,
      },
      interrupts: [
        {
          title: "The buffer zone",
          body: [
            "**Morningside Heights, Incorporated called its method horizontal restrictions.** A Columbia exhibition pamphlet, Living in America, describes them as buffer zones formed by establishing nonprofit institutions and racially integrated middle-class housing in the area, in place of the zoning techniques of the prewar years. The corporation, led by Columbia, Riverside Church and the Rockefeller family, said plainly that its aim was to separate Morningside Heights from Harlem.",
            "The advice came from Chicago. **In 1946 Wilbur Munnecke, a vice president of the University of Chicago, told the institutions here not to use racial restrictive covenants, and to use publicly assisted rebuilding instead, which would bring in the residents they wanted.** No one wrote race into a deed. They cleared blocks and put up apartments on financial terms, and the terms did the sorting. The University of Chicago's own commission did the same work in Hyde Park a few years later, and the Chicago walk follows what it cleared.",
          ],
          after: 2,
        },
      ],
      toNext: {
        text: "Walk north on Claremont Avenue to West 122nd Street and turn right to Broadway. Turn left and follow Broadway north, downhill under the apartment towers, to La Salle Street. Turn right onto La Salle Street and walk between the Morningside Gardens towers to Amsterdam Avenue. Stop at the corner, on the Gardens side, with General Grant Houses across the avenue.",
        distanceMeters: 828,
        minutes: 11,
      },
      sources: [
        {
          label: "Matthew A. Postal, The Riverside Church Designation Report, LP-2037, NYC Landmarks Preservation Commission (May 16, 2000)",
          url: "https://s-media.nyc.gov/agencies/lpc/lp/2037.pdf",
        },
        {
          label: "Wallach Art Gallery and Temple Hoyne Buell Center, Living in America, Frank Lloyd Wright, Harlem and Modern Housing (Columbia University, 2017), pages 31 and 35, Morningside Heights, Inc., its leaders, its aim and its horizontal restrictions",
          url: "https://buellcenter.columbia.edu/sites/default/files/2023-02/Living%20In%20America%20Full%20Pamphlet.pdf",
        },
        {
          label: "Morningside Gardens, History, David Rockefeller and the fourteen institutions in 1947",
          url: "https://www.morningsidegardens.com/history",
        },
        {
          label: "Samuel Zipp, Manhattan Projects, The Rise and Fall of Urban Renewal in Cold War New York (Oxford University Press, 2010), pages 166 to 169, and notes 18 to 21 on page 405 for Wilbur Munnecke's 1946 reports",
          url: "https://books.google.com/books?vid=ISBN9780195328745",
        },
        {
          label: "Columbia Rare Book and Manuscript Library, Morningside Area Alliance records, finding aid",
          url: "https://findingaids.library.columbia.edu/pdf/cul-4412857.pdf",
        },
        {
          label: "Martin Luther King, Jr. Research and Education Institute, Stanford University, Beyond Vietnam",
          url: "https://kinginstitute.stanford.edu/encyclopedia/beyond-vietnam",
        },
        {
          label: "Martin Luther King Jr., Beyond Vietnam, A Time to Break Silence, April 4, 1967, transcript hosted by Civil Rights Movement Veterans",
          url: "https://www.crmvet.org/docs/mlk-viet.htm",
        },
        {
          label: "King Institute, Clergy and Laymen Concerned About Vietnam (CALCAV)",
          url: "https://kinginstitute.stanford.edu/clergy-and-laymen-concerned-about-vietnam-calcav",
        },
        {
          label: "The Riverside Church, The Black Manifesto at The Riverside Church, the church's account and timeline",
          url: "https://www.trcnyc.org/blackmanifesto/",
        },
        {
          label: "James Forman, Black Manifesto, adopted by the National Black Economic Development Conference, April 26, 1969, scan hosted by Riverside Church",
          url: "https://www.trcnyc.org/wp-content/uploads/2019/04/Black-Manifesto1.pdf",
        },
      ],
    },
    {
      id: "gardens-grant",
      number: 4,
      title: "Morningside Gardens and Grant Houses",
      dek: "Two blocks of tenements became a cooperative most of their families could not afford, and public housing across the avenue",
      mapLabel: "Gardens & Grant Houses",
      lat: 40.81264,
      lng: -73.957,
      audioSrc: `${MEDIA}/audio/gardens-grant.mp3`,
      audioSeconds: 313,
      lookFor: "Public sidewalk at the corner of Amsterdam Avenue and La Salle Street, on the Morningside Gardens side. The six Gardens towers are west of Amsterdam, and the red brick towers of General Grant Houses are across the avenue. Keep residential entrances clear.",
      transcript: [
        "Stand at the corner of Amsterdam Avenue and La Salle Street and turn around once. Behind you, along La Salle toward Broadway, are the six towers of Morningside Gardens. Across the avenue are the red brick towers of General Grant Houses. **This is the buffer the corporation on the ridge drew up.** It is also what Wilbur Munnecke, a vice president of the University of Chicago, told the institutions to build when he came to advise them in 1946. He said not to write race into deeds, and to use publicly assisted rebuilding instead, which would bring in the residents they wanted. Gardens was built as a middle-income cooperative. Families bought shares and paid a monthly charge. Grant Houses was built by the city's Housing Authority as public housing. Both opened in 1957, and they were planned as one thing.",
        "First, what was here. **The two blocks the cooperative stands on held 1,626 families in dozens of tenements.** They were Black, Puerto Rican, white, Japanese and Chinese. On the 1938 appraisal map you saw at the park, these blocks were red. Under Title I of the federal Housing Act of 1949, the government could buy a site like this, clear it, and sell it to a private sponsor at a reduced price. Robert Moses's committee on slum clearance funded the plan in 1951. The city's brochure for the project showed these blocks from the rooftops, which is a good angle if you want people to see a slum and not the families inside.",
        "The families organized. **A group called the Save Our Homes Committee fought the clearance, and Elizabeth Barker was one of its leaders.** A 1953 report in the National Guardian described an early meeting at a Japanese restaurant on Broadway, where residents pooled money and wrote a petition asking one question. What happens to us when our homes come down? A week later a resident named Margaret Lamont wrote to the paper to say the report was one-sided and that the neighborhood needed the public housing the plan promised. **They were arguing about how to get a better home, not only about whether the wrecking should go ahead.** The wrecking went ahead. Construction started in 1954.",
        "**The first families moved into 80 La Salle Street in June 1957.** By 1958 all six towers were full, about 980 families. Black and white families lived here together, and that was real. So was the price. The historian Hilary Ballon records a purchase payment of 750 dollars a room and a charge of 21 dollars a month a room. **For a four-room apartment that is 3,000 dollars down and 84 dollars a month, in 1957 dollars.** A family that had lived on this block and could not raise 3,000 dollars did not come back, whatever its race. A Columbia exhibition pamphlet gives the opening figures. Three quarters of the first residents were white, a fifth Black, four percent Asian and one percent Puerto Rican, and about a third of the apartments were set aside for the sponsoring institutions to allocate. **The historian Samuel Zipp describes managers recruiting white and Asian applicants and trying to hold Black occupancy near twenty percent**, because they were afraid more Black residents would keep white applicants away. The integration was managed around what white families would accept.",
        "Now look across the avenue. **Nearly two thirds of the institutions in the corporation pushed for Grant Houses**, the pamphlet says, and they used the public housing here to win support for the whole plan at the city and in Washington. Federal housing officials called it visible evidence of the highest and best use of public housing in an overall plan for the reclamation of an entire neighborhood. At twenty-one stories it was the tallest project the Housing Authority had built. **Its architects, Eggers and Higgins, went on to draw the gymnasium in Morningside Park, the one with the separate door.** The people who planned this avenue and the people who planned that gym were largely the same people. And building public housing next to the cooperative did not mean the families cleared from either site got an apartment in either one.",
        "One of the people who lived in the Gardens was Antonia Pantoja, a Black Puerto Rican educator. **She lived at 70 La Salle Street, on this block, from the late 1950s until early 1969.** She held meetings of the Puerto Rican Association for Community Affairs in her living room, became the first director of ASPIRA, which supports Puerto Rican young people through education and leadership, and taught at Columbia's School of Social Work. In 1996 she received the Presidential Medal of Freedom. And one resident of Grant Houses will come back at the end of the walk. Sarah Martin, of the tenants association there, helped plan the park on the river where this tour ends.",
        "The next stop is north up Amsterdam to 125th Street and then down Broadway into the valley, to Columbia's new campus.",
      ],
      images: [
        {
          src: `${MEDIA}/gardens-grant-1955-bromley.jpg`,
          alt: "A colored land-book plate showing the blocks between Broadway, Amsterdam Avenue, La Salle Street and West 123rd Street, with the long pink outlines of the Morningside Gardens towers labeled MORNINGSIDE GARDENS, the angled towers of GEN. GRANT HOUSES (Section 1) above La Salle Street, and the small lots of the older streets between Broadway and Riverside Drive at the left",
          credit:
            "The two developments drawn side by side while they were still being built. G. W. Bromley and Company, Manhattan Land Book of the City of New York, 1955, plate 138. New York Public Library, via Wikimedia Commons. Public domain.",
          label: "1955",
          after: 1,
        },
        {
          src: `${MEDIA}/gardens-grant-1978-haer.jpg`,
          alt: "A black and white photograph along the elevated platform of the 125th Street subway station, with the tracks running away toward the tall towers of Grant Houses beyond",
          credit:
            "Grant Houses from the 125th Street station platform. Historic American Engineering Record survey of the Interborough Rapid Transit subway, HAER NY,31-NEYO,86-30, Library of Congress. Public domain.",
          label: "After 1968",
          after: 5,
        },
        {
          src: `${MEDIA}/morningside-gardens-1996-pantoja.jpg`,
          alt: "Antonia Pantoja, an older woman with short grey hair, dark earrings and a patterned jacket, seated in the East Room of the White House and smiling to her left",
          credit:
            "Antonia Pantoja in the East Room of the White House on September 9, 1996, as her citation for the Presidential Medal of Freedom was read. Frame from the White House Television Office recording, Clinton Presidential Library, National Archives, NAID 523731141. Public domain as a work of the United States government.",
          label: "1996",
          after: 6,
        },
      ],
      nowImage: {
        src: `${MEDIA}/gardens-grant-today.jpg`,
        alt: "Two tall red brick towers of General Grant Houses against a grey sky, with trees at their base",
        credit:
          "General Grant Houses today. Photograph by Kidfly182, May 2022, via Wikimedia Commons. CC BY-SA 4.0.",
        label: "Today",
        after: 5,
      },
      interrupts: [
        {
          title: "Urban renewal",
          body: [
            "**Title I of the Housing Act of 1949 let a city buy a neighborhood it had declared a slum, clear it with federal help, and sell the land at a discount to a private sponsor who promised something better.** Here the sponsor was the corporation of institutions on the ridge, the site was two blocks holding 1,626 families, and the something better was a cooperative most of those families could not afford. Building public housing next door did not mean the people cleared from either site were rehoused there. Title I paid for the clearing. It did not promise anyone a way back.",
            "The cooperative terms differ by source and date. **Hilary Ballon records 750 dollars a room down and 21 dollars a month per room. The National Guardian reported a 1953 proposal reduced to 625 and 21.** The four-room example in the narration is arithmetic from Ballon's figures, not an identified family's bill. Zipp's account of the preferred Black occupancy level should not be read as a claim that Black families could not live here. Many did, including Antonia Pantoja. It describes who decided how many. The Chicago walk covers the same law at work in Hyde Park, where the university's commission cleared about four thousand families.",
          ],
          after: 4,
        },
      ],
      toNext: {
        text: "Walk north on Amsterdam Avenue to West 125th Street. Turn left and walk west on 125th Street to Broadway. At the corner, look west along 125th Street. The white terra cotta building with tall arched windows on the north side of the street is Prentis Hall, the old milk plant. Then turn right and follow Broadway north under the elevated tracks for four blocks to West 129th Street. Stop at the northwest corner, beside the glass building, the Jerome L. Greene Science Center.",
        distanceMeters: 597,
        minutes: 8,
      },
      sources: [
        {
          label: "Wallach Art Gallery and Temple Hoyne Buell Center, Living in America (Columbia University, 2017), pages 31, 35 and 36, the 1,626 families, Title I, the opening figures, the institutions' third of the apartments, and General Grant Houses",
          url: "https://buellcenter.columbia.edu/sites/default/files/2023-02/Living%20In%20America%20Full%20Pamphlet.pdf",
        },
        {
          label: "Morningside Gardens, History, Robert Moses's committee in 1951, construction in 1954, the first residents in June 1957, 980 families by 1958",
          url: "https://www.morningsidegardens.com/history",
        },
        {
          label: "Hilary Ballon, Robert Moses and Urban Renewal, The Title I Program, in Ballon and Kenneth T. Jackson, editors, Robert Moses and the Modern City (W. W. Norton, 2007), the cooperative charges at page 115, note 56",
          url: "https://bpb-us-e1.wpmucdn.com/wp.nyu.edu/dist/f/5822/files/2017/01/BookScanCenter-4.pdf",
        },
        {
          label: "Samuel Zipp, Manhattan Projects (Oxford University Press, 2010), pages 166 to 169 on Wilbur Munnecke's 1946 advice and pages 204 to 208 on the management of the racial balance",
          url: "https://books.google.com/books?vid=ISBN9780195328745",
        },
        {
          label: "Themis Chronopoulos, Robert Moses and the Visual Dimension of Physical Disorder, Journal of Planning History 13, no. 3 (2014), the 1951 clearance brochure's rooftop photograph at figure 11",
          url: "https://cronfa.swan.ac.uk/Record/cronfa30504/Download/0030504-26012017225425.pdf",
        },
        {
          label: "Elmer Bendiner, The Manhattanville Story, National Guardian, New York edition, June 1, 1953, page 1",
          url: "https://www.marxists.org/history/usa/pubs/national-guardian/1953-06-01-5-32-nat-guardian.pdf",
        },
        {
          label: "Margaret F. Lamont, letter, The Manhattanville story, National Guardian, June 8, 1953, page 3",
          url: "https://www.marxists.org/history/usa/pubs/national-guardian/1953-06-08-5-33-nat-guardian.pdf",
        },
        {
          label: "Ronald Lawson, editor, The Tenant Movement in New York City, 1904 to 1984 (Rutgers University Press, 1986), the Save Our Homes chronology at pages 156 to 160",
          url: "https://libcom.org/book/export/html/45862",
        },
        {
          label: "Andrés Santana-Miranda, Antonia Pantoja Residence, NYC LGBTQ Historic Sites Project (July 2024), 70 La Salle Street",
          url: "https://www.nyclgbtsites.org/site/antonia-pantoja-residence/",
        },
        {
          label: "National Archives, President Clinton's Remarks on Presenting the Presidential Medal of Freedom, September 9, 1996, White House Television Office recording, NAID 523731141",
          url: "https://catalog.archives.gov/id/523731141",
        },
        {
          label: "Peggy M. Shepard, Christopher Greaves and Cecil Corbin-Mark, editors, Harlem-on-the-River, Making a Community Vision Real (WE ACT, 2004), the planning credits at pages 38 and 39",
          url: "https://d3n8a8pro7vhmx.cloudfront.net/weact/pages/480/attachments/original/1436983693/Harlem_on_the_River-Making_a_Community_Vision_Real.pdf?1436983693",
        },
      ],
    },
    {
      id: "manhattanville",
      number: 5,
      title: "The Manhattanville campus",
      dek: "A milk plant, a working valley, and seventeen acres taken by the state for a private university",
      mapLabel: "Manhattanville",
      lat: 40.816467,
      lng: -73.957992,
      audioSrc: `${MEDIA}/audio/manhattanville.mp3`,
      audioSeconds: 295,
      lookFor: "Public sidewalk at the northwest corner of Broadway and West 129th Street, beside the Jerome L. Greene Science Center. Keep the corner and the entrance clear.",
      transcript: [
        "You are at Broadway and 129th Street, beside the Jerome L. Greene Science Center, and you have come down off the ridge. This is Manhattanville, the valley between Morningside Heights and Hamilton Heights. The subway runs overhead here because the ground drops. **This corner is where Sheffield Farms kept its horses.** Sheffield was one of the big milk companies in the city. Its processing plant is the white building with the tall arched windows that you saw on 125th Street, just west of Broadway. Milk came in from the country by rail, was pasteurized and bottled there, and went out by horse and wagon. The stable stood right here, on Broadway between 129th and 130th, and held more than a hundred animals and their wagons. At one point Sheffield owned more than a thousand horses, about half as many as it had people. In 1938 the company said it would replace them with trucks, and the Times told its readers that milk horses were doomed. A photograph in the city archives shows the old stable under the elevated tracks. Now the first building of Columbia's new campus stands on the site.",
        "**Columbia bought the milk plant in 1949 and turned it into a university building**, Prentis Hall. That was the same period the corporation on the ridge was planning its buffer, and it was the university's first step down into this valley. For fifty years nothing much followed it. The valley stayed what it had been. In November 1937 the photographer Berenice Abbott stood under the Riverside Drive viaduct at 125th Street and 12th Avenue, where you will walk on the way to the river, and made a picture for her project Changing New York. Her caption lists what she saw. The structure of the viaduct overhead. A storage tank. Cars, pedestrians, meat wholesalers and other businesses. **Milk, meat, storage, garages, a bus depot and a gas station, with public housing on the slope above them. That is the valley a seventeen-acre campus replaced.**",
        "**In the 2000s Columbia proposed that campus across this valley**, with laboratories, academic buildings, public space and shops. The university said it needed room to grow and that the campus would bring jobs and investment. **The local community board, Community Board 9, wrote a plan of its own.** It wanted to keep the industrial businesses that were here, protect the housing people could afford, and grow without pushing anyone out. The two plans went to the city at the same time. A state map from December 2008 shows how much of the site Columbia already controlled, alongside city land, Con Edison land and a few holdouts. There were still homes and businesses here. The state's plan at that point expected to relocate 298 people from about 135 apartments. Those were planning figures, not a count of who actually moved.",
        "Some owners would not sell. **A gas station owner named Parminder Kaur and the Tuck-It-Away storage company, which had buildings in these blocks, took the state to court.** The state was using eminent domain, its power to take private property for a public use, to clear the last parcels for a private university. In 2010 New York's highest court ruled for the state, and the red plate on this stop explains how. Across Broadway, behind you, the Manhattanville Houses are public housing from 1961, six towers with 1,272 apartments. Their tenants were the campus's closest neighbors through all of it.",
        "There was also a signed agreement. **In 2009 Columbia committed to a 76 million dollar benefits fund for the community, 20 million for affordable housing and up to 4 million for legal help with housing.** Those numbers say what the university promised. They do not say what any one family got. For two families the record is clearer. Hilda Muentes and Luisa Henriquez lived in a building on West 132nd Street that the city had taken for unpaid taxes in 1978, and the tenants there had spent decades trying to buy it as a cooperative. **Columbia built them a replacement building at Broadway and 148th Street. Nineteen families moved in December 2016, and in April 2018 they became owners.** They got what they had wanted, in a different building, sixteen blocks north.",
        "The last stop is back down at 125th Street and out to the river, under the viaduct where Abbott stood.",
      ],
      images: [
        {
          src: `${MEDIA}/manhattanville-sheffield-plant-2008.jpg`,
          alt: "A white terra cotta industrial building on West 125th Street with tall arched windows, the former Sheffield Farms milk plant, now Prentis Hall, with a red brick building beside it",
          credit:
            "The former Sheffield Farms plant on West 125th Street, now Columbia's Prentis Hall. Photograph by Paul Lowry, April 2008, via Wikimedia Commons. CC BY 2.0.",
          label: "Prentis Hall",
          after: 1,
        },
        {
          src: `${MEDIA}/manhattanville-1937-abbott.jpg`,
          alt: "A black and white photograph beneath the Riverside Drive viaduct at 125th Street and 12th Avenue, its steel structure overhead, with a storage tank at the right, parked cars, pedestrians and the signs of meat wholesalers and other businesses below",
          credit:
            "Under the Riverside Drive viaduct at 125th Street and 12th Avenue, in the working district the campus later replaced. Photograph by Berenice Abbott, November 10, 1937, for Changing New York. New York Public Library, via Wikimedia Commons. Public domain.",
          label: "1937",
          after: 2,
        },
        {
          src: `${MEDIA}/manhattanville-2018-construction.jpg`,
          alt: "The Manhattanville campus under construction, seen from the viaduct, with cranes, excavations and new glass buildings rising among older brick blocks and the elevated subway",
          credit:
            "The campus under construction, seen from the Riverside Drive viaduct. Photograph by Jim.henderson, April 2018, via Wikimedia Commons. CC BY-SA 4.0.",
          label: "2018",
          after: 3,
        },
        {
          src: `${MEDIA}/manhattanville-houses-today.jpg`,
          alt: "The tall red brick towers of the Manhattanville Houses public housing development, with trees and parked cars along the street below",
          credit:
            "Manhattanville Houses, across Broadway from the new campus. Photograph by Jim.henderson, March 2023, via Wikimedia Commons. CC BY-SA 4.0.",
          label: "Manhattanville Houses",
          after: 4,
        },
      ],
      nowImage: {
        src: `${MEDIA}/manhattanville-today.jpg`,
        alt: "The Jerome L. Greene Science Center, a long glass building with a grid of pale mullions, at the corner of Broadway with the elevated subway structure beside it",
        credit:
          "The Jerome L. Greene Science Center on the stable's site today. Photograph by ajay_suresh, June 2021, via Wikimedia Commons. CC BY 2.0.",
        label: "Today",
        after: 5,
      },
      interrupts: [
        {
          title: "The civic project",
          body: [
            "**Eminent domain lets government take private property for a public use, with compensation.** In Manhattanville the state's development agency did the taking and a private university got the land. New York's highest court upheld it in 2010, in Kaur against the New York State Urban Development Corporation, on two separate grounds. As a land use improvement project, which requires a finding that the area is blighted. And as a civic project, which the statute defines as providing facilities for educational, cultural or other civic purposes, and which needs no finding of blight at all.",
            "**The court said the agency was entitled to use eminent domain for a civic project whether or not the site was blighted.** So the argument over whether Manhattanville was really a slum, which the holdouts had won in the lower court, did not decide the case. The seventeen-acre campus is distinct from the thirty-five-acre rezoning around it. The 298 people and 135 apartments are the December 2008 planning figures. The people who sued owned a gas station and storage businesses, not family homes.",
          ],
          after: 4,
        },
      ],
      toNext: {
        text: "Walk south on Broadway to West 125th Street. Turn right and follow 125th Street west toward the river, under the elevated station and then under the steel arch of the Riverside Drive viaduct at 12th Avenue. The street becomes St. Clair Place. Use the marked crossings at 12th Avenue and Marginal Street to enter West Harlem Piers Park. Stop beside the walking path, clear of bicycle traffic.",
        distanceMeters: 620,
        minutes: 8,
      },
      sources: [
        {
          label: "Columbia University Libraries and Facilities, Sheffield Farms exhibition, Chapter 3, Manhattanville Transforms, the plant, the stable on Broadway between 129th and 130th, the horses and the 1949 purchase",
          url: "https://sheffieldfarms.neighbors.columbia.edu/content/chapter-3-manhattanville-transforms",
        },
        {
          label: "New York Public Library, Berenice Abbott, Under Riverside Drive Viaduct, 125th Street at 12th Avenue, November 10, 1937, with her caption",
          url: "https://digitalcollections.nypl.org/items/510d47d9-4eaa-a3d9-e040-e00a18064a99",
        },
        {
          label: "Manhattan Community Board 9, 197-a Plan, Hamilton Heights, Manhattanville, Morningside Heights (adopted with modifications, 2007)",
          url: "https://www.nyc.gov/assets/planning/download/pdf/community/197a-plans/mn9_hamilton_manhattanville_197a.pdf",
        },
        {
          label: "New York State Urban Development Corporation, Manhattanville in West Harlem, Modified General Project Plan (December 18, 2008), relocation at pages 27 to 33 and the ownership map at Exhibit B",
          url: "https://esd.ny.gov/sites/default/files/media/document/2008-12-18-CUMV-Modified%20General-Project-Plan-with-Exhibits.pdf",
        },
        {
          label: "Matter of Kaur v. New York State Urban Development Corp., 15 NY3d 235, New York Court of Appeals (June 24, 2010), the land use improvement project, the civic project, the petitioners and the 17 acres",
          url: "https://www.nycourts.gov/reporter/3dseries/2010/2010_05601.htm",
        },
        {
          label: "West Harlem Community Benefits Agreement, West Harlem Local Development Corporation and the Trustees of Columbia University (May 18, 2009), the funding provisions at pages 8 to 11",
          url: "https://climate.law.columbia.edu/sites/default/files/content/CBAs/West%20Harlem%20-%20Columbia%20CBA.pdf",
        },
        {
          label: "Columbia University, Manhattanville Implementation Plan Report, Residential Relocation Obligations (October 15, 2025), including the 2016 newspaper report and the April 2018 announcement",
          url: "https://neighbors.columbia.edu/sites/neighbors.columbia.edu/files/content/Reporting/2025%20ESD%20Reporting/2025%20-%205.05%28b%29%28i%29%20Residential%20Relocation%20Obligations.pdf",
        },
        {
          label: "Josh Barbanel, A Long Journey to Ownership Nears Its Goal, The Wall Street Journal, February 17, 2016",
          url: "https://www.wsj.com/articles/a-long-journey-to-ownership-nears-its-goal-1455755210",
        },
        {
          label: "Manhattanville Houses, Wikipedia, citing the New York Times on the six twenty-story buildings and 1,272 apartments completed in 1961",
          url: "https://en.wikipedia.org/wiki/Manhattanville_Houses",
        },
      ],
    },
    {
      id: "west-harlem-piers",
      number: 6,
      title: "West Harlem Piers Park",
      dek: "The neighborhood turned down a hotel and drew its own park",
      mapLabel: "Harlem Piers",
      lat: 40.818198,
      lng: -73.961796,
      audioSrc: `${MEDIA}/audio/west-harlem-piers.mp3`,
      audioSeconds: 157,
      lookFor: "West Harlem Piers Park, near the entrance at West 125th Street, St. Clair Place and Marginal Street. Choose a place beside the walking path, away from bicycle traffic.",
      transcript: [
        "You are in West Harlem Piers Park, on the Hudson, and you have just walked under the steel arch that carries Riverside Drive across the valley. Abbott made her photograph under that arch in 1937, and eleven years before her an aerial photographer caught this shore from above, with the 125th Street ferry landing where the park is now. **The park opened on May 30, 2009. Before that it was a parking lot.** Now it is two acres of paths, plantings and two piers, one for boats and one for fishing.",
        "**In 1998 the city asked developers what they would build here, and got two answers, a thirty-three-story hotel and a six-story motel.** A neighborhood group, WE ACT for Environmental Justice, had been arguing for years that Black and Latino neighborhoods like this one got the city's pollution and none of its waterfront. By WE ACT's own account, the organizing here persuaded the city to pick neither building. **Then WE ACT and Community Board 9 held public meetings and a design workshop and drew up a plan of their own, called Harlem-on-the-River.** Their booklet has a photograph of the workshop. People standing around a big map, deciding where the paths should go.",
        "The plan wanted open space, room for boats, and a path for walking and cycling that ran along the river without breaking. In 2001 the city funded a formal planning process that started from the neighborhood's work. Building the park took city, state and federal money. **The plan of 2004, the approved plan and the park you are standing in are three different things, and not everything the neighborhood drew got built.** But the park was built on their idea and not on the hotel.",
        "The people who did it are people you have met. **The booklet credits Sarah Martin of the Grant Houses Tenants Association and Joan Levine of the Morningside Gardens Residents Association**, along with people from Riverside Church and Columbia. The two developments built fifty years earlier as a buffer sent their tenant leaders to plan a park for everybody. The artist Nari Ward made the sculptures called Voice from the eyelets on a fishing rod, and for the piece called Signage Barriers he collected words from neighbors' memories of this shore.",
        "That is the end of the walk. To get to the 1 train, go back east along 125th Street to Broadway, about a third of a mile. **Every stop on this walk was a decision about land made by an institution, and an answer from the people who lived next to it.** Thank you for walking with us.",
      ],
      images: [
        {
          src: `${MEDIA}/west-harlem-piers-1926-aerial.jpg`,
          alt: "A black and white aerial photograph of the Manhattanville waterfront in 1926, with the 125th Street ferry landing on the Hudson, the viaduct, the elevated railway and the dense blocks of the valley, and the campus and Grant's Tomb on the ridge above",
          credit:
            "The 125th Street ferry landing and the Manhattanville valley from the air in 1926, when the site of this park was a working shore. Via Wikimedia Commons. Public domain, published before 1931.",
          label: "1926",
          after: 1,
        },
        {
          src: `${MEDIA}/west-harlem-piers-1937-abbott.jpg`,
          alt: "A black and white photograph looking along 125th Street beneath the steel arches of the Riverside Drive viaduct toward the river, with trucks, storefronts and a gas station below the structure",
          credit:
            "The way to the river under the viaduct at 12th Avenue, on the path you have just walked. Photograph by Berenice Abbott, November 10, 1937, for Changing New York. New York Public Library, via Wikimedia Commons. Public domain.",
          label: "1937",
          after: 1,
        },
        {
          src: `${MEDIA}/west-harlem-piers-2021.jpg`,
          alt: "Cherry trees in pink bloom beside the walking path in West Harlem Piers Park, with a cyclist on the path, the lawn, and the Hudson River and the Palisades beyond",
          credit:
            "The park in spring. Photograph by Jim.henderson, April 2021, via Wikimedia Commons. CC BY 4.0.",
          label: "2021",
          after: 3,
        },
        {
          src: `${MEDIA}/west-harlem-piers-125th-station-2018.jpg`,
          alt: "The elevated platform of the 125th Street subway station, with its green 125 Street sign, a lamp, the tracks curving away and the red brick towers of Grant Houses in the distance",
          credit:
            "The 125th Street station on the 1 train, the way home. Photograph by Carol M. Highsmith, 2018, Carol M. Highsmith Archive, Library of Congress. No known restrictions on publication.",
          label: "The 1 train",
          after: 5,
        },
      ],
      nowImage: {
        src: `${MEDIA}/west-harlem-piers-today.jpg`,
        alt: "West Harlem Piers Park on a sunny day, with a lawn, lamp standards, the walking path, a low building and the piers reaching into the Hudson",
        credit:
          "West Harlem Piers Park, looking north. Photograph by Jim.henderson, October 2008, via Wikimedia Commons. Public domain.",
        label: "Today",
        after: 2,
      },
      sources: [
        {
          label: "Peggy M. Shepard, Christopher Greaves and Cecil Corbin-Mark, editors, Harlem-on-the-River, Making a Community Vision Real (WE ACT, 2004)",
          url: "https://d3n8a8pro7vhmx.cloudfront.net/weact/pages/480/attachments/original/1436983693/Harlem_on_the_River-Making_a_Community_Vision_Real.pdf?1436983693",
        },
        {
          label: "WE ACT for Environmental Justice, River Currents (May 2009), the opening celebration",
          url: "https://d3n8a8pro7vhmx.cloudfront.net/weact/pages/480/attachments/original/1436983767/River_Currents_Newsletter_May_2009_Vol_1.pdf?1436983767",
        },
        {
          label: "WE ACT for Environmental Justice, West Harlem Piers Park Project, 1998 organizing through the May 30, 2009 opening",
          url: "https://community.weact.org/west-harlem-waterfront-park",
        },
        {
          label: "City of New York, Office of the Mayor, release 244-09, Mayor Bloomberg Joins West Harlem Community to Celebrate Opening of West Harlem Piers Park (May 30, 2009), the park at opening and Nari Ward's works",
          url: "https://www.nyc.gov/html/dcla/downloads/pdf/244-09_West_Harlem_Piers_Park.pdf",
        },
        {
          label: "Riverside Park Conservancy, Riverside Park History, the West Harlem waterfront",
          url: "https://riversideparknyc.org/riverside-park-history/",
        },
      ],
    },
  ],
};
