import type { WalkTour } from "./walk-types";

// ------------------------------------------------------------------
// Walk Columbia and West Harlem. Six stops in Morningside Heights and
// the West Harlem blocks below it, told in the order the decisions
// were made, from the year Columbia arrived on the ridge to the year
// residents opened a park on the river. There are no detours. Every
// stop is a place where an institution decided what would happen to
// the ground around it and the people beside it answered.
//
// The narration is edited from a research manuscript prepared for
// Rooted Forward in September 2026 (Walk Columbia and West Harlem,
// with its Research and Image Guide and source register S01 to S50).
// Nothing in the transcript should outrun the sources printed on each
// stop; the guide's list of distinctions to preserve (Wells, the gym,
// the cooperative costs, the Riverside dates, the Manhattanville
// figures, the waterfront plan) is followed as written. The six red
// plates are the manuscript's printed boxes, page-only, never read
// into the audio.
//
// Photographs are public domain or open licence only. The manuscript's
// reference reproductions from Columbia's archives, WE ACT, CENTRO and
// the Wall Street Journal are not cleared for publication and are not
// used; the narration describes those documents and the sources link
// to them. Audio is generated by scripts/walk-tts.mjs --tour west-harlem
// (OpenAI, voice ash); durations.json is the source of audioSeconds.
// ------------------------------------------------------------------

const MEDIA = "/media/west-harlem-walk";

export const WEST_HARLEM_WALK: WalkTour = {
  title: "Walk Columbia and West Harlem",
  dek: "A free, self-guided audio tour from Columbia's gate on Broadway to the Hudson at West Harlem Piers, told in the order it happened. Six stops over about two and a half miles on how a university, a church and a city decided what would happen to the ground around them, and how the people living beside them answered.",
  walkMinutes: 56,
  listenMinutes: 21,
  distanceMiles: 2.6,
  startLabel: "Columbia's gate, Broadway at West 116th Street",
  practical: [
    {
      title: "Getting there and timing",
      text: "The walk starts on the public sidewalk outside Columbia's gate at Broadway and West 116th Street, one block from the 116th Street station on the 1 train, and ends in West Harlem Piers Park on the Hudson, about a third of a mile from the 125th Street station on the same line. The stops run in the order the history happened, so the route goes down to Morningside Park, back up to La Salle Street and Riverside Church, and then north and west to the river. Plan on an hour and a half to two hours with the stops. Short on time? Stop after Riverside Church, four stops in, and save Manhattanville and the river for another day.",
    },
    {
      title: "The ground",
      text: "City sidewalks the whole way, about two and a half miles, with real slopes. Morningside Drive runs along the top of a cliff and Broadway drops into the Manhattanville valley north of 122nd Street. The route never needs the park stairways; the second stop is at the top of the park, on the sidewalk. The longest leg is the fifteen minutes from the park up to La Salle Street. The busiest crossings are at 125th Street and 12th Avenue on the way to the river; use the marked crosswalks and follow any posted pedestrian diversions. The route has not been assessed for wheelchair access.",
    },
    {
      title: "Columbia's campus",
      text: "The main campus behind the gate requires a Columbia ID or approved guest access, and the university's visitor center does not admit walk-in self-guided visits. That was checked in September 2026 and can change. **Nothing on this walk needs you to enter the campus.** Every stop is on a public sidewalk or in a public park, and the account of the campus works from outside the gate.",
    },
    {
      title: "Listening",
      text: "Headphones are nicest, but a phone speaker works fine. Every stop's audio is also printed on the page, so you can read instead of listen. If you share your location, it is used only to draw your dot on the map. It never leaves your phone.",
    },
  ],
  route: [
    [40.80790, -73.96372],
    [40.80764, -73.96391],
    [40.80731, -73.96415],
    [40.80669, -73.96461],
    [40.80671, -73.96485],
    [40.80669, -73.96461],
    [40.80638, -73.96384],
    [40.80595, -73.96285],
    [40.80563, -73.96209],
    [40.80554, -73.96187],
    [40.80481, -73.96016],
    [40.80465, -73.96004],
    [40.80404, -73.96017],
    [40.80463, -73.95997],
    [40.80533, -73.95973],
    [40.80551, -73.95966],
    [40.80600, -73.95931],
    [40.80619, -73.95930],
    [40.80740, -73.95856],
    [40.80803, -73.95809],
    [40.80859, -73.95778],
    [40.80877, -73.95769],
    [40.80909, -73.95752],
    [40.80938, -73.95737],
    [40.80956, -73.95729],
    [40.80976, -73.95723],
    [40.80994, -73.95726],
    [40.81011, -73.95737],
    [40.81024, -73.95754],
    [40.81051, -73.95820],
    [40.81069, -73.95840],
    [40.81126, -73.95798],
    [40.81191, -73.95751],
    [40.81261, -73.95700],
    [40.81200, -73.95744],
    [40.81138, -73.95789],
    [40.81232, -73.96049],
    [40.81183, -73.96086],
    [40.81183, -73.96111],
    [40.81220, -73.96196],
    [40.81222, -73.96223],
    [40.81130, -73.96295],
    [40.81223, -73.96225],
    [40.81220, -73.96196],
    [40.81192, -73.96131],
    [40.81179, -73.96100],
    [40.81232, -73.96049],
    [40.81363, -73.95954],
    [40.81380, -73.95942],
    [40.81411, -73.95919],
    [40.81442, -73.95896],
    [40.81462, -73.95882],
    [40.81479, -73.95868],
    [40.81502, -73.95852],
    [40.81541, -73.95824],
    [40.81563, -73.95808],
    [40.81580, -73.95819],
    [40.81598, -73.95836],
    [40.81635, -73.95810],
    [40.81598, -73.95836],
    [40.81580, -73.95819],
    [40.81563, -73.95808],
    [40.81542, -73.95823],
    [40.81563, -73.95843],
    [40.81699, -73.95960],
    [40.81741, -73.96060],
    [40.81759, -73.96085],
    [40.81769, -73.96110],
    [40.81793, -73.96184],
    [40.81816, -73.96182],
    [40.81820, -73.96180],
  ],
  stops: [
    {
      id: "columbia-campus",
      number: 1,
      title: "Columbia moves to Morningside Heights",
      dek: "The university built a new campus here in 1897. In 1924, Frederick Wells defended his right to live in one of its dormitories",
      mapLabel: "Columbia",
      lat: 40.807895,
      lng: -73.963723,
      audioSrc: `${MEDIA}/audio/columbia-campus.mp3`,
      audioSeconds: 197,
      lookFor: "Public sidewalk on the east side of Broadway at West 116th Street, outside Columbia's gate. Keep the entrance clear. No campus entry is required.",
      transcript: [
        "Stand on the east side of Broadway at 116th Street, outside Columbia's gate, and look through it. The domed building at the top of the steps is Low Library. You do not need to go in. When this tour was written, in September 2026, the campus required a Columbia ID to enter, so the walk stays on the public sidewalk. **Columbia moved to Morningside Heights in 1897**, leaving its campus at Madison Avenue and 49th Street. **The university bought land formerly occupied by the Bloomingdale Asylum** and commissioned a new campus on it. Its arrival helped make this ridge a district of colleges, seminaries and churches.",
        "The year it moved, Columbia published a guide to the new campus. Its illustration of the library shows Low above a broad flight of steps. **The university had dug out a court along 116th Street and used the earth to raise the ground behind the library.** The guide explained that this arrangement would let people passing on the street see into the campus and would display its buildings above the street. **Seth Low, the university's president, had given one million dollars toward the library in 1895.** His gift let Columbia build on a scale its earlier site could not hold.",
        "The campus also needed housing for students. By 1924, Furnald Hall stood inside the grounds, south of this gate. **That March, Frederick W. Wells, a Black law student, moved into a room there. Some white residents demanded that he leave.** Dean Herbert Hawkes refused to remove him. The threats continued. **Shortly after midnight on April 3, someone burned a cross on South Field, outside the residence halls.** Wells also received letters threatening his life. **He stayed in his room.**",
        "Support reached him from outside the university. James Weldon Johnson, the secretary of the NAACP, sent a telegram offering the organization's help. **Wells's papers at the Schomburg Center preserve 61 supportive letters** from organizations, friends and members of the public, both Black and white. They document a response much wider than the students who had tried to force him out. Wells remained in the dormitory through the term. He later worked on housing issues in California and New York.",
        "Hawkes protected Wells's right to remain. The university's broader response was less decisive. Columbia's own historical account finds no apparent formal investigation of the cross burning. **In 1925, residence-hall applications began asking students to identify their race.** Officials defended the question as a way to group residents who would get along. The race question made white residents' objections a consideration in assigning housing. **Wells had kept his room. Black applicants after him faced a process that recorded their race before deciding where they would live.**",
        "At this first stop, Columbia controlled admission to its own housing. At the next, the dispute concerns land outside its campus, a public park used by the people of Harlem.",
      ],
      images: [
        {
          src: `${MEDIA}/columbia-campus-1897-library.jpg`,
          alt: "An engraved architectural view of Low Library, a domed building fronted by a row of columns, standing above a broad flight of steps, with small figures, lamp standards and young trees in the foreground and the words THE LIBRARY printed beneath",
          credit:
            "Low Library as Columbia presented it in the guide it published the year it moved. Columbia University, 1897 (New York, A. G. Bushnell), page 7. Avery Architectural and Fine Arts Library, Columbia University, via the Internet Archive. Public domain.",
          label: "1897",
          after: 1,
        },
        {
          src: `${MEDIA}/columbia-campus-1897-detroit.jpg`,
          alt: "A black and white photograph of the new Columbia campus from a distance, with Low Library's dome above long brick blocks, open ground and scattered buildings around it and the flat rooftops of the city beyond",
          credit:
            "The new campus on the ridge, photographed for the Detroit Publishing Company around 1897, the year of the move. Library of Congress, Prints and Photographs Division, LC-DIG-det-4a08582. No known restrictions on publication.",
          label: "c. 1897",
          after: 1,
        },
        {
          src: `${MEDIA}/columbia-campus-1897-barnard-view.jpg`,
          alt: "A photograph captioned View from Barnard College, April 15, 1897, showing the long brick blocks of Schermerhorn Hall, the Physics Building, Havemeyer Hall and the Engineering Building rising behind a fence, with bare trees and a path in the foreground",
          credit:
            "The campus under construction on April 15, 1897, from Barnard College. Columbia University, 1897, page 8. Avery Architectural and Fine Arts Library, Columbia University, via the Internet Archive. Public domain.",
          label: "April 1897",
          after: 2,
        },
      ],
      nowImage: {
        src: `${MEDIA}/columbia-campus-today.jpg`,
        alt: "Low Library today, its grey dome and columned front above the wide steps, with people sitting and walking on the steps and the lawn in front",
        credit:
          "Low Library today, seen from inside the gate. Photograph by Magpieturtle, February 2025, via Wikimedia Commons. CC BY 4.0.",
        label: "Today",
        after: 5,
      },
      interrupts: [
        {
          title: "A library with classrooms",
          body: [
            "Columbia's 1897 guide placed the Law School in the library's north wing, with a reading room on the main floor and lecture rooms above. **The building was designed to house both books and the teaching departments that used them.** Frederick Wells, a law student, would have studied in the wing the guide describes.",
          ],
          after: 2,
        },
      ],
      toNext: {
        text: "Walk south on Broadway to West 114th Street. Turn left and continue east across Amsterdam Avenue to Morningside Drive. Turn right and go one block to West 113th Street. Stop on the park-side sidewalk at the upper entrance to the park.",
        distanceMeters: 750,
        minutes: 10,
      },
      sources: [
        {
          label: "Columbia University Archives, Seth Low (1890 to 1901), the Morningside campus and the 1897 move",
          url: "https://library.columbia.edu/libraries/rbml/uarchives/resources/presidents/low_seth.html",
        },
        {
          label: "Columbia University Libraries, History of Collections, Seth Low's gift and the opening of Low Library",
          url: "https://library.columbia.edu/about/policies/collection-development/history_of_collections.html",
        },
        {
          label: "Columbia University, 1897 (New York, A. G. Bushnell), the university's guide to the new campus, via the Internet Archive",
          url: "https://archive.org/details/columbiauniversi00colu_0",
        },
        {
          label: "Columbia University and Slavery, historical marker, The 1924 Cross Burning at Columbia (research by Trey Greenough and Thomas Germain)",
          url: "https://columbiaandslavery.columbia.edu/historical-markers/furnald-hall-cross-burning.html",
        },
        {
          label: "Schomburg Center for Research in Black Culture, Frederick W. Wells papers, finding aid",
          url: "https://archives.nypl.org/scm/20602",
        },
        {
          label: "Columbia Spectator, April 3, 1924, Fiery Cross at Night Points to Protest Against Negro, in the Columbia University Libraries newspaper archive",
          url: "https://archive-publications.library.columbia.edu/?a=d&d=cs19240403-01.2.2",
        },
        {
          label: "Columbia Public Safety, Morningside campus access levels, checked September 2026",
          url: "https://publicsafety.columbia.edu/content/morningside-campus-access-levels",
        },
      ],
    },
    {
      id: "morningside-park",
      number: 2,
      title: "The gym Harlem stopped",
      dek: "Separate entrances and unequal facilities made a proposed Columbia gym a focus of protest",
      mapLabel: "Morningside Park",
      lat: 40.803932,
      lng: -73.960211,
      audioSrc: `${MEDIA}/audio/morningside-park.mp3`,
      audioSeconds: 210,
      lookFor: "Park-side sidewalk at Morningside Drive and West 113th Street, at the top of the park. The pond is below; the main route does not require the stairs.",
      transcript: [
        "You are at the top of Morningside Park, and the ground drops away in front of you. **Morningside Park occupies the steep slope between Morningside Heights and Harlem.** Its exposed rock and sharp fall made it difficult to extend Manhattan's street grid across this ground, so the city reserved the site as a park, with paths and stairs connecting the streets at the top to the streets at the bottom. Look down the slope for the pond. It did not exist in 1968. It sits in a hole that was dug for a building.",
        "**Columbia proposed building a gymnasium into that slope.** The university wanted better athletic facilities for Columbia College and offered a smaller recreation center for neighborhood residents as part of the project. **The state legislature approved the use of parkland in 1960.** Construction was delayed for years.",
        "Columbia's 1967 cross-section drawing, held in the University Archives, shows the plan from the side. Morningside Drive, where you are standing, is at the upper left. From there, Columbia's users would have entered a building containing pools, gyms and squash courts. **Near the bottom, a separate space is labeled as the community gymnasium. Its entrance faces the lower park, on the Harlem side.** Opponents called the project Gym Crow, after Jim Crow segregation. The drawing shows the basis of their objection. **Columbia would receive most of a building on public land, while the surrounding neighborhood would enter a smaller facility from below.**",
        "The plan divided users by college affiliation. **The largely white institution would have the larger share, next to a largely Black neighborhood whose residents had a separate entrance.** Opponents challenged both that arrangement and the transfer of public park space to the university. Local residents had been organizing before the student occupations made national news. **Suki Terada Ports and Christiane Collins fought the park proposal.** Members of the West Harlem Community Organization picketed the site.",
        "**Construction began in February 1968. On April 23, demonstrators left a campus rally and came down to the excavation**, where a photograph by Steve Ditlea shows them pulling at the construction fence. The gym became one of the central demands in the occupations of Columbia buildings that followed. Black and white students initially occupied Hamilton Hall together. Early on April 24, Black students asked the white students to leave. **The Students' Afro-American Society wanted to direct its own occupation** and keep its demands distinct from the less clearly defined aims of the white students led by Students for a Democratic Society.",
        "**The Black students' press statement connected their action to the community's earlier resistance.** Alongside an end to the gym, they demanded protection for demonstrators and an end to Columbia's affiliation with the Institute for Defense Analyses, which conducted research for the military. Their statement placed Harlem's park dispute beside opposition to the university's role in the war effort.",
        "**The gym was never built. Columbia's trustees formally abandoned it in March 1969.** Later park improvements converted the excavated area into the pond and waterfall below you. **The pond occupies the site of the gym that residents and students stopped.**",
      ],
      images: [
        {
          src: `${MEDIA}/morningside-park-1900s-postcard.jpg`,
          alt: "A tinted postcard view looking down over Morningside Park, with the elevated railway station at 110th Street on tall iron legs at the left, the park's lawns and paths below, and rows of apartment houses along the far side",
          credit:
            "Morningside Park and the Ninth Avenue elevated at 110th Street, before the gym was imagined. Detroit Publishing Company postcard number 12453, 1908 to 1909, New York Public Library, via Wikimedia Commons. Public domain.",
          label: "1908 to 1909",
          after: 1,
        },
        {
          src: `${MEDIA}/morningside-park-1968-helix.jpg`,
          alt: "Coarse newspaper halftone of a dense crowd of young people filling a campus space, some with raised arms, printed above an account of the Columbia revolt",
          credit:
            "The photograph Helix ran above its account of the Columbia revolt, volume 3, number 7, May 9, 1968. No photographer is credited on the page, and the issue is catalogued to Paul Dorpat. Seattle Public Library via the Digital Public Library of America and Wikimedia Commons. No Copyright, United States.",
          label: "1968",
          after: 5,
        },
        {
          src: `${MEDIA}/morningside-park-hamilton-hall.jpg`,
          alt: "The stone entrance front of Hamilton Hall, with its arched doorway, tall windows and a bronze statue of Alexander Hamilton on a pedestal before the door",
          credit:
            "Hamilton Hall, where Black and white students first occupied together and where the Students' Afro-American Society then held the building on its own. Photograph by Beyond My Ken, 2014, via Wikimedia Commons. CC BY-SA 4.0.",
          label: "Hamilton Hall",
          after: 6,
        },
      ],
      nowImage: {
        src: `${MEDIA}/morningside-park-today.jpg`,
        alt: "A green pond at the foot of a grey rock cliff in Morningside Park, with trees on the slope above the rock and the pond's still water in front",
        credit:
          "The pond and the cliff today, on the site of the gymnasium excavation Columbia abandoned. Photograph by Epicgenius, August 2019, via Wikimedia Commons. CC BY-SA 4.0.",
        label: "Today",
        after: 7,
      },
      interrupts: [
        {
          title: "Who would use the gym?",
          body: [
            "**The large university facility was intended for Columbia College, then a men's undergraduate college.** Graduate and professional students, Barnard students and Teachers College students were excluded from that intended use. \"University\" and \"community\" therefore describe the two parts of the drawing, not an offer of equal access to everyone enrolled at Columbia.",
          ],
          after: 3,
        },
      ],
      toNext: {
        text: "Continue north on Morningside Drive, along the top of the park, to West 122nd Street. Turn left to Amsterdam Avenue, then right and continue north to La Salle Street. Stop beside the intersection, where you can compare the housing on the two sides of Amsterdam Avenue. Stay on the streets rather than taking the park stairways.",
        distanceMeters: 1128,
        minutes: 15,
      },
      sources: [
        {
          label: "NYC Landmarks Preservation Commission, Morningside Park Designation Report, LP-2254 (2008), terrain, the gym chronology and the later pond",
          url: "https://s-media.nyc.gov/agencies/lpc/lp/2254.pdf",
        },
        {
          label: "Columbia University Libraries, 1968 Columbia in Crisis, The Gymnasium",
          url: "https://exhibitions.library.columbia.edu/exhibits/show/1968/causes/gym",
        },
        {
          label: "Columbia University Archives, The New Columbia Gymnasium (1967), the foldout cross-section, Buildings and Grounds Collection, box 8, folder 11",
          url: "https://exhibitions.library.columbia.edu/exhibits/show/1968/item/5520",
        },
        {
          label: "Columbia University Archives, Stop Columbia's Gym Crow (1968), the organizers' circular",
          url: "https://exhibitions.library.columbia.edu/exhibits/show/1968/item/5519",
        },
        {
          label: "Steve Ditlea, photograph of the construction-fence protest, April 23, 1968, Columbia University Libraries exhibition",
          url: "https://exhibitions.library.columbia.edu/exhibits/show/1968/item/5654",
        },
        {
          label: "Press Statement of Black Students in Hamilton Hall, April 1968, Columbia University Archives",
          url: "https://exhibitions.library.columbia.edu/exhibits/show/1968/item/5536",
        },
        {
          label: "Columbia University Libraries, 1968 Columbia in Crisis, the Students' Afro-American Society",
          url: "https://exhibitions.library.columbia.edu/exhibits/show/1968/protests/sas",
        },
        {
          label: "Stefan M. Bradley, Harlem vs. Columbia University, Black Student Power in the Late 1960s (University of Illinois Press, 2009)",
          url: "https://books.google.com/books?id=lHd25eE8Z1UC&printsec=frontcover",
        },
        {
          label: "Schomburg Center, Christiane C. Collins papers relating to the West Harlem Coalition for Morningside Park, finding aid",
          url: "https://archives.nypl.org/scm/20875",
        },
      ],
    },
    {
      id: "gardens-grant",
      number: 3,
      title: "New housing on different terms",
      dek: "Morningside Gardens and Grant Houses offered new homes. The redevelopment also forced existing residents to leave",
      mapLabel: "Gardens & Grant",
      lat: 40.81261,
      lng: -73.957001,
      audioSrc: `${MEDIA}/audio/gardens-grant.mp3`,
      audioSeconds: 250,
      lookFor: "Public sidewalk at the southwest corner of Amsterdam Avenue and La Salle Street, on the Morningside Gardens side. Gardens is west of Amsterdam; General Grant Houses is across and to the northeast. Keep residential entrances clear.",
      transcript: [
        "Stand at the southwest corner of Amsterdam Avenue and La Salle Street. **Morningside Gardens is the group of towers west of Amsterdam, beside you. General Grant Houses is across the avenue, to the northeast.** The towers were built in the 1950s under different housing programs. Gardens was built as a middle-income cooperative. Grant was built by the New York City Housing Authority as public housing. Officials planned the projects together, expecting them to improve housing and stabilize the neighborhood around Columbia.",
        "**Morningside Heights, Inc., formed in 1947, brought the educational and religious institutions into the redevelopment effort.** Columbia, Riverside Church and their neighbors wanted to protect their campuses and attract residents they believed would support the area's future.",
        "The planning had a direct connection to Hyde Park in Chicago. **In 1946, Wilbur Munnecke, a vice president of the University of Chicago, advised the leaders here.** He rejected racial restrictive covenants, the deed clauses that prevented property from being sold or rented to excluded racial groups. Instead, he recommended publicly assisted rebuilding that would attract the residents the institutions wanted. That proposal removed explicit racial exclusion from the method. **It still gave the institutions a way to influence who could live nearby. Replace the existing housing with apartments offered on new financial terms.**",
        "**The clearance area already housed Black, Puerto Rican, white, Japanese and Chinese residents.** A photograph in the city's 1951 redevelopment brochure looked across the rooftops of these blocks. The view helped officials present them as a clearance site, and it said much less about the people inside the buildings. A 1953 report in the National Guardian followed the Save Our Homes Committee, which organized against displacement. Elizabeth Barker was one of its leaders. The newspaper described an early gathering at a Japanese restaurant on Broadway, where residents pooled money and prepared a petition asking what would happen to them when their homes were demolished. **Organizing began among people who needed an answer to that immediate question.**",
        "The Guardian supported the tenants' campaign. A week later, a resident named Margaret F. Lamont challenged its account as one-sided. Her letter stressed the need for the proposed low-rent public housing. The disagreement was about how to secure better homes, as well as whether demolition should go ahead.",
        "**Morningside Gardens admitted its first residents in 1957.** Its six towers provided nearly a thousand homes, and Black and white families lived there together. The cooperative offered an important opportunity for integrated housing. The cost of entering it limited that opportunity. The historian Hilary Ballon records a purchase payment of $750 per room and a monthly charge of $21 per room. **A four-room apartment on those terms required $3,000 up front and $84 a month, in the dollars of the day.** A family who could not raise the purchase payment could not obtain an apartment simply because the development welcomed people of its race.",
        "Management also tried to control the racial balance. The historian Samuel Zipp describes efforts to recruit white and Asian applicants and to keep Black occupancy near a preferred level of 20 percent. Managers feared that more Black residents would discourage white applicants. **Integration was being managed partly around white families' willingness to move in.**",
        "One Gardens resident was Antonia Pantoja, a Black Puerto Rican educator who lived at 70 La Salle Street from the late 1950s until early 1969. **She held meetings of the Puerto Rican Association for Community Affairs in her living room and became the first director of ASPIRA**, which supports Puerto Rican young people through education and leadership programs. She also taught at Columbia's School of Social Work.",
      ],
      images: [
        {
          src: `${MEDIA}/gardens-grant-1955-bromley.jpg`,
          alt: "A colored land-book plate showing the blocks between Broadway, Amsterdam Avenue, La Salle Street and West 123rd Street, with the long pink outlines of the Morningside Gardens towers labeled MORNINGSIDE GARDENS, the angled towers of GEN. GRANT HOUSES (Section 1) above La Salle Street, and the small lots of the older streets between Broadway and Riverside Drive at the left",
          credit:
            "The two developments drawn side by side while they were still being built. G. W. Bromley and Company, Manhattan Land Book of the City of New York, 1955, plate 138. New York Public Library, via Wikimedia Commons. Public domain.",
          label: "1955",
          after: 1,
        },
        {
          src: `${MEDIA}/gardens-grant-1978-haer.jpg`,
          alt: "A black and white photograph along the elevated platform of the 125th Street subway station, with the tracks running away toward the tall towers of Grant Houses beyond",
          credit:
            "Grant Houses from the 125th Street station platform. Historic American Engineering Record survey of the Interborough Rapid Transit subway, HAER NY,31-NEYO,86-30, Library of Congress. Public domain.",
          label: "After 1968",
          after: 5,
        },
        {
          src: `${MEDIA}/gardens-grant-from-125th-station.jpg`,
          alt: "The red brick towers of General Grant Houses rising above trees, seen from the elevated platform of the 125th Street station",
          credit:
            "General Grant Houses from the 125th Street station. Photograph by Kidfly182, May 2022, via Wikimedia Commons. CC BY-SA 4.0.",
          label: "Grant Houses",
          after: 6,
        },
      ],
      nowImage: {
        src: `${MEDIA}/gardens-grant-today.jpg`,
        alt: "Two tall red brick towers of General Grant Houses against a grey sky, with trees at their base",
        credit:
          "General Grant Houses today. Photograph by Kidfly182, May 2022, via Wikimedia Commons. CC BY-SA 4.0.",
        label: "Today",
        after: 8,
      },
      interrupts: [
        {
          title: "Two housing programs",
          body: [
            "**Gardens residents bought shares in a cooperative and paid monthly charges. Grant Houses residents rented from NYCHA under public-housing eligibility rules.** Federal Title I assistance helped acquire and clear the cooperative's site; it did not make every displaced household eligible for, or able to afford, a new apartment. Building public housing nearby did not guarantee that the people removed from either site would be rehoused there.",
            "The cooperative terms differ by source and date. **Hilary Ballon records $750 per room down and $21 a month per room; the National Guardian reported a 1953 proposal reduced to $625 and $21.** The four-room example in the narration is arithmetic from Ballon's figures, not an identified family's bill.",
          ],
          after: 6,
        },
      ],
      toNext: {
        text: "Walk south on Amsterdam Avenue to West 123rd Street. Turn right to Broadway, then left to West 122nd Street. Turn right to Claremont Avenue and left toward West 120th Street. Stop outside Riverside Church near its Claremont Avenue entrance.",
        distanceMeters: 794,
        minutes: 11,
      },
      sources: [
        {
          label: "Samuel Zipp, Manhattan Projects, The Rise and Fall of Urban Renewal in Cold War New York (Oxford University Press, 2010), pages 166 to 169 and 204 to 208, and notes 18 to 21 on page 405 for the Munnecke reports",
          url: "https://books.google.com/books?vid=ISBN9780195328745",
        },
        {
          label: "Hilary Ballon, Robert Moses and Urban Renewal, The Title I Program, in Ballon and Kenneth T. Jackson, editors, Robert Moses and the Modern City (W. W. Norton, 2007), pages 94 to 115, the cooperative charges at page 115, note 56",
          url: "https://bpb-us-e1.wpmucdn.com/wp.nyu.edu/dist/f/5822/files/2017/01/BookScanCenter-4.pdf",
        },
        {
          label: "Themis Chronopoulos, Spatial Regulation in New York City, From Urban Renewal to Zero Tolerance (Routledge, 2011), chapter 1",
          url: "https://api.pageplace.de/preview/DT0400.9781136740688_A23879466/preview-9781136740688_A23879466.pdf",
        },
        {
          label: "Themis Chronopoulos, Robert Moses and the Visual Dimension of Physical Disorder, Journal of Planning History 13, no. 3 (2014), the 1951 clearance brochure photograph at figure 11",
          url: "https://cronfa.swan.ac.uk/Record/cronfa30504/Download/0030504-26012017225425.pdf",
        },
        {
          label: "Elmer Bendiner, The Manhattanville Story, National Guardian, New York edition, June 1, 1953, page 1",
          url: "https://www.marxists.org/history/usa/pubs/national-guardian/1953-06-01-5-32-nat-guardian.pdf",
        },
        {
          label: "Margaret F. Lamont, letter, The Manhattanville story, National Guardian, June 8, 1953, page 3",
          url: "https://www.marxists.org/history/usa/pubs/national-guardian/1953-06-08-5-33-nat-guardian.pdf",
        },
        {
          label: "Ronald Lawson, editor, The Tenant Movement in New York City, 1904 to 1984 (Rutgers University Press, 1986), the Save Our Homes chronology at pages 156 to 160",
          url: "https://libcom.org/book/export/html/45862",
        },
        {
          label: "Morningside Gardens, History, construction in 1954, first occupancy in 1957, completion in 1958",
          url: "https://www.morningsidegardens.com/history",
        },
        {
          label: "Wallach Art Gallery and Temple Hoyne Buell Center, Living in America, Frank Lloyd Wright, Harlem and Modern Housing (Columbia University, 2017), Morningside Gardens and General Grant Houses",
          url: "https://buellcenter.columbia.edu/sites/default/files/2023-02/Living%20In%20America%20Full%20Pamphlet.pdf",
        },
        {
          label: "Andrés Santana-Miranda, Antonia Pantoja Residence, NYC LGBTQ Historic Sites Project (July 2024)",
          url: "https://www.nyclgbtsites.org/site/antonia-pantoja-residence/",
        },
        {
          label: "Columbia Rare Book and Manuscript Library, Morningside Area Alliance records, finding aid",
          url: "https://findingaids.library.columbia.edu/pdf/cul-4412857.pdf",
        },
      ],
    },
    {
      id: "riverside-church",
      number: 4,
      title: "Riverside Church and racial justice",
      dek: "Martin Luther King Jr. spoke here against the Vietnam War. James Forman later demanded reparations from religious institutions",
      mapLabel: "Riverside Church",
      lat: 40.8113,
      lng: -73.962944,
      audioSrc: `${MEDIA}/audio/riverside-church.mp3`,
      audioSeconds: 192,
      lookFor: "Public sidewalk outside Riverside Church, 81 Claremont Avenue, near West 120th Street. The account works outside; entering the church is optional.",
      transcript: [
        "You are outside Riverside Church at 81 Claremont Avenue, near 120th Street. The tower above you is the tallest thing in Morningside Heights. **Riverside Church opened in 1930, with John D. Rockefeller Jr. as its principal financial supporter and Harry Emerson Fosdick as its founding pastor.** Its founders envisioned a congregation open across denominations, races and nationalities. The tower made the church a prominent part of the neighborhood.",
        "Riverside also joined the institutions involved in neighborhood redevelopment. **Its commitment to interracial fellowship existed alongside decisions about land and housing that affected who could remain nearby.**",
        "**On April 4, 1967, Martin Luther King Jr. delivered the speech called Beyond Vietnam here.** Clergy and Laymen Concerned About Vietnam, an interfaith antiwar organization, arranged the gathering. King used the church to make a public argument about the connection between the war abroad and racial inequality at home. He argued that military spending was undermining efforts to relieve poverty. He described Black and white young men fighting together abroad while being denied equal schools and neighborhoods at home. He also asked listeners to consider the Vietnamese people's experiences and wishes.",
        "For King, a civil rights movement concerned with housing, wages and poverty had to confront the government decisions that shaped those conditions. **His criticism of the war drew condemnation from major newspapers and some civil rights allies.** Speaking here was a deliberate expansion of the public argument he was making about racial justice.",
        "Two years later, James Forman brought a demand for economic change directly to the church. This time, Riverside was being asked to pay. **On May 4, 1969, Forman interrupted Sunday worship to present the Black Manifesto.** Adopted at the National Black Economic Development Conference in Detroit the week before, it demanded $500 million in reparations from white churches and Jewish synagogues across the country. Riverside was one institution being addressed by a national campaign.",
        "The manifesto proposed institutions controlled by Black people, including a land bank, publishing enterprises and a university. It argued that religious institutions had benefited from Black exploitation and owed money to support Black economic independence. Its program also endorsed confrontation and the possible use of force.",
        "**At Riverside, the organ played over Forman, and the minister led worshippers out.** The church subsequently refused to pay Forman or the Black Economic Development Conference. It created its own Fund for Social Justice, with a goal of raising $450,000 over three years, and kept authority over its grants. Forman had demanded that Black-led institutions control the funds. **That disagreement remained even after Riverside established its program.**",
      ],
      images: [
        {
          src: `${MEDIA}/riverside-church-1930-underhill.jpg`,
          alt: "A black and white photograph of the newly completed Riverside Church, its tall Gothic tower rising above the nave, seen from the street with apartment buildings alongside",
          credit:
            "Riverside Church the year it opened. Photograph by Irving Underhill, 1930. Library of Congress, Prints and Photographs Division. No known restrictions on publication.",
          label: "1930",
          after: 1,
        },
        {
          src: `${MEDIA}/riverside-church-1952-rizzuto.jpg`,
          alt: "A black and white view over rooftops toward the tower of Riverside Church, with Grant's Tomb beyond it and the Hudson River and the Palisades in the distance",
          credit:
            "The tower over Morningside Heights, photographed by Angelo Rizzuto in 1952. Anthony Angel Collection, Library of Congress. No known restrictions on publication.",
          label: "1952",
          after: 2,
        },
        {
          src: `${MEDIA}/riverside-church-1964-king.jpg`,
          alt: "Martin Luther King Jr. speaking with his right hand raised, in a dark suit and tie, beside a lectern with a microphone",
          credit:
            "Martin Luther King Jr. in New York in 1964, three years before he spoke here. Photograph by Dick DeMarsico for the New York World-Telegram and Sun, Library of Congress. No known restrictions on publication.",
          label: "1964",
          after: 3,
        },
      ],
      nowImage: {
        src: `${MEDIA}/riverside-church-today.jpg`,
        alt: "The stone tower of Riverside Church rising against a blue sky, lit by low sun, with the church's Gothic windows and buttresses below",
        credit:
          "Riverside Church today. Photograph by PortableNYCTours, July 2019, via Wikimedia Commons. CC BY-SA 4.0.",
        label: "Today",
        after: 7,
      },
      interrupts: [
        {
          title: "The demand and the church's response",
          body: [
            "**The Black Manifesto's $500 million was a national reparations demand. Riverside's $450,000 was a fundraising goal for its own program.** It was not a payment of that amount to Forman, and the goal alone does not establish how much the church ultimately raised. The church's own account reports $357,242.72 raised when the third year's recipients were announced.",
          ],
          after: 7,
        },
      ],
      toNext: {
        text: "Walk north on Claremont Avenue to West 122nd Street, then right to Broadway. Turn left and continue north, descending toward the elevated subway at West 125th Street. Continue to West 129th Street and stop beside the Jerome L. Greene Science Center at 3227 Broadway.",
        distanceMeters: 860,
        minutes: 12,
      },
      sources: [
        {
          label: "Matthew A. Postal, The Riverside Church Designation Report, LP-2037, NYC Landmarks Preservation Commission (May 16, 2000)",
          url: "https://s-media.nyc.gov/agencies/lpc/lp/2037.pdf",
        },
        {
          label: "Martin Luther King, Jr. Research and Education Institute, Stanford University, Beyond Vietnam",
          url: "https://kinginstitute.stanford.edu/encyclopedia/beyond-vietnam",
        },
        {
          label: "Martin Luther King Jr., Beyond Vietnam, A Time to Break Silence, April 4, 1967, transcript hosted by Civil Rights Movement Veterans",
          url: "https://www.crmvet.org/docs/mlk-viet.htm",
        },
        {
          label: "King Institute, Clergy and Laymen Concerned About Vietnam (CALCAV)",
          url: "https://kinginstitute.stanford.edu/clergy-and-laymen-concerned-about-vietnam-calcav",
        },
        {
          label: "The Riverside Church, The Black Manifesto at The Riverside Church, the church's account and timeline",
          url: "https://www.trcnyc.org/blackmanifesto/",
        },
        {
          label: "James Forman, Black Manifesto, adopted by the National Black Economic Development Conference, April 26, 1969, scan hosted by Riverside Church",
          url: "https://www.trcnyc.org/wp-content/uploads/2019/04/Black-Manifesto1.pdf",
        },
      ],
    },
    {
      id: "manhattanville",
      number: 5,
      title: "Columbia expands into Manhattanville",
      dek: "A new campus replaced much of an industrial district. Residents and business owners proposed different futures for the area",
      mapLabel: "Manhattanville",
      lat: 40.816467,
      lng: -73.957992,
      audioSrc: `${MEDIA}/audio/manhattanville.mp3`,
      audioSeconds: 224,
      lookFor: "Public sidewalk at the northwest corner of Broadway and West 129th Street, beside the Jerome L. Greene Science Center. Keep the corner and entrance clear.",
      transcript: [
        "You are at Broadway and 129th Street, beside the Jerome L. Greene Science Center. The subway runs overhead here because the land drops into the Manhattanville valley. **This corner was once a stable. Sheffield Farms kept the horses that pulled its milk wagons on this site**, and a photograph in the Municipal Archives shows the old stable building beneath the elevated railway. The neighborhood supplied the city with transport, storage and industrial work long before it housed this campus.",
        "**Sheffield's processing plant survives nearby as Prentis Hall, on West 125th Street.** Columbia bought it in 1949 and adapted it for university use. The stable site underwent a more complete change. Its older building was replaced by the science center.",
        "**Columbia's Manhattanville proposal called for a seventeen-acre campus** with research and academic buildings, public space and services. The university argued that it needed room to grow and that its expansion would bring jobs and investment. **Community Board 9 proposed another approach.** Its neighborhood plan sought to retain industrial businesses, protect affordable housing and support development without displacement. Its goals included preserving the area's economic and ethnic diversity. Residents were offering a plan for investment on different terms.",
        "**The state's ownership map from December 2008 shows Columbia's control of much of the project area**, alongside city, Con Edison and other property. The site still contained homes and businesses. That version of the project plan anticipated relocating 298 occupants of about 135 dwelling units. These were planning figures, rather than a final count of people who moved.",
        "Some commercial property owners refused to sell. Parminder Kaur, Amanjit Kaur, P.G. Singh Enterprises and the Tuck-It-Away storage companies were among those who challenged the state's acquisition of their property for the university. **In 2010, New York's highest court upheld the state's authority**, reversing a lower-court decision. A public development agency could use eminent domain for the project even though Columbia, a private institution, would occupy the campus.",
        "Negotiations also produced a signed community benefits agreement in 2009. **It committed Columbia to a $76 million benefits fund, $20 million for affordable housing and up to $4 million for housing-related legal assistance.** Those amounts state the agreement's obligations. They do not, by themselves, show what every household received.",
        "For Hilda Muentes and Luisa Henriquez, relocation intersected with a much older effort to own their homes. They lived in a West 132nd Street building the city had taken through foreclosure in 1978. Its residents had spent decades seeking ownership as a low-income cooperative. In February 2016, the Wall Street Journal followed the neighbors as they prepared to move to a replacement building Columbia had constructed at Broadway and 148th Street. Muentes, an eighty-year-old retired garment sample maker, visited her new apartment and photographed the kitchen window. **Columbia later reported that nineteen families from the West 132nd Street building moved in December 2016 and became cooperative shareholders in April 2018.** Their ownership goal had finally been realized in a different building, farther uptown.",
      ],
      images: [
        {
          src: `${MEDIA}/manhattanville-1906-viaduct.jpg`,
          alt: "A sepia photograph from a 1906 view book showing the great steel arch of the Riverside Drive viaduct spanning the Manhattanville valley, with the elevated subway structure beyond it and low buildings beneath",
          credit:
            "The Riverside Drive viaduct crossing the Manhattanville valley, from Scenes of Modern New York (L. H. Nelson Company, 1906). Seymour B. Durst Old York Library, Columbia University, via the Internet Archive and Wikimedia Commons. No known restrictions.",
          label: "1906",
          after: 1,
        },
        {
          src: `${MEDIA}/manhattanville-1937-abbott.jpg`,
          alt: "A black and white photograph beneath the Riverside Drive viaduct at 125th Street and 12th Avenue, its steel structure overhead, with a storage tank at the right, parked cars, pedestrians and the signs of meat wholesalers and other businesses below",
          credit:
            "Under the Riverside Drive viaduct at 125th Street and 12th Avenue, in the working district the campus later replaced. Photograph by Berenice Abbott, November 10, 1937, for Changing New York. New York Public Library, via Wikimedia Commons. Public domain.",
          label: "1937",
          after: 1,
        },
        {
          src: `${MEDIA}/manhattanville-sheffield-plant-2008.jpg`,
          alt: "A white terra cotta industrial building on West 125th Street with tall arched windows, the former Sheffield Farms milk plant, now Prentis Hall, with a red brick building beside it",
          credit:
            "The former Sheffield Farms plant on West 125th Street, now Columbia's Prentis Hall. Photograph by Paul Lowry, April 2008, via Wikimedia Commons. CC BY 2.0.",
          label: "Prentis Hall",
          after: 2,
        },
        {
          src: `${MEDIA}/manhattanville-2018-construction.jpg`,
          alt: "The Manhattanville campus under construction, seen from the viaduct, with cranes, excavations and new glass buildings rising among older brick blocks and the elevated subway",
          credit:
            "The campus under construction, seen from the Riverside Drive viaduct. Photograph by Jim.henderson, April 2018, via Wikimedia Commons. CC BY-SA 4.0.",
          label: "2018",
          after: 4,
        },
      ],
      nowImage: {
        src: `${MEDIA}/manhattanville-today.jpg`,
        alt: "The Jerome L. Greene Science Center, a long glass building with a grid of pale mullions, at the corner of Broadway with the elevated subway structure beside it",
        credit:
          "The Jerome L. Greene Science Center on the stable's site today. Photograph by ajay_suresh, June 2021, via Wikimedia Commons. CC BY 2.0.",
        label: "Today",
        after: 7,
      },
      interrupts: [
        {
          title: "Eminent domain",
          body: [
            "**Eminent domain allows government to acquire private property for a legally recognized public use, with compensation.** In this case, the state development agency exercised the power; Columbia benefited from it. The 2010 decision upheld that legal authority. It did not decide whether the project was the best plan for everyone living and working in West Harlem.",
            "Keep the seventeen-acre campus distinct from the roughly thirty-five-acre rezoning around it, and the 298 occupants in about 135 units as the December 2008 planning baseline. **The litigants' properties were a gas station and storage businesses, not owner-occupied family homes.**",
          ],
          after: 5,
        },
      ],
      toNext: {
        text: "Walk south on Broadway to West 125th Street. Turn right and follow West 125th Street, which becomes St. Clair Place, west toward the Hudson. Use the marked pedestrian crossings at 12th Avenue and Marginal Street to enter West Harlem Piers Park. Stop beside the walking path, clear of bicycle traffic. Follow posted pedestrian diversions if the crossings change.",
        distanceMeters: 620,
        minutes: 8,
      },
      sources: [
        {
          label: "Columbia University Libraries and Facilities, Sheffield Farms exhibition, Chapter 3, Manhattanville Transforms",
          url: "https://sheffieldfarms.neighbors.columbia.edu/content/chapter-3-manhattanville-transforms",
        },
        {
          label: "Manhattan Community Board 9, 197-a Plan, Hamilton Heights, Manhattanville, Morningside Heights (adopted with modifications, 2007)",
          url: "https://www.nyc.gov/assets/planning/download/pdf/community/197a-plans/mn9_hamilton_manhattanville_197a.pdf",
        },
        {
          label: "New York State Urban Development Corporation, Manhattanville in West Harlem, Modified General Project Plan (December 18, 2008), relocation at pages 27 to 33 and the ownership map at Exhibit B",
          url: "https://esd.ny.gov/sites/default/files/media/document/2008-12-18-CUMV-Modified%20General-Project-Plan-with-Exhibits.pdf",
        },
        {
          label: "Matter of Kaur v. New York State Urban Development Corp., 15 NY3d 235, New York Court of Appeals (June 24, 2010)",
          url: "https://www.nycourts.gov/reporter/3dseries/2010/2010_05601.htm",
        },
        {
          label: "West Harlem Community Benefits Agreement, West Harlem Local Development Corporation and the Trustees of Columbia University (May 18, 2009), the funding provisions at pages 8 to 11",
          url: "https://climate.law.columbia.edu/sites/default/files/content/CBAs/West%20Harlem%20-%20Columbia%20CBA.pdf",
        },
        {
          label: "Columbia Neighbors, Community Commitments, the university's description of the 2009 agreement and the 2011 declaration",
          url: "https://neighbors.columbia.edu/content/community-commitments",
        },
        {
          label: "Columbia University, Manhattanville Implementation Plan Report, Residential Relocation Obligations (October 15, 2025), including the 2016 newspaper report and the April 2018 announcement",
          url: "https://neighbors.columbia.edu/sites/neighbors.columbia.edu/files/content/Reporting/2025%20ESD%20Reporting/2025%20-%205.05%28b%29%28i%29%20Residential%20Relocation%20Obligations.pdf",
        },
        {
          label: "Josh Barbanel, A Long Journey to Ownership Nears Its Goal, The Wall Street Journal, February 17, 2016",
          url: "https://www.wsj.com/articles/a-long-journey-to-ownership-nears-its-goal-1455755210",
        },
      ],
    },
    {
      id: "west-harlem-piers",
      number: 6,
      title: "Residents plan the waterfront",
      dek: "West Harlem organizers helped turn a neglected stretch of the Hudson into a public park",
      mapLabel: "Harlem Piers",
      lat: 40.818198,
      lng: -73.961796,
      audioSrc: `${MEDIA}/audio/west-harlem-piers.mp3`,
      audioSeconds: 171,
      lookFor: "West Harlem Piers Park, near the entrance at West 125th Street, St. Clair Place and Marginal Street. Choose a place beside the walking path, away from bicycle traffic.",
      transcript: [
        "You are in West Harlem Piers Park, near the entrance from 125th Street. **The park opened on May 30, 2009.** A former waterfront parking lot had become a two-acre park with walking and bicycle paths, planted space, and separate docking and fishing piers.",
        "**WE ACT for Environmental Justice and Community Board 9 helped bring that change about.** WE ACT linked access to the Hudson with a wider local problem. Black and Latino neighborhoods had borne pollution and received too little investment in places for recreation. The organization wanted residents involved in deciding what would be built here. Its planning booklet shows participants gathered around a map, working through practical choices about open space, movement along the river and connections to the streets where people lived.",
        "**In 1998, the city sought commercial proposals for the waterfront site. It received plans for a thirty-three-story hotel and a six-story motel.** According to WE ACT's account, neighborhood organizing helped persuade the city to select neither proposal. WE ACT and Community Board 9 instead developed a plan called Harlem-on-the-River through public meetings and a design workshop. The community plan proposed open space, waterfront activities and a continuous pedestrian and bicycle route. In 2001, the city funded a master-planning process that drew on the neighborhood's work. The completed park required city, state and federal support, along with funding from other public bodies.",
        "The connections reached across this walk. **The planning booklet credits Sarah Martin of the Grant Houses Tenants Association and Joan Levine of the Morningside Gardens Residents Association**, as well as participants from Riverside Church and Columbia. Residents of the two developments you stood between at the third stop helped shape a place their neighbors could use together.",
        "WE ACT's account of the opening includes a ribbon-cutting, children making paddles, and a performance by Dance Theatre of Harlem. **The park's art also drew on residents' experiences.** Nari Ward based the sculptures called Voice on the eyelets that guide fishing line along a rod. For the accompanying Signage Barriers, he gathered words from neighbors' memories of the area. The city installed those works as part of the park project.",
        "The tour ends here. To reach the 1 train, return east along 125th Street to Broadway, about a third of a mile. **Each stop on this walk marked a decision about land made by an institution, and a response from the people who lived beside it.** Thank you for walking with us.",
      ],
      images: [
        {
          src: `${MEDIA}/west-harlem-piers-1926-aerial.jpg`,
          alt: "A black and white aerial photograph of the Manhattanville waterfront in 1926, with the 125th Street ferry landing on the Hudson, the viaduct, the elevated railway and the dense blocks of the valley, and the campus and Grant's Tomb on the ridge above",
          credit:
            "The 125th Street ferry landing and the Manhattanville waterfront from the air in 1926, when the site of this park was a working shore. Via Wikimedia Commons. Public domain, published before 1931.",
          label: "1926",
          after: 1,
        },
        {
          src: `${MEDIA}/west-harlem-piers-1937-abbott.jpg`,
          alt: "A black and white photograph looking along 125th Street beneath the steel arches of the Riverside Drive viaduct toward the river, with trucks, storefronts and a gas station below the structure",
          credit:
            "The way to the river under the viaduct at 12th Avenue, on the path you have just walked. Photograph by Berenice Abbott, November 10, 1937, for Changing New York. New York Public Library, via Wikimedia Commons. Public domain.",
          label: "1937",
          after: 3,
        },
        {
          src: `${MEDIA}/west-harlem-piers-2021.jpg`,
          alt: "Cherry trees in pink bloom beside the walking path in West Harlem Piers Park, with a cyclist on the path, the lawn, and the Hudson River and the Palisades beyond",
          credit:
            "The park in spring. Photograph by Jim.henderson, April 2021, via Wikimedia Commons. CC BY 4.0.",
          label: "2021",
          after: 5,
        },
        {
          src: `${MEDIA}/west-harlem-piers-125th-station-2018.jpg`,
          alt: "The elevated platform of the 125th Street subway station, with its green 125 Street sign, a lamp, the tracks curving away and the red brick towers of Grant Houses in the distance",
          credit:
            "The 125th Street station on the 1 train, the way home. Photograph by Carol M. Highsmith, 2018, Carol M. Highsmith Archive, Library of Congress. No known restrictions on publication.",
          label: "The 1 train",
          after: 6,
        },
      ],
      nowImage: {
        src: `${MEDIA}/west-harlem-piers-today.jpg`,
        alt: "West Harlem Piers Park on a sunny day, with a lawn, lamp standards, the walking path, a low building and the piers reaching into the Hudson",
        credit:
          "West Harlem Piers Park, looking north. Photograph by Jim.henderson, October 2008, via Wikimedia Commons. Public domain.",
        label: "Today",
        after: 2,
      },
      interrupts: [
        {
          title: "Environmental justice at the waterfront",
          body: [
            "**WE ACT's campaign connected recreation, neighborhood health and participation in public decisions.** Its planning booklet is an account written by the organizers. Read it alongside the city's opening announcement. The first explains residents' aims and campaign; the second documents the facilities and public funding announced when the park opened. The 2004 concept plan, the later approved plan and the 2009 park are different objects, and not every feature proposed in the booklet was built.",
          ],
          after: 3,
        },
      ],
      sources: [
        {
          label: "Peggy M. Shepard, Christopher Greaves and Cecil Corbin-Mark, editors, Harlem-on-the-River, Making a Community Vision Real (WE ACT, 2004)",
          url: "https://d3n8a8pro7vhmx.cloudfront.net/weact/pages/480/attachments/original/1436983693/Harlem_on_the_River-Making_a_Community_Vision_Real.pdf?1436983693",
        },
        {
          label: "WE ACT for Environmental Justice, River Currents (May 2009), the opening celebration",
          url: "https://d3n8a8pro7vhmx.cloudfront.net/weact/pages/480/attachments/original/1436983767/River_Currents_Newsletter_May_2009_Vol_1.pdf?1436983767",
        },
        {
          label: "WE ACT for Environmental Justice, West Harlem Piers Park Project, 1998 organizing through the May 30, 2009 opening",
          url: "https://community.weact.org/west-harlem-waterfront-park",
        },
        {
          label: "City of New York, Office of the Mayor, release 244-09, Mayor Bloomberg Joins West Harlem Community to Celebrate Opening of West Harlem Piers Park (May 30, 2009), the park at opening and Nari Ward's works",
          url: "https://www.nyc.gov/html/dcla/downloads/pdf/244-09_West_Harlem_Piers_Park.pdf",
        },
        {
          label: "Riverside Park Conservancy, Riverside Park History, the West Harlem waterfront",
          url: "https://riversideparknyc.org/riverside-park-history/",
        },
      ],
    },
  ],
};
