import type { Metadata } from "next";
import PageTransition from "@/components/layout/PageTransition";

export const metadata: Metadata = {
  title: "Privacy Policy | Rooted Forward",
  description:
    "The Rooted Forward privacy policy for rooted-forward.org and the Walk Hyde Park mobile application. What we collect, how we use and disclose it, how long we keep it, and your rights.",
};

/* ------------------------------------------------------------------
   Privacy policy for rooted-forward.org and the Walk Hyde Park iOS
   app. Structured on the ordinary corporate template (dated header,
   linked contents, numbered sections and subsections, CCPA category
   table, jurisdiction blocks, formal contact) so it reads like the
   policy a reader has seen on every other site.

   The App Store listing links here, and Apple's guideline 5.1.1 wants
   this page to state the data collected, how it is collected, every
   use, the parties it is disclosed to, retention, and how a user
   withdraws consent and deletes an account. Keep every claim true of
   what the site and the app actually do.
   ------------------------------------------------------------------ */

const LAST_UPDATED = "July 26, 2026";

type Clause = {
  heading?: string;
  paragraphs?: string[];
  bullets?: string[];
  /** Definition-style rows, used for the processor and retention lists. */
  defs?: { term: string; text: string }[];
};

type Section = { id: string; title: string; clauses: Clause[] };

const SECTIONS: Section[] = [
  {
    id: "scope",
    title: "Scope of This Policy",
    clauses: [
      {
        paragraphs: [
          "This Privacy Policy applies to the Rooted Forward website at rooted-forward.org and to the Walk Hyde Park application for iPhone and iPad, which we refer to together as the Services.",
          "It does not apply to any third-party website, application or service that we link to. Those are governed by their own policies, and we describe them further in Section 10.",
          "By using the Services you agree to this Privacy Policy. If you do not agree with it, please do not use the Services.",
        ],
      },
    ],
  },
  {
    id: "collect",
    title: "Information We Collect",
    clauses: [
      {
        heading: "2.1 Information You Provide to Us",
        paragraphs: [
          "You can read every page of the website, including the full text of the walking tour and the research archive, without an account and without providing any information about yourself. We collect the following only when you choose to give it.",
        ],
        defs: [
          {
            term: "Account information",
            text: "Your name, your email address and a password, provided when you register an account on the website. Passwords are hashed by our authentication provider and are never stored or visible to us in readable form.",
          },
          {
            term: "Google account information",
            text: "If you register using Google, Google provides us with your name and email address in order to create the account. We receive nothing else from Google.",
          },
          {
            term: "Content you submit",
            text: "Comments, policy campaign signatures, proposal submissions and any other material you post through the website, together with the account that posted it.",
          },
          {
            term: "Correspondence",
            text: "Your email address and the contents of your message when you write to us. The website has no contact form, so this reaches us only as ordinary email.",
          },
        ],
      },
      {
        heading: "2.2 Information We Collect Automatically",
        defs: [
          {
            term: "Authentication cookie",
            text: "A single cookie that keeps you signed in as you move between pages. It is set only while you are signed in, and it is the only cookie the website places on your device. We use no advertising, analytics or third-party cookies.",
          },
          {
            term: "Server log data",
            text: "Our hosting provider records ordinary web server logs, including your IP address, the pages requested, the date and time, and your browser type. These are generated by the act of serving a web page and are used to operate the site and to prevent abuse.",
          },
          {
            term: "Research archive activity",
            text: "When you download a file from the research archive we record which file was requested, when, and by which account. We use this to understand how the archive is used and to detect scraping.",
          },
        ],
      },
      {
        heading: "2.3 Information Collected Through the Mobile Application",
        paragraphs: [
          "Almost none, and none of it identifies you. The application asks for no name, no email address and no account, and it records nothing about how you use the walk.",
          "The entire tour, including every stop, photograph and audio file, is contained in the application when you install it, so it operates offline. The application contains no account system, no sign-in screen, no registration, no crash-reporting library and no advertising identifier.",
          "There is one exception, and it exists because we advertise the application. The application includes Google Analytics for Firebase, which is there so we can tell whether an advertisement led to somebody installing it. When the application is first opened it sends Google a record that an install happened, along with the model of phone, the operating system version, the country and a random identifier generated for that installation. We have defined no events of our own, so which stops you open, how far you walk, what you listen to and how long you stay are not measured and are not sent. The advertising identifier is not collected. That software is not in the application, which is why the application never asks for permission to track you, and the random installation identifier is erased when you delete the application.",
          "Two categories of information exist while you use the application, and both remain on your device. Neither is transmitted to us or to any other party.",
        ],
        defs: [
          {
            term: "Tour progress",
            text: "Which stops you have completed and where you stopped, stored locally so that the walk resumes where you left it. Removing the application removes it.",
          },
          {
            term: "Device location",
            text: "If you grant permission, your location is used on the device to display your position on the tour map and to indicate when you are near a stop. It is processed entirely on the device and is never transmitted. Section 7.4 describes the permission and how to withdraw it.",
          },
        ],
      },
      {
        heading: "2.4 Information We Do Not Collect",
        paragraphs: [
          "We do not collect payment information, government identifiers, biometric information, health information, precise location on our servers, or any special category of personal data. We do not purchase personal information from data brokers.",
        ],
      },
    ],
  },
  {
    id: "use",
    title: "How We Use Information",
    clauses: [
      {
        paragraphs: [
          "Because the application collects nothing, this section concerns the website only. We use the information described in Section 2 for the following purposes.",
        ],
        bullets: [
          "To create your account, authenticate you, and keep you signed in.",
          "To display your comments, submissions and campaign signatures where you posted them, attributed to your account.",
          "To respond to your correspondence and to provide support.",
          "To understand which research datasets are used and to prevent bulk scraping of the archive.",
          "To operate, maintain and secure the Services, and to detect and prevent fraud, abuse and technical problems.",
          "To comply with applicable law and to enforce our terms.",
        ],
      },
      {
        paragraphs: [
          "We do not use your information for advertising, we do not build advertising or behavioral profiles, and we do not use anything you provide to train machine learning models, whether our own or a third party's.",
        ],
      },
    ],
  },
  {
    id: "disclose",
    title: "How We Disclose Information",
    clauses: [
      {
        heading: "4.1 Service Providers",
        paragraphs: [
          "We disclose information to a small number of service providers that process it on our behalf, on our instructions, and under contractual confidentiality and security obligations. They are not permitted to use it for their own purposes.",
        ],
        defs: [
          {
            term: "Supabase",
            text: "Database and authentication provider. Holds accounts, authentication records, comments, campaign signatures, submissions and research download records.",
          },
          {
            term: "Vercel",
            text: "Hosting provider for the website. Generates and retains the server logs described in Section 2.2.",
          },
          {
            term: "Google",
            text: "Identity provider, and only if you choose to register or sign in using Google. Google provides your name and email address to us for that purpose.",
          },
          {
            term: "Apple",
            text: "Distributes the application through the App Store and provides us with anonymous, aggregate download statistics through its own dashboard. Apple does not identify you to us, and the application transmits nothing to Apple on our behalf.",
          },
        ],
      },
      {
        heading: "4.2 Legal and Safety Disclosures",
        paragraphs: [
          "We may disclose information if we are required to do so by law, subpoena or other legal process, or where we believe in good faith that disclosure is necessary to protect the rights, property or safety of Rooted Forward, our users or the public. Where we are legally permitted to notify you of such a request, we will.",
        ],
      },
      {
        heading: "4.3 Business Transfers",
        paragraphs: [
          "Rooted Forward is a nonprofit and is not for sale. If it were ever to merge with or transfer its programs to another organization, we would notify you before any personal information became subject to a different privacy policy, and you would have the opportunity to delete your account first.",
        ],
      },
      {
        heading: "4.4 No Sale or Sharing of Personal Information",
        paragraphs: [
          "We do not sell personal information, we do not rent or trade it, and we do not share it for cross-context behavioral advertising, as those terms are defined under the California Consumer Privacy Act. We have never done so.",
        ],
      },
    ],
  },
  {
    id: "retention",
    title: "Data Retention",
    clauses: [
      {
        paragraphs: [
          "We retain personal information only for as long as it serves the purposes described in Section 3, after which it is deleted.",
        ],
        defs: [
          {
            term: "Account information",
            text: "Retained until you delete your account. Deletion is described in Section 7.2.",
          },
          {
            term: "Content you submit",
            text: "Retained until you delete it or delete your account, which removes it.",
          },
          {
            term: "Research archive activity",
            text: "Retained for two years, then deleted.",
          },
          {
            term: "Server log data",
            text: "Retained by our hosting provider for approximately thirty days.",
          },
          {
            term: "Application data",
            text: "Never held by us at all. Tour progress and location remain on your device and are removed when you remove the application.",
          },
        ],
      },
    ],
  },
  {
    id: "security",
    title: "How We Secure Information",
    clauses: [
      {
        paragraphs: [
          "All traffic to and from the Services is encrypted in transit using HTTPS. Passwords are hashed by our authentication provider using industry-standard algorithms and are never stored or seen by us in readable form. Access to the production database is limited to the individuals who administer the organization. The application stores no credentials of any kind.",
          "No method of transmission or storage is completely secure, and we do not claim otherwise. In the event of a data breach affecting your personal information, we will notify you and the appropriate authorities as required by applicable law.",
        ],
      },
    ],
  },
  {
    id: "rights",
    title: "Your Privacy Rights and Choices",
    clauses: [
      {
        heading: "7.1 Rights Available to You",
        paragraphs: [
          "Depending on where you live, you may have some or all of the rights below under applicable law. As a matter of policy we extend all of them to every user regardless of location.",
        ],
        bullets: [
          "The right to know what personal information we hold about you and how we use and disclose it.",
          "The right to access a copy of that information in a portable format.",
          "The right to correct information that is inaccurate.",
          "The right to delete your personal information.",
          "The right to withdraw consent you previously gave, at any time.",
          "The right to opt out of the sale or sharing of personal information, which we note we do not do.",
          "The right not to receive discriminatory treatment for exercising any of these rights.",
        ],
      },
      {
        heading: "7.2 Exercising Your Rights",
        paragraphs: [
          "To exercise any right above, email contact@rooted-forward.org from the address associated with your account. We will respond within thirty days and we do not charge a fee. We may ask you to confirm your identity before acting on a request, in order to protect your account. An authorized agent may submit a request on your behalf with written proof of authorization.",
          "To delete your account, email contact@rooted-forward.org from the address on the account. Deletion is permanent and takes effect within seven days. It removes your profile, your authentication record, your comments, your submissions and your campaign signatures. It cannot be reversed, and we are unable to restore an account once it has been deleted.",
          "The application has no account and no sign-in, so there is nothing in it to delete. Removing the application from your device removes everything it held.",
        ],
      },
      {
        heading: "7.3 Cookies",
        paragraphs: [
          "The only cookie we set is the authentication cookie described in Section 2.2. Because it is strictly necessary to keep you signed in, there is no consent banner and nothing to opt out of. If you sign out or clear your browser's cookies, it is removed. We use no advertising, analytics or third-party cookies, so there is no cross-site tracking to disable.",
        ],
      },
      {
        heading: "7.4 Location Permission in the Application",
        paragraphs: [
          "The application requests location access once, when you tap Find me on the tour map, and it requests access only while the application is in use. It never requests background location. If you decline, every part of the tour continues to work.",
          "You may withdraw the permission at any time by opening the iOS Settings application and selecting Privacy and Security, then Location Services, then Walk Hyde Park. Because your location is processed on your device and is never transmitted, withdrawing permission leaves nothing behind on our side to delete.",
        ],
      },
    ],
  },
  {
    id: "children",
    title: "Children's Privacy",
    clauses: [
      {
        paragraphs: [
          "The Services are intended for a general audience, including students, and the walking tour is written to be used by secondary school classes. We do not knowingly collect personal information from children under 13 years of age. No account is required to read, listen to or walk any part of the Services, so a child may use all of it without providing anything to us.",
          "If you believe that a child under 13 has provided us with personal information, please email contact@rooted-forward.org and we will delete it promptly.",
        ],
      },
    ],
  },
  {
    id: "international",
    title: "International Users and Data Transfers",
    clauses: [
      {
        paragraphs: [
          "Rooted Forward is based in Chicago, Illinois, in the United States, and our service providers store data in the United States. If you access the Services from outside the United States, your information is transferred to and processed in the United States, where data protection law may differ from that of your country.",
          "Where we transfer personal data from the European Economic Area or the United Kingdom, we rely on the European Commission's Standard Contractual Clauses as incorporated into our agreements with our service providers.",
        ],
      },
    ],
  },
  {
    id: "third-party",
    title: "Third-Party Links and Services",
    clauses: [
      {
        paragraphs: [
          "The Services link to external websites, including archives, libraries, newspapers and the sources cited on every tour stop. We do not control those sites and this Privacy Policy does not apply to them. We encourage you to read the privacy policy of any site you visit.",
          "Tapping Directions in the application opens your device's own maps application. What that application does with the request is governed by its own privacy policy and by your device settings.",
        ],
      },
    ],
  },
  {
    id: "jurisdiction",
    title: "Jurisdiction-Specific Disclosures",
    clauses: [
      {
        heading: "11.1 California Residents",
        paragraphs: [
          "Under the California Consumer Privacy Act, as amended, California residents are entitled to the disclosures in this section and to the rights listed in Section 7. In the twelve months preceding the date of this policy, we collected the categories of personal information marked below. We disclosed the marked categories to the service providers listed in Section 4.1 for the business purposes described in Section 3. We sold no personal information and shared none for cross-context behavioral advertising.",
        ],
      },
      {
        heading: "11.2 EEA and United Kingdom Residents",
        paragraphs: [
          "Rooted Forward is the controller of the personal data described in this policy. We rely on the following legal bases under the General Data Protection Regulation and the UK GDPR.",
        ],
        defs: [
          {
            term: "Consent",
            text: "Creating an account, posting content, and granting location permission. You may withdraw consent at any time, as described in Section 7.",
          },
          {
            term: "Legitimate interests",
            text: "Operating and securing the Services, preventing abuse of the research archive, and responding to correspondence. We have assessed that these interests are not overridden by your rights.",
          },
          {
            term: "Legal obligation",
            text: "Retaining or disclosing information where the law requires it.",
          },
        ],
      },
      {
        paragraphs: [
          "You have the right to lodge a complaint with your local supervisory authority. In the United Kingdom this is the Information Commissioner's Office. We would appreciate the chance to address your concern first, at contact@rooted-forward.org.",
        ],
      },
    ],
  },
  {
    id: "changes",
    title: "Changes to This Policy",
    clauses: [
      {
        paragraphs: [
          "We may update this Privacy Policy from time to time. When we do, we will revise the date at the top of this page. If a change materially affects what we collect or how we use it, we will state that plainly at the top of this page rather than rely on you to notice the new date.",
          "Your continued use of the Services after a revision takes effect constitutes acceptance of the revised policy.",
        ],
      },
    ],
  },
  {
    id: "contact",
    title: "Contact Us",
    clauses: [
      {
        paragraphs: [
          "If you have questions about this Privacy Policy, wish to exercise a right described in Section 7, or believe we hold information about you that should be corrected or removed, please contact us. A person reads every message.",
        ],
      },
    ],
  },
];

/** The standard CCPA category list, answered honestly for this site. */
const CCPA_ROWS: { cat: string; examples: string; collected: string }[] = [
  {
    cat: "A. Identifiers",
    examples: "Real name, email address, IP address, account identifier",
    collected: "Yes, website only",
  },
  {
    cat: "B. Categories in Cal. Civ. Code 1798.80(e)",
    examples: "Name and email address",
    collected: "Yes, website only",
  },
  {
    cat: "C. Protected classification characteristics",
    examples: "Race, age, sex, national origin, disability",
    collected: "No",
  },
  {
    cat: "D. Commercial information",
    examples: "Records of products or services purchased",
    collected: "No",
  },
  {
    cat: "E. Biometric information",
    examples: "Fingerprints, faceprints, voiceprints",
    collected: "No",
  },
  {
    cat: "F. Internet or other network activity",
    examples: "Pages requested, research files downloaded, server logs",
    collected: "Yes, website only",
  },
  {
    cat: "G. Geolocation data",
    examples: "Physical location or movements",
    collected: "No. Processed on your device and never transmitted",
  },
  {
    cat: "H. Sensory data",
    examples: "Audio, electronic, visual or similar information",
    collected: "No",
  },
  {
    cat: "I. Professional or employment information",
    examples: "Job history, performance evaluations",
    collected: "No",
  },
  {
    cat: "J. Non-public education information",
    examples: "Student records under FERPA",
    collected: "No",
  },
  {
    cat: "K. Inferences drawn from other personal information",
    examples: "Profiles reflecting preferences or behavior",
    collected: "No",
  },
];

function Paragraphs({ items }: { items: string[] }) {
  return (
    <>
      {items.map((p, i) => (
        <p
          key={i}
          className="mt-4 font-body text-[15px] leading-[1.75] text-ink/80"
        >
          {p}
        </p>
      ))}
    </>
  );
}

function Defs({ items }: { items: { term: string; text: string }[] }) {
  return (
    <dl className="mt-4 space-y-3.5">
      {items.map((d) => (
        <div key={d.term}>
          <dt className="font-body text-[15px] font-semibold text-ink">
            {d.term}
          </dt>
          <dd className="mt-1 font-body text-[15px] leading-[1.75] text-ink/75">
            {d.text}
          </dd>
        </div>
      ))}
    </dl>
  );
}

function CcpaTable() {
  return (
    <div className="mt-5 overflow-x-auto">
      <table className="w-full min-w-[36rem] border-collapse border border-border text-left">
        <thead>
          <tr className="bg-cream-dark/60">
            {["Category", "Examples", "Collected"].map((h) => (
              <th
                key={h}
                scope="col"
                className="border border-border px-3 py-2.5 font-body text-[11px] font-semibold uppercase tracking-[0.15em] text-forest"
              >
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {CCPA_ROWS.map((r) => (
            <tr key={r.cat} className="align-top">
              <th
                scope="row"
                className="border border-border px-3 py-2.5 font-body text-[13.5px] font-semibold leading-snug text-ink"
              >
                {r.cat}
              </th>
              <td className="border border-border px-3 py-2.5 font-body text-[13.5px] leading-snug text-ink/75">
                {r.examples}
              </td>
              <td className="border border-border px-3 py-2.5 font-body text-[13.5px] leading-snug text-ink/75">
                {r.collected}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default function PrivacyPage() {
  return (
    <PageTransition>
      <div className="bg-cream pb-20 pt-16 md:pt-24">
        <div className="mx-auto max-w-3xl px-6">
          {/* Header */}
          <h1 className="font-display text-4xl font-semibold leading-[1.03] tracking-tight text-forest md:text-6xl">
            Privacy Policy
          </h1>
          <p className="mt-3 font-body text-sm text-warm-gray">
            Last updated {LAST_UPDATED}
          </p>

          <div className="mt-8 border-t border-border pt-8">
            <Paragraphs
              items={[
                "Rooted Forward (“Rooted Forward,” “we,” “us” or “our”) is a nonprofit organization in Chicago, Illinois. We operate the website at rooted-forward.org and the Walk Hyde Park application for iPhone and iPad. This Privacy Policy describes the personal information we collect, how we use and disclose it, how long we retain it, and the rights and choices available to you.",
              ]}
            />
            <p className="mt-4 font-body text-[15px] font-semibold leading-[1.75] text-forest">
              The Walk Hyde Park application has no account and no sign-in,
              and it records nothing about how you use the walk. It does
              report to Google that an install happened, so we can tell
              whether an advertisement worked, and Section 2.3 sets out
              exactly what that report contains. The provisions below
              concerning accounts, stored records and disclosure apply to
              the website only.
            </p>
          </div>

          {/* Contents */}
          <nav
            aria-label="Contents"
            className="mt-10 border border-border bg-cream-dark/30 px-6 py-5"
          >
            <h2 className="font-body text-[11px] font-semibold uppercase tracking-[0.2em] text-warm-gray">
              Contents
            </h2>
            <ol className="mt-3 space-y-1.5">
              {SECTIONS.map((s, i) => (
                <li key={s.id} className="flex gap-2.5">
                  <span className="font-body text-[14px] tabular-nums text-warm-gray">
                    {i + 1}.
                  </span>
                  <a
                    href={`#${s.id}`}
                    className="font-body text-[14px] text-forest underline decoration-border underline-offset-4 transition-colors hover:decoration-forest"
                  >
                    {s.title}
                  </a>
                </li>
              ))}
            </ol>
          </nav>

          {/* Body */}
          <div className="mt-12 space-y-11">
            {SECTIONS.map((section, i) => (
              <section
                key={section.id}
                id={section.id}
                className="scroll-mt-28"
              >
                <h2 className="font-display text-2xl leading-snug text-forest">
                  {i + 1}. {section.title}
                </h2>

                {section.clauses.map((clause, j) => (
                  <div key={j} className={clause.heading ? "mt-6" : ""}>
                    {clause.heading && (
                      <h3 className="font-body text-[15px] font-semibold text-ink">
                        {clause.heading}
                      </h3>
                    )}
                    {clause.paragraphs && (
                      <Paragraphs items={clause.paragraphs} />
                    )}
                    {clause.bullets && (
                      <ul className="mt-4 list-disc space-y-2 pl-5 marker:text-rust">
                        {clause.bullets.map((b) => (
                          <li
                            key={b}
                            className="font-body text-[15px] leading-[1.75] text-ink/80"
                          >
                            {b}
                          </li>
                        ))}
                      </ul>
                    )}
                    {clause.defs && <Defs items={clause.defs} />}
                    {section.id === "jurisdiction" &&
                      clause.heading?.startsWith("11.1") && <CcpaTable />}
                  </div>
                ))}

                {section.id === "contact" && (
                  <address className="mt-5 border border-border bg-cream-dark/30 px-6 py-5 not-italic">
                    <p className="font-body text-[15px] font-semibold text-ink">
                      Rooted Forward
                    </p>
                    <p className="mt-1 font-body text-[15px] leading-[1.75] text-ink/75">
                      Chicago, Illinois, United States
                    </p>
                    <p className="mt-1 font-body text-[15px] leading-[1.75]">
                      <a
                        href="mailto:contact@rooted-forward.org"
                        className="text-forest underline decoration-border underline-offset-4 transition-colors hover:decoration-forest"
                      >
                        contact@rooted-forward.org
                      </a>
                    </p>
                  </address>
                )}
              </section>
            ))}
          </div>

          <p className="mt-14 border-t border-border pt-6 font-body text-sm text-warm-gray">
            This Privacy Policy is effective as of {LAST_UPDATED} and supersedes
            all prior versions.
          </p>
        </div>
      </div>
    </PageTransition>
  );
}
